### ISSUE TITLE
Is tamagui ready for production?

### ISSUE THREAD

**Issue by tecsobs** [tamagui/tamagui#1003]
Hi in the search of a great ui framework for react native i have found this great library. 

I wonder if it is ready for production seeing a lot of bugfixes released almost every day.

Also how old are the benchmarks made? Because some of the caching of the library has been modified or removed.

Thanks and great work

**Comment by natew** [comment]
Thank you!

The one cache that was removed didn't make a diff in performance, I tested it. The main performance benefit is the optimizing compiler and smart use of themes.

Tamagui is in use by a bunch of companies in production, we have 12 corporate sponsors. Two big companies are now onboarding, one valued at over a billion dollars.

We are focusing on correctness now, if you find a bug I think we will have it fixed within short order. We've been steadily adding tests to cover all features.
