### ISSUE TITLE
Nested stacks skip the 3th theme change cycle

### ISSUE THREAD

**Issue by DaLukasTI** [tamagui/tamagui#1008]
### Current Behavior

When applying a background color to a nested Stack component (Stack, XStack, YStack) it skips the 3th theme change cycle. This only applies to stacks nested inputs, buttons etc change their color respectively. Only the stacks skip their 3th theme cycle. 

### Expected Behavior

The stack should also change it's background color and not skip the 3th cycle.
This only happens to the Stack components and not to inputs buttons etc.
 This only happens when stacks get nested. If I pull them apart and render them at the top wrapped with `<></>` the issue dissapears.

### Tamagui Version

```markdown
"tamagui": "^1.15.32"
```

### Reproduction

```markdown
- create fresh tamagui app with  `npm create tamagui`
- head over to features/home/screen.tsx
- apply a bg color to the 2nd stack(the one with `maw={600}`  ) eg `bg={'$pink5'}`
- switch from dark to light and light to dark
- theme switching should work but will lagg one cycle behind on the stack components
```

### System Info

```markdown
System:
    OS: Linux 6.2 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 14.88 GB / 31.28 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.20.13 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.32.0 
    prettier: ^2.7.1 => 2.8.3 
    turbo: ^1.8.3 => 1.8.3 
    typescript: ^4.7.4 => 4.9.4
```

**Comment by natew** [comment]
I think we discussed this in Discord but just for context here the option in createTamagui “maxDarkLightNesting” controls this for web. But I think you also said Android emulator had trouble with it, but not the actual device?

**Comment by DaLukasTI** [comment]
Yes that's correct. This issue is only happening in my android emulator. Running on a native device there is no such behaviour. Thanks for your quick response, I'll close this issue.
