### ISSUE TITLE
tamagui Button component onClick not working for mobile

### ISSUE THREAD

**Issue by kyunghoon** [tamagui/tamagui#101]
**Describe the bug**
Recently updated tamagui from 1.0.1-beta.21 to 1.0.1-beta.66.
Button component `onClick` no longer seems to fire on mobile. works fine on web. upon debugging i found `onTouchStart`, which seems to work for mobile but does not for web.

**To Reproduce**
create a  Button component, implement onClick property, and click it in the simulator

**Environment (please complete the following information):**
mac ios simulator

**Comment by seeden** [comment]
use onPress instead of onClick

**Comment by kyunghoon** [comment]
thanks for the help. i had already tried `onPress`.

problem went away when i updated tamagui from beta.66 to beta.67.

closing
