### ISSUE TITLE
Burnt and Toasts on native dont work with the starter monorepo

### ISSUE THREAD

**Issue by chrisciszak** [tamagui/tamagui#1022]
### Current Behavior

After closing SheetDemo the following errors occur on iOS in Expo Go. Web working fine and the toast shows after closing the SheetDemo

![IMG_9720](https://user-images.githubusercontent.com/11364221/234069673-652e7e1c-1c23-4207-9a9a-b8ab58038ac7.PNG)
![IMG_9719](https://user-images.githubusercontent.com/11364221/234069676-cd91e168-5c87-499c-b0e3-686c11a298a9.PNG)

### Expected Behavior

Should be able to close the SheetDemo and see the toast.

### Tamagui Version

```markdown
1.15.34
```

### Reproduction

```markdown
run npm create tamagui and yarn native inside the project folder
```

**Comment by nandorojo** [comment]
Burnt doesn't work with Expo Go. Could check this with Expo constants.

**Comment by alitnk** [comment]
This is misleading/unexpected because the CLI advises the user to run `yarn native` after starter's created. We should probably update the message there.

To get a development build you can do: 
```bash
cd apps/expo
yarn ios # or yarn android
```
and toast should work just fine after that.

**Comment by chrisciszak** [comment]
that's exactly what the problem was - thanks guys

**Comment by benschac** [comment]
If I want to run the application on my phone, what should I do? Would be helpful to note in the readme.

**Comment by alitnk** [comment]
> If I want to run the application on my phone, what should I do? Would be helpful to note in the readme.

@benschac 
Not really in the scope of what Tamagui does. https://docs.expo.dev/workflow/run-on-device/ - Where on readme do you think having this would be helpful?

**Comment by benschac** [comment]
In `create-tamagui`. Coming into the project with a fresh install it's a bit of a goose chase figuring out why your app is failing in expo go.

Also, on the beta docs. https://tamagui.dev/docs/components/toast/1.15.15
