### ISSUE TITLE
ReferenceError: Cannot access 'parentManager' before initialization

### ISSUE THREAD

**Issue by lobor** [tamagui/tamagui#1031]
### Current Behavior

I use docusaurus and i'am base on starter of tamagui, i have error `ReferenceError: Cannot access 'parentManager' before initialization` when i use with theme-live-codeblock

(all step based on root project path)
in `apps/doc/docs/Components/Input.mdx` i try to load button in live code, provider is load here `apps/doc/src/theme/Root.tsx`, context of liveblock here `apps/doc/src/theme/ReactLiveScope/index.tsx` and the tamagui-plugin here `apps/doc/docusaurus.config.js`

I try to put in live block  tamagui provider directly, but same error, I haved check version mismatch, i have any idea when can be source of this error

### Tamagui Version

```markdown
1.15.37
```

### Reproduction

```markdown
clone https://github.com/lobor/tamagui-react-hook-form
checkout to the branch bug-docusaurus
`yarn install`
`yarn workspaces foreach --include '{@my/ui,@my/demo,tamagui-react-hook-form}' -pi run build`
`yarn doc`
Go to `http://localhost:3000/tamagui-react-hook-form/docs/Components/Input`
`ReferenceError: Cannot access 'parentManager' before initialization`
```

**Comment by natew** [comment]
that branch doesn't exist for me

**Comment by lobor** [comment]
do you test on repo ?

**Comment by lobor** [comment]
Hi, i updated repo, you can get error in live to this url https://lobor.github.io/tamagui-react-hook-form/bug/
and the file in repo https://github.com/lobor/tamagui-react-hook-form/blob/main/apps/doc/src/pages/bug.tsx

**Comment by lobor** [comment]
I migrate to nextra from docusaurus, resolve probleme

**Comment by lobor** [comment]
sorry, i can't wait your bug fix
