### ISSUE TITLE
Cannot use `@tamagui/animations-reanimated` with starter

### ISSUE THREAD

**Issue by thecoorum** [tamagui/tamagui#1036]
### Current Behavior

While trying to use `@tamagui/animations-reanimated` with starter, I'm facing the issue when web app fails with error that it needs an appropriate loader (see screenshot)

## Media
![image](https://user-images.githubusercontent.com/32096016/234492113-941a99ed-438c-4673-86e7-4ee85cf9f0f3.png)

### Expected Behavior

Being able to replace `@tamagui/animations-react-native` with `@tamagui/animations-reanimated` and use them

### Tamagui Version

```markdown
1.16.3
```

### Reproduction

```markdown
- Use tamagui starter with `npm create tamagui@latest`
- Install `react-native-reanimated` into `apps/expo` with `npx expo install react-native-reanimated`
- Uncomment `react-native-reanimated/plugin` in `babel.config.js`
- Install `@tamagui/animations-reanimated` into `packages/app` and run `yarn` in project root
- Run `yarn web`
```

### System Info

```markdown
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 135.69 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - ~/.asdf/installs/nodejs/19.4.0/bin/node
    Yarn: 3.5.0 - ~/.asdf/shims/yarn
    npm: 9.2.0 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 110.0.1
    Safari: 16.3
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.37.0 
    prettier: ^2.7.1 => 2.8.7 
    turbo: ^1.8.3 => 1.8.8 
    typescript: ^4.7.4 => 4.9.5
```

**Comment by natew** [comment]
Can you try the new `@tamagui/animations-moti` it uses reanimated under the hood and was just implemented by fernando, we may replace it soon.

**Comment by thecoorum** [comment]
@natew thanks for super quick reply! Should it be also installed into `packages/app`? Also, should I install it into `packages/ui` 'cause I can see that `@tamagui/animations-react-native` is listed in `package.json` there?

**Comment by thecoorum** [comment]
@natew are there any extra steps that need to be taken in account during installation? While trying to install `@tamagui/animations-moti` and `moti` into `packages/app` and `packages/ui` web app still complains about missing loader to handle reanimated

**Comment by thecoorum** [comment]
One more thing, seems like `@tamagui/animations-moti` is breaking animation for bottom sheet and tooltip

**Comment by natew** [comment]
Summoning @nandorojo

**Comment by nandorojo** [comment]
that original screenshot indicates that reanimated isn't in transpile packages in your next config. also be sure to use v3 to avoid the need for the babel plug-in

**Comment by nandorojo** [comment]
Re: the tooltip stuff, I can take a look. I couldn't get sandbox working on native so I didn't test those out. Might happen if we didn't pull in my worklet changes in the moti PR.

As for setting up moti...just install moti and the moti driver in packages/ui. then install reanimated 3 in apps/expo (v3+)

lastly, add reanimated / moti to transpile packages for next.js

i'm on my phone right now so let me know if any of this isn't clear

**Comment by thecoorum** [comment]
@nandorojo thanks for the clarification. I just didn't included reanimated to the transpile list in `next.config`. Now it's working!
