### ISSUE TITLE
[Bug] CreateFont configuration

### ISSUE THREAD

**Issue by antoine-waag** [tamagui/tamagui#1042]
### Current Behavior

I've got some warnings when I tried to add some custom font sizes and use it on some components like `Heading` or `SizableText`.

To solve this warning, I have to add the `fontFamily` props on Heading. It seems the default props `fontFamily` is equal at $8 by default like the size. 
However, I've no solution for `SizableText`.

I've also some other related issues like : 
- On props `fontWeight`, if I use a number like 600 it works, but I've an typing error. If it's a string instead of a number, there is no error.
- If I use the `Text` component, I have to set the `fontFamily` props, the $body is not taken by default

Maybe all of that issues are caused by my config. 

<img width="388" alt="image" src="https://user-images.githubusercontent.com/14271745/234780743-5eb2d8e5-5a86-4ca8-9c2e-c180d1e1d9f0.png">

### Expected Behavior

I would like to use custom sizes for my fonts, and if possible do not use numbered keys, like it should be possible regarding the documentation : _Note, you don't need to use numbered keys, you can use sm or tiny or whatever you'd like. But you do want keep those keys consistent._

If I do something wrong my config, tell me how to figure out what I'am looking for please 🙏  

### Tamagui Version

```markdown
1.16.4
```

### Reproduction

```markdown
const fontSizes = {
  '10xl': 84,
  '9xl': 80,
  '8xl': 76,
  '7xl': 72,
  '6xl': 60,
  '5xl': 48,
  '4xl': 36,
  '3xl': 30,
  '2xl': 22,
  'xxs': 10,
  'xs': 12,
  'sm': 14,
  'md': 16,
  'lg': 18,
  'xl': 20,
  'xxl': 24,
};

const lineHeight = {
  '10xl': 100,
  '9xl': 96,
  '8xl': 91,
  '7xl': 86,
  '6xl': 72,
  '5xl': 48,
  '4xl': 43,
  '3xl': 39,
  '2xl': 29,
  'xxs': 15,
  'xs': 18,
  'sm': 21,
  'md': 24,
  'lg': 27,
  'xl': 30,
  'xxl': 33,
}; 

const fontWeight = {
  '10xl': 600,
  '9xl': 600,
  '8xl': 600,
  '7xl': 600,
  '6xl': 600,
  '5xl': 600,
  '4xl': 600,
  '3xl': 600,
  '2xl': 600,
  'xxs': 400,
  'xs': 400,
  'sm': 400,
  'md': 400,
  'lg': 400,
  'xl': 400,
  'xxl': 400,
};
 
const letterSpacing = {};

export const EpilogueFont = createFont({
  family: 'Epilogue',
  size: fontSizes,
  lineHeight: lineHeight,
  weight: fontWeight,
  letterSpacing: letterSpacing,
});

export const IBMPlexSans = createFont({
  family: 'IBM Plex Sans',
  size: fontSizes, 
  lineHeight: lineHeight,
  weight: fontWeight,
  letterSpacing: letterSpacing,
});

const config = createTamagui({
  themes,
  tokens,
  shorthands,
  fonts: {
    heading: EpilogueFont,
    body: IBMPlexSans,
  },
});

export type AppConfig = typeof config;

declare module 'tamagui' {
  // overrides TamaguiCustomConfig so your custom types
  // work everywhere you import `tamagui`
  interface TamaguiCustomConfig extends AppConfig {}
}

export default config;

<Heading fontSize={'$2xl'}>My heading</Heading>
```

**Comment by natew** [comment]
This is documented, you can re-create your own heading very trivially this is the entire source of Headings.tsx:

```tsx
import { GetProps, styled } from '@tamagui/web'

import { Paragraph } from './Paragraph'

export const Heading = styled(Paragraph, {
  tag: 'span',
  name: 'Heading',
  accessibilityRole: 'header',
  fontFamily: '$heading',
  size: '$8',
  margin: 0,
})

export type HeadingProps = GetProps<typeof Heading>

export const H1 = styled(Heading, {
  name: 'H1',
  tag: 'h1',
  size: '$10',
})

export const H2 = styled(Heading, {
  name: 'H2',
  tag: 'h2',
  size: '$9',
})

export const H3 = styled(Heading, {
  name: 'H3',
  tag: 'h3',
  size: '$8',
})

export const H4 = styled(Heading, {
  name: 'H4',
  tag: 'h4',
  size: '$7',
})

export const H5 = styled(Heading, {
  name: 'H5',
  tag: 'h5',
  size: '$6',
})

export const H6 = styled(Heading, {
  name: 'H6',
  tag: 'h6',
  size: '$5',
})

```

Tamagui is opinionated. We're working on making this potentially customizable there's someone who started a PR thinking about it, but it's not a bug, it's documented.
