### ISSUE TITLE
[Bug] Typescript suggestion on VSCode

### ISSUE THREAD

**Issue by antoine-waag** [tamagui/tamagui#1046]
### Current Behavior

Suggestions on props `space` are not all corrects.

I have got : "$-number" instead of only "$number"

<img width="549" alt="image" src="https://user-images.githubusercontent.com/14271745/234810344-33cd8541-34c7-4ae9-8b66-0dbd1fe447d0.png">

### Expected Behavior

Get only the right values for the concerned props

### Tamagui Version

```markdown
1.16.4
```

### Reproduction

```markdown
const config = createTamagui({
  tokens,
  shorthands,
  themes
});

export type AppConfig = typeof config;

declare module 'tamagui' {
  // overrides TamaguiCustomConfig so your custom types
  // work everywhere you import `tamagui`
  interface TamaguiCustomConfig extends AppConfig {}
}

export default config;

<YStack space='$-12'>
```

**Comment by la55u** [comment]
they are correct I believe: https://tamagui.dev/docs/intro/tokens

also, there is `gap` now built in to RN that can be used instead of `space`

**Comment by antoine-waag** [comment]
Oh, my bad... i didn't notice that it was a negative value... Thanks for your answer 👍
