### ISSUE TITLE
popover content has unwanted style | bug

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#106]
In version 70 popover content has always height 44px ($4) and padding. Therefore it is not working correctly for vertical group items. 

Here is example: popover.content is div with red background:
<img width="225" alt="Screenshot 2022-06-20 at 15 33 45" src="https://user-images.githubusercontent.com/3958832/174625052-a74ba31b-056f-4d0d-94cb-d2f46dff3303.png">

Version: 70

Temp fix:
```jsx
<Popover.Content
        height="auto"
        paddingLeft="0"
        paddingRight="0"
```

**Comment by natew** [comment]
Should be fixed with https://github.com/tamagui/tamagui/pull/115/commits/138424a06aa7785bb87bc31abcf57da255c25c8b
