### ISSUE TITLE
styled(Input) and borderColor or borderWidth | bug

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#108]
When I try to override borderColor or borderWidth for styled(Input) it is not working.
The reason is that tamagui is using border-left-color instead of border-color. Probably it is mismatched somewhere in the code.

```ts
const StyledInput = styled(Input, {
  borderColor: 'transparent',
  borderWidth: '0px',
});
```

Version: 70

**Comment by natew** [comment]
Good catch, will be fixed in https://github.com/tamagui/tamagui/pull/115/commits/7172b1f5084441c6025495813247132873f7e672

**Comment by seeden** [comment]
Fixed, thanks
