### ISSUE TITLE
`<TextArea />` inside `<Dialog />` infinite loop bug

### ISSUE THREAD

**Issue by brunocrosier** [tamagui/tamagui#1104]
### Current Behavior

When the `value` and `onChangeText` props are set on a `<TextArea />` component inside a `<Dialog />` component, the component will rerender infinitely whenever `value` changes

Interestingly, if we do something like this, then it does work:

```tsx
import { useState } from 'react'
import { Dialog, TextArea } from 'tamagui'

export default function Bug() {
  const [text, setText] = useState('')
  return (
    <Dialog modal open>
      <Dialog.Portal>
        <Dialog.Overlay key="overlay" />

        <Dialog.Content bordered elevate key="content" space>
          <Dialog.Title>TextArea in Dialog bug</Dialog.Title>
          <Dialog.Description>Minimum reproduction</Dialog.Description>

          <TextArea
            // value={text} <-- if we do not tie `value` to the state, it works
            onChangeText={setText}
            placeholder="Try and type in here"
            numberOfLines={6}
            multiline
          />
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog>
  )
```

### Expected Behavior

Same as when `<TextArea />` is used outside of `<Dialog />` (i.e. you can set both `value` and `onChangeText` and it won't infinitely rerender)

### Tamagui Version

```markdown
1.22.3
```

### Reproduction

```markdown
copy and paste this code:



import { useState } from 'react'
import { Dialog, TextArea } from 'tamagui'

export default function Bug() {
  const [text, setText] = useState('')
  return (
    <Dialog modal open>
      <Dialog.Portal>
        <Dialog.Overlay key="overlay" />

        <Dialog.Content bordered elevate key="content" space>
          <Dialog.Title>TextArea in Dialog bug</Dialog.Title>
          <Dialog.Description>Minimum reproduction</Dialog.Description>

          <TextArea
            value={text}
            onChangeText={setText}
            placeholder="Try and type in here"
            numberOfLines={6}
            multiline
          />
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog>
  )
```

**Comment by natew** [comment]
Need info on which platform, then re-open

**Comment by brunocrosier** [comment]
platform is iOS (may also happen on other platforms but haven't been able to test)

**Comment by anckaertv** [comment]
I have exactly the same issue, platform is iOS.

**Comment by anckaertv** [comment]
I've tested this bug in two platforms:

1. iOS: could reproduce it with both <TextArea/> from tamagui + <TextInput/> from react-native with multiLine props.
2. Android: could not reproduce it with <TextArea/> from tamagui.
3. Web: did not test it since I am not targeting web. Sorry.

**Comment by anckaertv** [comment]
Could someone take a look at this issue?

**Comment by TheEhsanSarshar** [comment]
I'll check that on iOS, wasn't able to re-produce it on the web.
btw this pattern is not recommended in general

```jsx
const [text, setText] = useState('')
<Dialog>
    <Dialog.Content>
         <TextArea value={text} />
    <Dialog.Content>
</Dialog>
```
 as for every text change, it will make the whole dialog re-render, which is not good for performance.

instead, make your Dialog a separate component and pass content as props
```jsx
const MyDialog = ({children}) => {
   <Dialog>
      <Dialog.Content>
         {children}
      <Dialog.Content>
   </Dialog>
}

const MyComp = () => {
    return (
       <MyDialog>
            <MyForm />
       </MyDialog>
    )
}

const MyForm = () => {
        const [text, setText] = useState('')
        return <YStack>
             <TextArea value={text} />
             { ** rest of the components **}
        </Stack>
}
```

**Comment by TheEhsanSarshar** [comment]
This is an issue related to react-native textinput within portals in general
https://stackoverflow.com/questions/76935205/why-ios-multiline-textinput-not-works-correctly-in-react-native-paper-dialog

the best solution is the pattern that I posted
the other solution is to use `defaultValue` instead of `value` on iOS
