### ISSUE TITLE
colors are mismatched 

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#1106]
### Current Behavior

In the latest version, 1.22.11, colors are mismatched. Some colors are missing. It was working fine in version 1.22.7

### Expected Behavior

Tamagui should show the correct colors.

### Tamagui Version

```markdown
 1.22.11
```

### Reproduction

```markdown
I will add it when it is hard to reproduce
```

**Comment by natew** [comment]
What colors?

**Comment by seeden** [comment]
I moved back to 1.22.7 but problem is there as well. I am trying to use my previous version 1.17.0

**Comment by natew** [comment]
I need a repro or something it's very hard to tell, do you mean the `color1` => `color10` colors?

**Comment by seeden** [comment]
I removed everything, and the last working version for me is 1.22.7. I will stay with it until I release it.
I will try new versions in a few days. 
The problem with repro is that my project is huge and it is not that easy to create repro

**Comment by natew** [comment]
i reverted it to previous color set, there was a skip that moved 1 index, i verified its the same as previous now in latest releases (this was a few releases ago)

**Comment by seeden** [comment]
I tried the latest 1.29.4, and bug is still there moving back to 1.22.7
