### ISSUE TITLE
Typescript doesn't recognize the shorthands set in the tamagui.config

### ISSUE THREAD

**Issue by joseortiz9** [tamagui/tamagui#1119]
### Current Behavior

I configured tamagui in a project that was using native-base before, and the shorthands from `@tamagui/shorthands`, were added to the config following the documentation and the expo-next-template from `tamagui create`. The shorthands work as expected but typescript in my project cannot detect them and now I have ts error everywhere in my code :/
![](https://user-images.githubusercontent.com/26872450/234585130-014d645b-019e-489e-8520-a69f9d10feef.png)

I also tried to use the recommendation from @aawalton here https://github.com/tamagui/tamagui/issues/145#issuecomment-1368106211 but didn't work for me.

### Expected Behavior

Typescript should recognize the shorthands as available props for the component.

### Tamagui Version

```markdown
1.23.0
```

### Reproduction

```markdown
Here is an example of the project I'm having issues with, you can check `screens/InitialScreen.tsx` I put there some example code.
https://github.com/joseortiz9/storange-template-tamagui-rn
```

### System Info

```markdown
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 53.05 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
    Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 107.0.1
    Safari: 16.4
  npmPackages:
    expo: ^48.0.16 => 48.0.16
    react: 18.2.0 => 18.2.0 
    @tamagui/animations-react-native: ^1.23.0 => 1.23.0 
    @tamagui/babel-plugin: ^1.23.0 => 1.23.0 
    @tamagui/config: ^1.23.0 => 1.23.0 
    @tamagui/theme-base: ^1.23.0 => 1.23.0
    tamagui: ^1.23.0 => 1.23.0
```

**Comment by natew** [comment]
It does recognize them, this means you have something set up wrong. Usually a mismatched package version or just a clean and install is necessary.

**Comment by Seamus1989** [comment]
No same here. Followed installation and been through it twice now, all versions matching, code runs fine but shorthands throwing errors

**Comment by joseortiz9** [comment]
@Seamus1989 It could be related to tsconfig misconfiguration, check how it looks in the monorepo template from tamagui.

**Comment by Seamus1989** [comment]
@joseortiz9 I've tried all of this, any more specific ideas?

**Comment by joseortiz9** [comment]
@Seamus1989 noup :( I solved my issue by migrating the project to the monorepo template
