### ISSUE TITLE
Avatar Fallback issue

### ISSUE THREAD

**Issue by varand-pez** [tamagui/tamagui#1131]
### Current Behavior

When `src` is `null` or `undefined` for `Avatar.Image`, Android does not call Fallback properly.
Assigning "" empty string to `src` DOES call the Fallback but it in turns throw warning `source.uri should not be an empty string`
I'm using Android emulator API 33

### Expected Behavior

`null` or `undefined` image source should trigger Avatar.Fallback. There is no issue on iOS.

### Tamagui Version

```markdown
"tamagui": "1.23.0",
```

### Reproduction

```markdown
...
<Avatar.Image src={user?.userImage} />
      <Avatar.Fallback
        alignItems="center"
        justifyContent="center"
      >
        <Text
          fontSize={18}
          fontWeight="500"
        >
          U
        </Text>
      </Avatar.Fallback>
...
```
```


### System Info

_No response_

**Comment by hritikutekar** [comment]
Instead of setting the `src` prop to undefined or null, consider modifying the code like this:

```jsx
<Avatar circular>
  {user?.userImage ? <AvatarImage src={user.userImage} /> : null}
  <AvatarFallback alignItems="center" justifyContent="center">
    <Text fontSize={18} fontWeight="500">U</Text>
  </AvatarFallback>
</Avatar>

**Comment by alitnk** [comment]
Is this still an issue on the latest tamagui version? Should be a simple enough fix if there's still an issue.

**Comment by natew** [comment]
I can't repro on web or native, tested:

![CleanShot 2024-01-02 at 11 55 41@2x](https://github.com/tamagui/tamagui/assets/12100/61300670-9a2a-434b-9eaa-8c910e019a1d)

![CleanShot 2024-01-02 at 11 55 27@2x](https://github.com/tamagui/tamagui/assets/12100/723c33b9-cdb0-4a9c-8cd0-e768831cf35e)
