### ISSUE TITLE
Customizing Font Styling in Tamagui Components Using `tamagui.config.ts`

### ISSUE THREAD

**Issue by osejrafael** [tamagui/tamagui#1153]
I am attempting to customize the font styling of Tamagui's default components (such as `H1`, `Button`, etc.) in my React Native project. Specifically, I want to modify the font family and font weight for these components directly from my `tamagui.config.ts` file. However, [the existing documentation](https://tamagui.dev/docs/core/configuration#font-tokens) is somewhat unclear, and my attempts have not yielded the expected results. 
A suggestion would be to add a full working example on how to create a custom font and skip `//...` or point to a full object for reference. I would be happy help with this once I understand how this works.

To illustrate, consider the following scenarios:

1. **Customizing `H1` Component:** When I import the `H1` component from Tamagui, I want to apply a predefined font family and font weight on top of the default styling. I expect this to work by setting multiple `fonts` in the configuration file and then referencing the font name, like `fontFamily="$heading"`. However, this doesn't seem to apply the desired styles. Is explicitly defining `fontFamily` necessary, even for heading tags (`H`)? 

2. **Default Styling:** I would like to set default styles for certain components, such as `H1`. For instance, a plain `H1` (or any `H`) component, with no additional props and imported directly from Tamagui, should use my custom font and font weight for headings. This configuration should be achievable via the `tamagui.config.ts` file.

3. **Button Component:** Similarly, I'd like to ensure all `Button` (or any other) components have a specific font weight or styling by default based on my config file and imported directly from Tamagui. 
*Then for any other variants, I can create a `styled` component.*

Is it possible to accomplish these customizations solely using the `tamagui.config.ts` file? If not, could you please guide me on how to achieve this? 

For reference, here is my current configuration file (I've confirmed that the fonts are correctly imported via Expo and fully loaded before use):

```javascript
const tamaguiConfig = createTamagui({
  themes: {
    ...themes,
    brandLight,
    brandDark
  },
  tokens,
  animations,
  shorthands,
  defaultTheme: "light",
  themeClassNameOnRoot: false,
  shouldAddPrefersColorThemes: false,
  fonts: {
    heading: headingFont,
    body: bodyFont
  },
  media: createMedia({
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
    short: { maxHeight: 820 },
    tall: { minHeight: 820 },
    hoverNone: { hover: "none" },
    pointerCoarse: { pointer: "coarse" }
  })
});
```

This is how im currently creating fonts
```javascript
 createFont({
    family: "Manrope",
    lineHeight,
    weight: fontWeight,
    letterSpacing,
    size: sizes,
    face: {
      100: { normal: "Manrope-ExtraLight" },
      200: { normal: "Manrope-ExtraLight" },
      300: { normal: "Manrope-Regular" },
      400: { normal: "Manrope-Medium" },
      500: { normal: "Manrope-Medium" },
      600: { normal: "Manrope-SemiBold" },
      700: { normal: "Manrope-Bold" },
      800: { normal: "Manrope-ExtraBold" },
      900: { normal: "Manrope-ExtraBold" }
    },
    ...overrides
  })
```
Any guidance or clarification would be greatly appreciated.

**Comment by tylerrrkd** [comment]
hi friend, and how do you fix this problem? appreciated.

**Comment by tylerrrkd** [comment]
> I did not, but this is more of a question/discussion rather than an issue. That's why I closed it.
> 
> Ended up just creating my own version of each component using `styled`

@osejrafael I was confused, I config my theme by `tamagui.config.ts` in `packages/ui` which create by starter monorepo template. and it does not work.

**Comment by tylerrrkd** [comment]
```typescript
import { createTamagui, createTheme, createTokens } from 'tamagui'
import { createInterFont } from '@tamagui/font-inter'
import { shorthands } from '@tamagui/shorthands'
import { themes as defaultThemes, tokens as defaultTokens } from '@tamagui/themes'
import { createMedia } from '@tamagui/react-native-media-driver'

import { animations } from './animations'

// modified start
const tokens = createTokens({
  ...defaultTokens,
  color: {
    ...defaultTokens.color,
    primary: '#F78F21',
  },
})

const themes = {
  light: createTheme({
    ...defaultThemes.light,
    primary: tokens.color.primary,
  }),
  dark: createTheme({
    ...defaultThemes.dark,
    primary: tokens.color.primary,
  }),
}
// modified end

const headingFont = createInterFont({
  size: {
    6: 15,
  },
  transform: {
    6: 'uppercase',
    7: 'none',
  },
  weight: {
    6: '400',
    7: '700',
  },
  color: {
    6: '$colorFocus',
    7: '$color',
  },
  letterSpacing: {
    5: 2,
    6: 1,
    7: 0,
    8: -1,
    9: -2,
    10: -3,
    12: -4,
    14: -5,
    15: -6,
  },
  face: {
    700: { normal: 'InterBold' },
  },
})

const bodyFont = createInterFont(
  {
    face: {
      700: { normal: 'InterBold' },
    },
  },
  {
    sizeSize: (size) => Math.round(size * 1.1),
    sizeLineHeight: (size) => Math.round(size * 1.1 + (size > 20 ? 10 : 10)),
  }
)

export const config = createTamagui({
  animations,
  shouldAddPrefersColorThemes: true,
  themeClassNameOnRoot: true,
  shorthands,
  fonts: {
    heading: headingFont,
    body: bodyFont,
  },
  themes,
  tokens,
  media: createMedia({
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
    short: { maxHeight: 820 },
    tall: { minHeight: 820 },
    hoverNone: { hover: 'none' },
    pointerCoarse: { pointer: 'coarse' },
  }),
})

```
