### ISSUE TITLE
[Bug/Error] Image doesn't work with animation prop

### ISSUE THREAD

**Issue by mdj-goathamster** [tamagui/tamagui#1155]
### Current Behavior

Animation doesn't work on `<Image/>`
I've tried all 3 animation drivers with different props like (opacity,scale,y,x..)
 
Error when trying to animate opacity:
ERROR  Warning: Failed prop type: Invalid prop `opacity` of type `object` supplied to `Image`, expected `number`.
Bad object: {
  "width": 100,
  "height": 100,
  "zIndex": 1,
  "position": "relative",
  "opacity": 0,
  "transform": []
}
ERROR  Error: You attempted to set the key `_tracking` with the value `null` on an object that is meant to be immutable and has been frozen.

### Expected Behavior

Image should animate

### Tamagui Version

```markdown
1.27.3
```

### Reproduction

```markdown
1. fork tamagui/starters/next-expo-solito
1. add <Image/> component with animation props

Example code:
`import { Image } from '@my/ui'
import img from 'app/assets/images/emote-cheerful.png'
<Image
      source={img}
      width={100}
      height={100}
      opacity={1}
      enterStyle={{ opacity: 0 }}
      animation="lazy"
    />`
```

### System Info

```markdown
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 5.93 GB / 15.84 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.5.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.6.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.5
    @manypkg/cli: ^0.19.1 => 0.19.2
    check-dependency-version-consistency: ^3.0.3 => 3.1.1
    eslint: ^8.21.0 => 8.40.0
    node-gyp: ^9.3.1 => 9.3.1
    prettier: ^2.7.1 => 2.8.8
    turbo: ^1.8.3 => 1.9.4
    typescript: ^4.7.4 => 4.9.5
```

**Comment by TheEhsanSarshar** [comment]
oh I see, thanks for reporting

**Comment by TheEhsanSarshar** [comment]
for now, you can wrap your `Image` with a `Stack` and then animate that `Stack`. It will work in most cases.

**Comment by TheEhsanSarshar** [comment]
maybe animation on `Image` is disabled for some reason, I should ask the team for that.
anyway please let me know if that was not helpful for you, I'll surely take a look into this.

**Comment by natew** [comment]
Looking into this, with css its actually a bug with RNW I filed an issue and fixed it in react-native-web-lite, but still it doesn't animate due to something having to do with how it lazy loads images. I think ultimately we need to move off the RNW Image API it's not really nice at all.

For Spring I think the issue is the same, the animation is running properly but due to the image loading during the animation it seems to not show it for some reason.
