### ISSUE TITLE
Color options in variants for button not working

### ISSUE THREAD

**Issue by MatLish00010** [tamagui/tamagui#1156]
### Current Behavior

When I use it doesn't work, but it worked in version 1.15.33.

### Expected Behavior

The color should change if another option is selected

### Tamagui Version

```markdown
1.27.3
```

### Reproduction

```markdown
import {Button as ButtonTamagui, styled} from 'tamagui';

export const Button = styled(ButtonTamagui, {
  borderRadius: '$8',
  fontFamily: '$body',
  fontSize: '$4',
  fontWeight: '$7',
  height: '$5',
  maxWidth: '100%',

  variants: {
    disabled: {
      true: {
        opacity: 0.5,
      },
    },
    type: {
      contained: {
        backgroundColor: '$background',
        color: '$color',
      },
      outlined: (_, {props}) => {
        return {
          backgroundColor: props.active ? '$lightColor' : '$backgroundSecondary',
          color: props.active ? '$color' : '$secondaryColor',
          borderColor: props.active ? '$lightColor' : '$borderColor',
        };
      },
      text: {
        borderWidth: 0,
        backgroundColor: 'transparent',
        color: '$secondaryColor',
      },
    },
  } as const,

  defaultVariants: {
    type: 'contained',
  },
});

<Button type="outlined">Text</Button>
```

**Comment by la55u** [comment]
It's not a bug, you can't use `color` in a styled(Button). For now you have to resort to the "advanced" section in the docs. A new Button is in the works to make this easier.

**Comment by GigaBigBoss** [comment]
I know there was a bug a few months ago where themes didn't apply on native to buttons. Updating fixed it for me

**Comment by natew** [comment]
Actually latest release even fixes color in styled(Button), thanks to the magic of `createStyledContext`

**Comment by wan54** [comment]
Couldn't make it work with `createStyledContext`. `withStaticProperties` approach works beautifully for me.

`Button.Primary` - custom background and foreground colors
`Button.Secondary` - custom foreground and border colors

**Comment by brianbolnick** [comment]
Does this apply to button font weights too? On the latest version and passing through the `fontWeight` prop to a button does not make it through to the text component as the docs specify @natew 


<img width="670" alt="image" src="https://github.com/tamagui/tamagui/assets/4327477/8b654945-7cb8-439a-a507-ce88657f2b5c">


Button component shows the right weight:
<img width="397" alt="image" src="https://github.com/tamagui/tamagui/assets/4327477/164a3633-f6b7-490c-9152-2e61d64a049e">


But the Text component doesn't have it:
<img width="395" alt="image" src="https://github.com/tamagui/tamagui/assets/4327477/20d4d43a-12b5-4708-8c10-2a36ce2a8e42">
