### ISSUE TITLE
styled `TouchableOpacity` does not forward the `onPress` prop

### ISSUE THREAD

**Issue by Christopher2K** [tamagui/tamagui#1164]
### Current Behavior

Hi team! I found something when I was working with `styled` in a native only expo app.

Given this situation
```typescript
import {  styled } from 'tamagui'
import { TouchableOpacity } from 'react-native'

const CustomTouchable = styled(TouchableOpacity, { bg: 'green' })

...

<CustomTouchable onPress={() => console.log('LOG!') />
```

When I press on this touchable, it won't print anything. It's working when I remove the second argument in the styled declaration! For some reason, if we provide a style object, `onPress` is not forwarded.

### Expected Behavior

I expect that, if I wrap a TouchableOpacity using styled and providing a default style, it should still forward the `onPress` property!

### Tamagui Version

```markdown
1.27.3
```

### Reproduction

```markdown
https://github.com/Christopher2K/touchable-tamagui-bug/commit/dedf0eeebeeccf4accc7bbe8abcf7540a48c6bc3
```

### System Info

```markdown
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 67.55 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.asdf/installs/nodejs/16.14.2/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/16.14.2/bin/yarn
    npm: 8.5.0 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 16.4
```

**Comment by natew** [comment]
This is actually just about intended, those are utility components that overlap with built-in behavior, I'm adding a docs not about this in a PR.

**Comment by Christopher2K** [comment]
Thanks for the clarification!

**Comment by huhuanming** [comment]
hello, i am stuck in this trouble.
any docs for here?

**Comment by baronha** [comment]
I also faced this. So where are the documents?

**Comment by natew** [comment]
Have you tried adding isReactNative true to the third argument of styled()

**Comment by natew** [comment]
Still it’s a bad idea to do this it’ll be slow and you can just make touchableopacity with a simple pressStyle on a regular View

**Comment by baronha** [comment]
> Still it’s a bad idea to do this it’ll be slow and you can just make touchableopacity with a simple pressStyle on a regular View

Thank you. Because I would probably wrap a `Touchable` or `Pressable` class on the outside of the ButtonFrame. Thanks for this great `@tamagui/core`
