### ISSUE TITLE
themeInverse does not look right on native since v1.22.10

### ISSUE THREAD

**Issue by G-Ray** [tamagui/tamagui#1170]
On native, a button with `themeInvese` is not readable and does not have the expected look since [v1.22.10](https://github.com/tamagui/tamagui/releases/tag/v1.22.10).
Meanwhile it looks fine on web.

[v1.22.9](https://github.com/tamagui/tamagui/releases/tag/v1.22.9)
![image](https://github.com/tamagui/tamagui/assets/2981774/680cc625-6ea7-4c9c-944e-3902b8807109)

Since [v1.22.10](https://github.com/tamagui/tamagui/releases/tag/v1.22.10)
![image](https://github.com/tamagui/tamagui/assets/2981774/82262759-302a-4db2-9157-97db86141d28)

**Comment by G-Ray** [comment]
This seems partially fixed from https://github.com/tamagui/tamagui/releases/tag/v1.28.0.
The text color is correctly inverted, but not the icon yet.

Web: 
![image](https://github.com/tamagui/tamagui/assets/2981774/609cd39f-6e82-47f4-a081-93cffdfacc79)

Native:
![image](https://github.com/tamagui/tamagui/assets/2981774/d1ba8f25-0673-4bdc-8da5-1914a2eedf74)

**Comment by natew** [comment]
thanks for finding the exact version, helped a lot. fixed in `1.28.3`.
