### ISSUE TITLE
Allow changing project root for tamagui loader

### ISSUE THREAD

**Issue by Mimameid** [tamagui/tamagui#1175]
### Current Behavior

In our nx monorepo setup the tamagui loader has issues finding the correct `tsconfig.json`. We have a hacky fix in place, which is pretty much calling `process.chdir()` somwhere and some adjustments of paths in configuration files. 

The said property is already a parameter but not configurable yet: https://github.com/tamagui/tamagui/blob/41f84591377e5a9b1dc920f4571fab6f6abcf55e/packages/static/src/extractor/loadTamagui.ts#LL144C18-L144C18

### Tamagui Version

```markdown
1.27.1
```

### Reproduction

```markdown
Can try to provide when it is actually needed.
```

**Comment by natew** [comment]
Ack, this actually isn't even necessary, I'm removing the check for now in the next release.

**Comment by natew** [comment]
Disabled in latest
