### ISSUE TITLE
Unable to build the starter project as a preview app for IOS with EAS 

### ISSUE THREAD

**Issue by matthewhausman** [tamagui/tamagui#1176]
### Current Behavior

I cloned the tamagui start repo. Then I made a script in package.json for build a preview app w/ EAS. Did all the project setup on expo. 

the script is:
`
{
    ...,
    "build:native:preview": "cd apps/expo && eas build --profile preview"
}
`

The build errors look like this:

`❌  (ios/Pods/SDWebImageAVIFCoder/SDWebImageAVIFCoder/Classes/Conversion.m:158:28)

  156 |     state->biasY = (state->yuvRange == AVIF_RANGE_LIMITED) ? (float)(16 << (state->yuvDepth - 8)) : 0.0f;
  157 |     state->biasUV = (float)(1 << (state->yuvDepth - 1));
> 158 |     state->biasA = (image->alphaRange == AVIF_RANGE_LIMITED) ? (float)(16 << (state->yuvDepth - 8)) : 0.0f;
      |                            ^ no member named 'alphaRange' in 'struct avifImage'; did you mean 'alphaPlane'?
  159 |     state->rangeY = (float)((state->yuvRange == AVIF_RANGE_LIMITED) ? (219 << (state->yuvDepth - 8)) : state->yuvMaxChannel);
  160 |     state->rangeUV = (float)((state->yuvRange == AVIF_RANGE_LIMITED) ? (224 << (state->yuvDepth - 8)) : state->yuvMaxChannel);
  161 |     state->rangeA = (float)((image->alphaRange == AVIF_RANGE_LIMITED) ? (219 << (state->yuvDepth - 8)) : state->yuvMaxChannel);`

### Expected Behavior

Successfully build a preview app with EAS. 

### Tamagui Version

```markdown
latest
```

### Reproduction

```markdown
https://github.com/matthewhausman/ios-preview-build-failure-reprod
```

### System Info

```markdown
System:
    OS: macOS 13.0
    CPU: (12) arm64 Apple M2 Pro
    Memory: 205.84 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 112.0.1
    Safari: 16.1
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.39.0 
    node-gyp: ^9.3.1 => 9.3.1 
    prettier: ^2.7.1 => 2.8.8 
    turbo: ^1.8.3 => 1.9.3 
    typescript: ^4.7.4 => 4.9.5
```

**Comment by matthewhausman** [comment]
found https://forums.expo.dev/t/expo-image-causes-eas-build-to-fail/71498/2

**Comment by wilsonquest** [comment]
You have to fix your expo image to 1.2.3... They messed up the Pod files

**Comment by matthewhausman** [comment]
@wilsonquest yea..., and now my app renders as a black screen haha

**Comment by matthewhausman** [comment]
alright just added     "plugins": [["expo-router", { "origin": "https://..." }]], to expo config think that'll do the trick

**Comment by natew** [comment]
Merged some fixes, but can you send a PR fixing the expo-image version?

**Comment by matthewhausman** [comment]
I think that the PR you merged removed expo image which wasn't used in the starter anyway 

https://github.com/tamagui/tamagui/issues/1176
