### ISSUE TITLE
[Issue] Invariant Violation: View config getter callback for component `div` must be a function (received `undefined`).

### ISSUE THREAD

**Issue by 404-html** [tamagui/tamagui#1185]
### Current Behavior

An attempt to use Tamagui in existing React Native project results in following error being thrown:

```
Invariant Violation: View config getter callback for component `div` must be a function (received `undefined`). Make sure to start component names with a capital letter.

This error is located at:
    in div
    in Unknown (created by App)
    in PortalProviderComponent
    in _Theme (created by _ThemeProvider)
    in _ThemeProvider (created by _TamaguiProvider)
    in _TamaguiProvider
    in Unknown (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in app(RootComponent), js engine: hermes
```

### Expected Behavior

It would be nice to use at least core Tamagui components.

### Tamagui Version

```markdown
1.28.1
```

### Reproduction

Add Tamagui to the project by following installation steps:
https://tamagui.dev/docs/intro/installation#native

with one exception: skip Expo installation step, as according to this comment it should no longer be mandatory.
https://github.com/tamagui/tamagui/discussions/1125#discussioncomment-5923702

Config file:

```
import { config } from '@tamagui/config';
import { createTamagui } from 'tamagui'; // or '@tamagui/core'

const appConfig = createTamagui(config);

export type AppConfig = typeof appConfig;

declare module '@tamagui/core' {
    // overrides TamaguiCustomConfig so your custom types
    // work everywhere you import `tamagui`
    interface TamaguiCustomConfig extends AppConfig {}
}

export default appConfig;
```

App.tsx:
```
import React from 'react';
import { TamaguiProvider, YStack } from 'tamagui';

import config from './app/common/theme/tamagui.config';

type Props = {};

export const App = (props: Props) => {
    return (
        <TamaguiProvider config={config}>
            <YStack></YStack>
        </TamaguiProvider>
    );
};
```

### System Info

```markdown
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz   
    Memory: 2.62 GB / 15.92 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE        
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @babel/core: ^7.20.0 => 7.21.0
    @babel/preset-typescript: ^7.15.0 => 7.21.0
    @babel/runtime: ^7.20.0 => 7.21.0
    @react-native-async-storage/async-storage: 1.17.11 => 1.17.11
    @react-native-clipboard/clipboard: 1.11.2 => 1.11.2
    @react-native-community/blur: 4.3.0 => 4.3.0
    @react-native-community/checkbox: 0.5.14 => 0.5.14
    @react-native-community/eslint-config: ^3.2.0 => 3.2.0
    @react-native-community/hooks: 3.0.0 => 3.0.0
    @react-native-community/image-editor: 2.3.0 => 2.3.0
    @react-native-community/netinfo: 9.3.7 => 9.3.7
    @react-native-firebase/analytics: 17.3.2 => 17.3.2
    @react-native-firebase/app: 17.3.2 => 17.3.2
    @react-native-firebase/crashlytics: 17.3.2 => 17.3.2
    @react-native-firebase/in-app-messaging: 17.3.2 => 17.3.2
    @react-native-firebase/messaging: 17.3.2 => 17.3.2
    @react-native-firebase/remote-config: 17.3.2 => 17.3.2
    @svgr/cli: 6.2.1 => 6.2.1
    @tamagui/babel-plugin: 1.28.1 => 1.28.1
    @tamagui/config: 1.28.1 => 1.28.1
    @tanstack/react-query: 4.26.0 => 4.26.0
    @trpc/client: 10.14.0 => 10.14.0
    @trpc/react-query: 10.14.0 => 10.14.0
    @trpc/server: 10.14.0 => 10.14.0
    @types/jest: ^29.2.1 => 29.4.0
    @types/react: ^18.0.24 => 18.0.28
    @types/react-native: ^0.66.16 => 0.66.27
    @types/react-test-renderer: ^18.0.0 => 18.0.0
    axios: 0.21.1 => 0.21.1
    babel-jest: ^29.2.1 => 29.5.0
    babel-plugin-transform-inline-environment-variables: 0.4.4 => 0.4.4
    eslint: 8.19.0 => 8.19.0
    googleapis: 118.0.0 => 118.0.0
    husky: ^7.0.0 => 7.0.4
    jest: ^29.2.1 => 29.5.0
    lodash: 4.17.21 => 4.17.21
    metro-react-native-babel-preset: 0.73.9 => 0.73.9
    native-base: 3.4.6 => 3.4.6
    prettier: ^2.4.1 => 2.8.4
    pretty-quick: ^3.1.1 => 3.1.3
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    react-native: 0.71.5 => 0.71.5
    react-native-animatable: ^1.3.3 => 1.3.3
    react-native-awesome-gallery: 0.3.4 => 0.3.4
    react-native-camera: react-native-camera/react-native-camera#3443/head => 4.2.1
    react-native-clean-project: ^3.6.7 => 3.6.7
    react-native-code-push: 7.1.0 => 7.1.0
    react-native-device-info: 7.3.1 => 7.3.1
    react-native-drag-sort: 2.4.4 => 2.4.4
    react-native-exception-handler: 2.10.10 => 2.10.10
    react-native-gesture-handler: 2.9.0 => 2.9.0
    react-native-iap: ^7.4.1 => 7.5.6
    react-native-image-picker: 5.1.0 => 5.1.0
    react-native-localize: 2.2.5 => 2.2.5
    react-native-rate: 1.2.12 => 1.2.12
    react-native-reanimated: 3.1.0 => 3.1.0
    react-native-safe-area-context: 4.5.0 => 4.5.0
    react-native-sensitive-info: ^5.5.8 => 5.5.8
    react-native-snowflakes: ^1.0.3 => 1.0.3
    react-native-svg: ^12.1.0 => 12.5.1
    react-native-svg-transformer: ^0.14.3 => 0.14.3
    react-native-ux-cam: 5.3.4 => 5.3.4
    react-native-video: 5.2.1 => 5.2.1
    react-redux: 8.0.5 => 8.0.5
    react-test-renderer: 18.2.0 => 18.2.0
    redux: 4.2.1 => 4.2.1
    redux-logger: 3.0.6 => 3.0.6
    redux-thunk: 2.4.2 => 2.4.2
    svgo: 3.0.2 => 3.0.2
    tailwind-rn: ^3.0.1 => 3.0.1
    tamagui: 1.28.1 => 1.28.1
    typescript: ^4.8.4 => 4.9.5
    zustand: 4.0.0-rc.1 => 4.0.0-rc.1
```

**Comment by 404-html** [comment]
I did a bit of the debugging and for some reason `isReactNative` ends up set as `false` here:
https://github.com/tamagui/tamagui/blob/master/packages/web/src/styled.tsx#L87

**Comment by 404-html** [comment]
Thanks @natew. That was my guess to but when I console log `process.env.TAMAGUI_TARGET` around the line linked in my previous comment it logs `native`. 

And that's the `babel.config.js`:
```js
// just to ensure TAMAGUI_TARGET is set
process.env.TAMAGUI_TARGET = 'native';

module.exports = {
    presets: ['module:metro-react-native-babel-preset'],
    plugins: [
        [
            'transform-inline-environment-variables',
            {
                include: ['TAMAGUI_TARGET'],
            },
        ],
    ],
};
```

**Comment by TehseenJawed** [comment]
Thank you for opening this issue. I am trying to use tamagui library for 2 days. I am using it in react native / Expo and after installing it and related dependencies. and wrapping the whole app with its provider I am getting errors when I am using any of the Tamagui assets. I moved my react, and react-dom to version 18, and integrated typescript with the help of Expo doc but it didn't fix my problem.
I have doubts what is causing this failure. Please check my node modules.

Package.json.

`"@bugsnag/react-native": "^7.10.3",
    "@expo/webpack-config": "^18.0.4",
    "@js-joda/core": "^5.2.0",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/cli-platform-android": "^6.3.0",
    "@react-native-community/datetimepicker": "6.1.2",
    "@react-native-community/hooks": "2.4.3",
    "@react-native-community/push-notification-ios": "^1.0.6",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/stack": "^6.0.7",
    "@tamagui/animations-react-native": "^1.28.1",
    "@tamagui/babel-plugin": "^1.28.1",
    "@tamagui/config": "^1.28.1",
    "@tamagui/font-inter": "^1.28.1",
    "@tamagui/theme-base": "^1.28.1",
    "@testing-library/react-hooks": "^7.0.2",
    "@testing-library/react-native": "^7.2.0",
    "@types/react": "^18.2.6",
    "cuid": "^2.1.6",
    "deep-diff": "^1.0.2",
    "deep-object-merge": "^1.0.0",
    "deepmerge": "^4.2.2",
    "expo": "~45.0.0",
    "expo-background-fetch": "~10.2.0",
    "expo-build-properties": "^0.3.0",
    "expo-device": "~4.2.0",
    "expo-font": "^11.1.1",
    "expo-image-loader": "~3.2.0",
    "expo-linking": "~3.1.0",
    "expo-localization": "~13.0.0",
    "expo-modules-core": "~0.9.2",
    "expo-notifications": "~0.15.2",
    "expo-splash-screen": "~0.16.1",
    "expo-status-bar": "~1.3.0",
    "expo-store-review": "~5.2.0",
    "expo-task-manager": "~10.2.1",
    "fast-deep-equal": "^2.0.1",
    "global": "^4.4.0",
    "i18n-js": "^3.8.0",
    "just-is-empty": "^2.0.1",
    "poly-filter": "^1.0.2",
    "poly-find": "^1.0.1",
    "poly-map": "2.2.4",
    "postinstall-postinstall": "^2.0.0",
    "re-reselect": "^3.4.0",
    "react": "18.0.0-alpha-5ca4b0433-20211020",
    "react-dom": "18.0.0-alpha-5ca4b0433-20211020",
    "react-native": "0.68.2",
    "react-native-animatable": "^1.3.3",
    "react-native-blink-view": "^0.0.6",
    "react-native-calendars": "^1.264.0",
    "react-native-chooser": "^1.7.0",
    "react-native-datepicker": "rikur/react-native-datepicker#upgrade",
    "react-native-flipper": "^0.127.0",
    "react-native-fs": "2.16.6",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-highlight-words": "^1.0.1",
    "react-native-html-to-pdf": "^0.11.0",
    "react-native-iphone-x-helper": "^1.2.1",
    "react-native-localize": "^2.1.1",
    "react-native-modal": "^13.0.0",
    "react-native-modest-checkbox": "^3.3.0",
    "react-native-pixel-perfect": "^1.0.2",
    "react-native-privacy-snapshot": "darling-apps/react-native-privacy-snapshot",
    "react-native-purchases": "^4.2.0",
    "react-native-reanimated": "~2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-safe-area-view": "^1.0.0",
    "react-native-screens": "~3.11.1",
    "react-native-share": "^7.3.3",
    "react-native-size-matters": "0.3.0",
    "react-native-swipe-gestures": "^1.0.4",
    "react-native-text-input": "raccoon-technology/react-native-text-input",
    "react-native-theme-picker": "^1.0.0",
    "react-native-view-shot": "3.1.2",
    "react-native-web": "^0.19.4",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-persist": "^5.10.0",
    "redux-persist-seamless-immutable": "^2.0.0",
    "redux-saga": "^1.1.1",
    "redux-saga-rn-alert": "^1.2.7",
    "redux-seamless-immutable": "^0.4.0",
    "reselect": "^4.0.0",
    "seamless-immutable": "^7.1.4",
    "tamagui": "^1.28.1",
    "thenby": "^1.3.0"`
    
    tamagui.config.ts.
    
    `import { createAnimations } from '@tamagui/animations-react-native'
import { createInterFont } from '@tamagui/font-inter'
import { createMedia } from '@tamagui/react-native-media-driver'
import { shorthands } from '@tamagui/shorthands'
import { themes, tokens } from '@tamagui/themes'
import { createTamagui } from 'tamagui'
import * as ReactNative from 'react-native'
import {setupReactNative} from '@tamagui/core'

const animations = createAnimations({
  bouncy: {
    type: 'spring',
    damping: 10,
    mass: 0.9,
    stiffness: 100,
  },
  lazy: {
    type: 'spring',
    damping: 20,
    stiffness: 60,
  },
  quick: {
    type: 'spring',
    damping: 20,
    mass: 1.2,
    stiffness: 250,
  },
})
const headingFont = createInterFont()
const bodyFont = createInterFont()
setupReactNative(ReactNative)
const config = createTamagui({
  animations,
  defaultTheme: 'dark',
  shouldAddPrefersColorThemes: false,
  themeClassNameOnRoot: false,
  shorthands,
  fonts: {
    heading: headingFont,
    body: bodyFont,
  },
  themes,
  tokens,
  media: createMedia({
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
    short: { maxHeight: 820 },
    tall: { minHeight: 820 },
    hoverNone: { hover: 'none' },
    pointerCoarse: { pointer: 'coarse' },
  }),
})
export type AppConfig = typeof config
declare module 'tamagui' {
  // overrides TamaguiCustomConfig so your custom types
  // work everywhere you import `tamagui`
  interface TamaguiCustomConfig extends AppConfig {}

}
export default config`

bable.config.js
`// Don't forget to specify your TAMAGUI_TARGET here or ideally in the command to run / .env files
process.env.TAMAGUI_TARGET = 'native'

module.exports = function(api) {
  api.cache(true)
  return {
    presets: ['module:metro-react-native-babel-preset'],
    sourceMaps: 'inline',
    retainLines: true,
    // presets: ["babel-preset-expo"],
    plugins: [
      [
        'module-resolver',
        {
          root: ['.'],
          extensions: ['.ios.js', '.android.js', '.js', '.json'],
        },
      ],
      // NOTE: this is required to pass the right environment
      [
        'transform-inline-environment-variables',
        {
          include: 'native',
        },
      ],
      // NOTE: this is optional, you don't *need* the compiler
      [
        '@tamagui/babel-plugin',
        {
          components: ['tamagui'],
          config: './tamagui.config.ts',
          logTimings: true,
        },
      ],
      // NOTE: this is only necessary if you are using reanimated for animations
      'react-native-reanimated/plugin',
    ],
  }
}`

<img width="895" alt="Screenshot 2023-05-20 at 3 03 34 AM" src="https://github.com/tamagui/tamagui/assets/51497155/0fd31c01-b8c1-4a98-a5dd-6fa9ff12bfd1">

**Comment by natew** [comment]
looks like outdated react actually, thats trying to call useSyncExternalStore and its undefined. double check your lockfile and maybe use `resolutions` in yarn if youre using it to ensure only one version of react 18 installed.

**Comment by TehseenJawed** [comment]
@natew I am using react version "18.0.0-alpha-5ca4b0433-20211020", which is the version that is not giving undefined errors inside react node module. Please check the attached screenshot which is giving an error inside react in the latest version 18
<img width="1054" alt="Screenshot 2023-05-22 at 3 01 21 AM" src="https://github.com/tamagui/tamagui/assets/51497155/f4038916-1009-4659-af3a-5066cf363b68">
.2

**Comment by natew** [comment]
i need repros in order to not get totally bogged down on issues, if you create one you can re-open and i'll investigate

**Comment by kevinchristianto** [comment]
I'm having a related issue that shows `TAMAGUI_TARGET` error as the first error.

If I used any `Stack` component with no child component in it, I got the same invariant violation error as @404-html, then when I added a `Text` component inside of it, the error changed to _Text strings must be rendered within a <Text> component_
I also printed TAMAGUI_TARGET at my index file, and the value is `native`

I really have no idea

**Comment by theUpsider** [comment]
Same problem. Really frustrating.

**Comment by idrakimuhamad** [comment]
In Expo 49, the usage `transform-inline-environment-variables` would seems conflicting with the expo support for .env. All of my environment loaded from .env file would be undefined.

If i remove the plugin, tamagui would not work. The only way to make everything work is to *manually* include all of my env into the plugin's `include` list.


```js
[
        "transform-inline-environment-variables",
        {
          include: [
            "TAMAGUI_TARGET",
            "EXPO_ROUTER_APP_ROOT",
            "EXPO_ROUTER_PROJECT_ROOT",
            "EXPO_ROUTER_IMPORT_MODE",
            "EXPO_ROUTER_IMPORT_MODE_ANDROID",
            "EXPO_ROUTER_IMPORT_MODE_IOS",
            "EXPO_ROUTER_IMPORT_MODE_WEB",
            "EXPO_PUBLIC_BASE_URL_DEV",
            "EXPO_PUBLIC_APP_KEY_DEV",
            "EXPO_PUBLIC_APP_SECRET_DEV",
          ]
        }
]
```

Is there anyway you can support both `TAMAGUI_TARGET` **and** `EXPO_PUBLIC_TAMAGUI_TARGET`?

**Comment by Michael9311** [comment]
@idrakimuhamad did you get a working solution for Expo 49?

**Comment by Michael9311** [comment]
@idrakimuhamad's solution, plus running expo metro with --clear solved the problem for me.

**Comment by idrakimuhamad** [comment]
> @idrakimuhamad's solution, plus running expo metro with --clear solved the problem for me.

In my recent attempt, what I did is to remove TAMAGUI_TARGET from babel json, add it into .env, but leave the transform inline environment variable without anything else.
