### ISSUE TITLE
TextInput unexpectedly captitalized

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [tamagui/tamagui#1197]
### Current Behavior

All TextInput fields are capitalized even though `autoCapitalize` is not set, or is set to "none"

### Expected Behavior

The text in the input is not captitalized in this way.

### Tamagui Version

```markdown
1.29.1
```

### Reproduction

```markdown
- Create an app with `npm create tamagui@latest`
- Create a simple TextInput
- There it is
```

### System Info

```markdown
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 1.51 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nodenv/versions/18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nodenv/versions/18.15.0/bin/yarn
    npm: 9.6.7 - ~/.nodenv/versions/18.15.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.1
    Safari: 16.4
```

Images:

![image](https://github.com/tamagui/tamagui/assets/7723097/a0e58c0b-87d7-448c-93be-df88ab690ebc)

(Yes, even the placeholder is capitalized).

**Comment by natew** [comment]
Ah this is due to the order of definition in the fonts.

If you set `defaultFont: 'body'` in your createTamagui it will fix this for now, I'm cutting a release in a minute that adds backwards compat for this to fix it automatically.

**Comment by natew** [comment]
Add `defaultFont` and change the order of `fonts` like this:

<img width="439" alt="CleanShot 2023-05-22 at 06 58 51@2x" src="https://github.com/tamagui/tamagui/assets/12100/66d3d186-6c2d-4c59-a972-7a33f7a32b8d">

Release going out now with a fix so you don't have to do this as well.
