### ISSUE TITLE
Tamagui.dev Sheet demo missing

### ISSUE THREAD

**Issue by KrastanD** [tamagui/tamagui#1198]
### Current Behavior

Can't see the sheet trigger button on tamagui.dev demo on Firefox, Chrome or Brave
<img width="848" alt="image" src="https://github.com/tamagui/tamagui/assets/32044675/af5f93f5-2fca-4a9a-a519-dbaa02dd8b21">

### Expected Behavior

It used to have a box and you could see the sheet both in the box and in the whole browser. 

### Tamagui Version

```markdown
I assume 1.28
```

### Reproduction

```markdown
go to tamagui.dev then to the sheet demo page and see it missing.
```

### System Info

```markdown
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 52.78 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Brave Browser: 113.1.51.114
    Chrome: 106.0.5249.119
    Firefox: 113.0.1
    Safari: 16.4
```

**Comment by natew** [comment]
Can't replicate this... tested on all three browsers.

**Comment by KrastanD** [comment]
Yea, I'm seeing it now too. At the time the route wasn't adding the 1.27.0 at the end. Will reopen if I figure out how to replicate consistently.
