### ISSUE TITLE
[Issue] Toast not usable in bare React Native project because Burnt depends on `expo-modules-core`

### ISSUE THREAD

**Issue by saaymeen** [tamagui/tamagui#1200]
Tamaguis toast implementation relies on `burnt`, a third party package to provide its native functionality. The maintainer of this library marked an [issue](https://github.com/nandorojo/burnt/issues/4) about compatibility with bare React Native (non expo-managed workflow) as "wontfix". Currently, developers who want to use tamagui to its fullest extend are forced to rely on expo when using React Native, which is rather suboptimal. Yes, expo modules can be added to any RN project, but developers shouldn't be forced to add this overhead only for a toast functionality (there are reasons behind not realying on expo after all).
Similar points can be made towards the `LinearGradient` implementation.

**Comment by natew** [comment]
Toast isn't included in `tamagui` neither is linear-gradient, so you don't need to install it if you don't need them.
