### ISSUE TITLE
`children` props are not available when extending a component using `styled` and `variants`

### ISSUE THREAD

**Issue by idrakimuhamad** [tamagui/tamagui#1205]
I notice that whenever I create a component using `styled` and added `variants`, and when I use the component, TS complaining about non-existence `children`.

Example component.

```jsx
export const Card = styled(ThemeableStack, {
  name: "Card",
  hoverTheme: false,
  pressTheme: false,
  focusTheme: false,

  bg: "$card.bg",
  p: "$4",
  borderRadius: "$5",

  variants: {
    floating: {
      true: {
        elevation: '$4',
        elevationAndroid: 2
      }
    }
  } as const
})
```

<img width="653" alt="Screenshot 2023-05-24 at 11 32 04 AM" src="https://github.com/tamagui/tamagui/assets/1400323/0c6d9d85-9755-48b4-baa1-8798926de546">

If I remove `variants`, the error go away. Is there a correct way to do this so TS won't complain?

tamagui: `1.28.1`

**Comment by natew** [comment]
Need a repro please theres a codesandbox

**Comment by idrakimuhamad** [comment]
Very well. Here's the repo.

https://github.com/idrakimuhamad/repro-tamagui

Specifically the issue example is at this file

https://github.com/idrakimuhamad/repro-tamagui/blob/main/packages/ui/src/card.tsx

![Screenshot 2023-05-25 at 6 09 41 PM](https://github.com/tamagui/tamagui/assets/1400323/745f0406-ace4-44ff-8215-71dd044e430b)

The repo created using `create-tamagui` and nothing was added nor removed. I just create a new file, and added the sample component.

**Comment by andrewkucz** [comment]
I am experiencing this issue as well, on the latest tamagui 1.30.16

I think you may have closed this because OP did not provide a repro but I think he has since provided one. Can this issue be re-opened and looked at when possible? Thanks @natew

**Comment by thecynicalpaul** [comment]
Experiencing the same issue as of 1.30.16

It seems like it's not just the `children` prop, it is all props of the component – they seem to be overridden by variant types. E.g.: 

![auto complete example](https://cdn.discordapp.com/attachments/466916630434283534/1113932000097730671/image.png)

**Comment by natew** [comment]
Are you guys on the latest Typescript 5.1? I noticed it breaks types everywhere.

**Comment by andrewkucz** [comment]
Strangely I am on typescript 4.9.4

**Comment by thecynicalpaul** [comment]
> Are you guys on the latest Typescript 5.1? I noticed it breaks types everywhere.

I am on Typescript 5.0.2

**Comment by natew** [comment]
Not seeing an error on the repo:

<img width="1094" alt="CleanShot 2023-06-03 at 13 38 54@2x" src="https://github.com/tamagui/tamagui/assets/12100/f41dea3f-5e67-43c9-8e0e-98f0b5ca60ff">

Are you using experimental TS plugin for vcode?

**Comment by lostpebble** [comment]
I was running into this issue today, I found that reverting and locking my TypeScript version to this worked:

```
"typescript": "5.0.4"
```

**Comment by idrakimuhamad** [comment]
> Not seeing an error on the repo:
> 
> 
> 
> <img width="1094" alt="CleanShot 2023-06-03 at 13 38 54@2x" src="https://github.com/tamagui/tamagui/assets/12100/f41dea3f-5e67-43c9-8e0e-98f0b5ca60ff">
> 
> 
> 
> Are you using experimental TS plugin for vcode?

I do not, at least I don't think so.

My TS version in my monorepo goes from 4.9 to 5.1. I will try fixed resolution to 5.0 and see if it's working.

Note also, I see this error if I use `ThemeableStack`, not if I use `YStack`

**Comment by alexbchr** [comment]
Started getting this problem after updating to Typescript 5.1.3, which is now stable.

**Comment by natew** [comment]
5.1 fixed in https://github.com/tamagui/tamagui/releases/tag/v1.31.0
