### ISSUE TITLE
(website): safari mobile, hamburger bottom sheet renders no content

### ISSUE THREAD

**Issue by benschac** [tamagui/tamagui#1206]
### Current Behavior

Bottom sheet doesn’t render menu items 
![Tamagui — React Native + Web UI kit png](https://github.com/tamagui/tamagui/assets/2502947/15b07b12-d893-4103-9954-65248645c0a7)

### Expected Behavior

Should render menu items

### Tamagui Version

```markdown
N/a
```

### Reproduction

```markdown
on mobile web site, using safari mobile
```

### System Info

```markdown
safari mobile
```

**Comment by natew** [comment]
ah in optimizing some stuff broke that, thanks
