### ISSUE TITLE
Sheet with CSS driver isn't animating to open state

### ISSUE THREAD

**Issue by la55u** [tamagui/tamagui#1209]
### Current Behavior

When you open the sheet with the CSS driver enabled it weirdly just pops up on the screen instead of sliding up from the bottom like in the inline mode or with the RN animation driver. It seems like it's skipping the transition somehow and just appears suddenly like it was conditionally rendered.

[tamagui.webm](https://github.com/tamagui/tamagui/assets/30611343/a054e744-e6cb-4260-b89c-80a8e36830fe)

### Expected Behavior

The sheet should be sliding up from the bottom smoothly

### Tamagui Version

```markdown
site default
```

### Reproduction

```markdown
1. open the demo here: https://tamagui.dev/docs/components/sheet/1.27.0
2. switch to CSS driver at the top left
3. change to "modal" mode
4. click on the Open button
5. See the issue
```

### System Info

```markdown
System:
    OS: Linux 6.2 Fedora Linux 37 (Workstation Edition)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 16.85 GB / 31.04 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 114.0b7
  npmPackages:
    @babel/runtime: ^7.21.0 => 7.21.5 
    @commitlint/cli: ^17.6.1 => 17.6.3 
    @commitlint/config-conventional: ^17.6.1 => 17.6.3 
    @types/react: ^18.0.38 => 18.2.6 
    check-dependency-version-consistency: ^3.0.3 => 3.1.1 
    eslint: ^8.36.0 => 8.40.0 
    husky: ^8.0.3 => 8.0.3 
    node-gyp: ^9.3.1 => 9.3.1 
    prettier: ^2.8.7 => 2.8.8 
    turbo: ^1.8.5 => 1.9.6 
    typescript: 4.9.5 => 4.9.5
```

**Comment by natew** [comment]
Good catch, fix going out in `1.30.2`, would be nice to get some tests around this we do have it set up so it wouldn't take too long.
