### ISSUE TITLE
Uncaught Error (0 , _Pressability.usePressability) is not a function

### ISSUE THREAD

**Issue by jonnigg** [tamagui/tamagui#1210]
### Current Behavior

Using certain props on certain components generates a fatal error with the following information:

![image](https://github.com/tamagui/tamagui/assets/3459294/55baebd2-2607-4207-87d9-89950470bb8c)

Two examples have been when using <YStack> with the space={'$2'} prop or the <Image> component with the source={{}} prop.

If these props are removed, the web starts working again

### Tamagui Version

```markdown
"tamagui": "^1.28.0"
```

### Reproduction

```markdown
import { YStack, Text } from 'tamagui'


<YStack space={'$2'} borderWidth={2} borderColor='$color'>
 <Text>Hello World</>
</YStack>
```

### System Info

```markdown
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 458.04 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.1.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.4 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 113.1.51.118
    Safari: 16.0
  npmPackages:
    @babel/core: ^7.20.0 => 7.21.8
    @babel/plugin-proposal-export-namespace-from: ^7.18.9 => 7.18.9
    @expo/vector-icons: ^13.0.0 => 13.0.0
    @react-navigation/drawer: ^6.6.2 => 6.6.2
    @react-navigation/native: ^6.0.2 => 6.1.6
    @tamagui/animations-react-native: ^1.28.0 => 1.28.0
    @tamagui/babel-plugin: ^1.29.6 => 1.29.6
    @tamagui/config: ^1.28.0 => 1.28.0
    @tamagui/font-inter: ^1.28.0 => 1.28.0
    @tamagui/react-native-media-driver: ^1.29.6 => 1.29.6
    @tamagui/shorthands: ^1.29.6 => 1.29.6
    @tamagui/theme-base: ^1.28.0 => 1.28.0
    @tamagui/themes: ^1.29.6 => 1.29.6
    @types/react: ~18.0.14 => 18.0.38
    babel-plugin-transform-inline-environment-variables: ^0.4.4 => 0.4.4
    expo: ~48.0.15 => 48.0.17
    expo-dev-client: ~2.2.1 => 2.2.1
    expo-font: ^11.1.1 => 11.1.1
    expo-linking: ~4.0.1 => 4.0.1
    expo-router: ^1.5.2 => 1.5.3
    expo-splash-screen: ~0.18.2 => 0.18.2
    expo-status-bar: ~1.4.4 => 1.4.4
    expo-system-ui: ~2.2.1 => 2.2.1
    expo-web-browser: ~12.1.1 => 12.1.1
    jest: ^29.2.1 => 29.5.0
    jest-expo: ~48.0.0 => 48.0.2
    react: 18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    react-native: 0.71.7 => 0.71.7
    react-native-device-info: ^10.6.0 => 10.6.0
    react-native-gesture-handler: ~2.9.0 => 2.9.0
    react-native-reanimated: ~2.14.4 => 2.14.4
    react-native-safe-area-context: 4.5.0 => 4.5.0
    react-native-screens: ~3.20.0 => 3.20.0
    react-native-svg: ^13.9.0 => 13.9.0
    react-native-web: ~0.18.10 => 0.18.12
    react-test-renderer: 18.2.0 => 18.2.0
    tamagui: ^1.28.0 => 1.28.0
    typescript: ^4.9.4 => 4.9.5
```

**Comment by natew** [comment]
Need more info on stack setup and reproduction

**Comment by meedwire** [comment]
> Precisa de mais informações sobre configuração e reprodução de pilha

Create an expo application  with typescript.
Configure to run with expo web
Add tamagui
Create a screen with a simple button

**Comment by alitnk** [comment]
is the `TAMAGUI_TARGET` env var set?

**Comment by ceshm** [comment]
In my case setting the TAMAGUI_TARGET in the babel.config.js as
`process.env.TAMAGUI_TARGET = "native"`

was confusing me, because that var got catched so even if I later ran the sript  `"web": "TAMAGUI_TARGET=web expo start --web"`. 
I still got the issue as if I was running as native. Try running with  `TAMAGUI_TARGET=web expo start --web --clear`

**Comment by jonnigg** [comment]
@ceshm you are the best! After reading your comment, I decided to change ```process.env.TAMAGUI_TARGET = "native"``` to ```process.env.TAMAGUI_TARGET = "web"``` to test and it worked. Changed it back and it broke again. So running ```TAMAGUI_TARGET=web expo start --clear``` didn't seem to be setting the TAMAGUI_TARGET. At least I have a starting point.

**Comment by olavoasantos** [comment]
If anybody runs into this, setting the `TAMAGUI_TARGET` conditionally seems to work for me:

```js
process.env.TAMAGUI_TARGET = process.env.TAMAGUI_TARGET || 'native';
```
