### ISSUE TITLE
1st open movement of example of Sheet not working

### ISSUE THREAD

**Issue by anckaertv** [tamagui/tamagui#1212]
### Current Behavior

When we open the sheet for the first time, animation is really weird & seems like its going up to far & then gets in the right place. After, if we close it & reopen it, it's working really well.

This uses the basic example of tamagui website. Tested it with expo react native in dev build + test flight build with eas.

All tamagui packages: 1.29.6
react: 1.18.2
expo: 48.0.11
See video of behavior here :
https://github.com/tamagui/tamagui/assets/47726947/9e1e4110-d1e0-4aec-9a64-309d449624a9

### Tamagui Version

```markdown
1.29.6
```

### Reproduction

```markdown
Take the example from the website: https://tamagui.dev/docs/components/sheet/1.27.0

copy & paste it in an expo app with the version of packages mentioned above.

Reload the app, you will see that for every sheet that is opened for the first time, the animation is not the same as with the next times that you will open it.
```

**Comment by KrastanD** [comment]
I had the same issue and it wasn't related to the tamagui version but to state updates. On button click I was setting a large object in a state variable then sending that state variable to the dialog to display in a component. I assume this was causing a re-render as the sheet was opening which is what caused the jerky animation. I solved it by instead storing an index in the state variable and passing the object to the component in the dialog by indexing into an array.
