### ISSUE TITLE
Button.Icon not receiving context causing build error

### ISSUE THREAD

**Issue by la55u** [tamagui/tamagui#1235]
### Current Behavior

When using buttons with the new `createStyledContext` API I experienced a strange bug that the context is not getting passed to the Icon component. What makes it weird is that it works in dev mode when running `yarn web`.  It only happens during build (and prod). I tested this by copy-pasting the button guide code into the next-expo-solito-starter and trying to build it. The build process exits with the following error: 
```TypeError: Cannot destructure property 'size' of 'ctx' as it is null.```

This causes the button to not be usable with icons.

Any help would be appreciated. Thank you

### Expected Behavior

The context should be defined during build.

### Tamagui Version

```markdown
starter default (1.30.16)
```

### Reproduction

Minimal reproduction (see the commit history): https://github.com/la55u/tama-button-icon-bug
The CustomButton component in the above repo is the copy-paste from the button guide's full example on the top with the only exception that instead of `$md` it uses `$10` as a size.

1. Clone the repo
3. Run `yarn` and `yarn web` to confirm it works (context gets logged to console)
4. Stop `yarn web` and run `yarn web:prod`
5. You should see the TypeError during build and the context being logged as `null`

### System Info

```markdown
System:
    OS: Linux 6.2 Fedora Linux 37 (Workstation Edition)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 18.57 GB / 31.04 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 114.0b9
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.39.0 
    node-gyp: ^9.3.1 => 9.3.1 
    prettier: ^2.7.1 => 2.8.8 
    turbo: ^1.8.3 => 1.9.3 
    typescript: ^4.7.4 => 4.9.5
```

**Comment by natew** [comment]
Should be fixed in `v1.30.19` lmk
