### ISSUE TITLE
Bug: Rich Text Editor not working correctly, when using Tamagui in the same project

### ISSUE THREAD

**Issue by MarNeumann** [tamagui/tamagui#1250]
### Issue Summary:
When using Rich Text Editors in combination with the Tamagui UI Framework, pressing Enter does not create line breaks as intended. This issue is observed across multiple Rich Text Editors, including the Rich Text Editor in Lexical and another editor available in the Tamagui-Kitchen-Sink Storybook playground. Regardless of the specific editor being used, the behavior remains consistent.

### Steps to Reproduce:
Access the Tamagui-Kitchen-Sink Storybook playground.
Navigate to the section featuring a Rich Text Editor component.
Start typing in the editor.
Press Enter to create a new line or paragraph.

### Expected Behavior:
Pressing Enter should create a new line or paragraph and move the cursor to the beginning of the next line, allowing for proper organization and separation of text when using any Rich Text Editor in conjunction with the Tamagui UI Framework.

### Actual Behavior:
When pressing Enter, the cursor remains within the same line or paragraph, causing the text to continue without the expected line break. Although pressing Enter twice may visually appear to create a new paragraph, the underlying DOM structure of the document does not reflect this correctly, indicating an issue with the interaction between Rich Text Editors and the Tamagui UI Framework.

### Additional Information:
The issue is not specific to a particular Rich Text Editor and has been observed in both the Rich Text Editor plugin in Lexical and another editor available in the Tamagui-Kitchen-Sink Storybook playground.
Tamagui Version: [Specify the version of Tamagui UI Framework]
Operating System: [Specify your operating system and version]
Browser: [Specify the browser and version if applicable]
Note:
Please let me know if any additional information or clarification is required.

### Tamagui Version

```markdown
1.29.3
```

### Reproduction

```markdown
https://tamagui-extras.vercel.app/?path=/docs/richtext-tiptap-editor--documentation
```

**Comment by MarNeumann** [comment]
Lexical also provides a Tree View, where the issue is somewhat clearly observable.


https://github.com/tamagui/tamagui/assets/21364119/1614f473-819c-40a6-8959-ef3616a16186

**Comment by natew** [comment]
Can you isolate it to a specific component that is on the page that causes it?

**Comment by MarNeumann** [comment]
> Can you isolate it to a specific component that is on the page that causes it?

Removing the import `'@tamagui/core/reset.css'` in the _app.tsx fixed my issue.

**Comment by armelhbobdad** [comment]
Hi @MarNeumann. I'm looking for a maintained Rich Text Editor (Tiptap or Lexical) component for Tamagui, do you have any suggestions?
