### ISSUE TITLE
Tooltip font not showing correctly

### ISSUE THREAD

**Issue by clayrisser** [tamagui/tamagui#1257]
### Current Behavior

![2023-06-05-154928_screenshot](https://github.com/tamagui/tamagui/assets/6234038/eeea8985-7118-4222-b3a7-d9b822e30677)

### Tamagui Version

```markdown
1.30.21
```

### Reproduction

```markdown
go to https://tamagui.dev/docs/components/tooltip/1.0.0
```

**Comment by natew** [comment]
fixed
