### ISSUE TITLE
Bug: TS error when using tamagui prop type exports

### ISSUE THREAD

**Issue by nderscore** [tamagui/tamagui#1258]
### Current Behavior

Since `v1.30.21`, importing any prop types from the tamagui library which include the `style` prop results in a typescript error.

This error doesn't happen on `v1.30.20`.

I _think_ the fix is that the `RecursiveArray` interface needs to be exported from `@tamagui/web/types`

### Expected Behavior

No TS errors

### Tamagui Version

```markdown
1.30.21
```

## Given

```tsx
import { ButtonProps } from 'tamagui';

export const useButton = (propsIn: ButtonProps) => {
  return { ...propsIn };
}
```

## Result

```bash
error TS4058: Return type of exported function has or is using name 'RecursiveArray' from external module "/path/to/node_modules/@tamagui/web/types/types" but cannot be named.
```

## Workaround

Omitting the `style` prop gets rid of the error:

```tsx
const useButton = (propsIn: Omit<ButtonProps, 'style'>) => {
```

**Comment by nderscore** [comment]
This is fixed as of [v1.30.22](https://github.com/tamagui/tamagui/releases/tag/v1.30.22)

**Comment by nderscore** [comment]
This is broken again as of [v1.30.24](https://github.com/tamagui/tamagui/commit/1fe8672e3a6a5d3d78a777dea8c72f79b02a6a9c)

It looks like the fix was accidentally reverted in this commit: https://github.com/tamagui/tamagui/commit/72386b4b787776a45f6f7703344285caadf0059a

**Comment by natew** [comment]
f5c49da170aa7519d37f191d94faee8b779b83f5 should be out soon
