### ISSUE TITLE
Required tokens & themes

### ISSUE THREAD

**Issue by pcmaffey** [tamagui/tamagui#126]
First off, thanks for all your work on this! Really excellent stuff.

I created a new project using `create-tamagui-app@latest` and have been working backwards removing / changing things to learn how it fits together.

When I replace `import { themes, tokens } from '@tamagui/theme-base'` with my own themes and tokens, I get all sorts of warnings for components and style props that I'm not using.

```
...
You've passed the value "$borderColorFocus" to the style property "borderColor", but there's no theme or token with the key "$borderColorFocus". Using theme "undefined".
You've passed the value "$true" to the style property "minWidth", but there's no theme or token with the key "$true". Using theme "undefined".
...
NaN shadow NaN $4
⚠️ You've passed the value "$4" to the style property "borderRadius", but there's no theme or token with the key "$4". Using theme "undefined".
```

Do I need to use these `theme-base` definitions to use the `tamagui` package? I could switch to `tamagui/core` but I'd like to use some of the tamagui components, I just don't need all those themes and tokens.

**Environment (please complete the following information):**
 -  iOS
 - Firefox
- 1.0.1-beta.95

**Comment by natew** [comment]
@pcmaffey the minWidth one is certainly weird/wrong, are you doing `minWidth="$true"` or maybe just plain `minWidth` anywhere?

For the others, at the minimum you do need to defined all the colors * pseudos in `tamagui` themes, so:

`(background, color, shadowColor, borderColor) * (, Hover, Press, Focus)`

for each theme you make. That's sort of the magic-sauce of tamagui, and what makes it elegant. By enforcing these theme values, you can swap the entire look and feel of the UI kit. It's especially powerful with component themes, where you can customize down to each `styled()` components look and feel with themes ending in `_ComponentName` (like `_Button`).

I do want to make this all a lot easier to understand and author, and am working on a few things towards that. But for now I'd recommend either keeping things simple and defining all those properties manually for each theme, or copy/paste the logic in theme-base and just remove pieces you don't need.

**Comment by pcmaffey** [comment]
Thanks for the quick response.

> the minWidth one is certainly weird/wrong, are you doing minWidth="$true" or maybe just plain minWidth anywhere?

No, I removed all style props. I'm literally just rendering 
```
<Stack>
   <Text>test</Text>
</Stack>
```
I even switched to just `@tamagui/core` and am still getting that warning `You've passed the value "$true" to the style property "minHeight"` warning for `minWidth`, `minHeight` `height` and `width` (strangely, not maxHeight/maxWidth). Something going on in here perhaps? https://github.com/tamagui/tamagui/blob/5cef857570e32634498761d39308e2aa8d8724f9/packages/core/src/helpers/createPropMapper.ts

Ideally, it'd be great to have sensible unstyled defaults for all these values (like unstyled HTML), but I can see how that could be awkward for some of the UI components. I'll prolly just keep things simple for now and import any components directly as needed, mostly though building my own design system.

Overall, I can see you've made a lot of abstraction choices that will enable an awesome, scalable component library. And I love the extraction > flattening compilation process. I was sold when I turned off JS and your docs site still worked great.

**Comment by natew** [comment]
Any chance you can push up the repo for me to take a look?

**Comment by pcmaffey** [comment]
https://github.com/pcmaffey/tamagui-test

I created this earlier this week using `create-tamagui-app`. Only changes were scrubbing home/screen.jsx and adding custom `themes, tokens` to tamagui.config.

On build, it's outputting all the warnings for missing colors as well as the `You've passed the value "$true" to minWidth` warnings...

I also ran `upgrade:tamagui` 2 days ago and since then, have been getting the error `react__WEBPACK_IMPORTED_MODULE_1__.startTransition is not a function` in NextThemeProvider on first render.

**Comment by natew** [comment]
@pcmaffey looking it over, the startTransition is a legit but I'm pushing a fix to `@tamagui/next-theme` now, as for the rest, your tamagui.config.ts needs some love. I'd recommend forking from theme-base and then just slimming it down, because `tamagui` needs keys named in some specific ways.

**Comment by pcmaffey** [comment]
Figure it out. `tokens.space` requires a property named `true`.

**Comment by natew** [comment]
An my bad, I’ll document that.
