### ISSUE TITLE
Bug: Babel plugin chokes on solito library

### ISSUE THREAD

**Issue by nderscore** [tamagui/tamagui#1260]
After upgrading from `v1.30.19` to `v1.30.23` I started seeing a new error when trying to run the expo dev server.

It seems to be choking on some syntax in the `solito` library. I get the following error output in the terminal from the babel plugin:

```
transform[stderr]: Tamagui failed loading the pre-built tamagui.config.ts
transform[stderr]: 
transform[stderr]: Unexpected token 'export'
transform[stderr]: /path/to/node_modules/solito/link/index.js:1
transform[stderr]: export * from '../build/link'
transform[stderr]: ^^^^^^
transform[stderr]: 
transform[stderr]: SyntaxError: Unexpected token 'export'
transform[stderr]:     at Object.compileFunction (node:vm:360:18)
transform[stderr]:     at wrapSafe (node:internal/modules/cjs/loader:1084:15)
transform[stderr]:     at Module._compile (node:internal/modules/cjs/loader:1119:27)
transform[stderr]:     at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
transform[stderr]:     at Object.newLoader (/path/to/node_modules/esbuild-register/dist/node.js:2262:9)
transform[stderr]:     at Object.extensions..js (/path/to/node_modules/esbuild-register/dist/node.js:4807:24)
transform[stderr]:     at Module.load (node:internal/modules/cjs/loader:1033:32)
transform[stderr]:     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
transform[stderr]:     at Module.require (node:internal/modules/cjs/loader:1057:19)
transform[stderr]:     at Module.tamaguiRequire [as require] (/path/to/node_modules/@tamagui/static/dist/cjs/require.js:62:20)
transform[stderr]:     at require (node:internal/modules/cjs/helpers:103:18)
transform[stderr]:     at Object.<anonymous> (/path/to/packages/ui/dist/cjs/core/TextLink.js:29:19)
transform[stderr]:     at Module._compile (node:internal/modules/cjs/loader:1155:14)
transform[stderr]:     at Module._compile (/path/to/node_modules/esbuild-register/dist/node.js:2258:26)
transform[stderr]:     at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
transform[stderr]:     at Object.newLoader (/path/to/node_modules/esbuild-register/dist/node.js:2262:9)
transform[stderr]:     at Object.extensions..js (/path/to/node_modules/esbuild-register/dist/node.js:4807:24)
transform[stderr]:     at Module.load (node:internal/modules/cjs/loader:1033:32)
transform[stderr]:     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
transform[stderr]:     at Module.require (node:internal/modules/cjs/loader:1057:19)
transform[stderr]:     at Module.tamaguiRequire [as require] (/path/to/node_modules/@tamagui/static/dist/cjs/require.js:62:20)
transform[stderr]:     at require (node:internal/modules/cjs/helpers:103:18)
transform[stderr]:     at Object.<anonymous> (/path/to/packages/ui/dist/cjs/core/index.js:21:26)
transform[stderr]:     at Module._compile (node:internal/modules/cjs/loader:1155:14)
transform[stderr]:     at Module._compile (/path/to/node_modules/esbuild-register/dist/node.js:2258:26)
transform[stderr]:     at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
transform[stderr]:     at Object.newLoader (/path/to/node_modules/esbuild-register/dist/node.js:2262:9)
transform[stderr]:     at Object.extensions..js (/path/to/node_modules/esbuild-register/dist/node.js:4807:24)
transform[stderr]:     at Module.load (node:internal/modules/cjs/loader:1033:32)
transform[stderr]:     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
transform[stderr]:     at Module.require (node:internal/modules/cjs/loader:1057:19)
transform[stderr]:     at Module.tamaguiRequire [as require] (/path/to/node_modules/@tamagui/static/dist/cjs/require.js:62:20)
transform[stderr]:     at require (node:internal/modules/cjs/helpers:103:18)
transform[stderr]:     at Object.<anonymous> (/path/to/packages/ui/dist/cjs/index.js:21:25)
transform[stderr]:     at Module._compile (node:internal/modules/cjs/loader:1155:14)
transform[stderr]:     at Module._compile (/path/to/node_modules/esbuild-register/dist/node.js:2258:26)
transform[stderr]:     at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
transform[stderr]:     at Object.newLoader (/path/to/node_modules/esbuild-register/dist/node.js:2262:9)
transform[stderr]:     at Object.extensions..js (/path/to/node_modules/esbuild-register/dist/node.js:4807:24)
transform[stderr]:     at Module.load (node:internal/modules/cjs/loader:1033:32)
transform[stderr]:     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
transform[stderr]:     at Module.require (node:internal/modules/cjs/loader:1057:19)
transform[stderr]:     at Module.tamaguiRequire [as require] (/path/to/node_modules/@tamagui/static/dist/cjs/require.js:62:20)
transform[stderr]:     at require (node:internal/modules/cjs/helpers:103:18)
transform[stderr]:     at Object.<anonymous> (/path/to/apps/expo/tamagui.config.ts:24:17)
transform[stderr]:     at Module._compile (node:internal/modules/cjs/loader:1155:14)
transform[stderr]:     at Module._compile (/path/to/node_modules/esbuild-register/dist/node.js:2258:26)
transform[stderr]:     at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
transform[stderr]:     at Object.newLoader [as .ts] (/path/to/node_modules/esbuild-register/dist/node.js:2262:9)
transform[stderr]:     at Module.load (node:internal/modules/cjs/loader:1033:32)
transform[stderr]: 
transform[stderr]: You can see if it loads in the node repl:
transform[stderr]: 
transform[stderr]: require("./solito/link").default
```

**Comment by natew** [comment]
We stopped silently quieting errors to avoid lots of confusion, so this probably existed before but was silently ignored.

Reproduction?

**Comment by nderscore** [comment]
Dig a little more digging on this today. A minimal reproduction can be found here: https://gist.github.com/nderscore/6c5bdd04b844414c73b9e41a738556dc

As far as I can tell, the issue is related to esm `export * from ...` syntax in `.js` files.

In my own babel config for native, I already have this plugin installed: 

https://babeljs.io/docs/babel-plugin-transform-export-namespace-from

Without knowing too much about the internals of `@tamagui/static`, I made a naive attempt to fix this by adding `'exportNamespaceFrom'` to the [list of babel plugins inside `extractor/babelParse.ts`](https://github.com/tamagui/tamagui/blob/master/packages/static/src/extractor/babelParse.ts#L4), but that didn't seem to make any difference.

**Comment by nandorojo** [comment]
Interesting that this caused that issue. I believe [babel-plugin-transform-export-namespace-from](https://babeljs.io/docs/babel-plugin-transform-export-namespace-from) is for `export * as` not `export * from`, which should just work with any native config.

**Comment by nderscore** [comment]
> I think the * export is a red herring. The error comes from the export keyword itself.

Yeah, I think the real issue is having a dependency that uses _any_ ESM import/export syntax but not an `.mjs` file extension. Running `foo = require('solito/router')` in a bare instance of node throws the same error.

Since `solito` expects to be a transpiled dependency, this normally isn't an issue. But if a tamagui UI library (`@my/ui`) imports it, the static extraction plugin breaks. It seems like it isn't transpiling dependencies maybe?

> Does disabling the Tamagui Babel plugin fix this?

Yeah, the error is specifically coming from the plugin. Removing the plugin or removing the import of solito from my ui library resolves the error.

**Comment by benschac** [comment]
I ran into this issue with `expo-constants` as well.

**Comment by natew** [comment]
There is no `1.30.23` btw would be helpful to know which version it broke in exactly.

**Comment by natew** [comment]
We did start showing errors in the pre-bundle that before we just sent to /dev/null unless you added a flag, so could be there. Reason is because we just throw in a proxy around the module if we can't bundle it and it usually works anyway. I need to find a good balance...

**Comment by natew** [comment]
Tried to add the latest solito + expo-constants and it works for me: f486e49ac

**Comment by natew** [comment]
If someone can set up the failure using the kitchen-sink / sandbox-ui setup (just `yarn sandbox` to run it and it uses `packages/sandbox-ui` as the test ui package.

**Comment by itsnayeem** [comment]
Getting the same errors in my app as well.

I ran kitchen sink after adding `"kitchen-sink:ios": "yarn workspace @tamagui/kitchen-sink ios",` to the root package.json and was able to produce some of the same errors: https://gist.github.com/itsnayeem/06745f93cb18d7b73a690219a20e7550

Hopefully this helps

**Comment by natew** [comment]
Cleaned this up a bunch in v1.32.1:

- Made it just warn a short warning
- Only warns once per module
- ENV to ignore all
- ENV to ignore specific ones
- ENV to show full error
- Added a whitelist to automatically ignore known fine modules like solito

It links to the docs when it shows the warning. 

Let me know if it works.
