### ISSUE TITLE
AnimatePresence not working as intended

### ISSUE THREAD

**Issue by andrewkucz** [tamagui/tamagui#1269]
### Current Behavior

With both `@tamagui/animations-react-native` and `@tamagui/animations-reanimated` I'm seeing unexpected behavior when trying to use the AnimatePresence component.

For one driver the box does not animated and grows and shrinks abruptly and for the other it doesn't change at all. See demo videos below. In addition,  with the animations-react-native driver, the box will sometimes disappear after a short time.

https://github.com/tamagui/tamagui/assets/13070523/82f90992-1c9c-40f1-a3c4-c04c07f2c6ff

https://github.com/tamagui/tamagui/assets/13070523/f1d8409c-771f-4739-92a8-01ab294054d8

### Expected Behavior

I expect the square to grow and shrink in an animated spring "bouncy" way, 

### Tamagui Version

```markdown
1.31.2
```

### Reproduction

```markdown
Init'ed a new expo repo, followed all the installation and expo docs on tamagui.dev

Added a simple AnimatePresence component like the example in the docs.

https://github.com/andrewkucz/tamagui-animation-test
```

### System Info

```markdown
Tested on both Mac with iOS simulator and Windows Android emulator

---

  System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 3.90 GB / 15.93 GB
  Binaries:
    Node: 18.12.1 - ~\.nvm\versions\node\v18.12.1\bin\node.EXE
    npm: 8.19.2 - ~\.nvm\versions\node\v18.12.1\bin\npm.CMD
  Browsers:
    Chrome: 114.0.5735.110
    Edge: Spartan (44.22621.1702.0), Chromium (114.0.1823.41)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @babel/core: ^7.20.0 => 7.22.1
    @tamagui/animations-react-native: ^1.31.2 => 1.31.2
    @tamagui/animations-reanimated: ^1.31.2 => 1.31.2
    @tamagui/babel-plugin: ^1.31.2 => 1.31.2
    @tamagui/config: ^1.31.2 => 1.31.2
    @tamagui/font-inter: ^1.31.2 => 1.31.2
    @tamagui/theme-base: ^1.31.2 => 1.31.2
    @types/react: ~18.0.14 => 18.0.38
    babel-plugin-transform-inline-environment-variables: ^0.4.4 => 0.4.4

    expo: ~48.0.18 => 48.0.19
    expo-font: ^11.1.1 => 11.1.1
    expo-status-bar: ~1.4.4 => 1.4.4
    react: 18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
    react-native-reanimated: ~2.14.4 => 2.14.4
    react-native-web: ^0.19.4 => 0.19.4
    tamagui: ^1.31.2 => 1.31.2
    typescript: ^4.9.4 => 4.9.5
```

**Comment by benschac** [comment]
https://github.com/tamagui/tamagui/pull/1223

I was able to get reanimated working in the starter. I need to fix up the PR and get it merged. Hopefully, the configuration in the PR can help get animations working on your end. Just tried my PR on my Android test device and it was working as expected.

**Comment by natew** [comment]
there's also the moti driver, undocumented but you can test it out `@tamaguji/animations-moti` which uses reanimated under the hood

**Comment by natew** [comment]
moti driver is out, lmk if still an issue
