### ISSUE TITLE
Select component is not customisable

### ISSUE THREAD

**Issue by dheerajneelam-sigfyn** [tamagui/tamagui#1294]
### Current Behavior

First of all, thanks for creating such a wonderful library.
So, I can't customise the native Select field. I tried giving styles to Select.Group and Select.Item, but it's not taking any of them.
For example, this code
```
import React from 'react';
import { Select, SelectProps } from 'tamagui';

function CustomSelect(props: SelectProps & { val: string; setVal: any }) {
	const { val, setVal, ...rest } = props;
	const items = ['Apple', 'Pear', 'Mango'];
	return (
		<Select value={val} onValueChange={setVal} native {...rest}>
			<Select.Content>
				<Select.Group>
					{items.map((item, i) => {
						return (
							<Select.Item index={i} key={item} value={item}>
								<Select.ItemText>{item}</Select.ItemText>
							</Select.Item>
						);
					})}
				</Select.Group>
			</Select.Content>
		</Select>
	);
}

export default CustomSelect;
```
will result in this:
![image](https://github.com/tamagui/tamagui/assets/94339923/937cdb90-eec4-42b3-a5c3-8a045a36b646)
![image](https://github.com/tamagui/tamagui/assets/94339923/60cbb9f0-4c78-4b9b-b031-a5e8dd715407)

Now when I try to give a width, height or background color to either Select.Group or Select.Item, it doesn't work. 

And as per the docs, I noticed that Select.Item extends ListItem and it takes hardcoded tokens like $background for background color.  I noticed that it has something to do with https://github.com/tamagui/tamagui/issues/941. 

When I change the color code of $background in theme config, I was able to change the background color. But I was expecting it to respect the props like every other components.

### Expected Behavior

Select component should take in-line styles like backgroundColor, width, height, textual props like font sizes, font colors etc., and reflect it when it is rendered.

### Tamagui Version

```markdown
1.30.18
```

### Reproduction

```markdown
Take the code I posted in the "Current Behaviour" section or create a Select component from tamagui with native behaviour and try to customise the styles.
```

**Comment by natew** [comment]
When using `native` it won't let you customize the sub-components, only if you avoid the native prop will it. We could clarify this better in docs..
