### ISSUE TITLE
On Long Press is missing on Stack component

### ISSUE THREAD

**Issue by maylukas** [tamagui/tamagui#1295]
### Current Behavior

onLongPress is not exposed by the Stack component

### Expected Behavior

Shall be exposed if it is supposed to be used as a pressable replacement on react-native

### Tamagui Version

```markdown
1.33.2
```

### Reproduction

```markdown
Create a Stack component and try to set the onLongPress prop :)
```

**Comment by mojavad** [comment]
Came here to make the exact same issue 😅

**Comment by hackily** [comment]
I am running into this issue as well

**Comment by mojavad** [comment]
Created a PR for this: https://github.com/tamagui/tamagui/pull/1334

**Comment by mojavad** [comment]
@maylukas & @hackily - this has now been merged into the latest version of Tamagui

**Comment by natew** [comment]
btw this only works on native i believe, on web it just defers to a press (but i think we could make it work by using pressable in core)
