### ISSUE TITLE
Animation prop changing the anchor tag on web

### ISSUE THREAD

**Issue by alitnk** [tamagui/tamagui#1310]
> If I do `<View href="" animation="quick" ... />`, on web it renders a `div`. Once I remove the `animation` it gets fixed and renders `a`. Setting `tag='a'` didn't change anything. Perhaps this is expected, just thought I'd flag it.
> setting `accessibilityRole="link"` didn't help, but `tag="a"` did once I removed the animation

Reported by @nandorojo on Discord

Shouldn't be hard to fix - I believe we set the `View` of the on web to be a div. So, may need to first check the current tag of the element and then default to div.

**Comment by TimPetricola** [comment]
@alitnk any news on this one? 🙂 We're having the same issue, preventing us from using animation for links on web

**Comment by natew** [comment]
this is actually determined by the animation view which is react-native-web, which doesn't allow changing tag unfortunately:

https://stackoverflow.com/questions/60217769/react-native-web-control-the-html-tag-generated-by-view

closest you can get is accessibilityRole, or using CSS driver.

we could add this in react native web lite but i don't plan on supporting it in the future so best strategy maybe either just wrapping it or asking on RNW repo

**Comment by nandorojo** [comment]
@natew does adding the animation tag cause it to use the RNW view? if so, then that makes sense, though i’ve never faced this issue with RNW (passing it an href with accessibility role makes it an a usually)

**Comment by natew** [comment]
Yea you’d just need to set the accessibility role so it makes rnw change the tag

**Comment by natew** [comment]
Which does make me think maybe we could avoid the whole rnw view altogether somehow and really speed up animated views.

**Comment by nandorojo** [comment]
it’s weird though because i am setting the role here
