### ISSUE TITLE
[Bug] Sheets don't respect theme change. Can be reproduced on tamagui.dev site.

### ISSUE THREAD

**Issue by stoickeyboard** [tamagui/tamagui#1319]
### Current Behavior

When you open a sheet after changing the theme, the new theme colors are not shown, instead the previous theme colors are shown.

### Expected Behavior

I'd expect sheets to show the current theme colors

### Tamagui Version

```markdown
1.35.6
```

### Reproduction

```markdown
This can be reproduced on tamagui.dev

1. Go to sheet section on tamagui.dev
2. Open the sheet to see that it is the color of the current theme
3. Hover over a different colored letter on the top TAMAGUI Header Title to change theme color
4. Observe that the sheet doesn't show the new theme color

I noticed this after upgrading from 1.23.0 to 1.35.6 if that helps at all
```

**Comment by kzlar** [comment]
Seeing this as well:
https://discord.com/channels/909986013848412191/974145843919716412/1122672189485891635

**Comment by natew** [comment]
Should be fixed in v1.36.3 lmk if working for you

**Comment by timothymiller** [comment]
I'm experiencing this bug on `1.68.2`, unfortunately.

**Comment by timothymiller** [comment]
FWIW I think it's worth re-investigating this issue. It seems theme updates are toooo granular, haha.
https://github.com/timothymiller/t4-app/issues/81
