### ISSUE TITLE
Select doesn't include crucial functionality

### ISSUE THREAD

**Issue by matthewhausman** [tamagui/tamagui#1323]
### Current Behavior

The select component isn't useful for data that may not have unique display names. Say we have a list of warehouses. 

```
warehouses = [
    {
        name: 'Koreatown Warehouse',
        address: 'Los Angeles'
    },
    {
       name: 'Koreatown Warehouse',
       address: 'New York'
    }
]
```

The current state of the select component would make it impossible to use with data like this. 

If you look at this select api, it is much more useful https://v2.vuetifyjs.com/en/api/v-select/#props-items

Items can be passed as an array of objects and user can choose which field will be displayed, and can have a custom key for each row

### Expected Behavior

described above sorry

### Tamagui Version

```markdown
not exactly important
```

### Reproduction

```markdown
not relevant
```

### System Info

```markdown
not relevant
```

**Comment by cat-turner** [comment]
I concur
