### ISSUE TITLE
Disabled flag on Input does not work

### ISSUE THREAD

**Issue by JonLatane** [tamagui/tamagui#1327]
I'm happy to investigate this myself! But before doing so, figured I should create an issue. If you'd like me to take it on, just assign it to me. I'm using Tamagui for [one of the frontends to my AGPL social media app, Jonline](https://github.com/JonLatane/jonline/tree/main/frontends/tamagui), and enjoy contributing back. I've also contributed to [rocket_async_compression](https://github.com/Ameobea/rocket_async_compression) in furtherance of this project 🙂 But I'm also relatively new to frontend dev vs. backend dev, and so could just not be using Tamagui correctly! But I seem to be able to reproduce this from a starter repo.

(I have not tested in the regular web starter.)

### Current Behavior

1. Create the starter app (Expo+Next).
2. Paste `<Input disabled={true} placeholder="Type something..." />` into the `home/screen.tsx` file (and `Input,` into the `import {...} from '@my/ui'` of course).
3. Fire up the server (`yarn web`)

The input is not disabled. Futher, I seem to see client-side errors stemming from the `onTextChanged` callbeing being made when it shouldn't be.

### Expected Behavior

The input should be disabled.

### Tamagui Version

```markdown
1.35.8
```

### Reproduction

```markdown
I honestly can't get this thing to log me in with Google or GitHub. Again:

1. Create the starter app.
2. Paste `<Input disabled={true} placeholder="Type something..." />` into the `home/screen.tsx` file. (Also add `Input,` to the `import {...} from '@my/ui'`)
3. Fire up the server.
```

### System Info

```markdown
System:
    OS: macOS 13.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 467.32 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.3.0 - ~/.nvm/versions/node/v19.3.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.3.0/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v19.3.0/bin/npm
  Browsers:
    Brave Browser: 110.1.48.158
    Chrome: 114.0.5735.133
    Safari: 16.5
```

**Comment by megacherry** [comment]
Hi @JonLatane,

try it like that:

```
<Input editable={false} placeholder="Type something..." />
```

Andy

**Comment by JonLatane** [comment]
@megacherry This works! However, `disabled` is the parameter for `Button`, `Switch`, etc., so this API seems inconsistent. Would there be any opposition to me adding a PR to add `disabled` as an alias for `editable` on `Input` elements? Happy to do so 🙂

**Comment by natew** [comment]
Depends on how we want it to work. Probably we shouldn't have added disabled, (is it on switch, perhaps extending themeablestack). The web does have a disabled state that we could technically implement as a pseudo style like `disabledStyle`. Not sure what's best.

**Comment by natew** [comment]
sets editable=false in next release
