### ISSUE TITLE
Input component's testID prop does not map to data-testid

### ISSUE THREAD

**Issue by hackily** [tamagui/tamagui#1329]
### Current Behavior

The input component's `testID` prop does not map to `data-testid`
If I provide the prop directly to the component as `data-testid`, in a production build, this prop doesn't forward to the final component.

My e2e tests are failing, as they rely on test id.

### Expected Behavior

The `testID` prop should map to `data-testid` in all components

### Tamagui Version

```markdown
1.35.12
```

### Reproduction

```markdown
https://codesandbox.io/p/sandbox/sharp-sanne-pxgysy?file=%2Fpackages%2Fapp%2Ffeatures%2Fhome%2Fscreen.tsx%3A26%2C85
```

**Comment by natew** [comment]
fix in next release

**Comment by kpoelhekke** [comment]
I'm still experiencing this issue on `1.93.3`.  `testID` is forwarded for dev builds, but is removed on production builds. Hence all E2E tests depending on it fail.
