### ISSUE TITLE
Removing sandbox-web broke Vite documentation

### ISSUE THREAD

**Issue by ryan0x44** [tamagui/tamagui#1346]
### Current Behavior

When you visit https://tamagui.dev/docs/guides/vite there's a broken link

> For a full-featured example, you can reference [the experimental tamagui.dev site written using vite](https://github.com/tamagui/tamagui/tree/master/apps/sandbox-web).

( `https://github.com/tamagui/tamagui/tree/master/apps/sandbox-web` )

It appears commit 958de216da59d87c19b0f14f58a7ed639efe7007 from PR #952 removed sandbox-web.

### Tamagui Version

```markdown
Latest (v1.36.4)
```

**Comment by natew** [comment]
fixed
