### ISSUE TITLE
Popovers adapted as sheets on iOS do not open

### ISSUE THREAD

**Issue by kzlar** [tamagui/tamagui#1347]
### Current Behavior

Under certain scenarios (repro below), even though the internal state of the sheet says "open: true", the sheet itself does not appear.
From what I can tell, to get into this scenario, you need a list of components (where each has a popover as a child) and you need to remove components from that list until you hit the repro. One interesting point is that the issue only happens with modal sheets.
Discord msg: https://discord.com/channels/909986013848412191/974145843919716412/1123423873153642606

### Expected Behavior

Sheet should appear

### Tamagui Version

```markdown
1.36.3
```

### Reproduction

```markdown
function Test2(props: { v: string; remove: () => void }) {
  return (
    <Popover>
      <Popover.Trigger asChild>
        <Text fontSize={'$8'}>{props.v}</Text>
      </Popover.Trigger>
      <Popover.Adapt platform="touch">
        <Popover.Sheet modal>
          <Popover.Sheet.Overlay />
          <Popover.Sheet.Frame padding="$4">
            <Popover.Adapt.Contents />
          </Popover.Sheet.Frame>
        </Popover.Sheet>
      </Popover.Adapt>
      <Popover.Content>
        <Popover.Close asChild>
          <Button onPress={props.remove}>
            <Button.Text textAlign="center">Remove</Button.Text>
          </Button>
        </Popover.Close>
      </Popover.Content>
    </Popover>
  )
}

function Test() {
  const [state, setState] = useState<string[]>(['Click me', 'Click me'])
  const add = useEvent(() => {
    setState((prev) => {
      const next = [...prev, 'Click me']
      return next
    })
  })
  const remove = useEvent(() => {
    setState((prev) => {
      const next = [...prev]
      next.pop()
      return next
    })
  })
  return (
    <YStack justifyContent="center" flex={1} alignContent="center">
      <YStack h="50%" gap="$3">
        {state.map((v, i) => {
          return <Test2 key={i} v={v} remove={remove} />
        })}
      </YStack>
      <Button onPress={add}>
        <Button.Text>Add</Button.Text>
      </Button>
    </YStack>
  )
}
```
Run this under a tamagui provider, click one of the "click me" to open a modal sheet and click "remove". You'll then notice you can't click the other "click me" for some reason! What's weirder is that if you try to inspect the app (w/ flipper), click "click me" and look at the sheet context, you'll see that the props do toggle, but visually nothing happens! So something else is preventing the sheet from being shown.
```


### System Info

_No response_

**Comment by TheEhsanSarshar** [comment]
this issue happens because of nested portals
can you check this
add a custom name for sheet portal
```
<Popover.Sheet
    portalProps={{host: "mysheet"}}
```

**Comment by natew** [comment]
@TheEhsanSarshar could we make it so popovers create a new host name in their context?

**Comment by TheEhsanSarshar** [comment]
@natew yea that's the way to fix this maybe using `useId()`.
I need to test it on an App that I'm working on
it was working perfectly as I tested it in kitchen-sink
anyway I'll create a PR to not lose the track

**Comment by TheEhsanSarshar** [comment]
oh actually the problem is something else, working on it ...

**Comment by TheEhsanSarshar** [comment]
ok, I got a fix it was actually an issue with context not passing down.
I've tested that on Android and web, can you please test it on ios

**Comment by kzlar** [comment]
@TheEhsanSarshar appreciate you taking the time to look into this!
Unfortunately, it doesn't seem to fix it with the repro I used above, at least on iOS on tamagui 1.39.5

**Comment by TheEhsanSarshar** [comment]
@kzlar is it the same behaviour ? can you share a video

**Comment by kzlar** [comment]
Yeah same behavior, after you add and remove labels, the last "Click me" is un-clickable
