### ISSUE TITLE
Skipping loading of ./CustomToast and expo-constants in starter monorepo

### ISSUE THREAD

**Issue by RobJacobson** [tamagui/tamagui#1356]
### Current Behavior

When I create a sample monorepo app using `npm create tamagui@latest`, open with `yarn native`, and open with Expo on Android or iOS, the terminal shows these error messages:

`Tamagui Warning [001]: Skipping loading ./CustomToast due to error bundling.`
`Tamagui Warning [001]: Skipping loading expo-constants due to error bundling.`

The package opens the sample project, but the toast message does not appear.

Everything works fine with web.

### Expected Behavior

The toast message should display. Ideally, these warnings shouldn't appear for an out-of-the-box installation.

### Tamagui Version

```markdown
1.36.6
```

### Reproduction

```markdown
Steps to reproduce:
1. Run `npm create tamagui@latest` and create a sample monorepo project.
2. Run `yarn native`
3. Open with Expo in Android or iOS
```

### System Info

```markdown
System:
    OS: Linux 5.15 Zorin OS 16.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 7.19 GB / 15.48 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 20.1.0 - ~/.nvm/versions/node/v20.1.0/bin/node
    Yarn: 3.5.0 - /usr/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v20.1.0/bin/npm
    pnpm: 8.3.1 - /usr/bin/pnpm
  Browsers:
    Brave Browser: 114.1.52.129
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.22.5 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.3.0 
    eslint: ^8.21.0 => 8.43.0 
    node-gyp: ^9.3.1 => 9.4.0 
    prettier: ^2.7.1 => 2.8.8 
    turbo: ^1.10.3 => 1.10.6 
    typescript: ^5.1.3 => 5.1.6
```

**Comment by natew** [comment]
@alitnk this just needs a build?

**Comment by alitnk** [comment]
@natew both are essentially coming from `expo-constants` and boil down to `Cannot use import statement outside a module` - tried on both expo go and dev build but no difference

**Comment by natew** [comment]
quieted this confusing warning by default now
