### ISSUE TITLE
[Feature] Lucide icons default to the color black, but defaulting to $color would allow better support for dark mode

### ISSUE THREAD

**Issue by mphill** [tamagui/tamagui#1360]
It appears that colors need to be manually applied to Lucide icons, they rely on a hardcoded value of "black" unless color is passed in.

Using $color would allow for icons to work on dark-themed modes out of the box without having additional props passed to icons.

**Comment by juniorogaa** [comment]
The same for me.

**Comment by natew** [comment]
fixed in v1.39.2
