### ISSUE TITLE
Support for Reanimated 3

### ISSUE THREAD

**Issue by mc-petry** [tamagui/tamagui#1363]
### Current Behavior

I tried [Expo 49](https://blog.expo.dev/expo-sdk-49-beta-is-now-available-6373e78f8624) which comes with Reanimated 3. So the tanimations from the docs won't work.

### Expected Behavior

Animations with Reanimated 3 should work

### Tamagui Version

```markdown
1.36.6
```

### Reproduction

```markdown
Just use example section from the docs: https://tamagui.dev/docs/core/animations#animatepresence-and-exitstyle
```

**Comment by natew** [comment]
they do work, i've tested them just today using the moti driver (new docs from today). lmk more specifically what doesnt work

**Comment by alariej** [comment]
Looks like web support is broken for react-native-reanimated v3.4.2. Getting:

`[ERROR] No matching export in "node_modules/react-native-reanimated/lib/module/reanimated2/animation/decay.js" for import "WithDecayConfig"`

when running `yarn web`

v3.4.1 works.

**Comment by natew** [comment]
they are fixing it in 3.4 https://github.com/software-mansion/react-native-reanimated/issues/4645#issuecomment-1671875388
