### ISSUE TITLE
undefined is not a function.    import_react.useSyncExternalStore

### ISSUE THREAD

**Issue by themarufsharifi** [tamagui/tamagui#1364]
### Current Behavior

I followed the docs and got setup the tamagui for react native but when i run the android app it gives me following error

 ERROR  TypeError: undefined is not a function (near '...(0, import_react.useSyncExternalStore)...')
This error is located at:
    in Unknown (at App.tsx:13)
    in PortalProvider
    in _Theme (created by _ThemeProvider)
    in _ThemeProvider (created by _TamaguiProvider)
    in _TamaguiProvider
    in Unknown (at App.tsx:12)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in main(RootComponent) (at renderApplication.js:60)

### Expected Behavior

I expect it to work properly 

### Tamagui Version

```markdown
"react-native": "0.66.4",
"tamagui": "^1.36.6",
"react": "17.0.2",
```

### Reproduction

```markdown
Try to use tamagui with following configurations

//babel.config.js

process.env.TAMAGUI_TARGET = 'native'

module.exports = {
  plugins: [
    ['transform-inline-environment-variables', {
      include: ['TAMAGUI_TARGET']
    }]
  ]
}



//tamagui.config.ts

import { shorthands } from '@tamagui/shorthands'
import { themes, tokens } from '@tamagui/themes'
import {createMedia} from '@tamagui/react-native-media-driver'
import { createFont, createTamagui } from 'tamagui'
export default createTamagui({
  media: createMedia({
        xs: { maxWidth: 660 },
        // ...
  }),
  themes,
  tokens,
  shorthands,
  fonts: {
    body: createFont({
      family: 'Arial',
      size: {
        4: 14,
      },
      lineHeight: {
        4: 16,
      },
    }),
  },
})



// App.tsx


/* eslint-disable jsx-a11y/accessible-emoji */
import React from 'react';
import { TamaguiProvider, View } from 'tamagui'
import config from '../../tamagui.config'



const App = () => {


  return (
    <TamaguiProvider config={config}>
      <View></View>
  </TamaguiProvider>
 
  );
};


export default App;
```

**Comment by mphill** [comment]
Try to add this to your bable file:

```js
[
      '@tamagui/babel-plugin',
      {
        components: ['tamagui'],
        config: './tamagui.config.ts',
        importsWhitelist: ['constants.js', 'colors.js'],
        logTimings: true,
        disableExtraction: process.env.NODE_ENV === 'development',
      }
    ],
```


Based on https://tamagui.dev/docs/intro/compiler-install#babel--metro

Looks like your mobile app thinks its a website.

**Comment by natew** [comment]
You need at least React 18, or to `import '@tamagui/react-17-patch'` which isn't guaranteed to work
