### ISSUE TITLE
Enter key in textarea doesn't work properly

### ISSUE THREAD

**Issue by loveholly** [tamagui/tamagui#1370]
### Current Behavior

When you press down `Enter` key in a textarea, it only shows a space

### Expected Behavior

It should display a new line in textarea when `Enter` key pressed down.

### Tamagui Version

```markdown
1.36.6
```

### Reproduction

```markdown
https://tamagui.dev/docs/components/inputs
```

**Comment by TheEhsanSarshar** [comment]
do you mean it adds a space instead of moving to a new line?
I don't know but it works as expected for me

**Comment by loveholly** [comment]
> RE: do you mean it adds a space instead of moving to a new line?

Yes. 

> RE: I don't know but it works as expected for me

Seems like that it works well on Chrome, but failed on Firefox.

**Comment by TheEhsanSarshar** [comment]
@loveholly thanks for reporting.

**Comment by natew** [comment]
its fixed in latest
