### ISSUE TITLE
Styled buttons in 1.37.0 not correctly applying properties

### ISSUE THREAD

**Issue by mphill** [tamagui/tamagui#1373]
### Current Behavior

Buttons that are built from `styled` do not appear to render correctly, seems like the flexDirection row property is missing with other styling properties.

The top is a styled button, the bottom is stock.
<img width="401" alt="image" src="https://github.com/tamagui/tamagui/assets/2466039/3a01d357-d395-4c95-948c-890f18705d99">

This styled button has no styling applied.

### Expected Behavior

Buttons should look the same as 1.36.6

### Tamagui Version

```markdown
1.37.0

was working in 1.36.6
```

### Reproduction

```markdown
import {Button as TButton } from "tamagui";
import { Button } from "../primatives/buttons"; // use any styled button, doesn't matter.

				<YStack space>
					<Button icon={<Play />} iconAfter={<Play />}> 
						Play
					</Button>

					<TButton icon={<Play />} iconAfter={<Play />}>
						Play
					</TButton>
				</YStack>
```
```


### System Info

_No response_

**Comment by natew** [comment]
Please add repro
