### ISSUE TITLE
Bug with non-native Select component

### ISSUE THREAD

**Issue by NavyAnt24** [tamagui/tamagui#1392]
When testing out the Select component on Firefox on web, there appears to be a bug whereby after clicking outside of options after first opening the menu, the values no longer stay open upon subsequent clicks.

If Firefox is not intended to be fully supported, we can close this issue.

https://github.com/tamagui/tamagui/assets/4275598/7ea86e1e-decb-4719-b7f3-535f7ded1e3d

**Comment by TheEhsanSarshar** [comment]
I'll see that on weekend if no one fix it till then, I guess it might be something related to event propagation or focus

**Comment by la55u** [comment]
Related: https://github.com/tamagui/tamagui/issues/1058
