### ISSUE TITLE
Popover allows pressing even when closed

### ISSUE THREAD

**Issue by juniorogaa** [tamagui/tamagui#1396]
### Current Behavior

When I open Popover and close it, when I click again instead of closing, it performs the action again. It seems that there is a delay until it actually closes.

![Popover](https://github.com/tamagui/tamagui/assets/96478892/6421dc8f-a756-4740-88b5-9570539dd74b)
![Popover2](https://github.com/tamagui/tamagui/assets/96478892/462d2928-f23d-4e36-b9eb-5a98d6adcbc4)

### Expected Behavior

Close Popover instantly

### Tamagui Version

```markdown
1.39.1
```

### Reproduction

```markdown
In the example of the documentation it is possible to test.

https://tamagui.dev/docs/components/popover/1.0.0
```

**Comment by juniorogaa** [comment]
It's the animation delay to close. I left the opacity always visible to test, and it really goes up and then closes.

![Popover3](https://github.com/tamagui/tamagui/assets/96478892/8b5b0e61-ca59-43b8-abba-cbc1d3f23a99)

**Comment by natew** [comment]
Yea we need to disable pointer events immediately, @alitnk this should be a quick win.
