### ISSUE TITLE
Dripsy import

### ISSUE THREAD

**Issue by nandorojo** [tamagui/tamagui#14]
https://github.com/tamagui/tamagui/blob/3c9d4f59ec541058426844d1591199d123ebdccc/packages/benchmarks/bench/drispy/index.tsx#L1

super cool! I think this View should be imported from RN though, rather than a recursive `styled` call (I have to update Dripsy docs for this)

**Comment by natew** [comment]
Thanks, should be fixed now I'll re-run benchmarks.
