### ISSUE TITLE
input without default style after update

### ISSUE THREAD

**Issue by juniorogaa** [tamagui/tamagui#1400]
### Current Behavior

input without default style after update

Before

<img width="329" alt="image" src="https://github.com/tamagui/tamagui/assets/96478892/98a00595-3498-420d-9258-b6a33ff9edd1">

After

<img width="307" alt="image" src="https://github.com/tamagui/tamagui/assets/96478892/84f66b17-9efa-4d70-9e54-6861265bf151">

### Expected Behavior

input with default style

### Tamagui Version

```markdown
1.39.3
```

### Reproduction

```markdown
Put an input on the screen, and see that it has no default style
```

**Comment by natew** [comment]
Needs platform and repro, not seeing it myself
