### ISSUE TITLE
switch thumb with black color by default

### ISSUE THREAD

**Issue by juniorogaa** [tamagui/tamagui#1401]
### Current Behavior

after updating tamagui, the thumb switch started to come with a black color by default. Even setting the background color, it looks like it turns black.

<img width="305" alt="image" src="https://github.com/tamagui/tamagui/assets/96478892/1c8a9a74-bd92-4583-b59c-8cfee410ae38">

### Expected Behavior

the background color is a light gray, but when placed in the thumb it turns black.

### Tamagui Version

```markdown
1.39.3
```

### Reproduction

```markdown
Put a switch on the screen and see the default color.
```

**Comment by natew** [comment]
No platform info no repro
