### ISSUE TITLE
Tamagui Expo template build broke when trying to import local image file from `packages`

### ISSUE THREAD

**Issue by t18n** [tamagui/tamagui#1412]
### Current Behavior

I tried to use local file with Solito image as per the [documentation](https://solito.dev/usage/image#local-files) and it broke my build.
![Broken build](https://github.com/tamagui/tamagui/assets/14198542/3755643e-4a56-45a1-8b39-aa866a223bf9)

The build returns so many errors and eventually resulted in the page being loaded
![image](https://github.com/tamagui/tamagui/assets/14198542/7a60b89c-ca35-4163-8dcc-1c32dadf9ccc)

there are also many node processes spawned and cannot be killed with Ctrl+C
![Many node process](https://github.com/tamagui/tamagui/assets/14198542/6e1f3c11-75c3-4c0d-aedd-a38dc7cca2ef)

Please see the reproduction in `packages/ui/src/components/image/image.tsx` file in the repo below.

### Expected Behavior

Local images should be loaded when import a component from `ui` or `app` to `next app.

### Tamagui Version

```markdown
"@tamagui/core": 1.39.6
```

### Reproduction

```markdown
https://github.com/t18n/repro-tamagui-expo-next-solito
```

**Comment by t18n** [comment]
Apparently, the issue occured only from the components in the `ui` package, aka `import testimage from '../assets/test.png';`. The `import icon from '../../assets/icon.png'` from `app/features` works fine.

**Comment by natew** [comment]
Yes in general if these issues come up you can move your components up to features, as UI should mostly be styled components, we've also added a few more things to help avoid these errors in ui builds since.

**Comment by MiguelValdez-mv** [comment]
Hello, I have the same error. I would like to know if there is another alternative to solve it.

I find it very difficult to use `.png` or `.jpg` files only in `packages/app` because most of the components or features are implemented (at the interface level) in `packages/ui`. In other words, to implement the solution you propose, I would need to make a very big change in my project 😅

@natew
