### ISSUE TITLE
Modal Sheet on Mobile not showing the full

### ISSUE THREAD

**Issue by rayliao** [tamagui/tamagui#1414]
If I have content at the bottom, I won't see it.  I just created a new one, changed snapPoints to 50, and nothing else

tamagui version: latest

<img width="492" alt="image" src="https://github.com/tamagui/tamagui/assets/5601068/3247219a-2df4-4ff9-b04e-505bc48efbd8">

<img width="1001" alt="image" src="https://github.com/tamagui/tamagui/assets/5601068/eb3f7e23-27d0-48e9-9f0a-901a95925f48">

**Comment by natew** [comment]
check latest
