### ISSUE TITLE
Button doesn't increase its size to fit its content

### ISSUE THREAD

**Issue by liebharc** [tamagui/tamagui#1417]
### Current Behavior

Hi,

We just migrated our app to tamagui and really like this library ♥. There is one thing which we noticed however: If the text inside a button gets long, then the button height doesn't increase anymore and the text is rendered outside the button:

![grafik](https://github.com/tamagui/tamagui/assets/544520/fb038a31-33a4-4a75-b161-e3532fb24ed6)

In plain react-native the button would get larger as well to always fit its content. 

This issue could very likely be something we do wrong and not a bug. But since we failed to understand how to change this behavior, we've decided to open this issue.

Things I tried:

- Try various properties to make the button scale, most noteworthy max-height and flex options
- Read the button documentation on tamagui.dev 
- Searched for a similar issue report here on Github
- Considered making a custom button according to https://tamagui.dev/docs/guides/how-to-build-a-button , but thought it's worth asking here first
- Checked the tamagui source code for hints at https://github.com/tamagui/tamagui/blob/master/packages/button/src/Button.tsx

### Expected Behavior

With the default props a button should always be sized to fit its content.

### Tamagui Version

```markdown
1.33.4
```

### Reproduction

This repo is one commit on top of a `npm create tamagui@latest`: https://github.com/liebharc/tama-buttons
Run `yarn web` from the repo.

### System Info

```markdown
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 3600XT 6-Core Processor
    Memory: 10.63 GB / 31.93 GB
  Binaries:
    Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.79)
  npmPackages:
    babel-loader: 9.1.2 => 9.1.2
    babel-plugin-react-native-web: ^0.19.4 => 0.19.4
    buffer: ^6.0.3 => 6.0.3
    eslint-plugin-jest: ^27.2.1 => 27.2.1
```

**Comment by natew** [comment]
its technically not a bug, we set height based on your tokens, you can override it though by wrapping in styled() and changing the size variant, theres a getButtonSized export i think you can re-use and then override it...

**Comment by liebharc** [comment]
Thanks, that seems to work nicely! For other people who might be interested: This commit illustrates the necessary changes: https://github.com/liebharc/tama-buttons/commit/049e7333494c057a3396b94c2fa7cdf8b0db30e9
