### ISSUE TITLE
Switch Component Switches to disabled state on checked on Native

### ISSUE THREAD

**Issue by benschac** [tamagui/tamagui#1418]
### Current Behavior

![CleanShot 2023-07-12 at 11 59 31](https://github.com/tamagui/tamagui/assets/2502947/b05e9566-d16a-4b9d-a53c-4de2d566726b)

### Expected Behavior

https://tamagui.dev/docs/components/switch/1.28.0

should not switch to disabled state, like in the docs on web. 

### Tamagui Version

```markdown
'latest' per the next starter 1.39.6
```

### Reproduction

```markdown
https://github.com/benschac/repo-switch-disable
```

### System Info

```markdown
npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.39.0 
    node-gyp: ^9.3.1 => 9.3.1 
    prettier: ^2.7.1 => 2.8.8 
    turbo: ^1.10.3 => 1.10.3 
    typescript: ^5.1.3 => 5.1.3
```

**Comment by natew** [comment]
just noticed this too, when i brought back active theme state it happened...

**Comment by natew** [comment]
is it not the same on web? may be but on the site we dont show the plain light switch just the colored version...

**Comment by natew** [comment]
ive tweaked themes on the latest so it doesnt look disabled!

**Comment by natew** [comment]
lmk if that didnt work
