### ISSUE TITLE
Buttons are not clickable on mobile

### ISSUE THREAD

**Issue by matthieuh** [tamagui/tamagui#142]
**Describe the bug**
`Buttons` are not clickable on mobile when they are on the web. Reproducible on both version `1.0.1-beta.115` and `1.0.1-beta.116`.

**To Reproduce**
```jsx
<Button onPress={() => console.log('signIn')}>
  Sign in
</Button>
```

**System Info (please complete the following information):** 
```
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 97.30 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
Browsers:
    Brave Browser: 103.1.40.113
    Chrome: 103.0.5060.134
    Safari: 15.5```

**Comment by natew** [comment]
Weird. I see it logging out in a test, and the tamagui site itself uses onPress for various demos like Dialog, Sheet etc which are working.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/12100/180630022-c30a865e-11ad-4cef-a375-cfad15b7d031.png">

**Comment by natew** [comment]
Happy to re-open if you get some more info on how to repro.

**Comment by matthieuh** [comment]
I have probably not been clear but the issue is happening on mobile using expo. On mobile using next/react-native-web it works.

**Comment by mwarger** [comment]
@natew I'm also seeing this issue with Buttons using expo.

**Comment by mwarger** [comment]
@natew @matthieuh I updated to beta 133 - I also added the babel plugin and it worked.... 🤷

**Comment by johnkahn** [comment]
@natew I'm running into this issue on iOS using Expo 46. The babel plugin is setup according to the docs and I am on beta 135. I've verified that `process.env.TAMAGUI_TARGET === 'native'` when running it as well. I've got a `Button` with `onPress` defined but it is not called when I press it. I can also verify that React Native doesn't think it's enabled either because I can use the inspector to show all touchable views and it is not highlighted.

I tried looking through the source code to see if I could find the root problem, but it started getting over my head once I made it to the `createComponent` file where it utilizes the `Pressability` API. I'm going to keep digging, but to unblock myself I've just created a wrapper component that uses the React Native `Pressable` component around the Tamagui Button component. I lose the styling for pressed, hover, etc, but it at least functions.

I would love any advice on how to get the default Button component working or any direction on where I can better debug this in the source code, thanks!

**Comment by natew** [comment]
Hm, we need to figure out what triggers this, seems only a few people having this issue. I've tested on RN 68/69 and Expo 45, today I'll try upgrading the expo starter to 46 and see what happens.

@johnkahn the `createComponent` file really is the meat of things. It uses Pressability as a hook and then just adds the events. So it may not inspect, I'll check if the inspector shows for me.

One outstanding bug with Pressability in RN, and I think I need to file an issue there, is that nested Pressability breaks. The inner one I believe stops working altogether.

Adding `debug="verbose"` prop to your button can at least give some info, but likely not the most helpful. Are you using the compiler? Shouldn't affect anything but could be worth turning it off.

What Mac version and is this on Simulator?

**Comment by johnkahn** [comment]
Sounds good, if I use the `Pressable` component from `react-native` it is highlighted in red, and it uses the Pressability API in that component. The touchable inspector highlights `Pressability` components in read and `Touchable` components in blue, AFAIK.

It wasn't working before I nested it and I put a `Pressable` next to it in the tree and that worked, so I think we can cross that off the list of things causing this.

I'll try the debug flag. And by compiler you mean the babel plugin correct? I do have that enabled in the config.

I'm on Mac 12.4, but it is running on a physical iPhone 13 Pro Max iOS 15.6.

I'm going to try to reproduce in a minimal application so I can share it publicly and also try in the simulator to see if I can reproduce it there. I will keep you updated you on both of those.

**Comment by johnkahn** [comment]
I've got no clue what I did to cause it to start working, but it just randomly started working. I've been migrating our app from Native Base to Tamagui, so I'd been slowly going through all the components to swap them over. At some point during the swap it started working. I'll finish removing Native Base before I say I'm in the clear, but it may have be some wacky issue with having two theme systems. 🤷

**Comment by natew** [comment]
Weird. Will close for now.

**Comment by johnkahn** [comment]
To add a little more info into this for anyone else that may run into this in the future. I just had my teammate run into this and the fix was to clear the metro cache. I think it has something to do with the compilation steps. So just add `--clear` onto your start command, it worked for us.

**Comment by johnmikel** [comment]
I ran to this issue, adding back the babel plugin solved it for me. The babel plugin, however, stalls the build on a real device (according to my Discord discussion with @natew). I guess I'll have to remove the babel-plugin, or at least find a way how to not use it, when doing a real device build.
