### ISSUE TITLE
Eslint "JavaScript heap out of memory"

### ISSUE THREAD

**Issue by Aleksandern** [tamagui/tamagui#1420]
Hello.

If I import components from `tamagui'
```
import {
  Text,
  Button,
} from 'tamagui';
```

Eslint crashes:
`
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
`

If I import like so:
```
import {
  Text,
} from '@tamagui/core';

import {
  Button,
} from '@tamagui/button';
```
Eslint works okay.

===================
"react-native": "0.71.10",
"tamagui": "^1.39.8",

**Comment by natew** [comment]
not a tamagui bug

**Comment by natew** [comment]
also never seen it across many stacks, likely something on your machine

**Comment by Aleksandern** [comment]
I use `nx.dev` on my project and it's `react-native` app. Nx uses symlink for `node_modules` inside  react-native apps.
So adding `"preserveSymlinks": true,` to my `tsconfig.json` has solved the issue.
