### ISSUE TITLE
Multiple toasts laggy with animation on Next.JS

### ISSUE THREAD

**Issue by randomGitBeing132** [tamagui/tamagui#1421]
I'm using the next-expo-solito starter, showing a toast is fine, but if toast.show is triggered multiple times, then it takes awhile before the next toasts appear.

After commenting animation='quick', the toasts appear immediately, but this animation is used in Dialog without any delay issue.

Tamagui version: 1.39.8

**Comment by natew** [comment]
can you check with latest i spent a lot of time optimizing the mount and unmount there

**Comment by dlee** [comment]
This issue is still present in iOS. The second toast only appears a couple seconds after the initial toast is hidden. I can also confirm that the issue disappears if you remove `animation=quick`, but that disables all animation is not pretty.

**Comment by LuanNguyen-HnL** [comment]
@dlee did you fix the problem? I'm facing the same

**Comment by dlee** [comment]
> @dlee did you fix the problem? I'm facing the same

No, I just don't use it. I haven't found a simple workaround.
