### ISSUE TITLE
Documentation missing for `Configuring Tokens`

### ISSUE THREAD

**Issue by arjanwit** [tamagui/tamagui#1422]
### Current Behavior

The documentation is missing for the following section in the docs - https://tamagui.dev/docs/core/configuration#configuring-tokens

### Expected Behavior

[### Strict tokens]

In documentation for version 1.38.4
(https://github.com/tamagui/tamagui/blob/v1.38.4/apps/site/data/docs/core/configuration.mdx)

### Tamagui Version

```markdown
1.39.0
```

### Reproduction

```markdown
See above
```

**Comment by natew** [comment]
It's there for me, I think we merged a fix, thanks
