### ISSUE TITLE
npm create tamagui failing 

### ISSUE THREAD

**Issue by matthewhausman** [tamagui/tamagui#1423]
### Current Behavior

run ```npm create tamagui```

error: 
@tamagui/toast@npm:1.39.9: The remote server failed to provide the requested resource
➤ YN0035: │   Response Code: 404 (Not Found)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: https://registry.yarnpkg.com/@tamagui/toast/-/toast-1.39.9.tgz
➤ YN0035: │ @tamagui/web@npm:1.39.9: The remote server failed to provide the requested resource
➤ YN0035: │   Response Code: 404 (Not Found)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: https://registry.yarnpkg.com/@tamagui/web/-/web-1.39.9.tgz

### Expected Behavior

npm create tamagui is successful

### Tamagui Version

```markdown
not applicable
```

### Reproduction

```markdown
not applicable
```

### System Info

```markdown
System:
    OS: macOS 13.0
    CPU: (12) arm64 Apple M2 Pro
    Memory: 76.44 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.1
```

**Comment by natew** [comment]
npm was down
