### ISSUE TITLE
asChild doesn't pass styles to Image child on web

### ISSUE THREAD

**Issue by TimPetricola** [tamagui/tamagui#1435]
### Current Behavior

With the following code:

```tsx
<Stack asChild height={50} width={50}>
  <Image
    source={{
      uri: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.c7OiBKlepoXREhbpfenGSgAAAA%26pid%3DApi&f=1&ipt=57fb8b7b88e32a85643940b6de1dbb522939aad092356b532d197efe08fc9c70&ipo=images',
    }}
  />
</Stack>
```

The `Image` does not get the the `height` / `width` styles resulting in it being rendered in 0x0px

_Note that it does work on mobile_

### Expected Behavior

I would expect the `Image` to get the height/width set in CSS.

### Tamagui Version

```markdown
Latest (1.43.6)
```

### Reproduction

Reproduction in [this CodeSandbox](https://codesandbox.io/p/sandbox/gallant-margulis-3d7yl7?file=%2Fpackages%2Fapp%2Ffeatures%2Fhome%2Fscreen.tsx%3A35%2C7-41%2C15)

**Comment by natew** [comment]
Because RN doesn't support className, we have `acceptsClassName` for styled() maybe we can make it a component prop too..

**Comment by natew** [comment]
We have our own Image that just wraps RN Image btw

**Comment by TimPetricola** [comment]
Actually I ended relying on `@tamagui/image` directly to avoid relying and it works perfectly! Thanks for the tip :)
