### ISSUE TITLE
SelectTriggerProps not being exported from 'tamagui'

### ISSUE THREAD

**Issue by matthewhausman** [tamagui/tamagui#1436]
### Current Behavior

Can no longer import SelectTriggerProps for use in types throughout my application code

### Expected Behavior

Should be exported, I know it's just ListItemProps and nbd though

### Tamagui Version

```markdown
latest
```

### Reproduction

```markdown
easily reproduced
```

### System Info

```markdown
not applicable
```

**Comment by natew** [comment]
release notes didnt pick it up but version going out now fixes this
