### ISSUE TITLE
[Feature Request] onSlideStart & onSlideEnd callbacks from Slider

### ISSUE THREAD

**Issue by joeonmars** [tamagui/tamagui#1441]
Having these callback props will allow for calling analytics or handling other UI interactivities after the gesture is started/ended.

Currently, registering "onPressIn" event to the Slider itself can serve as a workaround for "onSlideStart". Though "onPressOut" is not good enough to use for "onSlideEnd" because it won't trigger when the gesture is finished outside the component.

**Comment by natew** [comment]
released in `1.45`
