### ISSUE TITLE
fontWeight can't be changed on Android

### ISSUE THREAD

**Issue by chabanenkopp** [tamagui/tamagui#1443]
### Current Behavior

I can't change `fontWeight` on `Android` - iOS works perfectly. Other props seem to work correctly.
Important: I am using custom fonts **TitilliumWeb**

### Expected Behavior

You pass 300 / 400 / 500, etc, and that affects the font-weight.

### Tamagui Version

```markdown
1.39.5
```

### Reproduction

```markdown
I guess there is no need to explain this :)
```

**Comment by chabanenkopp** [comment]
So, I guess it's not a Tamagui issue, it's related to a legacy RN issue here - https://github.com/facebook/react-native/issues/26193

My workaround for this is to define separate fonts in `tamagui.config.ts` for each font weight using the actual font name from you fonts ttf files: 

```
   extraLight: createFont({
      family: 'TitilliumWeb-ExtraLight',
      size: Sizes,
      lineHeight: {
        4: 16,
      },
    }),
```

It's not the best solution, especially if you use > 1 custom fonts.

**Comment by natew** [comment]
Tamagui has an ofifical workaround with the `face` property of fonts, check the docs for it.
