### ISSUE TITLE
Default tamagui theme not working React Native

### ISSUE THREAD

**Issue by pierroo** [tamagui/tamagui#1444]
### Current Behavior

I have followed the doc very closely to implement Tamagui for react native.
(which, btw, is super confusing for newcomers since it merges both web & native, and some points feel like they are in the wrong order)

I reached that part:
`For an even quicker start, you can get a full design system with @tamagui/config, which we show on the [Configuration](https://tamagui.dev/docs/core/configuration) page. That page also goes into more detail on everything createTamagui accepts.`

So I added the "quick start configuration" as is in my tamagui.config.ts, but two issues:

1- setupReactNative is not exported from tamagui, so it crashes
2- so I assumed it was not needed for native, as mentioned in the comments, so here is my final code for this config file:

```
import { config } from '@tamagui/config'

import { createTamagui } from 'tamagui' // or '@tamagui/core'
const appConfig = createTamagui(config)
export type AppConfig = typeof appConfig

declare module 'tamagui' {
  interface TamaguiCustomConfig extends AppConfig {}
}

export default appConfig

```

But still, seems like it is not being applied at all:
instead of the expected blue <Button>, it is black
I also can't use any of the shorthands like "btrr" etc which I thought would already be part of the default configuration?

Am I missing something here?
I am using the latest 1.43.12 version

### Expected Behavior

Default config as per the documentation should world

### Tamagui Version

```markdown
1.43.12
```

### Reproduction

```markdown
the fork is for next, my issue is on RN
```

**Comment by 0xsj** [comment]
Try upgrading your tamagui version to 1.7..2 or @latest?

**Comment by pierroo** [comment]
> Try upgrading your tamagui version to 1.7..2 or @latest?

I didn't realize there were dozens of updates in just a week;
But even then the latest seems to be 1.47.1; no 1.7xxx

And now that I updated to the latest, the app crashes from this error:
![image](https://github.com/tamagui/tamagui/assets/17619412/e8354a4d-9f9b-46ad-a4c1-8782c7d55940)

It was working perfectly fine before;
and it doesn't even tell me in which screen it comes from... the risks of working with a "fast moving library" I guess :)

**Comment by HialeahLiam** [comment]
I am also having this issue. My buttons appear black by default. Adding themes to the `theme` prop doesn't affect the component at all.

I think an update might have broken it?

[The example shown here isn't working properly i.e. the *superblue them isn't applied*.](https://tamagui.dev/docs/intro/themes#addtheme)

[I even cloned this repo and tried adjusting](https://github.com/ivopr/tamagui-expo) themes there and they weren't responsive either.

**Comment by scornz** [comment]
Any update on this? I am also running into issues with the config seemingly not being applied in a blank app.

**Comment by natew** [comment]
Fix going out for the superblue that was only specific to the site.

Can you guys give me a repro on the tamagui starter? Platform details too. It's working for us we tested a few different ways.

**Comment by TheEhsanSarshar** [comment]
let me know to re-open it when you have a repro
