### ISSUE TITLE
The application build process reaches 99% completion, but it takes more than a minute or even longer to reach 100%+ hard to configure my own color also hard to integrate with my existing expo js  project 

### ISSUE THREAD

**Issue by Ahmed-Ibrahim-Anter** [tamagui/tamagui#1445]
I recently came across your Tamagui package while developing an Expo project using JavaScript on my Linux Mint system. First and foremost, I'd like to express my gratitude for your hard work and the effort you've put into creating this package.

I followed the steps provided in the documentation to set up Tamagui within my project:

1. `npm create tamagui`
2. Used Git for version control
3. Navigated to `apps/expo`
4. Ran `yarn start`

The setup process went smoothly, and I appreciate the features and components that Tamagui offers. However, during the build process, I encountered a couple of issues that I wanted to share with you:

1. The application build process reaches 99% completion, but it takes more than a minute or even longer to reach 100%. I was wondering if there's any specific reason for this delay or if there are any optimizations I can make to improve the build time.

2. I tried customizing the colors to match my project's theme, but unfortunately, I faced difficulties in doing so. Could you please provide some guidance on how to customize the colors effectively within the Tamagui package?

3- Moreover, I encountered difficulties when trying to integrate Tamagui into an existing Expo project developed in JavaScript. It would be immensely helpful if you could include a comprehensive guide or documentation on how to seamlessly integrate Tamagui into Expo projects.

Once again, thank you for your dedication to this project. Tamagui has the potential to enhance the development process significantly, and I believe resolving these issues will further strengthen its position as an essential tool for Expo developers.

https://github.com/tamagui/tamagui/assets/76538677/227d7f82-e7e7-46f7-84bb-548433b6253d

**Comment by dondxniel** [comment]
You can check my issue #1455 to see the color configuration on my `tamagui.config.ts`, it might be of some help. Sorry I'm not sure I can help with the other issue as I'm experiencing it too.

**Comment by natew** [comment]
The 99% thing is typical to Metro the RN bundler, it just has to do with the way it shows that progress bar and not to do with tamagui.

**Comment by 0xsj** [comment]
I was also looking into the issue and has been driving me nuts for the past couple of days. 
Build hangs at 99.3%, the sim will disconnect, but after checking the bundling was done in console -> refreshing the sim would finally run. 

After the initial bundle, the reloads work fine. 
however if by some chance you accidentally disconnect or kill node processes, you have to go through the somewhat painful 3min bundling again. 

Any ideas for a work around on this? @natew

**Comment by alitnk** [comment]
> however if by some chance you accidentally disconnect or kill node processes, you have to go through the somewhat painful 3min bundling again.

@0xsj That's most likely because cache is disabled. I think with cache on that'd be resolved. Could be either be turned off in your metro config or using `-c` when you start expo. (correct me if I'm wrong)

**Comment by Ahmed-Ibrahim-Anter** [comment]
> > however if by some chance you accidentally disconnect or kill node processes, you have to go through the somewhat painful 3min bundling again.
> 
> @0xsj That's most likely because cache is disabled. I think with cache on that'd be resolved. Could be either be turned off in your metro config or using `-c` when you start expo. (correct me if I'm wrong)

still facing  this problem also with a new project

**Comment by 0xsj** [comment]
@alitnk negative. this is not a cache disable issue.
all fresh installs that ive done recently has this same problem. 

bundle time `118539ms`

**Comment by natew** [comment]
Hm @alitnk can we test disabling the studio and config watching and see if that’s getting in the way?

**Comment by natew** [comment]
i found an issue where babel was re-loading the config on every file, this has been patched. because that should improve things and otherwise i can't replicate anything, closing but we can re-open if its an issue still
