### ISSUE TITLE
Select throws error when adapted to Sheet (can't read getFloatingProps of undefined)

### ISSUE THREAD

**Issue by nderscore** [tamagui/tamagui#1447]
### Current Behavior

When a Select is adapted to a Sheet on small viewport, a runtime error is thrown when the conditions of the Adapt are met:

```
TypeError: Cannot read properties of undefined (reading 'getFloatingProps')

@ ../node_modules/@tamagui/select/dist/esm/SelectViewport.js (64:6)
```

This issue was introduced in release 1.40.0. Version 1.39.9 does not have this error.

### Tamagui Version

```markdown
1.40.0 - 1.43.12
```

### Reproduction

https://codesandbox.io/p/sandbox/reverent-clarke-4jcyqt?file=%2Fpackages%2Fapp%2Ffeatures%2Fhome%2Fscreen.tsx%3A1%2C1

Steps to reproduce:

1. Open codesandbox demo
2. Shrink viewport width to be "small"

**Comment by JonLatane** [comment]
For search-index-friendliness: I encountered this error specifically on `context.interactions.getFloatingProps`. And to fix it, I just commented out the following block in my `<Select />`:

```tsx
{/* <Adapt when="xs" platform="touch">
      <Sheet ... />
</Adapt> */}
```

However, this makes usability on my iPhone a bit weird (have to long-press the Select to make it not immediately disappear). A fix for the underlying issue would be nice.

**Comment by natew** [comment]
i think fixed on latest, tested locally and on sandbox, adding some extra checks in a patch as well next release

**Comment by matthewmturner** [comment]
@natew im still having this issue on 1.46

**Comment by natew** [comment]
You likely have a version mismatch make sure all your Tamagui versions are lined up.
