### ISSUE TITLE
fontFamily "Interbold" is not a system font and has not been loaded through Font.loadAsync

### ISSUE THREAD

**Issue by 0xsj** [tamagui/tamagui#1448]
### Current Behavior

New projects started with tamagui on a fresh install will throw this error through the simulator. 

There are two versions / installations with expo-font that happens. 

1.  node_modules/expo-font
2. node/modules/expo/node_modules/expo-font

Running `rm -rf ./node_modules/expo/node_modules/expo-font` fixes this issue. 

### Expected Behavior

newly created projects should have minimal errors as possible. 

### Tamagui Version

```markdown
@tamagui - 1.43
@expo - 48.0.7
@expo-font - ^11.1.1
```

### Reproduction

```markdown
to reproduce 
- npm create tamagui@latest
- yarn 
- yaran native
```

**Comment by NavyAnt24** [comment]
I ran into this issue as well after I was upgrading a bunch of packages, since I ran the starter a while back. I am not sure what the problem is exactly, but I believe the version of `expo` in the starter had a resolution to a higher version of `expo-font` in `yarn.lock`, and I'm guessing 2 versions of `expo-font` end up getting installed.

We may be able to solve this but updating the resolutions in `package.json` to specify a version of `expo-font`. Alternatively, I upgraded `expo` to `v49.0.4`, which appears to have solved the problem, but it did take me some time to get things running again. In the short-term, it might be simpler just to add a resolution.

**Comment by 0xsj** [comment]
@NavyAnt24 thanks for the response. 
closing this comment as it seems like a dupe of a closed issue from last week.

**Comment by emregca** [comment]
weird enough im getting this issue on the starter i created a long while ago, and removing `node_modules/expo/node_modules/expo-font` does not do the trick.

**Comment by seyaobey-dev** [comment]
I'm still facing the same issue with fresh `expo` app

```
"@tamagui/config": "^1.76.0",
"@tamagui/core": "^1.76.0",
"expo": "~49.0.15",
"expo-font": "~11.4.0",
"tamagui": "^1.76.0"
```

**Comment by nikodraca** [comment]
Seeing the same issue, even tried to manually install Inter:
```
    "@expo-google-fonts/inter": "^0.2.3",
    "@tamagui/config": "^1.76.0",
    "@tamagui/lucide-icons": "^1.76.0",
    "expo": "~49.0.13",
    "expo-font": "^11.6.0",
    "tamagui": "^1.76.0"
```

**Comment by dr-farooq** [comment]
Hi all, same issue, tried all of the above with no success
- tried rm -rf ./node_modules/expo/node_modules/expo-font
- tried manual imports as suggested by @jamesst20 but didnt work for me :( 
- tried reinstalling expo font
- tried createFont/createInterFont

Any other suggestions?

**Comment by dr-farooq** [comment]
I back @jamesst20, worked for me. Thanks bro 😎

**Comment by willybeans** [comment]
> @seyaobey-dev @nikodraca
> 
> Same issue but loading them myself resolves the issue. Ain't the expected way to do so?
> 
> ```
> import { useFonts } from "expo-font";
> 
> export default function() {
>   const [loaded] = useFonts({
>     Inter: require('@tamagui/font-inter/otf/Inter-Medium.otf'),
>     InterBold: require('@tamagui/font-inter/otf/Inter-Bold.otf'),
>   });
> 
>   return loaded;
> }
> ```

this worked for me as well.

**Comment by Myself-Ikram** [comment]
Can you explain this little bit more because iam unable to understand

**Comment by i1kaaasra** [comment]
I do not use Inter .. I use my own fonts but still I get this error

**Comment by AsadAnsariPocket** [comment]
const [loaded] = useFonts({
        Inter: require('@tamagui/font-inter/otf/Inter-Medium.otf'),
        InterBold: require('@tamagui/font-inter/otf/Inter-Bold.otf'),
    })

    if (!loaded) {
        return null
    }
Just use this in in the index file in react native , Solved the problem while using tamagui and expo router
