### ISSUE TITLE
Using panels (Dialog and Sheet)

### ISSUE THREAD

**Issue by apperside** [tamagui/tamagui#145]
**Describe the bug**
Hello @natew ,
first of all let me tell you that the work you have done is truly impressive, and I don't understand why tamagui is so less popular than other similar framework like Native Base or other. BTW, I am very happy to have found tamagui, and I think I will use it by default on all my future projects, its build layer is a real superpower, and the typing system is amazing.

That being said, I am also a [NX](nx.dev) fan boy and an [Expo](https;//expo.dev) detractor, so I built a monorepo project with NX + Tamagui + NextJS + Bare React Native Project, you can find it [here](https://github.com/apperside/nx-tamagui-example). 

It works pretty well, I also managed to integrate [solito](https://solito.dev) (even though  I had quite a lot of headaches with it).

The reason for this issue however is because I am experiencing troubles integrating Dialogs and Sheet on both the web and native.

From what I can understand from the documentation:
- `AlertDialog` work only on web
- `Dialog` work  on web and on native too, but it needs some tweak on the latter
- `Sheet` has no warning about compatibility, so I assume it should work both on the web and native

I am than trying to integrate `Sheet`, and the first problem is this:

<img width="911" alt="Screenshot 2022-07-24 at 13 10 45" src="https://user-images.githubusercontent.com/5955338/180644344-cf6aad61-b5ca-4821-bf0f-628991ac877e.png">

it seem that shorthands are not recognized, even though they are on the rest of the codebase.

It is just a typescript error, so I am able to use it anyway by ignoring warnings: If I add to my a component with the exact same code of you example https://tamagui.dev/docs/components/sheet, I get this error on the web

<img width="977" alt="Screenshot 2022-07-24 at 13 18 54" src="https://user-images.githubusercontent.com/5955338/180644632-b646f06a-ba49-419d-9edd-6079ee19be0c.png">

and this one on mobile

![Screenshot 2022-07-24 at 13 16 56](https://user-images.githubusercontent.com/5955338/180644655-98857712-9ca3-4563-b868-37725bc43c1a.png)

The tamagui provider is properly integrated as I can successfully use `useTheme` hook.

What's the proper way to integrate the Sheet component?

The second question is:

In the docs, for the `Modal` component, you say

> Notice: Dialog is in beta for Web only, it renders on Native but some styling and interaction needs fixes before it's usable.

Can you please elaborate more on what you mean for "but some styling and interaction needs fixes before it's usable."?

Thank you

**To Reproduce**
- Clone the repo https://github.com/apperside/nx-tamagui-example
- **CHECKOUT `test-sheet` branch**
- launch mobile and web app and you will get the described errors.

**System Info (please complete the following information):** 
  System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 248.80 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.19.3/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 102.0.1
    Safari: 15.5

**Comment by natew** [comment]
@apperside love the repo, thanks for checking it out. I think once we get to 1.0 and maybe post to ProductHunt, we'll get make up the stars. I also prefer bare RN projects, I've just done the starter as it is to be a bit simpler. Have some vague plans to put together a much nicer starter at some point.

Sheet.Frame should accept shorthands, it does for me in the demo at least. Not sure on that yet.

The useContext error is interesting, are you sure you've de-duped the react node_module? Just a guess.

Dialog, Sheet, and AlertDialog are all coming out of beta soon and should work on native as well as of the latest betas. 

Thanks for the repro, I'll check it out soon.

**Comment by natew** [comment]
@apperside can you try updating that repo to the latest? There's be 14 releases since with a variety of fixes. I have it pulled but don't have time yet to upgrade.

**Comment by apperside** [comment]
Hello @natew ,
thanks for your update. 
I tried to upgrade all of tamagui dependencies in my `main` branch to `1.0.1-beta.135`, but unfortunately something gets broken:

on iOS I get the folling error

![Screenshot 2022-08-05 at 10 08 14](https://user-images.githubusercontent.com/5955338/183032875-e0464d0c-064d-46d4-a30d-43282f52ef5d.png)

on web I cannot even run the app because of this error

```bash
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error

 >  NX   Cannot find module 'html-webpack-plugin'

   Require stack:
   - /Users/simone/dev/tamagui/nx-tamagui-example/node_modules/html-inline-css-webpack-plugin/build/index.js
   - /Users/simone/dev/tamagui/nx-tamagui-example/node_modules/@tamagui/next-plugin/dist/cjs/withTamagui.js
   - /Users/simone/dev/tamagui/nx-tamagui-example/node_modules/@tamagui/next-plugin/dist/cjs/index.js
   - /Users/simone/dev/tamagui/nx-tamagui-example/apps/web/next.config.js
   Pass --verbose to see the stacktrace.
```

Consider that the only and unique changes from the working version and the not working one is just the tamagui pacakges versions.

Are there some breaking changes I should be aware of? Reading the release notes I only see one breaking change, but it is related to a shorthand change

**Comment by natew** [comment]
@apperside thanks for the detail, I'll check the repo again.

**Comment by natew** [comment]
Did this ever resolve?

**Comment by apperside** [comment]
I'll need to check, I focused on other things and made a lot of changes, need to check again, I'll let you know

**Comment by natew** [comment]
i think fixed, re-open if not

**Comment by aawalton** [comment]
I ran into a similar issue starting from `npm create tamagui`. Tracked it down the `@typescript-eslint/no-empty-interface` linter rule, which when added replaced an interface with a type in `packages/ui/src/global.ts`, which somehow cause all of the shorthand properties to no longer be treated as valid types.
