### ISSUE TITLE
'transparent' variant

### ISSUE THREAD

**Issue by Aleksandern** [tamagui/tamagui#1450]
After upgrading from `"tamagui": "^1.43.10"` to `"tamagui": "^1.43.13"` my `transparent` variant of my button component stopped working. I had to rename it.

**Comment by natew** [comment]
are you using `as const` on your variants?

**Comment by Aleksandern** [comment]
Yes, I am. It worked okay before the update.

```
export const Button = styled(ButtonOrig, {
  backgroundColor: '$primary',
  borderRadius: 18,
  color: '$c10',
  fontWeight: '$semiBold',
  variants: {
    secondary: {
      true: {
        backgroundColor: 'red',
      },
    },
    transparent: {
      true: {
        backgroundColor: 'transparent',
        borderWidth: 0,
        pressStyle: {
          opacity: 0.5,
        },
      },
    },
    disabled: {
      true: {
        opacity: 0.5,
      },
    },
  } as const,
  pressStyle: {
    opacity: 0.8,
  },
});
```

**Comment by natew** [comment]
![CleanShot 2023-07-22 at 09 33 00](https://github.com/tamagui/tamagui/assets/12100/0ef12242-283b-4990-a025-6105241a1de1)

I can't replicate, if you can send a codesandbox
