### ISSUE TITLE
Select. 'PortalDispatchContext' cannot be null

### ISSUE THREAD

**Issue by Aleksandern** [tamagui/tamagui#1451]
Hello.

When I use `Select.Viewport` inside `Select.Content` I get the error:
```
'PortalDispatchContext' cannot be null, please add 'PortalProvider' to the root component.
```

Is it a bug or I missed something?

**Comment by haveamission** [comment]
How'd you end up solving this?

**Comment by Aleksandern** [comment]
> add 'PortalProvider' to the root component.

```
import {
  PortalProvider,
} from '@tamagui/portal';

etc...
```

**Comment by mariacheline** [comment]
+1 still doesn't work for me despite adding PortalProvider in the root
