### ISSUE TITLE
[Expo] Typescript errors running tsc --pretty --noEmit 

### ISSUE THREAD

**Issue by atanaskanchev** [tamagui/tamagui#1472]
### Current Behavior

```shell
native:type-check: ../../node_modules/@tamagui/create-theme/src/masks.tsx:63:11 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
native:type-check:   No index signature with a parameter of type 'string' was found on type '{}'.
native:type-check: 
native:type-check: 63           out[key] = value + overrideShift
native:type-check:              ~~~~~~~~
native:type-check: 
native:type-check: ../../node_modules/@tamagui/create-theme/src/masks.tsx:66:11 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
native:type-check:   No index signature with a parameter of type 'string' was found on type '{}'.
native:type-check: 
native:type-check: 66           out[key] = override[key]
native:type-check:              ~~~~~~~~
native:type-check: 
native:type-check: ../../node_modules/@tamagui/create-theme/src/masks.tsx:77:9 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
native:type-check:   No index signature with a parameter of type 'string' was found on type '{}'.
native:type-check: 
native:type-check: 77         out[key] = clamped
native:type-check:            ~~~~~~~~
native:type-check: 
native:type-check: ../../node_modules/@tamagui/create-theme/src/ThemeBuilder.tsx:270:9 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
native:type-check:   No index signature with a parameter of type 'string' was found on type '{}'.
native:type-check: 
native:type-check: 270         out[themeName] = themeDefinition.theme
native:type-check:             ~~~~~~~~~~~~~~
native:type-check: 
native:type-check: ../../node_modules/@tamagui/create-theme/src/ThemeBuilder.tsx:303:9 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
native:type-check:   No index signature with a parameter of type 'string' was found on type '{}'.
native:type-check: 
native:type-check: 303         out[themeName] = createTheme(palette, template, options, themeName)
native:type-check:             ~~~~~~~~~~~~~~
native:type-check: 
native:type-check: ../../node_modules/@tamagui/create-theme/src/ThemeBuilder.tsx:308:22 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
native:type-check:   No index signature with a parameter of type 'string' was found on type '{}'.
native:type-check: 
native:type-check: 308       const parent = out[parentName]
native:type-check:                          ~~~~~~~~~~~~~~~
native:type-check: 
native:type-check: ../../node_modules/@tamagui/create-theme/src/ThemeBuilder.tsx:323:7 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
native:type-check:   No index signature with a parameter of type 'string' was found on type '{}'.
native:type-check: 
native:type-check: 323       out[themeName] = applyMask(
native:type-check:           ~~~~~~~~~~~~~~
native:type-check: 
native:type-check: 
native:type-check: Found 7 errors in 2 files.
native:type-check: 
native:type-check: Errors  Files
native:type-check:      3  ../../node_modules/@tamagui/create-theme/src/masks.tsx:63
native:type-check:      4  ../../node_modules/@tamagui/create-theme/src/ThemeBuilder.tsx:270
native:type-check:  ELIFECYCLE  Command failed with exit code 2.
n
```

### Tamagui Version

```markdown
1.45.8
```

### Reproduction

```markdown
Using tamagui in an expo project in turborepo
```

### System Info

```markdown
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 54.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    pnpm: 8.6.10 - /opt/homebrew/bin/pnpm
  Browsers:
    Safari: 16.5.2
  npmPackages:
    @commitlint/cli: 17.6.7 => 17.6.7 
    @commitlint/config-conventional: 17.6.7 => 17.6.7 
    @ianvs/prettier-plugin-sort-imports: 4.1.0 => 4.1.0 
    @turbo/gen: 1.10.11 => 1.10.11 
    check-dependency-version-consistency: 4.1.0 => 4.1.0 
    eslint: 8.45.0 => 8.45.0 
    eslint-config-custom: workspace:* => 0.0.0 
    eslint-plugin-turbo: 1.10.11 => 1.10.11 
    husky: 8.0.3 => 8.0.3 
    lint-staged: 13.2.3 => 13.2.3 
    prettier: 3.0.0 => 3.0.0 
    prettier-plugin-tailwindcss: 0.4.1 => 0.4.1 
    turbo: 1.10.11 => 1.10.11
```

**Comment by croshim** [comment]
Have the same issue with 1.45.4 version

**Comment by jonsherrard** [comment]
@croshim can you post your package.json?

**Comment by atanaskanchev** [comment]
{
  "name": "native",
  "version": "0.0.0",
  "main": "index.js",
  "private": true,
  "scripts": {
    "start": "expo start --clear",
    "android": "TAMAGUI_TARGET=native expo run:android",
    "ios": "TAMAGUI_TARGET=native expo run:ios",
    "clean": "rm -rf node_modules .expo .turbo *.apk *.tar.gz",
    "deps:check": "pnpx expo install --check",
    "deps:fix": "pnpx expo install --fix",
    "dev:android": "expo start --android",
    "dev:ios": "expo start --ios",
    "lint": "eslint . --ext .ts,.tsx,.js,.jsx",
    "lint:report": "eslint . --ext .ts,.tsx,.js,.jsx --format json --output-file ./lint-results/types.json",
    "lint:fix": "eslint src --ext .ts,.tsx,.js,.jsx --fix",
    "format:check": "prettier --check \"./**/*.{ts,tsx,js,jsx,md,json}\"",
    "format:write": "prettier --write \"./**/*.{ts,tsx,js,jsx,md,json}\"",
    "_type-check": "tsc --pretty --noEmit",
    "pods": "pod-install",
    "studio": "studio android",
    "xcode": "xed ios",
    "prebuild": "APP_ENV=production pnpm expo prebuild --clean",
    "prebuild:dev": "APP_ENV=development pnpm expo prebuild --clean --skip-dependency-update expo",
    "build:ios": "pnpm eas build --platform ios --local --non-interactive --clear-cache",
    "build:android": "pnpm eas build --platform android --local --non-interactive --clear-cache",
    "build:ios:dev": "pnpm eas build --profile development --platform ios --local --non-interactive --clear-cache",
    "build:android:dev": "pnpm eas build --profile development --platform android --local --non-interactive --clear-cache",
    "submit:ios": "pnpm eas submit --platform ios",
    "submit:android": "pnpm eas submit --platform android"
  },
  "dependencies": {
    "@babel/runtime": "7.22.6",
    "@hookform/resolvers": "3.1.1",
    "@lf/services-drizzle-orm-schema": "workspace:*",
    "@lf/services-supabase-types": "workspace:*",
    "@react-navigation/native": "6.1.7",
    "@shopify/flash-list": "1.5.0",
    "@supabase/supabase-js": "2.29.0",
    "@t3-oss/env-core": "0.6.0",
    "@tamagui/animations-react-native": "1.45.8",
    "@tamagui/font-inter": "1.45.8",
    "@tamagui/react-native-media-driver": "1.45.8",
    "@tamagui/shorthands": "1.45.8",
    "@tamagui/themes": "1.45.8",
    "@tamagui/toast": "1.45.8",
    "@tanstack/react-query": "4.32.0",
    "@types/react-native": "0.72.2",
    "babel-plugin-module-resolver": "5.0.0",
    "burnt": "0.11.7",
    "countries-list": "2.6.1",
    "eas-cli": "3.17.0",
    "expo": "49.0.5",
    "expo-constants": "14.4.2",
    "expo-dev-client": "2.4.6",
    "expo-font": "11.4.0",
    "expo-linear-gradient": "12.3.0",
    "expo-linking": "5.0.2",
    "expo-router": "2.0.1",
    "expo-secure-store": "12.3.1",
    "expo-splash-screen": "0.20.4",
    "expo-status-bar": "1.6.0",
    "expo-system-ui": "2.4.0",
    "expo-updates": "0.18.11",
    "lucide-react-native": "0.263.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "7.45.2",
    "react-native": "0.72.3",
    "react-native-gesture-handler": "2.12.0",
    "react-native-qonversion": "5.0.2",
    "react-native-safe-area-context": "4.7.1",
    "react-native-screens": "3.22.1",
    "react-native-svg": "13.10.0",
    "react-native-web": "0.19.7",
    "tamagui": "1.45.8",
    "zod": "3.21.4"
  },
  "devDependencies": {
    "@babel/core": "7.22.9",
    "@expo/metro-config": "0.10.7",
    "@tamagui/babel-plugin": "1.45.8",
    "babel-plugin-transform-inline-environment-variables": "0.4.4",
    "metro-minify-terser": "0.77.0",
    "pod-install": "0.1.38",
    "react-native-url-polyfill": "2.0.0",
    "typescript": "5.1.6"
  }
}

**Comment by GV14982** [comment]
I am also getting this error. I'm on the latest `1.45.10`
