### ISSUE TITLE
exactOptionalPropertyTypes causing errors

### ISSUE THREAD

**Issue by AkritW** [tamagui/tamagui#1475]
### Current Behavior

If you add exactOptionalPropertyTypes to tsconfig.json

{
  "compilerOptions": {
    ...
   "exactOptionalPropertyTypes": true,
  },
  ...
}

It will cause errors.

### Expected Behavior

No error even though exactOptionalPropertyTypes and is set to true

### Tamagui Version

```markdown
1.46.0
```

### Reproduction

```markdown
https://codesandbox.io/p/sandbox/github/tamagui/tamagui/tree/master/starters/next-expo-solito?file=%2Ftsconfig.json%3A1%2C1
```

**Comment by natew** [comment]
Add skip lib checking I think.
