### ISSUE TITLE
Input & Textarea crash on React Native

### ISSUE THREAD

**Issue by pierroo** [tamagui/tamagui#1478]
### Current Behavior

As soon as I try to use a <Input /> (simple as that) the app crashes entirely with the following error:

Invariant Violation: [1189,"AndroidTextInput",11,{"allowFontScaling":true,".....
...ge":true,"text":""}] is not usable as a native method argument

This error is located at:
    in AndroidTextInput (created by InternalTextInput)
    in InternalTextInput (created by TextInput)

### Expected Behavior

I just want to be able to use Input and textarea, simple

### Tamagui Version

```markdown
1.43.12 (latest)
```

### Reproduction

```markdown
the codesandbox link provided above crashes on the website
```

### System Info

```markdown
using latest RN version (0.72.3)
```

**Comment by 0xsj** [comment]
I think your issue is that your imports are incorrect?
You should be using the Input component, not the TextInput (which is a react-native out of the box) if im not mistaken

**Comment by pierroo** [comment]
Thank you for the feedback, but no: I was using <Input> and <Textarea> as expected

I rolled back version until there is a fix for that.

In case that helps, I am using this tamagui.config file:

```
import { config } from '@tamagui/config'

import { createFont, createTamagui } from 'tamagui' // or '@tamagui/core'

const Nunito = createFont({
  family: 'Nunito-ExtraBold',
  size: {
    1: 11,
    2: 12,
    3: 13,
    4: 14,
    true: 14,
    5: 16,
    6: 18,
    7: 20,
    8: 23,
    9: 30,
    10: 46,
    11: 55,
    12: 62,
    13: 72,
    14: 92,
    15: 114,
    16: 134
  },
  weight: {
    100: 100,
    200: 200,
    300: 300,
    400: 400,
    true: 900,
    500: 500,
    600: 600,
    700: 700,
    800: 800,
    900: 900
  },
});

const NunitoSemi = createFont({
  family: 'Nunito-SemiBold',
  size: {
    1: 11,
    2: 12,
    3: 13,
    4: 14,
    true: 14,
    5: 16,
    6: 18,
    7: 20,
    8: 23,
    9: 30,
    10: 46,
    11: 55,
    12: 62,
    13: 72,
    14: 92,
    15: 114,
    16: 134
  },
  weight: {
    100: 100,
    200: 200,
    300: 300,
    400: 400,
    true: 900,
    500: 500,
    600: 600,
    700: 700,
    800: 800,
    900: 900
  },
});

const appConfig = createTamagui({
  ...config,
  fonts: {
    heading: Nunito, // overrides the default heading font
    body: NunitoSemi, // overrides the default body font
    nunito: Nunito // introduce a specific token for your new font
  },
})
export type AppConfig = typeof appConfig

declare module 'tamagui' {
  interface TamaguiCustomConfig extends AppConfig {}
}

export default appConfig
```

**Comment by alitnk** [comment]
@pierro Can you share a snippet of how you're using it?

**Comment by pierroo** [comment]
Just plain <Textarea /> and plain <Input /> from tamagui, nothing else, they just crash the app.

**Comment by idrakimuhamad** [comment]
I had this happened when I created my own text input using RN text input. And it seems to relate to when I set fontFamily "$body" to it when i uses styled with it. When i removed it, the crash doesn't occur.

**Comment by natew** [comment]
you may need this before you use your input, its how tamagui knows which components to treat as react native ones:

<img width="331" alt="CleanShot 2023-08-06 at 10 05 19@2x" src="https://github.com/tamagui/tamagui/assets/12100/49b98938-ac58-4021-875a-01946f9e933c">

we did this so we could support tree shaking, its a bit confusing. if you import tamagui it does this for you automatically though so i doubt this is it, but just noting
