### ISSUE TITLE
Nested Dialogs modals lose contexts provided values

### ISSUE THREAD

**Issue by G-Ray** [tamagui/tamagui#1481]
On web, when instantiating a nested Dialog modal inside another one, context values can't be accessed with `useContext` in the nested Dialog.

**Comment by natew** [comment]
yo can you get me a repro so i can debug this easily, you fan fork and make a PR with it in sandbox

**Comment by Aleksandern** [comment]
@G-Ray 
Have you found any solution?

Similar issue with Portal https://github.com/callstack/react-native-paper/issues/3880

**Comment by G-Ray** [comment]
> @G-Ray 
> Have you found any solution?
> 
> @natew 
> Similar issue with Portal https://github.com/callstack/react-native-paper/issues/3880

Unfortunately I have not found any solution, as a workaround I pass my props directly to the nested dialogs, without using context.
