### ISSUE TITLE
Using Starter template to create app but failed to run it

### ISSUE THREAD

**Issue by bambooom** [tamagui/tamagui#1485]
### Current Behavior

I use the starter tool `npm create tamagui` and choose the `simple web` template to build a demo.
But after install, I cannot run it locally, with errors:

![Screenshot 2023-07-31 at 16 45 57](https://github.com/tamagui/tamagui/assets/14840170/02047e65-633d-4e1c-b788-0049b98a58e3)

### Expected Behavior

Successfully run the web locally.

### Tamagui Version

```markdown
1.48.0
```

### Reproduction

```markdown
1. `npm create tamagui`
2. choose `Simple Web` template and waiting for installation
3. `cd demo-app`
4. `yarn web` to start it locally
```

### System Info

```markdown
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 97.72 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 3.3.0 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    pnpm: 8.6.9 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 115.0.5790.114
    Edge: 114.0.1823.55
    Safari: 16.3
```

**Comment by alitnk** [comment]
Hey. We just released a new version with a fix. Can you try again and see if that fixes it?

**Comment by bambooom** [comment]
@alitnk Hi! I've tried with 1.49.7 but still many errors like this:

![Screenshot 2023-08-05 at 13 14 35](https://github.com/tamagui/tamagui/assets/14840170/1d1578f9-2487-4a5a-80c0-a2aa4f36989e)
![Screenshot 2023-08-05 at 13 14 49](https://github.com/tamagui/tamagui/assets/14840170/00d14847-81c4-48b4-b20a-1fbd75e875a2)
![Screenshot 2023-08-05 at 13 15 35](https://github.com/tamagui/tamagui/assets/14840170/af714094-4539-40be-9ffb-2d6e20759594)
![Screenshot 2023-08-05 at 13 16 03](https://github.com/tamagui/tamagui/assets/14840170/257d678a-e736-4508-9838-7f6ec6f53500)
