### ISSUE TITLE
Broken typescript types for ScrollView ref

### ISSUE THREAD

**Issue by apperside** [tamagui/tamagui#1486]
### Current Behavior

I am trying to use a ref for a ScrollView, but I am encountering some problems with typescript definitions.
If I import ScrollView from tamagui, this is what I get

<img width="1057" alt="Screenshot 2023-08-01 at 08 42 38" src="https://github.com/tamagui/tamagui/assets/5955338/3cc8735b-d73c-49d7-b357-5aeb70f99b72">

If I use `typeof ScrollView` for the generic type, the error disappears but I cannot access ScrollView's methods

<img width="754" alt="Screenshot 2023-08-01 at 08 44 15" src="https://github.com/tamagui/tamagui/assets/5955338/dad3905a-182f-428c-8451-77a4fab15d49">

This is instead what happens if I import ScrollView from react-native:

<img width="741" alt="Screenshot 2023-08-01 at 08 45 25" src="https://github.com/tamagui/tamagui/assets/5955338/afb41d23-06c8-45a0-b113-4e3d8b2be195">

the typescript error doesn't happen and I can access all ScrollView's methods

### Expected Behavior

When I import ScrollView from tamagui, typescript definitions should work in the same way it works when imported from react-native

### Tamagui Version

```markdown
1.45.8
```

### Reproduction

```markdown
try to declare this variable in any component

import {ScrollView} from "tamagui"

...


const scrollViewRef = useRef<ScrollView>(null)
```

**Comment by alitnk** [comment]
You should be able to do `useRef<ScrollView>() ` now.
