### ISSUE TITLE
Select Broken For Android but fine on iOS and web

### ISSUE THREAD

**Issue by stoickeyboard** [tamagui/tamagui#1487]
### Current Behavior

When rendering a Select component on Android the error `SelectGroup must be used within Select` or `SelectItem must be used within Select` is triggered. However, the Select component renders fine on iOS and Web

### Tamagui Version

```markdown
1.48.7
```

### Reproduction

```markdown
The code is in the `next-expo-solito` starter project. Apologies but I couldn't get `kitchen-sink` running on my computer.

https://github.com/stoickeyboard/tamagui-select-issue
```

**Comment by deggertsen** [comment]
We're also experiencing this issue.

**Comment by ezavalatyro** [comment]
If you are using the `Select` with the `Select.Sheet` adapter, the issue is related to context propagation. The documentation says:

https://tamagui.dev/docs/components/sheet#notes

```
For Android you need to manually re-propagate any context when using modal. This is because React Native doesn't support portals yet.
```

Unfortunately, there is no further information about how to do that.

For a temporary solution, as the SelectGroup and SelectItem extends from Group and Item, I had to replace them and handle by myself the states. 

```tsx
  const [isSelectOpen, setIsSelectOpen] = useState(false);
  const [internalValue, setInternalValue] = useState<string>('');

  const handleUpdateValue = (newValue: string) => {
    setIsSelectOpen(false);
    setInternalValue(newValue);
  };

  return (
    <Select
      value={internalValue}
      open={isSelectOpen}
      onOpenChange={setIsSelectOpen}
      onValueChange={handleUpdateValue}
    >
      <Select.Trigger asChild>
        <Button>Select</Button>
      </Select.Trigger>

      <Adapt when="sm" platform="touch">
        <Sheet modal>
          <Adapt.Contents />
        </Sheet>
      </Adapt>

      <Select.Content>
        <Select.ScrollUpButton />
        <Select.Viewport>
          <Group>
            <ListItem onPress={() => handleUpdateValue('option A')}>
              Option A
            </ListItem>
          </Group>
        </Select.Viewport>
        <Select.ScrollDownButton />
      </Select.Content>
    </Select>
  );
```

**Comment by chornos13** [comment]
I have the same issue, it's looks like working normal in older version 1.3x.x I guess (because I forgot what version is working before this bug happened)

**Comment by natew** [comment]
Fix going out now in v1.48.8

**Comment by stoickeyboard** [comment]
@natew I appreciate what you do man. You're a godsend!

**Comment by jones-sam** [comment]
I am still getting this error on the latest version, works fine on iOS but doesn't work on Android
