### ISSUE TITLE
[Windows] Required appropriate loader error when running yarn web 

### ISSUE THREAD

**Issue by vktrwlt** [tamagui/tamagui#151]
**Describe the bug**
Received a required appropriate loader error when running `yarn web` on fresh install using `npx create-tamagui-app@latest my-app` 

```
error - ../packages/app/provider/index.tsx
Module parse failed: Unexpected token (5:46)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { TamaguiProviderProps } from '@my/ui'
|
> export function Provider({ children, ...rest }: TamaguiProviderProps) {
|   return (
|     <Tamagui.Provider disableInjectCSS defaultTheme="light" {...rest}>
```

**To Reproduce**
1. Start a new project using  `npx create-tamagui-app@latest my-app` 
2. cd to project
3. run `yarn web`

**System Info (please complete the following information):** 
Output of `npx envinfo --system --npmPackages '{vitest,vite,@vitejs/*}' --binaries --browsers`

```
  System:
    OS: Windows 10 10.0.19044
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 15.48 GB / 31.91 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD       
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.134
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)    
    Internet Explorer: 11.0.19041.1566

```

**Comment by BrandonDigital** [comment]
I run yarn and then yarn web. I still get the same issue.

**Comment by abalirac** [comment]
I'm getting the same error just by starting a new project with create-tamagui-app. Any solution?

**Comment by natew** [comment]
Maybe a regression, checking it out now.

**Comment by natew** [comment]
Window support at the moment is not working. I know others have had success with WSL.

**Comment by abalirac** [comment]
Ok thanks. It is a windows OS related problem. I tried it in ubuntu with WSL as you suggested and it is working now. Do you know what is breaking compatibility with windows? I tried, before going into tamagui, standalone projects with next.js, next.js + expo or solito and all worked fine in windows.

**Comment by natew** [comment]
It definitely should work, I just need to find time to get a Windows VM up and running to figure out what's going on.

**Comment by natew** [comment]
So I've really struggled getting an ARM window VM to work, get OOM installing every time across 4 separate installs on 3 different VM apps...

But trying to just manually go through and fix the paths here: https://github.com/tamagui/tamagui/pull/192

Look out for beta 161 within next hour, let me know if it fixes.

**Comment by AviAvinav** [comment]
I wanted to try out tamagui but I am having the same problem as in this issue. I opened a discussion on it a few days ago: https://github.com/tamagui/tamagui/discussions/171. I tried to initiate another app just now and the same issue persists.

Here is the full output from running `yarn web`:

```
➤ YN0000: built @my/ui in 15799 ms
➤ YN0000: Done in 20s 5ms
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Disabling static extraction in development mode for better HMR
info  - automatically enabled Fast Refresh for 1 custom loader
error - ../../packages/app/provider/index.tsx
Module parse failed: Unexpected token (5:46)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { TamaguiProvider, TamaguiProviderProps } from '@my/ui'
|
> export function Provider({ children, ...rest }: Omit<TamaguiProviderProps, 'config'>) {
|   return (
|     <TamaguiProvider config={config} disableInjectCSS defaultTheme="light" {...rest}>
```

**Comment by ALegendsTale** [comment]
Hi all, I'm having the same issue. I attempted to create & run the starter with npm instead of yarn, which gave me a more verbose error. Maybe it can be of some use.

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Disabling static extraction in development mode for better HMR
info  - automatically enabled Fast Refresh for 1 custom loader
      | patched  dist\modules\createDOMProps\index.js
      | patched  dist\cjs\modules\createDOMProps\index.js

Tamagui built config and components:

  - Config: dist\tamagui-node\tamagui.config.js
  - Components: dist\tamagui-node\tamagui-components.config.js

Tamagui Webpack Loader Error TypeError: Cannot read properties of undefined (reading 'includes')
    at parseWithConfig (tamagui-starter\node_modules\@tamagui\static\dist\extractor\createExtractor.js:183:46)
    at Object.parse (tamagui-starter\node_modules\@tamagui\static\dist\extractor\createExtractor.js:104:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async extractToClassNames (tamagui-starter\node_modules\@tamagui\static\dist\extractor\extractToClassNames.js:84:15)
    at async Object.loader2 (tamagui-starter\node_modules\tamagui-loader\dist\cjs\loader.js:56:23)
Tamagui Webpack Loader Error TypeError: Cannot read properties of undefined (reading 'includes')
    at parseWithConfig (tamagui-starter\node_modules\@tamagui\static\dist\extractor\createExtractor.js:183:46)
    at Object.parse (tamagui-starter\node_modules\@tamagui\static\dist\extractor\createExtractor.js:104:14)
    at async extractToClassNames (tamagui-starter\node_modules\@tamagui\static\dist\extractor\extractToClassNames.js:84:15)
    at async Object.loader2 (tamagui-starter\node_modules\tamagui-loader\dist\cjs\loader.js:56:23)
Tamagui Webpack Loader Error TypeError: Cannot read properties of undefined (reading 'includes')
    at parseWithConfig (tamagui-starter\node_modules\@tamagui\static\dist\extractor\createExtractor.js:183:46)
    at Object.parse (tamagui-starter\node_modules\@tamagui\static\dist\extractor\createExtractor.js:104:14)
    at async extractToClassNames (tamagui-starter\node_modules\@tamagui\static\dist\extractor\extractToClassNames.js:84:15)
    at async Object.loader2 (tamagui-starter\node_modules\tamagui-loader\dist\cjs\loader.js:56:23)
Tamagui Webpack Loader Error TypeError: Cannot read properties of undefined (reading 'includes')
    at parseWithConfig (tamagui-starter\node_modules\@tamagui\static\dist\extractor\createExtractor.js:183:46)
    at Object.parse (tamagui-starter\node_modules\@tamagui\static\dist\extractor\createExtractor.js:104:14)
    at async extractToClassNames (tamagui-starter\node_modules\@tamagui\static\dist\extractor\extractToClassNames.js:84:15)
    at async Object.loader2 (tamagui-starter\node_modules\tamagui-loader\dist\cjs\loader.js:56:23)
error - ../../packages/app/provider/index.tsx
Module parse failed: Unexpected token (5:46)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { TamaguiProvider, TamaguiProviderProps } from '@my/ui'
|
> export function Provider({ children, ...rest }: Omit<TamaguiProviderProps, 'config'>) {
|   return (
|     <TamaguiProvider config={config} disableInjectCSS defaultTheme="light" {...rest}>
```

`"Tamagui Webpack Loader Error"` appears to have come from `\node_modules\tamagui-loader\dist\cjs\loader.js` (Line 82)

**Comment by zhamkovv** [comment]
I did this and everything worked 
![image](https://user-images.githubusercontent.com/89290682/192036551-ac438f51-d70b-4ebc-834b-e72311d3d5bd.png)
just delete '/app' from path shouldExtract in next.config.js
`shouldExtract: (path) => {
      if (path.includes('packages')) {
        return true
      }
    },`

**Comment by AviAvinav** [comment]
@zhamkovv I tried this out, it worked for a second and then threw this error:

<img src="https://i.imgur.com/gxljZ8l.png" />

the console however shows no errors

**Comment by zhamkovv** [comment]
Yes! I did it! finally I figured out this problem! now everything works for sure.

1. To resolve bug with Failed module parsing:
![image](https://user-images.githubusercontent.com/89290682/192096579-1fe4acba-2261-4749-8fa5-742d64b89709.png)
2. To fix bug with export is not defined - downgrade next to 12.1.6 version. More - https://github.com/vercel/next.js/issues/38117
![image](https://user-images.githubusercontent.com/89290682/192096661-445158af-5ab0-4171-afd2-98bb9e90a577.png)

**Comment by ALegendsTale** [comment]
@zhamkovv Awesome! This solution seems to work for me as well

**Comment by natew** [comment]
BTW guys, adding 'app' to `withTM` will disable all optimization! I pushed a change to instead do:

```
path.includes(join('packages', 'app'))
```

Which should fix windows support there.

You can test by adding `//! debug` to the top of any features/* components and see if it outputs stuff at compile time.

**Comment by ALegendsTale** [comment]
I went ahead and tested this out on a new project using `npx create-tamagui-app@latest my-app`, and it works for me now!

**Comment by AviAvinav** [comment]
Works for me too!

**Comment by natew** [comment]
This can be closed!?
