### ISSUE TITLE
pressStyle behaviour changed somewhere between 1.6 and 1.49, so all styles have to be stated

### ISSUE THREAD

**Issue by tomhicks** [tamagui/tamagui#1512]
### Current Behavior

I picked up a project using 1.6.3 with Buttons often used like this:
```tsx
<Button chromeless color="black" bg="white" pressStyle={{opacity: 0.9}}>Whatever</Button>
```
When the button is pressed, the `bg` and `color` used to be respected, but now (since I just updated to 1.49.x, thinking it would behave the same due to the semver being a minor) I have to add `bg: "white", color: "black"` into my `pressStyle` to get back the old behaviour.

### Expected Behavior

I would expect the behaviour to remain the same from 1.6 to 1.49 as it is not a major change.

### Tamagui Version

```markdown
1.6.3
```

### Reproduction

```markdown
<Button chromeless color="black" bg="white" pressStyle={{opacity: 0.9}}>Whatever</Button>
```
```


### System Info

_No response_

**Comment by megacherry** [comment]
yeah, this also no longer works:

```
import { Button, styled } from 'tamagui'

export const MyButton = styled(Button, {
  variants: {
    test: {
      true: {
        backgroundColor: 'yellow',
        pressStyle: {
          backgroundColor: 'red',
        },
      },
    },
  } as const,
})
```

backgroundColor red is not respected :/

**Comment by natew** [comment]
yall gotta fill in the info - platform especially

**Comment by natew** [comment]
fixed in `1.50.1` (going out in a minute)

**Comment by iykazrji** [comment]
Has this been fixed? I am experiencing the same behavior in `1.73.0`.

**Comment by natew** [comment]
1.73.1 fixes
