### ISSUE TITLE
ToastViewport errors out when using a custom config

### ISSUE THREAD

**Issue by GraemeHarris** [tamagui/tamagui#1513]
### Current Behavior

Error trace is as follows:
```
Error: Missing tamagui config, you either have a duplicate config, or haven't set it up. Be sure createTamagui is called before rendering.

This error is located at:
    in ViewportWrapper (created by ToastViewport)
    in ToastViewport (created by HomeScreen)
    ...
```
Error seems to occur in /node_modules/@tamagui/toast/node_modules/@tamagui/web/dist/cjs/config.js
Should be noted that I intend to only use tamagui for native development so maybe some setting clash I have to configure?

I have created my `<ToastViewport/>` within  `<TamaguiProvider config={config}>` and the config both exists and works fine without the `<ToastViewport>`.

Let me know if you need any more info or if I missed anything obvious 🙏

### Expected Behavior

Should just give me toast 🥐

### Tamagui Version

```markdown
"@tamagui/config": "^1.35.8",
"@tamagui/core": "^1.35.8",
"@tamagui/toast": "^1.49.6"
```

### Reproduction

```markdown
I believe to reproduce you just need to use the ToastViewport within a custom config TamaguiProvider.
```

**Comment by wowvain-dev** [comment]
I face the same issue. I've installed burnt (with expo for the native plugin) aswell. Whenever I try to use <ToastViewport /> I get:

` ERROR  Error: Missing tamagui config, you either have a duplicate config, or haven't set it up. Be sure createTamagui is called before rendering.

This error is located at:
    in ViewportWrapper (created by ToastViewport)
    in ToastViewport (created by Page)
    in RCTView (created by View)
    in View (created by Page)
    in RCTView (created by View)
    in View
    in Unknown (created by Page)
    in Page
    in Unknown (created by Route((auth)/register))
    in Route (created by Route((auth)/register))
    in Route((auth)/register) (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by QualifiedSlot)
    in QualifiedSlot (created by Slot)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by QualifiedNavigator)
    in QualifiedNavigator (created by Navigator)
    in Navigator (created by Slot)
    in Slot (created by RootLayoutNav)
    in AuthProvider (created by RootLayoutNav)
    in _ToastImperativeProvider (created by ToastProvider)
    in ToastProviderProvider (created by ToastProvider)
    in ToastCollectionProviderProvider (created by ToastCollectionProvider)
    in ToastCollectionProvider (created by ToastProvider)
    in ToastProvider (created by RootLayoutNav)
    in PortalProviderComponent (created by _TamaguiProvider)
    in Theme2 (created by _ThemeProvider)
    in _ThemeProvider (created by _TamaguiProvider)
    in _TamaguiProvider (created by _TamaguiProvider)
    in _TamaguiProvider (created by RootLayoutNav)
    in ThemeProvider (created by RootLayoutNav)
    in RootLayoutNav (created by RootLayout)
    in RootLayout
    in Try
    in Unknown
    in Unknown (created by Route())
    in Route (created by Route())
    in Route() (created by ContextNavigator)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by wrapper)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by wrapper)
    in wrapper (created by ContextNavigator)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by ContextNavigator)
    in ContextNavigator (created by ExpoRoot)
    in ExpoRoot (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App) (created by ErrorOverlay)
    in ErrorToastContainer (created by ErrorOverlay)
    in ErrorOverlay
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes`

**Comment by real-marshal** [comment]
After a few hours of banging my head, I came to the conclusion that this happens due to version mismatch of different tamagui packages. I was finally able to fix this by updating every `@tamagui/` package I had installed to 1.54.0 and then locking `tamagui` version to 1.54.0.

**Comment by alitnk** [comment]
As @real-marshal mentioned this is because you installed a newer version of `@tamagui/toast` compared to the rest of your tamagui dependencies. I added a note the error on #1570.
Closing this but feel free to re-open or continue discussion if it's not resolved

**Comment by GraemeHarris** [comment]
Thanks @real-marshal @alitnk! Cleared it up
