### ISSUE TITLE
Padding Bug in ScrollView Native

### ISSUE THREAD

**Issue by tjapa** [tamagui/tamagui#1514]
### Current Behavior

Using padding on the ScrollView cuts the content in Expo Android.

Current behavior in Expo Android:

https://github.com/tamagui/tamagui/assets/17579637/14e3a699-3062-4776-9f0d-55d03b0e26aa

Code:

```tsx
export function HomeScreen() {
  return (
    <XStack fullscreen>
      <YStack flexGrow={1}>
        <XStack>
          <H1>HEADER</H1>
        </XStack>
        <ScrollView bc="blue" padding="$5">
          <H1>Welcome 1</H1>
          <H1>Welcome 2</H1>
          <H1>Welcome 3</H1>
          <H1>Welcome 4</H1>
          <H1>Welcome 5</H1>
          <H1>Welcome 6</H1>
          <H1>Welcome 7</H1>
          <H1>Welcome 8</H1>
          <H1>Welcome 9</H1>
          <H1>Welcome 10</H1>
          <H1>Welcome 11</H1>
          <H1>Welcome 12</H1>
          <H1>Welcome 13</H1>
          <H1>Welcome 14</H1>
        </ScrollView>
        <H1>FOOTER</H1>
      </YStack>
    </XStack>
  )
}
```

### Expected Behavior

Expected behavior (works in the web!):

https://github.com/tamagui/tamagui/assets/17579637/799f7ee3-3142-4062-b8cd-3861d13a9c69

### Tamagui Version

```markdown
1.50.2
```

### Reproduction

```markdown
https://github.com/tjapa/tamagui-scroll-view-padding-bug
```

**Comment by tjapa** [comment]
Works if I add the padding to contentContainerStyle

```tsx
...
      <ScrollView bc="blue" contentContainerStyle={{ padding: 32 }}>
...
```

But breaks if a try:

```tsx
...
      <ScrollView bc="blue" contentContainerStyle={{ padding: '$5' }}>
...
```
![image](https://github.com/tamagui/tamagui/assets/17579637/29c47790-a2b0-4bec-9801-00e312f23c86)

**Comment by natew** [comment]
Yes contentContainerStyle doesn't accept tamagui props, if you want that just add an inner view. Closing as this is a feature request and those are more for discussions.

**Comment by JeffreyWardman** [comment]
I don't think this should have been closed. The issue occurs because the scrollview defaults to fullscreen mode with absolute positioning and the header in the example offsets the start and stop without accommodation.

```
// @tamagui/scroll-view/src

export const ScrollView = styled(ScrollViewNative, {
  name: 'ScrollView',
  scrollEnabled: true,

  variants: {
    fullscreen: {
      true: fullscreenStyle,
    },
  } as const,
})
```
