### ISSUE TITLE
Bug: Moti animation driver breaks with some complex styles (media queries?)

### ISSUE THREAD

**Issue by nderscore** [tamagui/tamagui#1520]
### Current Behavior

When using the Moti animation driver on a component, sometimes the animation does not occur. 

I haven't narrowed down the specific cause yet, but it seems to be related to combining variants and media query styles together.

The React Native animation driver does not have this issue. I've only tested this on web so far - its possible this doesn't happen on native.

### Expected Behavior

Animation 

### Tamagui Version

```markdown
1.50.3
```

### Reproduction

I've created a reproduction here:

https://github.com/nderscore/tamagui-moti-web-bug

Please see the notes in the readme.

**Comment by natew** [comment]
wonder - can you check something... a bit tricky but in createComponent:

<img width="1090" alt="CleanShot 2023-08-09 at 12 31 25@2x" src="https://github.com/tamagui/tamagui/assets/12100/690f03e5-1bb9-41e5-8366-9f5250b856e5">


change this useEffect into a useLayoutEffect... i think moti and the css driver get mad at each other about this depending on which way i go... you may need to patch it in node_modules/dist/cjs or esm not sure, and then clear cache and restart

**Comment by nandorojo** [comment]
> you may need to patch it in node_modules/dist/cjs or esm not sure

If it's for Next.js it might be in `dist/module` (if tamagui uses that).

I've been having `enterStyle` issues with the CSS driver so it may be related. I don't think responsive styles were related in my case. It was simply `enterStyle` not working. `useLayoutEffect` would presumably clear out the initial state so it would jump straight to the end state.

If we can figure out this whole zero-render-pseudo Moti branch then this should work fine with the moti driver, since a simple `mounted` shared value fired in an effect will for sure work (Moti uses this for `from` with no issues).

**Comment by nderscore** [comment]
> change this useEffect into a useLayoutEffect...

I tried replacing the `useEffect` on that line with `(typeof window === 'undefined' ? useEffect : useLayoutEffect)`. It didn't make a difference unfortunately.

Also maybe worth mentioning that I'm not using an `(enter/exit)Style` on this component. This animation is triggered by toggling between variants.

**Comment by nderscore** [comment]
I took another look at this today... and I think I've tracked down the actual condition that causes it.

It only seems to happen when percentage values (eg. `100%`, `-100%`, etc) are stored in tokens.

Given these space tokens:

```tsx
const spacetokens = {
  // ...
  full: '100%',
  '-full: '-100%',
  none: '0%',
}
```

The following does not animate correctly:

```tsx
variants: {
  open: {
    true: {
      x: '$none',
    },
    false: {
      x: '$-full',
    },
  },
} as const,
```

But this does work:

```tsx
variants: {
  open: {
    true: {
      x: '0%',
    },
    false: {
      x: '-100%',
    },
  },
} as const,
```

**Comment by natew** [comment]
Hmmmm, can you add `debug="verbose"` and see whats going on with that resolution?

**Comment by natew** [comment]
Had to revert that change we need to do it a bit differently and fix ssr issues with the RN animated driver.

**Comment by TheEhsanSarshar** [comment]
I think this is fixed now!
