### ISSUE TITLE
Can't build native app with fresh using next-expo-solito-monorepo

### ISSUE THREAD

**Issue by Djiit** [tamagui/tamagui#1522]
### Current Behavior

hey team, 

just creating a new projcet from the template and running `eas build`, I've got an error and can't go forward.
Did I miss anything?

```
[RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets FAILED
[RUN_GRADLEW] Error: ../../node_modules/expo-router/entry.js:Invalid call at line <unknown>: undefined
[RUN_GRADLEW] First argument of `require.context` should be a string denoting the directory to require.
[RUN_GRADLEW]     at transformJS (/private/var/folders/zk/190hbvt9047fdkkybctwrxhw0000gn/T/eas-build-local-nodejs/be21c26e-9bcf-4aaa-9d0a-88bf8a9d97cd/build/node_modules/metro-transform-worker/src/index.js:237:15)
[RUN_GRADLEW]     at transformJSWithBabel (/private/var/folders/zk/190hbvt9047fdkkybctwrxhw0000gn/T/eas-build-local-nodejs/be21c26e-9bcf-4aaa-9d0a-88bf8a9d97cd/build/node_modules/metro-transform-worker/src/index.js:372:16)
[RUN_GRADLEW]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[RUN_GRADLEW]     at async Object.transform (/private/var/folders/zk/190hbvt9047fdkkybctwrxhw0000gn/T/eas-build-local-nodejs/be21c26e-9bcf-4aaa-9d0a-88bf8a9d97cd/build/node_modules/metro-transform-worker/src/index.js:518:12)
[RUN_GRADLEW] error ../../node_modules/expo-router/entry.js: ../../node_modules/expo-router/entry.js:Invalid call at line <unknown>: undefined
[RUN_GRADLEW] First argument of `require.context` should be a string denoting the directory to require.
[RUN_GRADLEW] w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
[RUN_GRADLEW] 557 actionable tasks: 557 executed
[RUN_GRADLEW] FAILURE: Build completed with 2 failures.
[RUN_GRADLEW] 1: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:createBundleReleaseJsAndAssets'.
[RUN_GRADLEW] > Process 'command 'node'' finished with non-zero exit value 1
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] 2: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] java.lang.StackOverflowError (no error message)
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 1m 17s
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
npx exited with non-zero code: 1
    Error: build command failed.
```

### Expected Behavior

The eas build command works

### Tamagui Version

```markdown
latest?
```

### Reproduction

```markdown
npm create tamagui@latest
# let's use the default name "myapp"
cd myapp/apps/expo
eas build -p android --local --profile development
```
```


### System Info

```markdown
npx envinfo --system --npmPackages --binaries --browsers

  System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 2.27 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.9.0 - ~/.nvm/versions/node/v19.9.0/bin/node
    Yarn: 3.5.0 - /opt/homebrew/bin/yarn
    npm: 9.6.3 - ~/.nvm/versions/node/v19.9.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Firefox: 116.0.2
    Safari: 16.6
```
```

**Comment by ac009527** [comment]
> ### Current Behavior
> hey team,
> 
> just creating a new projcet from the template and running `eas build`, I've got an error and can't go forward. Did I miss anything?
> 
> ```
> [RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets FAILED
> [RUN_GRADLEW] Error: ../../node_modules/expo-router/entry.js:Invalid call at line <unknown>: undefined
> [RUN_GRADLEW] First argument of `require.context` should be a string denoting the directory to require.
> [RUN_GRADLEW]     at transformJS (/private/var/folders/zk/190hbvt9047fdkkybctwrxhw0000gn/T/eas-build-local-nodejs/be21c26e-9bcf-4aaa-9d0a-88bf8a9d97cd/build/node_modules/metro-transform-worker/src/index.js:237:15)
> [RUN_GRADLEW]     at transformJSWithBabel (/private/var/folders/zk/190hbvt9047fdkkybctwrxhw0000gn/T/eas-build-local-nodejs/be21c26e-9bcf-4aaa-9d0a-88bf8a9d97cd/build/node_modules/metro-transform-worker/src/index.js:372:16)
> [RUN_GRADLEW]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> [RUN_GRADLEW]     at async Object.transform (/private/var/folders/zk/190hbvt9047fdkkybctwrxhw0000gn/T/eas-build-local-nodejs/be21c26e-9bcf-4aaa-9d0a-88bf8a9d97cd/build/node_modules/metro-transform-worker/src/index.js:518:12)
> [RUN_GRADLEW] error ../../node_modules/expo-router/entry.js: ../../node_modules/expo-router/entry.js:Invalid call at line <unknown>: undefined
> [RUN_GRADLEW] First argument of `require.context` should be a string denoting the directory to require.
> [RUN_GRADLEW] w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
> [RUN_GRADLEW] 557 actionable tasks: 557 executed
> [RUN_GRADLEW] FAILURE: Build completed with 2 failures.
> [RUN_GRADLEW] 1: Task failed with an exception.
> [RUN_GRADLEW] -----------
> [RUN_GRADLEW] * What went wrong:
> [RUN_GRADLEW] Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> [RUN_GRADLEW] > Process 'command 'node'' finished with non-zero exit value 1
> [RUN_GRADLEW] * Try:
> [RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
> [RUN_GRADLEW] > Run with --info or --debug option to get more log output.
> [RUN_GRADLEW] > Run with --scan to get full insights.
> [RUN_GRADLEW] ==============================================================================
> [RUN_GRADLEW] 2: Task failed with an exception.
> [RUN_GRADLEW] -----------
> [RUN_GRADLEW] * What went wrong:
> [RUN_GRADLEW] java.lang.StackOverflowError (no error message)
> [RUN_GRADLEW] * Try:
> [RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
> [RUN_GRADLEW] > Run with --info or --debug option to get more log output.
> [RUN_GRADLEW] > Run with --scan to get full insights.
> [RUN_GRADLEW] ==============================================================================
> [RUN_GRADLEW] * Get more help at https://help.gradle.org
> [RUN_GRADLEW] BUILD FAILED in 1m 17s
> [RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
> 
> Build failed
> Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
> npx exited with non-zero code: 1
>     Error: build command failed.
> ```
> 
> ### Expected Behavior
> The eas build command works
> 
> ### Tamagui Version
> ```
> latest?
> ```
> 
> ### Reproduction
> ```
> npm create tamagui@latest
> # let's use the default name "myapp"
> cd myapp/apps/expo
> eas build -p android --local --profile development
> ```
> 
> ```
> 
> 
> ### System Info
> 
> ```markdown
> npx envinfo --system --npmPackages --binaries --browsers
> 
>   System:
>     OS: macOS 13.5
>     CPU: (8) arm64 Apple M1 Pro
>     Memory: 2.27 GB / 32.00 GB
>     Shell: 5.9 - /bin/zsh
>   Binaries:
>     Node: 19.9.0 - ~/.nvm/versions/node/v19.9.0/bin/node
>     Yarn: 3.5.0 - /opt/homebrew/bin/yarn
>     npm: 9.6.3 - ~/.nvm/versions/node/v19.9.0/bin/npm
>   Browsers:
>     Chrome: 115.0.5790.170
>     Firefox: 116.0.2
>     Safari: 16.6
> ```


I have the same problem bro, do you already know how to solve it?

**Comment by Sir-hennihau** [comment]
build also failed for me, somehow 90% of the starters have build problems, which kinda sucks

**Comment by Sir-hennihau** [comment]
push again for that issue, its a big dealbreaker and will prevent a lot of people from trying the library :/

**Comment by bakhytk** [comment]
For those facing the same issue, you can follow the steps mentioned in the 
[Expo Forums Post](https://forums.expo.dev/t/eas-build-success-with-profile-development-but-fails-with-profile-preview/71867/2)

To implement the fix, make the following change in your `apps/expo/metro.config.js` file:

replace: 

`'transform-inline-environment-variables',`

with:

`["transform-inline-environment-variables", {
                "exclude": [
                    "EXPO_ROUTER_APP_ROOT",
                    "EXPO_ROUTER_PROJECT_ROOT",
                    "EXPO_ROUTER_IMPORT_MODE",
                    "EXPO_ROUTER_IMPORT_MODE_ANDROID",
                    "EXPO_ROUTER_IMPORT_MODE_IOS",
                    "EXPO_ROUTER_IMPORT_MODE_WEB",
                ]
            }]`

**Comment by Sir-hennihau** [comment]
hey @bakhytk , thanks for the input. you have a small mistake in your answer, you have to mage the changes in `apps/expo/babel.config.js` and not in `apps/expo/metro.config.js`.

here is a complete config that i could run a complete build with

```
module.exports = function (api) {
  api.cache(true)
  return {
    presets: [['babel-preset-expo', { jsxRuntime: 'automatic' }]],
    plugins: [
      require.resolve('expo-router/babel'),
      [
        require.resolve('babel-plugin-module-resolver'),
        {
          root: ['../..'],
          alias: {
            // define aliases to shorten the import paths
            app: '../../packages/app',
            '@my/ui': '../../packages/ui',
          },
          extensions: ['.js', '.jsx', '.tsx', '.ios.js', '.android.js'],
        },
      ],
      // if you want reanimated support
      // 'react-native-reanimated/plugin',
      ...(process.env.EAS_BUILD_PLATFORM === 'android'
        ? []
        : [
            [
              '@tamagui/babel-plugin',
              {
                components: ['@my/ui', 'tamagui'],
                config: './tamagui.config.ts',
              },
            ],
          ]),
      [
        'transform-inline-environment-variables',
        {
          exclude: [
            'EXPO_ROUTER_APP_ROOT',

            'EXPO_ROUTER_PROJECT_ROOT',

            'EXPO_ROUTER_IMPORT_MODE',

            'EXPO_ROUTER_IMPORT_MODE_ANDROID',

            'EXPO_ROUTER_IMPORT_MODE_IOS',

            'EXPO_ROUTER_IMPORT_MODE_WEB',
          ],
        },
      ],
    ],
  }
}
```

**Comment by Sir-hennihau** [comment]
On the other hand I have to add even though my development build was successful, I couldn't get my Dev build to fetch any changes that I did to my JavaScript. 

Don't know yet why. Using Expo fetches the changes, but the dev build not.

**Comment by dohomi** [comment]
I am curious if the latest no-config version of Tamagui potentially remove the `'transform-inline-environment-variables'` section?

**Comment by natew** [comment]
Yea please try the latest, we've removed *all* need for any config at all. Tamagui should just work without setup besides installing and setting up the design system / TamaguiProvider.

**Comment by Sir-hennihau** [comment]
dev build seems to complete after installing `jre`, `jdk`,  and `ninja` for android

right in time. i was just about to set it up manually this morning :D
