### ISSUE TITLE
SharedBaseExtraStyleProps display doesn't include `inline-block`

### ISSUE THREAD

**Issue by EliRobinson** [tamagui/tamagui#1525]
In the @Tamagui -> web -> src -> `types.tsx` file, there is a type called `SharedBaseExtraStyleProps` which contains the `display` property, however it doesn't include `inline-block` is there a reason to not just default to all supported `display` values from CSS similar to `cursor` or `contain` which are pulling their types from the CSSTypes lib?

**Comment by natew** [comment]
cursor and contain are "extra" they have on effect on native, whereas display is shared between the two so we keep the stricter types
