### ISSUE TITLE
Creating selectable text

### ISSUE THREAD

**Issue by spfaul** [tamagui/tamagui#1536]
I am trying to create a selectable text component where the user is able to copy/paste/etc.

Consider the following
```js
// import { Text } from "react-native"; // this works!
// import { Text } from "tamagui"; // this doesn't work...

<Text selectable={true}>asdasd</Text>
```
Passing in `selectable` prop does not achieve same functionality when using Tamagui's `Text` component, however it works in React Native's component. Testing on Expo Go Android.

How should I implement selectable text using Tamagui's Text component?

**Comment by TheEhsanSarshar** [comment]
check this to see if it works ?
```jsx
import { Text } from 'tamagui'
import MText = styled(Text, {
   variants: {
     selectable: {
       true: {
         userSelect: 'text',
         cursor: 'text',
         selectable: true
       },
       false: {
         userSelect: 'none',
         cursor: 'default',
         selectable: true
       },
     },
   }
})
```
if it does, need a simple fix in tamagui

**Comment by spfaul** [comment]
I think you meant `const` instead of `import` on that second line but either way I'm still unable to select the text (Android Expo Go)

**Comment by alitnk** [comment]
Upgrading to >=[v1.57.1](https://github.com/tamagui/tamagui/releases/tag/v1.57.1) should fix this @spfaul

**Comment by spfaul** [comment]
Just seeing this now but thanks so much! works perfectly 🙏🙏
