### ISSUE TITLE
Unable to resolve module nanoid/non-secure

### ISSUE THREAD

**Issue by anandparmar-quark** [tamagui/tamagui#154]
**Describe the bug**

After initializing React Native CLI project and adding the following dependencies:

> {
  "name": "ui_test_with_tamagui",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@tamagui/babel-plugin": "^1.0.1-beta.133",
    "react": "18.0.0",
    "react-native": "0.69.3",
    "tamagui": "^1.0.1-beta.133"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.70.3",
    "react-test-renderer": "18.0.0",
    "@types/react-native": "^0.67.3",
    "@typescript-eslint/eslint-plugin": "^5.17.0",
    "@typescript-eslint/parser": "^5.17.0",
    "typescript": "^4.4.4"
  },
  "jest": {
    "preset": "react-native"
  }
}

getting this error: 

> error: Error: Unable to resolve module nanoid/non-secure from ui_test_with_tamagui/node_modules/@tamagui/portal/dist/cjs/GorhomPortal.js: nanoid/non-secure could not be found within the project or in these directories:
  node_modules
  ../node_modules
  31 | module.exports = __toCommonJS(GorhomPortal_exports);
  32 | var import_core = require("@tamagui/core");
> 33 | var import_non_secure = require("nanoid/non-secure");
     |                                  ^
  34 | var import_react = require("react");
  35 | var import_react2 = __toESM(require("react"));
  36 | var ACTIONS = /* @__PURE__ */ ((ACTIONS2) => {
    at ModuleResolver.resolveDependency

**babel.config.js**

> module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      '@tamagui/babel-plugin',
      {
        components: ['tamagui'],
        config: './tamagui.config.ts',
        importsWhitelist: ['constants.js', 'colors.js'],
        logTimings: true,
        disableExtraction: true,
      }
    ]
  ]
};

Please help me to resolve this issue. Let me know if more information is needed. Thanks in advance.

**Comment by natew** [comment]
Will be fixed in https://github.com/tamagui/tamagui/pull/156/commits/b52c144bab9098fce2b500f2d4abd722a5ea409a

**Comment by natew** [comment]
Check for fix in beta.134

**Comment by anandparmar-quark** [comment]
Thanks for the responses. I will try the latest beta. 

Thank you so much for the awesome work! 🙌
