### ISSUE TITLE
[Issue] Custom color tokens not working for Lucide Icons and LinearGradient

### ISSUE THREAD

**Issue by trymbill** [tamagui/tamagui#1543]
### Current Behavior

Given custom color tokens:
```ts
const tokens = createTokens({
  ...tamaguiTokens,
  color: {
    white: '#FFFFFF',
    black: '#000000',
  },
})
```

when used on Lucide Icons or LinearGradient:
```ts
<Button icon={AlarmCheck} color="$black">This button wont show an icon</Button>
<LinearGradient colors={['$white', '$black']} start={[0, 0]} end={[1, 1]} h={40} w={300} />
```

returns no color values and instead has `react-native-svg` complain about `"$black" is not a valid color or brush`.

### Expected Behavior

Custom color tokens should work on Lucide Icons and LinearGradient. Confirmed that this started happening in `v1.48.0`. `v1.47.9` works as expected.

### Tamagui Version

```markdown
v1.48.0
```

### Reproduction

```markdown
https://github.com/trymbill/color-tokens-to-icons-bug
```

### System Info

```markdown
System:
  OS: macOS 13.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 80.81 MB / 16.00 GB
  Shell: 3.6.0 - /opt/homebrew/bin/fish
Binaries:
  Node: 18.17.1 - ~/.local/share/nvm/v18.17.1/bin/node
  Yarn: 3.5.0 - ~/.local/share/nvm/v18.17.1/bin/yarn
  npm: 9.6.7 - ~/.local/share/nvm/v18.17.1/bin/npm
Browsers:
  Brave Browser: 108.1.46.153
  Chrome: 115.0.5790.170
  Safari: 16.2
```

**Comment by trymbill** [comment]
From the repro repo, notice that `red` pulled from `@tamagui/colors` works fine, but the same exact values for `green` but with a different name (i.e. `somethingotherthangreen1` through `somethingotherthangreen12`) does not work.

<img width="524" alt="Screenshot 2023-08-16 at 09 55 10" src="https://github.com/tamagui/tamagui/assets/658727/61144b38-3b76-4446-b6b9-fc16a8e8bd6e">

**Comment by natew** [comment]
fixed this, technically you're supposed to call createTokens() and this is why it was breaking, but i made it automatically do createTokens. it was a bit more involved that i imagined and fixed a few bugs along the way. check `1.52.7`
