### ISSUE TITLE
Out of place warning of `fontfamily "Inter" is not a system font and has not..."

### ISSUE THREAD

**Issue by astriskit** [tamagui/tamagui#1546]
Warning: Out of place warning of `fontfamily "Inter" is not a system font and has not been loaded through Font.loadAsync.

Setup: Expo-49 with expo-router, tamagui - 1.52.4

Verified using the `Fonts.isLoaded` - the inner-components/tamagui-text based components are not mounted before the font is loaded.

Any clue? Thanks.

**Comment by natew** [comment]
gotta have a repro, sorry

**Comment by shariandabre** [comment]
having same error.

**Comment by astriskit** [comment]
@natew - here is the repo that when run would repro it; feel free to reopen this, if that'd do.

https://github.com/astriskit/t-expo-tamagui

**Comment by lorenzolaricchia** [comment]
I'm having the same error with the last version of expo and tamagui.

**Comment by asyndesis** [comment]
Happens to me when I try to add text to a button without wrapping in a `<Text></Text>`

<img width="548" alt="Screenshot 2023-09-17 at 10 26 28 AM" src="https://github.com/tamagui/tamagui/assets/1721012/31394697-8082-46cd-b940-6eb71ecde614">

#### Works without erroring
```jsx
<Button icon={<Plus size="$4" />}>
  <Text>Hello world</Text>
</Button>
```

#### Errors with `fontFamily "Inter" is not a system font and has not been loaded through Font.loadAsync.`
```
<Button icon={<Plus size="$4" />}>
Hello world
</Button>
```

Followed most recent expo install guide on site:
@natew - is there some config that might be missing?

**Comment by mweel1** [comment]
+1

**Comment by JackNgulale** [comment]
Hello peaple, I have de solution.

tamagui example

const [loaded] = useFonts({
    Inter: require("@tamagui/font-inter/otf/Inter-Medium.otf"),
    InterBold: require("@tamagui/font-inter/otf/Inter-Bold.otf"),
  });
  
  how you have to do
  
  const [loaded] = useFonts({
    Inter: require("./assets/Inter-Medium.otf"),
    InterBold: require("./assets/Inter-Bold.otf"),
  });
  
  obs: copy or cut the font from @tamagui/font-inter/otf to your folder assets.
  
  it's worked for me, try to do same thing
