### ISSUE TITLE
 Warning: React has detected a change in the order of Hooks called by Sheet.

### ISSUE THREAD

**Issue by shariandabre** [tamagui/tamagui#1551]
### Current Behavior

I am using expo router in my app. One of my pages contain sheet,So whenever I navigate to it and try to go back it gives me this errors :

1.  Warning: React has detected a change in the order of Hooks called by Sheet. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
1. useSyncExternalStore       useSyncExternalStore
2. useRef                     useRef
3. useRef                     useRef
4. useContext                 useContext
5. useState                   useContext
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2.TypeError: Cannot read property 'length' of undefined

This error is located at:
    in Sheet

### Tamagui Version

```markdown
^1.52.2
```

### Reproduction

```markdown
.
```

**Comment by natew** [comment]
no repro and don't see it myself, nothing i can see in the source
