### ISSUE TITLE
Add Tailwind-esque Style Parsing

### ISSUE THREAD

**Issue by lewxdev** [tamagui/tamagui#1574]
Historically, I haven't been the biggest fan of tailwind. But working with tamagui, I'm starting to see some of the merit to it: being able to separate out style props from component props could help improve the DX in specific use cases.

## What I'm proposing

Instead of a component like...
```tsx
<Input
  autoCorrect={false}
  backgroundColor="$slate2"
  borderColor="$slate6"
  borderWidth={3}
  color="$slate9"
  placeholder="Enter your name"
  size="$5"
  value={firstName}
  onChangeText={setFirstName}
/>
```

We could do...
```tsx
<Input
  style="bg-slate2 boc-slate6 bw-3 col-slate9 size-5"
  autoCorrect={false}
  placeholder="Enter your name"
  value={firstName}
  onChangeText={setFirstName}
/>
```

- Uses the [recommended/default shorthands](https://github.com/tamagui/tamagui/blob/master/packages/shorthands/src/index.tsx), as prefixes
- Could potentially allow for integrating with the tailwind ecosystem of tools and plugins (and/or copy their homework more easily, see #1573)
- Reduces unnecessary verbosity when it comes to styling

At first this can be an experimental opt-in feature. The `style` prop on `TamaguiComponent` could be a union of `StyleProp | string` when the feature is enabled which parses and handles styling just as the props would

**Comment by alitnk** [comment]
Related: https://github.com/tamagui/tamagui/pull/234
