### ISSUE TITLE
Text can not convert lineHeight to px 

### ISSUE THREAD

**Issue by gigasource** [tamagui/tamagui#158]
**Describe the bug**
I use Stylesheet like that : 
<img width="315" alt="image" src="https://user-images.githubusercontent.com/56248437/183230593-3abc4737-7c3f-4890-894f-c33aa44caf71.png">
Result: Text can not convert lineHeight to px.

**Comment by natew** [comment]
Not sure I understand, what's the issue on tamagui?

**Comment by gigasource** [comment]
Text component from react-native-web can convert lineHeight to px, i think tamagui should do that too .

**Comment by natew** [comment]
That does work, need a repro case to debug.
