### ISSUE TITLE
Switch.Thumb slides only halfway when height and width are explicitly set

### ISSUE THREAD

**Issue by AleksandarRoncevic** [tamagui/tamagui#1591]
### Current Behavior

I've encountered an issue where the slide behaviour of the Switch.Thumb differs based on whether the dimensions (height and width) are explicitly set on the thumb itself versus being inherited from the Switch component that wraps around it. When explicitly setting the dimensions (height and width) of the Switch.Thumb, it doesn't slide all the way but only halfway through.
![image](https://github.com/tamagui/tamagui/assets/68542174/24c37624-996a-44aa-a888-ca54c58f39d4)

### Expected Behavior

The expected behaviour is that the sliding of the thumb should be consistent regardless of whether the dimensions (height and width) are explicitly set or not.

### Tamagui Version

```markdown
1.48.2
```

### Reproduction

```markdown
Using a Switch in this manner will reproduce the sliding behaviour of the Thumb that is attached in the above section.
    <Switch
        backgroundColor={isChecked ? "green" : "gray"}
        onCheckedChange={onChange}
        checked={isChecked}
        width={44}
        height={24}
        animateOnly={["backgroundColor"]}
        animation={"fast"}
      >
        <Switch.Thumb
          backgroundColor={"white"}
          animation={"fast"}
          height={20}
          width={20}
        />
```

**Comment by natew** [comment]
I made some changes in 1.58 that should help with this, let me know if they work
