### ISSUE TITLE
Vite doesn't work

### ISSUE THREAD

**Issue by stereobooster** [tamagui/tamagui#1592]
### Current Behavior

When I run `yarn dev:vite` for `Simple Web - Learning only` project it shows empty page. There are no errors in console.

Off topic:

Webpack config uses `esbuild`, but Vite config uses `plugin-react-swc`. As far as I know Vite uses by default esbuild. Why do we need to switch to swc?

> Uses esbuild and Babel, achieving fast HMR with a small package footprint and the flexibility of being able to use the Babel transform pipeline. **Without additional Babel plugins, only esbuild is used during builds.**
>
> -- https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react

### Expected Behavior

render application

### Tamagui Version

```markdown
1.57.4
```

### Reproduction

```markdown
https://github.com/stereobooster/tamagui-myapp
```

### System Info

```markdown
System:
    OS: macOS 11.6.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 199.27 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.6.12 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 15.5
  npmPackages:
    @manypkg/cli: ^0.19.1 => 0.19.2
    @pmmmwh/react-refresh-webpack-plugin: ^0.5.10 => 0.5.11
    @tamagui/animations-css: latest => 1.57.4
    @tamagui/core: latest => 1.57.4
    @tamagui/create-theme: latest => 1.57.4
    @tamagui/react-native-svg: latest => 1.57.4
    @tamagui/vite-plugin: latest => 1.57.4
    @vitejs/plugin-react-swc: ^3.3.0 => 3.3.2
    async-retry: 1.3.1 => 1.3.1
    babel-polyfill: ^6.26.0 => 6.26.0
    css-loader: ^5.2.4 => 5.2.7
    esbuild-loader: ^3.0.1 => 3.2.0
    esbuild-register: ^3.4.2 => 3.4.2
    file-loader: ^6.2.0 => 6.2.0
    html-webpack-plugin: ^5.5.0 => 5.5.3
    mini-css-extract-plugin: ^2.7.2 => 2.7.6
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    react-native-web: ^0.18.10 => 0.18.12
    react-refresh: ^0.14.0 => 0.14.0
    style-loader: ^3.3.1 => 3.3.3
    tamagui: latest => 1.57.4
    tamagui-loader: latest => 1.57.4
    thread-loader: ^3.0.4 => 3.0.4
    url-loader: ^4.1.1 => 4.1.1
    vite: ^4.3.0 => 4.4.9
    webpack: ^5.74.0 => 5.88.2
    webpack-bundle-analyzer: ^4.5.0 => 4.9.0
    webpack-cli: ^4.9.2 => 4.10.0
    webpack-dev-server: ^4.8.1 => 4.15.1
```

**Comment by natew** [comment]
fixed if you make a new one, also esbuild doesn't have react refresh support for hot reloading, thats where swc comes from!

**Comment by stereobooster** [comment]
@vitejs/plugin-react claims to support `Fast Refresh`:

> enable [Fast Refresh](https://www.npmjs.com/package/react-refresh) in development

Or it doesn't work for this case? (Just curious. Has nothing to do with original issue)

**Comment by stereobooster** [comment]
About `type: "module"` and why it doesn't wokr. Tamagui provides esm distribution, but NodeJS doesn't know those are esm files. In order to change this you can and `package.json` in `/dist/esm` folder, with:

```json
{
    "type": "module"
}
```

But then it would complain about imports like this 

```js
import { extensions } from "./extensions";
```

because it can't resolve modules like this in esm, it should be changed to (**.js**):


```js
import { extensions } from "./extensions.js";
```

And then it will complain about csm packages like this:

```js
import { readFile } from "fs/promises";
```

This resolution process is a mess. But maybe it will help someone
