### ISSUE TITLE
Tamagui site build failure during "yarn site:prod" test with no changes

### ISSUE THREAD

**Issue by johnsimeroth** [tamagui/tamagui#1597]
### Current Behavior

While following 'contributing' instructions (for a simple typo fix) everything web related was successful until `yarn site:prod` which gives the following error despite no changes made, and successful `yarn site`, and `yarn site:extract` builds. Here is the error:

```
Failed to compile.
./pages/api/studio/procedure.ts
Module not found: Can't resolve '@tamagui/studio/api'
https://nextjs.org/docs/messages/module-not-found
Build failed because of webpack errors
```
I dug around and can confirm that there is no packages/studio directory, which is where I believe @tamagui/studio points, but I'm not sure what the intent is so didn't rectify.

### Expected Behavior

successful yarn site:prod build when no changes have been made to the repo.

### Tamagui Version

```markdown
git clone of current repo's master branch
```

### Reproduction

```markdown
git clone https://github.com/tamagui/tamagui.git
cd tamagui
yarn
yarn watch:build
```
open a new terminal
`yarn site` then `yarn site:extract` then `yarn site:prod`
```


### System Info

```markdown
System:
    OS: macOS 13.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 721.22 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.6
  npmPackages:
    @manypkg/cli: ^0.19.1 => 0.19.2 
    @nderscore/tamagui-typescript-plugin: ^0.3.1 => 0.3.1 
    @vercel/og: ^0.5.8 => 0.5.8 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    import-sort-style-module: ^6.0.0 => 6.0.0 
    npm-run-all: ^4.1.5 => 4.1.5 
    p-map: ^5.5.0 => 5.5.0 
    prettier: ^2.8.1 => 2.8.8 
    pretty-quick: ^3.1.2 => 3.1.3 
    prompts: 2.1.0 => 2.1.0 
    retry-cli: ^0.7.0 => 0.7.0 
    rome: ^12.1.3 => 12.1.3 
    turbo: ^1.10.13 => 1.10.13 
    typescript: ^5.2.2 => 5.2.2 
    ultra-runner: ^3.10.5 => 3.10.5
```

**Comment by alitnk** [comment]
This isn't an issue. Just that some of the files are encrypted using `git-crypt` and only accessible to maintainers. 
It shouldn't block you for development though. You can still run `yarn site` with no issues.

> I dug around and can confirm that there is no packages/studio directory, which is where I believe @tamagui/studio points, but I'm not sure what the intent is so didn't rectify.

It's pointing to `apps/studio`.

**Comment by natew** [comment]
adding a note to the docs and i'll add some logic to skip building studio unless you have a dev flag set

**Comment by johnsimeroth** [comment]
Thanks for clarifying!
