### ISSUE TITLE
Button component from tamagui ui component library onPress event does not gets call in v1.57.7 in React Native native app in iOS

### ISSUE THREAD

**Issue by vaibhav-patel-25** [tamagui/tamagui#1598]
### Current Behavior

When importing the Button component and calling it with the onPress or any of the event props and those event props does not gets called. 
In android it is working as expected but for iOS it does not. 

```typescript
import { Button, TamaguiProvider } from 'tamagui';
import React from 'react';
import appConfig from './tamagui.config';

const App: React.FC = () => {
  return (
    <TamaguiProvider config={appConfig}>
      <Button mt={50} onPress={() => console.log('called')}>
        Button
      </Button>
    </TamaguiProvider>
  );
};

export default App;
``` 

### Expected Behavior

The expected behavior should be the button event props should work as same as the native core component for iOS. And should able to handle the all of the event props.

### Tamagui Version

```markdown
from v1.57.7
```

### Reproduction

```markdown
Install and configure the tamagui version 1.57.7 or 1.57.8 in react native non expo version (native) and import the button from the tamagui in iOS. This step should reproduce the bug where button does not gets pressed or any of the button event props does not gets called.
```

**Comment by natew** [comment]
i think there was a couple bad releases due to some code we accidentally left in, this has been fixed since. we're getting maestro mobile tests into our ci pipeline this week so this wont happen again.
