### ISSUE TITLE
Bug: Static extraction produces inconsistent results on web

### ISSUE THREAD

**Issue by nderscore** [tamagui/tamagui#1599]
### Current Behavior

I'm not sure exactly when this started happening, but lately I've seen a few instances of styles being different between dev and prod builds with static extraction enabled.

The most simple example I have is this one:

```tsx
export const MyComponent = styled(YStack, {
  name: 'MyComponent',

  variants: {
    fullbleed: {
      true: {},
      false: {
        padding: '$4',
      },
    },
  } as const,

  defaultVariants: {
    fullbleed: false,
  },
});
```

In dev, with static extraction disabled, these render as expected:

```tsx
<MyComponent /> // <-- renders with padding
<MyComponent fullbleed /> // <-- renders without padding
```

With static extraction enabled, these both render with the same appearance:

```tsx
<MyComponent /> // <-- renders with padding
<MyComponent fullbleed /> // <-- also renders with padding :-/
```

Setting `disableOptimization: true` in the component also has no effect.

### Tamagui Version

```markdown
1.57.8
```

### Reproduction

```markdown
TBD
```

**Comment by natew** [comment]
lmk if not fixed

**Comment by mrevanzak** [comment]
same as me, defaultVariants seems not worked at all
