### ISSUE TITLE
Animation + pressStyle not applied if not used in a variant

### ISSUE THREAD

**Issue by foyarash** [tamagui/tamagui#162]
**Describe the bug**

The `pressStyle` styles are not applied upon a press on a View if it's not put in a variant, just like what is done for the `ThemableStack` component

**To Reproduce**

The following gist reproduces the issue https://gist.github.com/foyarash/186a299eadbb1df5335dedc22a706dce

**System Info (please complete the following information):** 

Node v16.16.0
Tamagui beta 138

**Comment by natew** [comment]
I've tested on the tamagui sandbox, if you clone the repo you can just run the development instructions and then run `yarn sandbox` and try out stuff there (minus compiler).

Do you have compilation enabled? Webpack?

**Comment by foyarash** [comment]
I actually was able to make it working but not totally

The issue seems to come from the animation prop. If i remove it, the styles are applied, but its not applying tokens coming from the theme. If i use a color token, it works fine.

**Comment by natew** [comment]
Should be fixed in latest, lmk if not
