### ISSUE TITLE
Export `resolveAssetSource` in Image component

### ISSUE THREAD

**Issue by ayushsharma82** [tamagui/tamagui#1646]
### Current Behavior

By default we can't use imported images with Image component in reference to latest updates in tamagui. Simply passing the imported image in uri parameter of `source` will throw an error.

Instead I'll suggest exporting the `resolveAssetSource` from React Native Image component in the tamagui Image component itself to make things easier and more compliant.

Working Example:
```js
import { Image } from 'react-native'
import { Image as TamaguiImage } from 'tamagui'

import logoImg from '../assets/logo.png'

<TamaguiImage source={{ uri: Image.resolveAssetSource(logoImg).uri, width: 120, height: 40 }} resizeMode='contain' />
```

### Tamagui Version

```markdown
1.64.4
```

### Reproduction

Does not work! ( Throws an error in native/iOS ):

```js
import { Image } from 'tamagui'

import logoImg from '../assets/logo.png'

<Image source={{ uri: logoImg, width: 120, height: 40 }} resizeMode='contain' />
```

**Comment by natew** [comment]
i think this is an invalid usage of uri, since import passes a number, but i have a fix in the next release

**Comment by natew** [comment]
i've made this work out of the box so no need to export
