### ISSUE TITLE
Select shows as empty on first render or value change

### ISSUE THREAD

**Issue by ayushsharma82** [tamagui/tamagui#1650]
### Current Behavior

Hi @natew ,

I'm using Select component in native and Select.Value shows as empty on first value change no matter after how much time I change the `value` parameter. I'm loading options through an API.

This is something new which happened recently with tamagui upgrade, previously it used to load fine ( around 4 months back ).

Preview:
![image](https://github.com/tamagui/tamagui/assets/26592968/df9e2a92-6f14-478c-af7a-53a713714eba)

### Expected Behavior

It should show the selected option name upon change of `value` parameter.

### Tamagui Version

```markdown
1.64.4
```

### Reproduction

```markdown
-
```

**Comment by natew** [comment]
I can't reproduce locally, it's working on first change for me. Sorry but have to ask for repro.

**Comment by Chrischuck** [comment]
Getting this as well

**Comment by Chrischuck** [comment]
@ayushsharma82 I resolved the issue of the value not being displayed on value change
<img width="465" alt="Screenshot 2023-10-24 at 3 32 45 PM" src="https://github.com/tamagui/tamagui/assets/13311268/c681d486-9e78-49b3-b6fc-0a30bc3222e4">

put the value you want in the Select.Value

The docs don't seem to reflect this behavior? If this is the intended behavior, I'd be happy to add this to the docs for you @natew

**Comment by isaachinman** [comment]
@natew Just ran into this. Is it expected that users have to manually put the value inside `<Select.Value>`?

The docs do not indicate that.

I have another select in my code base that works as per the docs. I believe perhaps this issue is related to the `value` prop being uninitialised on first render.
