### ISSUE TITLE
"ReferenceError: navigator is not defined" when testing with `@testing-library/react-native`

### ISSUE THREAD

**Issue by pierpo** [tamagui/tamagui#1651]
### Current Behavior

When testing a Tamagui app with `jest` + `@testing-library/react-native`, I get the following error.

```
FAIL  src/MyTest.test.tsx
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.

    ReferenceError: navigator is not defined

    > 1 | import { Github, Twitter } from "@tamagui/lucide-icons";
        |                                                        ^
      2 | import { Link, useRouter } from "expo-router";
      3 | import {
      4 |   Button,

      at Object.<anonymous> (node_modules/@tamagui/constants/src/index.ts:13:44)
      at Object.<anonymous> (node_modules/@tamagui/helpers/src/validStyleProps.ts:5:7)
      at Object.<anonymous> (node_modules/@tamagui/helpers/src/index.ts:4:15)
      at Object.<anonymous> (node_modules/@tamagui/web/src/Tamagui.ts:10:22)
      at Object.<anonymous> (node_modules/@tamagui/web/src/index.ts:1:15)
      at Object.<anonymous> (node_modules/@tamagui/core/src/index.ts:16:8)
      at Object.<anonymous> (node_modules/@tamagui/helpers-icon/src/themed.tsx:13:3)
      at Object.<anonymous> (node_modules/@tamagui/helpers-icon/dist/cjs/index.native.js:16:25)
      at Object.<anonymous> (node_modules/@tamagui/lucide-icons/src/icons/accessibility.tsx:24:25)
      at Object.<anonymous> (node_modules/@tamagui/lucide-icons/dist/cjs/index.native.js:1103:28)
      at Object.<anonymous> (app/index.tsx:1:56)
      at Object.<anonymous> (src/MyTest.test.tsx:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.202 s, estimated 2 s
Ran all test suites.
```

As you can see, web stuff is imported. But it really shouldn't, because I want my app to be 100% iOS+Android.
The crash comes from a variable that is not defined in `node_modules/@tamagui/constants/dist/cjs/index.js`, which is in fact a web file. It should use `node_modules/@tamagui/constants/dist/cjs/index.native.js`.

It doesn't, because `node_modules/@tamagui/constants/package.json` overrides the module resolution logic (that prioritizes `.native.js` over `.js`) because of this:

```json
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "types": "./types/index.d.ts",
      "import": "./dist/esm/index.js",
      "require": "./dist/cjs/index.js"
    }
  },
```

Removing it solves this first issue (it works on my repro example). I am not sure removing it is a viable solution that could be committed here, though.

But note that I do get more errors on my project. There are other problematic web imports (I'll probably open other issues, I guess).

### Expected Behavior

I should be able to run the tests seamlessly without configuring jest with a web environment.

### Tamagui Version

```markdown
1.61.3
```

### Reproduction

Clone this:

https://github.com/pierpo/tamagui-jest-repro

```
yarn
yarn test
```

### Workaround

Patching `@tamagui/constants` with this seems to work. Also, you might need to adjust your `jest.config.js` to have the proper `native.js` module extension prioritized.

```patch
diff --git a/package.json b/package.json
index 1ebad5b4aefb5ac315c7a95e64aaf05411cdb748..482e985772feb6f16c2151cf3012fe29acc446c0 100644
--- a/package.json
+++ b/package.json
@@ -21,14 +21,6 @@
     "@tamagui/build": "1.64.4",
     "react": "^18.2.0"
   },
-  "exports": {
-    "./package.json": "./package.json",
-    ".": {
-      "types": "./types/index.d.ts",
-      "import": "./dist/esm/index.js",
-      "require": "./dist/cjs/index.js"
-    }
-  },
   "peerDependencies": {
     "react": "*"
   },
```

**Comment by natew** [comment]
Can you try aliasing `@tamagui/core` to `@tamagui/core/native-test`

**Comment by natew** [comment]
Hm this is a bit odd, must be a behavior set up in your testing framework... looking into solutions, but that `exports` isnt technically wrong I don't think. Anything looking for RN support needs to prefer `.native.` file endings.

**Comment by natew** [comment]
You'd want to add `.native.js` to your resolve extensions setting, this is an option in Jest. Unless you know of some other way, I can't really think of anything better than this though, as package.json exports doesn't really work otherwise. We could add `"react-native"` field? But then you still need to configure that `.native.` behavior anyway so it doesn't help.

**Comment by pierpo** [comment]
Thank you for the answers! I'll try the alias on Monday :blush: 

About the extension setting, I forgot to mention: I did try to override the module resolution to prioritize `.native.js` over `.js` (and I verified that it worked in my project sources to make sure I did it properly), but it did not have any effect in the node modules. Proof of that is that if I remove the "exports" fields of the package.json, it starts working.

**Comment by EgorKrasno** [comment]
I am getting the same issue with Jest and RNTL. ` ReferenceError: navigator is not defined` pops up when testing any component.

**Comment by pierpo** [comment]
I tried the alias by adding this in my jest config

```tsx
// ...
  moduleNameMapper: {
    "@tamagui/core": "@tamagui/core/native-test"
  },
// ...
```

It does not work: the problematic import is not in `@tamagui/core` (if you have a look at the stack trace, `@tamagui/core` does not appear).

**Comment by pierpo** [comment]
About the other problems I have, it was a mistake on my end. Still, web code is imported even though I don't want it to be used. No impact for now but I'm starting fresh, so I don't know yet if it will be an issue.

I'm editing the original post with my workaround patch.

**Comment by msidqi** [comment]
I have the same issue on 1.68.5

**Comment by TheEhsanSarshar** [comment]
set this to false in your metro config. see if this helps
`unstable_enablePackageExports: false`

**Comment by jpmmatias** [comment]
I had the same issue when I was using version 1.6.8. Now, I've downgraded to version 1.57.3, and it's working

**Comment by natew** [comment]
Can you try aliasing:

- `@tamagui/core` => `@tamagui/core/native-test`
- `@tamagui/web` => `@tamagui/core/native-test`

**Comment by tobyclemson** [comment]
I'm having the same problem and adding the two suggested aliases does not resolve the issue.

Could you give an example of how to set the extension priority in jest? I'm using the `jest-expo` preset if that helps.

**Comment by tobyclemson** [comment]
I updated to v1.74.17 and this issue has disappeared.

**Comment by TimPetricola** [comment]
Same here, I confirm it's fixed in latest versions

**Comment by KrastanD** [comment]
If anyone else comes across this, I was able to fix it by adding the following to jest.config.js:
```  
testEnvironmentOptions: {
    customExportConditions: ['react-native'],
},
```
