### ISSUE TITLE
Select component's dropdown makes page scrollbar disappear

### ISSUE THREAD

**Issue by hackily** [tamagui/tamagui#1653]
### Current Behavior

When you click on the select component, the page scrollbar disappears

https://github.com/tamagui/tamagui/assets/8202335/4cdef135-b195-4794-875f-14d135aa3f9e

### Expected Behavior

Scrollbar doesn't disappear

### Tamagui Version

```markdown
Latest
```

### Reproduction

```markdown
Reproducible here: https://tamagui.dev/docs/components/select/1.40.0
```

### System Info

```
  System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 71.23 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.4.0 - ~/.nvm/versions/node/v20.4.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.7.2 - ~/.nvm/versions/node/v20.4.0/bin/npm
    Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.4
```

**Comment by natew** [comment]
This is intended as we'd have to implement a lot of logic to handle scrolling while open, and it seems like a decent trade off.

Added a new option in 6110d4bcb8753005ab85091998d6f61cddfefe9c that lets you disable this. In the future we can handle it more automatically.
