### ISSUE TITLE
Dialog default animation.

### ISSUE THREAD

**Issue by roiiiu** [tamagui/tamagui#1656]
### Current Behavior

I found that if the exit animation style is not set for the dialog, but only the animation properties are specified, there seems to be a delay when the dialog exits. Is there any way to only have an enter animation for the dialog? Also, this default setting is very misleading. I once thought it was a performance issue caused by the code.
<img width="476" alt="image" src="https://github.com/tamagui/tamagui/assets/11494827/5f9c1a5f-fbd2-40e8-8fb9-9aef56ab2e4f">

https://github.com/tamagui/tamagui/assets/11494827/a787c584-464e-4c49-aa88-d1984c12bc4b

### Tamagui Version

```markdown
1.66.0
```

### Platform (Web, iOS, Android)

```markdown
ios
```

### Reproduction

```markdown
Set animation properties for dialog, omit enterStyle and exitStyle.
```

**Comment by ethras** [comment]
Facing the same issue.

I use 
```ts
if (!isOpen) {
    return null;
  }
return <Dialog...>
```
as workaround for now

**Comment by natew** [comment]
I can't repro this anymore, tested a few different variants. Can you verify on latest and re-open if still an issue?

**Comment by kota113** [comment]
@roiiiu  @natew Hi, I'm experiencing the same issue and I'd like to provide details. 
Is the code below of my component enough for repro? I hope this helps to address the issue.  
The dialog closes with the animation, but the dialog itself stays for a while even after the animation ends.

Thank you for maintaining this library!

https://github.com/user-attachments/assets/5a488f9f-13b9-4bff-9649-a8ce5b26af94


```
function PrefDialog({open, setOpen, pref, setPref}: { open: boolean, setOpen: (open: boolean) => void, pref: BicycleCardPref, setPref: (pref: BicycleCardPref) => void }) {
  function switchPref(key: PrefKey) {
    setPref({...pref, [key]: !pref[key]});
  }
  return (
    <Dialog open={open}>
      <Dialog.Portal>
        <Dialog.Overlay
          key="overlay"
          animation="quicker"
          opacity={0.4}
          enterStyle={{opacity: 0}}
          exitStyle={{opacity: 0}}
        />
        <Dialog.Content width={"65%"}>
          <Dialog.Title fontSize={18}>
            設定
          </Dialog.Title>
          <XStack alignItems="center" justifyContent={"space-between"}>
            <Text>some content</Text>
          </XStack>
          <Unspaced>
            <Dialog.Close asChild>
              <Button
                position="absolute"
                top="$3"
                right="$3"
                size="$3"
                circular
                icon={X}
                onPress={() => setOpen(false)}
              />
            </Dialog.Close>
          </Unspaced>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog>
  )
}
```

**Comment by sumitsk1** [comment]
> [@roiiiu](https://github.com/roiiiu) [@natew](https://github.com/natew) Hi, I'm experiencing the same issue and I'd like to provide details. Is the code below of my component enough for repro? I hope this helps to address the issue. The dialog closes with the animation, but the dialog itself stays for a while even after the animation ends.
> 
> Thank you for maintaining this library!
> 
>  2024-11-10.123530.mp4 
> ```
> function PrefDialog({open, setOpen, pref, setPref}: { open: boolean, setOpen: (open: boolean) => void, pref: BicycleCardPref, setPref: (pref: BicycleCardPref) => void }) {
>   function switchPref(key: PrefKey) {
>     setPref({...pref, [key]: !pref[key]});
>   }
>   return (
>     <Dialog open={open}>
>       <Dialog.Portal>
>         <Dialog.Overlay
>           key="overlay"
>           animation="quicker"
>           opacity={0.4}
>           enterStyle={{opacity: 0}}
>           exitStyle={{opacity: 0}}
>         />
>         <Dialog.Content width={"65%"}>
>           <Dialog.Title fontSize={18}>
>             設定
>           </Dialog.Title>
>           <XStack alignItems="center" justifyContent={"space-between"}>
>             <Text>some content</Text>
>           </XStack>
>           <Unspaced>
>             <Dialog.Close asChild>
>               <Button
>                 position="absolute"
>                 top="$3"
>                 right="$3"
>                 size="$3"
>                 circular
>                 icon={X}
>                 onPress={() => setOpen(false)}
>               />
>             </Dialog.Close>
>           </Unspaced>
>         </Dialog.Content>
>       </Dialog.Portal>
>     </Dialog>
>   )
> }
> ```

Same issue
