### ISSUE TITLE
Upgrade to solito v4 for starter

### ISSUE THREAD

**Issue by Sir-hennihau** [tamagui/tamagui#1661]
### Current Behavior

Current starter still installs solito v3

### Expected Behavior

Tamagui starter should come with latest solito version

It supports the new app router for next

Will running the upgrade command then also support automatically install the latest solito and support for it for the starter for existing repos?

### Tamagui Version

```markdown
latest
```

### Platform (Web, iOS, Android)

```markdown
both
```

### Reproduction

```markdown
Create starter with solito
```

**Comment by gorbypark** [comment]
For what it is worth, it's very easy to upgrade yourself.  Just make the upgrade in `packages/apps/package.json` like you would any other package and then go back to the root of the project and run `yarn`.  After that, just change all imports to be from `solito/navigation`.  For example, there's two pages in the starter.  In `packages/app/features/home/screen.tsx` change the useLink import to `import { useLink } from 'solito/navigation'` and in `packages/app/features/user/details-screen.tsx` change to `import { useLink, useParams } from 'solito/navigation'` and slightly change the param line to something like 
```ts
  const { id } = useParams()
```
That should be it.
