### ISSUE TITLE
npm create tamagui@latest not working

### ISSUE THREAD

**Issue by abhishekpal-nexg** [tamagui/tamagui#1670]
### Current Behavior

Hi,

I was thinking to try out the project. 

However, whenever I am accessing it, throws below error, tried on different systems, still the same. 
macOS, windows, linux

![image](https://github.com/tamagui/tamagui/assets/105267735/e209dfea-984d-4026-887b-f3089e6dae13)

### Expected Behavior

Should download and be able to run the project. 

### Tamagui Version

```markdown
@latest
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
Step 1. npm create tamagui 
Step 2. not working
```

### System Info

```markdown
❯ npx envinfo --system --npmPackages --binaries --browsers
npx: installed 1 in 2.497s

  System:
    OS: macOS 14.0
    CPU: (12) x64 Apple M2 Pro
    Memory: 284.74 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
  Browsers:
    Brave Browser: 115.1.56.14
    Chrome: 115.0.5790.114
    Safari: 17.0
```

**Comment by alitnk** [comment]
Strange error. Can't reproduce unfortunately...
Have you tried it using Node 18?

**Comment by natew** [comment]
Node 14 not supported!
