### ISSUE TITLE
Popover behavior on web is broken in certain scenarios

### ISSUE THREAD

**Issue by matthewhausman** [tamagui/tamagui#1674]
### Current Behavior

Popover content is always placed in the top left of window regardless of where the trigger is when using "isChild" on the trigger.

When isChild is false, the popover appears in the top right of the window.

Then I put placement="left" on the Popover and it becomes vertically placed in the correct spot, but to the rightmost side of the window.

finally, I put offset of 0 to get the thing to work for now at least

### Expected Behavior

Popover shouldn't behave differently in different places....

I'm not able to reproduce my own situation. However if you pull the reprod and click the popover trigger you will see there is something not right in the reprod as well. I hope fixing this will help in my own situation as described above

### Tamagui Version

```markdown
latest
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://github.com/matthewhausman/reprod-popover-behavior
```

### System Info

```markdown
System:
    OS: macOS 13.0
    CPU: (12) arm64 Apple M2 Pro
    Memory: 214.31 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 3.3.1 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 117.0.5938.88
    Firefox: 112.0.1
    Safari: 16.1
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.20.13 
    @hookform/resolvers: 2.9.11 => 2.9.11 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    @typescript-eslint/eslint-plugin: latest => 5.53.0 
    @typescript-eslint/parser: latest => 5.53.0 
    eslint: ^8.21.0 => 8.33.0 
    eslint-plugin-react: ^7.32.2 => 7.32.2 
    eslint-plugin-react-hooks: ^4.6.0 => 4.6.0 
    eslint-plugin-react-native: ^4.0.0 => 4.0.0 
    prettier: ^2.7.1 => 2.8.3 
    turbo: ^1.4.2 => 1.7.2 
    typescript: ^5.1.3 => 5.1.6
```

**Comment by natew** [comment]
Hm I copied your example in the kitchen sink and tried a few things and can't replicate, it shows on each side for me in the sandbox. Will have to check your repo later but odd since its the same code.

**Comment by matthewhausman** [comment]
@natew get a chance to check?

**Comment by matthewhausman** [comment]
although the placement is fixed with setting a specific offset value in each axis, I am unable to take advantage of the stayInFrame and allowFlip props with the same effectiveness as usual in my application...

**Comment by MichaelKim39** [comment]
Had a similar issue on my app and was able to fix by removing `asChild` prop as described

**Comment by TheEhsanSarshar** [comment]
also copy-pasted the code in the repo and wasn't able to reproduce the issue. everything works fine with or without asChild.
try to upgrade your Tamagui version, that might help!
I'll try to clone your repo and check there

**Comment by TheEhsanSarshar** [comment]
`yarn tamagui:upgrade` fixed the issue!
