### ISSUE TITLE
asChild usage with non-Tamagui component

### ISSUE THREAD

**Issue by TimPetricola** [tamagui/tamagui#1680]
### Current Behavior

I have a usecase where I need to pass arbitrary components (i.e. non-Tamagui ones) as children and rely on `asChild`. Most of the time, it's about passin a `Link` (a `react-router-dom` one in my case, but the same think happens with `next/link`).

It works fine but logs many errors about unsupports props in the console:

```
Warning: Unknown event handler property `onPress`. It will be ignored.
a
LinkComponent@webpack-internal:///../../node_modules/next/dist/client/link.js:105:254
Slot<@webpack-internal:///../../node_modules/@tamagui/web/dist/esm/views/Slot.js:19:38
```

(same errors for `onLongPress`, and `onPressIn`)

### Expected Behavior

I'm looking for a way to make it work without the noise

### Tamagui Version

```markdown
1.68.6
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```tsx
import Link from 'next/link'
import { Stack } from 'tamagui'

export default function Page() {
  return (
    <>
      <Stack backgroundColor="red" asChild>
        <Link href="/">Next Link</Link>
      </Stack>
    </>
  )
}
```

[Codesandbox for reproduction](https://codesandbox.io/p/sandbox/heuristic-julien-pdp3xd?file=/apps/next/pages/index.tsx:1,1-13,1)

**Comment by natew** [comment]
Hm this is a decent point, it assumes a "react native" like environment, so for example if you did `asChild` with any react native type view it works, but for web it doesn't.

How about a new option `asChild="web"` where it basically assumes a web-like view (on web only) and changes onPress => onClick?

**Comment by natew** [comment]
added `asChild="web"` going out in the next release.

**Comment by TimPetricola** [comment]
That works perfectly! Many thanks for the reactivity @natew 🙇
