### ISSUE TITLE
Contexts are not working inside Portals.

### ISSUE THREAD

**Issue by Chasty** [tamagui/tamagui#1685]
### Current Behavior

I have a context like this.

```js
type CustomToastContext = {
  showToast: ({ title, message }: { title: string; message: string }) => void;
  hideToast: () => void;
};

const CustomToastContext = createContext<CustomToastContext>(
  {} as CustomToastContext
);
```
with a provider.

```js
const CustomToastProvider = (children) => {

 const showToast = ({title, message,}: {title: string;message: string;}) => {
    alert("Show Toast Alert!!");
  };

  const hideToast = () => {
    alert("Hide Toast Alert!!");
  };
  
  
return (
    <CustomToastContext.Provider
      value={{
        showToast,
        hideToast,
      }}
    >
      {children}
    </CustomToastContext.Provider>
  );
}
```

You can see `showToast` and `hideToast` only alerts for testing.

so outside the Dialog.Portal works perfectly, it show the native window alert, but inside a Dialog.Portal, it seems like the contexts are removed, and the value in the context is undefined.

### Expected Behavior

1. Tapping on Show, should alert `Show Toast Alert!!`
2. Tapping on Hide, should alert "Hide Toast Alert!!"

This is indeed related to this issue as well https://github.com/tamagui/tamagui/issues/1675

### Tamagui Version

```markdown
latest
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
https://github.com/Chasty/toastInsideDialogIssue
```

**Comment by moesalih** [comment]
hi @Chasty. did you find a solution for this? i'm seeing a similar issue where contexts are not available in dialogs. just wondering i'm doing something wrong or something is misconfigured.
