### ISSUE TITLE
`props.color` never passed into Component in helpers icon themed

### ISSUE THREAD

**Issue by chef-jojo** [tamagui/tamagui#1689]
I am using `themed` from helpers-icon to wrap our own icon components, I found that the color never passed into the icon
The defaultColor should take `propsIn.color` instead?

https://github.com/tamagui/tamagui/blob/02e769219b35e75b3b44955e956dcff82f77c616/packages/helpers-icon/src/themed.tsx#L21-L24

**Comment by natew** [comment]
fix going out in 1.69.1
