### ISSUE TITLE
Bug: static extraction drops responsive flex direction on styled Stack

### ISSUE THREAD

**Issue by nderscore** [tamagui/tamagui#1694]
### Current Behavior

Given this styled component, extending `XStack`:

```tsx
const MyComponentContainer = styled(XStack, {
  name: 'MyComponent',

  gap: '$4',
  alignItems: 'stretch',
  justifyContent: 'flex-start',

  $sm: {
    flexDirection: 'column',
  },
});

export const MyComponent = withStaticProperties(MyComponentContainer, { /* ... */ });
```

This works fine in the dev server.

But in a production build where static optimizations are enabled, the resulting classnames/styles do not include the responsive flex direction:

```html
<div class="  is_MyComponent _ai-stretch _dsp-flex _fd-row _fb-auto _bxs-border-box _pos-relative _mih-0px _miw-0px _fs-0 _gap-1481558276 _jc-flex-start ">
```

Adding `disableOptimization: true` to the styled() props doesn't change the resulting output. 

Neither does adding `// tamagui-ignore` to the file.

Only `disableExtraction: true` in the next plugin resolves it.

Curiously, using a media query _JSX prop_ on the component works just fine with static extraction enabled:

```tsx
<MyComponent $sm={{ flexDirection: 'column' }}>
```

So the issue is something to do with optimization of `styled()` calls specifically. 🤔 

Also, the same issue happens with trying to set a responsive flex direction on a `YStack` or `SizeableStack`.

### Expected Behavior

Responsive styles are applied to the component when optimizations are enabled.

### Tamagui Version

```markdown
1.69.1
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
TBD
```

**Comment by natew** [comment]
i think fixed right?

**Comment by natew** [comment]
Er, maybe not actually?
