### ISSUE TITLE
TS error on variant of a styled(Button)

### ISSUE THREAD

**Issue by la55u** [tamagui/tamagui#1700]
### Current Behavior

If you create a `styled(Button)`, add a variant to it named `variant` and try to use that component in another component TS will show an error: `Type 'string' is not assignable to type 'undefined'.ts(2322)` and the project cannot be built. Interestingly, if I rename `variant` to let's say `mode` it works as expected.

### Expected Behavior

It should work with `variant` too, or if it's not supported it should be mentioned in the docs.

### Tamagui Version

```markdown
latest (1.70.0)
```

### Platform (Web, iOS, Android)

```markdown
all? (it happens in the UI package)
```

### Reproduction

Repo: https://github.com/la55u/tama-variant-ts-bug (This is the latest default solito starter with the only exception that a new MyButton and MyComponent files were added.)

1. clone the repo & run `yarn`
2. run `yarn build`
3. you should see the error in your terminal

### System Info

```markdown
System:
    OS: Linux 6.4 Fedora Linux 38 (Workstation Edition)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 24.61 GB / 31.04 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 117.0.5938.92
    Firefox: 118.0b9
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.39.0 
    node-gyp: ^9.3.1 => 9.3.1 
    prettier: ^2.7.1 => 2.8.8 
    turbo: ^1.10.3 => 1.10.3 
    typescript: ^5.1.3 => 5.1.3
```

**Comment by natew** [comment]
fix coming in next release

**Comment by natew** [comment]
fixed https://github.com/tamagui/tamagui/releases/tag/v1.74.20

**Comment by theyanniss23002** [comment]
version tamagui ^1.76.0
![Uploading Снимок экрана 2023-11-03 в 10.44.06.png…]()
