### ISSUE TITLE
Error While Building Lucide Icons

### ISSUE THREAD

**Issue by neeraj15022001** [tamagui/tamagui#1703]
### Current Behavior

**Use Case** : Use Case here is that i want to extend Lucide icons and include icons of my own in this library

**Current Issue** : Facing type errors while building using tamagui build
<img width="906" alt="Screenshot 2023-09-25 at 1 05 49 PM" src="https://github.com/tamagui/tamagui/assets/55191873/c6037f1d-59f4-43ed-96b8-5caf508d07c1">

### Expected Behavior

Build Lucide Icons without any errors

### Tamagui Version

```markdown
1.71.0
```

### Platform (Web, iOS, Android)

```markdown
All
```

### Reproduction

```markdown
- Clone Tamagui Repository
- Copy lucide icons from packages folder inside tamagui
- delete biome.json
- Copy following config into tsconfig.json

{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "@my-package/custom-icons",
  "_version": "0.0.1",
  "compilerOptions": {
    "target": "es5",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "jsx": "preserve",
    "module": "esnext",
    "declaration": true,
    "declarationDir": "types",
    "sourceMap": true,
    "outDir": "dist",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "emitDeclarationOnly": true,
    "incremental": true,
    "baseUrl": ".",
    "composite": true
  },
  "include": [
    "src/**/*.tsx",
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}

- Run yarn install
- Build using yarn build
```

**Comment by neeraj15022001** [comment]
tsconfig.tsbuildinfo - [new.txt](https://github.com/tamagui/tamagui/files/12712412/new.txt)

**Comment by natew** [comment]
this is out of scope for us to fix
