### ISSUE TITLE
Tamagui's Image ignoring dimensions

### ISSUE THREAD

**Issue by TimPetricola** [tamagui/tamagui#1704]
### Current Behavior

Using `Image` from `tamagui` results in:
- the element not being displayed on web
- showing the image in its original dimensions on mobile

This happens even when dimensions are passed

### Expected Behavior

I'm expecting the image to render at the proper size, on both web and mobile

### Tamagui Version

Latest (`1.71.0`)

### Platform (Web, iOS, Android)

At least web and iOS

### Reproduction

```tsx
import { Image } from "@tamagui/image
<Image
  source={{ uri: 'https://tamagui.dev/social.png ' }}
  height={200}
  width={200}
  />
```

This renders but dimensions are completely ignored. [Codesandbox to reproduce](https://codesandbox.io/p/sandbox/tamagui-image-bug-repro-ppfkdh?file=%2Fapps%2Fnext%2Fpages%2Findex.tsx%3A10%2C20)

**Comment by natew** [comment]
Can you add width/height to the `source={{ uri: '', width: 200, height: 200 }}`

The outer width/height applies only to style, whereas the source one applies to the image.

**Comment by TimPetricola** [comment]
@natew 

> The outer width/height applies only to style, 

Actually, the issue is that it currently does not apply at all, not even to style. I believe this is the regression

> Can you add width/height to the source={{ uri: '', width: 200, height: 200 }}

This is a good workaround for web in the meantime. But it won't work on mobile where the `source` can be a `number` handled by Metro. 

---

### Workaround

As a workaround, I'm back to using `react-native`'s `Image`:

```tsx
import { useStyle } from "@tamagui/core"; 
const style = useStyle(propsIn, { resolveValues: "auto" })
<Image style={style} source={source} />;
```

**Comment by natew** [comment]
fix in next release

**Comment by natew** [comment]
lmk if that works

**Comment by TimPetricola** [comment]
Works perfectly! Thanks for the import normalization as well, I had something custom that's not necessary anymore 🙂
