### ISSUE TITLE
TooltipTrigger can't be rendered as inline anymore

### ISSUE THREAD

**Issue by TimPetricola** [tamagui/tamagui#1706]
### Current Behavior

Setting `<TooltipTrigger display="inline" />` does not work anymore and instead renders as `flex`

### Expected Behavior

I expect it to use `display: inline;` on web.

### Tamagui Version

latest (`1.71.0`)

### Platform (Web, iOS, Android)

web

### Reproduction

[Codesandbox to reproduce](https://codesandbox.io/p/sandbox/tamagui-tooltip-inline-debug-rr75x5?file=%2Fapps%2Fnext%2Fpages%2Findex.tsx%3A14%2C19)

```tsx
<Text color="blue">
  This is an
  <Tooltip>
    <Tooltip.Trigger display="inline">
      <Text>inline tooltip</Text>
    </Tooltip.Trigger>
    <Tooltip.Content>
      <Tooltip.Arrow />
      <Text>Label</Text>
    </Tooltip.Content>
  </Tooltip>
</Text>;

```

**Comment by natew** [comment]
Can you re-open if still an issue?

**Comment by TimPetricola** [comment]
@natew I don't seem to have the permission to re-open, but I confirm this is still an issue preventing upgrading. It was also noticed by someone else las week in https://github.com/tamagui/tamagui/issues/3634
