### ISSUE TITLE
[web] Themes are not propagating properly when providers are in separate files

### ISSUE THREAD

**Issue by hdwatts** [tamagui/tamagui#1718]
### Current Behavior

`NextThemeProvider` and `TamaguiProvider` must be in the same component. If they are abstracted away from each other then they no longer work (even though structurally the output should be the same).

In the reproduction repo:

1. Access `http://localhost:3000/` and toggle the themes, the top switch will not respond to theme changes.
2. Access `http://localhost:3000/pages-test` and toggle the themes, both switches will not change colors.
3. In `tamagui-playground/src/app/_providers/index.tsx` comment out the `Providers` default export and uncomment the `BothCombinedProvider` default export
4. Restart nextjs and retry steps 1 and 2. The switches now color as expected

### Expected Behavior

It should not matter if the providers are in different files.

### Tamagui Version

```markdown
1.72.3
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://github.com/hdwatts/tamagui-playground
```

### System Info

```markdown
System:
    OS: macOS 13.6
    CPU: (8) arm64 Apple M1
    Memory: 602.61 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.6
  npmPackages:
    @tamagui/animations-css: ^1.72.3 => 1.72.3
    @tamagui/font-inter: ^1.72.3 => 1.72.3
    @tamagui/lucide-icons: ^1.72.3 => 1.72.3
    @tamagui/next-plugin: ^1.72.3 => 1.72.3
    @tamagui/next-theme: ^1.72.3 => 1.72.3
    @tamagui/themes: ^1.72.3 => 1.72.3
    @types/node: latest => 20.7.0
    @types/react: latest => 18.2.23
    @types/react-dom: latest => 18.2.7
    eslint: latest => 8.50.0
    eslint-config-next: latest => 13.5.3
    next: latest => 13.5.3
    react: latest => 18.2.0
    react-dom: latest => 18.2.0
    tamagui: ^1.72.3 => 1.72.3
    typescript: latest => 5.2.2
```

**Comment by natew** [comment]
Are you using onChangeTheme from next provider to ensure it also changes in TamaguiProvider?

![CleanShot 2023-10-22 at 20 04 20@2x](https://github.com/tamagui/tamagui/assets/12100/4b7799c0-0c16-44f8-bd68-2566bcdbe2f7)

**Comment by hdwatts** [comment]
@natew Yes I am

NextThemeProvider set here, which calls `setTheme`
https://github.com/hdwatts/tamagui-playground/blob/main/src/app/_providers/tamagui-theme-provider.tsx

TamaguiProvider set here
https://github.com/hdwatts/tamagui-playground/blob/main/src/app/_providers/tamagui-provider.tsx

I see we have different props for TamaguiProvider, namely `themeClassNameOnRoot`, could that be the culprit?
