### ISSUE TITLE
Could not overwrite component color while using theme

### ISSUE THREAD

**Issue by longnguyen2508** [tamagui/tamagui#1728]
### Current Behavior

When attempting to assign color tokens such as `$blue10` to the `color` or `backgroundColor` properties of certain components like `H1` or `Stack`, I encountered an issue. This problem occurred specifically when using themes like `light_green` or `dark_green`. Interestingly, the tokens worked correctly for the components when I reverted to the default themes (`light` or `dark`).

#### Setting theme is `light` or `dark`

<img width="466" alt="Screenshot 2023-09-29 at 20 35 37" src="https://github.com/zcmgyu/tamagui-demo/assets/13638569/f8d7c4a6-1689-4ca4-8343-64d97250b499">

All color tokens passed to Component has displayed as expected

#### After switch theme to `light_green` or `green_dark`, everything’s gone

<img width="466" alt="Screenshot 2023-09-29 at 20 35 13" src="https://github.com/zcmgyu/tamagui-demo/assets/13638569/4bd75529-cf06-4e4c-ba31-87c96c697164">

### Expected Behavior

Expected to accept color tokens like `$blue10`, `$green9` while using theme like `light_green`

### Tamagui Version

```markdown
1.73.0
```

### Platform (Web, iOS, Android)

```markdown
iOS
```

### Reproduction

I was unable to reproduce the issue in the apps/kitchen-sink application due to the problem described in [this ticket](https://github.com/tamagui/tamagui/issues/517). Instead, I created a new one using the command npm create tamagui@latest and replicated the issue in this pull request:

https://github.com/zcmgyu/tamagui-demo/pull/1

### System Info

```markdown
System:
    OS: macOS 13.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 584.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    Watchman: 2023.08.14.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.6
  npmPackages:
    @babel/core: ^7.20.0 => 7.22.10
    @babel/preset-env: ^7.20.0 => 7.22.10
    @babel/runtime: ^7.20.0 => 7.22.10
    @commitlint/cli: ^17.7.1 => 17.7.1
    @commitlint/config-conventional: ^17.7.0 => 17.7.0
    @notifee/react-native: ^7.8.0 => 7.8.0
    @react-native-async-storage/async-storage: ^1.19.3 => 1.19.3
    @react-native-firebase/app: ^18.3.2 => 18.3.2
    @react-native-firebase/auth: ^18.3.2 => 18.3.2
    @react-native-firebase/firestore: ^18.3.2 => 18.3.2
    @react-native-google-signin/google-signin: ^10.0.1 => 10.0.1
    @react-native-picker/picker: ^2.5.0 => 2.5.0
    @react-native/eslint-config: ^0.72.2 => 0.72.2
    @react-native/metro-config: ^0.72.11 => 0.72.11
    @react-navigation/bottom-tabs: ^6.5.8 => 6.5.8
    @react-navigation/native: ^6.1.7 => 6.1.7
    @react-navigation/native-stack: ^6.9.13 => 6.9.13
    @tamagui/animations-react-native: ^1.73.0 => 1.73.0
    @tamagui/babel-plugin: ^1.73.0 => 1.73.0
    @tamagui/config: ^1.73.0 => 1.73.0
    @tamagui/font-inter: ^1.73.0 => 1.73.0
    @tamagui/lucide-icons: ^1.73.0 => 1.73.0
    @tamagui/shorthands: ^1.73.0 => 1.73.0
    @tamagui/themes: ^1.73.0 => 1.73.0
    @tsconfig/react-native: ^3.0.0 => 3.0.2
    @types/react: ^18.0.24 => 18.2.20
    @types/react-test-renderer: ^18.0.0 => 18.0.0
    babel-jest: ^29.2.1 => 29.6.3
    eslint: ^8.50.0 => 8.50.0
    eslint-plugin
```

**Comment by longnguyen2508** [comment]
Any help :(

**Comment by natew** [comment]
You are making the root theme light_green, but only `light` has `$blue9` set on it, that's just how we set up our themes. You can fix this by having TamaguiProvider defaultTheme="light" and then *below* that just use a separate <Theme name="green">

**Comment by longnguyen2508** [comment]
@natew Thank you for your advice

Using the theme worked as I expected.

```
    <TamaguiProvider
      config={tamaguiConfig}
      defaultTheme={colorSchema === 'dark' ? 'dark' : 'light'}>
      <Theme
        name={
          colorSchema === 'dark' ? 'dark_green' : 'light_green'
        }>
        <SafeAreaProvider initialMetrics={initialWindowMetrics}>
          {children}
        </SafeAreaProvider>
      </Theme>
    </TamaguiProvider>
```
