### ISSUE TITLE
Support for Expo v49

### ISSUE THREAD

**Issue by mirkokiefer** [tamagui/tamagui#1743]
https://github.com/tamagui/tamagui/blob/af0aac139ae5586992e0b58753fb462a0452f4de/starters/next-expo-solito/apps/expo/package.json#L20C6-L20C6

Just gave tamagui a try with the expo starter template and a bit disappointed to find that its still running on Expo v48.
I found some [other templates running v49](https://github.com/ivopr/tamagui-expo/blob/main/package.json#L19) but would be great to have official support.

What's the version tamagui takeout supports?

Found this related issue:
- https://github.com/tamagui/tamagui/issues/1457

**Comment by vonovak** [comment]
you can buy takeout https://tamagui.dev/takeout

it comes with expo 49 and a bunch of other goodies too

**Comment by natew** [comment]
It works with 49 just needs an upgrade. It’s not hard we can make that happen. Would be a great contribution.

**Comment by mirkokiefer** [comment]
I'd buy takeout if there was some way to trial it and dependencies are kept up to date. I tested it using the free version but then the lack of updated dependencies in the official repo makes me hesitate.

**Comment by natew** [comment]
No way to trial it but we can maybe make visibility into some of the updates and general structure better.

The free starter and takeout are different projects, the free starter is OSS and we maintain it in our free time. There's two PRs updating it to 49 now in review.

Takeout is on 49 and is generally miles ahead in terms of setup. It's very much a high investment project for us.

**Comment by natew** [comment]
49 is in the starter
