### ISSUE TITLE
Popover crashes on Android

### ISSUE THREAD

**Issue by elbiedeswardt-troy** [tamagui/tamagui#1748]
After our recent upgrade to Tamagui  v1.74.0 the PopOver crashes on Android when `open` is set to true. This behaviour replicates itself setting the open to true manually or simply triggering it by pressing the trigger button. This however does not persist on iOS devices.

Please see the crashing error message below.
![Screenshot_1696414580](https://github.com/tamagui/tamagui/assets/139891205/53642f30-c5cf-4497-ba11-7ea6e0a72096)

**Comment by contactsimonwilson** [comment]
This issue is also impacting me and I can confirm it is still an issue on 1.74.15. Right now if using popovers on native, it seems like the highest usable version is somewhere around 1.64.1

**Comment by jmurphy4** [comment]
Still seeing this on 1.76.0

**Comment by edwinvrgs** [comment]
Same issue for me, happening on version `1.76.0`. Any updates?

**Comment by costaDZ** [comment]
Facing the same issue on version `1.79.1`
