### ISSUE TITLE
Elevation no longer respects numbers, have to use token.

### ISSUE THREAD

**Issue by hackily** [tamagui/tamagui#1749]
### Current Behavior

Elevation used to respect numbers but now we have to use tokens.

### Expected Behavior

Numbers should work for elevation, or at least a change in behavior should be called out as a breaking change in the release notes.

### Tamagui Version

```markdown
I was previously on 1.61.3 and it worked on that version.
It is broken on 1.74.8
```

### Platform (Web, iOS, Android)

```markdown
Web
Didn't test ios/android
```

### Reproduction

```markdown
https://codesandbox.io/p/sandbox/great-vaughan-ls7pjr?file=%2Fpackages%2Fapp%2Ffeatures%2Fhome%2Fscreen.tsx%3A28%2C81
```

**Comment by natew** [comment]
This is working both type and at runtime for me:

![CleanShot 2023-10-04 at 07 47 39@2x](https://github.com/tamagui/tamagui/assets/12100/d8734f41-cdb8-4807-914c-3489baa33f95)

**Comment by natew** [comment]
there is an elevation on your example, its just subtle, but that logic didn't change.
