### ISSUE TITLE
Tamagui ^1.74.9 Button does not accept any props declared in textProps

### ISSUE THREAD

**Issue by alien9996** [tamagui/tamagui#1758]
### Current Behavior

When I updated tamagui from version 1.72.3 to ^1.74.9. All props used in textProps: {} do not work.

### Tamagui Version

```markdown
^1.74.9
```

### Platform (Web, iOS, Android)

```markdown
Android and iOS
```

### Reproduction

```markdown
import {Button} from "tamagui";

<Button
     ref={ref as any}
     pressStyle={pressStyle}
     disabled={disabled}
     ai="center"
     jc="center"
     textProps={{ // ===> not working
       textTransform: "uppercase",
       textDecorationLine: "underline"
        }},
        >
{"Text"}
</Button>
```

**Comment by tomhicks** [comment]
I'm seeing the same. I'm unable to set `fontWeight` using any of:
- default props `fontWeight`
- prop `fontWeight`
- `textProps.fontWeight`

**Comment by alien9996** [comment]
Maybe we need to wait for tamagui to update the new version for this. I had to use version 1.72.3 to fix it.

**Comment by natew** [comment]
oh interesting, sorry about that we have very few usages of textProps and no tests yet. i'll get a patch release out somewhat soon.

**Comment by natew** [comment]
Fixed in latest version
