### ISSUE TITLE
@tamagui/next-plugin still requires experimental appDir setting for NextJs app dir support.

### ISSUE THREAD

**Issue by bpmckee** [tamagui/tamagui#1762]
### Current Behavior

NextJS 13's app router is now stable.  However, @tamagui/next-plugin requires you to set `appDir: true` in your `next.config.js`'s experimental settings.  When doing that Next gives this warning.
```
 ⚠ Invalid next.config.js options detected: 
 ⚠     The value at .experimental has an unexpected property, appDir, which is not in the list of allowed properties
```

However, without this appDir setting I've seen many very confusing issues with Tamagui.  For example
- Prod CSS styles aren't getting injected.
- Some components like `Stack` are throwing errors if imported from the Tamagui lib directly.  An example of this error is below.

```
Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'parentNode')

Call Stack
options.insert
../../packages/ui/components/src/navigation/node_modules/tamagui-loader/dist/cjs/packages/ui/components/src/navigation/BottomTabs.tsx
```

### Expected Behavior

You can use Tamagui without having to set `experimental.appDir` in your `next.config.js` file.

### Tamagui Version

```markdown
1.74.10
```

### Platform (Web, iOS, Android)

```markdown
Web - Next JS w/ app router specifically.
```

### Reproduction

```markdown
This line of code shows it's still reliant on experimental.appDir - https://github.com/tamagui/tamagui/blob/bc1ce099c85828b21719263fe179fdf66cb945dc/packages/next-plugin/src/withTamagui.ts#L28
```

**Comment by natew** [comment]
New setting on the latest version.
