### ISSUE TITLE
Outlined variant not applying to Button

### ISSUE THREAD

**Issue by ArekBartnik** [tamagui/tamagui#1775]
### Current Behavior

Variant `outlined` isn't applying to Button like we can see in docs.
<img width="718" alt="CleanShot 2023-10-12 at 21 34 21@2x" src="https://github.com/tamagui/tamagui/assets/1569446/9391ac1c-0407-46f1-bb45-b35e716d4910">

### Tamagui Version

```markdown
1.74.15
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://stackblitz.com/edit/github-ojykqm
```

**Comment by aschenkuttel** [comment]
same for me using 1.74.10

**Comment by natew** [comment]
The stackblitz is failing due to missing webpack-serve for me, closing until we get reliable repro.

**Comment by ArekBartnik** [comment]
@natew I've created an repo with repro (with NextJs as base) -> https://github.com/ArekBartnik/tamagui-button-outlined-problem and deployed it here -> https://tamagui-button-outlined-problem.vercel.app

There's also codesanbox if you prefer https://codesandbox.io/p/github/ArekBartnik/tamagui-button-outlined-problem :)

Using Tamagui v1.75.5
