### ISSUE TITLE
`TAMAGUI_TARGET` being set to `web` in Babel plugin

### ISSUE THREAD

**Issue by DimitarNestorov** [tamagui/tamagui#1777]
### Current Behavior

In `index.js` in `dist` it's hardcoded to `web`.
<img width="803" alt="image" src="https://github.com/tamagui/tamagui/assets/8790386/6251b0bf-96c3-43ae-acc0-d46ac0c919da">

### Expected Behavior

Should match source code:
https://github.com/tamagui/tamagui/blob/40843faefdfaa908bd48a3b6aa60005ddb8ec276/packages/babel-plugin/src/index.ts#L21

<img width="600" alt="image" src="https://github.com/tamagui/tamagui/assets/8790386/0743cd94-a09c-4c95-9e1a-758956abecd8">

### Tamagui Version

```markdown
1.74.15
```

### Platform (Web, iOS, Android)

N/A

### Reproduction

https://www.npmjs.com/package/@tamagui/babel-plugin/v/1.74.15?activeTab=code and open `dist/cjs/index.js`

This issue was first introduced in `1.62.0`

### System Info

N/A

**Comment by natew** [comment]
fix going out in next release - as of today it should all be compiled away anyway, but perhaps the native extension was picking this up weird
