### ISSUE TITLE
How to Customize Press State Styles for Tamagui's Button Component in React Native (IOS)?

### ISSUE THREAD

**Issue by tonyabracadabra** [tamagui/tamagui#1780]
I'm attempting to use Tamagui's Button component to build a React Native application, and I've encountered an issue with styling the "press" state. The Button component's hoverStyles are working perfectly on the web. However, I'm struggling to achieve similar functionality on mobile, specifically in the iOS simulator.

Here's the code snippet I'm using:

```
<Button pressStyle={{ bg: 'cyan' }} pressTheme={true} onPress={() => console.log('pressed!')}>
  Plain
</Button>
```

Tamagui Version
```
1.74.15
```

Platform
```
IPhone 14 Simulator
```

I expect the button's background to change to cyan when pressed. However, both pressStyle and pressTheme are not producing the desired effect, despite the onPress event firing correctly (confirmed by the console log output).

How can I get the button background to change to cyan on press in the React Native iOS simulator?

**Comment by pierroo** [comment]
I confirm that pressStyle was broken somewhere along the way :/

**Comment by natew** [comment]
this is on my next up todos, but just know the official starter templates work and so does the uniswap app and my personal app, along with a variety of client apps i checked in with. but i believe its breaking in some way, a repro would really help me help you guys fix!

**Comment by masrurimz** [comment]
> Updates: I downgraded the package to version `1.61.1` and the pressStyle works again @natew

How do you downgrade tamagui from T4 stack ?
I downgrade it but got this error
<img width="1032" alt="Screenshot 2023-10-22 at 18 53 26" src="https://github.com/tamagui/tamagui/assets/8275908/e8006001-c6fd-47e1-a599-c0acac83867a">

**Comment by johnsimeroth** [comment]
I also just upgraded today hoping to fix an issue where pressStyle stayed on forever and ended up with pressStyle doing nothing at all (V 1.98.1).
