### ISSUE TITLE
tamagui styles broken

### ISSUE THREAD

**Issue by hiroingk** [tamagui/tamagui#1784]
<img width="1259" alt="image" src="https://github.com/tamagui/tamagui/assets/36590410/b1bed766-9248-47b6-824a-d022894e5b79">

The style in the official tamagui documentation is broken.
Also, the style is broken in my project storybook as well.

**Comment by natew** [comment]
It seems Vercel is having some issues, I've rolled it back but we're seeing breaking styles despite proper builds locally and across different projects without any changes. Thanks for the heads up.
