### ISSUE TITLE
styled() theme property works in dev but not prod build

### ISSUE THREAD

**Issue by johnsimeroth** [tamagui/tamagui#1794]
### Current Behavior

I have a component named Pre that uses styled() to set the text and background color
```
export const Pre = styled(SizableText, {
  name: 'Pre',
  theme: 'dark_green',
  color: '$color9',
  backgroundColor: '$gray3',
  numberOfLines: 0,
  tag: 'pre',
})
```

**In dev mode, the text color is dark green 9, as expected, but in prod mode it's gray 9.**

### Expected Behavior

Consistent dev and prod behavior.

### Tamagui Version

```markdown
1.74.17
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
repro here: https://github.com/johnsimeroth/tamagui-web-bug-1

steps:
1. `npm create tamagui@latest`
2. choose next/expo/solito
3. create styled component as shown in overview above
4. run yarn:web and see text is green
5. run yarn web:prod
6. run yarn web:prod:serve and see text is grey
```

### System Info

```markdown
System:
    OS: macOS 13.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 2.21 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 3.6.3 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 16.6
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.39.0 
    node-gyp: ^9.3.1 => 9.3.1 
    prettier: ^2.7.1 => 2.8.8 
    turbo: ^1.10.3 => 1.10.3 
    typescript: ^4.9.4 => 4.9.5 
```
```

**Comment by johnsimeroth** [comment]
Obviously not a critical issue since I can just use '$green9' here and get rid of the theme prop. But unexpected behavior that might have bigger implications for someone else.

**Comment by johnsimeroth** [comment]
<img width="554" alt="Screenshot 2023-10-20 at 9 27 16 AM" src="https://github.com/tamagui/tamagui/assets/51033195/8810ba11-dc00-4607-962e-7bbe8710b46e">
<img width="554" alt="Screenshot 2023-10-20 at 9 27 11 AM" src="https://github.com/tamagui/tamagui/assets/51033195/3432b742-1606-4e96-865f-361cc6d5fba3">

**Comment by TheEhsanSarshar** [comment]
@johnsimeroth thanks for reporting! It should be fixed with the next release!
