### ISSUE TITLE
Unexpected text node: SpecialButton. A text node cannot be a child of a <View>.

### ISSUE THREAD

**Issue by christianalares** [tamagui/tamagui#180]
**Describe the bug**
When using the Button-component in web together with the `styled`-function I get the following error:
`Unexpected text node: SpecialButton. A text node cannot be a child of a <View>.`

**To Reproduce**
```javascript
import { Button, styled } from 'tamagui';

const SpecialButton = styled(Button, {
  color: 'red',
});

const Component = () => {
  <SpecialButton>SpecialButton</SpecialButton> /* <-- Gives error */
  /* <Button>Button</Button> */ /* <-- Works fine */
}
```

**System Info (please complete the following information):** 
Output of `npx envinfo --system --npmPackages '{vitest,vite,@vitejs/*}' --binaries --browsers`

```
System:
  OS: macOS 12.4
  CPU: (10) x64 Apple M1 Max
  Memory: 418.04 MB / 64.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 14.18.2 - /usr/local/bin/node
  Yarn: 4.0.0-rc.13 - /usr/local/bin/yarn
  npm: 8.5.3 - /usr/local/bin/npm
Browsers:
  Chrome: 104.0.5112.101
  Firefox Developer Edition: 104.0
  Safari: 15.5
  Safari Technology Preview: 15.4
```

**Comment by natew** [comment]
In the latest versions it should warn that `styled(Button)` is not actually allowed. The way `styled()` works is it takes either a base React Native view, or another styled view, but not just any old component. Button is a functional component so it doesn't work, but I did add a warning recently that should say as much.

It's possible eventually to get this to work, I think, but it's more complicated than it may seem so I'm holding off for a while.
