### ISSUE TITLE
Property 'React' doesn't exist

### ISSUE THREAD

**Issue by ayushsharma82** [tamagui/tamagui#1801]
### Current Behavior

Hi @natew ,

I just upgraded tamagui from v1.64.4 to v1.75.1 using `yarn upgrade:tamagui` on my Expo app and the whole thing crashed with `Property 'React' doesn't exist` error. What could cause this?

Note: I just upgraded tamagui, nothing else.

### Tamagui Version

```markdown
v1.75.1
```

### Platform (Web, iOS, Android)

```markdown
React Native Only
```

### Reproduction

```markdown
yarn upgrade:tamagui
```

**Comment by natew** [comment]
Need a stack trace. You can probably patch by just setting React as a global but the question is what’s causing it.

**Comment by rizaldirnm** [comment]
Hi @natew I have same problem but I am using "React-Native CLI"
I just kick starter project for learning purpose

Package:
- React: 18.2.0
- react-native: 0.73.4
- tamagui: ^1.89.28

```javascript
my current babel.config.js

module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};
```

I assume some config in `babel.config.js` is needed.

This is error stack hopefully help to debug

![CleanShot 2024-02-17 at 19 35 26@2x](https://github.com/tamagui/tamagui/assets/26857590/e68dc550-c23b-4b69-80b1-486323a406d2)
![CleanShot 2024-02-17 at 19 35 11@2x](https://github.com/tamagui/tamagui/assets/26857590/3b8bbb99-e611-4a9c-abfa-e02708afc0c5)

**Comment by natew** [comment]
I think I know why this just popped up again. Have a fix for next release. You can set globalThis.React for now to the react import

**Comment by natew** [comment]
This should be fixed in the last couple patch releases. We added a process step in the build script that reverted the jsx setting from automatic. Sorry for the trouble!

**Comment by rizaldirnm** [comment]
Thank you nate for quick response.
