### ISSUE TITLE
Performance issue on Android and IOS devices

### ISSUE THREAD

**Issue by Tekdey** [tamagui/tamagui#1807]
### Current Behavior

Page renderer is slow when they are more multiple components on the page, we are using this monoreop to develop a cross platfrome application and after  our first release we notice a performance issues on multiple devices (list is below). These performance issue were seen on dev mode and we thought  that after the  apk release the app will be faster but it is not the case. 

We pick Tamgui for the performance  benchmark and I think that the issue is coming from the combination between expo and Tamgui

Please check the reproduction github project below

### Expected Behavior

Should not have not latences when they are less component rendered and should not have to rerender component when the static page is already visited.

### Tamagui Version

```markdown
1.75.4
```

### Platform (Web, iOS, Android)

```markdown
Android : Samsung Galaxy Tab A7 SMT 500, Samsung Galaxy A14
IOS : Iphone 12
```

### Reproduction

```markdown
Starter repository : https://github.com/tamagui/tamagui/tree/master/starters/next-expo-solito
Reproduction repository : https://github.com/Tekdey/tamagui-latences

To explain this bug I did a simple scrollview with some elements on another page, (did not work when they are many component on the page not du to this map specifically) : 

<ScrollView>
            {Array.from({ length: isWeb ? 1 : 100 }).map((_, i) => (
                <ReseauCard key={i}
                uri={"https://images.unsplash.com/photo-1682687220640-9d3b11ca30e5?auto=format&fit=crop&q=80&w=1770&ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"} />
            ))}
</ScrollView>
```

When i navigate on this page, the navigation is super slow and i should wait 1-5 seconds before render this page. 

I tested with native components and i have the same problem that's why I think that the issue is coming from the monorepo.
I built the project with an apk and i have same problem. 

I tried to use the last version of expo, test on faster devices like Samsung S22 and the app is slow
```


### System Info

```markdown
System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 918.75 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 3.6.3 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Watchman: 2023.01.09.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 116.1.57.53
    Chrome: 118.0.5993.88
    Firefox: 116.0.1
    Safari: 16.1
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.39.0 
    node-gyp: ^9.3.1 => 9.3.1 
    prettier: ^2.7.1 => 2.8.8 
    turbo: ^1.10.3 => 1.10.3 
    typescript: ^4.9.4 => 4.9.5
```

**Comment by natew** [comment]
You say you tested with native components and its still slow? This is definitely not a Tamagui issue. We have extensive benchmarks and our performance is close to native, when you use the optimizing compiler equal to it in many cases. I need a clear example where its slow.

**Comment by Tekdey** [comment]
HI @natew ,
did you check the reproduction URL  https://github.com/Tekdey/tamagui-latences ?
You have a complete and simple example of the issue.  could you test it ?

**Comment by Kidvalram** [comment]
Same problem too, actually after to use the project in iOS you can't see any problem at all, but after to test it in an Android device is really slowly.
Is not possible to run and deploy a project like to the market 🙁
