### ISSUE TITLE
Outlined variant not applying to Button (new reproduction)

### ISSUE THREAD

**Issue by ArekBartnik** [tamagui/tamagui#1810]
### Current Behavior

(this is a new version of issue #1775  with working reproduction)

Variant `outlined` isn't applying to Button like we can see in docs.
<img width="832" alt="CleanShot 2023-10-27 at 15 47 15@2x" src="https://github.com/tamagui/tamagui/assets/1569446/0ad1aff2-b6ee-4a6c-88b9-e05a1371b135">

### Tamagui Version

```markdown
v1.75.5, v1.76.0
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

repo (with NextJs as base) -> https://github.com/ArekBartnik/tamagui-button-outlined-problem

deploy -> https://tamagui-button-outlined-problem.vercel.app

codesandbox -> https://codesandbox.io/p/github/ArekBartnik/tamagui-button-outlined-problem

### System Info

```markdown
macOS Ventura 13.6, Chrome, Firefox, Safari
```

**Comment by alitnk** [comment]
This happens due to `$borderColor` resolving to `transparent`. Not sure why yet but that's what I got looking at the sandbox.

**Comment by pluveto** [comment]
The same issue exists with the current latest version

**Comment by TheEhsanSarshar** [comment]
wasn't able to re-produce it on the web, I'll close it as resolved. feel free to re-open
```jsx
 <Button variant="outlined">
     <Button.Text>Hey</Button.Text>
 </Button>
  ```

**Comment by BooDzioo** [comment]
Error still occurs in v1.116.12

**Comment by alfawal** [comment]
@byteab 

I'm encountering a similar issue on IOS (`tamagui@^1.132.15`) where the outline variant doesn't have a an outline as well as the clicking effect.

I'm using the Ignite template but as I've checked, it shouldn't have anything to do with this issue.

<img width="342" height="257" alt="Image" src="https://github.com/user-attachments/assets/2842b620-3c1f-44aa-9331-1d6680fb57ea" />

Config:
```ts
import { createTamagui, createTokens } from "tamagui"
import { defaultConfig, shorthands } from "@tamagui/config/v4"
import { color, radius, size, space, themes, zIndex } from "@tamagui/themes"

const tokens = createTokens({
  size,
  space,
  zIndex,
  color,
  radius,
})

const config = createTamagui({
  ...defaultConfig,
  shorthands,
  themes,
  tokens,
})

type Conf = typeof config

declare module "tamagui" {
  interface TamaguiCustomConfig extends Conf {}
}

export default config
```

Code:
```tsx
import { Activity, Airplay } from "@tamagui/lucide-icons"
import { Button, XGroup, XStack, YStack } from "tamagui"

export default function LoginScreen() {
  return (
    <YStack flex={1} justify="center" verticalAlign="center" p="$4" bg="$color.yellow10Light">
      <YStack p="$3" gap="$3">
        <Button>Plain</Button>
        <Button self="center" icon={Airplay} size="$6">
          Large
        </Button>
        <XStack gap="$2" justify="center">
          <Button size="$3" theme="red">
            Active
          </Button>
          <Button size="$3" variant="outlined">
            Outlined
          </Button>
        </XStack>
        <XStack gap="$2">
          <Button themeInverse size="$3">
            Inverse
          </Button>
          <Button iconAfter={Activity} size="$3">
            iconAfter
          </Button>
        </XStack>
        <XGroup>
          <XGroup.Item>
            <Button width="50%" size="$2" disabled opacity={0.5}>
              disabled
            </Button>
          </XGroup.Item>

          <XGroup.Item>
            <Button width="50%" size="$2" chromeless>
              chromeless
            </Button>
          </XGroup.Item>
        </XGroup>
      </YStack>
    </YStack>
  )
}
```
