### ISSUE TITLE
@tamagui/lucide-icons not working with NextJS app router

### ISSUE THREAD

**Issue by gorbypark** [tamagui/tamagui#1812]
### Current Behavior

When importing and then using any icon from `@tamagui/lucide-icons` when using the NextJS app router there is the following error:
``` 
Internal error: ReferenceError: React is not defined
    at eval (webpack://next-app/node_modules/@tamagui/helpers-icon/dist/jsx/themed.js?c4e0:14:5)
```
Having a look at the contents of the dist/compiled version located in `node_modules/@tamagui/helpers-icon/dist/jsx/themed.js` it does indeed show that there is no `import React from 'react'` line.  Looking at the source of that file [https://github.com/tamagui/tamagui/blob/master/packages/helpers-icon/src/themed.tsx](https://github.com/tamagui/tamagui/blob/master/packages/helpers-icon/src/themed.tsx) shows there is actually an import line.  

If I monkey patch `node_modules/@tamagui/helpers-icon/dist/jsx/themed.js` to include `import React from 'react'` it makes everything work.

I'm not exactly clear of the entire transpilation process that NextJS is now using (swc), but it seems that somewhere along the line that import is being removed.  My theory is that it is probably due to the newish automatic JSX import feature of React, where importing React is not required for most components (and is being stripped by swc?).

I've attached a GitHub repo with a reproduction.  All icon usage have been commented out except for `packages/app/features/home/screen.tsx` line 66.  If you comment out that icon, the project will work.

### Expected Behavior

Working icons

### Tamagui Version

```markdown
1.75.5
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://github.com/gorbypark/tamaguisolitomono
```

### System Info

```markdown
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
    Memory: 246.53 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /opt/homebrew/opt/node@18/bin/npm
    pnpm: 8.6.12 - /opt/homebrew/bin/pnpm
    Watchman: 2023.09.18.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 16.5
```

**Comment by natew** [comment]
I have a fix slated for next release, but this seems like a NextJS bug and worth filing on their end. Closing but next patch release should fix on our side.
