### ISSUE TITLE
Image component not working on NExt side,

### ISSUE THREAD

**Issue by Oguzzsancaktar** [tamagui/tamagui#1813]
### Current Behavior

When we are trying to implement simple Image on cross platform next.js side says React is not defined;

### Expected Behavior

Need to show image on web browser.

### Tamagui Version

```markdown
1.75.5
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
We get that error.
```

**Comment by haveamission** [comment]
Did you find a solution to this problem?
