### ISSUE TITLE
Select.Item lacks an API to customize the styles of the selected state. 

### ISSUE THREAD

**Issue by PrimulaX** [tamagui/tamagui#1816]
I'm trying to change the background of the selected item inside the bottom sheet of list items, but I can't style the item accordingly because I don't have access to the selected state of `Select.Item`.

I want to change the background color of the selected item or any preferred style.
Tamagui version: ^1.75.4Ï

**Comment by TheEhsanSarshar** [comment]
Select take a `value` and `onValueChange` prop using that you can keep track of select item

<Select.Item value={itemValue}  bc={selectedValue === itemValue ? 'red' : 'gray' }>

**Comment by PrimulaX** [comment]
@TheEhsanSarshar I need this in `styled` `variants` not as inline comparison

**Comment by PrimulaX** [comment]
@TheEhsanSarshar why did you close this one?

**Comment by TheEhsanSarshar** [comment]
styled is supposed to take static props while open value is tied to a specific component state and it's not possible to access it that way, although you can create an `open` variant and then change the style according to that
```
const SelectItem = styled(Select.Item, {
     open: {
          true: {
             backgroundColor: 'red'
          }
     }
})
```
```<SelectItem open={seletedValue === itemValue} />```

**Comment by PrimulaX** [comment]
Hey @TheEhsanSarshar, I was looking forward to this type of solution: #1793
So I guess there is no possible way, The same question goes for `Tabs` component as well
