### ISSUE TITLE
styled() + variants sometimes breaking typescript types

### ISSUE THREAD

**Issue by ibedwi** [tamagui/tamagui#184]
**Describe the bug**

Following [this discussion](https://github.com/tamagui/tamagui/discussions/183), I tried to use several combinations of `LayoutStyles`. Turns out, some of the `LayoutStyles` makes type error, something like `"typescript: 'boolean' is not assignable to type never"`.

**To Reproduce**

```typescript
export const Circle = styled(View, {
  borderRadius: 100_000_000,
  backgroundColor: 'aqua',

  variants: {
    pin: {
      top: {
        flex: 1,
      },
    },
    centered: {
      true: {
        flex: 1,
        alignItems: 'center', // <--- this LayoutStyles will make the error
        justifyContent: 'center', // <--- this LayoutStyles will make the error
      },
    },
    size: {
      '...size': (size, { tokens }) => {
        return {
          width: tokens.size[size] ?? size,
          height: tokens.size[size] ?? size,
        };
      },
    },
  },
});

// Error: "typescript: 'boolean' is not assignable to type never"
const s = <Circle size="$10" centered pin="top" />;
```

**System Info (please complete the following information):** 

`package.json`

```json
{
  ...
  "dependencies": {
    ...,
    "tamagui": "^1.0.1-beta.160",
    "@tamagui/build": "^1.0.1-beta.141",
    "@tamagui/font-inter": "^1.0.1-beta.141",
    "@tamagui/next-plugin": "^1.0.1-beta.141",
    "@tamagui/next-theme": "^1.0.1-beta.141",
    "@tamagui/shorthands": "^1.0.1-beta.141",
    "@tamagui/theme-base": "^1.0.1-beta.141",
  }
}
```

```
 System:
    OS: macOS 12.5.1
    CPU: (8) x64 Apple M1
    Memory: 51.67 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2022.01.03.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 105.0.5195.102
    Safari: 15.6.1
```

**Comment by ibedwi** [comment]
Digging up through the Tamagui's codebase, I notice the variants object is typed `as const` [here](https://github.com/tamagui/tamagui/blob/91e8bbd0309000a6785dfdcca71d8622f701885e/packages/stacks/src/Stacks.tsx#L33)

I updated the code above and the error is gone

```typescript
export const Circle = styled(View, {
  borderRadius: 100_000_000,
  backgroundColor: 'aqua',

  variants: {
    pin: {
      top: {
        flex: 1,
      },
    },
    centered: {
      true: {
        flex: 1,
        alignItems: 'center', // <--- this LayoutStyles will make the error
        justifyContent: 'center', // <--- this LayoutStyles will make the error
      },
    } as const, // <-- added this, and the error is gone
    size: {
      '...size': (size, { tokens }) => {
        return {
          width: tokens.size[size] ?? size,
          height: tokens.size[size] ?? size,
        };
      },
    },
  },
});
```

**Comment by natew** [comment]
Yes, this is one if my biggest blockers before 1.0. I spent some time digging in and it’s hard to figure out why exactly this happens. But thanks for documenting here and adding the temporary solution.

**Comment by ibedwi** [comment]
> Yes, this is one if my biggest blockers before 1.0. I spent some time digging in and it’s hard to figure out why exactly this happens. But thanks for documenting here and adding the temporary solution.

I see. No problem, I think this is good for now 😁  
Thanks!

**Comment by natew** [comment]
All good. I’ll reopen actually just so others can find it.

**Comment by captDaylight** [comment]
Great find @ibedwi, this is super helpful workaround for the time being!

**Comment by natew** [comment]
Aha, this is the related issue: https://github.com/microsoft/TypeScript/issues/30680

**Comment by natew** [comment]
Closing again, `as const` is documented until we can get rid of it.
