### ISSUE TITLE
Custom component themes are broken

### ISSUE THREAD

**Issue by hackily** [tamagui/tamagui#1844]
### Current Behavior

Custom component subthemes don't work.

### Expected Behavior

If I have a theme called `custom` and a component called `Link` then the Link component should use the `custom_Link` theme.
https://tamagui.dev/docs/intro/themes#component-themes

### Tamagui Version

```markdown
Broken in 1.76.0-1.79.7
Last working version 1.75.9
```

### Platform (Web, iOS, Android)

```markdown
Web
Didn't test ios/android
```

### Reproduction

```markdown
https://codesandbox.io/p/devbox/focused-hill-j6vty4?file=%2Fpackages%2Fapp%2Ffeatures%2Fhome%2Fscreen.tsx%3A40%2C14
```

### System Info
```
  System:
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 104.06 MB / 2.01 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 3.6.3 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.39.0 
    node-gyp: ^9.3.1 => 9.3.1 
    prettier: ^2.7.1 => 2.8.8 
    turbo: ^1.10.3 => 1.10.3 
    typescript: ^4.9.4 => 4.9.5 
  ```

**Comment by natew** [comment]
Likely due to not having `light_custom` and `light_custom_Link` I assume its under the root light so it doesn't find it. Still a bug but at least easy to fix in the interim.

**Comment by hackily** [comment]
I updated the reproduction sandbox, but my defaultTheme is set to `custom` so I would expect that I don't need to prefix with `light` if I'm not using that theme anywhere in my app.

I tested again, 1.75.9 is the last working version, 1.76.0 is the first version this broke and component themes are still broken in 1.79.7

**Comment by timothymiller** [comment]
It's hard to tell from the codesandbox what the correct pattern for custom themes should be.

From reading the [docs](https://tamagui.dev/docs/intro/themes), it seems like this is the correct pattern?

```tsx
import { Button, styled } from 'tamagui'

export const CustomButton = styled(Button, {
  name: 'CustomButton',
  backgroundColor: '$green10',
  color: '$green10',
})

export const dark_CustomButton = {
  backgroundColor: '$red10',
  color: '$red10',
}

export const light_CustomButton = {
  backgroundColor: '$blue10',
  color: '$blue10',
}
```

In either case, it doesn't set the component theme based on the prefix theme objects like I'd expect. 

Coming from a `starter-free` base w/ Tamagui `v.1.75.9`

**Comment by natew** [comment]
New version fixes a few component theme things, lmk if still an issue
