### ISSUE TITLE
Animation does not work error No animation prop given to component with enterStyle / exitStyle, these styles will be ignored

### ISSUE THREAD

**Issue by theyanniss23002** [tamagui/tamagui#1846]
I took an instance of the Tabs component example from the tamagui documentation and it doesn't work...
https://tamagui.dev/docs/components/tabs/1.7.0

**Comment by theyanniss23002** [comment]
<img width="462" alt="Снимок экрана 2023-11-07 в 16 15 08" src="https://github.com/tamagui/tamagui/assets/57316921/dfd1c791-c387-4609-a55f-2f0933cfe602">
<img width="471" alt="Снимок экрана 2023-11-07 в 16 15 14" src="https://github.com/tamagui/tamagui/assets/57316921/3c824b95-f4e8-4134-8dfd-5d5d1c9d4539">

https://github.com/tamagui/tamagui/assets/57316921/d0b3fee7-6e62-46ef-80b1-f52406bd00a3

**Comment by natew** [comment]
Tabs demos work on the kitchen sink which uses the same code as the site examples! Need a repro
