### ISSUE TITLE
TextInput should have an Icon/IconAfter prop

### ISSUE THREAD

**Issue by maxkrieger** [tamagui/tamagui#1848]
Pretty common usecase to have a preceding icon for eg search fields

**Comment by osmanyz** [comment]
It would be nice if that icon could provide a button functionality too.

**Comment by natew** [comment]
There's a PR for this that could use someone to help get it across the finish line, you guys should help there.'

https://github.com/tamagui/tamagui/pull/1654

Don't use issues for this, Discussions are where we take requests.
