### ISSUE TITLE
Option to use react-native-linear-gradient instead of expo-linear-gradient

### ISSUE THREAD

**Issue by coycoylaniba** [tamagui/tamagui#1849]
I have a project and I don't want to use expo on it but I want to use `tamagui` for the ui elements but I'm stuck on the `<LinearGradient />` component from `tamagui` because it requires `expo-linear-gradient`. Is it possible if I can use `react-native-linear-gradient` instead of `expo-linear-gradient`? Thank you

**Comment by natew** [comment]
Any reason? It's easy to wrap any component, you may even be able to just do `styled()` and have it work.

**Comment by coycoylaniba** [comment]
@natew really? that's great. sorry i have no idea `styled()` works with custom components, i did not read all the docs. thanks!
