### ISSUE TITLE
AlertDialog: action buttons' callbacks are not trigged in native alerts

### ISSUE THREAD

**Issue by jnak** [tamagui/tamagui#1852]
Currently, the recommended way to pass callbacks to `AlertDialog` is to use [the Press events](https://tamagui.dev/docs/intro/props#press-events) on the `Button` elements nested in `AlertDialog.Action`. However, those do not get called when the `AlertDialog` is rendered natively (i.e. `<AlertDialog native>`). The only way to pass a callback on native is to use `onOpenChange` but there is only one for the entire dialog.

**Comment by natew** [comment]
Need a more clear example + repro, but the native alertdialog is limited, what do you want to do?

**Comment by jnak** [comment]
We'd like to attach a callback to each action (e.g. `onClickOk` and `onClickCancel`). Using the  [example from the AlertDialog](https://tamagui.dev/docs/components/alert-dialog/1.0.0), the callbacks `onCancel` and `onAccept` will be called on web, but not on native. 

```ts
export function AlertDialogDemo() {
  return (            
              ...
              <AlertDialog.Cancel asChild>
                <Button onPress={onCancel}>Cancel</Button>
              </AlertDialog.Cancel>
              <AlertDialog.Action asChild>
                <Button theme="active" onPress={onAccept}>Accept</Button>
              </AlertDialog.Action>
            ...
  )
}
```

It should be possible to attach callbacks since [`Alert` in react-native](https://reactnative.dev/docs/alert) allows passing an onPress prop to each action.
