### ISSUE TITLE
ios: Stack swallows all onPress events

### ISSUE THREAD

**Issue by Fuzzyma** [tamagui/tamagui#1853]
On ios (v17.0), whenever I put a Pressable, Button or anything that receives a press event into any tamagui stack, the pressable stops working. It just doesnt receive any press event anymore.
On android that works fine and I would expect it to work since I use XStack and YStack to build layouts.
Am I wrong in assuming that this should just work?

This is the code that I was testing with:
```tsx
<YStack>
  <Pressable onPress={() => console.log("Pressed")}>
    <Text>Press Me</Text>
  </Pressable>
</YStack>
```

I am using expo in case that matters

**Comment by hackily** [comment]
Can you put your onPress directly onto the Stack?

**Comment by Fuzzyma** [comment]
I tested that as well. If a Stack is in another Stack it wont work

**Comment by hackily** [comment]
Are you using the tamagui compiler? I've run into a bug similar to that before on a different set of components
Perhaps try adding a `disableOptimization` prop on the stack
https://tamagui.dev/docs/intro/compiler-install#disabling-the-compiler

From the Babel/Metro section:
> Note that the @tamagui/babel-plugin is completely optional, and on native Tamagui doesn't optimize as much as on web, so leaving it out is actually recommended to start. If later on you feel the need for a bit more speed, you can try adding it.

**Comment by Fuzzyma** [comment]
No, I didnt activate it yet for exactly the reason you quoted. My app is not performance sensitive at all so I doubt I will ever enable it

**Comment by natew** [comment]
I believe in react native pressable inside pressable doesn't work. Our onPress uses Pressable so this can cause issues. But that should only happen if you have onPress or pressStyle or something. Let me check..

**Comment by Fuzzyma** [comment]
@natew I figured out my mistake. There was a fullscreen stack covering everything else and basically blocked any input -.-
Its weird how it still worked in android.

I will close this since this is clearly a user error. Sorry for the inconvenience!

**Comment by mphill** [comment]
@Fuzzyma I think you did find a bug.

Can you try this snippet of code and see if tapped shows in the console?

```tsx
           <YStack>
                <XStack>
                    <XStack>
                        <YStack onPress={() => console.log("tapped")}>
                            <Paragraph>Tap me</Paragraph>
                        </YStack>
                    </XStack>
                </XStack>
            </YStack>
```

**Comment by mphill** [comment]
For anyone who sees this issue and uses https://gorhom.github.io/react-native-bottom-sheet/

Please see https://gorhom.github.io/react-native-bottom-sheet

When using Gorhom's bottom sheet, buttons from Tamagui will work fine but if you want to make anything else tapable you must use `TouchableOpacity` or an analog.
