### ISSUE TITLE
Tamagui starter not compatible with Expo EAS build

### ISSUE THREAD

**Issue by dohomi** [tamagui/tamagui#186]
**Describe the bug**
Starting a new project with `npm create tamagui-app@latest` will not successful build on Expo EAS services. This is mostly I think due to the fact that the tamagui-app starter uses yarn v3 which seems not compatible with Expo services.

**To Reproduce**
Run `npm create tamagui-app@latest` and install all dependencies. After that drop a minimal eas.json into the `apps/expo` folder:
```json
{
  "build": {
    "development": {
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      },
      "ios": {
        "simulator": true,
        "image": "latest"
      }
    },
    "production": {
      "distribution": "store",
      "android": {
        "buildType": "app-bundle"
      }
    }
}
```
Last run following command in `apps/expo` folder
```
eas build --profile development --platform ios
```

See attached screenshot that on ios builds the eas build hangs and does not complete.

**System Info (please complete the following information):** 
```
  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.20 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Brave Browser: 105.1.43.88
    Safari: 15.5

```
<img width="638" alt="Screenshot 2022-08-18 at 17 07 42" src="https://user-images.githubusercontent.com/489221/188369718-65222ced-ac14-47aa-8531-6612f324d08f.png">

**Comment by dohomi** [comment]
@natew should I provide a PR with a fix? basically the package.json needs to be adjusted to downgrade to yarn v1 and a minimal eas.json needs to be present inside of the expo folder. Then the iOS build runs successful

**Comment by dohomi** [comment]
The Android build does not complete. The `gradlew` tab looks ok but the build exceeds 45mins and fails 
<img width="1216" alt="Screenshot 2022-09-05 at 15 26 11" src="https://user-images.githubusercontent.com/489221/188392622-2a5cb14e-037a-4521-bf86-e2fc46cb0b73.png">

**Comment by natew** [comment]
@dohomi thanks a bunch for checking into this, weird that v3 isn't supported it's been out for so long (and it had a node-link option to have compat).

If you can get everything working with v1 that's fine, but have a link to v3 issue on it being broken with EAS? I haven't used EAS in over a year for our app, but I *think* I was using yarn 3 back then and had it working... maybe not.

**Comment by dohomi** [comment]
@natew I think this one is related, it seems that Metro under the hood causing this issue:
https://github.com/expo/expo-cli/issues/1073
After downgrade to yarn v1 iOS succeeds but Android doesn't. You can try out the behaviour with the current starter. Maybe it would be a good idea to run Github actions and run eas builds against the codebase to see if everything still works.

My main intention to use Tamagui is with the combination of Expo and EAS because that was the pain point in the past (Capacitor, Cordova etc) I was dealing with. I want to throw some money at a company dealing with the native builds its been such a hassle in the past..

**Comment by natew** [comment]
I think that issue is unrelated because we don't use PnP mode.

I was able to get it at least to just say success just by adding the `eas.json`:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/12100/189030146-395e171b-1c7c-4ae6-b82f-91bd3793351d.png">

**Comment by dohomi** [comment]
@natew did you succeed with `--platform android` as well? Its strange I just checked on version 160 the starter and ran your command and it did not even finish the install on iOS

**Comment by hlynurstef** [comment]
@dohomi @natew I'm using version 160 currently and yarn v1 and I've successfully built ios with expo eas but the android build hangs on the same place as you posted. As you can see in the following screenshot, the build has been over 70 minutes and just hangs on this spot:

![image](https://user-images.githubusercontent.com/15615089/189890702-e9f879ad-2bf9-460a-90f5-bfaba6dfa3de.png)

**Comment by dohomi** [comment]
@hlynurstef I haven't found a solution yet..

**Comment by hlynurstef** [comment]
@dohomi I tried removing the `@tamagui/babel-plugin` from my `babel.config.js` and rerunning the android eas build and this time it succeded.

According to the [Expo docs](https://docs.expo.dev/build-reference/variables/#built-in-environment-variables) you can use the environment variable `EAS_BUILD_PLATFORM` to conditionally disable the `@tamagui/babel-plugin` on android as a way to get android building until this gets fixed.

**Comment by dohomi** [comment]
@hlynurstef great to know, I think this was what @natew already suspected to be the cause

**Comment by SushritPasupuleti** [comment]
Was on stock config 1.65, and both builds worked for me after following [the expo docs](https://docs.expo.dev/build-reference/variables/#built-in-environment-variables) just as @hlynurstef mentioned. And can confirm it works on 1.70 as well

**Comment by natew** [comment]
Added this exception to the default starter template for now.

**Comment by dohomi** [comment]
@SushritPasupuleti did you use yarn v1 or yarn v3 to make it work with iOS builds? I currently still downgraded to yarn v1

**Comment by SushritPasupuleti** [comment]
> @SushritPasupuleti did you use yarn v1 or yarn v3 to make it work with iOS builds? I currently still downgraded to yarn v1

Yarn v3 here, had no issues getting builds, I just ran it before replying as a sanity check. I'd suggest trying it in a VM once, you know same setup but eliminate any other variables. This worked for me a couple months ago when I had a similar eas build issue with another monorepo config I was trying out.

**Comment by hlynurstef** [comment]
@natew any updates on this?

**Comment by natew** [comment]
I thought it was working so long as the babel plugin is removed conditionally, @dohomi can you confirm? Does it properly render with styles and everything?

I'm revisiting this once this gets merged: https://github.com/tamagui/tamagui/pull/280 which is almost there just a couple last animation fixes.

**Comment by dohomi** [comment]
currently you have to follow https://github.com/tamagui/tamagui/issues/186#issuecomment-1246066111 and it should work.

**Comment by natew** [comment]
Working on this now.

**Comment by natew** [comment]
I'm seeing this on my first attempt, despite runtime being in deps:

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/12100/198855337-07084fae-2af0-41f7-abe5-1d16ae173d46.png">

Anyone else?

**Comment by natew** [comment]
May be fixed in 205, if anyone can confirm

**Comment by wekongsi** [comment]
> Expo EAS

Having the exact same issue, don't think it's resolved yet
