### ISSUE TITLE
`Popover` does not trap focus anymore

### ISSUE THREAD

**Issue by TimPetricola** [tamagui/tamagui#1868]
### Current Behavior

When opening a `<Popover>`, it used to focus the first element, and then tabbing would stay in the popover (through a focus trap).

It's not the case anymore

### Expected Behavior

I'd expect focus to be trapped inside `Popopver.Content` when it's open, unless `trapFocus` is set to `false`

### Tamagui Version

```markdown
1.76.0
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
https://tamagui.dev/docs/components/popover
```

**Comment by TimPetricola** [comment]
Probably linked to the (accidental?) removal of `FocusScope` here https://github.com/tamagui/tamagui/commit/9965b17b83a6b043e0c40dd46886000372331ece#diff-b7929549816c3e897d28e33ff81904a2859ff0586853c68ccaaaffe0bf8ad899L434

**Comment by natew** [comment]
fixed on latest
