### ISSUE TITLE
onPress in production build (Next)

### ISSUE THREAD

**Issue by pontusab** [tamagui/tamagui#187]
**Describe the bug**
When using a Button from tamagui with `onPress` everything works in dev mode, but building and then running the event is not triggered. I found out that using `swcMinify: true` is the reason.

**To Reproduce**
enable: `swcMinify: true`
add a button
build project
start 

**System Info (please complete the following information):** 
  System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 23.15 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 4.0.0-rc.13 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.1

**Comment by natew** [comment]
Great catch. I'll check into why, guessing names are getting mangled somewhere they shouldn't.

**Comment by pontusab** [comment]
Can confirm it now works with the latest Next.js version and `swcMinify` set to true.
