### ISSUE TITLE
Android Sheet will move with keyboard even when moveOnKeyboardChange is false

### ISSUE THREAD

**Issue by ttonyxx** [tamagui/tamagui#1870]
### Current Behavior

The Sheet component will move with the keyboard even when I set moveOnKeyboardChange to false (it should be false by default anyway).

### Expected Behavior

It should remain stationary regardless of if the keyboard is there or not

### Tamagui Version

```markdown
1.76.0
```

### Platform (Web, iOS, Android)

```markdown
Android
```

### Reproduction

```markdown
This is the sheet I'm using: https://github.com/tomotime/tamagui/blob/main/tamagui-issues/components/CustomSheet.tsx.

I also attached a video of the problem with the code above running:


https://github.com/tamagui/tamagui/assets/32372239/5ae41260-f5f7-4a80-b377-077cb21bebee



```

**Comment by nderscore** [comment]
> it should be false by default anyway

It is, in fact, `false` by default.

> the bug is there just too lazy to reproduce

How can you expect anyone to put effort in to resolve your issue if you can't be bothered to even post a code sample? I can guess that probably you're rendering a non-modal sheet inside of a `KeyboardAvoidingView`, but who knows really 🤷

**Comment by ttonyxx** [comment]
My bad 🙇, was a little late. Edited to issue to include the code I'm running with a video.

**Comment by ttonyxx** [comment]
> > it should be false by default anyway
> 
> It is, in fact, `false` by default.
> 
> > the bug is there just too lazy to reproduce
> 
> How can you expect anyone to put effort in to resolve your issue if you can't be bothered to even post a code sample? I can guess that probably you're rendering a non-modal sheet inside of a `KeyboardAvoidingView`, but who knows really 🤷

My bad 🙇, was a little late. Edited to issue to include the code I'm running with a video.

**Comment by TheEhsanSarshar** [comment]
I'll close this this issue seems working fine for others, @ttonyxx please share a repro if you still have this issue
