### ISSUE TITLE
(Select) Cannot update a component (`ForwardRef`)

### ISSUE THREAD

**Issue by j3sch** [tamagui/tamagui#1875]
### Current Behavior

I use the Select component example. When I click on it and the dropdown opens and hover the select item one below ("Pear") with the mouse pointer, I get the following error message in the console:

```client.js:1 Warning: Cannot update a component (`ForwardRef`) while rendering a different component (`Select`). To locate the bad setState() call inside `Select`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render```

With the Native Select it doesn't happen.

### Tamagui Version

```markdown
1.76
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://github.com/j3sch/tamagui-select-error
```

### System Info

```markdown
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 122.88 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.7.0 - ~/.nvm/versions/node/v19.7.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v19.7.0/bin/npm
    pnpm: 8.6.12 - ~/Library/pnpm/pnpm
    bun: 1.0.9 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.1
```

**Comment by natew** [comment]
this is due to theme fix we have another issue tracking it

**Comment by extralsc** [comment]
I have the same issues as above
