### ISSUE TITLE
Unable to resolve module @tamagui/helper-tamagui while debugging React Native app

### ISSUE THREAD

**Issue by QuangBinhDinh** [tamagui/tamagui#188]
**Describe the bug**
I follow all step in this site https://tamagui.dev/docs/intro/installation#native to install Tamagui into my exist React Native project. When start debugging app, this error appear .

<img width="571" alt="image" src="https://user-images.githubusercontent.com/43164997/188607954-61151397-f9dc-4abc-aa97-2cc23c1f4910.png">

 Can someone help me to solve this ?

**To Reproduce**
Include steps to reproduce.

**System Info :** 
My `react-native` version is 0.66.3

**Comment by natew** [comment]
Fix for this will be in next release later today. You can just add that dependency to your package.json for now.
