### ISSUE TITLE
position web types are wrong

### ISSUE THREAD

**Issue by benschac** [tamagui/tamagui#1883]
```tsx
// @ts-expect-error - TODO: fix this
    <YStack
      $platform-web={{
        pos: 'fixed',
      }}
      tag="nav"
      px
      w="100%"
      ai="center"
      py="$5"
    >
      {/* <li>Home</li>
      <li>About</li>
      <li>Experience</li>
      <li>Tech</li>
      <li>Works</li>
      <li>Feedbacks</li>
      <li>Contact</li> */}
    </YStack>
```

    
   missing other web props
    `export type Position = Globals | "-webkit-sticky" | "absolute" | "fixed" | "relative" | "static" | "sticky";`

**Comment by yaroslavdraha** [comment]
Also faced the same problem

**Comment by j3sch** [comment]
same problem

**Comment by natew** [comment]
@TheEhsanSarshar maybe small one, we can make just the $platform-web types accept all web props, not sure what the cleanest way is. Our usual struggles with type explosions could become an issue too.

**Comment by natew** [comment]
We need to flesh out the types for other ones now too, but it has to be done carefully because we can't just throw in CSSProperties or something like that where the `string` types would break our nice autocompletes.
