### ISSUE TITLE
Optimized build is producing wrong styles

### ISSUE THREAD

**Issue by matthewmturner** [tamagui/tamagui#1884]
## Current Behavior
I have a `contentContainer` theme defined as the following:

```
const light_contentContainer = {
	...baseLight,
	background: "#fff",
	backgroundFocus: tokens.color.gableGreen400,
	backgroundHover: tokens.color.gableGreen500,
	backgroundPress: tokens.color.gableGreen300,
	backgroundStrong: tokens.color.gableGreen,
	backgroundTransparent: "transparent",
	borderColor: tokens.color.gableGreen,
};

const dark_contentContainer = {
	...baseDark,
	background: tokens.color.gableGreen,
	backgroundFocus: tokens.color.blackLight100,
	backgroundHover: tokens.color.blackLight200,
	backgroundPress: tokens.color.blackLight300,
	backgroundStrong: tokens.color.blackLight400,
	backgroundTransparent: "transparent",
	borderColor: tokens.color.gableGreen,
};
```

I create a `styled` component as follows:

```
export const ContentContainer = styled(ThemeableStack, {
	theme: "contentContainer",
	backgroundColor: "$background",
	borderColor: "$borderColor",
	borderWidth: 1,
	borderRadius: "$10",
	mb: "$4",
	px: "$6",
	py: "$6",
});
```

In dev styles are applied as expected for the `contentContainer` theme but in the optimized prod build the background and borders are wrong.

## Expected Behavior
1. Consistent styling between dev and prod builds. 
2. Theme to be updated

## Platform
Web

## Reference
Screenshots
Dev:
<img width="1309" alt="image" src="https://github.com/tamagui/tamagui/assets/22136083/06fc45cb-e31a-48ab-a529-495eb9bf7905">

Prod:
<img width="1309" alt="image" src="https://github.com/tamagui/tamagui/assets/22136083/fd5b2b0a-26ba-466d-b5b9-f6e7487d83c3">

**Comment by matthewmturner** [comment]
So it seems this is related to importing / exporting.

The code i show above is all in packages/ui.  And the screen i show above is in packages/app.  I have some other cases where i am using contentContainer but within packages/ui and i dont have the issue there.

I was able to find a workaround for this by redefining the styled component in packages/app instead of importing from packages/ui.

what confuses me is that i was under the impression that these types of components were supposed to be defined in packages/ui.  am i misunderstanding?

**Comment by natew** [comment]
Weird, not able to replicate it in the sandbox, it outputs the right border and code.

![CleanShot 2023-11-18 at 12 49 33@2x](https://github.com/tamagui/tamagui/assets/12100/123fb166-1757-4218-9d19-2259d5f1a0bd)
![CleanShot 2023-11-18 at 12 51 09@2x](https://github.com/tamagui/tamagui/assets/12100/53eae52b-2120-4edf-8b23-81b5a8957836)
![CleanShot 2023-11-18 at 12 51 14@2x](https://github.com/tamagui/tamagui/assets/12100/a0971c96-ee74-439e-9772-73a5739fad3e)

**Comment by matthewmturner** [comment]
@natew How can I help? Would you like access to my repo?

**Comment by youniaogu** [comment]
Hi @matthewmturner i got same wrong behavior https://github.com/tamagui/tamagui/issues/1971 and also looking resolution

So is you `contentContainer` border style value with untransform tokens in prod?

**Comment by natew** [comment]
Reproduction and we will check it asap.

**Comment by TheEhsanSarshar** [comment]
@matthewmturner is this still an issue?

**Comment by matthewmturner** [comment]
yeah but havent upgraded recently so i wouldnt be seeing any recent fixes

**Comment by natew** [comment]
Plz re-opne with repo and we will fix
