### ISSUE TITLE
[Takeout] If already on Github Repo the "Claim Access" button returns 500 error

### ISSUE THREAD

**Issue by natew** [tamagui/tamagui#1893]
This file:

`apps/site/protected/_utils/github.ts`

The fetch in `inviteCollaboratorToRepo` will throw an error if you're already invited.

Ideally we check this up front so it doesn't show Get Access but rather shows "You're in!"

**Comment by alitnk** [comment]
Fixed on https://github.com/tamagui/tamagui/commit/703a772127d35d7550e57f8b7e4084a8e3360b5d
