### ISSUE TITLE
Performance and navigation latency

### ISSUE THREAD

**Issue by DMZakaria** [tamagui/tamagui#1895]
I initiated a project within our company using the [next-expo-solito](https://github.com/tamagui/tamagui/tree/master/starters/next-expo-solito) mono-repo. However, I encountered several issues related to performance and navigation latency on Android and iOS devices such as the Samsung Galaxy Tab A7 and A8.

There was a relevant issue that was closed a few weeks ago, and you requested additional details to determine whether the problem originated from Tamagui. Initially, I suspected a navigation issue due to the router or the development environment. However, after conducting tests on various devices, I observed that the problem specifically arises on the A7 and A8 tablets.

These tablets are equipped with 3G or 4G of RAM and run on Android 12. In contrast, when I tested on the Nexus 9, Samsung FE 21, and an iPad 8th generation, the performance was considerably better.

For my testing, I utilized the example from a previous [issue](https://github.com/tamagui/tamagui/tree/master/starters/next-expo-solito) and your starter with Expo and Tamagui. 

# Scenarios 

## Scenario 1 
Clicking on "Go to use page" reproduces the Tamagui component as demonstrated in your demo, and I duplicated them as illustrated in the image below.
![image](https://github.com/tamagui/tamagui/assets/6096779/d9bf6df1-4b13-4c9c-b348-ea0f26a45197)

When I add more Tamagui the performance is worse ! 

## Scenario 2
In this test, I showcase 100 elements per view. The initial sets of lists are basic, devoid of any UI or Tamagui components, while the subsequent lists incorporate Tamagui components. Additionally, I conducted a parallel test employing React Native components.

# Results

## Nexus 9 (Emulator): 

https://gyazo.com/796ec2510be6e182a26ce6a970d5df0b

## Samsung Galaxy FE 21 (real device): 
https://gyazo.com/9ec6f8805b661d6a62475f5eb4fab825

## Tab A8 (SM X205) and Tab A7 (SM T505), real devices:
https://gyazo.com/37084c61cb527b7b657d7029a788c7bf 

As demonstrated by this example using the released APK, there is noticeable latency in navigation that is absent when using Nexus 9 and FE 21. When additional components are added, the latency further increases. Unfortunately, I am unable to provide access to the actual application at this time. However, we are scheduled to launch at the beginning of next year, and our views include multiple forms and Tamagui components, where latency issues persist and increase if the view is more complex on Samsung tab devices.

PS: I am utilizing Vysor to mirror the screens of the devices on my computer. The problems are evident on recently acquired physical devices. The example involving the React Native list may not be directly applicable because I am employing Flatlist and not implementing lazy loading on the list with Tamagui (it was included merely for testing purposes). The primary concern arises when additional Tamagui components are added to a view, leading to poor performance. 

The source code can be found at this [URL](https://github.com/DMZakaria/tamagui).
You can download the [release APK](https://www.transfernow.net/en/dd?utm_source=20231120o3f1WYjx)

**Comment by natew** [comment]
Thanks for the detail, can I ask are you testing the Spinner/Select like in your screenshot, or the base Tamagui views? Without any form of reproduction I can't really tell what's happening.

What I can say is we profiled extensively and brought our performance to be at most 50% slower than vanilla RN, but often only 10% or even 0 if the optimizing compiler is working. It's possible there's some memory leak on Android, if you guys can isolate to a code snippet that would make this debuggable.

**Comment by DMZakaria** [comment]
Hello @natew, I'm currently utilizing the spinner/select feature as depicted in my screenshot for testing purposes. By the way, I've duplicated the lines of your code, and you can find the reproduction on this [URL](https://github.com/DMZakaria/tamagui). The relevant code snippet is as follows:

```

import { ArrowLeft } from "@tamagui/lucide-icons";
import { useRouter, useSearchParams } from "expo-router";
import { Button, H3, H6, XStack } from "tamagui";

import DialogDemo from "../../components/DialogDemo";
import { MyStack } from "../../components/MyStack";
import SelectDemo from "../../components/SelectDemo";
import SpinnerDemo from "../../components/SpinnerDemo";
import SwitchDemo from "../../components/SwitchDemo";

export default function User() {
  const router = useRouter();
  const params = useSearchParams();

  return (
    <MyStack justifyContent="flex-start">
      <XStack
        alignItems="center"
        space="$2"
      >
        <Button
          icon={ArrowLeft}
          onPress={router.back}
        />
        <H3>{params.user}&apos;s user page</H3>
      </XStack>

      <H6>Some Tamagui components in action.</H6>

      <DialogDemo />
      <SelectDemo />
      <SpinnerDemo />
      <SwitchDemo />

      <SpinnerDemo />
      <SwitchDemo />
      <DialogDemo />
      <SelectDemo />
      <SpinnerDemo />
      <SwitchDemo />
      <DialogDemo />
      <SelectDemo />
      <SpinnerDemo />
      <SwitchDemo />
    </MyStack>
  );
}

This is 
```

Adding additional Tamgui components will result in a latency issue in the view. Unfortunately, I'm unable to provide more than what I've already shared. However, I'm open to suggestions, and I'll do my best to provide any necessary input if you have recommendations.

**Comment by DDushkin** [comment]
A few days ago we added a Select component like from this example https://tamagui.dev/docs/components/select/1.40.0 and we noticed some performance issues on that screen. For example, navigation from Main to that screen with Select takes more time. Although we have around 20 select options.

**Comment by natew** [comment]
We likely need to do a few things for select like unmounting things until they need to load and then virtualizing things so it only shows on the screen.

One big unfortunate part of Select is SelectItem which is based on ListItem. I thought this was clever at the time because it gives you nice things like sub titles, icon, iconAfter, etc, but the cost is that you run a whole new level of component.

There could be some other slowness, Select is one of the most complicated components in the kit, there's a decent amount of context passing, portals, sheets, etc. We can profile and see.

**Comment by TheEhsanSarshar** [comment]
yeah, as Nate said those are complex components, and if you make sure that the compiler is enabled and working correctly you can achieve much better performance.

but at the end of the day, it's more react native limitation, you need to make sure to avoid re-renders on initial load and avoid heavy renders, for example, you can partially load part of the screen and then load the rest.

**Comment by vjeranc** [comment]
I think here it might be an even simpler issue.

A simpler example is having a Switch inside an Accordion.Item. If the Switch has a Switch.Thumb defined with animation, collapsing the accordion (unmounting the Switch) takes nontrivial amount of time. Removing the thumb or changing the animation to `quick` or `100ms` speeds up the collapse.

**Comment by natew** [comment]
100% sure we can get a lot faster within Tamagui-land, so if we can set up a test we just need to get a nice isolated example of slowness. Seems like you could set up a PR on this repo where you follow contributing instructions and make a repro in the kitchen sink app for us (can put it in testcases folder to auto have it load into a sub-screen). 

Or you can make a new tamagui app and just get the minimal slow case isolated. That'll help start the investigation.

**Comment by natew** [comment]
@danstepanov @benschac i think this does illustrate that we should create a plain expo go based place in the monorepo for people to more easily make repros here and send them as PRs because our current kitchen sink is more of a "test everything" place and requires a full build of an app.

**Comment by BANG88** [comment]
@natew do you have any plan for this. or any guides or thoughts we can implement it in local for test.

Thank you very much.

**Comment by vjeranc** [comment]
```jsx
<Accordion type="multiple">
  <Accordion.Item value="Settings">
    <Accordion.Trigger
      flexDirection="row"
      justifyContent="space-between"
    >
      <Text>Section</Text>
    </Accordion.Trigger>
    <Accordion.Content>
      <Switch id="theme" onCheckedChange={() => {}}>
        <Switch.Thumb animation="slow" />
      </Switch>
    </Accordion.Content>
  </Accordion.Item>
</Accordion>
```

This is minimal slow case. Try to collapse the accordion section and you'll see it takes a long time. Change `animation="slow"` to `animation="100ms"` and now it takes much less (but still too much).

**Comment by natew** [comment]
@TheEhsanSarshar this is a good one to grab as a quicker win, just to see what's going on with accordion. I mean height animations are just slow in CSS even, you're trigger layout on every frame so that probably is just a bad idea to animate those with spring until we get layoutanimations. But we can check to make sure we aren't triggering extra re-renders during the animation.

**Comment by TheEhsanSarshar** [comment]
Once the Switch animation finishes, Accordion will collapse. I'll take care of fixing that. Apart from that, I wasn't able to replicate any performance issues with Accordion.

**Comment by TheEhsanSarshar** [comment]
@vjeranc this [PR](https://github.com/tamagui/tamagui/pull/2003) will fix that Accordion issue

**Comment by vjeranc** [comment]
@TheEhsanSarshar This bug is now resurfacing for other components. Now if `Input` is inside an accordion `expand` takes a nontrivial amount of time. When `Input` is not inside an accordion, the accordion expands instantly.

**Comment by BenjiLee** [comment]
Not sure if this is the same issue but I've created a new RN app to isolate the loading issues with Tamagui Switch I was seeing. Any animation prop seems to cause RN to hang which increases with the number of switches used. https://github.com/BenjiLee/TamaguiSwitchPerf/tree/main

**Comment by zzorba** [comment]
Seeing the same issue today in version 1.125.34, use of `animation` on components (in my case customized Buttons), causes react-navigation to be very slow when rendering screens that contain them.

Taking out the button, or eliminating the animation eliminates the issue.  @BenjiLee did you ever find a workaround for this?
