### ISSUE TITLE
[Feature] Support wrapping higher order Tamagui components with styled()

### ISSUE THREAD

**Issue by natew** [tamagui/tamagui#190]
`ListItem` and `Button` both don't support wrapping in `styled()` because they are actually higher order components that render out Tamagui styled() components inside. Supporting this feature is a bit involved to do right, I've looked into it a couple times but both times bailed out just due to it taking more time than I expected.

Adding this ticket to track the feature.

**Comment by dohomi** [comment]
@natew I think ideally it would be great if `styled` would accept any component which supports a `style` prop. This would make it easy to style any community RN components

**Comment by apperside** [comment]
So, given this is not possible yet, how do you suggest to create specific button variants and easily reuse them?
Should I handcraft something like this?


```typescript
type Props = { variant: 'variant1' | 'variant2' | 'variant3' } & ButtonProps;

export default function MyButton({variant,...props}: Props) {
  
  const button = useMemo(() => {
    switch (variant) {
      case 'variant2':
        // return customized button 2
        return <Button {...customProps2} {...props}></Button>;
      case 'variant3':
        // return customized button 3
        return <Button {...customProps3} {...props}></Button>;
      default:
        // return default button
        return <Button {...defaultProps} {...props}></Button>;
    }
  }, [variant,props]);

  return button;
}
```

**Comment by dohomi** [comment]
@apperside check out the newly added docs: **https://tamagui.dev/docs/components/button/1.0.0-beta.161#advanced-button-customization**

**Comment by apperside** [comment]
Thank you @dohomi , I had really missed it, thank you!

**Comment by natew** [comment]
Btw as of the latest betas you can wrap any component and it will use `style` by default. I haven't tested if this also fixes the Button/ListItem case.
