### ISSUE TITLE
How to dynamic type for styled component?

### ISSUE THREAD

**Issue by thienvu23** [tamagui/tamagui#1908]
### Current Behavior

import { FlatList } from 'react-native';
const FlatListStyled = styled(FlatList);

I get an ItemType is an unknown type

### Expected Behavior

I want using a dynamic type for ItemType of FlatList

### Tamagui Version

```markdown
1.78.0
```

### Platform (Web, iOS, Android)

```markdown
react-native expo
```

### Reproduction

```markdown
Create a dynamic type for styled FlatList component
```

**Comment by natew** [comment]
Still an issue in the latest?

**Comment by natew** [comment]
Seems to work for me, not sure what the ask is

**Comment by natew** [comment]
Oh it's to type the renderItem? Good point, this may be useful in the future as a feature. Converting to discussion.
