### ISSUE TITLE
"Expression produces a union type that is too complex to represent" when using `Spacer`

### ISSUE THREAD

**Issue by ArekBartnik** [tamagui/tamagui#1912]
### Current Behavior

![CleanShot 2023-11-24 at 22 25 54@2x](https://github.com/tamagui/tamagui/assets/1569446/811db8a4-b0ca-4cdd-9bc5-0ae5fe1aa964)

### Tamagui Version

```markdown
1.78.0 and 1.79.1 (so I would assume 1.78.0+)
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://codesandbox.io/p/github/ArekBartnik/tamagui-button-outlined-problem (don't look at the name, I've reused reproduction from another reported bug :))

The error is visible in `pages/index.tsx` file.
```

### System Info

```markdown
macOS Sonoma
```

**Comment by ifiokjr** [comment]
I'm having the same issue.

**Comment by hroland** [comment]
Same here

**Comment by mphill** [comment]
It's not confined to web BTW.  It only seems to occur with the `<Spacer />`
