### ISSUE TITLE
Select value can not controlled

### ISSUE THREAD

**Issue by satoren** [tamagui/tamagui#1928]
### Current Behavior

Select's Value display is not updated after changing the value of select.
If native select, it will be updated.

### Expected Behavior

Changing the value will also update the Select display

### Tamagui Version

```markdown
1.79.2
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

[codesandbox](https://codesandbox.io/p/sandbox/tamagui-select-forked-6qf76p?file=%2Fsrc%2FDemo.tsx%3A45%2C26&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clphlot6a00073b6isveaep5e%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clphlot6900033b6iohr6qh0y%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clphlot6900043b6ix5may2s6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clphlot6a00063b6ijrld2tql%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clphlot6900033b6iohr6qh0y%2522%253A%257B%2522id%2522%253A%2522clphlot6900033b6iohr6qh0y%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpkkpdix00il3b6iug04lzsm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A45%252C%2522startColumn%2522%253A26%252C%2522endLineNumber%2522%253A45%252C%2522endColumn%2522%253A26%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpkkpdix00il3b6iug04lzsm%2522%257D%252C%2522clphlot6a00063b6ijrld2tql%2522%253A%257B%2522id%2522%253A%2522clphlot6a00063b6ijrld2tql%2522%252C%2522activeTabId%2522%253A%2522clpkkgvc3009d3b6ihqgl21cf%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clpkkgvc3009d3b6ihqgl21cf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clphlot6900043b6ix5may2s6%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clphlot6900043b6ix5may2s6%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A16.636898184032177%257D)
```markdown

```

**Comment by TheEhsanSarshar** [comment]
if you want to change the selected value display box without opening the Selector bar then you need to render the selected value manually.

`<Select.Value>{selected}</Select.Value>`

the way Tamagui selects is working is that it clones the selected item and renders it inside `<Select.Value />`
but because you haven't opened that bar yet, then those components are not rendered yet.

**Comment by TheEhsanSarshar** [comment]
let me know if that fixes your issue
I'll close this

**Comment by satoren** [comment]
I had created a wrapper component that could be used in this way.
```tsx
<Select value={value} onValueChange={setValue}>
  {items.map((item, i) => {
       return (
         <Select.Item index={i} key={item.value} value={item.value}>
           <Select.ItemText>{item.name}</Select.ItemText>
         </Select.Item>
      )
   }
}
</Select>
```
Therefore, the above workaround could not be used because the value and the text actually rendered are different.

So my workaround is below.
```tsx
  const items = React.Children.map(props.children, (child) => {
    if (!React.isValidElement(child)) {
      return null;
    }
    return child
  })

  const selectedItem = items?.find((item) => item.props.value === props.value)
  ///......
          <Select.Value>
             {selectedItem?.props.children}
          </Select.Value>
```

**Comment by TheEhsanSarshar** [comment]
I don't think you need that much complexity, you have access to selected value. just render it inside <Select.Value>
