### ISSUE TITLE
iOS: Custom button - text with pressStyle. onPress doesn't work.

### ISSUE THREAD

**Issue by kzlar** [tamagui/tamagui#1929]
### Current Behavior

Scenario:

1. Only happens on iOS (works as expected on web, haven't checked Android)
2. I'm using a custom button following the guide https://tamagui.dev/docs/guides/how-to-build-a-button#the-solution-createstyledcontext
3. On my custom button text (`const ButtonText = styled(Text, { ... }`) when I apply a `pressStyle` prop, the `onPress` callback on the parent button is not called.

I guess this is somewhat of an edge case given how Tamagui implements pressStyle with Pressable. 

### Expected Behavior

I'd expect this to either be documented in the doc or fixed such that pressStyle would still be applied when pressing, but the parent button `onPress` would be called (perhaps through the context somehow)

### Tamagui Version

```markdown
latest
```

### Platform (Web, iOS, Android)

```markdown
iOS
```

### Reproduction

```markdown
No easy repro as this doesn't happen on web. Quick way to repro locally is to follow the custom button guide: https://tamagui.dev/docs/guides/how-to-build-a-button#the-solution-createstyledcontext
And change the custom button text to:

const ButtonText = styled(Text, {
  name: 'ButtonText',
  context: ButtonContext,
  color: '$color',
  userSelect: 'none',

  pressStyle: {
    color: 'red'
  }
  variants: {
    size: {
      '...fontSize': (name, { font }) => ({
        fontSize: font?.size[name],
      }),
    },
  } as const,
})
```
```


### System Info

_No response_

**Comment by kzlar** [comment]
@natew yep it's still an issue: https://github.com/kzlar/starter-free/commit/ef721a27b5b523dfeb762ce2d5afdff38c3a88fd
Not sure how to re-open this issue, should I create a new one?

**Comment by TheEhsanSarshar** [comment]
This is a behavior/limitation in React Native
pressable onPress won't be called when you have a nested onPress
<Pressable>
    <Text onPress />
</Pressable>
one workaround is to use `onTouchEnd` instead of `onPress` on the button

**Comment by kzlar** [comment]
@TheEhsanSarshar yeah I figured it's something like that.
IMHO there are 2 options here:

1. Implement a "hack" on tamagui's side (such as automatically transferring the onPress to the text). I appreciate this might be "ugly" but I'm sure it's not the ugliest hack for the sake of cross platform parity ;)
2. Add this caveat and workaround suggestions in the docs.

Keep in mind that from the point of view of a developer (i.e. Tamagui user), the whole point is feature parity without having to manage the kinks of each platform, to the highest degree possible. Having a feature (`pressStyle`) that breaks another feature (`onPress`) isn't ideal.

cc: @natew wondering what are your thoughts on this as well. And btw if you folks are open for a PR for option #1 and think it's suitable for a junior contributor I can take a stab at it.

**Comment by TheEhsanSarshar** [comment]
There could be a variety of bugs in react native that we may not be aware of, making it difficult to know and document each one or come up with a perfect solution. However, we can have a section in the documentation where we can highlight these limitations and provide some helpful workarounds. if you want to add that section, really appreciate it  ❤️

although for styling the content of a button it's more usual to capture `pressStyle` of the button and then make the Text child change style based on that just like in CSS `button:active > p` . which we have [Group](https://tamagui.dev/docs/intro/props#group) for that

**Comment by kzlar** [comment]
@TheEhsanSarshar thank you for your reply.

I was intrigued by your `group` suggestion so I tried it, unfortunately it's not exactly what I'm looking for.
When I add a `group:'Button'` prop to my frame , and then add `'$group-Button-press': { color: 'green',}` to my text I get the following scenario:
1. When I click the button, the text turns green.
2. When I click the text, nothing happens.

Seems like it keeps going back to the issue of `onPress` being handled on the text and not forwarded to the button itself.

I appreciate that there could be a variety of bugs, I don't expect Tamagui to be bug-proof, even though you guys seem to have it 99% of the way there :)
Just hoping that when a bug is pointed out, a solution could be found where cross-platform behavior is maintained 🤞

**Comment by TheEhsanSarshar** [comment]
add `pointerEvents="none"` to the Text and try to remove any `pressStyle` or `onPress` from the Text

**Comment by kzlar** [comment]
Hmm, very cool, this seems much better, thanks!
It does create a different issue though, which may be more related to groups:
If I have multiple buttons (let's say in a YStack), by clicking any of the buttons, the texts on **all** of the buttons turns green. 
I thought group props are supposed to be contained to a single component and not be app wide, is that not the case?

**Comment by TheEhsanSarshar** [comment]
that seems a bug, ok I'll check that thanks
