### ISSUE TITLE
[FeatureRequest] Icon only button adjust circle styles to border and paddings

### ISSUE THREAD

**Issue by dohomi** [tamagui/tamagui#193]
**Is your feature request related to a problem? Please describe.**
A button without content but only icon shows padding to the left and right

**Describe the solution you'd like**
It would be great if the <Button/> component would be a round circle if no text is set.

**Comment by natew** [comment]
`<Button circular>` should do the trick. For an icon `<Button circular icon={Component} />`

**Comment by dohomi** [comment]
that was a simple solution..! I still struggle with the use of custom SVG where the size is not applied correctly. But this is another issue will close this for now
