### ISSUE TITLE
Docs: "Extras" page not found

### ISSUE THREAD

**Issue by msidqi** [tamagui/tamagui#1932]
### Current Behavior

[Extras](https://tamagui.dev/docs/docs/extras) page which is mentioned in the [tokens](https://tamagui.dev/docs/core/tokens) docs return 404
https://github.com/tamagui/tamagui/blob/master/apps/site/data/docs/core/tokens.mdx#L50

<img width="1270" alt="Screenshot 2023-12-01 at 10 18 07" src="https://github.com/tamagui/tamagui/assets/42954251/d857d4c0-b8f5-4c4d-ab88-7d9f4082e2e0">

### Tamagui Version

```markdown
1.79.3
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
Visit: https://tamagui.dev/docs/docs/extras
you will get 404 response
```

**Comment by natew** [comment]
Ty, fixed
