### ISSUE TITLE
Sheet trigger error onOpenChange if you use native prop on iOS

### ISSUE THREAD

**Issue by megacherry** [tamagui/tamagui#1939]
### Current Behavior

I implemented the sheet and want to close it via onOpenChange but this error is thrown:

ModalView, setVisibility failed:
[Error: message: Guard check failed, modal already dismissed - debugMessage: N/A- fileID: react_native_ios_modal/RNIModalView.swift- functionName: dismissModal(completion:)- lineNumber: 886]

If i use it without native it works fine.

### Expected Behavior

Sheet should be closed properly.

### Tamagui Version

```markdown
1.79.4
```

### Platform (Web, iOS, Android)

```markdown
iOS
```

### Reproduction

```markdown
not possible right now, because i get errors with the new starter-free project.

Just implement the native prop and you will see it. :)
```

### System Info

```markdown
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1
    Memory: 116.02 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.19.0 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 4.0.0 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - /opt/homebrew/opt/node@18/bin/npm
    Watchman: 2023.11.27.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 119.0.6045.199
    Safari: 17.1
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.23.2
    @manypkg/cli: ^0.19.2 => 0.19.2
    @nderscore/tamagui-typescript-plugin: ^0.6.0 => 0.6.0
    @tamagui/cli: ^1.79.4 => 1.79.4
    check-dependency-version-consistency: ^3.3.0 => 3.3.0
    dotenv: ^16.3.1 => 16.3.1
    dotenv-cli: ^6.0.0 => 6.0.0
    eslint: ^8.46.0 => 8.52.0
    node-gyp: ^9.3.1 => 9.4.0
    prettier: ^2.8.8 => 2.8.8
    turbo: ^1.10.16 => 1.10.16
    typescript: ^5.1.6 => 5.2.2
```

**Comment by TheEhsanSarshar** [comment]
Do you mean to close it via `open` prop?

**Comment by TheEhsanSarshar** [comment]
closing via open prop ( which internally calls `ref.setVisibility() ) seems not to be working in the native implementation of `react-native-ios-modal`
I'll try to find a workaround or fix it on their side

**Comment by megacherry** [comment]
I was just about to reply, but you were quicker. good luck :)

**Comment by xwiz** [comment]
I'll highly advise dropping support for tamagui sheet, it's very buggy and distracts from the other features provided by tamagui.

**Comment by megacherry** [comment]
@xwiz: What do you mean by your comment?

**Comment by xwiz** [comment]
Do a search for sheet on Tamagui github issues page

**Comment by TheEhsanSarshar** [comment]
sorry for the bad experiences that you had 
most of these issues are related to `react-native-ios-modal` which we use internally to render native sheet on iOS. although the cross-platform version of the sheet is performant and working perfectly so you don't have to use native sheet.

Tamagui sheet supports more features like adaptive sheet height, which is not available out of the box on other famous react native sheet libraries.

I've opened an issue on their GitHub repo and as soon as they address that issue we will patch that in Tamagui and will let you know 🙂

**Comment by LamDoHoang** [comment]
> I'll highly advise dropping support for tamagui sheet, it's very buggy and distracts from the other features provided by tamagui.

kinda true. Its kinda encounter much bugs and it bring bad performance on my project somehow even I only use basic example on tamagui doc. It render with low fps

**Comment by natew** [comment]
Should be fixed, we upgraded and moved to the new version. Also better performance overall especially on web.
