### ISSUE TITLE
Github Security Lab Vulnerability Report

### ISSUE THREAD

**Issue by Kwstubbs** [tamagui/tamagui#1944]
### Current Behavior

Github Security Lab has found potential vulnerabilities in tamagui. Please let us know the best point of contact to disclose these issues privately. If you do not have a point of contact, we recommend [Private Vulnerability Reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository). We also recommend creating a security policy under https://github.com/tamagui/tamagui/security/policy, to direct future security reports.

### Tamagui Version

```markdown
https://github.com/tamagui/tamagui/releases/tag/v1.79.6
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
Private
```

**Comment by natew** [comment]
You can contact me my email is in my profile.

**Comment by natew** [comment]
We've addressed all issues!
