### ISSUE TITLE
Multiple issues with groups 

### ISSUE THREAD

**Issue by CorentinAndre** [tamagui/tamagui#1946]
### Current Behavior

When using groups, I stumbled upon a few issues:
- when no pressStyle is given to a group parent, its children do not react upon press or hover events. If you look at the reproduction, the first group is working because I gave a pressStyle to the Stack parent. the not working example does not have a press style
- also when giving a $group-X-press & $group-X-hover, the only one to be displayed is the hover state. I believe the order to apply style is messed up ?

If you can give me some hints on where I should search in the code, I'd be happy to submit a PR

### Expected Behavior

- pseudo states should work no matter if the parent is styled or not. Maybe we should base this on whether the parent is pressable or not ? (maybe use the role or the focusable prop ?)
- press state should take priority over hover state

### Tamagui Version

```markdown
latest
```

### Platform (Web, iOS, Android)

```markdown
Every platform
```

### Reproduction

```markdown
https://github.com/CorentinAndre/tamagui-group-issue
```

### System Info

```markdown
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 540.25 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 3.6.3 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    Watchman: 2023.10.30.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 119.0.6045.199
    Safari: 17.1
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.39.0 
    node-gyp: ^9.3.1 => 9.3.1 
    prettier: ^2.7.1 => 2.8.8 
    turbo: ^1.10.3 => 1.10.3 
    typescript: ^4.9.4 => 4.9.5
```

**Comment by CorentinAndre** [comment]
I believe it's related to https://github.com/tamagui/tamagui/issues/1945 ?

**Comment by TheEhsanSarshar** [comment]
using `-` in group names will break things. 
changing `not-working` to `notworking` will fix the issue
as for the second issue I wasn't able to reproduce it. press style seems working fine ( when the button is pressed it's red and after release, it's back to the initial value )
is it on native?

**Comment by CorentinAndre** [comment]
You're right for the first one, but the second one is not what you should have.
The effects are:
- red border on hover
- blue text on press
The only one triggered is the red border, the text does not go blue on press
