### ISSUE TITLE
Usage of the word `ellipse` is incorrect here

### ISSUE THREAD

**Issue by EliRobinson** [tamagui/tamagui#1948]
https://github.com/tamagui/tamagui/blob/767047565fc5f12638e6eac7e63544aae5c2fcb9/packages/text/src/types.ts#L11

This is probably one of the most pedantic issues I've ever filed, however it's actually quite important.

An Ellipse is a ovular object, an ellipsis is a trail off of speech. Why that's important, if someone is adding the ability to do an ellipsis to a Text node, and they don't type `ellipse` it doesn't work and throws errors.

I'm totally down to make these changes, do you recommend we do this as a "stepped change" e.g. deprecate `ellipse` and add `ellipsis` then slowly phase it out?

**Comment by TheEhsanSarshar** [comment]
@EliRobinson awesome nice catch!
yeah stepped is better

**Comment by natew** [comment]
Good point, we can do the deprecate now and then when we cut v2 in the next month or two we can remove it.

**Comment by natew** [comment]
first step here cf5c2847b54d1cc1dbe53cebbe8de4a538524fc5

**Comment by natew** [comment]
Closing since we have it mostly resolved.
