### ISSUE TITLE
[FeatureRequest] Port NextJS useTheme logic to @tamagui/core

### ISSUE THREAD

**Issue by dohomi** [tamagui/tamagui#195]
**Is your feature request related to a problem? Please describe.**
It would be great if the API of @tamagui/next-theme would be ported to tamagui or @tamagui/core

**Describe the solution you'd like**
Currently the API of `useTheme` of @tamagui/next-theme and tamagui shares the same name but has different purpose which is confusing at a start. Especially for universal use I missed the `toggleTheme` function for Expo/RN. It would be great if the API would move to tamagui either with a renamed theme, but that you can write one theme switch for all platforms 

```ts
import { useTheme } from '@tamagui/next-theme' // => it would be great if this is handled outside of NextJS and ported to tamagui

export default () => {
  const { theme, toggleTheme } = useTheme()
  return <Button>Change theme (currently: {theme})</Button>
}
```

**Comment by natew** [comment]
The nextjs stuff is really specific to next, so it needs to live separately. I think `next-theme` should rename the hook though to not collide. Maybe `useNextTheme`. Happy to accept PR there + some docs on it would be nice in the next guide mdx.
