### ISSUE TITLE
Popover focuses last element on mount

### ISSUE THREAD

**Issue by TimPetricola** [tamagui/tamagui#1957]
### Current Behavior

When mounting a `Popover`, the last element gets the focus

### Expected Behavior

The first element should get the focus instead

### Tamagui Version

```markdown
1.79.9
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

Can be reproduced in the [Popover documentation directly](https://tamagui.dev/docs/components/popover)

**Comment by natew** [comment]
Thanks for the report, fix is going out with a9bafc946a3d8c54c123d6b8e2d13e0a25f82c3e
