### ISSUE TITLE
Create Tamagui Next-Expo-Solito doesn't work

### ISSUE THREAD

**Issue by antonio-silencio** [tamagui/tamagui#1963]
### Current Behavior

Using npm create tamagui and choosing Next Expo Solito template throws an error

[tamagui] Failed to copy example into ...

 [Error: ENOENT: no such file or directory, lstat '.../tamagui.git/starters/next-expo-solito']

In fact there is no folder on the starters in the github repo called next-expo-solito

### Tamagui Version

```markdown
npm create tamagui - 1.79.11
```

### Platform (Web, iOS, Android)

```markdown
cli
```

### Reproduction

```markdown
npm create tamagui
```

**Comment by natew** [comment]
There's no longer a next-expo-solito its been renamed to starter-free, make sure you run `npm create tamagui@latest`
