### ISSUE TITLE
Error fontFamily "Inter" is not a system font

### ISSUE THREAD

**Issue by riccardoratta** [tamagui/tamagui#1966]
### Current Behavior

Following the initial configuration for Tamagui for react native with expo (https://tamagui.dev/docs/intro/installation) I always end up with the error:

```
fontFamily "Inter" is not a system font and has not been loaded through Font.loadAsync.
```

I've already tried all the suggested fixes, but the error persist:

- https://github.com/tamagui/tamagui/issues/1645
- https://github.com/tamagui/tamagui/issues/1546
- https://github.com/tamagui/tamagui/issues/1448

### Expected Behavior

App run without any error.

### Tamagui Version

```markdown
1.79.12
```

### Platform (Web, iOS, Android)

```markdown
iOS and Android
```

### Reproduction

```markdown
https://github.com/riccardoratta/example-app 
```

I've created a repository since my flow doesn't include using the starter template.

### System Info

```markdown
System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.82 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.6.5 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.7.1 - ~/Library/pnpm/pnpm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 17.2
  npmPackages:
    @babel/core: ^7.20.0 => 7.23.6 
    @tamagui/config: ^1.79.12 => 1.79.12 
    @types/react: ~18.2.14 => 18.2.45 
    expo: ^49.0.21 => 49.0.21 
    expo-status-bar: ~1.6.0 => 1.6.0 
    react: 18.2.0 => 18.2.0 
    react-native: 0.72.6 => 0.72.6 
    tamagui: ^1.79.12 => 1.79.12 
    typescript: ^5.1.3 => 5.3.3
```

**Comment by psycho-baller** [comment]
I resolved this issue by following [this](https://github.com/tamagui/tamagui/issues/1448#issuecomment-1836624195). I instead named the function and exported it and called that function in the root/layout/provider component and that resolved my issue

```ts
import { useFonts } from "expo-font";

export function loadFonts() {
  const [loaded] = useFonts({
    Inter: require('@tamagui/font-inter/otf/Inter-Medium.otf'),
    InterBold: require('@tamagui/font-inter/otf/Inter-Bold.otf'),
  });

  return loaded;
}
```

**Comment by natew** [comment]
@psycho-baller thanks for the heads up, we really need to improve docs overall. The `@tamagui/config` does use Inter, we should make that configurable and document how to change it better too.

If you do have time to send a PR just to add a note to the expo section that'd be helpful.

**Comment by riccardoratta** [comment]
> I resolved this issue by following [this](https://github.com/tamagui/tamagui/issues/1448#issuecomment-1836624195). I instead named the function and exported it and called that function in the root/layout/provider component and that resolved my issue
> 
> ```ts
> import { useFonts } from "expo-font";
> 
> export function loadFonts() {
>   const [loaded] = useFonts({
>     Inter: require('@tamagui/font-inter/otf/Inter-Medium.otf'),
>     InterBold: require('@tamagui/font-inter/otf/Inter-Bold.otf'),
>   });
> 
>   return loaded;
> }
> ```

Sorry, just to be clear, this code is in the `tamagui.config.ts` file?

**Comment by psycho-baller** [comment]
> Sorry, just to be clear, this code is in the `tamagui.config.ts` file?

I have it in my `ui` package([code here](https://github.com/psycho-baller/convo-topics/blob/main/packages/ui/src/loadFonts.ts)). But you can also follow what the docs say, just discovered that it shows how you should do it [in the docs](https://tamagui.dev/docs/guides/expo#setup-tamagui).

**Comment by psycho-baller** [comment]
> @psycho-baller thanks for the heads up, we really need to improve docs overall. The `@tamagui/config` does use Inter, we should make that configurable and document how to change it better too.
> 
> If you do have time to send a PR just to add a note to the expo section that'd be helpful.

Hey Nate, I'm not too sure what you'd like me to change

**Comment by riccardoratta** [comment]
Thanks, I've found the guide suggested by @psycho-baller in the official Tamagui doc. Can be useful to link this guide in the [Native section in the Installation doc](https://tamagui.dev/docs/intro/installation#native), since without loading the font the app doesn't run.

**Comment by lgoudriaan** [comment]
I had the same issue, but I had dependencies which are incompatible with the installed expo version. Fixed it by running the command: npx expo install --fix

**Comment by davidchalifoux** [comment]
> I had the same issue, but I had dependencies which are incompatible with the installed expo version. Fixed it by running the command: npx expo install --fix

This worked for me, thanks!

**Comment by grimz11** [comment]
> I had the same issue, but I had dependencies which are incompatible with the installed expo version. Fixed it by running the command: npx expo install --fix

Worked for me as well.
