### ISSUE TITLE
Select dropdown viewport will slide across the screen when scrolled upon

### ISSUE THREAD

**Issue by hackily** [tamagui/tamagui#1969]
### Current Behavior

The select dropdown viewport will move across the screen when scrolled upon.

https://github.com/tamagui/tamagui/assets/8202335/0bb042c9-9c8d-4ac1-9803-55d30eb901e4

### Expected Behavior

The dropdown viewport should stay static, and only the content inside should be scrolled.

### Tamagui Version

```markdown
Latest, 1.79.12
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://tamagui.dev/docs/components/select/1.40.0
```

**Comment by hackily** [comment]
As an aside, is it possible to keep the dropdown as a dropdown? Maybe add a max height to the dropdown popover.
With the behavior today, once we choose any option besides the top option, we start to see the dropdown begin to drop _up_

**Comment by floyddeadshot** [comment]
Agree with @hackily.

Also for me on the tamagui docs site, the select viewport is still showing the same behaviour?
