### ISSUE TITLE
custom token don't transform to css variable in prod mode

### ISSUE THREAD

**Issue by youniaogu** [tamagui/tamagui#1971]
### Current Behavior

custom token don't transform to css variable in prod mode

<img width="681" alt="截屏2023-12-19 14 58 06" src="https://github.com/tamagui/tamagui/assets/13073995/197adc23-40f9-4b18-a0d9-3cc66d0cdb26">

### Expected Behavior

custom token can transform to css variable

<img width="651" alt="image" src="https://github.com/tamagui/tamagui/assets/13073995/535ca602-5c8d-4191-883f-642cfaf013d9">

### Tamagui Version

```markdown
1.79.12
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
https://github.com/youniaogu/tamagui-reproduction


yarn install
yarn web:prod
yarn web:prod:serve

open http://localhost:8151/user/nate
select First name element and check color
```
```


### System Info

```markdown
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M2
    Memory: 54.50 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 3.6.3 - ~/.nvm/versions/node/v16.20.2/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 17.1
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.39.0 
    node-gyp: ^9.3.1 => 9.3.1 
    prettier: ^2.7.1 => 2.8.8 
    turbo: ^1.10.3 => 1.10.3 
    typescript: ^4.9.4 => 4.9.5
```

**Comment by natew** [comment]
@alitnk another good one, maybe due to something with `$x.y`, check without compiler first then with, even if you narrow it down just using `// debug-verbose` and see where its breaking in compiler i can fix.

**Comment by youniaogu** [comment]
it don't fix, here is my reproduction:
```
git clone https://github.com/youniaogu/tamagui-reproduction
yarn install
yarn upgrade:tamagui
yarn web:prod
yarn web:prod:serve
```
