### ISSUE TITLE
Default background colors behave differently in production vs development build

### ISSUE THREAD

**Issue by johnsimeroth** [tamagui/tamagui#1973]
### Current Behavior

In a dev build, background colors default to dark, but in a prod build they default to system theme colors. Both are referencing css "prefers-color-scheme-light" but color variables differ. See images.
<img width="1792" alt="Screenshot 2023-12-19 at 1 50 53 PM" src="https://github.com/tamagui/tamagui/assets/51033195/40ed550d-4d19-42e8-af0e-869c74c04499">
<img width="1792" alt="Screenshot 2023-12-19 at 1 50 47 PM" src="https://github.com/tamagui/tamagui/assets/51033195/f3f11a2a-30a1-4886-a44c-ce0390511a78">

### Expected Behavior

I expect dev and prod builds to look the same

### Tamagui Version

```markdown
1.79.12
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
Reproducible with no changes to the free starter. steps to reproduce:
1. set system settings to light mode
2. `npm create tamagui@latest`
3. `yarn web` and open in browser (should look dark)
4. open a new terminal
5. `yarn web:prod`
6. `yarn web:prod:serve` and open in another window (should look light)
```

### System Info

```markdown
System:
    OS: macOS 14.1.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 120.12 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 21.1.0 - /usr/local/bin/node
    Yarn: 3.6.3 - ~/.nvm/versions/node/v21.1.0/bin/yarn
    npm: 10.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 17.1.2
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.39.0 
    node-gyp: ^9.3.1 => 9.3.1 
    prettier: ^2.7.1 => 2.8.8 
    turbo: ^1.10.3 => 1.10.3 
    typescript: ^4.9.4 => 4.9.5
```

**Comment by natew** [comment]
@alitnk one more after the other two.

**Comment by TheEhsanSarshar** [comment]
is this issue still happening @johnsimeroth ?

**Comment by TheEhsanSarshar** [comment]
as no one else complained about this issue, so I think it's fixed!
if you still face this issue let me know!
