### ISSUE TITLE
[Next.js] getNewCSS example in doc is wrong and getNewCSS can't respond properly in app router

### ISSUE THREAD

**Issue by tkow** [tamagui/tamagui#1976]
### Current Behavior

The explanation in https://tamagui.dev/docs/guides/next-js#server-components is wrong, because the response is css string, thus it should be:

```jsx
          <style
            dangerouslySetInnerHTML={{
              __html: Tamagui.getNewCSS({
                // if you are using "outputCSS" option, you should use this "exclude"
                // if not, then you can leave the option out
                exclude: process.env.NODE_ENV === 'production' ? 'design-system' : null,
              }),
            }}
          />
```

In addition, next server may cache read CSS position globally in lastCSSInsertedRulesIndex variable, thus requests more than once from the server starting  can't resolve runtimeStyle and FOUC happens. See reproduction link.

https://github.com/tamagui/tamagui/blob/5a5de3bf3355ca6f5ae99d911afa81e3a45b92f6/packages/web/src/createTamagui.ts#L222-L226

### Expected Behavior

getNewCSS avoids FOUC.

### Tamagui Version

```markdown
1.79.12
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
https://codesandbox.io/p/devbox/next-tamagui-yg2sz9?file=%2Fsrc%2Fapp%2FNextTamaguiProvider.tsx%3A19%2C58-19%2C67
```

**Comment by natew** [comment]
This should be fixed now
