### ISSUE TITLE
FlatList Error Cannot convert object to primitive value

### ISSUE THREAD

**Issue by Jmg-21** [tamagui/tamagui#198]
**Describe the bug**
Im having issue using FlatList on web. Is this RN component is already supported ? or do we have proper docs how to fix or way to use it.
![image](https://user-images.githubusercontent.com/24725067/189534510-c854c8c9-dd1c-48a5-bbf8-2f4946f408de.png)

**To Reproduce**
Create simple list using FlatList then run it on web. 

**System Info (please complete the following information):** 
Tamagui version:  1.0.1-beta.165
System:
    OS: Linux 5.4 Peppermint 10 (Ten)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 580.52 MB / 7.22 GB
    Container: Yes
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 14.20.0 - /usr/bin/node
    Yarn: 3.2.0 - /usr/bin/yarn
    npm: 8.18.0 - /usr/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 102.0

**Comment by natew** [comment]
`FlatList` is no included in `tamagui` so this seem unrelated, can you show me example code?
