### ISSUE TITLE
Group pseudo state prop crashes

### ISSUE THREAD

**Issue by CorentinAndre** [tamagui/tamagui#1992]
### Current Behavior

If I nest a component within a group component, and apply some pseudo state prop like `$group-myCustomGroup-press` or `$group-myCustomGroup-hover`, the app crashes with:

`Cannot read property add of undefined`.
It comes from this line: https://github.com/tamagui/tamagui/blob/052f8699d57c2e63ab24d878acc6a0377cb21be2/packages/web/src/createComponent.tsx#L415 and was introduced by https://github.com/tamagui/tamagui/pull/1960.

It works on web though

### Expected Behavior

The starter does not crash

### Tamagui Version

```markdown
1.79.17
```

### Platform (Web, iOS, Android)

```markdown
iOS & Android only
```

### Reproduction

```markdown
Check https://github.com/CorentinAndre/tamagui-group-issue under app/features/home/screen.tsx
```

**Comment by natew** [comment]
This is fixed in latest versions, thanks.
