### ISSUE TITLE
onPress is not triggered only works if the pressStyle is defined

### ISSUE THREAD

**Issue by ezavalatyro** [tamagui/tamagui#1995]
### Current Behavior

The `onPress` was working in `1.59.3`. However, it stopped working after upgrading to `1.79.17`. I noticed that if the `pressStyle` is defined, it works.

https://github.com/tamagui/tamagui/assets/127100578/98a2fb79-c45e-4ba0-9ab6-526a373809c4

### Tamagui Version

```markdown
1.79.17
```

### Platform (Web, iOS, Android)

```markdown
ios/android
```

### Reproduction

```markdown
<YStack
      pressStyle={{ opacity: 1 }}
      onPress={() => {
        console.log('onPress');
      }}
    >
      <Paragraph color="$colorSecondary">
        the onPress event does not work
      </Paragraph>
    </YStack>
```

**Comment by natew** [comment]
Need a better reproduction, it's working for me across a few configs so it depends on your config I think.
