### ISSUE TITLE
"No native ExponentConstants module found" error on a fresh install

### ISSUE THREAD

**Issue by jaminday** [tamagui/tamagui#1997]
### Current Behavior

Running "yarn ios" from the `./apps/expo` folder on a fresh Tamagui install, I see the following error in the console:

```
transform[stderr]: No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?
```

### Expected Behavior

The `expo-constants` package is installed by default in `./apps/expo/package.json` (currently showing version "~14.4.2"), therefore I would not expect the error to appear.

### Tamagui Version

```markdown
1.79.18
```

### Platform (Web, iOS, Android)

```markdown
iOS
```

### Reproduction

```markdown
1. npm create tamagui@latest
2. Select option 1 during install ("Free - Production ready base universal app monorepo")
3. Replace yourprojectsname in app.json as directed during install
4. cd ./apps/expo
5. yarn ios

Note: I also had to run `npx expo install burnt` from the `./apps/expo` folder before step 4 in order for the development build to run successfully.
```

### System Info

```markdown
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 195.83 MB / 16.00 GB
    Shell: 3.6.4 - /opt/homebrew/bin/fish
  Binaries:
    Node: 21.4.0 - ~/.asdf/installs/nodejs/21.4.0/bin/node
    Yarn: 3.6.3 - ~/.asdf/installs/nodejs/21.4.0/bin/yarn
    npm: 10.2.5 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 118.0.5993.117
    Firefox: 121.0
    Safari: 17.2.1
```

**Comment by salman-ar-sar** [comment]
Having the same issue. Also couldn't build for iOS as mentioned. Had to do `npx expo install burnt` which I found after Googling the error. This is not the expected behaviour right?

**Comment by salman-ar-sar** [comment]
I have opened a [PR](https://github.com/tamagui/starter-free/pull/13) to fix the build issue.

**Comment by natew** [comment]
Merged! lmk if still an issue

**Comment by salman-ar-sar** [comment]
> Merged! lmk if still an issue

@natew Thanks for merging it. But that MR was only meant to fix the build issue mentioned here. This error is still appearing in metro console. Just tried with the new version. @jaminday Please confirm. 

<img width="1413" alt="image" src="https://github.com/tamagui/tamagui/assets/16640612/b63d31aa-f9cf-4bec-b869-c2c1d0716c1c">

**Comment by jaminday** [comment]
Yes the build step works for me in the update but I still get the ExponentConstants error message in the console.
