### ISSUE TITLE
Website is blocked is india -  https://tamagui.dev/

### ISSUE THREAD

**Issue by naveenkash** [tamagui/tamagui#20]
![Screenshot 2021-11-26 at 5 30 20 PM](https://user-images.githubusercontent.com/31365913/143577983-dce6074f-962b-41f7-a4a1-30913d94034f.png)

**Comment by naveenkash** [comment]
what could be the reason that they blocked it?

**Comment by natew** [comment]
Oh man, thats too bad! No idea...

**Comment by r1jsheth** [comment]
I am able to access it from India.

**Comment by Just-Moh-it** [comment]
The website is blocked for me as well (when accessed through the most famous consumer ISP in India). I am able to access it through my digital ocean server (India-located) vpn though...

The name sounds very chinese (taama-goeey), maybe that's the reason 🤔; (India China relations are not very good and many chinese apps and products have been banned in India)

**Comment by Just-Moh-it** [comment]
Soon after I wrote the above comment and reloaded, it started working. I don't know why I get the restriction message on the website often..
