### ISSUE TITLE
Placeholder on Input not supporting dark mode on native

### ISSUE THREAD

**Issue by dohomi** [tamagui/tamagui#200]
**Describe the bug**
The placeholder on `<Input placeholder="Search..." />` is not inverting the color on dark mode on `native`. Web works without an issue but iOS or Android doesn't inverts the color

**To Reproduce**
Add `<Input placeholder="Search..." />` to a native screen. The color is not been inverted.

**Comment by peterjskaltsis** [comment]
@natew the issue number you linked here is incorrect, looks like its referencing this issue. Did you mean #223? 

Wanted to add that `placeholderTextColor` does not work at all with `$color.token` theme color tokens.
