### ISSUE TITLE
Popover does not trap focus anymore

### ISSUE THREAD

**Issue by TimPetricola** [tamagui/tamagui#2004]
### Current Behavior

When opening a `Popover`, focus isn't trapped anymore. It used to work in 1.79.12 so the regresison is quite recent.

### Expected Behavior

Focus should be trapped

### Tamagui Version

```markdown
1.79.19
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

See [Popover's documentation](https://tamagui.dev/docs/components/popover/) examples.

**Comment by ylkhayat** [comment]
I can confirm this, and was wondering which release caused the issue. 
Thought it was this one https://github.com/tamagui/tamagui/releases/tag/v1.79.18 as it was mentioned here 
```
popover: reset Presence state for children inside Popover (https://github.com/tamagui/tamagui/pull/1982) https://github.com/tamagui/tamagui/pull/1982 ([Ehsan sarshar](https://github.com/tamagui/tamagui/commit/2a1d171c9c1d21d42b2c5db419c8eb8c60619c9b))
```
Thus, I downgraded to `1.79.17` but the issue still persists. I am guessing these last few releases were short frequent and maybe one of them tampered with the `Popover`'s focus logic.

Rolling back to `1.79.12` for the time being.
