### ISSUE TITLE
Feather icon's onClick

### ISSUE THREAD

**Issue by apperside** [tamagui/tamagui#201]
**Describe the bug**
Typescript gives error for the `onClick` prop of components imported from `@tamagui/feather-icons`, even if it works if you add it anyway.

![Screenshot 2022-09-13 at 13 11 03](https://user-images.githubusercontent.com/5955338/189886633-1d2ff724-5c56-45ad-8b22-def29800eeeb.png)

**To Reproduce**
Add onClick prop on icons components imported from `@tamagui/feather-icons`

**System Info (please complete the following information):** 

  System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 128.06 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Firefox: 104.0.2
    Safari: 16.0

**Comment by dohomi** [comment]
I'd suggest wrap the icon with a button and add a onPress to the button..

**Comment by apperside** [comment]
Thanks for your suggestion @dohomi ,
since I think this is a violation to DRY principle, while I wait for my pr #204 to be merged,  I used [patch-package](https://www.npmjs.com/package/patch-package) library to create a patch to the typings file
