### ISSUE TITLE
Documentation site css is broken

### ISSUE THREAD

**Issue by hackily** [tamagui/tamagui#2011]
### Current Behavior

No css
https://tamagui.dev/docs/intro/installation
![image](https://github.com/tamagui/tamagui/assets/8202335/fa001e5b-7f83-4cef-b259-dfc83863da9b)

It's probably this commit
https://github.com/tamagui/tamagui/commit/423a5f2d1261df717a2558564a369cf1b4ca7f74

### Expected Behavior

Has css

### Tamagui Version

```markdown
1.79.19
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://tamagui.dev/docs/intro/installation
```

**Comment by 403access** [comment]
It's also https://tamagui.dev/

**Comment by natew** [comment]
Fixed, thanks for heads up
