### ISSUE TITLE
Outdated docs regarding sandbox

### ISSUE THREAD

**Issue by MusabIlhan** [tamagui/tamagui#2022]
Hey I was just reading [this](https://tamagui.dev/docs/intro/compiler-install#webpack). The first link seems to be broken because sandbox doesn't seem to exist anymore. Did it get replaced by kitchen sink or what happened? Let me know If I can help!

**Comment by natew** [comment]
Ty, fixed here for now 09c6f6d0cee53ca8456da54176639db1d3b839bc
