### ISSUE TITLE
fontWeight on Button being ignored

### ISSUE THREAD

**Issue by iamtommcc** [tamagui/tamagui#2024]
### Current Behavior

Currently, passing `fontWeight` on a Button seems to not work despite what the docs indicate. This occurs in all cases, either when passing fontWeight directly as a prop or via `styled()`

Other text props, such as `color`, seem to work fine.

<img width="398" alt="image" src="https://github.com/tamagui/tamagui/assets/7507516/60cf73d5-db67-4f4f-b8ac-ab1296776a02">

### Expected Behavior

Passing fontWeight to a Button - either via direct prop or `styled()`, should adjust the font weight.

### Tamagui Version

```markdown
1.79.6
```

### Platform (Web, iOS, Android)

```markdown
Tested on iOS, unsure about other platforms.
```

### Reproduction

```markdown
1. In a fresh `starter-free` repo, add fontWeight of 700 to the "Link to user button"
2. The text should be bolded, however it isn't.

Fork with a reproduction commit: https://github.com/iamtommcc/tamagui-fontweight-bug/commit/4d1e7a2530670147138ac18b3f86be49951165ec
```

### System Info

```markdown
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 78.20 MB / 16.00 GB
    Shell: 3.3.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 4.0.2 - /opt/homebrew/bin/yarn
    npm: 7.24.2 - /opt/homebrew/bin/npm
    Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 120.0.6099.129
    Firefox: 118.0.1
    Safari: 17.0
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0
    @manypkg/cli: ^0.19.1 => 0.19.2
    check-dependency-version-consistency: ^3.0.3 => 3.0.3
    eslint: ^8.21.0 => 8.39.0
    node-gyp: ^9.3.1 => 9.3.1
    prettier: ^2.7.1 => 2.8.8
    turbo: ^1.10.3 => 1.10.3
    typescript: ^5.1.3 => 5.3.3
```

**Comment by natew** [comment]
We've been refactoring button quite a bit, fix is here (aedf04ee1f05e6bc66b251f56de483356f1f9316), next release will have it.
