### ISSUE TITLE
Is support for mobile react-native platforms present?

### ISSUE THREAD

**Issue by luvvvdev** [tamagui/tamagui#203]

**Comment by hirbod** [comment]
Yes

**Comment by luvvvdev** [comment]
@hirbod 
> Yes
After installing tamagui, I get an error when using Input:
![Error](https://user-images.githubusercontent.com/39151330/189919381-f6bc8970-4d21-4b05-b079-4dc4e5dd6605.png)

**Comment by natew** [comment]
Check for duplicate `react`, `react-dom`. Make sure React 18. If you can do the system info log or repro repo that'd help a lot.

**Comment by luvvvdev** [comment]
I solved this problem by removing the react package from package.json
