### ISSUE TITLE
Typescript errors on template in expo "Cannot use JSX unless the '--jsx' flag is provided"

### ISSUE THREAD

**Issue by jordisantamaria** [tamagui/tamagui#2032]
### Current Behavior

I installed the app with the cli, using template "Free - Production ready base universal app monorepo"

Then when I move to expo/app/index.tsx, I get a lot of typescript errors, attached a screenshot.
The 2 errors is showing is
1.  The import of home screen `Module 'app/features/home/screen' was resolved to...`
2.  Cannot use JSX unless the '--jsx' flag is provided

![image](https://github.com/tamagui/tamagui/assets/6263700/9a0a2523-1eaf-4ceb-a350-af4eda1138db)

### Expected Behavior

No typescript errors on the project template

### Tamagui Version

```markdown
Last version
```

### Platform (Web, iOS, Android)

```markdown
Expo
```

### Reproduction

```markdown
1. Install the app with the cli, using template "Free - Production ready base universal app monorepo"
2. Move to expo/app/index.tsx, It shows a lot of typescript errors
```

### System Info

```markdown
System:
    OS: Linux 5.15 Linux Mint 21.1 (Vera)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 20.92 GB / 31.26 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 4.0.2 - /usr/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
  Browsers:
    Brave Browser: 113.1.51.114
    Chrome: 115.0.5790.170
    Firefox: 108.0.1
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0
    @manypkg/cli: ^0.19.1 => 0.19.2
    check-dependency-version-consistency: ^3.0.3 => 3.0.3
    eslint: ^8.21.0 => 8.39.0
    node-gyp: ^9.3.1 => 9.3.1
    prettier: ^2.7.1 => 2.8.8
    turbo: ^1.10.3 => 1.10.3
    typescript: ^5.1.3 => 5.3.3
```

**Comment by Cazforshort** [comment]
I think this is an issue with your IDE having a different setting. In VSCode the button is at the bottom to switch to a specific typescript version. Just pick workspace.

**Comment by jordisantamaria** [comment]
Well, it should work on all editors by default right? 

Btw vscode have the same problem
![image](https://github.com/tamagui/tamagui/assets/6263700/41866f63-45d2-4e3e-9d92-15045c1e80ee)

**Comment by Cazforshort** [comment]
It works on all editors, but the editor needs to know the package version to use (The editors version or the workspace version). Including VSCode. I was just saying how to fix it on VSCode.

**Comment by natew** [comment]
Latest versions fix everything
