### ISSUE TITLE
Buttons are throwing this error

### ISSUE THREAD

**Issue by naresh9949** [tamagui/tamagui#2042]
### Current Behavior

Warning: Cannot update a component (`Button`) while rendering a different component (`Button`). To locate the bad setState() call inside `Button`, follow the stack trace as described in https://react.dev/link/setstate-in-render
    in Button
    in Unknown (created by Themed(Anonymous))
    in Theme (created by Themed(Anonymous))
    in Themed(Anonymous) (created by TaskCategoryScroll)
    in AndroidHorizontalScrollContentView (created by ScrollView)
    in AndroidHorizontalScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by TaskCategoryScroll)
    in TaskCategoryScroll (created by Home)
    in RNCSafeAreaView (created by Container)
    in Container (created by Home)
    in Home (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by HomeStack)
    in HomeStack (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (created by UserStack)
    in UserStack (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in Theme (created by App)
    in App (created by Main)
    in PortalProviderComponent (created by _TamaguiProvider)
    in Theme (created by _ThemeProvider)
    in _ThemeProvider (created by TamaguiProvider)
    in Provider (created by TamaguiProvider)
    in TamaguiProvider (created by _TamaguiProvider)
    in _TamaguiProvider (created by Main)
    in Provider (created by Main)
    in Main
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    
    react-native version : 0.7

### Tamagui Version

```markdown
1.82.3
```

### Platform (Web, iOS, Android)

```markdown
Android
```

### Reproduction

```markdown
just run the project
```

### System Info

```markdown
Warning: Cannot update a component (`Button`) while rendering a different component (`Button`). To locate the bad setState() call inside `Button`, follow the stack trace as described in https://react.dev/link/setstate-in-render
    in Button
    in Unknown (created by Themed(Anonymous))
    in Theme (created by Themed(Anonymous))
    in Themed(Anonymous) (created by TaskCategoryScroll)
    in AndroidHorizontalScrollContentView (created by ScrollView)
    in AndroidHorizontalScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by TaskCategoryScroll)
    in TaskCategoryScroll (created by Home)
    in RNCSafeAreaView (created by Container)
    in Container (created by Home)
    in Home (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by HomeStack)
    in HomeStack (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by BottomTabView)
    in RCTView (created by View)
    in View (created by Screen)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by Screen)
    in Screen (created by BottomTabView)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (created by UserStack)
    in UserStack (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in Theme (created by App)
    in App (created by Main)
    in PortalProviderComponent (created by _TamaguiProvider)
    in Theme (created by _ThemeProvider)
    in _ThemeProvider (created by TamaguiProvider)
    in Provider (created by TamaguiProvider)
    in TamaguiProvider (created by _TamaguiProvider)
    in _TamaguiProvider (created by Main)
    in Provider (created by Main)
    in Main
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    
    react-native version : 0.7
```

**Comment by TheEhsanSarshar** [comment]
@naresh9949  plz share a repo or a code snippet

**Comment by naresh9949** [comment]
import React from 'react';
import {
  View,
  StyleSheet,
  ImageBackground,
  Dimensions,
  Text,
} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Button, XStack, H3, Paragraph, SizableText} from 'tamagui';

import FontSize from '../../constants/FontSize';
import {welcomeHeader,welcomeSubHeader} from '../../constants/appOptions';
import Spacing from '../../constants/Spacing';
import Colors from '../../constants/Colors';
import {AuthenticationStackParamList} from '../../config/stackParams';
const {height} = Dimensions.get('window');

// navigation
import {NativeStackScreenProps} from '@react-navigation/native-stack';

type WelcomeProps = NativeStackScreenProps<
  AuthenticationStackParamList,
  'Welcome'
>;

const Welcome = ({navigation}: WelcomeProps): JSX.Element => {
  return (
    <SafeAreaView style={styles.container}>
      <View>
        <ImageBackground
          style={{height: height / 2.5}}
          resizeMode="contain"
          source={require('./../../assets/images/welcome.png')}
        />
      </View>

      <H3 fontFamily={'$heading'} style={{textAlign: 'center'}}>
        {welcomeHeader}
      </H3>

      <Text style={styles.welcomeSubHeader}>{welcomeSubHeader}</Text>

      <XStack space style={{marginTop: 22}} justifyContent="center">
        <Button
          size={'$3'}
          themeInverse
          width={'70%'}
          theme={'active'}
          onPress={() => navigation.navigate('SignUp')}
          >
          Sign up
        </Button>
      </XStack>

      <XStack style={styles.loginButtons} justifyContent="center">
        <Paragraph>Already have an Account ? </Paragraph>
        <SizableText
          theme={'alt1'}
          onPress={() => navigation.navigate('Login')}>
          Sign in
        </SizableText>
      </XStack>

      <SizableText
        paddingTop={30}
        size={'$2'}
        fontFamily={'$body'}
        textAlign="center">
        By signing up, you agree to our Terms of Use and Privacy Policy.
      </SizableText>
    </SafeAreaView>
    );
};

const styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    padding: Spacing,
    height: '100%',
    backgroundColor: '#fff',
  },
  welcomeHeader: {
    paddingTop: Spacing * 2,
    paddingHorizontal: Spacing * 2,
    fontSize: FontSize.xLarge,
    textAlign: 'center',
    color: Colors.text,
  },
  welcomeSubHeader: {
    paddingHorizontal: Spacing * 2,
    paddingTop: Spacing,
    fontSize: FontSize.small,
    textAlign: 'center',
  },
  loginButtons: {
    paddingTop: Spacing * 3,
  },
});
export default Welcome;

**Comment by natew** [comment]
We have this logged here https://github.com/tamagui/tamagui/issues/1828

It doesn't affect anything just annoying, I worked on a refactor to fix it but saw performance regressions so need to rethink it a bit further.

**Comment by therealpurplemana** [comment]
I'm getting the same thrown error on ToastImpl

**Comment by Brunowilliang** [comment]
> Estou recebendo o mesmo erro gerado no ToastImpl

me too

**Comment by eoisaac** [comment]
Any updates about that issue? I'm using Tamagui `^1.91.3` and I'm facing that problem. Sometimes it's a little annoying to get that error in the console.

**Comment by ethras** [comment]
Same issue here with version 1.94.5
