### ISSUE TITLE
Vercel build fails with tamagui starter monorepo

### ISSUE THREAD

**Issue by dohomi** [tamagui/tamagui#205]
**Is your feature request related to a problem? Please describe.**
The current Tamagui starter does not build successfully on Vercel using the Github monorepo approach. 
```
Type error: Cannot find module '@my/ui' or its corresponding type declarations.
```
Locally NextJS works, also the build. It seems to be some config missing that Vercel recognises the path to "@my/ui" 
Below is the config for the Vercel build.

**Describe the solution you'd like**
Add the necessary config to NextJS for successful deploy to Vercel 
<img width="914" alt="Screenshot 2022-09-15 at 09 16 58" src="https://user-images.githubusercontent.com/489221/190290768-bf9a76c9-8ad6-4af7-8d31-a1eeb052552f.png">

**Comment by natew** [comment]
Is this from the `deploy to vercel` button? I need to fix that to use the new monorepo approach somehow.

**Comment by dohomi** [comment]
Thats using Vercel add project button with Github and monorepo approach. The internal "@my/ui" package can't get resolved.

**Comment by natew** [comment]
To be clear it definitely works, but I'm moving starters into the monorepo because otherwise it's way too much overhead to maintain them...

Not sure what's best in terms of Vercel though now.

**Comment by natew** [comment]
It does make sense to have them as a separate repo so people can fork it easily, I think I'll have it be write-only and automatically push there somehow.

Ultimately I'd like a better solution for starters where they are easier to update in general.

**Comment by dohomi** [comment]
@natew I used the https://github.com/dohomi/tamagui-kitchen-sink which is a fork of the starter to deploy to Vercel. There the exact issue occurs, when adding the Github repo as a mono repo Vercel installs all packages but does not build successful due to the  `Type error: Cannot find module '@my/ui' or its corresponding type declarations.` message. I contacted the support of Vercel what I missed (I think maybe the "*" asterix) inside of the package.json has issue to be resolved correctly but I am not sure

**Comment by SushritPasupuleti** [comment]
A few other things to get it working:

- You need to set an Env:

```env
YARN_ENABLE_IMMUTABLE_INSTALLS=false
```

- You can leave the default presets after choosing Next.js. (I did not override the install command)

- Just change your root directory to: `monorepo-folder/next`

This is what works for me.

**Comment by SushritPasupuleti** [comment]
> @SushritPasupuleti if you didn't overwrite the install command, how do you make sure that the `@my/ui` package is build? do you build locally and check in the types and dist folder of the package?

No, I do not push my dist folder. Honestly, I'm not sure what's going wrong on your end, I just set up a fresh app and followed my steps to get it deployed on vercel. I'd suggest trying a fresh repo once, confirm if it works and comparing your setup.

**Comment by dohomi** [comment]
The repo I'm working on is https://github.com/dohomi/tamagui-kitchen-sink. I will compare the setup tomorrow maybe some things changed after the last version

**Comment by dohomi** [comment]
After upgrading to yarn v3 and restructure the build command the build runs on Vercel. I think the turbo command I used linked a wrong folder structure while running on Vercel.
