### ISSUE TITLE
Typescript Error When upgrade 1.79.11 -> 1.82.9

### ISSUE THREAD

**Issue by thienvu23** [tamagui/tamagui#2051]
### Current Behavior

<img width="215" alt="image" src="https://github.com/tamagui/tamagui/assets/91444569/a60d02fb-c969-45d2-8dc1-58b40a8ba09d">

Some spacing type and color tokens is the wrong type after the upgrade version. How to fix it?
The font size is working fine.

### Expected Behavior

Type correct

### Tamagui Version

```markdown
1.82.9
```

### Platform (Web, iOS, Android)

```markdown
Expo native
```

### Reproduction

```markdown
Upgrade project to new version
```

**Comment by natew** [comment]
Can you repro on one of the starters
