### ISSUE TITLE
`asChild` not working with non-Tamagui web child anymore

### ISSUE THREAD

**Issue by TimPetricola** [tamagui/tamagui#2052]
### Current Behavior

Since [this commit](https://github.com/tamagui/tamagui/commit/ea1941adc264f4f8e0a92c1cf2b21accc6bbbf87), released in 1.80.3, the following doesn't work anymore:

```tsx
import { Link } from "react-router-dom";

<Stack asChild gap={20}>
  <Link to="/>
    <SomeIcon />
    <Text>A react-router link</Text>
  </Link>
</Stack>
```

As default web styles are not forwarded anmore, the element doesn't get a `display: flex`.

### Expected Behavior

I would expect `asChild` to forward web default to non-Tamagui child. Or at least have an option to do so.

### Tamagui Version

Any version >=1.80.3

### Platform (Web, iOS, Android)

Web

**Comment by TheEhsanSarshar** [comment]
you need to do this first

```const TLink = styled(Link)```

because Tamagui will forward props as inline props, not the style={{}} prop. so the child component needs to support inline style props
