### ISSUE TITLE
LinearGradient issues

### ISSUE THREAD

**Issue by hlynurstef** [tamagui/tamagui#206]
**Describe the bug**

I'm currently on `beta.165`

Following the LinearGradient docs: https://tamagui.dev/docs/components/linear-gradient

When I supply the `start` and `end` props I get these errors:

```
Error setting property 'start' of RCTView with tag #85: JSON value '(0, 1)' of type NSMutableArray cannot be converted to a YGValue.
Error setting property 'end' of RCTView with tag #85: JSON value '(0, 0)' of type NSMutableArray cannot be converted to a YGValue.
```

Removing those props allows the component to render. I however don't seem to get any IntelliSense or typing to the colors I have defined in the config, it seems to be only typed to `string[] | undefined`. If I supply a color token then the component does not render at all.

![image](https://user-images.githubusercontent.com/15615089/190448542-3674ca19-d579-4f31-a409-bac72fe144f6.png)

**To Reproduce**
Follow the docs in https://tamagui.dev/docs/components/linear-gradient while on `beta.165`

**System Info (please complete the following information):** 

  System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 84.28 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Safari: 15.3

**Comment by natew** [comment]
Have a fix for the types for next release, but I can't replicate the error you're seeing. I've tried a variety of `start` and `end`.

You can try `debug="verbose"` but it shouldn't be anything to do with Tamagui here, it just passes those directly to Expo. A breakpoint to ensure it looks right in LinearGradient may give us some info.
