### ISSUE TITLE
Resource leak on Sheet docs page

### ISSUE THREAD

**Issue by kdelalic** [tamagui/tamagui#2061]
### Current Behavior

Sheet page starts consuming a large amount of cpu after about 30 seconds.

<img width="714" alt="image" src="https://github.com/tamagui/tamagui/assets/17441833/f58c26cf-a485-47e0-be07-1b88396fe8a6">

### Tamagui Version

```markdown
1.84.0, but it is not a new bug.
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
1. Navigate to https://tamagui.dev/docs/components/sheet
2. Wait 30 seconds
3. Notice laptop heating up and CPU usage increase.
```

**Comment by TheEhsanSarshar** [comment]
Heap usage and other things like even listeners that can cause memory leaks seem ok and it was peak 45 MB usage, I've used the chrome dev tools Memory tab and also the `Performance monitor` tool. 
but still when you hover over tab it shows lot of memory usage, it's either chrome not releasing some garbage collected memory space, because system doesn't need it. or some other edge cases that I couldn't find.

**Comment by TheEhsanSarshar** [comment]
probably my first hypothesis is correct because I see a similar result with some other sites, like StackOverlfow and Github issues page. even some blogging platforms.

**Comment by TheEhsanSarshar** [comment]
I'll close this issue for now, if you got more info let me know to re-open

**Comment by kdelalic** [comment]
@TheEhsanSarshar it's about CPU usage, not memory usage. 100%+ cpu usage usually means there is something wrong

**Comment by kdelalic** [comment]
Although it doesn't seem tot be happening anymore

**Comment by lsthornt** [comment]
Not much helpful to add here, but I did want to chime in and say I also just encountered tamagui.dev consuming massive amounts of CPU in Chrome.

My system CPU was way over 100%, and the Chrome Task Manager showed my 3 tamagui tabs as the culprits. Regrettably, I did not capture the Mem/CPU usage of the tabs before I closed them. I generally keep my docs tabs open for quite a while, so these tabs had probably been open for at least 2 days.

All this to say, I would not want to preemptively dismiss this as a non-issue if others are also encountering it. Hopefully others can find this issue if they have more details. I'll make sure to profile next time I see it.

**Comment by dnbrwstr** [comment]
I've also encountered this + did grab a trace from Chrome devtools. It seems to happen semi-consistently when I leave a tab open for a long time in the background. This trace is from a few days ago, so may be outdated if thing have changed. 

Love tamagui btw :)
[Trace-20240115T174633.json](https://github.com/tamagui/tamagui/files/13999216/Trace-20240115T174633.json)
