### ISSUE TITLE
Render Error

### ISSUE THREAD

**Issue by AdzeB** [tamagui/tamagui#2078]
### Current Behavior

I have a bottom sheet component(using Gorhom's bottom sheet), and I display a list of communities with which a user can talk. The issue is when the bottom sheet is open, the app crashes. Before I upgraded to 1.84.1, it used to work. I was on 1.78.0, and now, even if I go back to 1.78.0, it no longer works.

Some of the errors messages I get(ambiguous but that's what I get)
```

This error is located at:
    in XStack (created by ListHeaderComponent)
    in ListHeaderComponent (created by VirtualizedList)
    in RCTView (created by View)
    in View (created by VirtualizedList)
    in VirtualizedListCellContextProvider (created by VirtualizedList)
    in RCTScrollContentView (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by VirtualizedList)
    in VirtualizedListContextProvider (created by VirtualizedList)
    in VirtualizedList (created by FlatList)
    in FlatList (created by AnimatedComponent(FlatList))
    in AnimatedComponent(FlatList)
    in Unknown (created by NativeViewGestureHandler)
    in NativeViewGestureHandler (created by BottomSheetFlatList)
    in RCTView (created by View)
    in View (created by AnimatedComponent(View))
    in AnimatedComponent(View)
    in Unknown (created by PanGestureHandler)
    in PanGestureHandler (created by BottomSheetDraggableViewComponent)
    in BottomSheetDraggableViewComponent (created by BottomSheetFlatList)
    in BottomSheetFlatList (created by BottomSheetFlatList)
    in RCTView (created by View)
    in View (created by AdminCommunityCasesModal)


```

Links to the errors I get
Screenshot 1: https://dropover.cloud/45ae17
Screenshot 2: https://dropover.cloud/e0c455

### Expected Behavior

The App should not crash and zero render errors 

### Tamagui Version

```markdown
1.84.1
```

### Platform (Web, iOS, Android)

```markdown
IOS & Android
```

### Reproduction

```markdown
This is the component I use

1. Create a button that triggers a bottom sheet appearance
2. The bottom sheet component is the following: https://gist.github.com/AdzeB/35faeb16a97b33b723c1faeddf588ef9
3.
```

### System Info

```markdown
https://gist.github.com/AdzeB/4c94163a0fcd9bef9325d57c15f0fac5
```

**Comment by TheEhsanSarshar** [comment]
please post the actual error message.

**Comment by AdzeB** [comment]
The Screenshots and the error message I posted is all I got; that's why I said it's very ambiguous or confusing

**Comment by TheEhsanSarshar** [comment]
from those errors, all it seems is something wrong with your `SizeableText` inside `ListHeaderComponent`

**Comment by AdzeB** [comment]
But if I comment out `SizeableText` then XStack is the one that has the rendering issue, but `YStack` works with no issues, also the `SizeableText` I haven't changed it one bit

**Comment by TheEhsanSarshar** [comment]
create a simple repro and I'll check that!

**Comment by TheEhsanSarshar** [comment]
I'll re-open it once you provide a repro
