### ISSUE TITLE
Storybook setup script or working example

### ISSUE THREAD

**Issue by RealOFF** [tamagui/tamagui#208]
**Is your feature request related to a problem? Please describe.**
I spent a lot of time in trying to setup this amazing library with storybook, but all my trying was failed.

**Describe the solution you'd like**
Please provide some proper solution to setup uikit with your library, e.g. storybook setup script or example.

**Comment by pontusab** [comment]
here is an example: https://github.com/dohomi/tamagui-kitchen-sink/tree/master/apps note that vite has some issues building, but the webpack version works great!

**Comment by dohomi** [comment]
at the moment the newest versions are not working as expected.. #172 keeps track on this
