### ISSUE TITLE
[Docs] Links don't use href attribute

### ISSUE THREAD

**Issue by danielberndt** [tamagui/tamagui#2086]
### Current Behavior

Looking at e.g. [this doc page](https://tamagui.dev/docs/intro/themes), you can see that the "Read the guide" link does not contain a `href` attribute. This makes it impossible to e.g. cmd+click to open the page in another tab.

<img width="396" alt="image" src="https://github.com/tamagui/tamagui/assets/856386/b5981ae4-db54-42a3-9f40-cc412597e916">

This seems to be true for most (if not all) links that are created using mdx in the docs.

### Expected Behavior

links should contain a `href` attribute

### Tamagui Version

```markdown
current docs
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
Visit this page: https://tamagui.dev/docs/intro/themes
```

**Comment by TheEhsanSarshar** [comment]
thanks for reporting! that's an issue with `mdx-bundler` that we internally use. I submitted an issue there

**Comment by ibash** [comment]
When evaluating tamagui vs other libraries this is something I noticed. Took a quick look and couldn't pinpoint where the issue was.

**Comment by TheEhsanSarshar** [comment]
yeah that's a Doc issue and won't impact users of Tamagui library

**Comment by ibash** [comment]
Found it! nextlink was stripping it out: https://github.com/tamagui/tamagui/pull/2544

And yep definitely understand it's a doc issue, just noting that as a dev it jumps out at me when the rest of the site is so polished :)
