### ISSUE TITLE
BorderColor type error on Input

### ISSUE THREAD

**Issue by jordisantamaria** [tamagui/tamagui#2088]
### Current Behavior

When I try to include a borderColor to a tamagui <Input/>, it returns me a typescript error but the color is applied.
Also there is no borderColor prop on the autocomplete for the Input component.

Some screenshots of the prove:
![image](https://github.com/tamagui/tamagui/assets/6263700/13a919ac-e326-476e-b772-95a8fb32076c)
![image](https://github.com/tamagui/tamagui/assets/6263700/8cb0a55d-531c-4850-bb45-0a5ad0319d58)

### Expected Behavior

Input not returning type error for borderColor prop

### Tamagui Version

```markdown
1.85.2
```

### Platform (Web, iOS, Android)

```markdown
Android
```

### Reproduction

```markdown
Try to apply borderColor prop to the tamagui starter-free template
Then it will return typescript error.
```

### System Info

```markdown
System:
    OS: Linux 5.15 Linux Mint 21.1 (Vera)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 20.69 GB / 31.26 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 4.0.2 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
  Browsers:
    Brave Browser: 113.1.51.114
    Chrome: 115.0.5790.170
    Firefox: 108.0.1
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0
    @manypkg/cli: ^0.19.1 => 0.19.2
    check-dependency-version-consistency: ^3.0.3 => 3.0.3
    eslint: ^8.21.0 => 8.39.0
    node-gyp: ^9.3.1 => 9.3.1
    prettier: ^2.7.1 => 2.8.8
    turbo: ^1.10.3 => 1.10.3
    typescript: ^5.3.3 => 5.3.3
```

**Comment by corasan** [comment]
I upgraded to `1.85.12` and the same thing is happening with `borderRadius`, it's not just a typescript error as it is not applying the token strings ($1, $2, etc.). I will have to downgrade to the version I was on before, `1.81.4`.

**Comment by TheEhsanSarshar** [comment]
probably there is a cache issue with your repos. try to remove node_modules
I'll close this issue for now

**Comment by jordisantamaria** [comment]
Well, I reinstalled with cli the tamagui starter free and same problem perceive.

It's not only borderColor, color and borderRadius also doesn't work, there is a huge problem with props typing on the library.

**Comment by TheEhsanSarshar** [comment]
did you run `yarn watch`

**Comment by jordisantamaria** [comment]
No I didnt, but  `yarn watch` doesn't work and there is no documentation about what does this command anywhere
![image](https://github.com/tamagui/tamagui/assets/6263700/8360f707-f926-46a6-9ed8-9ce7e62e3043)
