### ISSUE TITLE
create-tamagui-app Module parse failed: Unexpected token error in Provider

### ISSUE THREAD

**Issue by ALegendsTale** [tamagui/tamagui#209]
**Describe the bug**
Hello, I tried to create a new starter monorepo but when I run `yarn web`, I'm receiving this error:
```
error - ../../packages/app/provider/index.tsx
Module parse failed: Unexpected token (5:46)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { TamaguiProvider, TamaguiProviderProps } from '@my/ui'
|
> export function Provider({ children, ...rest }: Omit<TamaguiProviderProps, 'config'>) {
|   return (
|     <TamaguiProvider config={config} disableInjectCSS defaultTheme="light" {...rest}>
```

**To Reproduce**
Create new starter monorepo using `npx create-tamagui-app@latest myapp`
Run `cd myapp` `yarn web`

**Comment by natew** [comment]
This bug happens windows-only, I've tried fixing a few times but cannot get a Windows VM working on my mac.

**Comment by ALegendsTale** [comment]
Let me know if there's anything I can do to help test/fix this. In the meantime, I'll close this because I just realized that it's a duplicate of #151. I'll move there.
