### ISSUE TITLE
flex={2} doesnt apply flex: 2 as css in web

### ISSUE THREAD

**Issue by chrisaugustsson** [tamagui/tamagui#2091]
### Current Behavior

When adding flex={2} the styles applied are flex-grow: 2

### Expected Behavior

Adding flex={2} should add flex: 2 to the effected element. I need this to create a two column grid so I can have two equally sized containers, but instead the containers are adjusted to the content inside.

### Tamagui Version

```markdown
1.85
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://codesandbox.io/p/sandbox/snowy-http-5hpl4h?file=%2Fpackages%2Fapp%2Ffeatures%2Fhome%2Fscreen.tsx%3A55%2C39
```

**Comment by TheEhsanSarshar** [comment]
we are following react native standard of flex={2}.
you can add flexBasis={0} alongside flex={2} to achieve similar behaviour

**Comment by chrisaugustsson** [comment]
Yep, you are right. Sorry about that. Closing this one.
