### ISSUE TITLE
specific tokens and $color.token can't transform to css variable in production

### ISSUE THREAD

**Issue by youniaogu** [tamagui/tamagui#2092]
### Current Behavior

<img width="1436" alt="截屏2024-01-16 16 28 11" src="https://github.com/tamagui/tamagui/assets/13073995/b29cfe26-136f-4ebb-85d7-46f38d9e5e33">

### Tamagui Version

```markdown
1.85.12
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
git clone https://github.com/youniaogu/starter-free
cd ./starter-free
yarn install
yarn web:prod
yarn web:prod:serve
```

### System Info

```markdown
System:
  OS: macOS 14.1.1
  CPU: (8) arm64 Apple M2
  Memory: 536.80 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn: 4.0.2 - ~/.nvm/versions/node/v18.19.0/bin/yarn
  npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
Browsers:
  Chrome: 120.0.6099.216
  Safari: 17.1
npmPackages:
  @babel/runtime: ^7.18.9 => 7.21.0 
  @manypkg/cli: ^0.19.1 => 0.19.2 
  check-dependency-version-consistency: ^3.0.3 => 3.0.3 
  eslint: ^8.21.0 => 8.39.0 
  node-gyp: ^9.3.1 => 9.3.1 
  prettier: ^2.7.1 => 2.8.8 
  turbo: ^1.10.3 => 1.10.3 
  typescript: ^5.3.3 => 5.3.3
```

**Comment by TheEhsanSarshar** [comment]
Wasn't able to reproduce it!
let me clone your repo

**Comment by TheEhsanSarshar** [comment]
wasn't able to reproduce it in your repo as well.

**Comment by TheEhsanSarshar** [comment]
probably you forgot to run `yarn watch`

**Comment by youniaogu** [comment]
@TheEhsanSarshar it should reproduce in nextjs production env (run `yarn web:prod:serve`). development env work fine

**Comment by youniaogu** [comment]
and also i run `yarn watch` command but i got a error:

`Usage Error: Invalid option schema: missing at least one property from "all", "recursive", "since", or "worktree"`

**Comment by julianmills** [comment]
I am also experiencing this in production builds - @TheEhsanSarshar it's not a dev problem

**Comment by TheEhsanSarshar** [comment]
@youniaogu add `--all` after `foreach` inside that `watch` script!

**Comment by TheEhsanSarshar** [comment]
I tested that on both prod and dev and it was working fine
ok, I'll see this again

**Comment by youniaogu** [comment]
not work even add `yarn watch`, but i got a suppose after dig in `getToken` code

Is specificTokens has difference between dev and prod? https://github.com/tamagui/tamagui/blob/master/packages/web/src/config.ts#L60
