### ISSUE TITLE
fix(switch): warning message when change theme

### ISSUE THREAD

**Issue by juniorogaa** [tamagui/tamagui#2105]
### Current Behavior

When I change the theme, I receive a warning from the Switch component.

<img width="318" alt="image" src="https://github.com/tamagui/tamagui/assets/96478892/5cd1a98c-fa93-4d19-92bd-cf881c2116a0">

### Expected Behavior

Dont show warning.

### Tamagui Version

```markdown
1.86.5
```

### Platform (Web, iOS, Android)

```markdown
Android and iOS
```

### Reproduction

```markdown
Just you need a button to change the global theme to light/dark on Theme from tamagui.
```

**Comment by juniorogaa** [comment]
I receive the same message on H6 and ScrollView component.
<img width="323" alt="image" src="https://github.com/tamagui/tamagui/assets/96478892/ff6f034e-56cd-472e-9d3c-d53bc7f2dfc3">

<img width="320" alt="image" src="https://github.com/tamagui/tamagui/assets/96478892/3bb3756b-3ffb-469e-90f1-ab11b65f9032">

**Comment by TheEhsanSarshar** [comment]
this is just a warning! we are aware of this issue, soon will be fixed! 
it won't affect your app
