### ISSUE TITLE
Theme quick start missing types

### ISSUE THREAD

**Issue by apperside** [tamagui/tamagui#211]
**Describe the bug**
Hello,
I am trying to follow the Theme quick start guide (https://tamagui.dev/docs/intro/themes#quick-start), 
but the following imports do not work

`import { color, radius, size, space, themes, zIndex } from '@tamagui/theme-base'`

The only variable which is actually exported from `@tamagui/theme-base` is `themes`, all the others are not exported.
I am running on tamagui 1.0.1-beta.165

**To Reproduce**
Follow this quickstart https://tamagui.dev/docs/intro/themes#quick-start

**System Info (please complete the following information):** 
  System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 20.57 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 104.0.2
    Safari: 16.0

**Comment by natew** [comment]
Should be fixed in last two betas.
