### ISSUE TITLE
Lucide Icons Error

### ISSUE THREAD

**Issue by JayYoungman** [tamagui/tamagui#2111]
### Current Behavior

Lucide Icons not working after following the installation steps https://tamagui.dev/docs/components/lucide-icons/1.0.0

Error: Missing tamagui config, you either have a duplicate config, or haven't set it up. Be sure createTamagui is called before rendering. Also, make sure all of your tamagui dependencies are on the same version (`tamagui`, `@tamagui/package-name`, etc.) not just in your package.json, but in your lockfile.

### Tamagui Version

```markdown
"@tamagui/animations-css": "^1.84.0",
    "@tamagui/animations-react-native": "^1.84.0",
    "@tamagui/build": "^1.84.0",
    "@tamagui/helpers-icon": "^1.84.0",
    "@tamagui/lucide-icons": "1.84.0",
    "@tamagui/react-native-media-driver": "^1.84.0",
    "@tamagui/react-native-svg": "^1.84.0",
    "@tamagui/shorthands": "^1.84.0",
    "@tamagui/themes": "^1.84.0",
    "@tamagui/use-did-finish-ssr": "^1.84.0",
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
import { Button } from 'tamagui'
import { Plus } from '@tamagui/lucide-icons'

export default () => (
  <Button icon={Plus}>
    Hello world
  </Button>
)
```

**Comment by TheEhsanSarshar** [comment]
icons are working fine!
there is an issue in your repo. mostly an issue related to your tamagui versions.
check all package.json files and do cleanup by deleting node_modules and reinstalling

**Comment by TheEhsanSarshar** [comment]
@fabaohs I wasn't able to reproduce it!
is it possible to create a small reprod of this issue, try using a fresh tamagui project

**Comment by fabaohs** [comment]
<img width="1145" alt="Captura de Tela 2024-01-24 às 16 11 47" src="https://github.com/tamagui/tamagui/assets/85971236/e6a2aa5a-6a36-4afa-914c-092d3da11865">

**Comment by TheEhsanSarshar** [comment]
if you can create a reprod using Tamagui starter I'll check that, otherwise I can't reproduce it!

**Comment by JayYoungman** [comment]
Something else worth noting, is @tamagui/vite-plugin doesn't seem to be compatible with @tamagui/lucide-icons

v1.90.2

`14:52:44 [vite] Internal server error: Must provide components
  Plugin: tamagui-extract`

`✘ [ERROR] Could not resolve "@tamagui/use-did-finish-ssr"

    ../node_modules/@tamagui/portal/dist/esm/GorhomPortal.js:3:32:
      3 │ import { useDidFinishSSR } from "@tamagui/use-did-finish-ssr";`

**Comment by DatoKhojava** [comment]
I have same, even deleting node_modules didn't give me anything :(( any ideas ?
