### ISSUE TITLE
Dialog: `trapFocus`  forces element to always be focused

### ISSUE THREAD

**Issue by ArthurYidi** [tamagui/tamagui#2118]
### Current Behavior

`trapFocus` force elements to alway be focused. It should only trap the focus for elements inside the dialog.

### Expected Behavior

Allow elements to focus out, specially important in mobile so the **keyboard goes down**.

https://github.com/tamagui/tamagui/assets/1154353/097bba74-5496-4bf4-b90f-d001b849e649

### Tamagui Version

```markdown
`current`
```

### Platform (Web, iOS, Android)

```markdown
- Web: Desktop and Android Chrome
```

### Reproduction

```markdown
Kitchen Sink: `http://localhost:9000/?demo=Dialog`

- Add `trapFocus={open}` to `Dialog.Content`
- Focus on an element inside a Dialog
- Click on a non-focusable element
- Bug: Focus is still on the element
 
Note: modified default focus colors so it's easier to see.
```
https://github.com/tamagui/tamagui/assets/1154353/5cbcdaee-801e-4f74-93f1-0a2df84f0f05

**Comment by TheEhsanSarshar** [comment]
`Dialog.Content` also accepts `trapFocus` prop. making that prop `true` will fix this issue.
there seems to be missing types.

**Comment by ArthurYidi** [comment]
@TheEhsanSarshar it does not fix the issue see reproduction steps.

**Comment by TheEhsanSarshar** [comment]
emm, sorry maybe didn't understand the issue correctly.
are we going to make the focus to always be trapped inside Dialog?
if yes then making that prop to `true` should fix it.
btw I have a fix, le see if that resolve the issue

**Comment by ArthurYidi** [comment]
@TheEhsanSarshar no I proposed to help tackle that in a separate issue. 

> are we going to make the focus to always be trapped inside Dialog?

no the issue is about allowing the element to un-focus when clicking inside the dialog.

**Comment by ArthurYidi** [comment]
@TheEhsanSarshar also see: https://discord.com/channels/909986013848412191/909986013848412194/1197350336579522712

**Comment by TheEhsanSarshar** [comment]
that unfocus is working fine somehow in the doc.
btw we need to trap focus when it's modal and open, and I think it's better to keep it uncontrolled ? as that will avoid the bug of unclickable content when the user forgets to make the trapFocus false when Dialog is closed!

**Comment by TheEhsanSarshar** [comment]
is that still happening on the [site](https://tamagui.dev/docs/components/dialog/1.0.0)

**Comment by ArthurYidi** [comment]
> when it's `modal` and `open`

Agree


> is that still happening on the [site](https://tamagui.dev/docs/components/dialog/1.0.0)

I think you meant: https://vercel.live/open-feedback/site-git-fix-dialog-trapfocus-tamagui.vercel.app?via=pr-comment-visit-preview-link&passThrough=1

and yes still happening, make sure to test in Chrome:

https://github.com/tamagui/tamagui/assets/1154353/3bdd3876-6687-4153-a899-e890b56fe433

**Comment by ArthurYidi** [comment]
@TheEhsanSarshar the issue is caused by `display: contents` causing the `contains` in [FocusScope:81](https://github.com/ArthurYidi/tamagui/blob/3cfb678feff12a930258310cc69e11f6484e7759/packages/focus-scope/src/FocusScope.tsx#L81) to not work properly

**Comment by TheEhsanSarshar** [comment]
emm, tested on both Chrome and Safari, still wasn't able to reproduce. that's weird!

**Comment by TheEhsanSarshar** [comment]
https://github.com/tamagui/tamagui/assets/46188784/2402eac9-4116-457d-9d07-7fb49fabd2c2

**Comment by ArthurYidi** [comment]
@TheEhsanSarshar make sure you are testing it with `trapFocus`, it doesn't look like it is in your test. Your last tab looks like it went outside the container.

**Comment by TheEhsanSarshar** [comment]
oh, actually reproducible on my local project! I don't know why the Tamagui site is fine here!
anyway yeah that's an issue! were you able to find a solution for that

**Comment by natew** [comment]
I think this is fixed, I can't repro anymore.
