### ISSUE TITLE
Broken types to styled(TextInput)

### ISSUE THREAD

**Issue by radko93** [tamagui/tamagui#2120]
### Current Behavior

When adding `fontFamily` to

```
const InputFrame = styled(TextInput, {
  fontFamily: 'arial',
});
```

there's an TS error
`'fontFamily' does not exist in type 'Partial<GetFinalProps<TextInputProps, StackStylePropsBase>>`

### Tamagui Version

```markdown
1.88.0
```

### Platform (Web, iOS, Android)

```markdown
RN 0.73.2, TS 5.3.3
```

### Reproduction

```markdown
const InputFrame = styled(TextInput, {
  fontFamily: 'arial',
});
```
```


### System Info

_No response_

**Comment by TheEhsanSarshar** [comment]
you need to pick one of the font families defined in your config.
like `fontFamily: '$body'`

**Comment by radko93** [comment]
Hey, actually had '$1' in my code but replaced here in the example. Problem is font family does not exist.

**Comment by TheEhsanSarshar** [comment]
I wasn't able to reproduce it! if you can reprod it in a new Tamagui project, I can trace it more
