### ISSUE TITLE
Docs: Select Component Page has client-side exception on certain breakpoints.

### ISSUE THREAD

**Issue by SushritPasupuleti** [tamagui/tamagui#213]
**Describe the bug**
The `Select` component [docs](https://tamagui.dev/docs/components/select/1.0.0-beta.0) work fine on wider screens, but when you switch to a more mobile like width, it has a client side exception.

**To Reproduce**
Go  [here](https://tamagui.dev/docs/components/select/1.0.0-beta.0). Resize your window to less than 600px.

**Comment by natew** [comment]
This is fixed in latest beta, thanks for the report.
