### ISSUE TITLE
Clicking Select and closing doesn't focus the Select

### ISSUE THREAD

**Issue by natew** [tamagui/tamagui#2142]
### Current Behavior

.

### Expected Behavior

If you click it, then close it, it should show the focus ring around it. It doesn't if you aren't already focused before.

### Tamagui Version

```markdown
cur
```

### Platform (Web, iOS, Android)

```markdown
.
```

### Reproduction

```markdown
.
```

### System Info

```markdown
.
```

**Comment by TheEhsanSarshar** [comment]
using keyboard navigation it's working fine for me
could share the steps to re-produce it
