### ISSUE TITLE
Font tokens not working in variants (types only)

### ISSUE THREAD

**Issue by apperside** [tamagui/tamagui#218]
**Describe the bug**
I am trying to setup the typography in my design system, and I made this styled component:

```typescript

import { styled, Text as TamaguiText } from 'tamagui'

export const MyLabel = styled(TamaguiText, {
  borderRadius: 100_000_000,

  variants: {
    type: {
      H1: {
        fontFamily: '$myFont',
        fontSize: '1.43rem',
      },
      semiBold: {
        fontFamily: 'Barlow-SemiBold',
      },
      medium: {
        fontFamily: 'Barlow-Medium',
      },
      regular: {
        fontFamily: 'Barlow-SemiBold',
      },
    },

    size: {
      normal: {
        fontSize: '1rem',
      },
      large: {
        fontSize: '1.2rem',
      },
      small: {
        fontSize: '0.85rem',
      },
    },

  } as const,
  defaultVariants: {
    type: 'regular',
    size: 'normal',
  },
})


```

In this case `$myFont` is a font token I declared in my theme, and it works because the following works

```typescript
import { Label } from "tamagui"

<Label fontFamily={'$myFont'}>Dashboard</Label>
```

But the following doesn't

```typescript
import { MyLabel } from "@my/ui"

<MyLabel type={'h1'}>Dashboard</MyLabel>
```

So it seem that font tokens cannot be used in variants, but reading [this section](https://tamagui.dev/docs/core/variants#variants-and-pseudos-media-queries) of the docs, it should

**Comment by natew** [comment]
Good catch, the font system right now is in need of work I realize, because it really has some weird special properties. Ideally I should remove those if possible. But have a fix for most cases almost read.y

**Comment by natew** [comment]
This should be fixed in 174, let me know.

**Comment by apperside** [comment]
Hello @natew,
I can confirm it works now, but the tokens are not inferred. All the tokens you see for example here 
<img width="420" alt="Screenshot 2022-09-23 at 10 27 48" src="https://user-images.githubusercontent.com/5955338/191920913-450da64a-4f86-4150-aec1-030f412e8e53.png">

are not inferred at all. BTW, That's a good compromise for now, at least it works 😀

**Comment by natew** [comment]
That is odd - intellisense shows the right value as you type the property, but then doesn't autocomplete...

**Comment by apperside** [comment]
Hi Nate,
this is a screen recording


https://user-images.githubusercontent.com/5955338/192283104-41ed5137-84d3-4632-8f13-c643dab05181.mov

**Comment by alitnk** [comment]
This is an old issue and we've had dozens of releases since then. Closing this but feel free to re-open if you're still having the issue.

For the record, it works for me on the latest version.
<img width="523" alt="image" src="https://github.com/tamagui/tamagui/assets/35243344/d74a3c3d-5b6e-4ecd-8c3f-5bddba54ce3f">
