### ISSUE TITLE
Select doesn't go away once selected, on web mobile viewport

### ISSUE THREAD

**Issue by tazsingh** [tamagui/tamagui#2220]
### Current Behavior

If you go to the Select docs in Chrome, change the viewport to be Mobile Touch, and select the item that's also overlaying the `Trigger`, the overlaid items do not disappear

https://tamagui.dev/docs/components/select

### Expected Behavior

Once you select any item, the overlaid items should disappear

### Tamagui Version

```markdown
The URL says: https://tamagui.dev/docs/components/select/1.40.0
```

### Platform (Web, iOS, Android)

```markdown
Web, tested in Chrome Mobile touch Dev Tools
```

### Reproduction

```markdown
On Chrome, open the Dev Tools, go into Mobile Touch emulation mode

Open the Select docs: https://tamagui.dev/docs/components/select/1.40.0

Click to open the Custom Select

Click on the same Item that is overlaid with the Trigger

You should notice that the Select does not go away

If you select an Item that is not overlaid with the Trigger, the Select does go away, as expected
```

**Comment by TheEhsanSarshar** [comment]
check solutions in this [issue](https://github.com/radix-ui/primitives/issues/1658)

**Comment by medv** [comment]
Thanks for the solution!
Correction: the above ref should be placed on `Select.Item`
