### ISSUE TITLE
Input inside Dialog doesn't drop focus as expected

### ISSUE THREAD

**Issue by chrisaugustsson** [tamagui/tamagui#2222]
### Current Behavior

Pressing enter-key on a Input inside a Dialog will select all the text content inside the Input.

### Expected Behavior

Pressing enter should drop the focus of the Input.

### Tamagui Version

```markdown
1.89.11
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://codesandbox.io/p/sandbox/long-butterfly-2zxj54?file=%2Fpackages%2Fapp%2Ffeatures%2Fhome%2Fscreen.tsx%3A37%2C32
```

**Comment by TheEhsanSarshar** [comment]
I don't think that is an expected behaviour!
for changing focus you can use `Tab` or you can implement your own logic by using `onKeyDown` prop on Input!

**Comment by chrisaugustsson** [comment]
If you look in the example you can see that it works exactly as I mentioned outside of the Dialog, but when the input is inside the dialog, if you either press enter or use blur() on the ref, it highlights the text inside the input instead of dropping the focus.

**Comment by TheEhsanSarshar** [comment]
ah sorry maybe I didn't understand the problem correctly here
