### ISSUE TITLE
Input inside Dialog doesn't drop focus as expected

### ISSUE THREAD

**Issue by chrisaugustsson** [tamagui/tamagui#2223]
### Current Behavior

Using blur() on Input inside a Dialog causes the text inside the input to be highlighted. Doing the same outside doenst cause this.

### Expected Behavior

Using blur() on the ref should drop focus.

### Tamagui Version

```markdown
1.89.11
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://codesandbox.io/p/sandbox/long-butterfly-2zxj54?file=%2Fpackages%2Fapp%2Ffeatures%2Fhome%2Fscreen.tsx%3A37%2C32
```

**Comment by natew** [comment]
You have to instead focus another element within Dialog. Dialog has a focus guard that traps focus within it, so blurring instead is forced back to the first focused action

**Comment by natew** [comment]
You can also disable the focus trap behavior! Lmk if that works.

**Comment by chrisaugustsson** [comment]
> You can also disable the focus trap behavior! Lmk if that works.

That did work, however, there doesn't seem to be a way to set trapFocus to false from the Dialog.Content. If you take a look into DialogContentImpl, trapFocus is set to context.open, so there is no way to set it to false.

In FocusScope, the handleFocusOut function selects the last focused element if the target isn't in the container, but wouldn't it be possible to set to focus to the container itself? It works for my issue, but I'm not sure if it breaks anything else.

**Comment by chrisaugustsson** [comment]
If my suggestion would be a valid solution, I can make a PR for it.

**Comment by natew** [comment]
Looks like maybe two things here a bugfix for passing trapFocus. 

The second part is harder. Do we want to make trapFocus take another argument to prefer the container? But what if we want the first time to focus the input but then all blurs to do the container? I’d think what we could do is add some special logic to detect a blur called inside and have it automatically return the focus to the container rather than the first input in just that special case. Happy to accept a PR.

**Comment by chrisaugustsson** [comment]
I have a possible solution, that might be a bit hacky. However, I'm not allowed to create a PR?

In short the fix looks like this:
 `    function handleFocusIn(event: FocusEvent) {
      if (focusScope.paused || !container) return
      const target = event.target as HTMLElement | null
      if (container.contains(target)) {
        // Set container as lastFocusedElement to prevent inputs
        // to be refocused on blur events
        target?.addEventListener('blur', () => {
          lastFocusedElementRef.current = container
        })
        lastFocusedElementRef.current = target
      } else {
        focus(lastFocusedElementRef.current, { select: true })
      }
    }`
    
    We set a event listener on the target for blur events, and when it is called we set lastFocusedElement to the container. That way we don't have to do anything special in the handleFocusOut function, since we have already updated the target to focus.
