### ISSUE TITLE
Cannot find module '@tamagui/config/v3' or its corresponding type declarations

### ISSUE THREAD

**Issue by iamursky** [tamagui/tamagui#2224]
### Current Behavior

I'm trying to use the configuration from Quick Start section of the docs:
https://tamagui.dev/docs/core/configuration#quick-start

Getting a TypeScript error "Cannot find module '@tamagui/config/v3' or its corresponding type declarations".

### Tamagui Version

```markdown
- tamagui: 1.89.11
- @tamagui/config: 1.89.11
```

### Platform (Web, iOS, Android)

```markdown
Web, iOS, Android
```

### Reproduction

```markdown
Reproduction demo: https://github.com/iamursky/tamagui-config-v3-reproduction

Check out the `packages/config/src/tamagui.config.ts` file.
```

**Comment by dwbelliston** [comment]
Seeing the same

![Uploading Screenshot 2024-02-07 at 12.48.16 PM.png…]()

**Comment by DanTheTingler** [comment]
seeing the same thing as well

**Comment by webdiego** [comment]
Same!

**Comment by natew** [comment]
Ah man, what a terrible rollout. Added them to the other packages but not config itself. I have to manually add all root files using `files` with npm which I should really fix because its so error prone. And I need to see now why your create-tamagui integration test is silently failing...

Fix going out now.

**Comment by natew** [comment]
Fixed c7bd4579fc7e4bcf9b4bc225427bd976c48218a3

**Comment by iamursky** [comment]
Thank you for the fix! Upgraded and now I'm getting another error now: Unable to resolve "@tamagui/themes/v3-themes" from "node_modules/@tamagui/config/dist/cjs/v3.js"

```
@tamagui/animations-react-native: 1.89.15
@tamagui/config: 1.89.15
@tamagui/font-inter: 1.89.15
@tamagui/next-theme: 1.89.15
@tamagui/shorthands: 1.89.15
@tamagui/themes: 1.89.15
tamagui: 1.89.15
```

**Comment by natew** [comment]
Fix in release going out now.
