### ISSUE TITLE
[Bug] placeholderTextColor default and overrides don't apply on Android properly on

### ISSUE THREAD

**Issue by SushritPasupuleti** [tamagui/tamagui#223]
**Describe the bug**
The default placeholder text color isn't consistent with other platforms on android. Overriding it with the `placeholderTextColor` doesn't change it either.

On the default dark theme, the placeholder is colored in black on android while it's gray-ish white on all other platforms. And overriding the color doesn't work.

**To Reproduce**
Just test this sippet on all platforms:

```jsx
<Input
placeholder="This will be inconsistently colored on Android"
    // placeholderTextColor="$gray1Light" 
    //toggle above prop for override check
/>
```

### Update

Token Values of colors like `$color12` don't work but `"white"` works on android.

**System Info (please complete the following information):** 

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 104.48 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 3.2.0 - /usr/local/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
    Watchman: 2022.08.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 105.1.43.93
    Chrome: 105.0.5195.125
    Firefox: 104.0.2
    Safari: 16.0

**Comment by SushritPasupuleti** [comment]
if anyone is facing this issue, closing expo and running it with `--clear` fixed this somehow!

Full command:

```bash
yarn native --clear
```

Hope this helps someone! Closing this now!

**Comment by SushritPasupuleti** [comment]
Ok this is weird, it started doing it again. So I'm attaching screenshots

iOS: 
![Screenshot 2022-09-22 at 12 06 00 PM](https://user-images.githubusercontent.com/14891901/191675289-8a6e0fbb-7026-498f-aebc-c51c01c93d31.png)

Android:
![Screenshot 2022-09-22 at 12 06 57 PM](https://user-images.githubusercontent.com/14891901/191675430-86ce19ae-e609-4166-aa09-7169716f5537.png)

This is produced for the following snippet:

```jsx
<Input
    placeholder="This will be inconsistently colored on Android"
/>
```

**Comment by natew** [comment]
This should be fixed now in latest release. Please re-open if not.
