### ISSUE TITLE
checkbox rendering performance issue

### ISSUE THREAD

**Issue by flodev** [tamagui/tamagui#2233]
Hi,
I just noticed that rendering many checkboxes causes stuttering until the checkboxes are rendered.
I'm developing mainly expo react-native and didn't check on web. The issue was noticed on iOS simulator. Didn't check on android tho.
Since performance is written on your flag I thought I should report it.

I was rendering ~130 checkbox rows which looked the following:
```jsx
<ListPickerItemRow isChecked={isChecked} onPress={() => onCheckedChange(!isChecked)}>
      <Text>{label}</Text>
      <Checkbox checked={isChecked}>
        <Checkbox.Indicator>
          <CheckIcon />
        </Checkbox.Indicator>
      </Checkbox>
    </ListPickerItemRow>
```

When rendering this into a plain view the app takes about 5 seconds until the view appears.
Removing just the checkbox from the row fixes the issue.
Rendering 130 items in a flatlist improves it a bit but there is still a noticable slow down.

**Comment by natew** [comment]
In dev or prod? At the bare minimum before you break rules to open an issue you should include just simple details like this. It's why we have a form and rules.

**Comment by nfejer97** [comment]
@natew same for me in dev and prod also

**Comment by natew** [comment]
I think we had a ref issue where it may be setting state multiple times causing multiple re-renders... 1.118.1 should have a fix for that (going out now). Can you let me know if that helps?

**Comment by nfejer97** [comment]
> I think we had a ref issue where it may be setting state multiple times causing multiple re-renders... 1.118.1 should have a fix for that (going out now). Can you let me know if that helps?

@natew unfortunately, it is not working, and the same issue occurs with Select and Sheet as well. ("expo": "~51.0.36", "react-native": "0.74.5",)
