### ISSUE TITLE
Docs: Issue with Dialog at `sm` breakpoint on Web

### ISSUE THREAD

**Issue by SushritPasupuleti** [tamagui/tamagui#226]
**Describe the bug**
The docs page has a client-side exception when rendering the dialog on smaller viewports on web. May be similar to #213 

Second issue related to this is that the SheetBreakpoint doesn't work on Android (Portrait orientation). Disabling it renders the Popup dialog as expected.

**To Reproduce**
Visit [this](https://tamagui.dev/docs/components/dialog/1.0.0-beta.0) and reduce viewport width below 600px

And run the example on Android in Portrait Orientation.

**Comment by natew** [comment]
Oh wow, this is because I added `SelectDemo` *inside* `DialogDemo`, which means we have a Sheet inside Sheet. Seeing what it takes to get that working.

**Comment by natew** [comment]
Turns out slightly unrelated.

**Comment by SushritPasupuleti** [comment]
> Oh wow, this is because I added `SelectDemo` _inside_ `DialogDemo`, which means we have a Sheet inside Sheet. Seeing what it takes to get that working.

I understand, honestly I think this particular thing is more of a UX problem, about when a sheet and dialog really start becoming more accessible over the other.
