### ISSUE TITLE
lucide-icons removed with recent update

### ISSUE THREAD

**Issue by rmarscher** [tamagui/tamagui#2260]
### Current Behavior

I started receiving import errors in a project after updating Tamagui that was trying to import the `Edit` icon from `@tamagui/lucide-icons`.

I see there was an update to the icons in this PR https://github.com/tamagui/tamagui/pull/2095

It looks like maybe there was another commit that removed it?
https://github.com/tamagui/tamagui/commits/master/packages/lucide-icons/src/icons/edit.tsx

And then several were added back in this commit -
https://github.com/tamagui/tamagui/commit/ab0f19cd258692144ff53c81a69efee893b3cde3

But at least edit.tsx was not re-added.

This is not a big deal. I can find another icon. But I thought I should report it.

### Expected Behavior

This icon was available not long ago.

### Tamagui Version

```markdown
1.89.20
```

### Platform (Web, iOS, Android)

```markdown
Web, any
```

### Reproduction

```markdown
import { Edit } from '@tamagui/lucide-icons'
```

**Comment by anujjoshi63** [comment]
Facing this issue
