### ISSUE TITLE
Sheet content bug with different height of the sheet

### ISSUE THREAD

**Issue by KristoT** [tamagui/tamagui#2267]
### Current Behavior

RIght now if the sheet has as the first snap point 45% and the second one 100%, then if i drag it to 100% then the content is cutting and thinks like it is still in 45%.

### Expected Behavior

if i drag it to 100% then the content should also grow dynamically as i drag it.

### Tamagui Version

```markdown
1.89.20
```

### Platform (Web, iOS, Android)

```markdown
in all platforms it is the same behaviour
```

### Reproduction

```markdown
i have used this repo: https://github.com/tamagui/starter-free and commited and pushed: https://github.com/tamagui/starter-free/compare/main...KristoT:starter-free:main
```

**Comment by TheEhsanSarshar** [comment]
Snap points should be ordered from largest to smallest (most visible to least visible).
check [documentation](https://tamagui.dev/docs/components/sheet/1.59.0)
