### ISSUE TITLE
Font weight face module don't worked on Android

### ISSUE THREAD

**Issue by theyanniss23002** [tamagui/tamagui#2277]
### Current Behavior

I'm using createFont, the project is all set up. On iOS the fonts work great, but on Android their boldness refuses to work.

### Expected Behavior

Tell me how to solve the problem with the lack of bold font

### Tamagui Version

```markdown
Version Tamagui 1.89.8
```

### Platform (Web, iOS, Android)

```markdown
Android
```

### Reproduction

```markdown
import {createFont} from 'tamagui';

export const interFont = createFont({
    family: 'Inter',
    size: {
        //Heading
        h1: 36,
        h2: 28,
        h3: 24,
        h4: 20,
        h5: 18,
        h6: 16,
        //Subtitle
        s1: 14,
        s2: 14,
        //Paragraph
        p1: 16,
        p2: 14,
        //Body
        b1: 16,
        b2: 14,
        b3: 14,
        //Caption
        c1: 14,
        c2: 12,
        //Label
        label: 12,
        true: 16,
    },
    lineHeight: {
        //Heading
        h1: 44,
        h2: 32,
        h3: 30,
        h4: 24,
        h5: 22,
        h6: 20,
        //Subtitle
        s1: 20,
        s2: 20,
        //Paragraph
        p1: 24,
        p2: 22,
        //Body
        b1: 20,
        b2: 20,
        b3: 20,
        //Caption
        c1: 18,
        c2: 16,
        //Label
        label: 16,
        true: 20,
    },
    weight: {
        bold: 700,
        semiBold: 600,
        medium: 500,
        regular: 400,
        true: 400,
    },
    face: {
        400: {normal: 'Inter-Regular'},
        500: {normal: 'Inter-Medium'},
        600: {normal: 'Inter-SemiBold'},
        700: {normal: 'Inter-Bold'},
    },
});
```

**Comment by TheEhsanSarshar** [comment]
can you share your `App.js` file

**Comment by theyanniss23002** [comment]
> can you share your `App.js` file

<img width="705" alt="Снимок экрана 2024-02-16 в 10 02 15" src="https://github.com/tamagui/tamagui/assets/57316921/13747bc2-4fb3-48ee-9de9-f7a7ba10086e">

**Comment by TheEhsanSarshar** [comment]
you need to load those fonts
check this [doc](https://tamagui.dev/docs/core/configuration#custom-font-family-on-native)

**Comment by theyanniss23002** [comment]
> you need to load those fonts check this [doc](https://tamagui.dev/docs/core/configuration#custom-font-family-on-native)

I don't use expo in my application

**Comment by TheEhsanSarshar** [comment]
@theyanniss23002 is it on web ?
because you said on ios

**Comment by theyanniss23002** [comment]
> @theyanniss23002 is it on web ? because you said on ios

No. I wrote that on iOS the fonts work as they should, but on Android there is no weight

**Comment by TheEhsanSarshar** [comment]
sorry I'm confused lol, is it on web or native ?

**Comment by theyanniss23002** [comment]
> извини, я запутался, лол, это онлайн или нативно?

react native

**Comment by TheEhsanSarshar** [comment]
you need to load your font using expo `useFont` or if you're using bare react native instead of expo, there are ways for react native as well
