### ISSUE TITLE
`animation` prop breaks some behaviours

### ISSUE THREAD

**Issue by arekkubaczkowski** [tamagui/tamagui#2299]
### Current Behavior

I have encountered some issues with rendering HTML elements and their styles when the `animation` prop is provided.

### Tamagui Version

```markdown
"tamagui": "1.89.20"
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

1. Create a styled component with the following configuration:

```markdown
const Test = styled(View, {
  tag: 'button',
  animation: 'fast',
  backgroundColor: 'red',
  width: 50,
  height: 50,
  hoverStyle: {
    backgroundColor: 'blue',
  },
});
```
3. Note that the Test component was rendered as a div element instead of a button, and the animation of the backgroundColor doesn't work at all.
4. Remove the animation prop and notice that the button element is rendered properly.
5. Restore the animation prop and additionally provide animateOnly: ['backgroundColor'], and notice the animation works fine now
```
const Test = styled(View, {
  tag: 'button',
  animateOnly: ['backgroundColor'],
  animation: 'fast',
  backgroundColor: 'red',
  width: 50,
  height: 50,
  hoverStyle: {
    backgroundColor: 'blue',
  },
});
```

So there are 2 issues:
- `animation` prop breaks customizing `tag` prop
- Animation doesn't work if `animateOnly` is not explicitly provided
```


### System Info

_No response_

**Comment by TheEhsanSarshar** [comment]
try using `accessibilityRole: 'button'`
`backgroundColor` is costly to animate on native using react native animated API.
so we made it so that you explicitly enable it

**Comment by arekkubaczkowski** [comment]
thanks @TheEhsanSarshar 
to clarify, the second issue was fixed by https://github.com/tamagui/tamagui/commit/3bdf785c5ebdaee18753c17ab7cc767367722ce2

**Comment by junioroga** [comment]
Im facing a similar problem.

When i remove the animation, XStack works perfectly in the horizontal direction, but if I put it back on, the direction is wrong.

https://github.com/tamagui/tamagui/assets/7414393/98a9f38e-c8cf-4ddb-8b6a-981aaf3cd1b7

**Comment by natew** [comment]
We should document the tag issue - it's a limitation of the animation drivers using React Native Web.

**Comment by natew** [comment]
I have a fix I think for the tag one at least coming soon.

**Comment by junioroga** [comment]
Almost there! The first issue was solved! now, the second case is 


https://github.com/tamagui/tamagui/assets/7414393/8e3b7153-33d3-4153-bbc2-df1da1b3ca29

**Comment by ConnorHome** [comment]
I've got a similar issue with the `Input` component, everything renders fine without the `animation` prop, but when I add it all styles are lost. FWIW if I change the styled component to be anything else (for an example an `XStack` or `Button`) then everything renders as expected. Happy to open another bug report if it is possibly unrelated to this? I'm on `1.90.6`.

**Comment by arekkubaczkowski** [comment]
It seems like this issue also impacts on the recently added pseudo `focusVisibleStyle` style:

https://github.com/tamagui/tamagui/pull/2278#issuecomment-1976386101

cc @natew  @TheEhsanSarshar

**Comment by TheEhsanSarshar** [comment]
@arekkubaczkowski will be fixe by this PR
https://github.com/tamagui/tamagui/pull/2387

**Comment by juniorogaa** [comment]
i have a problem when i use animation with transform X on web.

![image](https://github.com/tamagui/tamagui/assets/96478892/41358e24-771c-4ec3-ab06-d5158e807a65)

**Comment by TheEhsanSarshar** [comment]
@arekkubaczkowski there is a [PR](https://github.com/tamagui/tamagui/pull/2406) for that

**Comment by TheEhsanSarshar** [comment]
Ok, it seems there are some bugs with the Moti driver I guess ?
I'll check that this weekend or monday

**Comment by TheEhsanSarshar** [comment]
this PR might fix some issues posted here
https://github.com/tamagui/tamagui/pull/2608
please let me know if it's okay to close this issue

**Comment by natew** [comment]
This should be fixed on latest version, lmk if not
