### ISSUE TITLE
Using the deprecated unimodules package for RN?

### ISSUE THREAD

**Issue by kbrandwijk** [tamagui/tamagui#23]
Your installation instructions for RN mention using `@unimodules/core` for `LinearGradient `support. However, this package is deprecated in favor of the `expo` package. I didn't want to jump in a rabbit hole, so I haven't tried it out yet with the `expo `package instead, I just wanted to get your thoughts on it first.

**Comment by natew** [comment]
Hey, fixing that. We successfully updates to the newest versions so it should work with expo.

**Comment by natew** [comment]
Let me know if it doesn't and I'll re-open.
