### ISSUE TITLE
Wrong typing for color tokens in variant functions

### ISSUE THREAD

**Issue by arekkubaczkowski** [tamagui/tamagui#2300]
### Current Behavior

There is a wrong typing for color tokens inside of the variant function:

Create a following styled component:
```
const CheckboxSelectorFrame = styled(View, {
  variants: {
    error: {
      true: (_, { props, tokens }) => ({
        borderColor: tokens.color['$color-border-destructive-bold-hover'], // this works but it's not consistent with TS
      }),
      false: {
          backgroundColor: '$color-bg-destructive-default', // this works perfectly, why can't the above scenario work the same way?
      },
    },
  } as const,
});
``` 

<img width="744" alt="Screenshot 2024-02-19 at 11 20 29" src="https://github.com/tamagui/tamagui/assets/18654447/e83eb748-f783-44dc-ab0c-bcfefd88c678">

TypeScript suggests the color tokens under the tokens.color prop without the '$' sign, which appears to be incorrect as that object contains the color keys with the '$' sign included. Adding the '$' sign fixes it. However, TypeScript still doesn't complain for some reason, which means that you can provide whatever key you want and TypeScript won't throw an error.

Question:
Why the function variant cannot work the same way as inline variants, so you can pass token string without accessing from  any additional object?

### Expected Behavior

Ideally if tokens would be available directly as a string values instead of getting it from the object that comes from the upper function

### Tamagui Version

```markdown
"tamagui": "1.89.20"
```

### Platform (Web, iOS, Android)

```markdown
Web/iOS/Android
```

### Reproduction

```markdown
-
```

**Comment by arekkubaczkowski** [comment]
@TheEhsanSarshar any update on this by chance? Can I help you somehow to get that fixed?

**Comment by TheEhsanSarshar** [comment]
@arekkubaczkowski this PR https://github.com/tamagui/tamagui/pull/2398 should fix it

**Comment by arekkubaczkowski** [comment]
@TheEhsanSarshar btw. is there any way to get font tokens of out react context similarly how getToken is doing it? as getToken has not included fonts for some reason

**Comment by TheEhsanSarshar** [comment]
there is a `getFontSize()` function
```tsx
import { getFontSize } from '@tamagui/font-size'
```

**Comment by arekkubaczkowski** [comment]
@TheEhsanSarshar nice, but what about the rest of properties like weight, lineheight?  is it accessible somehow?

**Comment by arekkubaczkowski** [comment]
if not, I can give a try to implement it based on getFontSize helper. Let me know

**Comment by arekkubaczkowski** [comment]
I was able to achieve like this, I will create a PR in a spare time, if you have any remarks about the API please let me know

<img width="605" alt="Screenshot 2024-03-09 at 10 18 25" src="https://github.com/tamagui/tamagui/assets/18654447/05f4bf51-29b7-4acf-b406-712c391d8fb4">

<img width="166" alt="Screenshot 2024-03-09 at 10 18 38" src="https://github.com/tamagui/tamagui/assets/18654447/0dd2fcad-4d43-4c96-9857-663472649126">

**Comment by TheEhsanSarshar** [comment]
it suggests both for me. having it without `$` sign is wrong?
ok I'll check it today
