### ISSUE TITLE
About plans to support the Table

### ISSUE THREAD

**Issue by Stephen-Song** [tamagui/tamagui#2313]
### Current Behavior

I would like to ask if tamagui has any plans to support the Table component? It is really urgently needed.
I noticed that there is code related to the table component in the repo, but unfortunately it is encrypted.😭

### Tamagui Version

```markdown
-
```

### Platform (Web, iOS, Android)

```markdown
-
```

### Reproduction

```markdown
-
```

**Comment by TheEhsanSarshar** [comment]
we have that in our pro-components.
it's available for early access now, and will be launched by the end of this month!
if things go well for the Table component we might make it open-source!

**Comment by Stephen-Song** [comment]
> we have that in our pro-components. it's available for early access now, and will be launched by the end of this month! if things go well for the Table component we might make it open-source!

If the table component is released, please comment on this issue, I will be very grateful to you 🥹
