### ISSUE TITLE
Input component does not forward data on nativeEvent

### ISSUE THREAD

**Issue by leononame** [tamagui/tamagui#2321]
### Current Behavior

When you set the `onBlur` callback on the Input component, the type `NativeSyntheticEvent<TextInputFocusEventData>` supposedly contains `event.nativeEvent.text` as a string. However, in tamagui the onBlur event does not contain that property. I debugged the react-native-web TextInput component and the `onBlur` callback never arrives there.

E.g., set the `detail-screen.tsx` in the starter:

```tsx
import { Button, Paragraph, YStack } from '@my/ui'
import { ChevronLeft } from '@tamagui/lucide-icons'
import React from 'react'
import { createParam } from 'solito'
import { useLink } from 'solito/link'
import {Input} from '@my/ui'

const { useParam } = createParam<{ id: string }>()

export function UserDetailScreen() {
  const [id] = useParam('id')
  const link = useLink({
    href: '/',
  })

  return (
    <YStack f={1} jc="center" ai="center" space>
      <Paragraph ta="center" fow="700">{`User ID: ${id}`}</Paragraph>
      <Input onBlur={event=> console.log(event.nativeEvent.text)}/>
      <Button {...link} icon={ChevronLeft}>
        Go Home
      </Button>
    </YStack>
  )
}
```

### Expected Behavior

It should include the text value in the event.

### Tamagui Version

```markdown
1.90.6
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
Clone https://github.com/tamagui/starter-free and apply this patch:


diff --git a/packages/app/features/user/detail-screen.tsx b/packages/app/features/user/detail-screen.tsx
index d3e63fe..2bee491 100644
--- a/packages/app/features/user/detail-screen.tsx
+++ b/packages/app/features/user/detail-screen.tsx
@@ -3,6 +3,7 @@ import { ChevronLeft } from '@tamagui/lucide-icons'
 import React from 'react'
 import { createParam } from 'solito'
 import { useLink } from 'solito/link'
+import {Input} from '@my/ui'

 const { useParam } = createParam<{ id: string }>()

@@ -15,6 +16,7 @@ export function UserDetailScreen() {
   return (
     <YStack f={1} jc="center" ai="center" space>
       <Paragraph ta="center" fow="700">{`User ID: ${id}`}</Paragraph>
+      <Input onBlur={event=> console.log(event.nativeEvent.text)}/>
       <Button {...link} icon={ChevronLeft}>
         Go Home
       </Button>
```

### System Info

```markdown
System:
    OS: Linux 6.7 Fedora Linux 39 (Workstation Edition)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 7.41 GB / 31.09 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.10.0 - /usr/bin/node
    Yarn: 4.1.0 - /usr/bin/yarn
    npm: 10.2.3 - /usr/bin/npm
    Watchman: 0.0.0 - /usr/bin/watchman
  Browsers:
    Firefox: 122.0.1
```

**Comment by TheEhsanSarshar** [comment]
try `onEndEditing` instead.

**Comment by TheEhsanSarshar** [comment]
on web event is what web platform pass to `onBlur`
even on native `e.nativeEvent.text` is not consistent specially when you have `multiline={true}`

**Comment by leononame** [comment]
@TheEhsanSarshar `onBlur` _does_ have `e.nativeEvent.text` set on react-native-web, but tamagui somehow masks that. You can verify that in the codebase of react-native-web [here](https://github.com/necolas/react-native-web/blob/5f9c32eba0f840bde7b462a57d0748358ff866f6/packages/react-native-web/src/exports/TextInput/index.js#L257). I have put an example together [here](https://github.com/leononame/tamagui-issue-2321/blob/main/packages/app/features/user/detail-screen.tsx) as well, you can clone my example repo and execute `yarn dev` in `apps/next` to navigate to the user screen and verify the behavior:
- React Native Web sets the text property on the `onBlur` event
- Tamagui does NOT have the text property
- I have set a breakpoint in Chrome in the React Native Web `onBlur` event and can verify that the RNW onBlur event is never triggered when using the tamagui `Input`, so that event is somehow masked.

The tamagui docs in `Input` state:

> Using the same base component TextInput, from React Native
or React Native Web, Tamagui simply wraps these components to allow the full set of style props, as well as scaling all the styles up or down using the size property, much like Button.

I would argue this means that the actual RNW/RN events are supported as is, plus the typescript definitions also show that the text property should be set on the Input.

Another point: I can't get `onEndEditing` to raise. Neither by using `tab` to focus on a different component, nor by pressing enter. I don't know if this is related to the same underlying issues (somehow masking the events and not passing them down), but that event is not working at all (as is verifiable in the example repo I linked above). I can open a separate issue for onEndEditing if you'd like.

I would really insist this is an issue. Neither `onEndEditing` nor `onBlur` work correctly, and at least for `onBlur` I can verify that it works correctly if I use react-native-web without tamagui. What issues arise when using a multiline? In RNW, `onBlur` works perfectly as a multiline input as well

**Comment by leononame** [comment]
@TheEhsanSarshar @natew Sorry to bother again, I understand you guys are really busy. 
On web,`onEndEditing` just does not fire, but `onBlur` does. However, tamagui does somehow overwrite the event that gets fired from react native web, so the text property is not set. I don't think this is on purpose, because there is no indication of this in the docs. Currently, on web, there is no way to use this component uncontrolled, because we can't get the value out.

**Comment by TheEhsanSarshar** [comment]
ok I'll revisit that today or on weekend
