### ISSUE TITLE
Using src/app as the app folder for Expo Router with Tamagui spams logs

### ISSUE THREAD

**Issue by mhamill2** [tamagui/tamagui#2333]
### Current Behavior

I am setting up a simple project using Expo Router and Tamagui, and I am using src/app/ as the root app directory rather than app/. Whenever I run the app with Expo Go on IOS or Android, the following log message spams infinitely until I stop the app (this only happens when I add the TamaguiProvider): `Using src/app as the root directory for Expo Router`

### Expected Behavior

The log message should not print over and over again. 

### Tamagui Version

```markdown
1.90.6
```

### Platform (Web, iOS, Android)

```markdown
Android and IOS
```

### Reproduction

```markdown
1. Clone the following repository: https://github.com/mhamill2/tamagui-expo-router-bug
2. Run npm i
3. Run npm start
4. Open the app in either an Android or iPhone simulator and see the log spamming

This directory has almost the same configuration as the tamagui expo router starter template, the main difference being that I am not using yarn. I get the same error on the template if I refactor it to use npm instead of yarn, and move the app dir into src/.
```

### System Info

```markdown
System:
    OS: macOS 14.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 479.48 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 21.6.1 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.15.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.184
    Edge: 122.0.2365.52
    Safari: 17.1
  npmPackages:
    @babel/core: ^7.20.0 => 7.23.9 
    @expo/metro-runtime: ^3.1.3 => 3.1.3 
    @tamagui/config: ^1.90.6 => 1.90.7 
    @tamagui/metro-plugin: ^1.90.6 => 1.90.7 
    @types/react: ^18.2.57 => 18.2.58 
    babel-preset-expo: ^10.0.1 => 10.0.1 
    expo: ~50.0.7 => 50.0.7 
    expo-constants: ~15.4.5 => 15.4.5 
    expo-font: ~11.10.3 => 11.10.3 
    expo-linking: ~6.2.2 => 6.2.2 
    expo-router: ~3.4.7 => 3.4.7 
    expo-status-bar: ~1.11.1 => 1.11.1 
    react: 18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-native: 0.73.4 => 0.73.4 
    react-native-safe-area-context: 4.8.2 => 4.8.2 
    react-native-screens: ~3.29.0 => 3.29.0 
    react-native-web: ^0.19.10 => 0.19.10 
    tamagui: ^1.90.6 => 1.90.7 
    typescript: ^5.3.3 => 5.3.3
```

**Comment by natew** [comment]
What's the log? Does it happen when you use yarn?

**Comment by mhamill2** [comment]
> What's the log? Does it happen when you use yarn?

It's in the description, but this is the log message that prints infinitely: `Using src/app as the root directory for Expo Router`

No, it does not happen when I use yarn as it's setup in the expo router template repo. Only when using npm.

**Comment by mhamill2** [comment]
I noticed the log doesn't print if I don't import the tamagui css file, i.e. if I remove the following:

`import '../../tamagui-web.css';`

Not sure why though

**Comment by octopitus** [comment]
@natew It will keep spamming a bunch of things like this:
<img width="428" alt="Screenshot 2024-03-06 at 3 39 10 PM" src="https://github.com/tamagui/tamagui/assets/6346034/45d62a7f-45ef-40df-8321-6a932913f29b">


@mhamill2 if you import the CSS file with a name then the logs will be gone
```ts
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import _styles from '../../tamagui-web.css';
```

**Comment by TheEhsanSarshar** [comment]
@octopitus is it still happening?

**Comment by TheEhsanSarshar** [comment]
try changing `outputCSS: './tamagui-web.css'` in your `metro.config` to `outputCSS: './src/tamagui-web.css'` 
and then import it one level up
```import from '../tamagui-web.css';```

anyway that seems to be an issue related to directory structure and expo-router this one might help https://github.com/expo/router/issues/41 if the problem persists
