### ISSUE TITLE
[Web] Tamagui components don't apply `disabled` prop properly to Button

### ISSUE THREAD

**Issue by arekkubaczkowski** [tamagui/tamagui#2337]
### Current Behavior

I having an issue with applying `disabled` prop to any Tamagui component that implements `tag="button"`.

1. Create following component and render it:
```
const ButtonFrame = View.styleable((props, ref) => (
  <View {...props} ref={ref} disabled tag="button" />
));

<ButtonFrame>Button</ButtonFrame>
```

2. Note that component was render without disabled prop.
It only applies `aria-disabled` which doesn't particularly impacts on default button behaviours.

<img width="737" alt="Screenshot 2024-02-26 at 13 35 46" src="https://github.com/tamagui/tamagui/assets/18654447/26d21082-9af6-45ac-8def-b7f7974094e3">

This issue causes problems with some interactions like navigating by keyboard etc. 

### Tamagui Version

```markdown
"tamagui": "1.90.6"
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
-
```

**Comment by arekkubaczkowski** [comment]
any update on this? is there anything that I can help you with to get this resolved?

**Comment by arekkubaczkowski** [comment]
<img width="816" alt="Screenshot 2024-03-06 at 09 38 49" src="https://github.com/tamagui/tamagui/assets/18654447/b8b1b1fe-2608-4baf-bcda-50c7d71f8ec9">

@TheEhsanSarshar I am still having this issue :(

**Comment by TheEhsanSarshar** [comment]
hmm that's weird, just tested that on Tamagui kitchen-sink and it was working fine
<img width="546" alt="image" src="https://github.com/tamagui/tamagui/assets/46188784/88b942af-53c8-4f9c-99f1-a9f92059e8df">

**Comment by arekkubaczkowski** [comment]
@TheEhsanSarshar  I am suspecting that it might be caused that I having different app configuration than kitchen-sink, is there any chance that it could be related to metro/babel configuration?

**Comment by TheEhsanSarshar** [comment]
I don't think it is something with configuration. see if you can re-produce it with Tamagui starter

**Comment by seanadkinson** [comment]
@byteab I was able to reproduce this issue in the latest tamagui starter.  It looks like if you use a `styled(Button)`, this issue appears.

Steps:
* npm create tamagui, select expo-router template (probably not important which template though)
* Open `CurrentToast.tsx`, and add `disabled` to the Show button on line 38
* Start app, open web, verify Show is properly disabled (cannot be interacted with)
* Add `const MyButton = styled(Button)` component, and change the Show button to use `MyButton`
* Refresh web app, notice that Show button can now be interacted with

Screenshot of `Button`, with working `disabled` property:
<img width="1408" alt="Screenshot 2024-12-05 at 9 58 37 AM" src="https://github.com/user-attachments/assets/189f58b9-dc46-47b8-a65d-3f7fc7fb93fb">

Screenshot of `MyButton`, with absent `disabled` property:
<img width="1408" alt="Screenshot 2024-12-05 at 9 56 11 AM" src="https://github.com/user-attachments/assets/f315bfb5-32ed-4a51-954c-5a4835184128">

Relevant code of non-working button:
```

const MyButton = styled(Button);

export function ToastControl() {
  const toast = useToastController()

  return (
    <YStack gap="$2" ai="center">
      <H4>Toast demo</H4>
      <XStack gap="$2" jc="center">
        <MyButton
          disabled
          onPress={() => {
            toast.show('Successfully saved!', {
              message: "Don't worry, we've got your data.",
            })
          }}
        >
          Show
        </MyButton>
        <Button
          onPress={() => {
            toast.hide()
          }}
        >
          Hide
        </Button>
      </XStack>
    </YStack>
  )
}
```

Can we reopen issue?  Or let me know if opening a new issue would be better.

**Comment by maxgenest** [comment]
I have the same issue with any tamagui component. Can we reopen the issue please ? Or tell me if a solution exists

**Comment by sebak94** [comment]
Same here
