### ISSUE TITLE
Image width and height props not working

### ISSUE THREAD

**Issue by coycoylaniba** [tamagui/tamagui#2358]
### Current Behavior

width and height props not working on Image component

### Expected Behavior

should work

### Tamagui Version

```markdown
1.90.13
```

### Platform (Web, iOS, Android)

```markdown
android
```

### Reproduction

```markdown
import { Image, View } from "tamagui";

const Root = () => {
  return (
    <View flex={1}>
      <Image
        source={require("~/assets/images/logo.png")}
        alt="logo"
        w="50%"
        aspectRatio={1}
      />
    </View>
  );
};

export default Root;
```

### System Info

```markdown
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
    Memory: 693.43 MB / 13.94 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.2 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.52)
    Internet Explorer: 11.0.22621.1
```

**Comment by tomashco** [comment]
I did some test and found out that using import { Image } from 'react-native' the prop width and height is not working either.

So my workaround by now has been to:

```
import { Image } from 'react-native'

<Image
            source={require('./facebook.png')}
            style={{ width: 20, height: 20 }} // this is actually working
            //   height={20} // not working either on react-native nor tamagui
            //   width={20}
          />
```

Hope this can help better understand what is the issue, but so far it seems related to react-native, not Tamagui

**Comment by floyddeadshot** [comment]
Same here. @natew insights about this?

**Comment by TheEhsanSarshar** [comment]
is that an issue only on Android?
it's working fine on ios

**Comment by TheEhsanSarshar** [comment]
weird! Android is working fine for me

**Comment by TheEhsanSarshar** [comment]
as I wasn't able to re-produce it anymore I assume it's fixed!
I'll close it for now, let me know if it still happens for you to reopen

**Comment by csulit** [comment]
I'm having an issue where an image is not displaying in my React Native app, but it is showing up in my web application built with Next.js.

**Comment by Martinnord** [comment]
If you have the styles prop it overrides the custom height / width,
```ts
<Image
  source={{
    uri: require("../../assets/images/apple.png"),
    width: 20,
    height: 20,
  }}
  width={20}
  height={20}
  // style={{ tintColor: "white" } as any}
/>
```

I'm on version `1.120.2`
