### ISSUE TITLE
Typescript error when using dynamic variant

### ISSUE THREAD

**Issue by davidavz** [tamagui/tamagui#2360]
### Current Behavior

Using dynamic variant I'm trying to access my props argument but I get a TS error `error TS2339: Property 'blue' does not exist on type 'Partial<GetFinalProps<RNTamaguiViewNonStyleProps, StackStyleBase, { elevation?: number | SizeTokens; fullscreen?: boolean; inset?: number | SizeTokens | Insets; }>>'`

### Expected Behavior

I should be able to access to my props in a dynamic variant (ithout TS error)

### Tamagui Version

```markdown
^1.90.15
```

### Platform (Web, iOS, Android)

```markdown
Web, iOS, Android
```

### Reproduction

```markdown
I have forked the starter free repo : https://github.com/davidavz/starter-free
Here is the issue : https://github.com/davidavz/starter-free/commit/aea24d239160ef5308b1ce98fa93549b051dbbc7
```

**Comment by arekkubaczkowski** [comment]
As per documentation likely you need to create a stylable wrapper with custom types provided
https://tamagui.dev/docs/core/styled#styleable
<img width="822" alt="Screenshot 2024-03-01 at 09 15 30" src="https://github.com/tamagui/tamagui/assets/18654447/ccfb1cf1-2a13-49ac-a78c-af4974a2678f">

**Comment by arekkubaczkowski** [comment]
However I don't like it as it requires a lot of biolerplate everytime I want to add a custom types to styled components. I hope there will be some better way to achieve this

**Comment by davidavz** [comment]
Oh, I didn't see this part of the documentation

It's a little bit tricky when it comes to play with `createStyledContext` 😄 

But it works for me now, thanks a lot!

**Comment by martijnmichel** [comment]
@davidavz how did you resolve this with createStyledContext? I can't get it to work ;/

**Comment by davidavz** [comment]
> @davidavz how did you resolve this with createStyledContext? I can't get it to work ;/

Here is the solution to my problem https://github.com/davidavz/starter-free/commit/0d6a2d2d1ab93b81c4a3881dba7bde2bb01151ae
