### ISSUE TITLE
src props of Avatar doesn't work as expected

### ISSUE THREAD

**Issue by guoqikai** [tamagui/tamagui#2365]
### Current Behavior

When passing url through the src prop, the image is always blank.

### Expected Behavior

Image should load

### Tamagui Version

```markdown
1.90.12
```

### Platform (Web, iOS, Android)

```markdown
iOS, Android
```

### Reproduction

```markdown
import { Avatar } from 'tamagui'

export default () => (
  <Avatar circular size="$6">
    <Avatar.Image src="http://placekitten.com/200/300" />
    <Avatar.Fallback bc="red" />
  </Avatar>
)
```

**Comment by TheEhsanSarshar** [comment]
I'm not able to re-produce

**Comment by guoqikai** [comment]
@TheEhsanSarshar Seems like it's an issue with the Image component in this library. There's also an issue when I try to load an image with file protocol:
`
<Image flex={1} source={{ uri: fileUrl }} />
`
This will show nothing. While changing the Image component to the native one fix the problem

**Comment by TheEhsanSarshar** [comment]
emmm, just tested and it seems working fine

**Comment by TheEhsanSarshar** [comment]
emmm, just tested and it seems working fine

**Comment by guoqikai** [comment]
@TheEhsanSarshar Hmm interesting i'll investigate further and get back to you. I'm pretty sure all these issues happen after I upgrade tamagui version tho

**Comment by StefanEissler** [comment]
I face the same issue in the monorepo. I did not check native, but in nextjs it is showing up in the html file but not rendering the picture. 

I read a picture with https://... With the normal <Image /> Tag it works fine.

```
<Avatar circular size="$5">
                        <Avatar.Image
                            src={profile?.avatar_url}
                        />
                        <Avatar.Fallback backgroundColor="$blue10" delayMs={600} />
</Avatar>
```

**Comment by guoqikai** [comment]
@TheEhsanSarshar I tried the example with https and it still doesn't work. Using the source prop with width and height set works(e.g. `<Image source={{width: 50, heigh:50, uri}}/>`). But both width and height must be set to a non-zero value and it's bit awkward as we don't know the image demission in most of the time. The issue can be reproduced on both Android and ios so I doubt it's related to http/https.

**Comment by StefanEissler** [comment]
I don´t know if the information helps. But when I remove the class in the  tag the picture shows up.
Otherwise it is not working for me.

`
<div class="is_Avatar _dsp-flex _ai-center _fd-column _fb-auto _bxs-border-box _pos-relative _mih-1611761883 _miw-1611761883 _fs-0 _jc-center _ox-hidden _oy-hidden _w-1611761883 _h-1611761883 _maw-1611761883 _mah-1611761883 _btlr-100000px _btrr-100000px _bbrr-100000px _bblr-100000px _pt-0px _pr-0px _pb-0px _pl-0px">
    <div class="_dsp-flex _ai-stretch _fd-column _fb-auto _bxs-border-box _pos-absolute _mih-0px _miw-0px _fs-0 _t-0px _l-0px _r-0px _b-0px _zi-1">
        <span class="_dsp_contents">
            <div class="css-view-175oi2r r-flexBasis-1mlwlqe r-overflow-1udh08x r-zIndex-417010 52px 52px is_Image ">
                <div class="css-view-175oi2r r-backgroundColor-1niwhzg r-backgroundPosition-vvn4in r-backgroundRepeat-u6sd8q r-bottom-1p0dtai r-height-1pi2tsx r-left-1d2f490 r-position-u8s1d r-right-zchlnj r-top-ipm5af r-width-13qz1uu r-zIndex-1wyyakw r-backgroundSize-4gszlv" style="background-image: url(&quot;https://mbddwyllcycsqyuinbvq.supabase.co/storage/v1/object/sign/avatars/MKS00155.JPG?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJhdmF0YXJzL01LUzAwMTU1LkpQRyIsImlhdCI6MTcwOTk5ODMxMSwiZXhwIjozMjg2Nzk4MzExfQ.XjSmpVLjxIsLtWSji7rJ-_PdQ_bku7AWqsrueMVhEqc&amp;t=2024-03-09T15%3A31%3A49.138Z&quot;);"></div>
                <img alt="" draggable="false" src="https://mbddwyllcycsqyuinbvq.supabase.co/storage/v1/object/sign/avatars/MKS00155.JPG?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJhdmF0YXJzL01LUzAwMTU1LkpQRyIsImlhdCI6MTcwOTk5ODMxMSwiZXhwIjozMjg2Nzk4MzExfQ.XjSmpVLjxIsLtWSji7rJ-_PdQ_bku7AWqsrueMVhEqc&amp;t=2024-03-09T15%3A31%3A49.138Z" class="css-accessibilityImage-9pa8cd">
            </div>
        </span>
    </div>
</div>

`

**Comment by StefanEissler** [comment]
Are there any news on this?
I meet this issue in web nextjs version.
I have tried to reinstall tamagui. I added the package for Avatars to my packages. 

<div class="is_Avatar _dsp-flex _ai-center _fd-column _fb-auto _bxs-border-box _pos-relative _mih-1611761883 _miw-1611761883 _fs-0 _jc-center _ox-hidden _oy-hidden _w-1611761883 _h-1611761883 _maw-1611761883 _mah-1611761883 _btlr-100000px _btrr-100000px _bbrr-100000px _bblr-100000px _pt-0px _pr-0px _pb-0px _pl-0px"><div class="_dsp-flex _ai-stretch _fd-column _fb-auto _bxs-border-box _pos-absolute _mih-0px _miw-0px _fs-0 _t-0px _l-0px _r-0px _b-0px _zi-1"><span class="_dsp_contents"><div class="css-view-175oi2r r-flexBasis-1mlwlqe r-overflow-1udh08x r-zIndex-417010 52px 52px is_Image "><div class="css-view-175oi2r r-backgroundColor-1niwhzg r-backgroundPosition-vvn4in r-backgroundRepeat-u6sd8q r-bottom-1p0dtai r-height-1pi2tsx r-left-1d2f490 r-position-u8s1d r-right-zchlnj r-top-ipm5af r-width-13qz1uu r-zIndex-1wyyakw r-backgroundSize-4gszlv" style="background-image: url(&quot;https://url;);"></div><img alt="" draggable="false" src="https://url" class="css-accessibilityImage-9pa8cd"></div></span></div></div>


When I remove the class of the <img> Tag it works...

**Comment by anonsyn** [comment]
Same issues here, I meet this issue in ios
