### ISSUE TITLE
forceStyle is not working

### ISSUE THREAD

**Issue by arekkubaczkowski** [tamagui/tamagui#2396]
### Current Behavior

Providing forceStyle prop to any tamagui components which implements pseudo styles doesn't force them to be rendered.

1. create a component with pseudo styles specified
```tsx
const Example = styled(View, {
  name: 'Button',
  tag: 'button',
  width: 200,
  height: 50,
  backgroundColor: 'red',
  hoverStyle: {
    backgroundColor: 'blue',
  },
  focusStyle: {
    backgroundColor: 'orange',
  },
  focusVisibleStyle: {
    backgroundColor: 'green',
  },
  pressStyle: {
    backgroundColor: 'yellow',
  },
});
```
2. Render it with various states
```tsx
<Example forceStyle='focus' />
<Example forceStyle='hover' />
<Example forceStyle='press' />
```
3. See that nothing has changed.
4. Another issue is that `focusVisibleStyle` is missing in `forceStyle`. It should be available explicitly or activated along with `forceStyle: focus`

### Tamagui Version

```markdown
1.91.3
```

### Platform (Web, iOS, Android)

```markdown
web, ios, android
```

### Reproduction

```markdown
-
```

**Comment by TheEhsanSarshar** [comment]
pushed a fix for focusVisible
btw able to reproduce! three of them have that forced style on initial render

**Comment by arekkubaczkowski** [comment]
It seems like this issue must be related to a configuration setting... It's strange that neither the 'forceStyle' nor 'disabled' props are working on my end. 
@TheEhsanSarshar could you please take a look at my config whether you see any possible cause https://github.com/tamagui/tamagui/issues/2411?

**Comment by TheEhsanSarshar** [comment]
is this issue still happening @arekkubaczkowski

**Comment by arekkubaczkowski** [comment]
@TheEhsanSarshar no, still happens unfortunately. I am using the latest version of the app

**Comment by TheEhsanSarshar** [comment]
is it possible to create a re-production with tamagui starter

**Comment by cmpickle** [comment]
I am seeing this same problem. I am able to reproduce it with the starter by creating a styled() Tamagui button and then that button is not able to set the `forceStyle` prop but I am able to set it for the button directly from 'tamagui`.
