### ISSUE TITLE
About the plan (question 

### ISSUE THREAD

**Issue by bang88** [tamagui/tamagui#240]
Hello @natew.

What's your plan for the next stable release, I want to do some contribution if time free.

By the way could we add a react-native example?

Thank  you.

**Comment by natew** [comment]
Stable release there are just a few bigger outstanding bugs and more smaller. 

next.md has very short notes on some of them. 

Windows fixes, general Testing coverage and CI need improvement, and then after release many things, performance, features and components. Happy to accept PR for any.
