### ISSUE TITLE
React Native Expo Only ?

### ISSUE THREAD

**Issue by greeedy-b** [tamagui/tamagui#2403]
Hello, I am using React Native CLI for develop.

Can you explain it, how to use in React Native cli project ?

Thanks in advance :)

**Comment by fr0staman** [comment]
You can use tamagui with React Native CLI, like in my example:
https://github.com/fr0staman/tamagui-react-native-i18next-zustand-starter

**Comment by greeedy-b** [comment]
> You can use tamagui with React Native CLI, like in my example: https://github.com/fr0staman/tamagui-react-native-i18next-zustand-starter

Thanks for reply.
I'll try it :)
