### ISSUE TITLE
getTokens returns undefined

### ISSUE THREAD

**Issue by junedomingo** [tamagui/tamagui#241]
**Describe the bug**

Upgraded to version *beta.181*

```
const tokens = getTokens();

console.log(tokens.color.black1) // undefined
```

while in the previous version, you can get the value like this 
```
console.log(tokens.color.$black1.val.toString()) // # 101817
```

or am I missing something?

Thanks!

**Comment by natew** [comment]
@dohomi I'm testing in the sandbox (and on the site in places) and I don't see that:

<img width="724" alt="image" src="https://user-images.githubusercontent.com/12100/193227007-3542ef1f-f511-4e7b-bc03-5dd9517287d7.png">

This means you are calling that before you call `createTamagui`, which must be at the very top of your app tree and imported early somewhere.

**Comment by dohomi** [comment]
@natew I made a strange mistake inside my mono repo requiring a wrong package version. Everything works as expected
