### ISSUE TITLE
Separator's borderColor are different on the native side.

### ISSUE THREAD

**Issue by bang88** [tamagui/tamagui#242]
<img width="2004" alt="image" src="https://user-images.githubusercontent.com/433259/193190025-41cd9c00-cdb9-4209-9de0-49262df03945.png">

**Comment by bang88** [comment]
The borderColor defined in themes is #232323, but on the native side it changed to 'rgba(232,232,232,1)'.

> splitStyles:Separator 


`
{"classNames": {}, "fontFamily": undefined, "mediaKeys": [], "medias": {}, "pseudos": {}, "rulesToInsert": [], "style": {"alignItems": "stretch", "borderBottomColor": "rgba(232,232,232,1.00)", "borderBottomStyle": "solid", "borderBottomWidth": 1, "borderLeftColor": "rgba(232,232,232,1.00)", "borderLeftWidth": 0, "borderRightColor": "rgba(232,232,232,1.00)", "borderRightWidth": 0, "borderTopColor": "rgba(232,232,232,1.00)", "borderTopWidth": 0, "flex": 1, "flexDirection": "column", "flexShrink": 0, "height": 0, "maxHeight": 0, "transform": [[Object]]}, "viewProps": {}}
`

**Comment by natew** [comment]
Should be fixed in 204, re-open if not
