### ISSUE TITLE
Unable to directly use Tamagui colors for styling with React Native components

### ISSUE THREAD

**Issue by annak1104** [tamagui/tamagui#2430]
### Current Behavior

Currently, it's not possible to directly use predefined Tamagui colors (like '$blue4') for styling properties like backgroundColor in React Native Components. Attempting to do so results in the color being treated as a string instead of resolving to the actual color value.

### Expected Behavior

I expected that this code would work. And the colors would be set according to the conditions:
**if (labelBackgroundColor !== undefined) {
  return labelBackgroundColor || '$blue5'; 
} else {
  return '$blue5';
}**

Instead of the code working, it is necessary to do it like this:
  **const theme = useTheme();**

**if (labelBackgroundColor !== undefined) {
        return theme[labelBackgroundColor]?.val || theme['$blue5']?.val;
      } else {
        return theme['$blue5']?.val;
      }**
      
      
      Сomponent:
      
         <TextInput
              formik={formik}
              name="phone"
              id="phone"
              testID="test-edit-profile-phone"
              returnKeyType="next"
              label={t('settings.editProfile.form.fields.phone')}
              enterKeyHint="next"
              **labelBackgroundColor="$blue4"**
            />

### Tamagui Version

```markdown
1.79.0
```

### Platform (Web, iOS, Android)

```markdown
Web, iOS, Android
```

### Reproduction

```markdown
https://prnt.sc/xAKXeXU7xjIX

Please, check the link. 
As you can see labelBackgroundColor does not work
```

### System Info

```markdown
--npmPackages
```

**Comment by TheEhsanSarshar** [comment]
Those color tokens are for Tamagui components, you can either use Tamagui Input or wrap your component with `styled` to make it accept tamagui props or there are some helper hooks like `usePropsStyle()` that takes Tamagui props and return react native props.

using `styled()`
```const MyInput = styled(TextInput)```
now Tamagui props will be pass to `TextInput` `style` prop internally, for custom props like `labelBackgroundColor` you need to define it in styled.

```
const MyInput = styled(
  Input,
  {},
  {
    accept: {
      labelBackgroundColor: 'color',
    },
  }
)
```
now `labelBackgroundColor` can accept any color token
