### ISSUE TITLE
Popover not anchoring properly to the trigger on web

### ISSUE THREAD

**Issue by filipebotti** [tamagui/tamagui#2446]
### Current Behavior

When the popover is opened, the position does not update when you scroll the window.

 It seems the trigger ref is not set correctly on the first render. If a re-render occurs, it works as expected.
 

https://github.com/tamagui/tamagui/assets/14228463/928dbc81-54bf-427a-aec9-3304a6be2162

### Expected Behavior

The Popover is anchored properly on first render.

### Tamagui Version

```markdown
Working on: 1.79.7
Broken on: ^1.91.4
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://github.com/filipebotti/popover-anchor
```

### System Info

```markdown
System:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M1
    Memory: 106.31 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 4.1.0 - /opt/homebrew/bin/yarn
    npm: 10.3.0 - ~/.nvm/versions/node/v18.18.2/bin/npm
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.3
```

**Comment by TheEhsanSarshar** [comment]
try adding `Popover.Arrow`

**Comment by filipebotti** [comment]
It worked. Thanks for helping!
