### ISSUE TITLE
tamagui suport RTL ???

### ISSUE THREAD

**Issue by ikaaasra** [tamagui/tamagui#2447]
SWITCH Component does not support RTL 

### Tamagui Version

```markdown
1.91
```

### Platform (Web, iOS, Android)

```markdown
Native
```

**Comment by TheEhsanSarshar** [comment]
what is your expected behavior? 
it seems working fine for me tho

**Comment by i1kaaasra** [comment]
it does not work for SWITCH Component

**Comment by TheEhsanSarshar** [comment]
I mean I tested that on Switch and it looks ok, do you see any specific issue

**Comment by TheEhsanSarshar** [comment]
ah I think that one is because of Moti driver, try to use react native animated driver instead of moti
you can change that in your `tamagui.config.ts`

**Comment by Ammar1999y** [comment]
> ah I think that one is because of Moti driver, try to use react native animated driver instead of moti you can change that in your `tamagui.config.ts`

```
import { config } from "@tamagui/config/v3";
import { createTamagui } from "tamagui";
import { createAnimations } from "@tamagui/animations-react-native";

const appConfig = createTamagui({
  ...config,
  animations: createAnimations({
    bouncy: {
      type: "spring",
      damping: 10,
      mass: 0.9,
      stiffness: 100,
    },
    lazy: {
      type: "spring",
      damping: 20,
      stiffness: 60,
    },
    quick: {
      type: "spring",
      damping: 20,
      mass: 1.2,
      stiffness: 250,
    },
  }),
});

export default appConfig;
```

i tried to use react native animated, but still the switch not working correctly, Did I do something wrong?
