### ISSUE TITLE
Tamagui create with vite/webpack misses expo-linear-gradient package

### ISSUE THREAD

**Issue by joernroeder** [tamagui/tamagui#2448]
### Current Behavior

A fresh installation of the "vite / webpack" template via the cli 1.91.4 fails. Running `yarn dev` or `yarn dev:vite` results in: 

```
✘ [ERROR] Could not resolve "expo-linear-gradient"

    node_modules/@tamagui/linear-gradient/dist/esm/linear-gradient.mjs:1:31:
      1 │ import { LinearGradient } from "expo-linear-gradient";
```

### Tamagui Version

```markdown
1.91.4
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
1. npm create tamagui
2. choose the "learn vite/webpack" template
3. run `yarn dev` or `yarn dev:vite`
4. see the missing dependency
```

**Comment by joernroeder** [comment]
adding `expo-linear-gradient` to deps myself fixes the issue, is this a package manager issue? I'm running yarn 1.22.21

**Comment by joernroeder** [comment]
`yarn dev:vite:extract` fails with 

```
Error: File 'expo-module-scripts/tsconfig.base' not found.
```

probably similar deps issue

**Comment by bnussman** [comment]
I'm also seeing this. I swear Tamagaui used to not try to import react native code when in Vite, but now it's importing `react-native` and `expo-linear-gradient`

**Comment by TheEhsanSarshar** [comment]
That error is because in `./Root.tsx` there is a usage of `LinearGradient`. so you need to install that manually
https://tamagui.dev/ui/linear-gradient
