### ISSUE TITLE
FlatList Error Cannot convert object to primitive value

### ISSUE THREAD

**Issue by apperside** [tamagui/tamagui#245]
**Describe the bug**
Although I can use everything from react-native in the NextJS app (View, Text, Button ecc), when I try to render a FlatList in the NextJS app, it crashes with the following error:

`Uncaught TypeError: can't convert Proxy to string: its [Symbol.toPrimitive] method returned an object`

The problem is very easily reproductibile:
1- create a new app with `npm create tamagui-app@latest`, add an empty FlatList like this

```jsx
<FlatList
  data={[]}
  showsVerticalScrollIndicator={false}
  renderItem={() => <YStack />}
/>
```

2- start the app with `npm run web` or `yarn web`

3- navigate with the browser to localhost:3000, you will see the error

4- remove the `FlatList` component and see the error disappear

**Comment by natew** [comment]
This is due to config `excludeReactNativeWebExports` which removes it to save bundle size.

If we switch to react-native-web-lite this all goes away :)

I'll look at adding a small warning.

**Comment by apperside** [comment]
I removed `FlatList` and `VirtualizedList` (it's important to also remove the latter because `FlatList` extends from it) and the error is gone, thank you for the tip! In the meanwhile, searching for alternatives I think I'm gonna try this https://shopify.github.io/flash-list/.

For the future readers who want to try it as well, in order to make it working on the web side, you have to slightly change your next.config.js file:

<img width="426" alt="Screenshot 2022-10-02 at 09 20 19" src="https://user-images.githubusercontent.com/5955338/193442819-77ccf3ba-193a-4ec3-9020-61dccfa0da7c.png">

**Comment by natew** [comment]
Try the useReactNativeWebLite as well, though I need to test more thoroughly with reanimated.
