### ISSUE TITLE
useMedia hook not working properly

### ISSUE THREAD

**Issue by apperside** [tamagui/tamagui#246]
Hello,
I am trying to use `useMedia` hook, but it seem to me it returns non properly valorized fields:

This is what I get on my desktop pc

```json
{
  "xs": false,
  "sm": false,
  "md": false,
  "lg": false,
  "xl": false,
  "xxl": false,
  "gtXs": true,
  "gtSm": true,
  "gtMd": true,
  "gtLg": true,
  "short": false,
  "tall": true,
  "hoverNone": false,
  "pointerCoarse": false
}

```

Non of the exact breakpoints (xs, sm, md, lg, xl, xxl) is true in this case

This is instead what is returned in iPhone 14 simulator

```json
{
  "xs": false,
  "sm": false,
  "md": false,
  "lg": false,
  "xl": false,
  "xxl": false,
  "gtXs": false,
  "gtSm": false,
  "gtMd": false,
  "gtLg": false,
  "short": false,
  "tall": false,
  "hoverNone": false,
  "pointerCoarse": false
}
```

In this case all values are false.

**Tamagui version**
`1.0.1-beta.184`

**System Info (please complete the following information):** 

  System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 282.38 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 3.2.0 - ~/dev/nx/foodelix-frontend/node_modules/.bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 105.0.1
    Safari: 16.0

**Comment by natew** [comment]
Working for me on simulator / chrome. Can you `npm create tamagui-app` and get a repro from there on a repo for me?

<img width="632" alt="image" src="https://user-images.githubusercontent.com/12100/193428046-ffac9186-557d-4a99-ba05-889e75cb7bc2.png">

**Comment by apperside** [comment]
Hello @natew ,
on a fresh project it doesn't replicate, I just found the issue in the project I'm working on and din't tried on fresh project because I don't think I doing anything special that could affect the viewport calculation, but I guess I'll need to dig deep in the code to undertand what it causing it

**Comment by natew** [comment]
Feel free to re-open if it’s legit on Tamagui side.

**Comment by usamaehsan** [comment]
@apperside have you found any solution?
i am getting true for all:
{xl: true, lg: true, md: true, sm: true, xs: true}

**Comment by apperside** [comment]
@usamaehsan actually this hook is working pretty well for me now, since a lot of releases ago, I don't remember what was the isse for me, the only thing I can suggest you is to try to make sure that your theme setup is correct
