### ISSUE TITLE
Documentation now returning 404 for all UI components from Bing/likely Google

### ISSUE THREAD

**Issue by zaptrem** [tamagui/tamagui#2467]
### Current Behavior

Documentation now returning 404 for all UI components from Bing/likely Google

### Expected Behavior

Documentation should not be returning 404 for all UI components from Bing/likely Google

### Tamagui Version

```markdown
n/a
```

### Platform (Web, iOS, Android)

```markdown
Bing
```

### Reproduction

```markdown
Bing/Google "Tamagui TextInput", click the link
```

**Comment by zaptrem** [comment]
any https://tamagui.dev/docs/components/ link now returns 404

**Comment by TheEhsanSarshar** [comment]
components are moved to `/ui` route 

https://tamagui.dev/ui/intro/1.0.0
maybe take a day for google to index it ?
