### ISSUE TITLE
No units for lineHeight after Next.js build

### ISSUE THREAD

**Issue by misterioss** [tamagui/tamagui#2468]
### Current Behavior

The code: 
```
<Text style={{lineHeight: 24}}>
          Here is a text!
 </Text>
```

Produces  HTML:
`
<span data-at="screen.tsx:36" data-in="HomeScreen" data-is="Text" class="font_body _ff-299667014 _dsp-inline _bxs-border-box _ww-break-word _whiteSpace-pre-wrap _mt-0px _mr-0px _mb-0px _ml-0px _col-675002279" style="line-height:24">Here is a text!</span>
`
**line-height:24**

![CleanShot 2024-03-23 at 13 42 48@2x](https://github.com/tamagui/tamagui/assets/3921977/74a4d242-5bcd-4373-a6e6-ddb715043668)

### Expected Behavior

Add units (px) for lineHeight after `next build`:
line-height:24px

### Tamagui Version

```markdown
^1.92.1
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://github.com/misterioss/tamagui_bug_report
```

### System Info

```markdown
System:
    OS: macOS 14.4
    CPU: (12) arm64 Apple M2 Pro
    Memory: 97.39 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.14.2 - ~/.local/share/nvm/v18.14.2/bin/node
    Yarn: 4.1.0 - ~/.local/share/nvm/v18.14.2/bin/yarn
    npm: 9.5.0 - ~/.local/share/nvm/v18.14.2/bin/npm
  Browsers:
    Chrome: 123.0.6312.58
    Safari: 17.4
```

**Comment by TheEhsanSarshar** [comment]
there is no need to use `style` prop here. you can pass `lineHeight` directly
```tsx
<Text lineHeight={24}>
          Here is a text!
 </Text>
 ```
 this will work for both dev and prod.
 yeah the style one seems broken, I'll take a look. but using inline prop will fix that issue
