### ISSUE TITLE
Hydration issue when forcing teme

### ISSUE THREAD

**Issue by kzlar** [tamagui/tamagui#2479]
### Current Behavior

If the following holds true:

1. Your system (or preferred) theme is `light`
2. You force a theme, i.e. `<Theme name='dark'>`
(or conversely, 1 as `light` and 2 as `dark`)

There is an hydration issue due to an additional span being added after hydration `<span class="t_light is_inversed _dsp_contents">`

Note that you may need to force the local theme to see this:
<img width="433" alt="image" src="https://github.com/tamagui/tamagui/assets/120426485/16d6822d-a388-4f01-94f8-067e91f3783a">

### Expected Behavior

No hydration issue

### Tamagui Version

```markdown
1.93.2
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
https://github.com/tamagui/tamagui/compare/master...kzlar:tamagui:repro/theme_hydration_issue
```

**Comment by antoniopresto** [comment]
It also happens without changing the theme.
The tamagui site itself is also rendered inside a `span`

<img width="1116" alt="image" src="https://github.com/user-attachments/assets/3a3cd591-a4ac-4c0d-9ab9-0d05f4d9b1ef">

**Comment by antoniopresto** [comment]
Hmm, I found it: https://github.com/tamagui/tamagui/blob/9648cbf67b32befad3bbba49d6a506404eb167f2/code/core/web/src/views/TamaguiProvider.tsx#L62-L78

**Comment by antoniopresto** [comment]
Using this for now:

```tsx
// HOTFIX for https://github.com/tamagui/tamagui/issues/2479
function cloneAndUnwrapSpan(element: ReactElement): ReactElement {
  const processElement = (el: React.ReactNode): React.ReactNode => {
    if (!isValidElement(el)) {
      return el;
    }

    if (el.type === 'span') {
      return <React.Fragment>{el.props.children}</React.Fragment>;
    }

    return React.cloneElement(el, el.props, processChildren(el.props.children));
  };

  const processChildren = (children: React.ReactNode): React.ReactNode => {
    return Children.map(children, (child) => processElement(child));
  };

  return processElement(element) as ReactElement;
}

export function ThemeProvider(props: PropsWithChildren) {
  const { children } = props;

//...

  return cloneAndUnwrapSpan(
    <ThemaguiProvider disableInjectCSS>
      {children}
    </ThemaguiProvider>,
  );
}
```

**Comment by brayanobisto** [comment]
> Hmm, I found it:
> 
> https://github.com/tamagui/tamagui/blob/9648cbf67b32befad3bbba49d6a506404eb167f2/code/core/web/src/views/TamaguiProvider.tsx#L62-L78

Could this be causing this error?

![image](https://github.com/user-attachments/assets/d867effb-759e-47a4-88ee-32641a8e80fd)

**Comment by RichardTunstall** [comment]
Try adding the property `forceClassName` to the Theme component, e.g. `<Theme name="dark" forceClassName></Theme>`

**Comment by natew** [comment]
Lmk if still an issue, we landed some improvements here.
