### ISSUE TITLE
`noTextWrap` prop on ListItem does not work

### ISSUE THREAD

**Issue by shahidcodes** [tamagui/tamagui#248]
**Describe the bug**
The list item wraps the text and setting `noWrapText` has no effect on it

**To Reproduce**
```screen.tsx


import { H1, ListItem, Paragraph, Separator, Text, YGroup, YStack } from '@my/ui'
import { ChevronRight, Moon, Star } from '@tamagui/feather-icons'
import React, { useState } from 'react'
import { useLink } from 'solito/link'

const duas = [
  {
    name: 'A very long long text that wraps',
    how_to: 'Recite after every salah',
    arabic_text:
      'رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً ۚ إِنَّكَ أَنتَ ٱلْوَهَّابُ ٨',
    translation:
      '˹They say,˺ “Our Lord! Do not let our hearts deviate after you have guided us. Grant us Your mercy. You are indeed the Giver ˹of all bounties˺.',
    transliteration:
      ' rabbanā lā tuzigh qulūbanā baʿda idh hadaytanā wahab lanā min ladunka raḥmatan innaka anta l-wahāb',
    id: 0,
  },
]

export function HomeScreen() {
  const [duaId, setDuaId] = useState<number | undefined>()
  const linkProps = useLink({
    href: `/dua/${duaId ?? ''}`,
  })

  return (
    <YStack f={1} jc="flex-start" ai="center" p="$4" space mt="$5">
      <YStack space="$4" maw={600}>
        <H1 ta="center">Cures from Glorious Quran</H1>
      </YStack>
      <YGroup als="center" bordered size="$5" mt="$5" separator={<Separator />}>
        {duas.map((dua) => {
          return (
            <ListItem
              key={`dua-${dua.id}`}
              hoverTheme
              pressTheme
              size="$14"
              title={<Paragraph>{dua.name}</Paragraph>}
              subTitle={dua.arabic_text}
              icon={Moon}
              iconAfter={ChevronRight}
              onPress={() => {
                setDuaId(0)
              }}
              noTextWrap
            />
          )
        })}
      </YGroup>
    </YStack>
  )
}


```

**Screenshot**
<img width="414" alt="image" src="https://user-images.githubusercontent.com/17620737/193423747-878dc6ef-c2cf-4f7c-af87-e07e9ce7702a.png">

**System Info (please complete the following information):** 
  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 2.04 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 105.0.1
    Safari: 16.0

**Comment by natew** [comment]
`noTextWrap` came from Button which has no title/subtitle so it only applies to the "children" property for now. It's interesting case though, maybe I'll just `noTextWrap="all"` for backwards compat? It's a weird property, I'd like to prefer composable style in the future which we can migrate to.
