### ISSUE TITLE
<Input /> element doesn't pass through the name prop.

### ISSUE THREAD

**Issue by kennetpostigo** [tamagui/tamagui#2495]
### Current Behavior

Hi i've tried both Input from tamagui and TextInput from react-native to pass the name prop through but in both they don't show up or get passed in. This causes FormActions from Next.js to not work because Input elements without `name` don't get registered in form-actions, only way to do so is for name props to be present.

### Expected Behavior

Expected behavior is for the passed in name prop to be passed into and rendered in the HTML.

### Tamagui Version

```markdown
I was on `latest`
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
import {Input} from 'tamagui';

export const Example = () =>  <Input name="test" />;
```

**Comment by kennetpostigo** [comment]
This can also apply to other form elements as well like Select

**Comment by natew** [comment]
We rely on react native web right now so this is what we have, but Input is up next to be rewritten ourselves, after the Image rewrite PR goes in.
