### ISSUE TITLE
How do I use Groups?

### ISSUE THREAD

**Issue by EdwardDrapkin** [tamagui/tamagui#2497]
I'm trying to use groups, but every time I do, I get a TS error about GroupNames being undefined.

The TS type is declared like so:

```ts

export interface TypeOverride {
  groupNames(): 1
}

export type GroupNames = ReturnType<TypeOverride['groupNames']> extends 1
  ? never
  : ReturnType<TypeOverride['groupNames']>

```

So clearly I'm supposed to do _something_ so that GroupNames is not always undefined, but I can find no documentation.

**Comment by TheEhsanSarshar** [comment]
you need to add this to your tamagui config type
```
declare module 'tamagui' {
  interface TamaguiCustomConfig extends AppConfig {}

  // if you want types for group styling props, define them like so:
  interface TypeOverride {
    groupNames(): 'a' | 'b' | 'c'
  }
}
```
reading doc will help know more about groups
https://tamagui.dev/docs/intro/styles#group
