### ISSUE TITLE
Alpha values for color tokens

### ISSUE THREAD

**Issue by bo-union** [tamagui/tamagui#2502]
### Current Behavior

const tokens = createTokens({
  ...config.tokens,
  color: {
    ...config.tokens.color,
    primary_100_alpha_10: '#CFD3FE1A',
    primary_100_alpha_20: '#CFD3FE33',
  },
});

<Input
      backgroundColor="$primary_100_alpha_20"
      borderColor="$primary_100_alpha_20"
    />

When I have a color token with an alpha value, the color is not displayed

### Expected Behavior

I want colors with alpha values to be shown.

I mainly want to know how to use colors with alpha values as tokens for tamagui components

### Tamagui Version

```markdown
1.76
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
const tokens = createTokens({
  ...config.tokens,
  color: {
    ...config.tokens.color,
    primary_100_alpha_10: '#CFD3FE1A',
    primary_100_alpha_20: '#CFD3FE33',
  },
});

<Input
      backgroundColor="$primary_100_alpha_20"
      borderColor="$primary_100_alpha_20"
    />
```

### System Info

```markdown
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 324.42 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.1.0 - ~/.nvm/versions/node/v19.1.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 9.7.2 - ~/.nvm/versions/node/v19.1.0/bin/npm
    pnpm: 8.15.4 - ~/.nvm/versions/node/v19.1.0/bin/pnpm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 123.0.6312.106
    Safari: 17.3.1
  npmPackages:
    @ianvs/prettier-plugin-sort-imports: ^4.2.1 => 4.2.1 
    @union/eslint-config: workspace:* => 1.0.0 
    concurrently: ^8.2.2 => 8.2.2 
    eslint: ^8.57.0 => 8.57.0 
    husky: ^9.0.11 => 9.0.11 
    lint-staged: ^15.2.2 => 15.2.2 
    prettier: ^3.2.5 => 3.2.5
```

**Comment by TheEhsanSarshar** [comment]
not sure what is `alpha` value here. you mean having `alpha` text in your color name will make it not work  ?

**Comment by bo-union** [comment]
> not sure what is `alpha` value here. you mean having `alpha` text in your color name will make it not work ?

For hex color values with alpha values 
https://www.digitalocean.com/community/tutorials/css-hex-code-colors-alpha-values#adding-an-alpha-value-to-css-hex-codes

**Comment by TheEhsanSarshar** [comment]
Just tested and it seems working fine on the web, please try with the latest version of Tamagui

**Comment by natew** [comment]
Can re-open if this is an issue, it shouldn't be
