### ISSUE TITLE
Passing style array to `contentContainerStyle` of `ScrollView` cause an error

### ISSUE THREAD

**Issue by likeSo** [tamagui/tamagui#2504]
### Current Behavior

<img width="666" alt="image" src="https://github.com/tamagui/tamagui/assets/12247340/57c03010-78a1-4021-9220-c8e27cce3ac7">

I am passing an style array to `contentContainerStyle` prop. For now, if a run my project, i got an error below:

`Error: Failed to set an indexed property [0] on 'CSSStyleDeclaration': Indexed property setter is not supported.`

### Expected Behavior

Works as built-in `ScrollView`. Built-in `ScrollView` has no error.

-----------
BTW i think some of Tamagui component look like... not Tamagui-style? For example:
- For `ScrollView`, is there an elegant way to use `contentContainerStyle`? For now, shorthands will pass to `style`, not `contentContainerStyle`.
- For `Input` and `TextArea`, they look like only a built-in RN component when a Tamagui theme😂

### Tamagui Version

```markdown
1.94.1
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
import {ScrollView} from 'tamagui'

<ScrollView contentContainerStyle={[xxx, xxx]} />
```

**Comment by TheEhsanSarshar** [comment]
I don't think you can pass an array to `contentContinaerStyle` you need to pass an object

```js
contentContainerStyle={{
     ...style.contentContainer,
     paddingLeft: 34,
     paddingRight: 20
}}
```

**Comment by likeSo** [comment]
Built-in `ScrollView` can do this as well. I am now using React Native's `ScrollView` component

**Comment by TheEhsanSarshar** [comment]
yeah because now ScrollView `containerContainer` supports Tamagui tokens.
there is this new field to `styled()` third field that let you add Tamagui token support to custom props
```
  {
    accept: {
      contentContainerStyle: 'style',
    },
  }
  ```
, we can add array support to that. but not a high priority right now
