### ISSUE TITLE
TypeScript errors 

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#2505]
### Current Behavior

In my monorepo I have ui package with tamagui components and your standard tamagui-build.
When I import this ui package and try to use components from it I see many new TypeScript issues.
It worked fine until version 1.90 - 1.91 I guess.

Here is brief example of these issues:
```ts
error TS2530: Property 'children' is incompatible with index signature.
  Type 'Element[]' has no properties in common with type 'WithThemeShorthandsAndPseudos<StackStyleBase, { elevation?: number | SizeTokens | undefined; fullscreen?: boolean | undefined; inset?: number | SizeTokens | Insets | undefined; }>'.

15           <YStack gap="$text">
              ~~~~~~
```

```ts
error TS2322: Type '{ children: ReactNode; }' is not assignable to type 'WithMediaProps<WithThemeShorthandsAndPseudos<TextStylePropsBase, { size?: FontSizeTokens | undefined; unstyled?: boolean | undefined; }>>'.
  Property 'children' is incompatible with index signature.
    Type 'ReactNode' is not assignable to type 'WithThemeShorthandsAndPseudos<TextStylePropsBase, { size?: FontSizeTokens | undefined; unstyled?: boolean | undefined; }> | undefined'.

18           <H3>{title}</H3>
```

### Expected Behavior

Do not see any TypeScript issues

### Tamagui Version

```markdown
1.91 - 1.94
```

### Platform (Web, iOS, Android)

```markdown
All
```

### Reproduction

```markdown
Because it is related to monorepo I will create reproduction when it is not easy fix
```

**Comment by TheEhsanSarshar** [comment]
make sure all your Tamagui dependencies are same versions and try removing `dist` `types` directory, so basically a clean start can help.

**Comment by seeden** [comment]
Yeah, I tried to remove everything already (node_modules, dist) but nothing helped

**Comment by TheEhsanSarshar** [comment]
a reproduction can be helpful
