### ISSUE TITLE
Button Press Style Inconsistency with Nested Text Component

### ISSUE THREAD

**Issue by sabaturgay** [tamagui/tamagui#2507]
### Current Behavior

When the button component is pressed, it scales down as expected. However, pressing the text within the button causes only the text to scale down, not the entire button. This inconsistent behavior seems to occur due to pressStyle not being applied to the button when the nested text is pressed.

Workaround:
A temporary workaround is to set textProps={{ disabled: true }}, which seems to fix the issue.

https://github.com/tamagui/tamagui/assets/22500853/00bdf24e-d634-48b8-96f5-383ff1e51955

### Expected Behavior

The pressStyle should be applied to the entire button component, including the nested text (even when the text inside of the button get pressed), ensuring consistent press effects.

### Tamagui Version

```markdown
1.94.1
```

### Platform (Web, iOS, Android)

```markdown
iOS
```

### Reproduction

```markdown
1- Create a button component with a nested text component.
2- Apply a pressStyle transformation to the button.
3- Observe the behavior when pressing the button directly versus pressing the text within the button.

<Button
onPress={() => onSignin(STRATEGIES.oauth_apple)}
w="$7/8"
mt="$2.5"
h="$4.5"
bg="black"
color="white"
icon={Apple}
>				{t('screens:signin.signinWithApple')}
</Button>

Tamagui config: 
defaultProps: {
 Button: {
  animation: '100ms',
  elevation: '$size.15',
  pressStyle: {
  elevation: '$size.7',
  scale: 0.95,
  },
 },
},
```

**Comment by TheEhsanSarshar** [comment]
not excatly sure if I understood your reproduction.
I tried this and it's working fine

```jsx
    <Button
      bg="red"
      pressStyle={{
        scale: 0.9,
      }}
    >
      <Button.Text>Click Me</Button.Text>
    </Button>
 ```

**Comment by TheEhsanSarshar** [comment]
that issue is because we use the same `name` for both `Button` and `Button.Text` to have a shared theme.
and that caused both to take the same default styles. One solution is to extend `Button.Text` and change its name like this
```jsx
const ButtonText = styled(Button.Text, { name: 'ButtonText'})
```
we will deprecate that pattern at some point, it's better to use `styled` or other ways to create reusable components
