### ISSUE TITLE
Elevation breaks toast in production ios

### ISSUE THREAD

**Issue by matthewhausman** [tamagui/tamagui#2508]
### Current Behavior

In production, when a toast has the elevation prop it will not render.

### Expected Behavior

Toast should work with elevation prop in production

### Tamagui Version

```markdown
1.91.4
```

### Platform (Web, iOS, Android)

```markdown
iOS
```

### Reproduction

```markdown
1) clone https://github.com/matthewhausman/toast-bug-reprod
2) run  && cd apps/expo
3) run `npx expo run:ios --configuration Release`
4) try to open toast when the initial screen renders and see that toast does not appear
5) remove ios directory in apps/expo
6) remove elevation prop from CustomToast component (packages/ui/src/components/CustomToast.tsx)
7) run `npx expo run:ios --configuration Release` again and click button to open toast when initial screen renders. Toast appears.
```

### System Info

```markdown
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M2
    Memory: 85.94 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 4.1.0 - ~/.nvm/versions/node/v18.17.0/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Chrome: 123.0.6312.106
    Safari: 17.4
```

**Comment by TheEhsanSarshar** [comment]
I wasn't able to re-produce using (ToastDemo)[https://github.com/tamagui/tamagui/blob/master/packages/demos/src/ToastDemo.tsx#L35] in Tamagui.
having `elevation `won't break it on debug and production

please try with latest version of Tamagui
let me know if need to re-open the issue

**Comment by TheEhsanSarshar** [comment]
oh I was able to re-prdouce it with moti driver.
use `animateOnly` for now ( also a good practice for performance ), I'm working on a fix for that
