### ISSUE TITLE
[Expo web (webpack 4)] Missing Default Web Styles when using Stack

### ISSUE THREAD

**Issue by sohcah** [tamagui/tamagui#251]
**Describe the bug**
When using the Stack component directly (rather than X/YStack) on Web without using the Tamagui Compiler, the default styles (eg `display: flex`) don't get applied.

**To Reproduce**
https://github.com/sohcah/tamagui-display-issue
- `yarn`
- `yarn web`
- Notice the Stacks not having `display: flex`

**System Info (please complete the following information):** 
  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 123.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: 3.2.0 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome Canary: 108.0.5333.0
    Firefox Developer Edition: 104.0
    Safari: 15.6.1

**Comment by natew** [comment]
You may need to use babel inline variables plugin:

https://docs.expo.dev/guides/environment-variables/

**Comment by sohcah** [comment]
Unfortunately, I don't believe this to be the issue, as I'm already using that plugin, as well as Webpack Define, and I can confirm that `isWeb` exported from tamagui is `true` as expected.

**Comment by natew** [comment]
Ah missed that repro sorry, this makes sense, we need to force `static` to always include the base stack/text stuff in case compiler misses them.

Though `getCSS` should return it at runtime I'd imagine.... 🤔 

Will check the repo here soon enough.

**Comment by natew** [comment]
This should be fixed in latest, have multiple fixes relating to this. Re-open if still seeing it.
