### ISSUE TITLE
Request for Student Discount or Affordable Pricing for TamaGUI Takeout

### ISSUE THREAD

**Issue by aayushnaphade** [tamagui/tamagui#2515]
I'm Ayush Naphade, a second-year B.Tech student in Mechanical Engineering at Visvesvaraya National Institute of Technology, India. I recently completed my first React Native app and was looking into pre-built UI component libraries to streamline development. That's when I came across Tamagui and its TakeOut UI component template, which seems like a fantastic tool for quick and easy app development.

However, as a student working with a startup, budget is a concern for us. The pricing for TakeOut is a bit steep, and we were wondering if there are any options available for a free template or at least a discount . We're really excited about the potential of Tamagui for our project and would love to explore it further.

Any guidance or assistance you can provide would be greatly appreciated!

Thanks,
Ayush Naphade ~ @aayushnaphade

**Comment by natew** [comment]
We have parity pricing that should show a banner on the bottom, but if you email us team@tamagui.dev I can also send you a coupon.
