### ISSUE TITLE
bug: Button component on native using theme="green" do not work correctly

### ISSUE THREAD

**Issue by bidah** [tamagui/tamagui#2523]
### Current Behavior

![CleanShot 2024-04-09 at 14 29 46@2x](https://github.com/tamagui/tamagui/assets/1574028/2b589294-e3cd-47a0-99f1-2a6675823779)

Button used on Bento Fullpage component that sets `theme="green"` prop do not work correctly on web. Green is not the expected color.

### Expected Behavior

Expect green theme to be same as how it looks on web version

### Tamagui Version

```markdown
1.94.4
```

### Platform (Web, iOS, Android)

```markdown
Android and IOS
```

### Reproduction

```markdown
available at <https://github.com/tamagui/tamagui/pull/2444>
```

### System Info

```markdown
System:
    OS: macOS 14.3.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 250.36 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    bun: 1.0.30 - ~/.bun/bin/bun
  Browsers:
    Chrome: 123.0.6312.107
    Safari: 17.3.1
```

**Comment by TheEhsanSarshar** [comment]
see if we are using the same themes from `@tamagui/config/v3` as in site

**Comment by natew** [comment]
Oh you know what kitchen sink has its own tamagui config it mutates purposefully makes button green for a specific test! This is not a bug. We should use a different config for bento.

**Comment by bidah** [comment]
ok got it. closing this issue.
