### ISSUE TITLE
[bug] Select component's sheetBreakpoint doesn't work properly on Android and iOS (repo included)

### ISSUE THREAD

**Issue by SushritPasupuleti** [tamagui/tamagui#256]
**Describe the bug**
When running the example code for select on an iOS, iPad simulator or Android Tab VM the following behaviour is observed:

- Android (Portrait Mobile): Drop down doesn't render (throws error attached below), Sheet doesn't trigger.

- iOS (Portrait Mobile): Sheet is triggered, Dropdown throws error attached belowr.

- iOS (iPad): Both do not work and Dropdown triggers the error attached below.

This was done on a fresh repo bootstrapped with .190 beta of tamagui via create-tamagui-app

![Screenshot 2022-10-03 at 1 42 48 PM](https://user-images.githubusercontent.com/14891901/193530584-48ac3f65-b1a9-4d8f-85a5-1e31438976a4.png)

This can be gotten around by setting the breakpoint on the 2 native platforms to "xl", to get atleast the full sheet to load, however on android both dropdown and sheet do not open under any circumstance.

Update: after performing a bit more of testing, I think the issue has to do with `sheetBreakpoint` prop and also the fact that the non-sheet version doesn't work on Native (the `document` keyword in the warning is a clear indicator).

Additionally, when there are more than 1 Select components in the screen, none of them seem to work on Native.

Link to the [repo](https://github.com/SushritPasupuleti/tamagui-select-issues)

**To Reproduce**
Run the sample code on an iPad or Android tab VM.

**Comment by kalvin807** [comment]
I had the same issue when running it on an android phone with Expo Go.
Happy to provide more debug stacks if needed

**Comment by natew** [comment]
Select doesn't work on native unless used as a sheet for now. We should make this automatic for native though as no alternative exists.

**Comment by natew** [comment]
Fixed in https://github.com/tamagui/tamagui/pull/451
