### ISSUE TITLE
The `Tabs` example given in the website doesn't work (Animations)

### ISSUE THREAD

**Issue by NocKby** [tamagui/tamagui#2560]
### Current Behavior

I tried copying the [`Tabs` example](https://tamagui.dev/ui/tabs/1.7.0#examples) given on the official site but the animations don't work (TabsRovingIndicator function and all the `AnimatePresence` components). There are also `enterVariant` and `exitVariant` declarations that are marked as deprecated.

### Tamagui Version

```markdown
1.94.0
```

### Platform (Web, iOS, Android)

```markdown
Android
```

### Reproduction

```markdown
import React from 'react'
import { useState } from 'react'
import type { StackProps, TabLayout, TabsTabProps } from 'tamagui'
import {
    AnimatePresence,
    Button,
    H5,
    SizableText,
    Stack,
    Tabs,
    XStack,
    YStack,
    styled,
} from 'tamagui'

const demos = ['background', 'underline'] as const
const demosTitle: Record<(typeof demos)[number], string> = {
    background: 'Background Indicator',
    underline: 'Underline Indicator',
}

export const TabsAdvancedDemo = () => {
    return (
        <TabsAdvancedUnderline />
    )
}

const TabsAdvancedUnderline = () => {
    const [tabState, setTabState] = useState<{
        currentTab: string
        /**
         * Layout of the Tab user might intend to select (hovering / focusing)
         */
        intentAt: TabLayout | null
        /**
         * Layout of the Tab user selected
         */
        activeAt: TabLayout | null
        /**
         * Used to get the direction of activation for animating the active indicator
         */
        prevActiveAt: TabLayout | null
    }>({
        activeAt: null,
        currentTab: 'tab1',
        intentAt: null,
        prevActiveAt: null,
    })

    const setCurrentTab = (currentTab: string) => setTabState({ ...tabState, currentTab })
    const setIntentIndicator = (intentAt) => setTabState({ ...tabState, intentAt })
    const setActiveIndicator = (activeAt) =>
        setTabState({ ...tabState, prevActiveAt: tabState.activeAt, activeAt })
    const { activeAt, intentAt, prevActiveAt, currentTab } = tabState

    /**
     * -1: from left
     *  0: n/a
     *  1: from right
     */
    const direction = (() => {
        if (!activeAt || !prevActiveAt || activeAt.x === prevActiveAt.x) {
            return 0
        }
        return activeAt.x > prevActiveAt.x ? -1 : 1
    })()

    const enterVariant =
        direction === 1 ? 'isLeft' : direction === -1 ? 'isRight' : 'defaultFade'
    const exitVariant =
        direction === 1 ? 'isRight' : direction === -1 ? 'isLeft' : 'defaultFade'

    const handleOnInteraction: TabsTabProps['onInteraction'] = (type, layout) => {
        if (type === 'select') {
            setActiveIndicator(layout)
        } else {
            setIntentIndicator(layout)
        }
    }

    return (
        <Tabs
            value={currentTab}
            onValueChange={setCurrentTab}
            orientation='horizontal'
            height={'63%'}
            width={'100%'}
            flexDirection='column'
            activationMode='manual'
            backgroundColor='$reversed'
            borderRadius='$4'
            alignItems='center'
            position='relative'
            marginTop={300}
        >
            <YStack>
                <AnimatePresence>
                    {intentAt && (
                        <TabsRovingIndicator
                            width={intentAt.width}
                            height='$0.5'
                            x={intentAt.x}
                            bottom={0}
                        />
                    )}
                </AnimatePresence>
                <AnimatePresence>
                    {activeAt && (
                        <TabsRovingIndicator
                            theme='active'
                            active
                            width={activeAt.width}
                            height='$0.5'
                            x={activeAt.x}
                            bottom={0}
                        />
                    )}
                </AnimatePresence>
                <Tabs.List
                    disablePassBorderRadius
                    loop={false}
                    borderColor='transparent'
                    backgroundColor='transparent'
                    width={'100%'}
                    justifyContent='space-between'
                    paddingTop={'$2.5'}
                    paddingBottom={'$1.5'}
                    paddingRight={'$5'}
                    paddingLeft={'$5'}
                >
                    <Tabs.Tab
                        unstyled
                        paddingHorizontal='$3'
                        paddingVertical='$2'
                        value='tab1'
                        onInteraction={handleOnInteraction}
                    >
                        <SizableText fontSize={16} color={'$color3'}>Informations</SizableText>
                    </Tabs.Tab>
                    <Tabs.Tab
                        unstyled
                        paddingHorizontal='$3'
                        paddingVertical='$2'
                        value='tab2'
                        onInteraction={handleOnInteraction}
                    >
                        <SizableText fontSize={16} color={'$color3'}>Historique</SizableText>
                    </Tabs.Tab>
                    <Tabs.Tab
                        unstyled
                        paddingHorizontal='$3'
                        paddingVertical='$2'
                        value='tab3'
                        onInteraction={handleOnInteraction}
                    >
                        <SizableText fontSize={16} color={'$color3'}>Statistiques</SizableText>
                    </Tabs.Tab>
                </Tabs.List>
            </YStack>

            <AnimatePresence
                exitBeforeEnter
                // custom={{ enterVariant, exitVariant }}
                enterVariant={enterVariant}
                exitVariant={exitVariant}
            >
                <AnimatedYStack key={currentTab} animation='100ms' x={0} opacity={1} flex={1}>
                    <Tabs.Content value={currentTab} forceMount flex={1} justifyContent='center'>
                        <H5 textAlign='center'>{currentTab}</H5>
                    </Tabs.Content>
                </AnimatedYStack>
            </AnimatePresence>
        </Tabs>
    )
}

const TabsRovingIndicator = ({ active, ...props }: { active?: boolean } & StackProps) => {
    return (
        <YStack
            position='absolute'
            backgroundColor='$color5'
            opacity={0.7}
            animation='100ms'
            enterStyle={{
                opacity: 0,
            }}
            exitStyle={{
                opacity: 0,
            }}
            {...(active && {
                backgroundColor: '$color8',
                opacity: 0.7,
            })}
            {...props}
        />
    )
}

const AnimatedYStack = styled(YStack, {
    variants: {
        isLeft: { true: { x: -25, opacity: 0 } },
        isRight: { true: { x: 25, opacity: 0 } },
        defaultFade: { true: { opacity: 0 } },
    } as const,
})
```

### System Info

```markdown
System:
    OS: Windows 11 10.0.26090
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 3.56 GB / 15.84 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.0.2 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Internet Explorer: 11.0.26090.1
  npmPackages:
    @babel/core: ^7.23.3 => 7.23.7
    @expo-google-fonts/inter: ^0.2.3 => 0.2.3
    @expo-google-fonts/montserrat: ^0.2.3 => 0.2.3
    @expo/metro-runtime: ~3.1.3 => 3.1.3
    @react-native-async-storage/async-storage: 1.21.0 => 1.21.0
    @react-navigation/native: ^6.0.2 => 6.1.9
    @tamagui/animations-css: ^1.94.4 => 1.94.4
    @tamagui/babel-plugin: ^1.94.0 => 1.94.0
    @tamagui/config: ^1.94.0 => 1.94.0
    @tamagui/lucide-icons: ^1.94.4 => 1.94.4
    @tamagui/metro-plugin: ^1.94.0 => 1.94.0
    @types/react: ~18.2.14 => 18.2.47
    babel-preset-expo: ^10.0.1 => 10.0.1
    expo: ~50.0.14 => 50.0.14
    expo-clipboard: ~5.0.1 => 5.0.1
    expo-font: ~11.10.3 => 11.10.3
    expo-image-picker: ~14.7.1 => 14.7.1
    expo-linear-gradient: ~12.7.2 => 12.7.2
    expo-linking: ~6.2.1 => 6.2.2
    expo-router: ~3.4.8 => 3.4.8
    expo-secure-store: ~12.8.1 => 12.8.1
    expo-splash-screen: ~0.26.4 => 0.26.4
    expo-status-bar: ~1.11.1 => 1.11.1
    expo-system-ui: ~2.9.3 => 2.9.3
    expo-web-browser: ~12.8.2 => 12.8.2
    firebase: 10.4.0 => 10.4.0
    lottie-react-native: 6.5.1 => 6.5.1
    react: ^18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    react-helmet-async: ~2.0.4 => 2.0.4
    react-native: 0.73.6 => 0.73.6
    react-native-gesture-handler: ~2.14.0 => 2.14.1
    react-native-reanimated: ~3.6.2 => 3.6.2
    react-native-safe-area-context: 4.8.2 => 4.8.2
    react-native-screens: ~3.29.0 => 3.29.0
    react-native-svg: ^15.1.0 => 15.1.0
    react-native-web: ^0.19.10 => 0.19.10
    tamagui: ^1.94.0 => 1.94.0
    typescript: ^5.3.3 => 5.3.3
```

**Comment by TheEhsanSarshar** [comment]
I wasn't able to re-produce, animations are working fine on Android

**Comment by NocKby** [comment]
So, do you have any solutions to this problem ? Could this be caused by dependency versions ?

**Comment by TheEhsanSarshar** [comment]
yeah you should have `100ms` animation defined in your tsconfig. there should be a ts complain for that ?

**Comment by NocKby** [comment]
Yeah here it is but i don't knwo how can i define it.

`
import { createAnimations } from '@tamagui/animations-react-native';
import { createMedia } from '@tamagui/react-native-media-driver';
import { shorthands } from '@tamagui/shorthands';
import { radius, size, space, zIndex } from '@tamagui/themes'
import { Button, createFont, createTamagui, createTokens, Input, styled, YStack } from 'tamagui';
import { SafeAreaView } from 'react-native-safe-area-context';

const montserratFont = createFont({
  family: 'MontserratMedium',
  size: {
    1: 12,
    2: 14,
    3: 15,
    4: 16
  },
  weight: {
    1: '200',
    2: '500',
    3: '600',
    4: '700'
  },
  letterSpacing: {
    1: 0,
    2: -1,
    3: 0.1
  },
  face: {
    200: { normal: 'MontserratExtraLight' },
    500: { normal: 'MontserratMedium' },
    600: { normal: 'MontserratSemiBold' },
    700: { normal: 'MontserratBold' }
  },
});

const tokens = createTokens({
  color: {
    darkRed: '#FA8072',
    lightRed: '#FFA07A',
    darkGrey: '#DCDCDC',
    lightGrey: '#A9A9A9'
  },
  space,
  size,
  radius,
  zIndex
})

const config = createTamagui({
  themes: {
    dark: {
      background: '#001F23',
      color: '#fff',
      reversed: '#317b8a',
      red: tokens.color.darkRed,
      grey: tokens.color.darkGrey,
      separator: 'rgba(255,255,255,0.1)',
      borderColor: '#D66900'
    },
    light: {
      color: '#fff',
      background: '#317b8a',
      reversed: '#001F23',
      red: tokens.color.lightRed,
      grey: tokens.color.lightGrey,
      separator: '#eee',
      borderColor: '#D66900'
    },
    red: {
      color: tokens.color.darkRed,
      background: tokens.color.darkRed,
      iconColor: tokens.color.darkRed
    },
    active: {
      color3: '#D66900',
      color5: '#fff',
      color8: '#D66900'
    }
  },

  defaultFont: 'body',
  animations: createAnimations({
    fast: {
      damping: 20,
      mass: 1.2,
      stiffness: 250,
    },
    medium: {
      damping: 10,
      mass: 0.9,
      stiffness: 100,
    },
    slow: {
      damping: 20,
      stiffness: 60,
    },
  }),
  shouldAddPrefersColorThemes: true,
  themeClassNameOnRoot: true,
  shorthands,
  fonts: {
    body: montserratFont,
    heading: montserratFont,
  },
  tokens,
  media: createMedia({
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
    short: { maxHeight: 820 },
    tall: { minHeight: 820 },
    hoverNone: { hover: 'none' },
    pointerCoarse: { pointer: 'coarse' },
  }),
});

export const Container = styled(SafeAreaView, {
  name: 'Container',
  flex: 1,
  backgroundColor: '$background',
  alignItems: 'center',
  justifyContent: 'center'
});

export const CustomInput = styled(Input, {
  name: 'CustomInput',
  backgroundColor: '$reversed',
  placeholderTextColor: '$grey',
  size: '$5',
  borderColor: 'transparent'
});

export const CustomButton = styled(Button, {
  name: 'CustomButton',
  backgroundColor: '$reversed',
});

export const ListContainer = styled(YStack, {
  name: 'ListContainer',
  backgroundColor: '$reversed',
  display: 'flex',
  position: 'relative',
  width: '95%',
  maxHeight: '70%',
  alignItems: 'center',
  justifyContent: 'center',
  borderRadius: 15,
  marginTop: 100,
  overflow: 'scroll'
});


type AppConfig = typeof config;

// Enable auto-completion of props shorthand (ex: jc="center") for Tamagui templates.
// Docs: https://tamagui.dev/docs/core/configuration

declare module 'tamagui' {
  interface TamaguiCustomConfig extends AppConfig { }
}

export default config;
`

**Comment by TheEhsanSarshar** [comment]
check this part
```js
animations: createAnimations({
    fast: {
      damping: 20,
      mass: 1.2,
      stiffness: 250,
    },
    medium: {
      damping: 10,
      mass: 0.9,
      stiffness: 100,
    },
    slow: {
      damping: 20,
      stiffness: 60,
    },
  }),
  ```
  
  add any custom animation here, or use one of these in your animations
  
  read docs to better understand it
  https://tamagui.dev/docs/core/animations

**Comment by TheEhsanSarshar** [comment]
your using `100ms` which is not included in the animations. you need to either include that or use one of these animations

**Comment by NocKby** [comment]
> your using `100ms` which is not included in the animations. you need to either include that or use one of these animations

I used one of the animations already defined in the `tamagui.config.ts`. I even tried using CSS animations instead of React Reanimated.

**Comment by TheEhsanSarshar** [comment]
hmmm tbh it's very hard to trace the issue without any re-production
if you re-produce it using one of tamagui starters and share the github code, I can check it more.

**Comment by NocKby** [comment]
I've created a new project and it's working well. But I don't know why it works in one and not in the other.
