### ISSUE TITLE
Adding fontWeight: 600 with system-fonts doesn't make texts appear bold on Android

### ISSUE THREAD

**Issue by Cooty** [tamagui/tamagui#2567]
### Current Behavior

I have a custom Tamagui theme that uses the system font on each platform. In my theme settings I set `600` as the value for weight number `3`. When using this value in my custom components either inline or with the `styled` function as `fontWeight="$3"` it works on iOS, but on Android the fonts are rendered as regular weight.

I'm only developing for Android and iOS right now, so web doesn't concern me. However I do use [@storybook/addon-react-native-web](https://storybook.js.org/addons/@storybook/addon-react-native-web) for presentation and QA and in the browser based Storybook environment the font-weight works properly.

I think this might be related to an earlier issue reported [here](https://github.com/tamagui/tamagui/issues/2282), but I see you've closed that for lack of reproducible example.

### Expected Behavior

The value `600` for the `fontWeight` property should render a bolded text on both Android and iOS.
If I add the basic `Text` component imported from `react-native`, that works on both platform.

```jsx
<Text style={{ fontWeight: "600" }}>
    Native Text component that's bold
</Text>
```

### Tamagui Version

**1.91.3**

### Platform (Web, iOS, Android)

Tested on:

- Android (Emulator): Pixel 7 Pro API level 34
- Android physical device: Google Pixel 4, Android Version 13, Expo Go v2.30.11
- iOS (Simulator): iPhone 15, iOS 17.2

### Reproduction

1. Clone the [example repository](https://github.com/Cooty/tamagui-android-font-weight-bug-demo)
2. Install dependencies (`npm run install`)
3. Run `npm run ios` and `npm run android` in two separate terminal windows and open the app in two emulators (or physical devices using Expo Go).
4. Tap on the "Toggle emphasis" button and observe that the text becomes bold on iOS, while it stays the same on Android.
5. Also observe the text "Native Text component that's bold" below the button, this is a native `Text` component with `fontWeight` set to `600` and it gets bolded on both platforms.

### System Info

```markdown
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 59.23 MB / 16.00 GB
    Shell: 3.7.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.11.0 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 123.1.64.122
    Chrome: 124.0.6367.60
    Safari: 17.2.1
  npmPackages:
    @babel/core: ^7.20.0 => 7.24.4 
    @tamagui/config: 1.91.3 => 1.91.3 
    @tamagui/core: 1.91.3 => 1.91.3 
    @types/react: ~18.2.45 => 18.2.79 
    expo: ~50.0.14 => 50.0.17 
    expo-status-bar: ~1.11.1 => 1.11.1 
    react: 18.2.0 => 18.2.0 
    react-native: 0.73.6 => 0.73.6 
    tamagui: 1.91.3 => 1.91.3 
    typescript: ^5.1.3 => 5.4.5
```

**Comment by Cooty** [comment]
FYI. for now the issue can be fixed by setting the `fontWeight` to `700`, but that doesn't explain why does it work with the value `600` using the built in React Native `<Text>` component.

**Comment by TheEhsanSarshar** [comment]
You need to specify your `fontFamily` name when using `Text` component, otherwise it will pick `defaultFont` value from your tamagui config which is `body` ( `'Inter'` ).

you can change `defaultFont` to `systemFont` in your tamagui config as well.

just tested and it's working fine what those changes, I'll close this issue. let me know if there's a need to re-open

**Comment by ShivamJoker** [comment]
@TheEhsanSarshar thanks for the clarification but can you give me an example on using system font with different weights?

**Comment by Cooty** [comment]
@TheEhsanSarshar I would actually want to use the default system font in my app.

Right now I have my font tokens set up like so

```ts
export const systemFont = createFont({
  family: '',
  size: {
    1: 12,
    2: 14,
    3: 16,
    4: 18,
    5: 20,
    6: 24,
    7: 26,
    8: 28,
    9: 30,
    10: 32,
  },
  lineHeight: {
    1: 16,
    2: 20,
    3: 24,
    4: 28,
    5: 28,
    6: 28,
    7: 32,
    8: 32,
    9: 40,
    10: 40,
  },
  weight: {
    1: '400',
    2: '400',
    3: '600',
    4: '700',
    5: '800',
    6: '800',
    7: '800',
    8: '800',
    9: '800',
    10: '800',
  },
  letterSpacing: {
    1: 0,
    2: 0,
    3: 0,
    4: 0,
  },
  face: {},
})
```

So that means I should set it up like

```ts
export const systemFont = createFont({
  family: 'systemFont',
  size: {
  // ...
```

**Comment by TheEhsanSarshar** [comment]
Your first setup is right. 
you just need to specify which font you want to use with your `Text` component
like this
`<Text fontFamily="myFontNameHere">`
 if you don't specify that, it will fallback to `defaultFont` that you specified in your `tamagui.config.ts`

or you can change `defaultFont` to your `myCustomFont`

```
const fonts = {
    mySystemFont: systemFont
}

const config = createTamagui({
     fonts,
     defaultFont: 'mySystemFont'
})
```

**Comment by Cooty** [comment]
> const fonts = {
>     mySystemFont: systemFont
> }

If I refactor my code as you've suggested above my app crashes.

![Screenshot_1714118796](https://github.com/tamagui/tamagui/assets/6146591/26d92cd2-639a-4ea1-97a4-ce82b20a9814)

**Comment by TheEhsanSarshar** [comment]
is your code on that github repo ?

**Comment by TheEhsanSarshar** [comment]
in that github repo. just put this line to your tamagui.config file and it should work

const config = createTamagui({
    defaultFont: "systemFont"
})

**Comment by ShivamJoker** [comment]
@TheEhsanSarshar I am still confused on how can I make my heading fonts to default bold with system fonts.
Can you please share some resources? Thanks!

**Comment by Cooty** [comment]
> in that github repo. just put this line to your tamagui.config file and it should work
> 
> const config = createTamagui({ defaultFont: "systemFont" })

@TheEhsanSarshar I've tried your suggestion in my demo repository ([this is the commit](https://github.com/Cooty/tamagui-android-font-weight-bug-demo/commit/69c6294089e9310c3fe67a8389cce5e961ac34fc)), but it's still not working.

<img width="772" alt="Screenshot 2024-05-07 at 09 05 13" src="https://github.com/tamagui/tamagui/assets/6146591/46b900aa-13d0-4292-8388-3cd0679c3320">

**Comment by Cooty** [comment]
@TheEhsanSarshar I've also tried using the unmodified `Text` component directly from `tamagui` and just setting `fontWeight="600"`. Same result, works on iOS but not on Android.

I also tried adding 

```jsx
<TamaguiText fontWeight="600" fontFamily="defaultFont">
    This here is the regular Text component from Tamagui
</TamaguiText>
```

or

```jsx
<TamaguiText fontWeight="600" fontFamily="systemFont">
    This here is the regular Text component from Tamagui
</TamaguiText>
```

These both yielded a Typescript error, since the only possible values would be `$body`, `$header` or `unset`.

Also after adding the `defaultFont: "systemFont"` line to my `tamagui.config.ts`, I see a warning on startup saying

> fontFamily "$systemFont" is not a system font and has not been loaded through expo-font. 
    at RCTText
    at Text
    
 
<img width="674" alt="Screenshot 2024-05-07 at 09 23 45" src="https://github.com/tamagui/tamagui/assets/6146591/a950e6b2-2bb3-45e9-a217-12fbc772d7cf">

**Comment by TheEhsanSarshar** [comment]
you need to have `systemFont` defined in your Tamagui config

```
createTamagui({
    fonts: {
       systemFont: {}
    }
})
```

and when using it directly in your components, you need to use it like `$systemFont`

**Comment by Cooty** [comment]
> you need to have `systemFont` defined in your Tamagui config
> 
> ```
> createTamagui({
>     fonts: {
>        systemFont: {}
>     }
> })
> ```
> 
> and when using it directly in your components, you need to use it like `$systemFont`

I've tried to add my custom `systemFont` to the `font` key, also set it as default font, plus tried to set it manually on one of my component in the [demo repository](https://github.com/Cooty/tamagui-android-font-weight-bug-demo) (see [this commit](https://github.com/Cooty/tamagui-android-font-weight-bug-demo/commit/8a637e2a81af754a443ea20f5e54fb70b38389ae)).

But nothing changed, as you can see Android still doesn't get bold weights.

<img width="758" alt="Screenshot 2024-05-14 at 18 08 41" src="https://github.com/tamagui/tamagui/assets/6146591/a4313ffd-bba5-4710-a5bd-3e5bdbbbbabc">

I also had the idea maybe I'm using the wrong mapping in my setting, but I've console logged the currently used config (using `useConfiguration`) and I can clearly see that `fontsParsed.$systemFont.weight.$3.val` is `"600"`.
