### ISSUE TITLE
Tamagui Website: Overload Animation Frames - Reanimated

### ISSUE THREAD

**Issue by lerisse** [tamagui/tamagui#2579]
### Current Behavior

Website crashes when zooming in and out. Web Inspector points to reanimated creating too many frames which crashes and shows 404 / A problem repeatedly occurred on "https://tamagui.dev"

[tamagui.dev-recording.json](https://github.com/tamagui/tamagui/files/15083918/tamagui.dev-recording.json)

https://github.com/tamagui/tamagui/assets/10137509/ea2365d9-cb43-4f9f-82a5-428f14787f40

### Platform (Web, iOS, Android)

```markdown
iOS (Safari, Chrome) : iPhone 13 Pro Max
Did not test on Android
```

### Reproduction

```markdown
- Go to Tamagui.dev on iPhone. 
- Zoom in all the way then out. 
- Website crashes for me
```

**Comment by TheEhsanSarshar** [comment]
wasn't able to re-reproduce on a simulator, I'll check that with a real device

**Comment by lerisse** [comment]
I'm not getting any CPU hikes which I thought was the problem. Sim works fine for me as well

**Comment by GreatTeacherOni** [comment]
Atm the website [https://tamagui.dev/](https://tamagui.dev/) currently renders a little bit slowly for me. It doesn't feel snappy or performant at all. On my linux pc the cpu fan starts to spin up and my cpu processor temp jumps from around 50°C up to 75-80°C while the website is loading and rendering stuff in Firefox. On chromium it feels more performant but still the animations don't feel really smooth.
On the windows machine the temperature issue isn't that dramatic (jumps up to 60-70°C).
My guess would be that it has to do with the animation elements but I didn't analyze it yet.

Tested on:
Firefox 126.0 (64-bit) - Linux (Kernel 6.6.31) ("recommended performance settings" activated) 
Chromium 125.0.6422.76 (Official Build) (64-bit) (Chromium has "use graphics acceleration when available" activated)
Firefox 126.0 (64-bit) - Windows 10 22H2 ("recommended performance settings" activated)

**Comment by natew** [comment]
We may have had some temporary regression, but it feels pretty decent now. We are pushing animations quite heavily.
