### ISSUE TITLE
Cannot force pseudo style of children in a group

### ISSUE THREAD

**Issue by CorentinAndre** [tamagui/tamagui#2581]
### Current Behavior

When applying any forceStyle value to a component which is a group (whether named or boolean group), children using the `$group-${pseudoState}` prop are not correctly styled.

### Expected Behavior

I would expect the pseudo style to be visible for children of a group.

### Tamagui Version

```markdown
1.95.1
```

### Platform (Web, iOS, Android)

```markdown
Web, iOS, Android
```

### Reproduction

```markdown
https://github.com/CorentinAndre/group-force-style-repro

it's visible on the first page
```

### System Info

```markdown
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 138.77 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
    Yarn: 4.1.0 - ~/.nvm/versions/node/v20.12.1/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.1/bin/npm
    Watchman: 2024.04.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 124.0.6367.79
    Safari: 17.4.1
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.39.0 
    node-gyp: ^9.3.1 => 9.3.1 
    prettier: ^2.7.1 => 2.8.8 
    turbo: ^1.10.3 => 1.10.3 
    typescript: ^5.3.3 => 5.3.3
```

**Comment by CorentinAndre** [comment]
If someone can point me in the right direction, I'd be happy to submit a PR :)

**Comment by TheEhsanSarshar** [comment]
hmm, not sure if that's an expected behavior
`group-hover` translate to something similar to this `.group:hover > .target { // some styles }` 
so the main purpose of `group-hover` is to react to the hover state of its group.

for your usecase you can use named groups. 

```jsx
<View group="container">

     <View $group-container={{ // apply some style }} />
```

**Comment by CorentinAndre** [comment]
Hi @TheEhsanSarshar, thanks for your reply.

Replace group by a named group in my example and this still won't work.

What I'm saying is that if I'm forcing the style of a group container with `forceStyle="hover"`, I would expect children of this component with `$group-container-hover` to apply this style as well.
I'm using this to display my components in a story and I want them to display their interactive styles in order to QA them with Chromatic.

**Comment by TheEhsanSarshar** [comment]
yea so when using `forceStyle="hover"` it just pick whatever styles we have inside `hoverStyle={{}}` and apply it directly to the component, but it won't trigger hover state of that component. which is an expected behaviour

`group-hover` will only react when you hovered that component via mouse or there might be a way to trigger it with javascript or Chromatic api,

**Comment by CorentinAndre** [comment]
Understood. I find it a bit counterintuitive though but if it's intentional I'll close my issue. 
Thanks 🙏
