### ISSUE TITLE
duplicate ID for input

### ISSUE THREAD

**Issue by ex-git** [tamagui/tamagui#2592]
### Current Behavior

showing "Warning, duplicate ID for input"

![Screenshot from 2024-04-26 22-59-28](https://github.com/tamagui/tamagui/assets/27160136/5b0da962-f077-4300-b865-fb61ed49839a)
![Screenshot from 2024-04-26 22-59-57](https://github.com/tamagui/tamagui/assets/27160136/33adc28e-0c66-4214-a81c-45afcd567ffb)

### Expected Behavior

Should not show warning

### Tamagui Version

```markdown
1.95.1
```

### Platform (Web, iOS, Android)

```markdown
native/iOS
```

### Reproduction

```markdown
<Fieldset gap="$3" horizontal>
        <Label
          h='auto'
          jc="flex-end"
          textAlign='right'
          htmlFor="password"
        >
          Password
        </Label>
        <Input
          flex={1}
          id="password"
        />
      </Fieldset>
```
```


### System Info

```markdown
System:
    OS: Linux 6.8 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 23.56 GB / 31.03 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.0.6 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
```

**Comment by TheEhsanSarshar** [comment]
yeah Label should have a unique id. you can use react `useId()` hook to generate a unique id

**Comment by ex-git** [comment]
> yeah Label should have a unique id. you can use react `useId()` hook to generate a unique id 

I don't get it. The warning is not for Label and my example code only set htmlFor for Label. 
If you look at example code for label, htmlFor should match the input id. https://tamagui.dev/ui/label/1.0.0

**Comment by TheEhsanSarshar** [comment]
yeah label and input id should match. I mean you probably used same id twice. like having two inputs or two labels with same id

**Comment by TheEhsanSarshar** [comment]
there is a PR that will fix this
Thanks for reporting ❤️

**Comment by grabbou** [comment]
Hey! I am getting the same error when using TextArea and looks like same code that was deleted in this PR https://github.com/tamagui/tamagui/pull/2596/files to fix that issue for Input is still present there. I am not sure what are the internal mechanisms here behind the scenes, but if same would fix it for TextArea, that would be great!
