### ISSUE TITLE
Bug(Android): Can't call tRPC inside Sheet

### ISSUE THREAD

**Issue by psycho-baller** [tamagui/tamagui#2594]
### Current Behavior

Seems like in the Android Sheet, you can't have a component inside the sheet that calls the tRPC backend(at least on load; i.e: useQuery)

It used to work fine when I run `expo start --android` but this error happens when I use the Expo dev client; i.e: `expo start --dev-client --android`

In other words, this fails:
```
export const ComponentUsedInsideTheSheet = (props: Props) => {
  const personQuery = api.person.all.useQuery() // this fails
  ...
  ...
  ...
}
```
<img width="381" alt="image" src="https://github.com/tamagui/tamagui/assets/81759594/13d5f227-0b9d-427d-8d27-839c0a17b0cb">

### Expected Behavior

It would work just as it works in web and iOS in Expo dev client

### Tamagui Version

```markdown
1.90.16
```

### Platform (Web, iOS, Android)

```markdown
Android
```

### Reproduction

```markdown
- Implement example from [tamagui Sheet](https://tamagui.dev/ui/sheet)  
- Create a component that contains a tRPC query as shown above
- Place that component inside the Sheet
- Run the Expo dev client on Android
- It should fail on Android but not iOS and web
```

### System Info

```markdown
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 49.63 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - ~/.asdf/installs/nodejs/21.2.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 10.2.3 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.15.4 - ~/.asdf/installs/nodejs/21.2.0/bin/pnpm
    bun: 1.1.4 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 124.1.65.114
    Chrome: 124.0.6367.91
    Safari: 17.4.1
  npmPackages:
    @acme/api: workspace:^0.1.0 => 0.1.0 
    @acme/app: workspace:^0.0.0 => 0.0.0 
    @acme/eslint-config: workspace:^0.2.0 => 0.2.0 
    @acme/prettier-config: workspace:^0.1.0 => 0.1.0 
    @acme/tailwind-config: workspace:^0.1.0 => 0.1.0 
    @acme/tsconfig: workspace:^0.1.0 => 0.1.0 
    @acme/ui: workspace:* => 0.1.0 
    @expo/metro-config: ^0.17.4 => 0.17.5
```

**Comment by TheEhsanSarshar** [comment]
here we used `Portals` to move the `Sheet` to the root of your app, which means it will lose any context, you need to re-propagate your trpc providers inside sheet. or try to move your trcp providers one level to the top of `<TamaguiProvider>`

**Comment by psycho-baller** [comment]
Ohh makes sense, thanks for the quick response :)

Out of curiosity, how was this done on iOS and web?

**Comment by TheEhsanSarshar** [comment]
iOS and web handle the Portal natively, so only the rendered result is ported on actual dom
