### ISSUE TITLE
Sheets having unexpected behaviour on Android

### ISSUE THREAD

**Issue by jamespb97** [tamagui/tamagui#261]
**Describe the bug**
Sheets component will either not show/load when prompted (when`modal` set to true) or when set to `false` the sheet will show but prompting to close will then still show the sheet.

**To Reproduce**
Clone the starters-next-expo-solito example, run `yarn native` and run on a physical android device.
Press the up chevron button and nothing will happen.
Change the `modal` prop to false and press again, this should then show the sheet but then pressing the close button will then not close the sheet.

**System Info (please complete the following information):** 

Android Device:
Xiaomi Poco F3, Running on Android 12.

```
System:
    OS: macOS 12.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.54 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Brave Browser: 88.1.19.88
    Chrome: 105.0.5195.125
    Safari: 15.2
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.18.9 
    @manypkg/cli: ^0.19.1 => 0.19.1 
    @types/react: ^18.0.15 => 17.0.21 
    @types/react-native: ^0.69.5 => 0.69.5 
    eslint: ^8.21.0 => 8.21.0 
    prettier: ^2.7.1 => 2.7.1 
    turbo: ^1.4.2 => 1.4.2 
    typescript: ^4.7.4 => 4.7.4 
```

**Comment by natew** [comment]
Fixed in latest release :)
