### ISSUE TITLE
Copying a command from code snippets, returns undefined

### ISSUE THREAD

**Issue by blueedgetechno** [tamagui/tamagui#2624]
### Current Behavior

Copying a code snippets copies "undefined" as text.

![image](https://github.com/tamagui/tamagui/assets/54899800/f7b15fe7-110c-48fc-b2e9-e34c768b851b)

### Expected Behavior

It should copy the content of the snippet.

### Tamagui Version

```markdown
0.19.6
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
- Visit https://tamagui.dev/docs/intro/installation#install.

- Copy a command

- Try to paste it.
```

**Comment by blueedgetechno** [comment]
| ![image](https://github.com/tamagui/tamagui/assets/54899800/ddc1ebb1-8637-487c-b76e-5c5257e09bd1) | ![image](https://github.com/tamagui/tamagui/assets/54899800/f7b15fe7-110c-48fc-b2e9-e34c768b851b) |
|---|---|

**Comment by natew** [comment]
This should be working now
