### ISSUE TITLE
bun create tamagui fails if git clone.defaultRemoteName is not "origin"

### ISSUE THREAD

**Issue by mrdomino** [tamagui/tamagui#2631]
### Current Behavior

When you try to get started with tamagui, it dies while trying to do a `git pull` from something called `origin` if you have changed `defaultRemoteName` to something more ergonomic, like for example `up`.

### Expected Behavior

It should either not depend at all on the remote name or, if that's too hard, then read the default remote name via `git config clone.defaultremotename` and use that.

### Tamagui Version

```markdown
1.0.1-rc.7.1 (according to `bunx create-tamagui-app --version`)
```

### Platform (Web, iOS, Android)

```markdown
N/A
```

### Reproduction

```markdown
% rm -rf ~/.tamagui
% git config --global clone.defaultRemoteName up
% bun create tamagui
```

### System Info

```markdown
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 138.23 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - /opt/local/bin/node
    Yarn: 1.22.21 - /opt/local/bin/yarn
    npm: 10.7.0 - /opt/local/bin/npm
    bun: 1.1.7 - ~/.bun/bin/bun
    Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 124.1.65.126
    Chrome: 124.0.6367.119
    Safari: 17.4.1
```
```

**Comment by natew** [comment]
Fix in next release 6b592edccb93140c4efca301ef277dca91de874e
