### ISSUE TITLE
DatePicker on mobile

### ISSUE THREAD

**Issue by gtkatakura** [tamagui/tamagui#2636]
### Current Behavior

Tests made using the https://tamagui.dev/bento/elements/datepickers

The DatePicker default behavior when open the calendar opens the keyboard view too. Did it makes sense?

#### Android Emulator - Pixel 6 Pro API 34 (Android 14.0)

<img src="https://github.com/tamagui/tamagui/assets/8618687/91b13669-44db-403e-b856-80d4a37ff7ce" height="800"/>

---

#### Real Device - Motorola Edge 30 Ultra

<img src="https://github.com/tamagui/tamagui/assets/8618687/f5f37788-a80f-46f5-9461-8996ddf52864" height="800"/>

### Tamagui Version

```markdown
Tests on https://tamagui.dev/bento/elements/datepickers
```

### Platform (Web, iOS, Android)

```markdown
1. Android Emulator - Pixel 6 Pro API 34 (Android 14.0)
2. Real Device - Motorola Edge 30 Ultra
```

### Reproduction

```markdown
Go to https://tamagui.dev/bento/elements/datepickers
Click on some datepicker
```

**Comment by bsoung** [comment]
Yep - encountering this issue as well, non emulator iphone 13 pro keyboard pops out alongside the date picker.

**Comment by Hoolaf** [comment]
guys can you check if for you in expo if the bento datapicker failed on android ?

**Comment by SamuraiF0x** [comment]
pushed a fix https://github.com/tamagui/tamagui/pull/2705

![image](https://github.com/tamagui/tamagui/assets/22216187/49a5e869-2ff0-4814-9a68-3fae3700af93)
