### ISSUE TITLE
[Documentation] Changing package manager does not change the command on other code block

### ISSUE THREAD

**Issue by romain-trotard** [tamagui/tamagui#2640]
Hello :)

### Current Behavior

Currently, we can change the package manager (thanks to tabs) to have the right command to execute. 

It changes the selected package manager for every code block, but the **command** does not change for other code block.

![Reproduction video](https://github.com/tamagui/tamagui/assets/17161484/f3c65646-49f1-4a5b-addd-5cd957e3433f)

### Expected Behavior

The command should changed in function of the selected package manager for all code blocks.

The reason is that there is a local state for the command in the [getBashCommand](https://github.com/tamagui/tamagui/blob/f960d880384c28ce9697cd5c6bdd0358edb50a4d/apps/site/lib/getBashCommand.ts#L44) file.
I think this state should be removed, because the source of truth should be the selected tabs (which is stored on the local storage) and the command, in my opinion, should be calculated on the render.

I have made a commit on a fork https://github.com/romain-trotard/tamagui/commit/5503296d9721d09266c032a69f0618c5006984e4. I will be very pleased to open a PR :) 

ps: I think it's possible to do another solution:  state up every state of the `RowingTabs` components in a hook (getBashCommand would be transformed into a hook), and use it in the `DocCodeBlock` component. But, I think there are some drawbacks like extracting the logic of the `RowingTabs`. The positive point would be that the `useEffect` I added would be removed.

### Tamagui Version

```markdown
Production environment: https://tamagui.dev/docs/intro/installation
```

### Platform (Web, iOS, Android)

```markdown
Web: chrome.
```

### Reproduction

```markdown
- Go to https://tamagui.dev/docs/intro/installation
- Change the package manager on the first code block -> it changes the command
- See that it has changed the selected package manager on other code block, but the command does not have changed
```

**Comment by natew** [comment]
Oof yea this was contributed and is my fault for merging in a sloppy state.

**Comment by natew** [comment]
Happy to accept the PR, and your suggestions sound right.

**Comment by natew** [comment]
Just pushed a simple fix for now. Actually looking at it its fine to keep as-is.
