### ISSUE TITLE
Why can't the website open?

### ISSUE THREAD

**Issue by JedediahXu** [tamagui/tamagui#2653]
### Current Behavior

Why can't the website open?   https://tamagui.dev/

![CleanShot 2024-05-17 at 23 16 48](https://github.com/tamagui/tamagui/assets/44160015/b7856f9e-47c0-458a-9954-f7004816da18)

![CleanShot 2024-05-17 at 23 17 52](https://github.com/tamagui/tamagui/assets/44160015/68bb0fc0-1dcc-4e98-9e2f-ed3224015cce)

### Tamagui Version

```markdown
https://tamagui.dev/
```

### Platform (Web, iOS, Android)

```markdown
https://tamagui.dev/
```

### Reproduction

```markdown
https://tamagui.dev/
```

**Comment by theshakeabhi** [comment]
Facing the same issue!

**Comment by JedediahXu** [comment]
It seems to have been resolved~
