### ISSUE TITLE
@tamagui/constants esm build is missing platform-specific .mjs files

### ISSUE THREAD

**Issue by sdcooke** [tamagui/tamagui#2670]
### Current Behavior

After running:
```sh
npm create tamagui@latest
```
`node_modules/@tamagui/constants/dist/esm` looks like:

<img width="247" alt="Screenshot 2024-05-22 at 17 45 15" src="https://github.com/tamagui/tamagui/assets/136235/e64c7c41-596d-49ea-9e53-b9838b443285">

note that there are only .mjs files for `index` and `constants` - not `constants.android`, `constants.ios` etc

The knock-on impact of this is under my expo project's module resolution setup, I'm getting a `property 'document' doesn't exist` error because the default (web) constants are being loaded.

i.e. importing `isWeb` and `isIos` from `@tamagui/constants` returns incorrect values

### Expected Behavior

When importing:

```typescript
import { isWeb, isIos } from "@tamagui/constants"; 
```

on iOS I would expect `isWeb === false` and `isIos === true`.

### Tamagui Version

```markdown
1.98.2
```

### Platform (Web, iOS, Android)

```markdown
Tested on iOS
```

### Reproduction

```markdown
Run:

npm create tamagui@latest

and look at `node_modules/@tamagui/constants/dist/esm`. Probably possible to confirm on any tamagui project.

If you think it's necessary I can look into a reproduction with my specific module resolution setup that causes the error, but my understanding is the missing files are a bug even without an error reproduction.
```

**Comment by sdcooke** [comment]
This has been fixed in [v1.99.1](https://github.com/tamagui/tamagui/commit/539b95e2974fc6b69dc85b2e8c169858aa9990b2) - thank you @natew! I just upgraded and tested and unfortunately it doesn't seem to fix my issue (tamagui thinking it's on web, when it's actually on iOS) - I think because `index.mjs` explicitly imports `./constants.mjs` so metro isn't loading the platform-specific files.

 For extra info my tsconfig is set to:

```
    "module": "Preserve",
    "moduleResolution": "Bundler",
```

I'm just trying out tamagui to see if it's right for my app, and don't have a deep enough knowledge of module resolution to work this out myself right now. If I decide to go ahead with tamagui and this isn't something you're able to work out straight away I can revisit later and see if I can work it out.

I've managed to work around it for now by adding this to my metro config:

```typescript
resolveRequest = (context, moduleName, platform) => {
  if (moduleName === "@tamagui/constants") {
    return context.resolveRequest(context, "@tamagui/constants/dist/esm/constants", platform);
  }
  return context.resolveRequest(context, moduleName, platform);
}
```

**Comment by sdcooke** [comment]
I've just discovered that `@tamagui/web` has the same issue with missing `.native.mjs` files - when trying to render text I'm getting an error because it's trying to render a `<span>`.

**Comment by natew** [comment]
Your app shouldn't be picking up the mjs files at all from native... we have a react-native exports field that points to `dist/cjs/index.native.js` from web, can you help me with a repro and I'll get this solved?

**Comment by sdcooke** [comment]
I think this issue may be caused by

```javascript
config.resolver.unstable_enablePackageExports = true;
```

I used `npm create tamagui` and updated `metro.config.js` to include that line and whilst I didn't get the same error (not sure why) I did get a lot of logs:

```
warning: The package .../node_modules/@tamagui/create-theme contains an invalid package.json configuration. Consider raising this issue with the package maintainer(s).
Reason: The resolution for ".../node_modules/@tamagui/create-theme" defined in "exports" is .../node_modules/@tamagui/create-theme/dist/esm/index.mjs, however this file does not exist. Falling back to file-based resolution.
```

There are a couple of workarounds - either adding:

```javascript
config.resolver.unstable_conditionNames = ["require"];
```

or

```javascript
config.resolver.resolveRequest = (context, moduleName, platform) => {
  if (moduleName.startsWith("@tamagui/")) {
    return context.resolveRequest(
      {
        ...context,
        unstable_conditionNames: config.resolver.unstable_conditionNames.filter((condition) => condition !== "import"),
      },
      moduleName,
      platform,
    );
  }
  return context.resolveRequest(context, moduleName, platform);
};
```

which is similar to something metro does internally as a workaround: https://github.com/facebook/metro/blob/6856d00cfdddc1dd5ed9ab35249fe7ca1610ca75/packages/metro-resolver/src/resolve.js#L265

This feels like it could be a metro issue - hopefully it will be fixed before `enablePackageExports` becomes the default!

Really appreciate your help - any suggestions about anything else I can do to help repro, or confirm whether it's a metro or tamgui problem?

**Comment by natew** [comment]
Yea so I am planning on improving this compile issue for exports for native, I just need time to fix the `tamagui-build.js` script, but also Metro should use the "react-native" exports field, or they need some way to have "react-native-import" or something, we should bring it to their attention.

**Comment by sdcooke** [comment]
I've opened an issue on the metro project (https://github.com/facebook/metro/issues/1278).

**Comment by sdcooke** [comment]
@natew looks like there's a relatively simple solution to this explained on that issue - `"react-native"` needs to be listed higher up in the package.json exports, and that will fix this issue.

**Comment by robhogan** [comment]
Hi @natew - `react-native` isn't being used here because it has a lower precedence than `import`, which Metro also asserts. It looks like `react-native` needs to be moved further up, because it's more specific.

See https://nodejs.org/api/packages.html#conditional-exports

> Within the ["exports"](https://nodejs.org/api/packages.html#exports) object, key order is significant. During condition matching, earlier entries have higher priority and take precedence over later entries. The general rule is that conditions should be from most specific to least specific in object order.

**Comment by natew** [comment]
Should be fixed

**Comment by LucasBourgeois** [comment]
Hi, 

just upgrade the tamagui version from 1.116.5 to 1.117.1.
Using Expo sdk 52 with new Arch enabled

Im getting this error on 1.117.1:
![image](https://github.com/user-attachments/assets/a335d89f-1200-43e1-99f0-2b8b6bb04e18)

It wasnt occuring on 1.116.5 using Expo sdk 52 with new Arch enabled
Removing import is a solution but seems to me to be hacky.

Can't found any change related to conditionNames changes between 1.116 and 1.117.

Here's my metro config
```
unstable_enablePackageExports: true,
unstable_conditionNames: ['react-native', 'browser', 'require', 'import']
```
 
regards

**Comment by guillempuche** [comment]
The same problem in `v1.120.1` @natew.

I've tried with `unstable_enablePackageExports: true`. No success.

**Comment by guillempuche** [comment]
To solve the problem, I did this:

1. Delete all `node_modules` and `yarn clean cache`
2. Install deps again
3. `unstable_conditionNames: ['react-native', 'require']`
