### ISSUE TITLE
Error when build application with animations-moti

### ISSUE THREAD

**Issue by junioroga** [tamagui/tamagui#2671]
### Current Behavior

I think moti was removed from the project dependencies

<img width="305" alt="image" src="https://github.com/tamagui/tamagui/assets/7414393/57a4d883-4478-4a43-91a0-c743bc137d49">

<img width="535" alt="image" src="https://github.com/tamagui/tamagui/assets/7414393/1687ac16-cf1b-4483-ab61-96aa258eef49">

### Expected Behavior

Build successfull

### Tamagui Version

```markdown
1.98.3
```

### Platform (Web, iOS, Android)

```markdown
All
```

### Reproduction

```markdown
Only install moti-animations, use on tamagui.config and build application.
```

**Comment by youssdevx** [comment]
Error disappear when installing `moti`

**Comment by juniorogaa** [comment]
> Error disappear when installing `moti`

but is this right?

**Comment by Pamavoc** [comment]
happening to me too

**Comment by flo-sch** [comment]
It was changed to a [peerDependency](https://nodejs.org/en/blog/npm/peer-dependencies) instead, which means it needs to be installed as well (without restriction of any version):
https://github.com/tamagui/tamagui/blob/v1.100.6/packages/animations-moti/package.json#L36

Documentation could need some updates probably

**Comment by natew** [comment]
Documented 819674a71db91e51f1786c256dbdbd3d87d0e294
