### ISSUE TITLE
Why does TamaGUI has so big slowdown in performance?

### ISSUE THREAD

**Issue by NDruce** [tamagui/tamagui#2678]
### Current Behavior

Look on benchmarks:
https://github.com/efstathiosntonas/react-native-style-libraries-benchmark

### Tamagui Version

```markdown
Idk
```

### Platform (Web, iOS, Android)

```markdown
Idk
```

### Reproduction

```markdown
Look the link I provided above
```

**Comment by NDruce** [comment]
Why just not build classes into native way in build time instead of runtime? It should remove any kind of performance impacts at all

**Comment by pipech** [comment]
[#### Note: Tamagui compiler is turned off in DEV mode, production/release performance is greatly improved, it reaches `StyleSheet` levels.](https://github.com/efstathiosntonas/react-native-style-libraries-benchmark/blob/2625703a09bf23450ef2d0fab5abdb7a9cfa58a6/README.md?plain=1#L15)

Related discussion: https://github.com/tamagui/tamagui/discussions/1471

**Comment by natew** [comment]
![CleanShot 2024-07-28 at 11 03 57@2x](https://github.com/user-attachments/assets/146571dc-e997-4882-af05-642e62458fa0)

**Comment by natew** [comment]
It can actually be significantly *faster* than hand-written, because compiler can flatten to ideal code, and also flattens to RCTView rather than View.

As usual, benchmarks are usually misleading.
