### ISSUE TITLE
borderStyle is ignored  when borderRadius is set

### ISSUE THREAD

**Issue by vipulrawat** [tamagui/tamagui#2685]
### Current Behavior

Adding `borderRadius` seems to ignore the `borderStyle` value.

```tsx
<YStack
  	w={100}
	h={100}
	borderRadius={10}
	borderWidth={2}
	borderStyle="dashed"
	borderColor="$color9"
/>
```

### Expected Behavior

The result should have `dashed` border style, but the resulting view has the border style as `solid`.	

### Tamagui Version

```markdown
1.98.0
```

### Platform (Web, iOS, Android)

```markdown
Android
```

### Reproduction

```markdown
Render the following:


<YStack
  	w={100}
	h={100}
	borderRadius={10}
	borderWidth={2}
	borderStyle="dashed"
	borderColor="$color9"
/>
```

**Comment by natew** [comment]
Not able to repro
