### ISSUE TITLE
create tamagui@latest start with a bug on mobile

### ISSUE THREAD

**Issue by t1gu1** [tamagui/tamagui#2686]
### Current Behavior

I just run the `npm create tamagui@latest` _(monorepo is a starter with Expo + Next.js)_ and when I start the mobile with a `yarn native` t give that following error:

![image](https://github.com/tamagui/tamagui/assets/12479055/7ec93c80-6ba3-4100-addf-5ca41512f6d8)

The web works.

### Expected Behavior

The starter project should not start with an error when we start using the mobile project without changing anything.

### Tamagui Version

```markdown
I use the @latest when starting the project.

Seems to be the `1.99.1`
```

### Platform (Web, iOS, Android)

```markdown
Mobile

Only tested on IOS with Expo GO
```

### Reproduction

```markdown
- npm create tamagui@latest
- Choose the monorepo is a starter with Expo + Next.js
- cd {name of your project}
- yarn native
```

### System Info

```markdown
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.76 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 4.1.0 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    bun: 1.0.2 - ~/.bun/bin/bun
    Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 125.0.6422.113
    Edge: 125.0.2535.67
    Safari: 17.5
  npmPackages:
    @babel/runtime: ^7.24.6 => 7.24.6 
    @manypkg/cli: ^0.21.4 => 0.21.4 
    check-dependency-version-consistency: ^4.1.0 => 4.1.0 
    eslint: ^9.3.0 => 9.3.0 
    node-gyp: ^10.1.0 => 10.1.0 
    prettier: ^3.2.5 => 3.2.5 
    turbo: ^1.13.3 => 1.13.3 
    typescript: ^5.4.5 => 5.4.5
```

**Comment by t1gu1** [comment]
It seems related to the following code

```
const linkProps = useLink({
    href: `${linkTarget}/nate`,
  })
```

In that file `packages/app/features/home/screen.tsx`

If i remove the `useLink` it works.. but I don't think it's the goal here?
Maybe since it use the expo navgation it's not required anymore???

Sry, I just start the project, not a pro of tamagui/solito/Expo router at the moment.

**Comment by SamuraiF0x** [comment]
PR with a fix is out, @t1gu1 check it out and lmk if it works now:
https://github.com/tamagui/starter-free/pull/27

**Comment by t1gu1** [comment]
@SamuraiF0x it works on your branch.

But be warned that there is a warning.

![image](https://github.com/tamagui/tamagui/assets/12479055/1fec614e-17f7-4bda-93ff-108cebecef53)

At least it works.
Thx!

**Comment by SamuraiF0x** [comment]
fix for that warning has just been merged:
https://github.com/tamagui/starter-free/pull/27
