### ISSUE TITLE
Expo router starter has wrong colorScheme on device set on light mode

### ISSUE THREAD

**Issue by giacomocerquone** [tamagui/tamagui#2691]
### Current Behavior

Hey there. Just spawned up a new project with `npm create` and I've chosen the expo router starter.

The simulator is in light mode, and for some reason this is what I see (n.b. the problem is not there when setting the simulator in dark mode):

![336034925-b6b77100-5297-44fe-8273-4c978e46c791](https://github.com/tamagui/tamagui/assets/9303791/cebba70f-9f3e-4282-8045-a5289f17e1b0)

### Expected Behavior

I should be able to read the text and have the correct color scheme

### Tamagui Version

```markdown
^1.99.1
```

### Platform (Web, iOS, Android)

```markdown
iOS
```

### Reproduction

```markdown
`npm create tamagui@latest`
select expo router
yarn run ios
```

### System Info

```markdown
System:
    OS: macOS 14.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 82.81 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 4.0.2 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    Watchman: 2024.01.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 17.5
  npmPackages:
    @babel/core: ^7.24.5 => 7.24.5 
    @expo/metro-runtime: ~3.2.1 => 3.2.1 
    @react-navigation/native: 6.1.17 => 6.1.17 
    @tamagui/config: ^1.99.1 => 1.99.1 
    @tamagui/lucide-icons: ^1.99.1 => 1.99.1 
    @tamagui/metro-plugin: ^1.99.1 => 1.99.1 
    @tamagui/toast: ^1.99.1 => 1.99.1 
    @types/react: ~18.2.79 => 18.2.79 
    @types/react-native: ^0.73.0 => 0.73.0 
    babel-preset-expo: ^11.0.6 => 11.0.6 
    burnt: ^0.12.2 => 0.12.2 
    expo: 51.0.9 => 51.0.9 
    expo-font: 12.0.6 => 12.0.6 
    expo-linking: ~6.3.1 => 6.3.1 
    expo-router: ~3.5.14 => 3.5.14 
    expo-splash-screen: ~0.27.4 => 0.27.4 
    expo-status-bar: ^1.12.1 => 1.12.1 
    expo-system-ui: ~3.0.4 => 3.0.4 
    expo-web-browser: ~13.0.3 => 13.0.3 
    react: ^18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    react-native: 0.74.1 => 0.74.1 
    react-native-reanimated: 3.10.1 => 3.10.1 
    react-native-safe-area-context: 4.10.1 => 4.10.1 
    react-native-screens: ~3.31.1 => 3.31.1 
    react-native-svg: 15.2.0 => 15.2.0 
    react-native-web: ^0.19.12 => 0.19.12 
    tamagui: ^1.99.1 => 1.99.1 
    typescript: ^5.3.3 => 5.4.5 
```
```

**Comment by giacomocerquone** [comment]
I'm not even sure the problem lies here or in expo router (or react navigation) since it seems like the `DarkTheme` passed to the `ThemeProvider` is not applied.

Furthermore, I'd say the starter should inverse tamagui's defaultTheme like this:

```
<TamaguiProvider config={config} defaultTheme={colorScheme === 'light' ? 'dark' : 'light'}>
  <ThemeProvider value={colorScheme === "dark" ? DarkTheme : DefaultTheme}>
```

**Comment by SamuraiF0x** [comment]
pushed fix, can you try now?

**Comment by giacomocerquone** [comment]
> pushed fix, can you try now?

Hey there. Thank you, but no, now on both light and dark mode, it appears like this:

![image](https://github.com/tamagui/tamagui/assets/9303791/3c94e88e-7269-418c-b5c7-6a3ea46ab944)

Also, here you should not set defaultTheme: https://github.com/tamagui/tamagui/blob/master/starters/expo-router/app/_layout.tsx#L47, but removing it still doesn't solve the problem and most importantly, you shouldn't push stuff like that, it makes difficult for me, or other contributors, comment and give advices over the code you want to change.

What do you say of opening a pr next time?

**Comment by SamuraiF0x** [comment]
Hi @giacomocerquone, thank you for your feedback and advice! I made a pr with changes, should work now if you want to test it

**Comment by giacomocerquone** [comment]
> Hi @giacomocerquone, thank you for your feedback and advice! I made a pr with changes, should work now if you want to test it

yes it is, thank you!
