### ISSUE TITLE
Installation with Expo requires config

### ISSUE THREAD

**Issue by xixixao** [tamagui/tamagui#2692]
### Current Behavior

https://tamagui.dev/docs/intro/installation suggest that `config` on `TamaguiProvider` is not required, but it is when using Expo.

### Tamagui Version

```markdown
"@tamagui/config": "^1.99.1",
"tamagui": "^1.99.1"
```

### Platform (Web, iOS, Android)

```markdown
iOS (Expo GO)
```

### Reproduction

1. `npx create-expo-app repro`
2. `cd repro`
3. `npm i tamagui`
4. `npm run reset-project`
5. Wrap `app/_layout.tsx` in `TamaguiProvider` imported from `tamagui`

You'll get an error:

```
TypeError: Cannot read property 'state' of undefined

This error is located at:
    in Theme (created by ThemeProvider)
    in ThemeProvider (created by TamaguiProvider)
    in Provider (created by TamaguiProvider)
    in TamaguiProvider (created by TamaguiProvider)
    in TamaguiProvider (created by RootLayout)
    in RootLayout
```

**Comment by SamuraiF0x** [comment]
`TamaguiProvider ` always requires `config`. It just depends whether you're using a custom one imported from your local `tamagui.config.ts` or from tamagui `import { config } from '@tamagui/config/v3'`

I've updated docs to make it more clear :)
