### ISSUE TITLE
Individual border radius properties are ignored on web

### ISSUE THREAD

**Issue by wongk** [tamagui/tamagui#2693]
### Current Behavior

On web, the individual border radius properties (i.e., `borderTopEndRadius`, `borderTopStartRadius`, etc...) are ignored. They work on native. The `borderRadius` property also works on both web and native.

Web:
![Screenshot 2024-06-03 at 10 26 08 AM](https://github.com/tamagui/tamagui/assets/599085/b558e568-d139-448d-b001-d9b3d0b6651e)

Native:
![Screenshot 2024-06-03 at 10 26 28 AM](https://github.com/tamagui/tamagui/assets/599085/0188d7e0-0d5a-4c74-becd-83b9a1bb0ff9)

### Tamagui Version

```markdown
1.99.1
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
<XStack
      backgroundColor="$background"
      padding="$3"
      borderTopEndRadius={index === 0 ? "$2" : "$0"}
      borderTopStartRadius={index === 0 ? "$2" : "$0"}
      borderBottomEndRadius={index === section.data.length - 1 ? "$2" : "$0"}
      borderBottomStartRadius={index === section.data.length - 1 ? "$2" : "$0"}
      marginBottom="$0.5"
      alignItems="center"
    >
      <Text fontSize={14}>{item.subcategoryName}</Text>
      <Spacer direction="horizontal" flex={1} />
      <PlusCircle size={20} />
    </XStack>
```
```


### System Info

_No response_

**Comment by natew** [comment]
@bidah another decent one since it's web only and likely just some logic in `getSplitStyles`

**Comment by guillempuche** [comment]
How to do it?

The browser still doesn't recognize it, Tamgui v1.109.1

**Comment by guillempuche** [comment]
I open #2906
