### ISSUE TITLE
Popover on web not closing when clicking outside or hitting scape

### ISSUE THREAD

**Issue by kasrak** [tamagui/tamagui#2701]
### Current Behavior

I have a simple `<Popover>` (copied from the docs). When I click outside it, or hit "Escape" on the keyboard, it doesn't close.

### Expected Behavior

I'd expect it to close when clicking outside or hitting "Escape"

### Tamagui Version

```markdown
1.100.0
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://github.com/kasrak/tamagui-popover-repro/blob/main/App.tsx
```

### System Info

```markdown
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M2 Pro
    Memory: 88.44 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.local/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 125.0.6422.142
    Chrome Canary: 127.0.6521.0
    Edge: 125.0.2535.85
    Safari: 17.5
  npmPackages:
    @babel/core: ^7.20.0 => 7.24.7
    @expo/metro-runtime: ~3.2.1 => 3.2.1
    @tamagui/config: ^1.100.0 => 1.100.0
    @types/react: ~18.2.45 => 18.2.79
    expo: ~51.0.10 => 51.0.10
    expo-status-bar: ~1.12.1 => 1.12.1
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    react-native: 0.74.1 => 0.74.1
    react-native-web: ~0.19.10 => 0.19.12
    tamagui: ^1.100.0 => 1.100.0
    typescript: ^5.1.3 => 5.4.5
```

**Comment by kasrak** [comment]
From [Popover.tsx](https://github.com/tamagui/tamagui/blob/master/packages/popover/src/Popover.tsx#L614)
```
const sheetActive = useSheetBreakpointActive(sheetBreakpoint)

const floatingContext = useFloatingContext({
  open,
  setOpen: handleOpenChange,
  disable: sheetActive,
  hoverable,
  disableFocus: disableFocus,
}) as any
```

When I run the repro example, `sheetActive` looks like `{current: undefined}`, so the value of `disable` is truthy

**Comment by shiroyk** [comment]
A few days ago, I also encountered this issue. I noticed that there is a package-lock.json file in the project you provided, indicating that you probably used `npm install` to install the dependencies. A temporary solution is to run `rm -rf node_modules && yarn install`

**Comment by kasrak** [comment]
Interesting, thank you -- that does seem to solve it in the repro. But ideally I'd love to find a way to make it work with npm because migrating our main repo from npm to yarn for this issue doesn't make a ton of sense.

Do you have any theories on why yarn vs npm install might be resulting in different behavior?

**Comment by shiroyk** [comment]
`npm` resolves dependencies differently than `yarn`, and this issue might be caused by conflicts between certain dependency versions.

**Comment by kasrak** [comment]
Ah, I figured out another temporary fix for anyone running into this with `npm`. When I add `@tamagui/floating` as an explicit top-level dependency in my package.json, the popover works as expected. I think multiple copies of `@tamagui/floating` were being installed previously.

```
	"dependencies": {
		"@tamagui/config": "1.100.0",
		"@tamagui/floating": "1.100.0",
		"tamagui": "1.100.0"
	},
```

**Comment by natew** [comment]
Glad it's resolved, yes Tamagui requires exact matching versions of all dependencies. We have a doctor command
