### ISSUE TITLE
[Next.Js] Error when rendering a non client component: cannot access Image.propTypes on the server.

### ISSUE THREAD

**Issue by foyarash** [tamagui/tamagui#2708]
### Current Behavior

Taking the starter-free repo as en example.

I try to add an `<Image />` component  from `next/image` in the render of the user page.

When i run `yarn web` and try to access to the user page, i get:

```
 Error: Cannot access Image.propTypes on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.
```

This error disappears when i remove the tamagui plugin from the next config.

A workaround for this is to wrap the Image component into a client component, but this is not really ideal.

I also saw this happening with the `GoogleAnalytics` component from `next/third-parties`.

### Expected Behavior

I can use the `Image` component or any other component without any issue and without needing to wrap them as client components

### Tamagui Version

```markdown
1.100.0
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
1. Start a starter-free project
2. Go to `apps/next/app/user/[id]/page.tsx` and render `<Image src="/favicon.ico" alt="Tamagui" width={32} height={32} />` inside it
3. Run `yarn web`
4. Access to `http://localhost:3000/user/1`
```

### System Info

```markdown
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M3 Pro
    Memory: 4.45 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 4.1.0 - ~/.nvm/versions/node/v20.13.1/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    bun: 1.0.29 - ~/.bun/bin/bun
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.5
  npmPackages:
    @babel/runtime: ^7.24.6 => 7.24.6
    @manypkg/cli: ^0.21.4 => 0.21.4
    check-dependency-version-consistency: ^4.1.0 => 4.1.0
    eslint: ^9.3.0 => 9.4.0
    node-gyp: ^10.1.0 => 10.1.0
    prettier: ^3.2.5 => 3.3.0
    turbo: ^1.13.3 => 1.13.4
    typescript: ^5.4.5 => 5.4.5
```

**Comment by natew** [comment]
No error for me on the latest version!
