### ISSUE TITLE
[bug] TypeError: Cannot create proxy with a non-object

### ISSUE THREAD

**Issue by dohomi** [tamagui/tamagui#273]
**Describe the bug**
With NextJS there is an error on build, which prevents next build to succeed:
```
next-app:build: Tamagui Webpack Loader Error TypeError: Cannot create proxy with a non-object as target or handler

```
**To Reproduce**
Build tamagui nextjs

Reproduction:
https://github.com/dohomi/tamagui-kitchen-sink

**Comment by dohomi** [comment]
this seems expo-av and expo-document-picker related.. works on Storybook, NextJS dev but not build.. frustrating experience

**Comment by dohomi** [comment]
This seems actually a bug inside tamagui. I created a blank ViteJS project and the error occured with the exact same error message.

**Comment by natew** [comment]
Just to save me some time could you try updating to latest and seeing what it logs?

**Comment by dohomi** [comment]
I'll close this issue for now, I somehow found a way around it - but i forgot the reason. I think it was related to .native.tsx or .web.tsx use, I will report back if the issue still occurs.
