### ISSUE TITLE
$theme-dark behavior under <Theme> components

### ISSUE THREAD

**Issue by kzlar** [tamagui/tamagui#2737]
### Current Behavior

```
<YStack h={100} w={100}>
  <Circle
    h={30}
    w={30}
    backgroundColor={'red'}
    $theme-dark={{ backgroundColor: 'green' }}
  ></Circle>
  <Theme name="dark">
    <Circle
      h={30}
      w={30}
      backgroundColor={'red'}
      $theme-dark={{ backgroundColor: 'green' }}
    ></Circle>
  </Theme>
</YStack>
```
The above code produces two red circles

### Expected Behavior

As mentioned in [discord](https://discord.com/channels/909986013848412191/974145843919716412/1253741268161265745) I'm not sure if this is intentional or not, but I'd expect the 2nd circle to be green since its under the "dark" theme.

The produces CSS looks like this:
```
:root.t_dark ._bg-_themedark_green {
    background-color: green;
}
```
So removing the `:root` prefix would make it behave as expected, but I'm not sure what the side-effects would be.

### Tamagui Version

```markdown
latest
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
See code above
```

**Comment by natew** [comment]
Can you re-open if still an issue, we did a variety of improvements here that should have fixed
