### ISSUE TITLE
Label component doesn't allow line height changes

### ISSUE THREAD

**Issue by NerdCowboy** [tamagui/tamagui#2738]
### Current Behavior

I added a description field underneath the `Label` component inside the `TextField` and `TextAreaField` components. I tried to tighten the spacing between them by reducing the Label's line height (`lh`) and noticed I could not modify it despite everything other style being modifiable. 

When poking inside the source code of `Label`, I noticed this:
```tsx
return {
          ...fontStyle,
          lineHeight: buttonHeight ? extras.tokens.size[buttonHeight] : undefined,
        }
```

I don't understand why line height has any relation to button height—maybe for horizontal forms? I'm fine if that needs to be the default for whatever reason, but it should still be overridable as it appears I'd have to modify the button height here and that's obviously not what we want.

### Expected Behavior

Editing the `Label` component's `lh` should affect the actual line height of the label.

### Tamagui Version

```markdown
1.98.3
```

### Platform (Web, iOS, Android)

```markdown
iOS (though presumably all given the source code I read)
```

### Reproduction

```markdown
Use the `Label` component and try to modify the `lh` or read the source code.
```

### System Info

```markdown
System:
    OS: macOS 14.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 11.08 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.3.0 - ~/.nvm/versions/node/v22.3.0/bin/node
    Yarn: 4.1.0 - /usr/local/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v22.3.0/bin/npm
    Watchman: 2024.05.06.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 110.1.48.171
    Chrome: 126.0.6478.63
    Safari: 17.5
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.24.5
    @manypkg/cli: ^0.19.1 => 0.19.2
    @nderscore/tamagui-typescript-plugin: ^0.6.0 => 0.6.0
    @tamagui/cli: ^1.98.3 => 1.98.3
    @turbo/gen: ^1.10.12 => 1.13.3
    change-case: ^4.1.2 => 4.1.2
    check-dependency-version-consistency: ^3.0.3 => 3.3.0
    dotenv: ^16.0.3 => 16.4.5
    dotenv-cli: ^6.0.0 => 6.0.0
    eslint: ^8.46.0 => 8.57.0
    node-gyp: ^9.3.1 => 9.4.1
    prettier: ^2.7.1 => 2.8.8
    turbo: ^1.10.14 => 1.13.3
    typescript: ^5.3.3 => 5.4.5
```

**Comment by jpaas** [comment]
Setting `lineHeight` does work for me actually. But if I set it to anything other than a number, it crashes on Android.

**Comment by NerdCowboy** [comment]
Seems to work now. Not entirely sure why. I did upgrade, so it's possible that fixed it or I just needed to restart the app again 🤷‍♂️
