### ISSUE TITLE
[bug] expo web is not working with a bare new starter

### ISSUE THREAD

**Issue by dohomi** [tamagui/tamagui#274]
**Describe the bug**
Expo web is not working. 

**To Reproduce**
Install latest tamagui-starter
```
npm create tamagui-app@latest

// required to install
npx expo install @expo/webpack-config@^0.17.0

// run expo
yarn native 
// choose "web" 
```

following error occurs:
```
Uncaught Error: Module parse failed: Unexpected token (9:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const Stack = createNativeStackNavigator<{
|   home: undefined
>   'user-detail': {
|     id: string
|   }
    at ../../node_modules/app/navigation/native/index.tsx 
```

I think its important that Tamagui runs on all Expo platforms, just in case people don't want to use NextJS for web (which is understandable). Reason for me trying expo web was non-compatible node modules which runs on expo web but not on NextJS

**Comment by KingAxanthic** [comment]
My understanding is this is intentional and Next is intended for Web. Unsure if the compiler installation steps have been done for expo web 🤔
No idea though as I've not been successful at getting Expo web to ever function.

**Comment by natew** [comment]
This is intentional, but if you send a PR explaining that in the starter README.md would be helpful
