### ISSUE TITLE
Website: Quick Nav produces a completely blank page

### ISSUE THREAD

**Issue by tazsingh** [tamagui/tamagui#2765]
### Current Behavior

If you click on any item in the Quick Nav, the entire page goes blank for me

### Expected Behavior

It should direct you to that item on the page

### Tamagui Version

```markdown
Website
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
Go to https://tamagui.dev/docs/core/styled

Click on "styleable" in the Quick Nav

See blank page

Copy of Web Console provided as a comment below. First console message was present on page load, before clicking on "styleable"
```

**Comment by tazsingh** [comment]
Copy of Web Console output
<img width="355" alt="image" src="https://github.com/tamagui/tamagui/assets/397824/f060b4e7-1c7b-4644-85d5-20aa68035d96">

**Comment by Stiffjobs** [comment]
facing the same issue

**Comment by vlanemcev** [comment]
Facing the same issue, it is impossible to navigate the site (

**Comment by ahmedu007** [comment]
I think #2771 is also related!

**Comment by natew** [comment]
This one should be fixed now for me at least
