### ISSUE TITLE
Website crashes on Client navigation.

### ISSUE THREAD

**Issue by ahmedu007** [tamagui/tamagui#2771]
### Current Behavior

The website crashes when navigating through the docs. 

Here is the error trace from the console:

<img width="736" alt="image" src="https://github.com/tamagui/tamagui/assets/30743917/41ba754f-7369-46d5-9d59-ecf494c00856">

### Expected Behavior

Should not crash, and load the page correctly. It works with no issues when navigated directly through the link

### Tamagui Version

```markdown
Latest
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
Open www.tamagui.dev

Click on `Docs` from the header. 

On the sidebar click `installation` in the **Compiler** section that takes us to https://tamagui.dev/docs/intro/compiler-install

Please note: The link works when navigated directly, but doesn't work when client side rendering.
```

### System Info

```markdown
MacOS
Tested on 
MS Edge: Version 126.0.2592.87
Safari: Version 17.5
```

**Comment by ahmedu007** [comment]
Similar to #2765

**Comment by natew** [comment]
Closing as I can't repro anymore, we did land a variety of things that I could see fixing that
