### ISSUE TITLE
`Image` component deprecation of `resizeMode` not wired through to `react-native-web` properly.

### ISSUE THREAD

**Issue by cojo** [tamagui/tamagui#2777]
### Current Behavior

The `Image` component deprecates `resizeMode`, but doesn't pass `objectFit` through to the `resizeMode` prop in the web platform. Since react-native-web doesn't support `objectFit` prop directly yet, this ends up breaking functionality unless you override / ignore the deprecation.

### Expected Behavior

Pending proper support of the prop at the react-native-web layer, I would recommend / expect that the Tamagui layer should forward the `objectFit` prop value to the `resizeMode` prop on the underlying `Image` element inside a conditional check for the web platform.

I think it is debatable that this should, perhaps, additionally be filed as a bug against react-native-web, but I think a better intermediate developer experience is for Tamagui to own this since Tamagui is choosing to own the deprecation in its own code (thus potentially misleading developers into expecting it to work, where it clearly won't as-is).

### Tamagui Version

```markdown
1.100.3
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
<Image
	source={someImage}
	width="100%"
	height="100%"
	aspectRatio={1}
	objectFit="contain"
/>
```
will not work as expected and will still end up assigning `cover` (the default value) to the background image on web.

Changing it to:
```
<Image
	source={someImage}
	width="100%"
	height="100%"
	aspectRatio={1}
	objectFit="contain" 
	resizeMode="contain"
/>
```
Works as expected, but incurs the deprecation warning.
```


### System Info

_No response_

**Comment by natew** [comment]
Good catch, fixed in 3c12cbfe5e1861a0799977a60573d843551b6330

Note we have a new `@tamagui/image-next` that will be the default in v2, coming soon, but can be used now. Much faster.
