### ISSUE TITLE
`color` prop not supported in `hoverStyle`, `focusStyle`, `pressStyle`

### ISSUE THREAD

**Issue by tenhsor1** [tamagui/tamagui#2779]
### Current Behavior

`color` prop is not supported on `hoverStyle`, `focusStyle`, `pressStyle`, etc.

ie:
```
import {styled, Button } from 'tamagui'

const IssueButton = styled(Button, {
  color: 'red',
  hoverStyle: {
    color: 'white' // This doesn't work
  }
});
```

Typescript error:
```
Object literal may only specify known properties, but 'color' does not exist in type 'WithThemeValues<StackStyleBase> & { size?: number | SizeTokens | undefined; variant?: "outlined" | undefined; disabled?: boolean | undefined; ... 14 more ...; chromeless?: boolean | ... 1 more ... | undefined; } & WithShorthands<...>'. Did you mean to write 'col'?ts(2561)
```

### Expected Behavior

`color` prop to be supported for web in `hoverStyle`, `pressStyle`, etc

### Tamagui Version

```markdown
1.93.3
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://codesandbox.io/p/devbox/immutable-firefly-2rhf3s?workspaceId=c1dcacd2-e666-4d23-bf20-1389af66ee43
```

**Comment by natew** [comment]
This is actually working as intended, we are going to replace Button in v2 with the composable button API where it doesn't take color directly. `styled` helpers in general don't let you just put any prop in them, they only accept "style" props. It's a bit awkward for now, apologies.

**Comment by tenhsor1** [comment]
Disappointing. How we are supposed to change the font color of a button in any of these css pseudo-classes? @natew

**Comment by natew** [comment]
For now you can use the separate <Button><Button.Text> API, and you can use groups if you'd like to do color change on frame hover:

`<Button group="button"><Button.Text $group-button-hover={{}}>`

Of course this is nicer to do abstracted into your own Button component.

We had this working at one point, but this API surface is extremely hard to get right, I will look at fixing this but we are almost ready with v2 and have a new `@tamagui/button-next` that's much faster, lighter, and better.
