### ISSUE TITLE
`tamagui.dev` landing page crashes on iOS

### ISSUE THREAD

**Issue by evanrs** [tamagui/tamagui#2780]
### Current Behavior

When viewing [the landing page](https://tamagui.dev) on iOS Safari the site crashes on scroll.

https://github.com/tamagui/tamagui/assets/297455/b1e90089-59df-4e94-83b6-db015f13467e

### Expected Behavior

Not crashing on scroll 😬

### Tamagui Version

Unknown version, assumed to match current head [1.102.1](https://github.com/tamagui/tamagui/blob/f36bfaf4dcb88337ce335bb6fadad9e508f0c44f/code/tamagui.dev/package.json#L51)

### Platform (Web, iOS, Android)

```markdown
iOS
```

### Reproduction

```markdown
1. Open Safari on an iOS device running 17.5.1 (does not occur in simulator on Apple Silicon) 
2. disable all browser extensions
3. open a private window
4. navigate to https://tamagui.dev
5. scroll at any speed to the bottom of the page
6. it should crash midway
```

### System Info

```markdown
Model: iPhone 15 Pro Max
iOS Version: 17.5.1
```

**Comment by natew** [comment]
This has been fixed! can't replicate with an SE
