### ISSUE TITLE
ScrollView type cannot be used with `React.forwardRef`

### ISSUE THREAD

**Issue by lindskogen** [tamagui/tamagui#2783]
### Current Behavior

```
Type 'ForwardedRef<ScrollView>' is not assignable to type 'LegacyRef<ScrollView> | undefined'.
  Type 'MutableRefObject<ScrollView | null>' is not assignable to type 'LegacyRef<ScrollView> | undefined'.
    Type 'MutableRefObject<ScrollView | null>' is not assignable to type 'RefObject<ScrollView>'.
      Types of property 'current' are incompatible.
        Type 'import("/project/sandbox/node_modules/@tamagui/scroll-view/types/ScrollView").ScrollView | null' is not assignable to type 'import("/project/sandbox/node_modules/react-native/Libraries/Components/ScrollView/ScrollView").ScrollView | null'.
          Type 'ScrollView' is missing the following properties from type 'ScrollView': scrollToEnd, flashScrollIndicators, getScrollResponder, getScrollableNode, and 37 more.typescript(2322)
index.d.ts(303, 9): The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & Omit<TamaguiComponentPropsBaseBase & ScrollViewProps, "contentContainerStyle" | keyof StackStyleBase | "fullscreen"> & ... 5 more ... & RefAttributes<...>'
```

### Expected Behavior

I expect passing ref would work without type errors.

### Tamagui Version

```markdown
1.102.1
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

Basically I expect this to work:

```tsx

import { forwardRef } from 'react'
import { ScrollView } from 'tamagui'

export const Screen = forwardRef<ScrollView, {}>((props, ref) => {
  return <ScrollView ref={ref}></ScrollView>
})
```

Sandbox link with repro here: (`apps/next/app/Screen.tsx`)

[Sandbox link](https://codesandbox.io/p/devbox/interesting-pasteur-9rs6f3?workspaceId=730ced8c-4fc8-4ac7-b600-ca5dad4fd76d&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyh9k1xq00053b6kwxrjqiko%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyh9k1xq00023b6k28qh2yu2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyh9k1xq00033b6k9xa4lx2v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyh9k1xq00043b6kbmzucsly%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyh9k1xq00023b6k28qh2yu2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyh9k1xp00013b6k5i9fmgbr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clyh9uu7m00473b6knihfhzto%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fapps%252Fnext%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clyh9k1xq00023b6k28qh2yu2%2522%252C%2522activeTabId%2522%253A%2522clyh9uu7m00473b6knihfhzto%2522%257D%252C%2522clyh9k1xq00043b6kbmzucsly%2522%253A%257B%2522id%2522%253A%2522clyh9k1xq00043b6kbmzucsly%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clyh9k1xq00033b6k9xa4lx2v%2522%253A%257B%2522id%2522%253A%2522clyh9k1xq00033b6k9xa4lx2v%2522%252C%2522activeTabId%2522%253A%2522clyh9kw25002g3b6k91krq0g7%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clyh9kw25002g3b6k91krq0g7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### System Info

```markdown
I forked the codesandbox repro base and didn't allow me to run the `envinfo` command.
```

**Comment by natew** [comment]
fixed in 893362851ce9e2a19508fc6720db82d96d5fe3e4 will go out in next release!
