### ISSUE TITLE
Paragraph does not respect border-radius in iOS

### ISSUE THREAD

**Issue by dlee** [tamagui/tamagui#2790]
The expo-router starter has a `<Paragraph>` element with a `br=""` prop, but the border-radius is not being respected in iOS. Either the Paragraph component should be fixed in order to support border-radius, or the starter example should not use the `br` prop since it's not supported.

See how it's being rendered (the blue `tamagui.config.ts`):

![Simulator Screenshot - iPhone 12 mini - 2024-07-13 at 12 52 21](https://github.com/user-attachments/assets/70bc59a5-4538-45f8-8d1c-7f46447d2274)

Here's the code:

https://github.com/tamagui/tamagui/blob/bdf45e1bfa51e7f69e2db1021a83290918139f16/code/starters/expo-router/app/(tabs)/index.tsx#L15

**Comment by natew** [comment]
This is unfortunately just a react native issue, and they closed the ticket :/ But until they fix, we can't. Closing as we keep these issues as a backlog of work, but this should automatically work once RN fixes.
