### ISSUE TITLE
Button component is not keyboard focusable on web

### ISSUE THREAD

**Issue by kevinwcyu** [tamagui/tamagui#28]
On web, Button components are not keyboard focusable when tabbing through the screen unless I add a `tag="button"` prop.

As a workaround right now, I'm just re-exporting the Tamagui Button component with the `tag` prop set to `button` like this:

```tsx
import React from 'react'
import { Button as TButton, ButtonProps } from 'tamagui'

export const Button = (props: ButtonProps) => {
  return <TButton {...props} tag="button" />
}
```

**Comment by natew** [comment]
This should be fixed in alpha.40, if not feel free to re-open.
