### ISSUE TITLE
tamagui.dev/docs site color scheme is unreadable (Chrome and Firefox tested)

### ISSUE THREAD

**Issue by tommmyngo** [tamagui/tamagui#2804]
### Current Behavior

Can't really read much with most content blending in with the background
![Screenshot_2024-07-22-18-29-21_5460x3840](https://github.com/user-attachments/assets/3d626d8c-a479-4cb4-bdd5-a495f5e65343)

Reproducible in Chrome and Firefox, PC and Mobile

### Expected Behavior

Something readable

### Tamagui Version

```markdown
docs site
```

### Platform (Web, iOS, Android)

```markdown
All
```

### Reproduction

```markdown
https://tamagui.dev/docs/intro/introduction
```

**Comment by just-toby** [comment]
pretty sure this is fixed now
