### ISSUE TITLE
Tamagui flex behaves different from react-native flex

### ISSUE THREAD

**Issue by TimoGlastra** [tamagui/tamagui#2806]
### Current Behavior

The flex behaviour (when using `flex={X}` on a tamagui component behaves different from setting `style={{ flex: X }}` (at least on web).  This is not an issue with flex working different than flex on web, there is an inconsistency between using flex from tamagui and flex from react native.

Instead setting `flexGrow={X} flexShrink={1} flexBasis={0}` (as is [documented in react native](https://reactnative.dev/docs/layout-props#flex)) does work:
> When flex is a positive number, it makes the component flexible, and it will be sized proportional to its flex value. So a component with flex set to 2 will take twice the space as a component with flex set to 1. flex: <positive number> equates to flexGrow: <positive number>, flexShrink: 1, flexBasis: 0.

I would expect flex in Tamagui to behave the same as setting `style={{ flex: X }}` on a component. However when using `flex={X}` with tamagui it will adjust the size based on the content of elements. But this makes it jump around if you add/remove elements.

https://github.com/user-attachments/assets/86f1ae96-c983-46e0-902b-815edf14434b

### Expected Behavior

Using `flex={X}` should give the same result as using `style={{ flex: X }}`

### Tamagui Version

```markdown
1.103.3
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

https://codesandbox.io/p/devbox/sad-solomon-lsly9q

The reproduction file is located at `apps/next/app/features/flex/screen.tsx`, this is by default imported as the root screen, so running `yarn dev` in the `apps/next` directory is enough.

The relevant code:

```tsx
import { YStack, Stack, Heading } from 'tamagui'
import { useState } from 'react'

type Mode = 'tamagui-flex' | 'tamagui-flex-extra' | 'react-native-flex'

export function FlexScreen() {
  const [withTamagui, setWithTamagui] = useState<Mode>('tamagui-flex')
  const toggleTamagui = () => setWithTamagui((m) => m === 'tamagui-flex' ? 'tamagui-flex-extra' : m === 'tamagui-flex-extra' ? 'react-native-flex' : 'tamagui-flex')

  if (withTamagui === 'tamagui-flex')
    return (
      <YStack fullscreen flex={1}>
        <Stack backgroundColor="red" flex={2} />
        <Stack backgroundColor="green" flex={1} />
        <Stack backgroundColor="purple" flex={2}>
          <Heading onPress={toggleTamagui}>With Tamagui Flex</Heading>
        </Stack>
      </YStack>
    )

    if (withTamagui === 'tamagui-flex-extra')
      return (
        <YStack fullscreen flex={1}>
          <Stack backgroundColor="red" flexGrow={2} flexBasis={0} flexShrink={1} />
          <Stack backgroundColor="green" flexGrow={1} flexBasis={0} flexShrink={1} />
          <Stack backgroundColor="purple" flexGrow={2} flexBasis={0} flexShrink={1}>
            <Heading onPress={toggleTamagui}>With Tamagui Extra Flex (flexGrow, flexBasis, flexShrink)</Heading>
          </Stack>
        </YStack>
      )

  return (
    <YStack fullscreen flex={1}>
      <Stack backgroundColor="red" style={{ flex: 2 }} />
      <Stack backgroundColor="green" style={{ flex: 1 }} />
      <Stack backgroundColor="purple" style={{ flex: 2 }}>
        <Heading onPress={toggleTamagui}>With React Native Flex</Heading>
      </Stack>
    </YStack>
  )
}
```

### System Info

```markdown
Denied in CodeSandBox
```

**Comment by natew** [comment]
I've added this: https://github.com/tamagui/tamagui/commit/fc89eb23c4100b9624b61c72622057c26ed5588f

I'm not sure how we got off spec here, it's a bit sad. In v2 I'll have to make this the default, we are also working on a web-aligned spec as RN is moving that direction for v2.

**Comment by dani-mp** [comment]
I'm a bit confused because this was working until very recently, no? When was this breaking change introduced?

**Comment by natew** [comment]
It definitely hasn’t changed recently, I’ll have to go back and look through history.

**Comment by natew** [comment]
Went back 5k commits and it’s been like this. Will have to be a change for v2. There’s a setting now to control it.

**Comment by dani-mp** [comment]
You're probably right, but I had a view like this (tested only web, as I was building a prototype):
```
      <YStack flex={1} alignItems="center">
        <YStack maxWidth={480} width="100%" flex={1} gap="$2">
          <H3 textAlign="center" padding="$3">
            TITLE
          </H3>
          <YStack flex={1} paddingHorizontal="$3" gap="$3" overflow="scroll">
            {body}
          </YStack>
          <XStack
            paddingHorizontal="$3"
            paddingVertical="$2"
            alignItems="center"
            gap="$2"
          >
            {buttons}
          </XStack>
        </YStack>
      </YStack>
```
and the flex behavior was what I expected. If you see the component, the view has like a header, a body and a footer. The body takes the whole space available and scrolls if needed.

This was working for me, had the prototype deployed and everything. Then I had a dependabot update that looked pretty minor so I just merged it (yolo) and some hours later I realized the body part wasn't taking the whole space available anymore, and was just as tall as its children. 

<img width="614" alt="Screenshot 2024-07-25 at 11 49 52" src="https://github.com/user-attachments/assets/4526af15-d83e-4845-84c8-86447106f633">

To fix it, I had to upgrade again and use the new config you mentioned above.

Maybe I'm missing something but this is what confused me, it was definitely working before, otherwise I wouldn't have start looking for the fix and see this issue.

**Comment by natew** [comment]
I went back in increments of 1,000 commits to 7,000 commits ago and it was always this way, so not sure what's going on there but if you can find the version that has that let me know.

**Comment by natew** [comment]
Closing as this is behind a setting for now `createTamagui({ settings: { styleCompat: 'react-native' } })`, in v2 I'll make this default likely.

**Comment by TimoGlastra** [comment]
I tested it with the new setting and this now works as expected! Thank you for the quick fix
