### ISSUE TITLE
A way to know deployment target

### ISSUE THREAD

**Issue by ayushsharma82** [tamagui/tamagui#281]
Hi there!

tamagui looks reaaallly good and i'm excited to use it for my next project.

Q: Is there any way by which we can know the deployment target within React ( i.e. native or web )? I basically want to do conditional rendering based on native or web version.

Regards,
Ayush

**Comment by dohomi** [comment]
@ayushsharma82 you can use https://reactnative.dev/docs/platform-specific-code for that

**Comment by ayushsharma82** [comment]
Completely forgot about that haha. Thanks for the reference.
