### ISSUE TITLE
docs: document Sheet unmountChildrenWhenHidden prop 

### ISSUE THREAD

**Issue by giacomocerquone** [tamagui/tamagui#2836]
### Current Behavior

Right now, whatever component you render within a Sheet is not unmounted when the sheet animates out.
This is a problem because all the views that needs an ephemeral state, think about forms for example, never lose their state unless establishing bad practices in devland's code.

This mechanism, imposed by tamagui, leads to writing code for the inner component that either produce antipatterns such as synchronizing props with state or forces the developer to move values within a context and then use the context in the component causing weird content shifts during sheet's animations.

Another very popular and famous library used to implement sheets does this. Take a look:

NON TAMAGUI'S SHEET

https://github.com/user-attachments/assets/ee9c50c0-77cc-4569-8789-499297818475

TAMAGUI'S SHEET

https://github.com/user-attachments/assets/6c109975-c0f3-4391-841b-563bc3125ab8

### Expected Behavior

I expect the components to unmount after the animation and to remount before the animation.

Either that or having the possibility to hook into callbacks such as "willSheetShow" and "didSheetHide" so to manually implement that in devland

### Tamagui Version

```markdown
latest: 1.108.0
```

### Platform (Web, iOS, Android)

```markdown
iOS, Android and web
```

### Reproduction

```typescript
import { ChevronDown } from "@tamagui/lucide-icons";
import { Sheet } from "@tamagui/sheet";
import { useMemo, useState } from "react";
import {
  Button,
  TamaguiProvider,
  XStack,
  YStack,
  createTamagui,
  Text,
  Button
} from "tamagui";
import { config } from "@tamagui/config/v3";
import StatefulComp from "components/StatefulComp";

function StatefulComp() {
  const [state, setstate] = useState("lol");

  return (
    <>
      <Button
        title="change state"
        onPress={() => {
          setstate((prev) => (prev === "lol" ? "asd" : "lol"));
        }}
      />
      <Text>{state}</Text>
    </>
  );
}

// you usually export this from a tamagui.config.ts file
const tamaguiConfig = createTamagui(config);

// TypeScript types across all Tamagui APIs
type Conf = typeof tamaguiConfig;
declare module "@tamagui/core" {
  interface TamaguiCustomConfig extends Conf {}
}

const spModes = ["percent", "constant", "fit", "mixed"] as const;

const SheetDemo = () => {
  const [position, setPosition] = useState(0);
  const [open, setOpen] = useState(false);
  const [modal, setModal] = useState(true);
  const [innerOpen, setInnerOpen] = useState(false);
  const [snapPointsMode, setSnapPointsMode] =
    useState<(typeof spModes)[number]>("percent");

  const snapPoints = useMemo(() => [25, 50], []);

  return (
    <TamaguiProvider config={tamaguiConfig}>
      <YStack space>
        <XStack space $sm={{ flexDirection: "column", alignItems: "center" }}>
          <Button onPress={() => setOpen(true)}>Open</Button>
        </XStack>
      </YStack>

      <Sheet
        forceRemoveScrollEnabled={open}
        modal={modal}
        open={open}
        onOpenChange={setOpen}
        snapPoints={snapPoints}
        snapPointsMode={snapPointsMode}
        dismissOnSnapToBottom
        position={position}
        onPositionChange={setPosition}
        zIndex={100_000}
        animation="medium"
      >
        <Sheet.Overlay
          animation="lazy"
          enterStyle={{ opacity: 0 }}
          exitStyle={{ opacity: 0 }}
        />
        <Sheet.Handle />
        <Sheet.Frame
          padding="$4"
          justifyContent="center"
          alignItems="center"
          space="$5"
        >
          <Button
            size="$6"
            circular
            icon={ChevronDown}
            onPress={() => setOpen(false)}
          />
          <StatefulComp />
        </Sheet.Frame>
      </Sheet>
    </TamaguiProvider>
  );
};

export default SheetDemo;
```

### System Info

```markdown
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13500
    Memory: 2.00 GB / 15.65 GB
  Binaries:
    Node: 20.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.6.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

**Comment by giacomocerquone** [comment]
So, the preferred solution IMHO should be within tamagui, forcing the devs to adhere to this unmount/mount pattern which is idiomatic for react.

If this is hard to achieve in the current state of the code, it should be easy to provide at least the callbacks for willOpen and didClose.

Let me know what do you think about this @natew

**Comment by giacomocerquone** [comment]
Wow I've just noticed there is an undocumented "unmountChildrenWhenHidden" 😰

Let's treat this as a documentation task (even though I think it should be true by default but I get it's a dangerous breaking change now)

**Comment by natew** [comment]
Not sure that’s desired to be on by default but definitely would love a PR with docs. 

Reason is the contents can often be expensive to render, and that would cause delays to rendering them. You want instant reactions as it opens and closes so ideally you have the content already rendered.

**Comment by natew** [comment]
We should definitely wrap the hide in a startTransition though

**Comment by giacomocerquone** [comment]
> Not sure that’s desired to be on by default but definitely would love a PR with docs.
> 
> Reason is the contents can often be expensive to render, and that would cause delays to rendering them. You want instant reactions as it opens and closes so ideally you have the content already rendered.

While brainstorming ways to implement this behaviour (before discovering that there was already a prop) I thought the same about rendering expensive components that would have result in delaying too much the sheet's opening.

To address this, I thought about providing devs with a couple of callbacks, like didShow and didHide. These would allow inserting a placeholder component during the opening phase (something that renders quickly, like a skeleton loader) and then swap it out with the actual component later. This approach would be used with `unmountChildrenWhenHidden=false`, as it effectively lets developers manage the unmounting process manually and more flexibly.

Wdyt?
