### ISSUE TITLE
[BUG] CSS Animations with exit/enter styles does not work

### ISSUE THREAD

**Issue by MantasMikal** [tamagui/tamagui#2863]
### Current Behavior

When using CSS animations driver, Tamagui components with enter/exit styles do not work.
See [the example](https://github.com/MantasMikal/tamagui-css-animations-popover-bug) with popover

Probably related to: 
https://github.com/tamagui/tamagui/issues/2593
https://github.com/tamagui/tamagui/issues/2660

Removing t_unmounted class from the root tag does fix it.

### Tamagui Version

```markdown
1.108.4
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
1. Clone https://github.com/MantasMikal/tamagui-css-animations-popover-bug
2. Click on Popover
```

### System Info

```markdown
System:
    OS: macOS 14.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 81.53 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 4.1.0 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 10.0.0 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 9.2.0 - ~/Library/pnpm/pnpm
    bun: 1.0.7 - ~/.bun/bin/bun
    Watchman: 2024.06.10.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 127.0.6533.120
    Safari: 17.6
  npmPackages:
    @babel/runtime: ^7.24.6 => 7.24.6
    @manypkg/cli: ^0.21.4 => 0.21.4
    check-dependency-version-consistency: ^4.1.0 => 4.1.0
    eslint: ^9.3.0 => 9.4.0
    node-gyp: ^10.1.0 => 10.1.0
    prettier: ^3.2.5 => 3.3.0
    turbo: ^1.13.3 => 1.13.4
    typescript: ^5.4.5 => 5.4.5
```

**Comment by natew** [comment]
Fixed coming out in 1.112.6, the fix is odd but it fixed in react 19, i thought it was a 19-only issue. We'll need to add tests for css actually animating not just applying the class and changing the style.
