### ISSUE TITLE
[bug] npm create tamagui-app@latest fails on windows

### ISSUE THREAD

**Issue by jdinard** [tamagui/tamagui#290]
**Describe the bug**
npm create tamagui-app@latest fails on windows

**To Reproduce**
Run
```
npm create tamagui-app@latest
```

Seems like a relatively straightforward. It fails because of the new line character

 ProcessOutput {
  stdout: '',
  stderr: "fatal: could not create leading directories of '$'C:\\\\Users\\\\<userfile>\\\\.tamagui\\\\tamagui'': Invalid argument\n",
  signal: null,
  exitCode: 128 (Invalid exit argument)
}
child_process.js:866
    throw err;

**Comment by natew** [comment]
Next release fixes this it was a zx issue: https://github.com/google/zx/releases
