### ISSUE TITLE
remix starter does not work

### ISSUE THREAD

**Issue by steveliles** [tamagui/tamagui#2902]
### Current Behavior

using `npm create tamagui@latest` to create a remix app does not work

### Expected Behavior

it should generate a working remix app

### Tamagui Version

```markdown
latest
```

### Platform (Web, iOS, Android)

```markdown
web/remix
```

### Reproduction

```markdown
1. use `npm create tamagui@latest` 
2. choose the remix starter option from the menu
3. when install complete, start remix with `yarn dev` 
4. See a bunch of errors: "Error bundling tamagui config: Cannot find module 'tamagui'" and "Internal server error: Must provide components"
```

### System Info

```markdown
System:
    OS: macOS 14.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.89 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.8.0 - ~/.nvm/versions/node/v22.8.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.8.0/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v22.8.0/bin/npm
  Browsers:
    Chrome: 128.0.6613.120
    Safari: 17.3.1
  npmPackages:
    @biomejs/biome: ^1.5.3 => 1.8.3 
    @remix-run/dev: ^2.10.3 => 2.11.2 
    @remix-run/node: ^2.10.3 => 2.11.2 
    @remix-run/react: ^2.10.3 => 2.11.2 
    @remix-run/serve: ^2.10.3 => 2.11.2 
    @tamagui/config: ^1.110.2 => 1.110.2 
    @tamagui/core: ^1.110.2 => 1.110.2 
    @tamagui/vite-plugin: ^1.110.2 => 1.110.2 
    @types/react: ^18.2.55 => 18.3.5 
    @types/react-dom: ^18.2.19 => 18.3.0 
    isbot: ^4.1.0 => 4.4.0 
    react: ^18.2.0 || ^19.0.0 => 18.3.1 
    react-dom: ^18.2.0 || ^19.0.0 => 18.3.1 
    typescript: ^5.5.2 => 5.5.4 
    vite: 6.0.0-alpha.18 => 6.0.0-alpha.18 
    vite-bundle-analyzer: ^0.9.2 => 0.9.4 
    vite-plugin-commonjs: ^0.10.1 => 0.10.1 
    vite-tsconfig-paths: ^4.3.2 => 4.3.2
```

**Comment by dennis-gonzales** [comment]
Same here, able to replicate.
![image](https://github.com/user-attachments/assets/db894d4a-e4b9-4557-8ad3-f38a3db81a9f)

**Comment by dennis-gonzales** [comment]
Same here, receiving the same error as op

**Comment by jonsherrard** [comment]
Hi both,

Just testing this and unfortunately "works on my machine", with Node 22 and Yarn 1.22.x and 3.5x and 4.1.x and 4.4x

Could you tell me your:

Operating System
Node version
Yarn version 

@dennis-gonzales ?

@steveliles could you send me the full output of this?

4. See a bunch of errors: "Error bundling tamagui config: Cannot find module 'tamagui'" and "Internal server error: Must provide components"

**Comment by dennis-gonzales** [comment]
> Hi both,
> 
> Just testing this and unfortunately "works on my machine", with Node 22 and Yarn 1.22.x and 3.5x and 4.1.x and 4.4x
> 
> Could you tell me your:
> 
> Operating System Node version Yarn version
> 
> @dennis-gonzales ?
> 
> @steveliles could you send me the full output of this?
> 
> 4. See a bunch of errors: "Error bundling tamagui config: Cannot find module 'tamagui'" and "Internal server error: Must provide components"

My OS is `Windows 11` with Version `23H2 (OS Build 22631.4112)`
Node version of `v20.12.2`
And yarn version `1.22.19`

**Comment by jonsherrard** [comment]
Fixed in #2914

**Comment by guillempuche** [comment]
Now template installs everything well in v1.112.22, but when `yarn dev` I get:

```sh
yarn dev
Error: @tamagui/static tried to access @tamagui/web, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @tamagui/web
Required by: @tamagui/static@virtual:
...
```

**Comment by gh-osama** [comment]
+1 to @guillempuche. getting same issue. setup:
latest mac os, node 22, yarn 4.5

**Comment by guillempuche** [comment]
@gh-osama, there's an open issue #3003
