### ISSUE TITLE
Warning: React does not recognize the textAlign prop on a DOM element.

### ISSUE THREAD

**Issue by j3sch** [tamagui/tamagui#2908]
### Current Behavior

In the latest version, Tamagui always causes the following React warning in the terminal:

`Warning: React does not recognize the `textAlign` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `textalign` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

After downgrading, the error has disappeared. 

### Tamagui Version

```markdown
v1.110.2
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
npm create tamagui@latest
```

**Comment by knksmith57** [comment]
+1 we're seeing this too, also now running `1.110.2`.

**Comment by natew** [comment]
This is fixed in latest

**Comment by gcoakleyjr** [comment]
I just upgrade to v1.111.11 and I currently see this error everywhere on a lot of my components.

**Comment by therealpurplemana** [comment]
I'm seeing this also.  Was there a resolution?

**Comment by mosleim** [comment]
> This is fixed in latest

this happened  again at version: 1.125.5

**Comment by velcis** [comment]
I'm on 1.126.13, and have this error.
