### ISSUE TITLE
Error: Cannot access NextTamaguiProvider.propTypes on the server.

### ISSUE THREAD

**Issue by aspirisen** [tamagui/tamagui#2912]
### Current Behavior

When I run fresh application I see the error
<img width="1036" alt="image" src="https://github.com/user-attachments/assets/a6843f4c-95f3-421a-88a8-242f605eff94">

### Expected Behavior

No errors an app is running 

### Tamagui Version

```markdown
1.110.3
```

### Platform (Web, iOS, Android)

```markdown
web (nextjs)
```

### Reproduction

```markdown
Run `npm create tamagui@latest`
Using https://www.npmjs.com/package/npm-check-updates update all the deps `ncu -u --deep`
Revert back app package version to `"app": "0.0.0",`
Run yarn install
Run nextjs application
```

### System Info

```markdown
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 18.58 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.7.0 - ~/.nvm/versions/node/v22.7.0/bin/node
    Yarn: 4.1.0 - ~/.nvm/versions/node/v22.7.0/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v22.7.0/bin/npm
    pnpm: 9.9.0 - ~/Library/pnpm/pnpm
    bun: 1.1.18 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 128.0.6613.120
    Chrome Canary: 130.0.6707.0
    Safari: 17.6
  npmPackages:
    app: 0.1.0 => 0.1.0 
    react-native: 0.75.2 => 0.75.2
```

**Comment by jonsherrard** [comment]
Hi there, I wouldn't recommend updating all dependencies in parallel like that - it's unlikely they'll all work together without errors.

I'm going to take a look at updating the the base Next.js version in the starters and some other dependencies. 

But for the most part I would stick with the deps you get from create tamagui and then update individual dependencies as you need.
