### ISSUE TITLE
[bug] BottomSheet with inputs is impossible to use on web mobile

### ISSUE THREAD

**Issue by apperside** [tamagui/tamagui#292]
**Describe the bug**
Hello,
I am trying to implement some forms inside the awesome BottomSheet component.
It works perfectly in desktop, it works pretty well on native side (beside some common problems with scroll views in react native) , but for some reason the web version is unusable on mobile devices.

To see the bug in action open this link [https://tamagui-bug-demo.vercel.app](https://tamagui-bug-demo.vercel.app), open the bottom sheet and try typing something in the textboxes..

I tried playing with focus related props, but didn't manage to understand what's going on.

Here is the source code https://github.com/apperside/tamagui-image-bug (don't mind the repo name, it was created for an older issue 😀), all the relevant code is in /packages/app/features/home/screen.tsx

**To Reproduce**

open this link  https://github.com/apperside/tamagui-image-bug, open the bottom sheet and try typing something in the textboxes

**Comment by apperside** [comment]
Hello @natew,
any update on this?

Thank you

**Comment by PhungVanHoa** [comment]
Any news?

**Comment by natew** [comment]
I just tested the link but worked for me well besides the red colors. Can you re-open with latest rc if still valid?

**Comment by apperside** [comment]
Tested on rc-8 and it seem it's working now, you really deserve a big thanks!
