### ISSUE TITLE
SSR styles not applied in Next.js App Router when deployed to Vercel

### ISSUE THREAD

**Issue by obonakdar2** [tamagui/tamagui#2938]
### Current Behavior

When deploying my Tamagui project using Next.js’ App Router to Vercel, styles are not applied during server-side rendering. This issue only occurs when deploying to Vercel; locally, the build works as expected, and the styles render correctly. Using the Page Router instead of the App Router avoids the issue.
[
![tamagui](https://github.com/user-attachments/assets/654dfa6a-3c13-4ee3-9432-2f77a4997b9f)
](url)

### Expected Behavior

Styles should be properly applied during server-side rendering (SSR) when using the Next.js App Router, whether deployed locally or on Vercel, consistent with how it works when using the Page Router.

### Tamagui Version

```markdown
"tamagui": "^1.112.0",
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
Clone the starter repository from the following link: https://github.com/tamagui/starter-free

some optional steps:
Upgrade Tamagui by running the following command: yarn upgrade:tamagui
Delete the Page Router from the project and use the App Router exclusively

Deploy the project to Vercel
In the Vercel build settings, use the following build command:
cd ../.. && turbo run build --filter=next-app
After deployment, visit the deployed site and observe that the styles are not applied in SSR-rendered pages (you can see SSR results by disabling javascript in browser).
However, running the project locally with:
yarn web:prod && cd apps/next && yarn start
works as expected, and the styles are applied correctly.
```

**Comment by obonakdar2** [comment]
from https://www.youtube.com/watch?v=AW1IthRgPT8 video I realized that I must command
exclude: process.env.NODE_ENV === 'production' ? 'design-system' : null,
line in nextTamaguiProvider.tsx file to solve the issue, thanks to him

**Comment by cgorrieri** [comment]
I am not sure if something has change but following the NextJs guide and trying with `exclude` or no exclude, the FOUC is consistently here with styles loaded via Javascript.

Since `NextThemeProvider` is using `useState` inside, I don't understand the magic that allows for SSR.

My packages:
```
    "@tamagui/config": "^1.126.13",
    "@tamagui/next-plugin": "^1.126.13",
    "next": "15.3.3",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-native": "^0.79.2",
    "react-native-web": "^0.20.0",
    "tamagui": "^1.126.13"
```
