### ISSUE TITLE
Serrated in android

### ISSUE THREAD

**Issue by xiongxiongDream** [tamagui/tamagui#2945]
### Current Behavior

![1727346476398](https://github.com/user-attachments/assets/51a49cf1-8e70-4e13-a315-02ed2000ab69)

Why is there a jagged display on the android side after tamagui sets borderRadius, but there is no such problem on the ios/web side. Do I need to configure any parameters?

### Tamagui Version

```markdown
1.108.3
```

### Platform (Web, iOS, Android)

```markdown
Android
```

### Reproduction

```markdown
Serrated in android
```

**Comment by jonsherrard** [comment]
Hi there,

Tamagui simply sets Border Radius on React Native views and doesn't control rendering fidelity in any way.

This could be to do with device/simulator resolution or display settings.
