### ISSUE TITLE
In Web only (Vite) mode missing platform="touch" breaks production mode

### ISSUE THREAD

**Issue by dohomi** [tamagui/tamagui#2963]
### Current Behavior

As discussed on Discord, the Adapt component has a platform prop which currently breaks web if not provided. This only appears in production mode.

### Expected Behavior

platform="touch" is not required

### Tamagui Version

```markdown
This issue appears from Tamagui > 1.111.11
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
in progress..
```

**Comment by dohomi** [comment]
it seems the issue breaks in production in case the developer console is on and the screen is wider than the `when` statement.

**Comment by natew** [comment]
this should be fixed in latest versions, lmk if not
