### ISSUE TITLE
React does not recognize the WebkitBackdropFilter prop on a DOM element.

### ISSUE THREAD

**Issue by Dmitry-GH** [tamagui/tamagui#2971]
### Current Behavior

Hey!
I have a question specific to backdropFilter prop - how we should work with "WebkitBackdropFilter"?

I saw that in this repo we examples, where we can put it in style prop like this:
```jsx
<View
backdropFilter={'blur(20px)'}
style={{
    WebkitBackdropFilter: 'blur(20px)',
   }}
 />
```
But React throws error then: 

> Warning: React does not recognize the `WebkitBackdropFilter` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `webkitbackdropfilter` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### Expected Behavior

No error from React for WebkitBackdropFilter

### Tamagui Version

```markdown
1.112.22
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://codesandbox.io/p/devbox/upbeat-breeze-qy3qhh?workspaceId=cf182979-6019-4b13-9ec5-14073d779215

Observe the error in the console.
Props added for "Link to user" button in:
/packages/app/features/home/screen.tsx
```

**Comment by jonsherrard** [comment]
you could try

```tsx
<Stack $platform-web={{
  WebkitBackdropFilter: 'blur(20px)`
}} />
