### ISSUE TITLE
`yarn next build` throws with `next/font`

### ISSUE THREAD

**Issue by nandorojo** [tamagui/tamagui#2974]
### Current Behavior

If you use `next/font` in your config, then `yarn next build` will throw.

```sh
TypeError: Cannot read properties of undefined (reading '0')
    at simpleHash (/Users/path/to/node_modules/@tamagui/simple-hash/dist/cjs/index.js:26:6)
    at createCSSVariable (/Users/path/to/node_modules/@tamagui/web/dist/cjs/createVariable.js:79:46)
    at variableToCSS (/Users/path/to/node_modules/@tamagui/web/dist/cjs/helpers/registerCSSVariable.js:25:139)
    at /Users/path/to/node_modules/@tamagui/web/dist/cjs/createTamagui.js:67:162
    at createTamagui (/Users/path/to/node_modules/@tamagui/web/dist/cjs/createTamagui.js:107:5)
    at Object.loadTamaguiSync (/Users/path/to/node_modules/@tamagui/static/dist/extractor/loadTamagui.js:133:11)
    at TamaguiPlugin.apply (/Users/path/to/node_modules/tamagui-loader/dist/cjs/TamaguiPlugin.js:101:31)
    at createCompiler (/Users/path/to/node_modules/next/dist/compiled/webpack/bundle5.js:28:1467449)
    at create (/Users/path/to/node_modules/next/dist/compiled/webpack/bundle5.js:28:1468029)
    at webpack (/Users/path/to/node_modules/next/dist/compiled/webpack/bundle5.js:28:1468340)
    at f (/Users/path/to/node_modules/next/dist/compiled/webpack/bundle5.js:28:895636)
    at /Users/path/to/node_modules/next/dist/build/compiler.js:35:47
    at new Promise (<anonymous>)
    at runCompiler (/Users/path/to/node_modules/next/dist/build/compiler.js:34:12)
    at /Users/path/to/node_modules/next/dist/build/webpack-build/impl.js:242:83
    at async Span.traceAsyncFn (/Users/path/to/node_modules/next/dist/trace/trace.js:154:20)
    at async webpackBuildImpl (/Users/path/to/node_modules/next/dist/build/webpack-build/impl.js:183:5)
    at async /Users/path/to/node_modules/next/dist/build/index.js:990:111
    at async Span.traceAsyncFn (/Users/path/to/node_modules/next/dist/trace/trace.js:154:20)
    at async build (/Users/path/to/node_modules/next/dist/build/index.js:352:9)
```

### Expected Behavior

Should work fine with `next/font`, though this is admittedly challenging potentially since `next/font` does some magic. Worth a pass to see if it's possible I think.

Next.js uses a build-time plugin for the font code to transform it into special code etc, so I think the problem is that `withTamagui` is running `esbuild` before this transform is done.

### Tamagui Version

```markdown
1.113.0
```

### Platform (Web, iOS, Android)

```markdown
Web, Next.js
```

### Reproduction

https://codesandbox.io/p/devbox/intelligent-mendeleev-xv6wtn?workspaceId=35a4fe1b-7440-42d4-b5e7-e00c1af26e95

1. See `tamagui.config.ts` to see what was changed in the code
2. `cd apps/next`
3. yarn next build

#### Custom reproduction

1. `yarn add geist`
4. Add `'geist'` to `transpilePackages` in `next.config.js
5. In `tamagui.config.ts`

```ts
import { GeistSans } from 'geist/font/sans'

const monoFont = createFont({
  family: GeistSans.style.fontFamily,
  letterSpacing: {},
  lineHeight: {},
  size: {},

  weight: {},
  face: {},
})
```

Then pass that to your `fonts` and it'll break in build mode.

6. **Run `yarn next build`** in the web folder. Dev mode works fine, web breaks.

**Comment by jonsherrard** [comment]
In your example would you ever aspire to use expo as well?

I agree with your instinct that importing next/local/font directly into tamagui.config is going to cause trouble.

Can you import geist into your next layout and then just do something like 

const body = createFont({
  family: 'Geist',
  size: {
    1: 12,
    2: 14,
    3: 16,
    4: 20,
    5: 24,
    6: 32,
    7: 48,
    8: 64,
  },
})


in tamagui.config

**Comment by nandorojo** [comment]
For native, I have a separate `.native.tsx` file which just passes strings since `family` in `createFont` is just for web.

> Can you import geist into your next layout

This would be fine if I were using app router, however, I've had issues with Tamagui + app router, so I switched back to pages...with pages router, you can't apply the font to the root `html` tag, since it has to go inside of `_app.tsx`.

Maybe I can try app router again.

**Comment by jonsherrard** [comment]
Looks like there's a fix to get it loading in pages router here: https://github.com/vercel/geist-font/issues/59 @nandorojo

**Comment by nandorojo** [comment]
Sorry to clarify, I already implemented the fix linked there (thanks for sending).

The issue I've had with using `pages_app.tsx` is that it doesn't apply the styles to the **root body tag**, which is necessary, since Radix/modals mount to this outer `body` tag, so the `variables` aren't scoped to it. I managed to fix the build issues, but just have had CSS scoping issues. This should be fixable though...let me see if I can just use a plain style tag or something

**Comment by nandorojo** [comment]
I think I can fix it it using a style tag string inside of `_app.tsx`, will let you know if this does it and I'll close if so

**Comment by nandorojo** [comment]
Here's how I fixed it:

1. Created `fontVars`:

```
export const fontVars = {
  body: '--font-body',
  heading: '--font-heading',
  mono: '--font-mono',
} as const
```

2. In `tamagui.config.ts`, when calling `createFont`, I passed that value to `family`:

```ts
const headingFont = createFont({ family: fontVars.heading, ... })
```

This way tamagui only deals with a variable I declare but never needs to import anything from `next/font`.

3. When declaring the Next.js font:

```tsx
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
import localFont from 'next/font/local'

const headingFont = localFont({
  ...
})


export const fonts = {
  heading: headingFont.style.fontFamily,
  body: GeistMono.style.fontFamily,
  mono: GeistMono.style.fontFamily,
} satisfies Record<keyof typeof fontVars, string>
```

Then, in `_app.tsx`

```tsx
<style global jsx>
{`
  :root {
    ${entries(fonts)
      .map(([varName, family]) => `${fontVars[varName]}: ${family};`)
      .join('\n')}
  }
  html {
    font-family: var(${fontVars.body});
  }
`}
</style>
```

**Comment by nandorojo** [comment]
For anyone wondering why I didn't use the normal `variable` approach recommended by the Next.js docs: it's because this gets set on the `div` inside of `_app.tsx`, but it does **not apply** to the root `body` tag. So `radix` components etc wouldn't have inherited font styles since they all mount to the root body tag.

Anyway, this approach seems to work haha

**Comment by nandorojo** [comment]
Thanks for the input @jonsherrard!
