### ISSUE TITLE
`$theme-dark` and `$theme-light` not working properly on native

### ISSUE THREAD

**Issue by brianGammon** [tamagui/tamagui#2980]
### Current Behavior

I just upgraded from v1.110.3 to v1.114.1 and noticed a regression related to styling with `$theme-dark` and `$theme-light` props. Example using the code from `app/(tabs)/_layout.tsx` (line 30) in the Expo Router Tamagui starter:
```
<Button mr="$4" bg="$purple8" color="$purple12" $theme-dark={{ bg: '$red8' }}>
  Hello!
</Button>
```
Adding the `$theme-dark={{ bg: '$red8' }}` is making the button background red even when in light mode. Likewise, if you used `$theme-light` it makes the button red even when in dark mode.

### Expected Behavior

The style of the background should use the override in the `$theme-dark` prop, only when in dark mode. In my example above the button should be purple in light mode and red in dark mode.

### Tamagui Version

```markdown
1.114.1
```

### Platform (Web, iOS, Android)

```markdown
iOS and Android only, works fine on web.
```

### Reproduction

```markdown
`npm create tamagui@latest`
Use the Expo-Router example
Open the file `app/(tabs)/_layout.tsx`
Edit the Button on line 30 to use $theme-dark like in my example above
Toggle light and dark mode on the iOS or Android simulator

Honestly you can probably just put a `$theme-dark` or `$theme-light` on anything you have that is running 1.114.1 to reproduce this.
```

### System Info

```markdown
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 110.58 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.5.0 - ~/Library/pnpm/pnpm
    bun: 1.1.15 - ~/.nvm/versions/node/v20.12.2/bin/bun
  Browsers:
    Chrome: 129.0.6668.100
    Safari: 17.6
```

**Comment by natew** [comment]
Fixed in latest

**Comment by brianGammon** [comment]
@natew I'm seeing this problem again too. It was fixed after I reported it (1.117.2), but now I've pulled in 1.120.0 and it's back. Furthermore I'm seeing dark mode issues with the default theme tokens such as '$color1' and '$background' not switching to the dark variants when the mode changes.

**Comment by jackhric** [comment]
Getting the same problem as well.

**Comment by brianGammon** [comment]
Android seems to be working as expected. @jackhric are you also seeing the issue only on iOS?

**Comment by jackhric** [comment]
Yep, issue is on iOS, same configuration as you. With a fresh project from npm create tamagui@latest, the Expo Router navigation follows the theming, but the content doesn't. Very odd.

**Comment by brianGammon** [comment]
Opened a new issue since it is similar but potentially a different issue: https://github.com/tamagui/tamagui/issues/3096
