### ISSUE TITLE
[bug] fill property on lucide-icons not working

### ISSUE THREAD

**Issue by dohomi** [tamagui/tamagui#300]
**Describe the bug**
The property "fill" on lucide-icons is hardcoded to "none". It would be great if the fill property is respected.

**To Reproduce**
Set a `fill={color}` on any lucide-icon

```jsx
<Star color="red" fill="red"/>
```

https://github.com/tamagui/tamagui/blob/master/packages/lucide-icons/src/icons/star.tsx#L41

**Comment by natew** [comment]
I don't think this is a bug, because fill would look weird depending on the icon. For something like Star where there's one shape it would work, but it would totally break others. I don't think they are meant to be used like that.

**Comment by dohomi** [comment]
I'll stick to the mdi icons for now, or maybe the lucide will have a filled star sometimes in the future
