### ISSUE TITLE
[bug] 1.0.1-beta.194 compiler is broken with the use of react-native-svg or @tamagui/lucide-icons   

### ISSUE THREAD

**Issue by dohomi** [tamagui/tamagui#301]
**Describe the bug**
As soon `react-native-svg` is in use (or @tamagui/lucide-icons) of `my/ui` NextJS is not compiling.

**To Reproduce**
Clone https://github.com/dohomi/tamagui-194-bug which is a reproduction of this bug. It essentially only adds one icon into `MyComponent` which breaks NextJS from compiling

The reproduce is the tamagui starter with only one line added to the component:
https://github.com/dohomi/tamagui-194-bug/blob/main/packages/ui/src/MyComponent.tsx#L12

**Comment by natew** [comment]
Fixed in two ways: https://github.com/tamagui/tamagui/commit/0040389044bbf1734010de62c2e9ac141d10a85d https://github.com/tamagui/tamagui/commit/b8c500ffc57dc46c53c612adb30c9823661e0b00
