### ISSUE TITLE
[bug] Styled Input does not apply the passed styles

### ISSUE THREAD

**Issue by apperside** [tamagui/tamagui#302]
**Describe the bug**
When you create a customized `Input` with `styled`, the provided styles are not applied, unless if you pass them inline when instantiating the component.

Here https://tamagui-bug-demo-jybrtd4jz-simonegaspari.vercel.app/ you can see 2 `Input`s: one with just the styles passed in `styled` and one with styles passed inline.

The desired behaviour would be that the cursor starts after the icon, and I'm adding left and right padding for this purpose, but it doesn't work.

Here is a sample repo https://github.com/apperside/tamagui-image-bug (the branch is `input-bug-repro`),
the relevant code is here https://github.com/apperside/tamagui-image-bug/blob/input-bug-repro/packages/app/features/home/SearchBox.tsx , and then 2 instances of this component are added to /packages/app/features/home/screen.tsx like this 

```jsx

<SearchBox  width="100%"/>
<SearchBox px={30} width="100%"/>
```
The first one doesn't have the padding added with `styled`

**System Info (please complete the following information):** 

System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 384.34 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 106.0.1
    Safari: 16.0
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.18.9 
    @manypkg/cli: ^0.19.1 => 0.19.1 
    @types/react: ^18.0.15 => 17.0.21 
    @types/react-native: ^0.69.5 => 0.69.5 
    eslint: ^8.21.0 => 8.21.0 
    prettier: ^2.7.1 => 2.7.1 
    turbo: ^1.4.2 => 1.4.2 
    typescript: ^4.7.4 => 4.7.4 

**Tamagui info**

Tamagui version 1.0.1-beta.193

**Comment by natew** [comment]
Did you set isReactNative? It’s a new requirement as of last versions, added to docs now.

**Comment by apperside** [comment]
No, I didn't set it because I wasn't aware of it :-) 
I'll give it a try, thank you!

**Comment by natew** [comment]
Seems like you're using `tamagui` which should set that up for you already anyway so not that. This is likely something else..

**Comment by dhiyaulhaqZA** [comment]
I got a similar problem. It's fine if i run it on local machine, but the problem appears when I deployed to Vercel. @natew

**Comment by apperside** [comment]
Hello @natew ,
I just tried `isReactNative` flag and it works now, thank you! 

I have a question however: since I am using it in the following way:

```typescript
import { Input, styled, isWeb } from "tamagui"

const MyComponent = styled(
  Input,
  {
    // component styles
  },
  { isReactNative: !isWeb } //<== using built-in flag
)
```
and it seem it works, why doesn't tamagui use that flag internally?
