### ISSUE TITLE
Can be use on React Native CLI project?

### ISSUE THREAD

**Issue by ManuelMGM** [tamagui/tamagui#303]
Hello! I'm wondering if Tamagui can be use on pure React Native CLI projects. I've tried and found following error wrapping my app with Tamagui Provider.

ERROR  Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at _TamaguiProvider (http://localhost:8081/node_modules/tamagui/node_modules/@tamagui/core/dist/cjs/views/TamaguiProvider.bundle?platform=android&app=com.userapp&modulesOnly=true&dev=true&minify=false&runModule=true&shallow=true:55:24)
    at anonymous (http://localhost:8081/node_modules/tamagui/dist/cjs/views/TamaguiProvider.bundle?platform=android&app=com.userapp&modulesOnly=true&dev=true&minify=false&runModule=true&shallow=true:46:24)
    at App (http://localhost:8081/src/App.bundle?platform=android&app=com.userapp&modulesOnly=true&dev=true&minify=false&runModule=true&shallow=true:41:54)
    at RCTView
    at View
    at RCTView
    at View
    at AppContainer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.userapp&modulesOnly=false&runModule=true:88956:36)
    at userapp(RootComponent) (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.userapp&modulesOnly=false&runModule=true:93667:28)
 ERROR  TypeError: Cannot read property 'useEffect' of null

This error is located at:
    in _TamaguiProvider
    in Unknown (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in userapp(RootComponent), js engine: hermes`

I've followed docs for installing, add some tamagui dependencies:  `"@tamagui/babel-plugin": "1.0.1-beta.195",
    "@tamagui/font-inter": "1.0.1-beta.195",
    "@tamagui/shorthands": "1.0.1-beta.195",
    "@tamagui/theme-base": "1.0.1-beta.195"`

and also add expo unimodules.

There is something else I should try?
Thanks!

**Comment by bang88** [comment]
@ManuelMGM Hi, Tamagui works very well on a pure React Native project, you should follow the official site's setup guide.https://tamagui.dev/docs/intro/compiler-install and check out the metro part.

**Comment by junedomingo** [comment]
@ManuelMGM try re-installing `react` and `react-dom`

**Comment by bang88** [comment]
Or using ` npx lernaupdate --dedupe`  to find out a different version

**Comment by natew** [comment]
In general be sure to use Yarn `resolutions` or similar to have only one version of `react` and `react-dom`

**Comment by ankit-gl** [comment]
> I was able to run the application with pure React Native successfully!! Steps I did:
> 
> 1. Create react native app from scratch (i've use typescript template)
>    `npx react-native init mobileWallets --template react-native-template-typescript`
> 2. Install expo unimodules:
>    `npx install-expo-modules@latest`
> 3. Install tamagui and react-dom:
>    `yarn add tamagui react-dom -S -E`
> 4. For quick setup, install tamagui helpers packages:
>    `yarn add -S -E @tamagui/shorthands @tamagui/theme-base @tamagui/font-inter @tamagui/animations-css`
> 5. Install needed packages:
>    `yarn add -S -E @tamagui/babel-plugin react-native-web`
> 6. Install dependecy package to config tamagui on babel:
>    `yarn add -S -E -D babel-plugin-transform-inline-environment-variables`
> 7. I had to update react version re-installing the package:
>    `yarn add -S -E react`
> 
> Also remember to follow documentation on create the tamagui.config.ts file and update babel.config.js file.
> 
> Check final package.json:
> 
> > {
> > "name": "myapp",
> > "version": "0.0.1",
> > "private": true,
> > "scripts": {
> > "android": "react-native run-android",
> > "ios": "react-native run-ios",
> > "start": "react-native start",
> > "test": "jest",
> > "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
> > },
> > "dependencies": {
> > "@tamagui/animations-css": "1.0.1-beta.210",
> > "@tamagui/babel-plugin": "1.0.1-beta.210",
> > "@tamagui/theme-base": "1.0.1-beta.210",
> > "expo": "^47.0.0",
> > "react": "18.2.0",
> > "react-dom": "18.2.0",
> > "react-native": "0.70.5",
> > "react-native-web": "0.18.10",
> > "tamagui": "1.0.1-beta.210"
> > },
> > "devDependencies": {
> > "@babel/core": "^7.12.9",
> > "@babel/runtime": "^7.12.5",
> > "@react-native-community/eslint-config": "^2.0.0",
> > "@tsconfig/react-native": "^2.0.2",
> > "@types/jest": "^26.0.23",
> > "@types/react": "^18.0.21",
> > "@types/react-native": "^0.70.6",
> > "@types/react-test-renderer": "^18.0.0",
> > "@typescript-eslint/eslint-plugin": "^5.37.0",
> > "@typescript-eslint/parser": "^5.37.0",
> > "babel-jest": "^26.6.3",
> > "babel-plugin-transform-inline-environment-variables": "0.4.4",
> > "eslint": "^7.32.0",
> > "jest": "^26.6.3",
> > "metro-react-native-babel-preset": "0.72.3",
> > "react-test-renderer": "18.1.0",
> > "typescript": "^4.8.3"
> > },
> > "jest": {
> > "preset": "react-native",
> > "moduleFileExtensions": [
> > "ts",
> > "tsx",
> > "js",
> > "jsx",
> > "json",
> > "node"
> > ]
> > }
> > }
> 
> Good luck @roaigen-robot !

@ManuelGarciaMasjoan why react-dom is required in react native

**Comment by TrejoCode** [comment]
Too hard to install, a lot of warnings kinds from createTamagui, fonts, etc.
