### ISSUE TITLE
bug: ListItem ignores theme background (iOS only). Uses system appearance settings.

### ISSUE THREAD

**Issue by peterlcsteele** [tamagui/tamagui#3032]
### Current Behavior

**ListItem** appears to ignores current theme **$background** color. ListItem applies a **backgroundColor** based on the iOS Simulator appearance (light or dark mode).
<img width="439" alt="appearance" src="https://github.com/user-attachments/assets/d95e9836-8ca0-4399-af7b-54846b663fc3">

### Expected Behavior

**ListItem** should apply **$background** from theme(s) in the following order:
1) light_ListItem or dark_ListItem
2) light or dark
3) tokens

### Tamagui Version

```markdown
1.116.9
```

### Platform (Web, iOS, Android)

```markdown
iOS Simulator - 18.0 - Theme background color is ignored.
Web: Background color is applied per theme as expected.
Android: Not tested.
```

### Reproduction

```markdown
1. Configure new project per starter-free
2. Create index/App.tsx with following:

// ... Import a tamaguiConfig (v3) containing both light and dark themes.
import { ListItem, TamaguiProvider, Theme } from 'tamagui'

return (
  <TamaguiProvider config={tamaguiConfig}>
     <Theme name='dark'>
        <ListItem>Something</ListItem>
     </Theme>
  </TamaguiProvider>
)

3. Run on iOS simulator with **Dark Appearance** set to **Off**. Observe no dark theme background color applied to **ListItem**.
4. Enable **Dark Appearance** in iOS Simulator. Observe a dark background is now applied to ListItem.
5. Change <Theme name='**light**'>. Observe a dark background is still applied, ignoring theme, but using iOS **Dark Appearance** setting.
```

**Comment by natew** [comment]
Lmk if the latest release fixes, we added a bunch of tests and I fixed some issues here. Make sure if using fastSchemeChange you keep the root theme synced with the system theme. Adding docs for that now.
