### ISSUE TITLE
$platform-web inside media query only renders the last prop

### ISSUE THREAD

**Issue by claubacher** [tamagui/tamagui#3037]
### Current Behavior

When `$platform-web` is nested inside of a media query, only the last style prop in `$platform-web` gets rendered.

Example:
```tsx
<H1
  $gtXs={{
    '$platform-web': {
      color: 'blue',
      backgroundColor: 'pink',
    },
 }}
>
  Welcome to Tamagui.
</H1>
```
This shows an H1 with a pink background but not blue text.

### Expected Behavior

All styles inside `$platform-web` should get rendered.

### Tamagui Version

```markdown
Observed in both 1.110.0 and 1.116.9
```

### Platform (Web, iOS, Android)

```markdown
Web (although I assume the same thing happens for `$platform-ios`, etc.)
```

### Reproduction

```markdown
https://codesandbox.io/p/devbox/admiring-hill-ls938k?workspaceId=1697902e-a02a-43db-86ce-2ade36939a27
```

**Comment by natew** [comment]
Fix here 27ffc83e31f9aaa4ec747357693a392a355b29d0, going out next release
