### ISSUE TITLE
Incorrect z-index ordering of sheets and dialogs

### ISSUE THREAD

**Issue by skyriverbend** [tamagui/tamagui#3046]
### Current Behavior

When opening a dialog after opening a sheet, the dialog gets displayed underneath the sheet. This didn't used to happen in Tamagui 1.108.0.

### Expected Behavior

The latest popovers/sheets/dialog should always show on top of previously opened popover/sheets/dialogs. See this [10 second loom](https://www.loom.com/share/bf9515ce1e89417ba0242ca61fddb1c2) of correct behavior on Tamagui v1.108.0 web

### Tamagui Version

```markdown
1.116.12
```

### Platform (Web, iOS, Android)

```markdown
Web, iOS, haven't tested Android
```

### Reproduction

```markdown
https://github.com/skyriverbend/starter-free

See the following loom videos to see behavior. Only the first video behaves the way expected.

Tamagui v1.108.0 sheet dialog web (intended behavior)
https://www.loom.com/share/bf9515ce1e89417ba0242ca61fddb1c2

Tamagui v1.108.0 sheet dialog iOS
https://www.loom.com/share/360a14b39c004bf78fbf35f4ff0e973d

Tamagui v1.116.12 sheet dialog web
https://www.loom.com/share/ca7905d1b0fc4454992aca2a33b9fc76

Tamagui v1.116.12 sheet dialog iOS
https://www.loom.com/share/9ee016d259bf4d8bb6fb18308eb1f804

(apologies for accidentally recording music in those videos above)
```

**Comment by skyriverbend** [comment]
You may wanna tackle #2978 at the same time as this since they are both related to z-index on popover-ish components.

**Comment by natew** [comment]
Fixed in `1.120.0`

**Comment by pranavmene2000** [comment]
> Fixed in `1.120.0`

Popover is working fine now. But sheet is now gets displayed underneath of another sheet. 
(I want to open Sheet on another Sheet).
Sheet is nothing but bottom drawer.

**Comment by natew** [comment]
Have you tried setting `stackZIndex` prop? I think it works by default if they are actually rendered inside like `<Sheet><Sheet>` but if they are next to each other you may need the stack prop.

**Comment by dylan-westbury** [comment]
@pranavmene2000 , were you ever able to solve? Behaviour is super inconsistent for me, sometimes the sheet will show above another sheet, sometimes it won't. I tinker with the ZIndex but no luck.

Basically just trying to show a child sheet over a parent sheet, I add Zindex to the child sheet to show on top, but no luck...
