### ISSUE TITLE
YStack inconsistency between dev and production: flex vs inline-flex

### ISSUE THREAD

**Issue by iameli** [tamagui/tamagui#3052]
### Current Behavior

My dev and production builds have inconsistent layouts. Dev:

<img width="769" alt="image" src="https://github.com/user-attachments/assets/098ec1e7-5760-481d-907c-481cd107ca2f">

Prod:

<img width="605" alt="image" src="https://github.com/user-attachments/assets/4ba89680-74d7-435d-8b1a-f290bb9493a7">

Is it expected that my entire app is wrapped in three `<span>` like this? Smells related.

<img width="569" alt="image" src="https://github.com/user-attachments/assets/d971f075-283c-4356-a93a-349f7fd3cf7a">

### Expected Behavior

I figured they would look the same

### Tamagui Version

```markdown
1.116.12
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
git clone https://git.aquareum.tv/aquareum-tv/aquareum.git
cd aquareum
git checkout 085b94cbcb7069fa5b79bfdadbebab31692decfe
make
```

To boot up a production node with the prod build:
```
make node && ./bin/aquareum --test-stream
```
And then it'll be there at `http://localhost:38080`

To boot up the development server with the dev build:
```
yarn run app start
```
And then it'll be there at `http://localhost:38081`

### System Info

```markdown
System:
    OS: macOS 15.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 67.77 MB / 16.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 22.9.0 - /opt/homebrew/bin/node
    Yarn: 4.3.0 - /opt/homebrew/bin/yarn
    npm: 10.8.3 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 129.1.70.126
    Chrome: 130.0.6723.92
    Safari: 18.0.1
  npmPackages:
    firebase-admin: ^12.7.0 => 12.7.0
    husky: ^9.1.6 => 9.1.6
    lerna: ^8.1.9 => 8.1.9
    lint-staged: ^15.2.10 => 15.2.10
    prettier: ^3.3.3 => 3.3.3
```

**Comment by iameli** [comment]
AFAICT it's a `<YStack>` difference. In development, it's `display: flex` and in production it's `display: inline-flex`.
<img width="2032" alt="image" src="https://github.com/user-attachments/assets/c1f8115f-a592-4095-ad6e-7f0f9bac6379">

<img width="2032" alt="image" src="https://github.com/user-attachments/assets/f1233bfc-49b3-46f6-9273-3d56e142c103">

Hacking in `display: flex` to the production one with the web inspector makes them consistent.

**Comment by iameli** [comment]
Replacing the YStack with a View didn't fix the problem but `<View display="flex">` did. Where's that inline-flex coming from? Pertinent component is this: 

```jsx
    <ScrollView
      contentContainerStyle={{
        alignItems: "stretch",

        ...contentContainerStyle,
      }}
      refreshControl={
        <RefreshControl
          refreshing={loading}
          onRefresh={() => setRetryTime(Date.now())}
        />
      }
    >
      {streams.map((seg) => (
        <View flex={1} key={seg.user}>
          <AQLink to={{ screen: "Stream", params: { user: seg.user } }}>
            <YStack f={1} alignItems="center">
              <Image
                f={1}
                aspectRatio={16 / 9}
                maxWidth={400}
                width="100%"
                src={`${url}/api/playback/${seg.user}/stream.jpg`}
                resizeMode="contain"
                objectFit="contain"
              />
              <H6>{formatAddress(seg.user)}</H6>
            </YStack>
          </AQLink>
        </View>
      ))}
    </ScrollView>
```

**Comment by natew** [comment]
Are you using optimizing compiler? Can you turn off if so? Definitely not seeing this across tons of apps. Can you try upgrading?
