### ISSUE TITLE
Failed to execute 'insertRule' when container group is mising

### ISSUE THREAD

**Issue by kzlar** [tamagui/tamagui#3053]
### Current Behavior

Container queries fail with `insertRule` error when a group is not set. See reproduction: https://codesandbox.io/p/devbox/vigilant-kowalevski-s8v97t

Note the following cases:

1. Neither of the stacks have the group prop - Works!
2. Both stacks of the group props - Works!
3. Only one of the stacks have the group - Fails!

Change boom from true/false to quickly see it

From what I can tell something with this line is wrong: https://github.com/tamagui/tamagui/blob/master/code/core/web/src/helpers/getSplitStyles.tsx#L499
Since only one group is available within the `context.groups.state`, it thinks we're using an anonymous group, but that's not true. This error causes the `keyInit` variable to be `group-true-<group_name>-<media>` instead of `group-<group_name>-<media>` which in turns creates a css class that looks like `xxx:<group_name>` (so `group_name` instead of an actual pseudo), then insert css rule fails.

### Expected Behavior

Error should not happen in all cases. Container query should only apply when the group is present in the component tree above.

### Tamagui Version

```markdown
1.116.12
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
https://codesandbox.io/p/devbox/vigilant-kowalevski-s8v97t
```

**Comment by 0xChqrles** [comment]
I'm hitting this same issue with the latest version (1.121.3)

**Comment by natew** [comment]
Couldn't repro in a7b02893c05ed31f90bc8e38f4b3eec6aa581a92 but added a fix anyway which also fixes the selector generated.
