### ISSUE TITLE
Is there a way to remove the animation from the Progress.Indicator?

### ISSUE THREAD

**Issue by matheusm** [tamagui/tamagui#3054]
I've tried using `unstyled={true}` and `animateOnly={[]}` but neither produced the expected result.

- When I set unstyled={true}, there was no noticeable difference in the styling.
- When I used animateOnly={[]}, the animation progress remained stuck at 100%.

Could you please provide guidance on achieving the desired behavior with these properties? Thanks!

![image](https://github.com/user-attachments/assets/041fedbf-f691-4ee9-9844-95f61600af36)

**Comment by nathanbrachotte** [comment]
I have the same issue. Setting `null` or removing the prop still uses the animation for me.

**Comment by w-aurelien** [comment]
Same here. Any feedback ?
