### ISSUE TITLE
font-silkscreen not exported from package

### ISSUE THREAD

**Issue by hirvesh** [tamagui/tamagui#3062]
### Current Behavior

If I try to import the Silkscreen font, via `import '@tamagui/font-silkscreen/css/400.css'`, I get the following error:

```
Module not found: Package path ./css/400.css is not exported from package 
> 6 | import '@tamagui/font-silkscreen/css/400.css'
```

### Expected Behavior

Expected behaviour is for it to load the font.

### Tamagui Version

```markdown
1.116.14
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://codesandbox.io/p/devbox/elastic-pine-kjnhj7
```

**Comment by natew** [comment]
Added an export for next version, thanks
