### ISSUE TITLE
Error when use Select component: need PortalProvider

### ISSUE THREAD

**Issue by Mistsink** [tamagui/tamagui#3077]
### Current Behavior

I encapsulate the Select components the same way as on the official website. https://tamagui.dev/ui/select?subpath=select
The code is:
```ts
import React from "react"
import { Adapt, FontSizeTokens, getFontSize, Select, SelectProps, Sheet, YStack } from "tamagui"
import { Check, ChevronDown, ChevronUp } from '@tamagui/lucide-icons'
import { LinearGradient } from 'tamagui/linear-gradient'

export function SelectGroup(props: SelectProps) {
    const [val, setVal] = React.useState('apple')
  
    return (
      <Select value={val} onValueChange={setVal} disablePreventBodyScroll {...props}>
        <Select.Trigger width={220} iconAfter={ChevronDown}>
          <Select.Value placeholder="Something" />
        </Select.Trigger>
  
        <Adapt when="sm" platform="touch">
          <Sheet
            native={!!props.native}
            modal
            dismissOnSnapToBottom
            animationConfig={{
              type: 'spring',
              damping: 20,
              mass: 1.2,
              stiffness: 250,
            }}
          >
            <Sheet.Frame>
              <Sheet.ScrollView>
                <Adapt.Contents />
              </Sheet.ScrollView>
            </Sheet.Frame>
            <Sheet.Overlay
              animation="lazy"
              enterStyle={{ opacity: 0 }}
              exitStyle={{ opacity: 0 }}
            />
          </Sheet>
        </Adapt>
  
        <Select.Content zIndex={200000}>
          <Select.ScrollUpButton
            alignItems="center"
            justifyContent="center"
            position="relative"
            width="100%"
            height="$3"
          >
            <YStack zIndex={10}>
              <ChevronUp size={20} />
            </YStack>
            <LinearGradient
              start={[0, 0]}
              end={[0, 1]}
              fullscreen
              colors={['$background', 'transparent']}
              borderRadius="$4"
            />
          </Select.ScrollUpButton>
  
          <Select.Viewport
            // to do animations:
            // animation="quick"
            // animateOnly={['transform', 'opacity']}
            // enterStyle={{ o: 0, y: -10 }}
            // exitStyle={{ o: 0, y: 10 }}
            minWidth={200}
          >
            <Select.Group>
              <Select.Label>Fruits</Select.Label>
              {/* for longer lists memoizing these is useful */}
              {React.useMemo(
                () =>
                  items.map((item, i) => {
                    return (
                      <Select.Item
                        index={i}
                        key={item.name}
                        value={item.name.toLowerCase()}
                      >
                        <Select.ItemText>{item.name}</Select.ItemText>
                        <Select.ItemIndicator marginLeft="auto">
                          <Check size={16} />
                        </Select.ItemIndicator>
                      </Select.Item>
                    )
                  }),
                [items]
              )}
            </Select.Group>
            {/* Native gets an extra icon */}
            {props.native && (
              <YStack
                position="absolute"
                right={0}
                top={0}
                bottom={0}
                alignItems="center"
                justifyContent="center"
                width={'$4'}
                pointerEvents="none"
              >
                <ChevronDown
                  size={getFontSize((props.size as FontSizeTokens) ?? '$true')}
                />
              </YStack>
            )}
          </Select.Viewport>
  
          <Select.ScrollDownButton
            alignItems="center"
            justifyContent="center"
            position="relative"
            width="100%"
            height="$3"
          >
            <YStack zIndex={10}>
              <ChevronDown size={20} />
            </YStack>
            <LinearGradient
              start={[0, 0]}
              end={[0, 1]}
              fullscreen
              colors={['transparent', '$background']}
              borderRadius="$4"
            />
          </Select.ScrollDownButton>
        </Select.Content>
      </Select>
    )
  }
  
  const items = [
    { name: 'Apple' },
    { name: 'Pear' },
    { name: 'Blackberry' },
    { name: 'Peach' },
    { name: 'Apricot' },
    { name: 'Melon' },
    { name: 'Honeydew' },
    { name: 'Starfruit' },
  ]
```

First, I received a TypeScript warning: In the when field of <Adapt when="sm" platform="touch">, Type 'string' is not assignable to type 'AdaptWhen | undefined'. ts(2322)
Adapt.d.ts(21, 5): The expected type comes from the 'when' property, which is declared here on type 'IntrinsicAttributes & AdaptProps'
(property) when?: AdaptWhen | undefined

Most importantly, when debugging on the native side using Expo, I encountered the following error:
```bash
 (NOBRIDGE) ERROR  Warning: Error: 'PortalDispatchContext' cannot be null, please add 'PortalProvider' to the root component.

This error is located at:
    in NonNativePortalComponent
    in Unknown (created by Portal)
    in Portal
    in Unknown
    in Unknown (created by SelectGroup)
    in Unknown (created by SelectGroup)
    in SelectSheetImpl (created by SelectInner)
    in SheetController (created by SelectSheetController)
    in SelectSheetController (created by SelectInner)
    in SelectProvider (created by SelectInner)
    in SelectProvider (created by SelectInner)
    in SelectInner
    in Provider (created by ProvideAdaptContext)
    in ProvideAdaptContext (created by AdaptParent)
    in AdaptParent
    in Unknown (created by SelectGroup)
    in SelectGroup (created by SettingSection)
```

I look forward to your reply.

### Tamagui Version

```markdown
^1.117.2
```

### Platform (Web, iOS, Android)

```markdown
Android
```

### Reproduction

```markdown
the code above
```

**Comment by natew** [comment]
Are you using TamaguiProvider at the root? Could you open a repro and I'll re-open this.

**Comment by unav4ila8le** [comment]
I am having the same issue. I trying both without and with TamaguiProvider at root. I am trying to render a Sheet inside a react-native modal. If anyone has any insight, that would be helpful.

**Comment by montasaurus** [comment]
I got the same error using Expo/React Native, fixed it by importing `TamaguiProvider` from `tamagui` instead of `@tamagui/core`, i.e.
```typescript
import { TamaguiProvider } from "tamagui";
```

Might be worth calling out in the docs that there's a subtle difference there.

**Comment by LuanNguyen-HnL** [comment]
> I am having the same issue. I tried both without and with TamaguiProvider at root. I am trying to render a Sheet inside a react-native modal. If anyone has any insight, that would be helpful.

@unav4ila8le did you fix the issue? I had same issue with Popover inside react-native-modal

**Comment by ettmetal** [comment]
I am currently having this issue, and have `TamaguiProvider` at application root, along with importing from `'tamagui'` as @montasaurus mentions. Is this something you need more input on to repro?

**Comment by unav4ila8le** [comment]
We ended up building our custom Sheet component and then setting it up at the root. Now we have much more better flexibility and we can easily also use nested sheets. Unfortunately we didn't manage to make it work with the Tamagui out of the box component.

**Comment by CrazyCoder** [comment]
For me the fix was to add `@tamagui/portal` to the dependencies and use `import {PortalProvider} from '@tamagui/portal'`.

**Comment by mdahewlett** [comment]
Try deduping your version of portal - first check whether your versions are mismatched with `npm ls @tamagui/portal tamagui @tamagui/popover`, then run `npm dedup` - I was having the issue you are describing with the popover, and now it runs well

**Comment by SDroidLabs** [comment]
> Try deduping your version of portal - first check whether your versions are mismatched with `npm ls @tamagui/portal tamagui @tamagui/popover`, then run `npm dedup` - I was having the issue you are describing with the popover, and now it runs well

This worked for me

**Comment by marlon-wiprud** [comment]
> > Try deduping your version of portal - first check whether your versions are mismatched with `npm ls @tamagui/portal tamagui @tamagui/popover`, then run `npm dedup` - I was having the issue you are describing with the popover, and now it runs well
> 
> This worked for me

for the next weary traveler - this worked for me as well 🙃

**Comment by Benjahzz** [comment]
> Try deduping your version of portal - first check whether your versions are mismatched with `npm ls @tamagui/portal tamagui @tamagui/popover`, then run `npm dedup` - I was having the issue you are describing with the popover, and now it runs well

This worked, thanks so much.
