### ISSUE TITLE
SyntaxError: Unexpected token 'typeof' when trying to start Remix app

### ISSUE THREAD

**Issue by jbojcic1** [tamagui/tamagui#3082]
### Current Behavior

When I want to start my built Remix/Tamagui app I am getting this error:
```
λ bun run start     
$ cross-env NODE_ENV=production node ./build/server.js
file:///Users/jbojcic/Projects/prism/boardwalkcash/node_modules/react-native/index.js:15
import typeof ActionSheetIOS from './Libraries/ActionSheetIOS/ActionSheetIOS';
       ^^^^^^

SyntaxError: Unexpected token 'typeof'
    at compileSourceTextModule (node:internal/modules/esm/utils:340:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:102:18)
    at #translate (node:internal/modules/esm/loader:433:12)
    at ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:480:27)

Node.js v22.11.0
error: script "start" exited with code 1
```

### Expected Behavior

It should start the app normally. I don't even have a react native app atm. I only have a remix web app

### Tamagui Version

```markdown
1.117.2
```

### Platform (Web, iOS, Android)

```markdown
Web - Remix
```

### Reproduction

```markdown
To reproduce:
1. Open the code here https://codesandbox.io/p/github/MakePrisms/boardwalkcash/setup-tamagui-for-codesandbox
2. Run `npx bun i`
3. Run `npm run build`
3. Run `npm run start:bun`
```

### System Info

```markdown
On my local machine:

 System:
    OS: macOS 15.1.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 9.28 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.local/state/fnm_multishells/27251_1733309568105/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.9.0 - ~/.local/state/fnm_multishells/27251_1733309568105/bin/npm
    pnpm: 8.6.10 - /opt/homebrew/bin/pnpm
    bun: 1.1.34 - /nix/store/xnj00gq1mfffvgyisghk4m9f38gc5c5c-bun-1.1.34/bin/bun
  Browsers:
    Brave Browser: 128.1.69.168
    Chrome: 131.0.6778.86
    Safari: 18.1.1
  npmPackages:
    @biomejs/biome: 1.9.4 => 1.9.4 
    @remix-run/dev: 2.15.0 => 2.15.0 
    @remix-run/express: 2.15.0 => 2.15.0 
    @remix-run/node: 2.15.0 => 2.15.0 
    @remix-run/react: 2.15.0 => 2.15.0 
    @tamagui/vite-plugin: 1.117.2 => 1.117.2 
    @types/express: 5.0.0 => 5.0.0 
    @types/react: 18.3.12 => 18.3.12 
    @types/react-dom: 18.3.1 => 18.3.1 
    cross-env: 7.0.3 => 7.0.3 
    express: 4.21.1 => 4.21.1 
    isbot: 4.4.0 => 4.4.0 
    npm-run-all: 4.1.5 => 4.1.5 
    react: 18.3.1 => 18.3.1 
    react-dom: 18.3.1 => 18.3.1 
    tamagui: 1.117.2 => 1.117.2 
    tsx: 4.19.2 => 4.19.2 
    typescript: 5.7.2 => 5.7.2 
    vite: 5.4.11 => 5.4.11 
    vite-tsconfig-paths: 4.3.2 => 4.3.2
```
```

**Comment by natew** [comment]
Did you try our Remix setup? It's hard to configure Vite for RNW, you should try https://onestack.dev, we do a lot of stuff to make it work automatically.

**Comment by natew** [comment]
You need optimizeDeps.include all transitive deps of react-native, and have the alias set. We have a plugin in One that does this automatically.

**Comment by jbojcic1** [comment]
@natew One would be ideal for our project but it seems to be too early. I bumped into issues even with most basic stuff (e.g. https://github.com/onejs/one/issues/255) so I was hoping we can go with Remix + Tamagui for now and then switch to One later but not even that seems to be easy so will probably need to pick other UI lib as well.

> Did you try our Remix setup?

I tried tamagui remix setup but it is not really configured properly. First, it uses an old Remix server entry file which doesn't do streaming (I think I solved that. See [here](https://github.com/tamagui/tamagui/issues/3066#issuecomment-2515616828)) . Second, the CSS extraction at build time doesn't work at all because the components are imported from `@tamagui/web` instead of `tamagui` (I think that is the reason but it's not really explained well in the docs). So I took some parts from that setup and tried to get everything work for our project and then bumped into this issue.

> You need optimizeDeps.include all transitive deps of react-native, and have the alias set. We have a plugin in One that does this automatically.

Can you elaborate on this one? We only need it to be compiled for the web for now (the plan was to make a web app first and only in a few months add React native app). I was hoping that the Vite plugin `platform` setting could be used for that but setting it to `web` didn't help, so I am not even sure what is that for?

Tamagui is very promising and interesting but the docs need a lot of work.

**Comment by hirbod** [comment]
@jbojcic1 I ran into the same problem, and the fix was pretty easy:

```diff
import { vitePlugin as remix } from '@remix-run/dev'
import { installGlobals } from '@remix-run/node'
import { defineConfig, loadEnv } from 'vite'
import tsconfigPaths from 'vite-tsconfig-paths'

installGlobals()

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), 'EXPO_PUBLIC_')
  return {
    resolve: {
      alias: {
        stream: 'rollup-plugin-node-polyfills/polyfills/stream',
        util: 'rollup-plugin-node-polyfills/polyfills/util',
+       'react-native': 'react-native-web',
      },
    },
    envPrefix: 'EXPO_PUBLIC_',
    plugins: [remix({ ssr: false }), tsconfigPaths()],
    define: {
      'process.env': env,
    },
  }
})
```

**Comment by jbojcic1** [comment]
> @jbojcic1 I ran into the same problem, and the fix was pretty easy. Had to add an alias in vite.config.ts to react-native-web

Do you know why is needed though and if I can somehow let it know that I only need web?

**Comment by hirbod** [comment]
React Native ships with FlowTypes, which simply break with the bundler. So you alias react-native to react-native-web, which fixes this. Another option would be to install a vite-babel plugin and strip flow types, which is much more error prone and complicated. The alias should be an easy fix.

**Comment by jbojcic1** [comment]
@hirbod thx for explaining. Do you know what is this `platform` config in vite plugin then? It can have 'web' or 'native' or undefined value. I was expecting that setting that to web would skip native bundling but doesn't seem to have any effect.

**Comment by kzlar** [comment]
@hirbod were you able to get remix SSR to run? with components that import from 'tamagui' instead of '@tamagui/web'? 
I tried the alias method but it still does not work for me.
@jbojcic1 were you able to make any of this work?

**Comment by jbojcic1** [comment]
@kzlar no. I gave up on for now and went with something else. Seems too early and docs are pretty bad

**Comment by guillempuche** [comment]
This is also happening with Tanstack https://tanstack.com/start/latest/docs/framework/react/overview
