### ISSUE TITLE
How to use with Remix Run

### ISSUE THREAD

**Issue by mtzfactory** [tamagui/tamagui#31]
I would like use this library within a [Remix Run](https://remix.run/) web, but can figure it how.

Any help would be appreciated.

**Comment by frontsideair** [comment]
I think it's not possible to use Tamagui with Remix, at least not without significant effort. Tamagui uses webpack while Remix uses esbuild. Theoretically, you may run a separate process to run Tamagui compiler, like how Remix uses Tailwind in official examples. The ideal scenario would be to wait for Remix or Tamagui to work on integration.

**Comment by natew** [comment]
If someone starts a PR, I'm happy to help that along. The webpack loader and babel plugin both share a base `@tamagui/static` package that abstracts a lot of the logic out.
