### ISSUE TITLE
Group documentation demonstrates deprecated usage of separator without any new recommendations

### ISSUE THREAD

**Issue by Hultner** [tamagui/tamagui#3104]
### Current Behavior

On the documentation page of group there's examples that show how to create a list with separator, this usage is deprecated and no alternative is shown.
https://tamagui.dev/ui/group?subpath=group

This is a not so much a classic bug, but more a case of outdated documentation.

### Expected Behavior

A non deprecated version example showcasing the same usage.

### Tamagui Version

```markdown
1.117.0
```

### Platform (Web, iOS, Android)

```markdown
iOS is what I'm using, but for the documentation I guess N/A.
```

### Reproduction

```markdown
Visit: 
https://tamagui.dev/ui/group?subpath=group
See first example with separators. Do this.
```

### System Info

```markdown
N/A
```

**Comment by vimalraj-a** [comment]
Yes, I need the updated doc. Currently the only way I'm doing this is adding separator based on the index

**Comment by natew** [comment]
We will leave separator for Group actually, but its hard to make the prop right until v2 comes out and removes the type. But just know that Group, YGroup and XGroup *will* still be able to use separator, just not the base components. Once v2 comes out this type will fix.

**Comment by Hultner** [comment]
> We will leave separator for Group actually, but its hard to make the prop right until v2 comes out and removes the type. But just know that Group, YGroup and XGroup _will_ still be able to use separator, just not the base components. Once v2 comes out this type will fix.

It would be nice with a heads up in the documentation about this until then add the current state is quite confusing as a library  user. I actually rewrote some of my groups to manually insert separators between the elements when I saw the deprecation warning.
