### ISSUE TITLE
[bug] npx create-tamagui-app@latest myapp fails

### ISSUE THREAD

**Issue by GigaBigBoss** [tamagui/tamagui#312]
npx create-tamagui-app@latest myapp
errors out 
![WindowsTerminal_7T4JgBGX8a](https://user-images.githubusercontent.com/106954969/198825719-a750919b-ba9c-4ef8-99ac-0a8931d6ee28.png)

**Comment by natew** [comment]
It says you already have a folder with that name

**Comment by GigaBigBoss** [comment]
> It says you already have a folder with that name

That was on second attempt after first failed, also I had the same first error on a new creation as well.

**Comment by GigaBigBoss** [comment]
@natew

**Comment by GigaBigBoss** [comment]
![WindowsTerminal_bG7DrpbYGH](https://user-images.githubusercontent.com/106954969/199433608-21c01a4b-92ff-47ac-bf79-d4d95a38463b.png)

Issue confirmed still present today.

**Comment by thegitparticle** [comment]
This has to be re-opened, it is still failing with same error on mac os as well.

**Comment by natew** [comment]
Please post the output on Mac. I am not seeing it. Include your shell info, Mac version, and git version.

**Comment by thegitparticle** [comment]
ZSH shell on mac OS 13.0 Ventura
Git version - 2.23.0

See the screenshot below for the output

<img width="722" alt="Screenshot 2022-11-13 at 12 34 04 PM" src="https://user-images.githubusercontent.com/12975157/201510061-7dcc6a7c-1a1c-4d17-8ab1-e7c8d0fc675f.png">

**Comment by thegitparticle** [comment]
@natew Hi, any update on this?

**Comment by thegitparticle** [comment]
The issue is with the git version. When upgrading it with brew, it is not over-writing the old version universally.
`brew link --overwrite git` - this did the trick and the create-tamagui-app works.

**Comment by natew** [comment]
there's a check for git version that should ensure it's right but maybe is failing, what versions are you on that are failing? `git --version`

**Comment by thegitparticle** [comment]
It failed on 2.23 I guess. I have now updated git 2.38.1 universally and it works.

**Comment by lostpebble** [comment]
![image](https://user-images.githubusercontent.com/1508863/205966093-27ef99a5-7b5d-4619-b1d3-6225ec231e0a.png)

Unfortunately this still seems to be an issue on Windows. I'm using PowerShell, which the latest blog post seemed to imply should work. I've also tried with an "admin" PowerShell and it still failed.

Upon looking inside my Windows user folder where it seems to want to clone something:

![image](https://user-images.githubusercontent.com/1508863/205967024-93fbce80-bebb-4dce-af5b-f3287c3176ea.png)

So it seems like there is some strange stuff happening, likely its executing file system things in a non-Windows way.
