### ISSUE TITLE
[bug] Issues making it work with Expo

### ISSUE THREAD

**Issue by TNAJanssen** [tamagui/tamagui#314]
**Describe the bug**
I get the following error when adding to a project, even when creating a new project using npx create-expo-app --template and then selecting navigation (typescript)

 ERROR  TypeError: undefined is not an object (evaluating 'conf.tokensParsed')
<img width="414" alt="image" src="https://user-images.githubusercontent.com/2812277/198832939-ff3642f9-947a-45b2-b41d-17e8a07b3c3d.png">

**System Info (please complete the following information):** 

  System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.27 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 3.2.4 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Brave Browser: 103.1.41.100
    Firefox: 98.0.2
    Safari: 16.1
  npmPackages:
    @babel/core: ^7.12.9 => 7.19.6
    @expo/vector-icons: ^13.0.0 => 13.0.0
    @react-navigation/bottom-tabs: ^6.0.5 => 6.4.0
    @react-navigation/native: ^6.0.2 => 6.0.13
    @react-navigation/native-stack: ^6.1.0 => 6.9.1
    @tamagui/animations-reanimated: ^1.0.1-beta.195 => 1.0.1-beta.199
    @tamagui/config-base: ^1.0.1-beta.195 => 1.0.1-beta.199
    @tamagui/feather-icons: ^1.0.1-beta.193 => 1.0.1-beta.193
    @tamagui/font-inter: ^1.0.1-beta.195 => 1.0.1-beta.199
    @tamagui/shorthands: ^1.0.1-beta.195 => 1.0.1-beta.199
    @tamagui/simple-hash: ^1.0.1-beta.199 => 1.0.1-beta.199
    @tamagui/theme-base: ^1.0.1-beta.195 => 1.0.1-beta.199
    @types/react: ~18.0.14 => 18.0.24
    @types/react-native: ~0.69.1 => 0.69.15
    expo: ~46.0.16 => 46.0.16
    expo-asset: ~8.6.1 => 8.6.2
    expo-constants: ~13.2.4 => 13.2.4
    expo-font: ~10.2.1 => 10.2.1
    expo-linking: ~3.2.2 => 3.2.3
    expo-splash-screen: ~0.16.2 => 0.16.2
    expo-status-bar: ~1.4.0 => 1.4.1
    expo-system-ui: ~1.3.0 => 1.3.0
    expo-web-browser: ~11.0.0 => 11.0.0
    jest: ^26.6.3 => 26.6.3
    jest-expo: ~44.0.1 => 44.0.1
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    react-native: 0.69.6 => 0.69.6
    react-native-reanimated: ~2.9.1 => 2.9.1
    react-native-safe-area-context: 4.3.1 => 4.3.1
    react-native-screens: ~3.15.0 => 3.15.0
    react-native-web: ~0.18.7 => 0.18.9
    react-test-renderer: 18.0.0 => 18.0.0
    tamagui: ^1.0.1-beta.199 => 1.0.1-beta.199
    typescript: ~4.3.5 => 4.3.5

**Comment by natew** [comment]
Be sure your `tamagui.config.ts` is imported by the root file only (that passes to TamaguiProvider) and not anywhere else, you need `createTamagui` to run as early as possible in your app and before any `getTokens` or anything else calls.

**Comment by TNAJanssen** [comment]
@natew yeah i did do that, i created a public repo with some testing code. If you could check it out that would be nice.

https://github.com/TNAJanssen/testing-tamagui

**Comment by ugened47** [comment]
Getting the same error with Expo 47. Works well with Expo 46.

**Comment by peetaloo** [comment]
Hey @TNAJanssen upgrading `react` and `react-native` to the latest versions seemed to fix the error for me.

    "expo": "~46.0.16",
    "react": "18.2.0",
    "react-native": "0.70.6",
    "typescript": "^4.6.3"

**Comment by MichaelKilbane** [comment]
Yep, I ran into this issue also. This is due to there being two instances of the `@tamagui/core` package being somewhere in the module resolution tree. I believe this was resolved by updating react as @peetaloo mentioned.
