### ISSUE TITLE
[bug] All styles are inlined

### ISSUE THREAD

**Issue by nandorojo** [tamagui/tamagui#319]
**Describe the bug**

On web, all styles are inlined redundantly into the `style` prop.

**To Reproduce**

See tamagui website.

<img width="1792" alt="Screen Shot 2022-10-31 at 6 17 05 PM" src="https://user-images.githubusercontent.com/13172299/199120689-0e424dab-c48c-4555-a634-a3972e796305.png">

**Comment by natew** [comment]
Fixed in release 202
