### ISSUE TITLE
[bug] Black screen with yarn web:prod

### ISSUE THREAD

**Issue by GigaBigBoss** [tamagui/tamagui#320]
**Describe the bug**
Issue seemed to appear at v1.0.1-beta.200 as it wasn't occurring until updating from 199 to 200.

You can see the issue here: https://tamagui-sandbox.vercel.app/

Using the Next starter with JSX enabled and the scroll view demo causes the screen to load then quickly flash black when using yarn web:prod but functions properly using yarn web.

This issue is present with scrollviewdemo as well as ThemePropagationTest components causes the screen to load then quickly flash black.
https://github.com/GigaBigBoss/tamagui/blob/master/starters/next-expo-solito/packages/app/features/home/screen.tsx

Video of issue:
https://user-images.githubusercontent.com/106954969/199218642-bbfd5016-8777-4803-b012-77eb52fdceff.mp4

**To Reproduce**
https://github.com/GigaBigBoss/tamagui
Then either place the scrollviewdemo or ThemePropagationTest components into the main homescreen function.

**Comment by natew** [comment]
I think this is fixed in 201, if you can just lmk if that fixes.

**Comment by GigaBigBoss** [comment]
@natew Issue appears resolved from my testing. Will reopen if it appears again.
