### ISSUE TITLE
[bug] Scrollview doesn't function with yarn web:prod

### ISSUE THREAD

**Issue by GigaBigBoss** [tamagui/tamagui#322]
**Describe the bug**
Happening on version 199 + 200 and older versions.
Scrollviewdemo component doesn't work with yarn web:prod. (Using Next starter with JSX enabled)
I've attempted various different heights and flex settings with no luck.

Yarn web (Works as intended)
https://user-images.githubusercontent.com/106954969/199220563-ab1fd3d4-59f2-4f59-afd8-9dca1e997696.mp4

yarn web:prod 
https://user-images.githubusercontent.com/106954969/199220615-60ed4a71-d301-4b87-9e76-1868064c21d2.mp4

**To Reproduce**
https://github.com/GigaBigBoss/tamagui

Ensure the scrollviewdemo component is inside main homescreen function and  the the themepropagation component isn't.

https://github.com/GigaBigBoss/tamagui/blob/master/starters/next-expo-solito/packages/app/features/home/screen.tsx

**Comment by natew** [comment]
Fixed in 205 likely, re-open if not
