### ISSUE TITLE
Tamagui Main page should only use Tamagui

### ISSUE THREAD

**Issue by GigaBigBoss** [tamagui/tamagui#323]
If I'm not mistaken the CSS used to make the homescreen on tamagui.com wouldn't work with native.
![image](https://user-images.githubusercontent.com/106954969/199221862-f6f93a52-5306-4ee0-9fea-f1939067b752.png)

Can someone confirm this? If this is the case I think we should update the homescreen to only use things that would be 1:1 on both web and native as if this is correct it feels a bit false advertising/cheating and I personally was disappoint that this wasn't the case.

**Comment by natew** [comment]
The philosophy of tamagui isn't that you always have 100% the same code. 95% of the site is, but I wanted CSS text gradients.
