### ISSUE TITLE
[bug] Next Starter Vercel Deploy button doesn't work 

### ISSUE THREAD

**Issue by GigaBigBoss** [tamagui/tamagui#324]
This issue has been present for a bit now just reconfirmed:
![image](https://user-images.githubusercontent.com/106954969/199223853-37fb1488-a0d1-409b-bc7b-1e2543042f9f.png)

I've been able to mitigate by cloning the monorepo and then setting the following:
![image](https://user-images.githubusercontent.com/106954969/199223814-41bc8201-08b4-4c3e-8f29-d3ce80404129.png)
Note any attempt to set the directory different I was seeing issues with, as well as not manually specifying Next as the framework. 🤔

The button should be removed ASAP if this can't be resolved to avoid causing pain to new devs attempting to try out tamagui and getting a sour taste in their mouth.

**Comment by natew** [comment]
Good catch removed for now
