### ISSUE TITLE
Next Starter Readme Clarity Needed

### ISSUE THREAD

**Issue by GigaBigBoss** [tamagui/tamagui#326]
Instructions regarding "yarn web:optimize" seem outdated and/or unclear. I'm unable to find a script anywhere in the starter for "yarn web:optimize"

![image](https://user-images.githubusercontent.com/106954969/199227698-a78d2209-c1f2-423b-a08d-48e475d9c0b3.png)

![image](https://user-images.githubusercontent.com/106954969/199227196-2e277850-0df6-407f-b359-a26ae6cebfa9.png)

**Comment by natew** [comment]
Good point, no idea I must have set up a command that runs tamagui on just the one file, but for now just the debug pragma works so deleting.
