### ISSUE TITLE
[bug] Docs have a visual bug on left navigator

### ISSUE THREAD

**Issue by GigaBigBoss** [tamagui/tamagui#327]
![image](https://user-images.githubusercontent.com/106954969/199352989-d88c8596-ede7-4e5a-b3c2-cff42658443d.png)
https://tamagui.dev/docs/intro/introduction

**Comment by natew** [comment]
Don't see a bug here?

**Comment by GigaBigBoss** [comment]
@natew Why is blog to the right all goofy? What else could I possibly be pointing out?

**Comment by natew** [comment]
External links have an icon indicating it but the blog is internal. The contrast could be higher, you monitor doesn’t show that well maybe.

**Comment by GigaBigBoss** [comment]
@natew Ah you're right fug.
Still looks goofy even with that tho but yeah that makes more sense lol.
