### ISSUE TITLE
swcMinify causes hydration errors in production

### ISSUE THREAD

**Issue by nandorojo** [tamagui/tamagui#328]
I'm seeing this in my app, but only on prod builds:

<img width="880" alt="Screen Shot 2022-11-01 at 6 59 52 PM" src="https://user-images.githubusercontent.com/13172299/199357814-a29b0824-5046-4ab1-9e2a-fd297216c1fa.png">

**Describe the bug**

With `next build`, the `AlertDialog` breaks, complaining about missing context. No issues in dev (compiler is disabled in dev.)

I tried to reproduce this, but the starter app crashes in prod without being able to display any UI.

<img width="1207" alt="Screen Shot 2022-11-01 at 7 15 52 PM" src="https://user-images.githubusercontent.com/13172299/199359827-21074f9a-b7d8-4a99-baba-1d907eda10f0.png">

**To Reproduce**

Here is a [reproduction](https://github.com/nandorojo/tgui/tree/portal-bug) (see the `portal-bug` branch.)

Full repro steps:

```sh
git clone https://github.com/nandorojo/tgui.git
cd tgui
git checkout portal-bug
yarn

cd apps/next
yarn next build
yarn next start
# open localhost:3000
```

Now look in logs, you'll see a ton of build errors. I don't actually see the exact same error I got, but I am reproducing many, many other errors, as seen here:

**System Info (please complete the following information):** 

```sh
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 7.64 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 3.2.3 - ~/.yarn/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 96.0.3
    Safari: 15.5
  npmPackages:
    react-native: 0.0.0 => 0.0.0 
```

**Tamagui info**

Paste all the following below:

Using tamagui v200 on the beta. Using the latest starter too.

**Comment by nandorojo** [comment]
<img width="1788" alt="Screen Shot 2022-11-01 at 7 18 18 PM" src="https://user-images.githubusercontent.com/13172299/199360035-fb7176ac-bc1e-4f3f-af2b-fc8006f0b43d.png">

Meanwhile, in dev, the app renders just fine and there are no errors of any kind.

**Comment by nandorojo** [comment]
The errors happen in prod, regardless of if `disableExtraction` is true or not.

**Comment by nandorojo** [comment]
Looks like this is somewhat of a duplicate of all the prod-related issues opened in the last day or so, like #321  #320 #325, etc.

**Comment by natew** [comment]
I think all these are fixed then in the latest release, not sure what happened I had to switch a `const` to a `function` to have it hoist and be available. It's odd the site itself doesn't get any error, just the starters, some difference in setup.

**Comment by natew** [comment]
Lmk if the latest stuff fixed this.

**Comment by natew** [comment]
This was due to `swcMinify` being on, not sure what the root cause is yet but if anyone else encounters this try turning off swcMinify to see if it fixes.

**Comment by natew** [comment]
Can't replicate these anymore at least on tamagui.dev site, turning it on works just fine.
