### ISSUE TITLE
[bug] npx create-tamagui-app@latest myapp fails on Windows

### ISSUE THREAD

**Issue by GigaBigBoss** [tamagui/tamagui#329]
Continuing from: https://github.com/tamagui/tamagui/issues/312
Which was closed due to misunderstanding.

![WindowsTerminal_bG7DrpbYGH](https://user-images.githubusercontent.com/106954969/199434081-a09d27f7-94cf-4b46-8867-c278a4c1399a.png)

![image](https://user-images.githubusercontent.com/106954969/199434225-14a7326b-6c6c-4422-bd10-96da2f10f4d2.png)

Issue is still present, also tested with run as administrator. Possible due to syslinks being used somewhere as I recall this being an issue I ran into when attempting to move the folder.
Confirmed on windows 11, will test WSL

**Comment by GigaBigBoss** [comment]
Works on WSL so just windows.
![image](https://user-images.githubusercontent.com/106954969/199435589-df433ec2-a282-45f1-a757-4c1f6e75f5a5.png)

**Comment by dhatGuy** [comment]
I can confirm this too
![image](https://user-images.githubusercontent.com/51405947/200416093-a901ddde-3c19-4ac0-a05b-dbe2c10da44f.png)

**Comment by loveholly** [comment]
Not sure if this: https://www.pugetsystems.com/labs/hpc/Note-Setup-Git-for-PowerShell-on-Windows-10-1653 can help.

**Comment by natew** [comment]
You need a newer version of git in most these cases

Tamagui even checks for it and warns but it must be missing your versions. Whats the output of `git --version`?

**Comment by natew** [comment]
Can anyone verify this with the latest release? Last I heard it's working and I made the git version check stricter.

**Comment by dhatGuy** [comment]
git version 2.38.1.windows.1

![image](https://user-images.githubusercontent.com/51405947/205522008-bd2a62a5-dc17-4d97-aa72-ee04e2a70da0.png)

**Comment by Haddadmj** [comment]
git latest version "git version 2.38.1.windows.1"

Log --> [Click Here](https://pastebin.com/8NegbgiH)

**Comment by stanislavnastasiu-dev** [comment]
> git version 2.38.1.windows.1
> 
> ![image](https://user-images.githubusercontent.com/51405947/205522008-bd2a62a5-dc17-4d97-aa72-ee04e2a70da0.png)

same error with latest version of GIT and latest release of tamagui 

git version 2.39.0.windows.2

**Comment by natew** [comment]
Still breaking?

**Comment by dhatGuy** [comment]
Works fine now for me
