### ISSUE TITLE
[bug] @tamagui/font-inter package missing regular font

### ISSUE THREAD

**Issue by META-DREAMER** [tamagui/tamagui#331]
**Describe the bug**
The @tamagui/font-inter package contains all the fonts except for the regular 400 weight one.
![CleanShot 2022-11-02 at 13 14 32](https://user-images.githubusercontent.com/7143583/199580877-d19eaf2a-6cb9-4e85-af0c-66d1a57383bc.png)

**Tamagui info**

v1.0.1-beta.201

P.S. it seems like the subset fonts are still 200+ kB each, feels like it should be smaller

**Comment by natew** [comment]
Only woff files are subset.

Added regular weight woff2 here: 51fbb9e754e2672ca779a207d7c48094f8536508

PR for subset + regular otf files would be appreciated, could convert from woff2.
