### ISSUE TITLE
[bug] pseudo style props inside styled() variants are not applied

### ISSUE THREAD

**Issue by bureyburey** [tamagui/tamagui#333]
**Description**
When using the `styled()` function to create an Input component, the pseudo style props `hoverStyle` (and other pseudo styles) are not applied inside a custom variant property:

**To Reproduce**
I've prepared the following [repo](https://github.com/bureyburey/vite-ts-tamagui-test) to demonstrate this issue.
the `<Input />` component uses the Tamagui Input directly, while the `<StyledInput />` is a the Tamagui Input wrapped with the `styled()` function with the `isInvalid` variant that attempts to apply the `hoverStyle` prop.

[StyledInput](https://github.com/bureyburey/vite-ts-tamagui-test/blob/main/src/components/styled-input/index.tsx)
[Input](https://github.com/bureyburey/vite-ts-tamagui-test/blob/main/src/components/input/index.tsx)

Additionally, when attempting to apply the style directly on the `<StyledInput />` and not using the `isInvalid` variant prop, the `hoverStyle` still not applied.

**Tamagui info**
version: 1.0.1-beta.201
environment: web

**Comment by natew** [comment]
Fix for this in the next release via dd6ed2dcbff4c01308dcc1d72e841e0f32323de7 and 6ac3fab77c8304364e91b574eed6faa5195d419b

**Comment by natew** [comment]
Fixed in release beta 208
