### ISSUE TITLE
[bug] Solito starter not working correctly

### ISSUE THREAD

**Issue by ayushsharma82** [tamagui/tamagui#340]
The latest solito starter template doesn't work for Expo. Yeah the CI might be giving it a pass but in reality it doesn't load the styles correctly. I would like one of the contributors to try it out. The next.js side of things work fine but when opening the Expo app, components are not what we see in the next.js version.

**To Reproduce**
Simply follow your installation instruction on the website:

```
npm create tamagui-app@latest
```

**Comment by natew** [comment]
Ah, thought I fixed this in the last release but left a couple lines out, fixed in fb2e3342a5fbef2e95d54dd3da80ece41e54cb8b and beta 207. Thanks for the report.

**Comment by ayushsharma82** [comment]
Hi @natew ,

Thanks for looking at the bug quickly but the useMemo fix didn't work, I suspect it's related to the "@my/ui" package:

Here are the screenshots of Next.js version and Expo app, notice the sheet button from starter template, it's not circular and layout is not getting enforced in Expo app. If you can spot what's the issue let me know:
Next.js:
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/26592968/200203111-a0e17ae9-64e3-492c-ad70-933bc1fbc55f.png">

Expo:
![Simulator Screen Shot - iPhone 14 - 2022-11-07 at 05 36 45](https://user-images.githubusercontent.com/26592968/200202991-158fe116-69ec-4b66-a2d0-a7e60b642a1f.png)

**Comment by natew** [comment]
That’s a different bug fixed in the latest release that just went out.

**Comment by ayushsharma82** [comment]
Tried out the latest release - upgraded via `yarn upgrade:tamagui`

Now metro builder reports this error and hangs my laptop completely:
```sh
iOS Bundling failed 17363ms
Unable to resolve "./icons/user" from "../../node_modules/@tamagui/lucide-icons/dist/cjs/index.js"
```

**Comment by ayushsharma82** [comment]
Deleted `yarn.lock` and `node_modules`, issue went away. Maybe the upgrade script doesn't work every time.

**Comment by ayushsharma82** [comment]
Also, the latest release fixed the original issue. Thanks Nate!
