### ISSUE TITLE
[bug] Media breakpoints does not work on native

### ISSUE THREAD

**Issue by bureyburey** [tamagui/tamagui#351]
**Description**
on the web media queries seem to work great, but on native they seem to be broken.
I know for a fact it used to work on version 1.0.1-beta.193 so I guess some regression occured.

**To Reproduce**
[Demo](https://www.loom.com/share/21d31b868acf4d80b82be2907e0a4fb1)

feel free to check on this [monorepo](https://github.com/bureyburey/vite-ts-tamagui-test.git)

tested using version 1.0.1-beta.211

**Comment by peterjskaltsis** [comment]
+1, I noticed this too. Right now I'm using `useMedia` as a work around like:

```jsx
const media = useMedia();

// ...

<Stack flexDirection={media.sm ? 'row' : 'column'}>...</Stack>
```

But using $sm etc as props on the components has no effect on native.

**Comment by natew** [comment]
Fixed in latest beta
