### ISSUE TITLE
Create `config` from any file and pass it via `Tamagui.Provider`

### ISSUE THREAD

**Issue by dmahajan980** [tamagui/tamagui#36]
Hello, I was trying to set up the library and the docs mentioned that we need to create a `tamagui.config.js` file at the root of the project. I think it might be more flexible to allow developers to define the `config` object in any file. The `config` object can be imported and passed via `Tamagui.Provider`.

For example, I have defined my config in `src/theme.js`:

```javascript
import { createTamagui } from 'tamagui';

const config = createTamagui({ ... });

export default config;
```

I can safely provide the config object via `Tamagui.Provider` in my `src/App.js` file:

```javascript
import config from './theme';

const App = () => {
  return (
    <Tamagui.Provider config={config}>
      {...}
    </Tamagui.Provider>
  );
}
```

**Comment by natew** [comment]
You can define it anywhere really, you just need to specify the filename in build settings if you do so. For type purposes and consistently it's nice to keep it near the root and named like so I think, but it's not strictly required. Separating out the Provider is an option, but not a big change.
