### ISSUE TITLE
[bug] running build never finishes on a vite/tamagui/typescript project

### ISSUE THREAD

**Issue by bureyburey** [tamagui/tamagui#366]
**Description**
running `yarn build` for the web project does build the project but never reaches the Done and has to be stopped manually.

<img width="949" alt="image" src="https://user-images.githubusercontent.com/20264976/201866934-6ced0dd5-98b3-4d9e-821a-7cbf8bfc60d4.png">

when removing the `tamaguiPlugin(...)` from `vite.config.ts` AND also removing the destructuring of it the build does succeed.

<img width="530" alt="image" src="https://user-images.githubusercontent.com/20264976/201867209-b6ea5b81-1039-4faa-a1ed-8aa13dc9d5a0.png">

<img width="951" alt="image" src="https://user-images.githubusercontent.com/20264976/201866270-a2bd052f-d11a-41a2-8ef8-5eb452d523ed.png">

also, when attempting to `import {tamaguiExtractPlugin, tamaguiPlugin} from '@tamagui/vite-plugin';` i am getting this error when trying to `yarn build` AND when trying to `yarn dev`:

<img width="1690" alt="image" src="https://user-images.githubusercontent.com/20264976/201868528-8a6646ba-0d15-4eec-8d63-7f13c7b83c84.png">

using `v1.0.1-beta.216` of Tamagui

this [repo](https://github.com/bureyburey/vite-ts-tamagui-test) can be used to reproduce this issue.

**Comment by bureyburey** [comment]
@natew 
Any idea about what might be the cause for this issue?

**Comment by natew** [comment]
Tried out your repo and I see something different when I enable compiler.

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/12100/205518504-25f240a6-3a68-4e1c-88c2-3f76344a0e50.png">

Next release will have a `loadModule` console log for debugging why it tries to get that path if you set DEBUG=tamagui 03d3545eb

**Comment by natew** [comment]
Tested on a new repo and it works for me
