### ISSUE TITLE
[bug] Accessibility props not stripped

### ISSUE THREAD

**Issue by nandorojo** [tamagui/tamagui#382]
Try adding `accessibilityElementsHidden` to an element.

<img width="499" alt="Screen Shot 2022-11-23 at 6 34 52 PM" src="https://user-images.githubusercontent.com/13172299/203663660-76e064ea-98fb-4b54-a60a-f230f4e6e453.png">

**Comment by nandorojo** [comment]
I think accessibility props might be doing nothing right now.

I tried adding this, but nothing got added to the DOM:

```ts
      accessibilityState={{
        busy: true,
      }}
```

This should add `aria-busy="true"`

**Comment by natew** [comment]
Fixed in latest release at least consistent to what I see on RNW
