### ISSUE TITLE
[bug] : When starting the `ext-expo-solito` app does not rebuild and watch "@my/ui" project

### ISSUE THREAD

**Issue by hitesh97** [tamagui/tamagui#383]
Trying to run `ext-expo-solito` mono repo.. it starts with web and android development apps.

I have done following as per the documentation,

1) run `yarn` on root directory to install global packages
2) run `yarn watch` on root directory to watch all project builds
3) in new terminal window, change directory to `starters/next-expo-solito` and then ran `yarn` again
4) run `yarn web` in another terminal window
5) run `yarn native` in another terminal window

but, When I am making changes / adding components in "@my/ui" they do not seem to rebuild/compile and I do not see changes on the `native` app.

also, I cannot seem to be able to use React style JSX component on "@my/ui" project.

not sure, If I am doing something wrong in set-up.

**Comment by jonsherrard** [comment]
Fixed in https://github.com/tamagui/tamagui/pull/389

**Comment by natew** [comment]
Fixed in latest releases
