### ISSUE TITLE
[bug] using styled(Input) causes 'Parent component is a functional component, ... ' warning message in nextjs.

### ISSUE THREAD

**Issue by kuk941025** [tamagui/tamagui#385]
**Describe the bug**

using styled and TextInput related components cause the following warning message in nextjs.

```
Parent component is a functional component, not a Tamagui styled() component. Extending with styled() will break and lead to incorrect styles. Given options:
```

**To Reproduce**

```tsx
// CustomInput.ts
import { styled, Input } from "tamagui";

export const InputStyled = styled(Input, {
  borderRadius: "$0",
  backgroundColor: "$yellow1Light",
});

// pages/index.tsx
import { Stack } from "tamagui";
import { InputStyled } from "@/components/CustomInput";

export default function Home() {
  return (
    <Stack>
      <InputStyled debug="verbose" />
    </Stack>
  );
}
```

Im using `^1.0.1-beta.220`, and a custom component with `extractable` also gives the same warning message.
I only tested in nextjs.

**System Info (please complete the following information):** 

System:
- OS: macOS 12.3
- CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz- 
- Memory: 24.41 MB / 32.00 GB
- Shell: 5.8 - /bin/zsh
Binaries:
- Node: 16.15.1 - /usr/local/bin/node
- Yarn: 1.22.19 - /usr/local/bin/yarn
- npm: 9.1.2 - /usr/local/bin/npm
Browsers:
- Chrome: 107.0.5304.121
- Edge: 107.0.1418.56
- Firefox: 97.0.1
- Safari: 15.4

**Comment by natew** [comment]
Can you check again, I removed the warning.

**Comment by kuk941025** [comment]
I no longer see the warning message in `1.0.1-rc.0`. Thanks!
