### ISSUE TITLE
[bug] Non sheet select box has a hard dependency on DOM code 

### ISSUE THREAD

**Issue by rymate1234** [tamagui/tamagui#386]
**Describe the bug**

The inline dropdown select seems to have a hard dependency on DOM code -- when the sheet implementation is not used it uses this file https://github.com/tamagui/tamagui/blob/8969917be9f2a6f1f6e751946ee432aa2727186f/packages/select/src/SelectImpl.tsx which utilises DOM specific code, causing the app to crash

**To Reproduce**

Implement a Select box as desribed in the docs but _without_ a `sheetBreakpoint`

![image](https://user-images.githubusercontent.com/581104/204262864-13852fcd-9452-4010-8437-29b8a93168ba.png)

**System Info (please complete the following information):** 

```
  System:
    OS: macOS 13.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 61.30 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.13.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 107.0
    Safari: 16.1
  npmPackages:
    @manypkg/cli: ^0.19.1 => 0.19.2
    @types/react: ^18.0.15 => 18.0.25
    @types/react-native: ^0.69.6 => 0.69.15
    eslint: ^8.21.0 => 8.28.0
    prettier: ^2.7.1 => 2.7.1
    react-native: 0.69.7 => 0.69.7
    turbo: ^1.4.2 => 1.6.3
    typescript: ^4.7.4 => 4.9.3

```

**Comment by natew** [comment]
Yep, Select/Popover don't work native yet they need breakpoints. Popover isn't a native concept really, and Select likewise is totally different on each platform typically. Plan is to add `native` prop to both eventually though with something that renders a bit closer.

**Comment by natew** [comment]
Added warning here 6390b1e87

We'll eventually make it work as a sheet always on native, and then eventually could have a `native` prop to adapt to native sheet implementation.
