### ISSUE TITLE
Weird dependency

### ISSUE THREAD

**Issue by nandorojo** [tamagui/tamagui#39]
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/13172299/155796795-d0ff5eca-d285-48e2-8c0b-0cd60dfdb49f.png">

Running `yarn why react-native-reanimated` gives me this weird dependency that seems to be caused by Tamagui. Not sure why this is a dependency.

**Comment by natew** [comment]
Ah yea, coming from the babel preset we use for static which is just used for tests I think. I'll get that removed for the next release.

**Comment by natew** [comment]
Just landed a fix in https://github.com/tamagui/tamagui/pull/41, once that's out should be good.
