### ISSUE TITLE
[bug] `TextInput` `theme` changes don't update when set back to `undefined`

### ISSUE THREAD

**Issue by nandorojo** [tamagui/tamagui#392]
I have the following logic:

```tsx
<Input theme={error ? 'red' : undefined} />
```

When the error becomes true, the theme goes red. However, once removed, it does not revert back to the previous theme. The `t_red` class remains attached to the DOM node. I can try to repro if needed, or I can send a discord with a screen share. But I think it's a new bug from the recent theme updates.

Setting it to `alt1` fixes it:

```tsx
<Input theme={error ? 'red' : 'alt1'} />
```

This does not fix it (since `dark` is a root theme, I assume):

```tsx
<Input theme={error ? 'red' : 'dark'} />
```

**Comment by dohomi** [comment]
I can confirm that. I currently do a workaround and set the `borderColor` meanwhile (https://github.com/dohomi/tamagui-kitchen-sink/blob/master/packages/ui/src/components/forms/LmInput.tsx#L32)

**Comment by natew** [comment]
Ah we must have regressed removing theme, will add to next
