### ISSUE TITLE
HookWebpackError when running with next.js

### ISSUE THREAD

**Issue by karlsander** [tamagui/tamagui#40]
I'm trying to get tamagui up and running with next.js but I cannot seem to make it work with my config.

I always get the following error (when I try to load the first page, not during startup):

```
error - HookWebpackError: Cannot read property 'replace' of undefined
error - unhandledRejection: HookWebpackError: Cannot read property 'replace' of undefined
```

I have no idea how to start finding the issue because this doesn't even mention a file inside webpack or anything.
I am trying to run it together with expo, maybe that's not supported?

Here is my next config:

```
process.env.TAMAGUI_TARGET = "web";

const { withExpo } = require("@expo/next-adapter");
const { withTamagui } = require("@tamagui/next-plugin");
const withTM = require("next-transpile-modules");
const withPlugins = require("next-compose-plugins");

const transform = withPlugins(
  [
    withTM(["shared", "mobile", "date-fns", "@expo/vector-icons"], {
      resolveSymlinks: true,
    }),
    withExpo,
    withTamagui({
      config: "../shared/utils/tamagui.config.ts",
      components: ["tamagui"],
      importsWhitelist: ["constants.js", "colors.js"],
      logTimings: true,
      disableExtraction: false,
      excludeReactNativeWebExports: ["Switch", "ProgressBar", "Picker"],
    }),
  ],
  {
    projectRoot: __dirname,
    typescript: {
      ignoreBuildErrors: true,
    },
  }
);

module.exports = function (name, { defaultConfig }) {
  return transform(name, { defaultConfig });
};
```

Resolved versions of relevant packages are:
- next@12.1.0
- webpack@5.70.0
- @tamagui/next-plugin@1.0.0-alpha.68
- tamagui@1.0.0-alpha.68
- @expo/next-adapter@3.1.17

Do you have any idea how to debug this?

**Comment by natew** [comment]
If it's at all possible to strip it down to a small example repo that would help a lot. I haven't tested it with `withExpo` but could debug from there.

**Comment by karlsander** [comment]
Yes, happy to do that. Crazy busy week for me, so it will be next week, but I'm very much looking forward to solving this and being able to actually utilize tamagui.

**Comment by natew** [comment]
Lots of fixes have landed since, may want to update and check again.
