### ISSUE TITLE
[bug] Can't style composable parts, such as `Dialog.Title`

### ISSUE THREAD

**Issue by nandorojo** [tamagui/tamagui#413]
**Describe the bug**

```tsx
import { Dialog as TDialog, styled } from 'tamagui'

export const Dialog = TDialog

Dialog.Title = styled(Dialog.Title, {
  fontWeight: 'bold',
  color: '$color12',
  fontSize: '$7',
})
```

I expect this usage to override `Dialog.Title`'s styles. However, `styled` doesn't appear to work. This makes it hard to have a reusable dialog component.

**To Reproduce**

Lmk if you need a repro.

**Comment by natew** [comment]
Hm, this works for me in the sandbox, even if i overwrite Dialog.Title:

<img width="889" alt="image" src="https://user-images.githubusercontent.com/12100/205804597-65da13d4-916e-4f66-bc0d-985123ff0b89.png">

**Comment by natew** [comment]
Closing for now unless you see again.
