### ISSUE TITLE
[bug] Tamagui Core insertStyleRules() function bug

### ISSUE THREAD

**Issue by sohcah** [tamagui/tamagui#415]
**Describe the bug**

In the `insertStyleRules` function in `@tamagui/core`, in production, Style Rules are always inserted regardless of whether or not they have been inserted before.

This causes massive slowdown as tens or hundreds of thousands of style rules are added, very quickly grinding the app to a halt.

This seemed to have been introduced in this commit:
https://github.com/tamagui/tamagui/commit/abf15dc76e483fc5ead44cf24dd2351878623985#diff-c3e01cc72906ae6dcb2f8aa9925a61750dd9fda8d3882fae1e260b88375d654fR146
where a `true` was changed to `''` in production, to make it consistently a string on prod and dev.

![image](https://user-images.githubusercontent.com/51970078/205746228-8c19dc5a-d973-44cb-86c7-2bb471d981b3.png)

This unintentionally made it falsey and as such makes the `if (allSelectors[identifier])` return false every time in production.

I believe just changing this (on the line linked below) from an empty string (`''`) to a string containing a single character (eg. `'-'`) should fix this.
https://github.com/tamagui/tamagui/blob/ea6b2e0c285ad7f98d73e71aa7cd303c0306fc7f/packages/core/src/helpers/insertStyleRule.tsx#L146

**Comment by natew** [comment]
Oh wow

**Comment by natew** [comment]
Fix in a253a35a041aff425175efeb52cb7aaf30b0a382, next rc will have it
