### ISSUE TITLE
Unable to resolve module '@unimodules/core` from '...expo-screen...'

### ISSUE THREAD

**Issue by jo-san** [tamagui/tamagui#42]
#### We are building our UI library in react-native which will get used in our web projects as well, we are trying to move our setup to `tamagui` and facing the below issue in our react-native project setup.

Attaching screenshot for reference:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/4059389/158375167-2c61b970-4187-4aa8-a937-8f402ce1ceeb.png">

**Package details**
`"@tamagui/babel-plugin": "1.0.0-alpha.68"`
`"react-native": "0.63.4"`
`"react-native-web": "0.17.7"`

**babel.config.js**
```[
      '@tamagui/babel-plugin',
      {
        components: ['tamagui'],
        config: './theme.js',
        importsWhitelist: ['constants.js', 'colors.js'],
        logTimings: true,
        disableExtraction: process.env.NODE_ENV === 'development',
      },
    ]```

**Comment by karlsander** [comment]
IIRC tamagui relies on @expo/match-media for media queries on the native site. That requires your project to be [set up for expo modules](https://docs.expo.dev/bare/installing-expo-modules/), formerly known as uni-modules. It should be a straightforward setup, as long as you aren't using react-native-navigation or a native-RN "brownfield" hybrid, then it's 😓

**Comment by natew** [comment]
@karlsander thanks for the heads up, I definitely should document that better or find a way to avoid the hard dep there.

**Comment by jothi-pyt** [comment]
Thanks @karlsander 
As we are using `native-cli` I have installed `react-native-unimodules` package which introduces the below errors, Please check and let me know how to make this work

We are using `@react-navigation/native`

<img width="621" alt="image" src="https://user-images.githubusercontent.com/23206756/160121467-e771e348-b800-4eea-8acb-4efa94a4a2a9.png">

**Comment by natew** [comment]
Please set up a reproduction repo and I'll check it out.

**Comment by natew** [comment]
I restructured things and removed the need for most unimodules stuff, just `expo`. Check the starter repo if you need and guidance.
