### ISSUE TITLE
[bug] [Docs] - Page not found - wrong link

### ISSUE THREAD

**Issue by MananTank** [tamagui/tamagui#426]
On the page https://tamagui.dev/docs/intro/introduction - there's below shown section: 

<img width="826" alt="image" src="https://user-images.githubusercontent.com/22043396/206829939-04af2e78-b010-45ac-89e7-2264cf0b237b.png">

clicking on the above-shown link leads to a 404 page ( https://tamagui.dev/docs/configuration ) - I think the link should should be https://tamagui.dev/docs/core/configuration

**Comment by natew** [comment]
Thank you
