### ISSUE TITLE
expo packages installed are not compatible with Android Gradle 7

### ISSUE THREAD

**Issue by hoodedice** [tamagui/tamagui#43]
The version of `expo-linear-gradient` that gets resolved through tamagui ends up being `11.2.0` which _does not_ have the `maven` --> `maven-publish` fix in `11.0.2` (see: https://github.com/expo/expo/issues/12774 )
```
$ yarn why expo-linear-gradient
├─ tamagui@npm:1.0.0-alpha.68
│  └─ expo-linear-gradient@npm:11.2.0 (via npm:^11.0.2)
│
├─ tamagui@npm:1.0.0-alpha.68 [23952]
│  └─ expo-linear-gradient@npm:11.2.0 [8ac96] (via npm:^11.0.2 [8ac96])
│
└─ tamagui@npm:1.0.0-alpha.68 [50cbc]
   └─ expo-linear-gradient@npm:11.2.0 [8ac96] (via npm:^11.0.2 [8ac96])
```

In tamagui's package json, the rule for linear gradient's version should be `~11.0.2` to fix this for now

**Comment by natew** [comment]
Thanks - fix is in https://github.com/tamagui/tamagui/pull/41, can follow that to see it.

**Comment by natew** [comment]
Let me know if fixed, can try with create-tamagui-app
