### ISSUE TITLE
Update basic installation instructions

### ISSUE THREAD

**Issue by j-fulbright** [tamagui/tamagui#443]
With the default installation instructions, here - https://tamagui.dev/docs/intro/installation#config-file 
It is notated that you need to create a config file and to speed things up, you can use a premade one, but it is not mentioned that if you do that, you need to install additional packages. 

<img width="768" alt="image" src="https://user-images.githubusercontent.com/10793868/209048017-707ca556-495d-4ed9-b926-378ee2e2b415.png">

#303 mentions all of the packages that needed to be added, and fortunately this line addresses it
<img width="750" alt="image" src="https://user-images.githubusercontent.com/10793868/209048499-36b315cc-bbdb-462d-a92b-f52b881510f2.png">

The basic instructions should include information about these packages when using the pre-made configuration, otherwise, it could cause people to think something is broken elsewhere

**Comment by sillyleo** [comment]
+1

**Comment by natew** [comment]
Fixed on latest
