### ISSUE TITLE
[bug] onPress fired twice for styled(Button) on native apps (both Android and iOS)

### ISSUE THREAD

**Issue by apperside** [tamagui/tamagui#446]
**Describe the bug**
When you create a styled Button, its onPress handler is fired twice

**To Reproduce**
[Here](https://github.com/apperside/tamagui-double-click-bug-reproduction) you can find a repo with the issue, but you just need to create a styled button

```typescript
const MyButton=styled(Button,{...myStylesAndVariants})
```

and then

```jsx
<MyButton onPress={()=>alert("clicked")}>CLICK ME </MyButton>
```

and you will see that the alert is shown twice.

It happens only on react-native side, next-js is ok

tamagui version: 1.0.1-rc.5.1

**System Info (please complete the following information):** 

```bash
npx envinfo --system --npmPackages --binaries --browsers

 tamagui version: 1.0.1-rc.5.1
  System:
    OS: macOS 13.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.56 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Brave Browser: 108.1.46.140
    Chrome: 108.0.5359.124
    Firefox: 108.0
    Firefox Developer Edition: 109.0
    Safari: 16.1
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.20.6
    @manypkg/cli: ^0.19.1 => 0.19.2
    eslint: ^8.21.0 => 8.28.0
    prettier: ^2.7.1 => 2.8.0
    turbo: ^1.4.2 => 1.6.3
    typescript: ^4.7.4 => 4.9.3

```

**Comment by izakfilmalter** [comment]
@apperside From what I have read, you don't want to do `styled(Button)`, https://github.com/tamagui/tamagui/issues/180. Instead you need to follow this: https://tamagui.dev/docs/components/button/1.0.0-rc#customization-advanced. I am assuming the double on press is caused by this.

**Comment by apperside** [comment]
> @apperside From what I have read, you don't want to do `styled(Button)`, https://github.com/tamagui/tamagui/issues/180. Instead you need to follow this: https://tamagui.dev/docs/components/button/1.0.0-rc#customization-advanced. I am assuming the double on press is caused by this.

I initially tried to do use that approach, and the event was fired twice. Since my implementation was a bit more customized, I then tried to narrow down the cause, first by using the simplest implementation (exactly the one on the docs) and the event was still fired twice. Then I tried with a minimal  `styled(Button)` and the isse was still there

**Comment by natew** [comment]
Yea we should have an error thrown if you try styled(Button), added to my notes. I'll check this out in a bit.
