### ISSUE TITLE
[bug] Cant install tamagui in fresh expo

### ISSUE THREAD

**Issue by vortechron** [tamagui/tamagui#457]
I install fresh expo project and successfully run the app in simulator, but when i try to setup tamagui, i got this error

```
TypeError: Cannot read property 'useReducer' of null
```

**Comment by vortechron** [comment]
My package.json

```
{
	"dependencies": {
		"@tamagui/font-inter": "^1.0.1-rc.17",
		"@tamagui/shorthands": "^1.0.1-rc.17",
		"@tamagui/theme-base": "^1.0.1-rc.17",
		"dotenv": "^16.0.3",
		"expo": "^47.0.0",
		"expo-dev-client": "~2.0.1",
		"expo-splash-screen": "~0.17.5",
		"expo-status-bar": "~1.4.2",
		"react": "18.1.0",
		"react-dom": "18.2.0",
		"react-native": "0.70.5",
		"react-native-flipper": "^0.176.1",
		"react-native-gesture-handler": "^2.8.0",
		"react-native-safe-area-context": "4.4.1",
		"react-native-web": "~0.18.7",
		"tamagui": "^1.0.1-rc.17"
	},
	"devDependencies": {
		"@babel/core": "^7.19.3",
		"@tamagui/babel-plugin": "^1.0.1-rc.17",
		"@types/react": "~18.0.24",
		"@types/react-native": "~0.70.6",
		"babel-plugin-transform-inline-environment-variables": "^0.4.4",
		"typescript": "^4.6.3"
	},
	"scripts": {
		"start": "expo start --dev-client",
		"android": "expo run:android",
		"ios": "expo run:ios",
		"web": "expo start --web"
	},
	"version": "1.0.0",
	"private": true
}
```

**Comment by jonsherrard** [comment]
I'm not 100% certain but I think this is due to duplicate versions of React. You can use resolutions to pin to a version across dependencies. 

On mobile so can't check.

**Comment by iBotPeaches** [comment]
Thanks @jonsherrard - That was it. I had react 18.1.0 via RN and 18.2.0 via Tamagui.

I feel a bit risky jumping my React Native 70 to React 18.2.0, when I only move `react` versions as React Native moves them, but that got me unblocked.

**Comment by nderscore** [comment]
I think this is because `react` and `react-dom` v18.2.0 are direct dependencies of the `tamagui` package:

https://github.com/tamagui/tamagui/blob/ae9377a26e4a2825681691b5817558765c13cea0/packages/tamagui/package.json#L71-L72

I think they should be peer dependencies instead? 🤔 

---

I had to work around this by setting yarn resolutions to force tamagui to use `react` and `react-dom` v18.1.0

**Comment by natew** [comment]
This has been fixed!
