### ISSUE TITLE
[bug] Dependency on expo-modules-core even if not using LinearGradient.

### ISSUE THREAD

**Issue by iBotPeaches** [tamagui/tamagui#459]
**Describe the bug**

Pretty new to the project, but attempting to just install/run this in a base React Native project. My goal is to not use Expo at all due to the large footprint it has. I figure that is acceptable as long as I don't use LinearGradient, which I don't plan on.

I'm only on like day 6 of Tamagui, so its quite possible my reproducer or examples are wrong in many ways. Still learning :)

**To Reproduce**

```
// https://github.com/iBotPeaches/rn71-rc5-tamagui-test
git@github.com:iBotPeaches/rn71-rc5-tamagui-test.git
yarn install
yarn run android
```

```
error: Error: Unable to resolve module expo-modules-core from /Users/connortumbleson/Desktop/RN0710RC5/node_modules/expo-linear-gradient/build/NativeLinearGradient.android.js: expo-modules-core could not be found within the project or in these directories:
  node_modules
> 1 | import { requireNativeViewManager } from 'expo-modules-core';
    |                                           ^
  2 | import * as React from 'react';
  3 | import { StyleSheet, View } from 'react-native';
```

* I was hoping if I never used LinearGradient - it shouldn't need to import/reference expo.
* An isolated commit of installing Tamagui on top of RN71 is [here](https://github.com/iBotPeaches/rn71-rc5-tamagui-test/commit/4e0c4a01c8752464ce709b5cbf759c5f0b6e70a4)

---
**System Info (please complete the following information):** 

```
  System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 128.08 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 3.3.1 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
    Watchman: 2022.12.05.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.0
  npmPackages:
    @babel/core: ^7.12.9 => 7.20.7 
    @babel/preset-env: ^7.14.0 => 7.20.2 
    @babel/runtime: ^7.12.5 => 7.20.7 
    @react-native-community/eslint-config: ^3.0.0 => 3.2.0 
    @tamagui/shorthands: ^1.0.1 => 1.0.1 
    @tamagui/theme-base: ^1.0.1 => 1.0.1 
    @tsconfig/react-native: ^2.0.2 => 2.0.3 
    @types/jest: ^29.2.1 => 29.2.4 
    @types/react: ^18.0.24 => 18.0.26 
    @types/react-test-renderer: ^18.0.0 => 18.0.0 
    babel-jest: ^29.2.1 => 29.3.1 
    eslint: ^8.19.0 => 8.30.0 
    jest: ^29.2.1 => 29.3.1 
    metro-react-native-babel-preset: 0.73.5 => 0.73.5 
    prettier: ^2.4.1 => 2.8.1 
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.0-rc.5 => 0.71.0-rc.5 
    react-test-renderer: 18.2.0 => 18.2.0 
    tamagui: ^1.0.1 => 1.0.1 
    typescript: 4.8.4 => 4.8.4 
```

**Comment by AnilSeervi** [comment]
Facing the same issue on a brand new RN project.

**Comment by nderscore** [comment]
I think this is because `react` and `react-dom` v18.2.0 are direct dependencies of the `tamagui` package:

https://github.com/tamagui/tamagui/blob/ae9377a26e4a2825681691b5817558765c13cea0/packages/tamagui/package.json#L71-L72

I think they should be peer dependencies instead? 🤔 

---

I had to work around this by setting yarn resolutions to force tamagui to use `react` and `react-dom` v18.1.0

**Comment by iBotPeaches** [comment]
Digging into this more. It seems this is because I just use `tamagui`. If I build my own design system importing via `@tamagui/core`. I could just leverage the dependencies I need to prevent dependency on Expo.

https://tamagui.dev/docs/guides/design-systems

Pair that with `core` peering instead of direct dependencies I can also remove dependency on `react-native-web`. This may prove to be false, but investigating that route now.

**Comment by iBotPeaches** [comment]
I believe after spending more time with Tamagui - I understand. After producing our own design kit which is honestly just a subset of exported `@tamagui/*` parts - all these issues resolved. We just won't export/use components we know introduce a dependency we don't need.

No more dependency on expo or rnw. Highly isolated and meant for specific RN projects w/ no Expo. Pushed up here - https://github.com/sourcetoad/tamagui-react-native

Closing.
