### ISSUE TITLE
[bug] BottomSheet with inputs not working on native

### ISSUE THREAD

**Issue by apperside** [tamagui/tamagui#468]
This is a follow up for issue #292  , which was opened because it was not working on web.
As [I stated](https://github.com/tamagui/tamagui/issues/292#issuecomment-1367094212) in that issue, the problem is solved, but unfortunately  it's now broken on native side, android side only apparently (tried on both device and simulator, on iOS I could have only tested on simulator and it's working).

For the purpose of this issue, I created [a brand new repository](https://github.com/apperside/tamagui-bottom-sheet-bug-reproduction) with the latest create tamagui-app@1.0.1

**To Reproduce**
- clone this repo https://github.com/apperside/tamagui-bottom-sheet-bug-reproduction
- checkout the branch bottomsheet-bug 
- run on Android
- open the bottom sheet and focus one oh the inputs

**Comment by apperside** [comment]
Hello @natew ,
any news on this?
I just tried to clone the reproduction repo, run `upgrade:tamagui` and try it again, but the problem still persists with tamagui 1.2.12 ( the issue was first opened for tamagui 1.0.1).

⚠️ **the bug reproduction have been moved to the branch `bottomsheet-bug`**⚠️

**Comment by natew** [comment]
Sheet now has a prop to avoid keyboard
