### ISSUE TITLE
Guides/Developing throws 404 error 

### ISSUE THREAD

**Issue by mikeytown19** [tamagui/tamagui#47]
When clicking on The Button below
![image](https://user-images.githubusercontent.com/16158800/167181151-134b64e9-d4a3-4594-83b2-f1c17b1dda1b.png)

it takes you to this page with 404 
![image](https://user-images.githubusercontent.com/16158800/167181242-c50eb2b7-a92d-4a1b-9e20-59539dda2d19.png)

**Comment by natew** [comment]
Thanks, fixed
