### ISSUE TITLE
[bug] expo-router support?

### ISSUE THREAD

**Issue by erickreutz** [tamagui/tamagui#474]
From my limited testing, this does not yet support `expo-router` as I'm getting NavigationContainer errors when using `useLink` in combination with `<Button {...linkProps} />` but importing `Link` from `expo-router` seems to work fine. Is this the case or am I doing something wrong?

**Comment by erickreutz** [comment]
Was able to get this working by tweaking the starter repo a bit more.

**Comment by lostpebble** [comment]
@erickreutz could you please share what tweaking you did? I'd also like to use `expo-router` with Tamagui.

**Comment by ArthurYidi** [comment]
@lostpebble The tamagui starter is out of date, I recommend referencing solito's: https://github.com/nandorojo/solito/tree/master/example-monorepos/with-expo-router

I was able to get it working by:
- removing `@react-navigation` packages
- removing navigation providers
- removing `ThemeProvider` from `_layout.tsx`
