### ISSUE TITLE
Dialogs don't respect theme settings [bug] 

### ISSUE THREAD

**Issue by GigaBigBoss** [tamagui/tamagui#477]
Everything else appears to properly accept theme except dialogs which instead will switch based on device lightmode/darkmode.
(I'm using DidSSRFinish() so this bug might only occur under whilst using outside of SSR)

![Code_izb9n11JxM](https://user-images.githubusercontent.com/106954969/210139779-2576a8cb-fa62-4449-8762-1853de77350d.png)
![Code_lkzRQaTIlx](https://user-images.githubusercontent.com/106954969/210139782-a73fa6c3-0919-451f-84c2-24d1549ef435.png)
![chrome_bDDBNS91EC](https://user-images.githubusercontent.com/106954969/210139784-4e3b340d-a224-4944-89db-36d7a9b48e2b.png)

**Comment by lobor** [comment]
What is your tamagui.config.ts ?
