### ISSUE TITLE
Text input styling break outside of SSR [bug] 

### ISSUE THREAD

**Issue by GigaBigBoss** [tamagui/tamagui#478]
Code where the issue is occuring:
![Code_VTAQVg2khB](https://user-images.githubusercontent.com/106954969/210139857-baaf52bf-0bbc-461f-8bc0-0b3bb1c7fade.png)

What it should look like:
![chrome_ZzZkKCRite](https://user-images.githubusercontent.com/106954969/210139883-6e87443d-b787-4b50-a67c-a7df90f48888.png)

What it looks like:
![chrome_PLRux3kJJv](https://user-images.githubusercontent.com/106954969/210139901-3b40dff6-9c02-460c-ab3c-4e1ea9cb0a86.png)

Here's a repo with the bug: https://github.com/GigaBigBoss/tamagui/tree/master/starters/next-expo-solito
and you can see it live here: https://tamagui-sandbox.vercel.app/

Issue doesn't occur when not using "SSR finish", issue seems to be present with more than just separators but am unsure what else at the moment, issue also appears to of popped up within the last month or so.

**Comment by GigaBigBoss** [comment]
Seems to also happen without a separator

**Comment by natew** [comment]
looking at this one shortly

**Comment by natew** [comment]
Just tested this on a branch: https://github.com/tamagui/tamagui/pull/new/repro-1

Don't see it happening on Next latest + Tamagui latest.
