### ISSUE TITLE
[bug] Reproducibly failing Vite project

### ISSUE THREAD

**Issue by tazsingh** [tamagui/tamagui#479]
Hey Nate, congrats and thanks for the v1 release! Super excited to give it a go 😄 

Sadly, I've ran into various teething issues with a Vite project. I've widdled it down to a minimally reproducible example that I've put into a CodeSandbox - https://codesandbox.io/p/sandbox/tamagui-vite-ssr-h3ueim . Let me know if you'd prefer that I add it to the `apps` folder!

In essence, I'm trying to set up Tamagui on Vite, with the compiler and with SSR. The above CodeSandbox is about as far as I can get. It renders fine on the client, without the compiler. The SSR dev server seems to pick up `react-native` module issues, despite only targetting the web.

I've annotated everything I've seen with a `TODO` in the codebase, so you should be able to more easily search. But to list them here as well:

`vite.config.ts`
1. Named import from `@tamagui/vite-plugin` doesn't seem to work correctly
2. I don't believe the Vite plugin is correctly applying its settings, from React Native Web Lite to Aliases
3. The compiler fails with errors originating from `variableToCSS` / `createCSSVariable`, where it appears to be trying to create a variable for the Proxy Worm, which I can't figure out why the config is being detected as such in the first place?

`devServer.ts`
1. Transpiling for the client works fine (via `yarn dev` -> `yarn dev:client`), however transpiling for SSR seems to pick up `react-native` modules (change `yarn dev` -> `yarn dev:ssr` in `package.json`)

Again, do let me know how I can help or if you need any more information on what I'm seeing! Hopefully, the CodeSandbox is a good starting point 🤞 

Much appreciated 🙏

**Comment by natew** [comment]
Thanks for the detailed issue @tazsingh 

Vite support has been less supported, it works in the monorepo but we don't have regression tests for outside the repo which would be helpful. This will be a good issue to track fixes, I should have time to look more deeply soon.

**Comment by natew** [comment]
@tazsingh can I clone that codesandbox somehow? Not familiar with it in general.

**Comment by tazsingh** [comment]
@natew Thanks! Yeah, there's the Fork button in the top right corner. It looks like you need to be signed in to do that

I've also added you as a Collaborator with Edit access directly on that same Sandbox above, so you don't need to Fork

**Comment by tazsingh** [comment]
Let me know if you got it! Also, happy to schedule in some time to pair up on this on your stream if you like 🙂

**Comment by Xmaxer** [comment]
I basically couldn't get the Vite plugin to work at all in its current state, importing @tamagui/vite-plugin just caused crash at start for me as well.

I am working in an ESM project, and I am not using SSR.

Full disclaimer that this isn't some kind of great permanent solution, this is really a hack to provide some insight. Also unsure if this is related to this issue, but this is where I landed after googling and seems the most relevant. Happy to raise a separate issue for this if not related.

What got it fully working was this patch (using patch-package), and I didn't have change any of my imports or setup from the official docs:

<details>

<summary>
The two changes were adding the 'type' to the package.json and setting it to 'module', as well as fixing an import in `extract.js`
</summary>

```
diff --git a/node_modules/@tamagui/vite-plugin/dist/esm/extract.js b/node_modules/@tamagui/vite-plugin/dist/esm/extract.js
index 233755c..54ebcb5 100644
--- a/node_modules/@tamagui/vite-plugin/dist/esm/extract.js
+++ b/node_modules/@tamagui/vite-plugin/dist/esm/extract.js
@@ -1,13 +1,10 @@
 import path from "path";
-import {
-  createExtractor,
-  extractToClassNames,
-  getPragmaOptions
-} from "@tamagui/static";
+import TamaguiStatic from "@tamagui/static";
 import outdent from "outdent";
 import { normalizePath } from "vite";
 const styleUpdateEvent = (fileId) => `tamagui-style-update:${fileId}`;
 const GLOBAL_CSS_VIRTUAL_PATH = "__tamagui_global_css__.css";
+const {  createExtractor, extractToClassNames, getPragmaOptions } = TamaguiStatic
 function tamaguiExtractPlugin(options) {
   const disableStatic = options.disable || options.disableDebugAttr && options.disableExtraction;
   if (disableStatic) {
diff --git a/node_modules/@tamagui/vite-plugin/package.json b/node_modules/@tamagui/vite-plugin/package.json
index 48e2ee4..03eb4c1 100644
--- a/node_modules/@tamagui/vite-plugin/package.json
+++ b/node_modules/@tamagui/vite-plugin/package.json
@@ -4,6 +4,7 @@
   "types": "./types/index.d.ts",
   "main": "dist/cjs",
   "module": "dist/esm",
+  "type": "module",
   "license": "MIT",
   "files": [
     "src",

```

</details>

I still didn't look into the issues for 'tamaguiExtractPlugin' which is still giving me errors, but works without it for now.

**Comment by natew** [comment]
At thanks I’ll fix this today.

**Comment by natew** [comment]
Try it out again in 1.1.9

**Comment by tazsingh** [comment]
Can confirm it works in the updated sandbox! 🎉 

I'm still having issues with SSR, but I think that's on my end. I'll continue debugging and create a new issue if it's something with Tamagui.

Thanks!
