### ISSUE TITLE
[bug] undefined props override styled properties

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#484]
**Describe the bug**

Undefined properties will override default values. Rendered container has no defined background color. When I remove backgroundColor property it is working fine.
Expected behaviour: undefined properties should be ignored.

**To Reproduce**

```tsx
const StyledContainer = styled(HStack, {
  backgroundColor: 'red',
  },
});


<StyledContainer backgroundColor={undefined} />
```

Version 1.0.2

**Comment by natew** [comment]
I think this is actually desired, otherwise you can't override backgroundColor to set it to be undefined in a parent component. I think the solution for this is just using a conditional spread: `<StyledContainer {...ifNeeded && { backgroundColor: 'green' }} />`
