### ISSUE TITLE
[bug]  media properties are broken for space in stacks

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#489]
**To Reproduce**
Tamagui always uses the first value when you try to change space for different media queries. In this case it will use 50px for the small and large screens as well.

```tsx
import { XStack, YStack } from 'tamagui';

<XStack
  $gtSm={{
      space: 50,
   }}
   $gtLg={{
       space: 200,
    }}
  > 
 
<YStack />
<YStack />

</XStack>
```

**Expected behaviour**

For large screen I will see space === 200px. For small screen I will see space === 50px;

Tamagui: 1.0.2

**Comment by natew** [comment]
Great catch, the media query refactors regressed this, fixed here: https://github.com/tamagui/tamagui/pull/508/commits/27c5183886ef658e362238e7565aa6a8aa9aad8c
