### ISSUE TITLE
[bug] Default `light` theme has faint button text color

### ISSUE THREAD

**Issue by ayushsharma82** [tamagui/tamagui#501]
**Describe the bug**

Hi,

I just used the tamagui starter and there is a small but weird issue related to theme. The buttons in `light` theme have a very faint text color instead of using black or something. This is reproducible in both web and native therefore my guess is something is wrong with the default theme only.

@natew A quick fix would be great.

### Screenshot:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/26592968/211004961-5d26d73b-c09e-4695-8051-acc8021dc1ef.png">

**To Reproduce**

```
npm create tamagui@latest
```

**Comment by natew** [comment]
Next release fixes 0ef8f012dbb847d7376e4fa80262aa4b45bca6c8
