### ISSUE TITLE
@tamagui/button - ARIA: link role - Replace <button role="link"> with <a>

### ISSUE THREAD

**Issue by criszz77** [tamagui/tamagui#505]
When used with `accesibilityRole="link"`(props returned by `Solito` for example), the `@tamagui/button` component is rendering a button HTML element with `role="link"` which I believe is an anti-pattern. 

While you [can customize the button](https://tamagui.dev/docs/components/button/1.0.0#customization-advanced) to achieve the wanted behaviour, I think that Tamagui should handle it internally as well.

Source: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/link_role

>Where possible, it is recommended that you use a native [&lt;a>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) element rather than the link role, as native elements are more widely supported by user agents and assistive technology. Native [<a>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) elements also support keyboard and focus requirements by default, without need for additional customization.
> ### [Best practices](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/link_role#best_practices)
> The various widget roles are used to define common interactive patterns. Similar to the document-structure roles, some of these roles, including the link role, duplicate the semantics of native HTML elements that are well supported, and should not be used.
> Avoid using `link`, which we've included for completeness. The [&lt;a>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) semantic equivalent with accessible interactivity is available and supported.

---

**To Reproduce**

1. `npm create tamagui@latest`
2. Run the app on the web
3. Inspect the `Link to user` button
![image](https://user-images.githubusercontent.com/55203625/211073370-0b2990ee-7eec-47a1-ac50-60265f545dc9.png)
4. Disable JavaScript.
5. Buttons won't work.

6. Go to https://tamagui.dev/
7. Disable JS.
8. Except for some theme colors, most of the website can be used because anchors are used.

---
The  `Pressable`  component from  `react-native-web` with `accesibilityRole="link"`  is rendering anchors:

1. Go to https://luna-gamma.vercel.app/ which is built with Next.js and `react-native-web`
4. Disable JS.
5. Buttons are still functional.

**Comment by t1gu1** [comment]
I totaly agree with you!

It give: (For web)
- Better semantic
- Better for A11y
- Works when javascript is disabled

---

My _"workaround"_ was to add the **props** `tag="a"`.
But it adds an **underline** to the text **inside the button** and that's not look great.
So I use `styled` to custom the button to remove the underline.

So yeah, would be nice if it handled by default when the button is a **link**.

**Comment by natew** [comment]
Testing here d8a7a1a43602c9f3519cfc00a1b9a71fa850239f

**Comment by criszz77** [comment]
@natew  I tested the new functionality. While it's better, having the anchor will add the `text-decoration` CSS prop:

<img width="147" alt="Screenshot 2023-01-14 at 15 37 41" src="https://user-images.githubusercontent.com/55203625/212474688-5278dbd7-1bce-4a25-b00c-46a0fad4db62.png">

One fix that I found is adding `textDecoration: 'none'` to the `style` prop. If it's ok, I can open a PR:


<img width="1106" alt="Screenshot 2023-01-14 at 15 24 59" src="https://user-images.githubusercontent.com/55203625/212474541-0c430865-1360-42a3-96b8-b4e99ef8e1f7.png">

**Comment by natew** [comment]
I added a note to the docs, add this somehwere in your app: `import '@tamagui/core/reset.css'`. It is true we could avoid this by having it directly there but for now this works.
