### ISSUE TITLE
[bug] dataSet on Ystack show object

### ISSUE THREAD

**Issue by lobor** [tamagui/tamagui#512]
On tamagui 1.0.2, when i use dataSet props on YStack component, the render is dataset="[object Object]"

![image](https://user-images.githubusercontent.com/3316940/211265055-bdb68564-7323-454e-a759-4dfc30f6f2a9.png)
![image](https://user-images.githubusercontent.com/3316940/211265093-7d3cc567-0275-4798-a547-5f81cf734331.png)

**Comment by natew** [comment]
Fix coming in next patch 1767ef97e5
