### ISSUE TITLE
[bug] Exclude withTamagui on api routes

### ISSUE THREAD

**Issue by pontusab** [tamagui/tamagui#513]
**Describe the bug**
I just noticed that tamagui is added to API routes, especially when trying to add `@vercel/og` it fails because `withTamagui` is added. Is there a way to exclude `withTamagui` from API-routes? 

**To Reproduce**
Compile and look at the output API file.

```
npm create tamagui@latest
```

Make your changes and then push and link it here. 🙏🙏🙏🙏🙏

**System Info (please complete the following information):** 

Output of `npx envinfo --system --npmPackages --binaries --browsers`

```
  System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 22.01 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 3.2.4 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2022.12.26.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 15.1
```

---

- [ ] yarn.lock or similar
- [ ] If it's a specific file, add `//! debug` to the top (the `!` works in esbuild compiled packages but not necessary always) and include that (only for compiler, but helps to know if it's on or off).
- [ ] Run your server/bundler with `DEBUG=tamagui` and include that output at the bottom.

**Comment by natew** [comment]
This is the logic here, I copied from other plugins that look for the non-next non-api loaders:

https://github.com/tamagui/tamagui/blob/master/packages/loader/src/plugin.ts#L67

If you find that file in your local app node_modules/@tamagui/loader/dist/cjs/plugin.js or something like that you can try modifying it and seeing what works? Would be helpful if you find some patch.

**Comment by natew** [comment]
@pontusab if you can do me a favor and check/close if this if fixed

**Comment by pontusab** [comment]
I can confirm adding this to `withTamagui` works but I haven't looked into why yet:

```
https://github.com/tamagui/tamagui/blob/master/packages/next-plugin/src/withTamagui.ts#L319


const cssRules = webpackConfig.module.rules.find(
          (rule) =>
            Array.isArray(rule.oneOf) &&
            rule.oneOf.some(
              ({ test }) =>
                typeof test === 'object' &&
                typeof test.test === 'function' &&
                test.test('filename.css')
            )
        ).oneOf.filter(x => x.issuerLayer !== 'api')


```

**Comment by natew** [comment]
Hm that would just disable all CSS support I'd imagine breaking the app... because the filter will clone it and so not mutate the original.

**Comment by natew** [comment]
Yo, closing some old issues, that code looks odd to me but if you can check one more time would be super helpful. Haven't seen anyone else having this :/

**Comment by pontusab** [comment]
Still an issue, will give you a repo
