### ISSUE TITLE
[docs] How to run kitchen Sink

### ISSUE THREAD

**Issue by mwood23** [tamagui/tamagui#517]
In order to run the expo app for tamagui, looks like we need a development build of the project. Not sure the best way to handle for contributors since looks like this is managed through EAS.

```
Logs for your project will appear below. Press Ctrl+C to exit.
› Opening on iOS...
CommandError: No development build (com.natew.myapp) for this project is installed. Please make and install a development build on the device first.
Learn more
```

**Comment by natew** [comment]
Lmk if still an issue, I think it's rebuilt now so it should work.

**Comment by thegitparticle** [comment]
any update on this? it causes the same error stated in the first comment

**Comment by percy507** [comment]
I am facing same problem. 

1. git clone the project
2. yarn
3. yarn kitchen-sink:build:android (then the error happens: `Please verify that the package.json has a valid "main" entry`)

I sloved this by build the packages. `yarn build` and `yarn build:js`
