### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by sebastianvitterso** [tamagui/tamagui#52]
Hi, I just noticed a typo on your website, and thought you might like to fix it. 

![image](https://user-images.githubusercontent.com/37065184/168030941-5f8a271c-8299-4919-8979-4ad1d5d79efd.png)

You've written `ryhthm`, but according to (e.g.) [wikipedia](https://en.wikipedia.org/wiki/Rhythm), the correct spelling is `rhythm`.

**Comment by natew** [comment]
Thank you, fixed.
