### ISSUE TITLE
[bug] Warning, duplicate ID for input: password on RN

### ISSUE THREAD

**Issue by nickreese** [tamagui/tamagui#520]
Warning, duplicate ID for input: password 

```
        <Input
          secureTextEntry
          textContentType="password"
          f={1}
          id="password"
          autoComplete="password"
          onChangeText={setPassword}
        />
```

**Describe the bug**

It appears autoComplete also must be adding an id.

**Comment by lobor** [comment]
if you use nativeID ?

**Comment by natew** [comment]
Need more info too

**Comment by gitstud** [comment]
I also see this, I think an example for a form using Label, Input, Trigger, and validation would be a huge help for first time adopters of tamagui.  

`<Label htmlFor="email">Email</Label>
            <Input
              id="email"
              autoComplete="email"
              placeholder="Email"
              value={email}
              onChange={(e) => setEmail(e.nativeEvent.text)}
              // @ts-expect-error
              required
            />`
            
            
results in duplicate id email and likewise for password.
            
Also when I remove that or add the onChange to the inputs, then I lose focus after each keypress.

expo:48.0.15, expo-router:1.5.3, tamagui:1.26.0 

This is the best example I can find for a complete form example but it is not using labels.

https://github.com/tamagui/tamagui/blob/f9aa6eafa614ba02783c04f6e2a80e5a748b3e9e/apps/site/pages/login.tsx#L133

**Comment by gitstud** [comment]
Looks like everything is working great when using react-hook-form to manage formState and just using tamagui for UI elements
