### ISSUE TITLE
Border Radius is not typed correctly for Image

### ISSUE THREAD

**Issue by mwood23** [tamagui/tamagui#522]
Looks like the types aren't coming through for `borderRadius` on image. However, if you pass it a token like this `borderRadius="$2"` it works. I could repro it on the docs site.

<img width="949" alt="CleanShot 2023-01-10 at 16 24 42" src="https://user-images.githubusercontent.com/13633613/211683323-dff5353c-0735-4cf1-9d60-b290791ab562.png">

**Comment by natew** [comment]
Fix coming 38a32b087701cf2c727408aadcb3c73ac811bf01
