### ISSUE TITLE
Reanimated crashing when using animations 

### ISSUE THREAD

**Issue by cmaycumber** [tamagui/tamagui#53]
When using the code: 

```jsx
<Square
  bc="$pink10"
  animation="bouncy"
  elevation="$4"
  size={110}
  br="$9"
  hoverStyle={{
    scale: 1.2,
  }}
  pressStyle={{
    scale: 0.9,
  }}
>
  <MyComponent width="$4" height="$4" />
</Square>;
```
I'm getting the following error: `Tried to synchronously call anonymous function from a different thread.`

**Comment by natew** [comment]
What platform, OS, browser, node?

**Comment by dmegue** [comment]
Facing the same issue in Android, browser works fine.

**Comment by cmaycumber** [comment]
Sorry for the late reply @natew 

> What platform, OS, browser, node?

OS - Mac Intel w/ iOS simulator
Browser - n/a
Node - v16

**Comment by natew** [comment]
I had some issues recently with simulator as well, a bit different, but if I attach the Chrome devtool debugger it fixes it. Seems like something in Reanimated itself.

Could anyone verify if that fixes for them?

**Comment by kyunghoon** [comment]
i also bumped into this issue.

when attempting to remote debug, it crashed with a different issue of "document not defined"

used a fresh install of `create-tamagui-app` on `1.0.1-beta.70`

**Comment by kyunghoon** [comment]
it's crashing again.

in `createAnimations.js` the inner function that is return by `callback(...)` *must* be anonymous.
typescript generates additional code which cannot be denoted as a worklet when the inner function is given a name.

**Comment by kyunghoon** [comment]
also, the fix i made had `onExitComplete` called. it doesn't seem to be working it anymore with beta.72

**Comment by natew** [comment]
@kyunghoon thanks, I did merge your PR mostly as-is and just made small adjustments to fix the exit thing in other areas, I think there's still some bug with exit but if you set exitStyle it doesn't happen. If I get a chance I'll take a look soon.

I have `keepNames` true now in tamagui-build, going to turn that off for next release.

**Comment by natew** [comment]
Lmk if it's still going on.
