### ISSUE TITLE
[bug] Font Weight automatically decreases after using color prop in Header Tag.

### ISSUE THREAD

**Issue by yo9e5h** [tamagui/tamagui#532]
**Describe the bug**

**To Reproduce**

```
<H2>Hello</H2>
<H2 color="$green11Dark">Yogesh</H2>
```

**System Info:** 

``` 
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 108.39 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.2.3 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 108.0.2
    Safari: 16.2
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.20.7
    @manypkg/cli: ^0.19.1 => 0.19.2
    @react-navigation/bottom-tabs: ^6.5.3 => 6.5.3
    eslint: ^8.21.0 => 8.31.0
    prettier: ^2.7.1 => 2.8.2
    turbo: ^1.4.2 => 1.7.0
    typescript: ^4.7.4 => 4.9.4
```

**Providing Screenshots 
![Simulator Screen Shot - iPhone 14 Pro - 2023-01-12 at 20 55 38](https://user-images.githubusercontent.com/11131787/212109988-98e78c9c-d9f4-4de6-b8b9-d714e329bf69.png)
for reference:** 

---

**Comment by jonsherrard** [comment]
+1 for some odd font-weight stuff on headers.

Upgrading from 1.0.1 to 1.0.7 my headings received "extra" bolding on web, and I had to set font-weight 400 on them in a style reset.

Not sure what changed.

**Comment by natew** [comment]
Yea something happened on fontWeight in patch 2 or 3. Should be fixed very soon.

**Comment by natew** [comment]
Have a fix almost ready. Leave the compiler off for now on native.

**Comment by natew** [comment]
1.0.9 Should fix, re-open if not.

**Comment by yo9e5h** [comment]
I can confirm, 1.0.9 fixed it for both native and web.
