### ISSUE TITLE
[bug]  children of `Footer` componenst missing unless `disable_extraction=true`

### ISSUE THREAD

**Issue by jonsherrard** [tamagui/tamagui#533]
**Describe the bug**

Unless `disable_extraction=true` is set, the Tamagui `Footer` component or any other view with `accessibilityRole="footer"` set is rendered as empty:

`<footer></footer>`

Footer renders as expected with `DISABLE_EXTRACTION=true`

**Comment by natew** [comment]
In the sanbox with extraction enabled I'm seeing it properly: 

<img width="701" alt="image" src="https://user-images.githubusercontent.com/12100/212488126-eb1dbaa4-7f7a-4b6a-89df-50b4526ce31b.png">

Need some more info to replicate.
