### ISSUE TITLE
[bug] version 1.0.8 is mismatched

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#536]
When I use the property "color" in the styled component, it is not working.
It was working fine in version 1.0.4. After upgrade to 1.0.8 something changed and it is not working anymore.

**Comment by natew** [comment]
Need more info to debug as it’s working currently. There’s a compiler bug I think you’re referring to on native. Try turning off compiler on native. Fix is almost ready and will be out today.

**Comment by seeden** [comment]
I have problem with web. I will try to create small reproduction now

**Comment by seeden** [comment]
```tsx
import { SizableText, styled } from 'tamagui';

export const StyledSizableText = styled(SizableText, {
  name: 'TextSizableText',
  variants: {
    muted: {
      true: {
        color: 'red',
      },
    },
  } as const,
});
```

```tsx
<StyledSizableText muted>I am read text</StyledSizableText>
```

Text is always black

**Comment by seeden** [comment]
@natew as I mentioned in previous example probably it is somehow connected to styled methods

**Comment by seeden** [comment]
One small improvement I also see font-family as element attribute. we should remove it.
```tsx
<span font-family="$body">TEST</span>
```

**Comment by natew** [comment]
Will check, thanks. I did notice that attribute is falling through too.

**Comment by seeden** [comment]
Thank you

**Comment by seeden** [comment]
It is probably related to this change:
https://github.com/tamagui/tamagui/commit/7d713b276c52e5099fca42e595637b8f4c1f4417#r96119380

**Comment by natew** [comment]
That was fixed before release it uses name now, but found the issue, 1.0.10 going out now!
