### ISSUE TITLE
running ejected expo app within xcode is broken

### ISSUE THREAD

**Issue by kyunghoon** [tamagui/tamagui#54]
Running `metro run:ios` successfully ejects/generates xcode project files and runs successfully outside of xcode. Inside however, metro paths become incorrect.

I believe it's related to this issue `https://github.com/facebook/metro/issues/605`. My guess is that react-native and workspaces do not get along.

Any advice on getting it to run without `expo-go` on a device would be greatly appreciated.

**Comment by natew** [comment]
Try out `rnx-kit`: https://github.com/microsoft/rnx-kit

**Comment by laogui** [comment]
I don't like expo too.
