### ISSUE TITLE
[bug] @tamagui/core - startClearStyleCacheInterval - prevents node process from exiting

### ISSUE THREAD

**Issue by criszz77** [tamagui/tamagui#543]
**Describe the bug**

 Similar to #540 - `startClearStyleCacheInterval` found in [packages/core/src/helpers/getStylesAtomic.ts](https://github.com/tamagui/tamagui/blob/master/packages/core/src/helpers/getStylesAtomic.ts#L52-L56) has a `setInterval` that's hanging.
```
PASS  src/__tests__/App-test.tsx
  ✓ renders correctly (22 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.46 s, estimated 3 s
Ran all test suites.

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  Timeout



      at startClearStyleCacheInterval (node_modules/@tamagui/core-node/dist/static.js:7058:3)
      at createTamagui (node_modules/@tamagui/core-node/dist/static.js:9878:3)

```

**To Reproduce**

Source code: https://github.com/criszz77/luna/tree/withTamagui
Failing pipeline: https://github.com/criszz77/luna/actions/runs/3922716171/jobs/6705843301

1. Run to install: 
<pre>npx react-native init <b>MyAppName</b> --template @criszz77/luna@next</pre>

2. Run `yarn jest --detectOpenHandles`

**Comment by natew** [comment]
Thanks, fixed in 94cbc1691b0fb39de6ca3c28a0b78623800a74c7
