### ISSUE TITLE
[bug] SheetScrollView Bug

### ISSUE THREAD

**Issue by ayushsharma82** [tamagui/tamagui#549]
### **Describe the bug**

I tried the `Sheet` component and there is a bug in `Sheet.ScrollView` component which cancels out the touch events. This bug is reproducible with the `Select` component as it uses Sheet for touch devices. I can see the Select.Item changing opacity in response to the press but it quickly cancels that action.

I only faced this issue on Android while it worked flawlessly on iOS.

### **Potential Fix**

Here's the line which causes the issue: https://github.com/tamagui/tamagui/blob/ff0df784fa6f99998c715e3abd72239244659708/packages/sheet/src/SheetScrollView.tsx#L89

I supplied the `Sheet.ScrollView` component with `onMoveShouldSetResponder={() => false}` and touch events started working again ( with scroll ). Looks like this was the root cause. I can confirm it works on both Android and iOS.

**To Reproduce**

Use the Select demo code from docs in expo.

**Comment by natew** [comment]
Fixed
