### ISSUE TITLE
Fails to build for expo.dev 

### ISSUE THREAD

**Issue by kyunghoon** [tamagui/tamagui#55]
After several hours of debugging, i figure out a hacky workaround.

`@tamagui/core/dist/cjs/constants/rnw.js` imports react-native-web and causes build errors on their servers. Commenting the offending lines fixes the issue on native, but breaks web. A conditional will not work because metro expands `require` statements. I suppose the proper fix would either be splitting @tamagui/core into native and web variants, or some sort of babel transformation.

**Comment by natew** [comment]
It should only import react-native-web if `TAMAGUI_TARGET = 'web'` which shouldn't be set for native builds. Are you setting that to web? Can you give me commands to build on expo.dev so I can replicate?

**Comment by kyunghoon** [comment]
this is not the case for `tamagui/packages/core/dist/cjs/constants/rnw.js`. it includes `react-native-web` outside of a TAMAGUI_TARGET === 'web' conditional. furthermore it wouldn't matter even if it were as metro expands the code before the conditional is even executed.

i got around this issue by creating a copy of `rnw.js` to `rnw.native.js` and removing the offending lines. unfortunately this ends up breaking `@tmagui/babel-plugin`, so i currently have it disabled.

the command used for deploying to expo is `eas build --profile development --platform ios`

**Comment by natew** [comment]
Thanks for the info, I'll check this out soon.

**Comment by natew** [comment]
I think this is fixed, I redid a few times this logic and it should follow module/main.
