### ISSUE TITLE
[bug] Select Component example breaks native production build

### ISSUE THREAD

**Issue by matthewhausman** [tamagui/tamagui#558]
Very simply please do not use an underscore in numbers if you will be deploying your native app through expo and EAS. I copied the code from the select component example and debugged for hours until I found that it was erroring due to the underscore within the z index style.

**Comment by natew** [comment]
Oh interesting, we need to compile to a lower target...

**Comment by natew** [comment]
Oh I see this is in copied, code, our transpiled code is fine.

**Comment by matthewhausman** [comment]
Thank you very much

**Comment by natew** [comment]
Fixed this on my stream, was a super confusing error. Opened an issue on Metro and then fixed in the code.
