### ISSUE TITLE
react native error of Tried to register two views with the same name RNCSafeAreaProvider

### ISSUE THREAD

**Issue by kyunghoon** [tamagui/tamagui#56]
running `expo run:ios` causes runtime errors due to module version conflicts.

the current version of expo uses `react-native-safe-area-context@4.2.4`. `tamagui/package.json` has a requirement of `^4.2.5`. lowering it to `^4.2.4` should resolve this issue.

**Comment by natew** [comment]
Hm, the latest starter repo runs for me, you may need to dedupe by using yarn `resolutions` or similar.

**Comment by kyunghoon** [comment]
Resolutions did the trick. Thanks.
