### ISSUE TITLE
[bug] Color token of the form `${colorName}${number}` not available in autocomplete for bg or color props on tamagui components

### ISSUE THREAD

**Issue by matthewhausman** [tamagui/tamagui#570]
<img width="718" alt="Screen Shot 2023-01-23 at 9 42 37 AM" src="https://user-images.githubusercontent.com/25216513/214068106-285950b3-c09c-4de3-99d9-e3e8021f84a2.png">

**Comment by matthewhausman** [comment]
The token actually works and will not show a ts error, but is not available in the autocomplete

**Comment by natew** [comment]
Fixed by https://github.com/tamagui/tamagui/commit/e0480b6ce88501e13e9e74cdbdae7d1cc9d8bb34
