### ISSUE TITLE
[bug] Lucide Icon behavior seems incompatible with theming (unless used within a tamagui button with color prop)

### ISSUE THREAD

**Issue by matthewhausman** [tamagui/tamagui#571]
I have yet to be able to theme icons, you cannot use color tokens with the color or fill props on the icon components. (has no impact). If I wrap the icon in a button and use the button's color prop the icon will be styled accordingly

**Comment by natew** [comment]
Fixed by e0480b6ce88501e13e9e74cdbdae7d1cc9d8bb34
