### ISSUE TITLE
[bug] Site it broken

### ISSUE THREAD

**Issue by foodelix** [tamagui/tamagui#581]
**Describe the bug**
The website https://tamagui.dev does not work, if you navigate to it you get this message

![Screenshot 2023-01-24 at 16 58 18](https://user-images.githubusercontent.com/117474318/214343294-74d5ffed-4660-4e9f-9771-159b6fd2f302.png)

**To Reproduce**
Navigate to https://tamagui.dev

**Comment by natew** [comment]
Wups
