### ISSUE TITLE
[bug] Unable to run native version of starter template

### ISSUE THREAD

**Issue by ugened47** [tamagui/tamagui#585]
Unable to run native version of fresh starter template with `yarn native`, always getting `Unable to resolve "@react-navigation/native" from "../../node_modules/solito/build/middleware/context.js"` both while bundling for Expo Go and during `eas build` process

**To Reproduce**

```
npm create tamagui
yarn native or eas build --profile development
```

**System Info (please complete the following information):** 

Output of `npx envinfo --system --npmPackages --binaries --browsers`
```
  System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 336.48 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.asdf/installs/nodejs/16.16.0/bin/node
    Yarn: 3.3.1 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.05.16.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 108.1.46.140
    Chrome: 109.0.5414.119
    Firefox: 91.0.2
    Safari: 16.2
  npmPackages:
    @expo/metro-config: ^0.3.21 => 0.3.22 
    @types/react-native: ~0.70.6 => 0.70.9 
```

**Comment by natew** [comment]
Fixed earlier today if you just re-run the cli.
