### ISSUE TITLE
[bug] Pass onPress to a component that wraps an extractable component results in double onPress call

### ISSUE THREAD

**Issue by foyarash** [tamagui/tamagui#599]
# Reproduction

The issue can be reproduced here https://github.com/foyarash/tamagui-weather-demo/tree/119d30a238c7c7920ac97947b17f6ce9020cb42a

There is a button "Hello" on the home page, clicking on it results in a double `press` log.

https://github.com/foyarash/tamagui-weather-demo/blob/119d30a238c7c7920ac97947b17f6ce9020cb42a/src/components/Button.tsx#L6 Replacing `Box` by `BoxFrame` at this line will get around the issue.

# Expected result

Calling `onPress` on any component should result on a single `onPress` call upon a single press event

# Note

`onPressIn` and `onPressOut` events are not affected

**Comment by lobor** [comment]
I try on your repo, very strange, can you try by replace @tamagui/core by tamagui package ?
also, if you want use theme with button, you can remove Theme component
```typescript
<ButtonFrame theme="primary_Button" size="$md" {...props}>
```

**Comment by lobor** [comment]
Today i had this bug with not extractable component, is not resolved

**Comment by lobor** [comment]
should be closed when #656 released
