### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by natew** [tamagui/tamagui#605]
The component API should somewhat look like Radix:

https://www.radix-ui.com/docs/primitives/components/toast

- Keyboard shortcuts should work like Radix

Some important differences:

- There should be an imperative helper to show/hide:

```tsx
import { createToast } from '@tamagui/toast'

const { toast, useToasts } = createToast({
  native: true,
  // can set some default values:
  timeout: 10,
})

toast.show({ title: ``, message: ``, icon: ``, type: ``, timeout: 2 })
toast.hide()
toast.hide(1)
toast.hide('all')
```

Note the `native` property:

- Can be set to true/false, or `['web', 'ios']` or `['native']` for example. If set like this it will try and use the platform-native toasts.
- For web this is an actual notification

---

For the `useToast`:

```tsx
const toasts = useToasts() // returns most recent on top

const elements = toasts.map(toast => {
   return (
     <Toast>
        <Toast.Title>{toast.title}</Toast.Title>
        <Toast.Description>{toast.description}</Toast.Description>
     </Toast>
   )
})

return (
  <Toast.Viewport anchor="top-center">
    {elements}
  </Toast.ViewPort>
)
```

---

Docs:

The end user should be able to use enterStyle/exitStyle and <AnimatePresence> to do animate things so showing in docs would be great.

---

Requirements:

- No using Radix libraries, Tamagui has equivalent libraries for most.
- Animations need to work across all the animation drivers.
- Add docs page to the site.
- Simple tests would be appreciated.

**Comment by Tolu-Mals** [comment]
I'd like to work on this

**Comment by natew** [comment]
@Tolu-Mals please go for it. Note also we want to use `burnt` https://github.com/nandorojo/burnt as an option, which would only enable if you set `native` true as well I think. Want to be sure though we don't force native dep install for Tamagui proper so it may need some fancy file structure or something for that...

@nandorojo ideas?

Also just realized my toasts in Burnt were the fullscreen variety not the nice top bubble one... 🤔

**Comment by nandorojo** [comment]
you can conditionally `require()` for burnt to avoid importing native dependencies i believe

**Comment by nandorojo** [comment]
you might be using `burnt.alert` instead of toast?

**Comment by alitnk** [comment]
@Tolu-Mals are you working on this one? I couldn't find a PR.

If not, I'd like to take this one.

**Comment by Tolu-Mals** [comment]
Go ahead @alitnk

**Comment by BANG88** [comment]
Please consider adding a callback or something that we know after the toast hid.

Thank  you very much.

**Comment by alitnk** [comment]
> Please consider adding a callback or something that we know after the toast hid.

You should be able to do that with the current API

**Comment by alitnk** [comment]
Closed in favor of #810

**Comment by alitnk** [comment]
Closed by #810

**Comment by BANG88** [comment]
> 

@alitnk Which api we can use for this  use case? Thank you.

**Comment by alitnk** [comment]
> > Please consider adding a callback or something that we know after the toast hid.
> 
> @alitnk Which api we can use for this use case? Thank you.

@BANG88 Have you tried the `onOpenChange` prop on `<Toast>`?

**Comment by BANG88** [comment]
Just  look at it . but I want handle it on special toast.eg toast.show('Hello',{})

**Comment by BANG88** [comment]
`toast.show('Hello',{
onClose: () => {
// do sth...
}
})`

**Comment by alitnk** [comment]
> `toast.show('Hello',{ onClose: () => { // do sth... } })`

I don't think if we can have a callback there considering `useToastController` it's used to handle native toasts as well. You can still pass `onOpenChange` if you're using custom toasts though.

**Comment by BANG88** [comment]
> > `toast.show('Hello',{ onClose: () => { // do sth... } })`
> 
> I don't think if we can have a callback there considering `useToastController` it's used to handle native toasts as well. You can still pass `onOpenChange` if you're using custom toasts though.

Ok  I will try it later.
