### ISSUE TITLE
UL and LI

### ISSUE THREAD

**Issue by natew** [tamagui/tamagui#606]
This is simple: on the web it should render to a native UL / LI, whereas on Native we need to make that look very similar.

**Comment by benschac** [comment]
I'd like to work on this

**Comment by mphill** [comment]
Seems like potentially there is overlap with ListItems.

Could you reuse https://tamagui.dev/docs/components/list-item/1.0.0 and add some new style props perhaps?

i.e. 

`listStyle : 'ordered' | 'unordered' | 'styled' `


Maybe a bad idea, just throwing it out there.

**Comment by natew** [comment]
@mphill it's not a bad idea...

**Comment by tlmader** [comment]
When using the ListItem component, I am currently getting the recommendation from Lighthouse:

> List items (<li>) are not contained within <ul>, <ol> or <menu> parent elements.

It would be helpful if Tamagui supplied a declarative way to wrap ListItems in list elements in cross-platform code.
