### ISSUE TITLE
ToggleGroup

### ISSUE THREAD

**Issue by natew** [tamagui/tamagui#607]
Almost identical to Radix:

https://www.radix-ui.com/docs/primitives/components/toggle-group

But instead of `<ToggleGroup.Root>` it should be `<ToggleGroup>`.

Requirements:

- No using Radix libraries, Tamagui has equivalent libraries for most.
- Add docs page to the site.
- Simple tests would be appreciated.

**Comment by glocore** [comment]
I'd like to work on this one!

**Comment by natew** [comment]
@glocore sounds good, open a draft PR that references this and we can consider it yours.

**Comment by natew** [comment]
With some initial real progress

**Comment by azeez1776** [comment]
Hey @natew can I work on this.

**Comment by natew** [comment]
@azeez1776 go for it I’ll reserve for you for next 48 hours. So long as you show decent progress within then it will be yours.

**Comment by azeez1776** [comment]
Thanks @natew , got it
