### ISSUE TITLE
RadioGroup

### ISSUE THREAD

**Issue by natew** [tamagui/tamagui#608]
Almost identical to Radix:

https://www.radix-ui.com/docs/primitives/components/radio-group

But: Instead of `<RadioGroup.Root>` it's just `<RadioGroup>`.

NOTE: This and ToggleGroup likely share the same underlying logic.

There's should be a `native` prop on the Indicator that would render to an actual `radio` on the web, on Native eventually it can render to something like the iOS style list of items with check marks but that can be later on.

Requirements:

- No using Radix libraries, Tamagui has equivalent libraries for most.
- Add docs page to the site.
- Simple tests would be appreciated.

**Comment by foyarash** [comment]
i'd like to work on this
