### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by natew** [tamagui/tamagui#609]
Almost identical to Radix:

https://www.radix-ui.com/docs/primitives/components/toggle-group

- But instead of <Checkbox.Root> it should be <Checkbox>.
- There should be a `native` prop on the root that on the web will just output to a plain old web checkbox.

Requirements:

- No using Radix libraries, Tamagui has equivalent libraries for most.
- Add docs page to the site.
- Simple tests would be appreciated.

**Comment by natew** [comment]
Assigned to @alitnk

**Comment by mphill** [comment]
I believe the link in this task is incorrect, should be: https://www.radix-ui.com/docs/primitives/components/checkbox
