### ISSUE TITLE
Expo app build fails

### ISSUE THREAD

**Issue by ivopr** [tamagui/tamagui#61]
**Describe the bug**
When creating a new tamagui app with `yarn create tamagui-app` expo eas build for android fails.

**To Reproduce**
Create a new app with `yarn create tamagui-app`, setup eas, expo-dev-client and build.
There's the logs on my builds.
https://expo.dev/accounts/ivopr/projects/vermeil/builds/cf02a075-242d-42a4-b09c-594fb3158c4b

This ceases to happen if I go to expo folder and `expo install expo-linear-gradient` here.

**Environment (please complete the following information):**
 - OS: Android
 - Browser .
 - Version All (?)

**Comment by natew** [comment]
Interesting, I had that set up before and removed it because it was causing some issue. I'll try adding again.

**Comment by natew** [comment]
Should be fixed in https://github.com/tamagui/starters/commit/4373a58b9618ebcf3b770991742d45bbdca035ff
