### ISSUE TITLE
[Feature] Add native prop to Switch

### ISSUE THREAD

**Issue by natew** [tamagui/tamagui#613]
On iOS and Android they have native Switch elements. We can add:

```tsx
<Switch native>{/* ... *}</Switch>
```

Where on native apps it will render to the React Native Switch. Should be done inside Switch.native.tsx to avoid bundle size on web.

**Comment by 54m1r** [comment]
Hey, can i work on this one?

**Comment by natew** [comment]
@54m1r if you can get a draft PR up soon with some decent start yes!
