### ISSUE TITLE
[bug] <Select /> scroll issue

### ISSUE THREAD

**Issue by alitnk** [tamagui/tamagui#617]
It's a bug in the select component example in the Tamagui docs - the scroll chevron goes up if you try hovering it from bottom. 

**Describe the bug**

https://user-images.githubusercontent.com/35243344/215306303-03572cc2-9e0e-4004-9968-6e1995fa7a02.mp4

Video recorded from Chrome.

**Comment by lobor** [comment]
fix on 1.3.0
