### ISSUE TITLE
[bug] Vite SSR Can't Resolve ESM

### ISSUE THREAD

**Issue by tazsingh** [tamagui/tamagui#619]
Hey Nate,

Thanks for the other Vite fixes in #479! It's now gotten me past those errors and onto this one.

I've managed to widdle it down to the following repo, where you can see the patch that worked for me for that 1st error and onto the next with essentially the same pattern: https://github.com/tazsingh/tamagui-ssr-vite

Note, the patch doesn't include changing this line:

https://github.com/tamagui/tamagui/blob/master/packages/normalize-css-color/package.json#L31

to: `"import": "./dist/esm/index.mjs",`

Essentially, I believe that Vite CLI is a bit more forgiving than Node's module resolution. Annoyingly, Node seems to want everything to be `.mjs` files for ESM, while Vite doesn't seem to mind as much. Since I'm trying to load the project via Vite for SSR, it's hitting Node's module resolution which is constantly tripping over the `.js` files not being `.mjs` files.

Additionally, it's odd to me that `"type": "module"` doesn't seem to matter much here, and separately removing the `"exports"` map entirely from `package.json` is also a fix 🤷 Thought I'd mention it in case you're debugging. The patch above is what I've discovered to be the path-of-least-resistance to change all ESM output to use `.mjs` files. Hope that helps 🙏 

**To Reproduce**

Check out my repo

`yarn install`

`yarn dev:ssr`

Notice the next bug, that isn't fixed by the patch above. Feel free to remove the patch to see the issue it's patching over.

**Comment by natew** [comment]
Woof, change to mjs is almost not doable for the hassle. All the module stuff has been a pain to get it working backwards compat.

**Comment by tazsingh** [comment]
This is only for the ESM build, which has always used `.mjs` and is backwards compatible to Node 14 but goes all the way back to Node 8: https://nodejs.org/docs/latest-v14.x/api/packages.html#packages_determining_module_system

The alternatives which aren't backwards compatible would be changing the `package.json` `"type"`, as that would affect ESM and CJS. However, per my testing above, that doesn't seem to matter anyway

I agree the whole ESM thing is a hassle though! 😅

**Comment by JoviDeCroock** [comment]
Hey Nate,

This is indeed a troublesome issue, we have had many issues with `urql` as well. The gist of it comes down to that plain `node` usage demands `.mjs` for anything that uses `ESM` type import/export. As Taz mentions, there are ways around this by marking your package as `type: 'module'` but then the `cjs` usage requires a `.cjs` extension.

Most bundlers have ways around this but when we go to the pure `node` site there aren't really any good ways around this, for the `react-urql` package [we stopped shipping export-maps entirely](https://www.runpkg.com/?urql@3.0.3/package.json#22) and for the `@urql/core` package we [started using `.mjs`](https://www.runpkg.com/?@urql/core@3.1.1/package.json#25).

The reason for this difference is that we had a few issues with `create-react-app` and how it interacted with the `.mjs` syntax (it didn't want to resolve it)...

**Comment by natew** [comment]
Sounds nightmarish... I've already gone through so many iterations too (leaving out export maps, bringing the back, trying various incantations).

I'm happy to make any change but I'd have to test quite a lot to be sure everything works so want to be sure we get it right.

@tazsingh what was the first patch in that repo? Without the commit log showing can't see easily.

@JoviDeCroock @tazsingh could one of you guys play around and figure out the full set of changes that gets it working and let me know?

**Comment by JoviDeCroock** [comment]
I have put in a suggestion, thanks for being open to this change @natew
