### ISSUE TITLE
Select does not support onBlur

### ISSUE THREAD

**Issue by clayrisser** [tamagui/tamagui#620]
I can seem to find the `onBlur` prop or support for the `<Select />` or `<Select.Trigger />`

**Comment by t1gu1** [comment]
On an `input`, `onBlur` makes sense cause you may not want to trigger an update with a state change each time you write a caracter.

With a `Select`, this is not a problem cause you only select one value.

`onValueChange` do the same job.

Ex: `<Select id="food" value={val} onValueChange={setVal}> ... </...>`
