### ISSUE TITLE
[bug] Document site has an ugly scrollbar in dark mode

### ISSUE THREAD

**Issue by Envov** [tamagui/tamagui#623]
<img width="1529" alt="image" src="https://user-images.githubusercontent.com/48908684/215425183-9fbb7eaf-d27b-42a0-a410-045081f54972.png">
It should be something like github：
<img width="641" alt="image" src="https://user-images.githubusercontent.com/48908684/215425403-3a24e39e-d9ec-4c93-a92e-a871bf2c7e67.png">

**Comment by natew** [comment]
Fixed 1.1.12
