### ISSUE TITLE
[bug] expo-camera breaks next app

### ISSUE THREAD

**Issue by patcito** [tamagui/tamagui#638]
How to reproduce:
- yarn add expo-camera
- import {Camera} from "expo-camera"
- add "expo-camera" to transpiled modules in next.config.js
- use the` <Camera />` tag in a screen
- refresh screen manually in browser

The error I get is: "SyntaxError: Cannot use import statement outside a module". Navigating to screen works but when refreshing or on first load I get this error.

Note, this works in solito.dev vanilla starter without tamagui.

Here is the repo to reproduce from starter https://github.com/patcito/tamagui-next-expo-camera

**Comment by dohomi** [comment]
@patcito make sure that `expo-camera` is part of transpiled modules in your next.config.js

**Comment by goatbarn** [comment]
I'm having the same issue after adding expo packages to setup my auth provider (expo-auth-session, expo-random, and expo-web-browser). All added to next config, just like OP.

Also, OPs repo DOES have expo-camera listed in transpileModules.. it's listed first...unless I'm crazy (or he edited?).

Is there anyway to further debug this message...other than looking at which library shows up in the stack?

**Comment by patcito** [comment]
@dohomi as noted by @goatbarn, I've already added "expo-camera" to next.config.js here https://github.com/patcito/tamagui-next-expo-camera/blob/main/apps/next/next.config.js#L78

**Comment by dohomi** [comment]
oh sorry I overlooked the first line (I only add new modules to the bottom and not top..). I have similar problems with expo modules like expo-av and expo-document-picker. What helped in my case was using [`transpile-module`](https://github.com/martpie/next-transpile-modules) instead of the built in feature. There is actually a discussion about it in Discord where I mentioned this. Most probably that will fix and can be used as a workaround

**Comment by natew** [comment]
Lets use the discord for things that aren't really tamagui related

**Comment by felicio** [comment]
Repost:

> I was able to make it work by removing tamagui-extras which I wasn't using, I may use it in the future though so would be nice if you find a fix 🙂
> – https://discord.com/channels/909986013848412191/1070796779555147856/1071027668864217088

**Comment by dohomi** [comment]
@felicio open an issue at discord or https://github.com/dohomi/tamagui-kitchen-sink a lot has changed since february

**Comment by felicio** [comment]
> @felicio open an issue at discord or https://github.com/dohomi/tamagui-kitchen-sink a lot has changed since february

@dohomi another issue is already open at https://github.com/tamagui/tamagui/issues/846. I was just providing context to this one should anyone stumble upon it 🙂.
