### ISSUE TITLE
warning: matchMedia implementation is not provided. 

### ISSUE THREAD

**Issue by patrykczubek** [tamagui/tamagui#641]
Hi, I'm not sure why, but I keep getting this on mobile.

![image](https://user-images.githubusercontent.com/67239078/216118497-f553029a-4317-42be-a6d8-633db193e3a3.png)

**Comment by natew** [comment]
The docs were in `useMedia` but should be under configuration, I moved them over to there so in a couple minutes that will show. Sorry about that.

**Comment by ThatGuySam** [comment]
This is still showing up for me for version 1.9.1 while running Expo. 

I just disabled the `media` option on config for now since I'm not targeting that many devices.

**Comment by strewhella** [comment]
Anyone that runs into this too, it's covered in the docs (just hit it myself): https://tamagui.dev/docs/core/configuration#setup-media-query-driver

**Comment by nnennajohn** [comment]
Hi,

I am running into this issue too. I am on expo 49. Followed the guide to setup media. The error still shows.

<img width="647" alt="Screenshot 2023-07-02 at 8 42 15 PM" src="https://github.com/tamagui/tamagui/assets/1761197/7edceb94-0566-4f8b-90f8-d41004bf6a58">
<img width="729" alt="Screenshot 2023-07-02 at 8 42 38 PM" src="https://github.com/tamagui/tamagui/assets/1761197/57839f6e-1555-4890-9483-4fec6ee80f11">
<img width="734" alt="Screenshot 2023-07-02 at 8 43 23 PM" src="https://github.com/tamagui/tamagui/assets/1761197/0687eef4-a1b0-4dd1-96b1-85da18333873">

**Comment by anthonyn60** [comment]
Also still getting this with Expo 49- I have `createMedia` imported from `"@tamagui/react-native-media-driver"`

**Comment by pierroo** [comment]
why is it closed?
This error still appears on latest version, I did the jumb from v1.43.12 to 1.91.3 and now I face it.
I am not even using createMedia or matchMedia or anything like that in my config.

**Comment by mario-deaconescu** [comment]
This is an ongoing issue

**Comment by c0repwn3r** [comment]
This should be reopened. It's still actively happening.

**Comment by natew** [comment]
Can anyone make a repro? We have a ton of apps not running into it, so likely it's a duplicated dependency. Make 10000000% sure you have all the same exact versions of Tamagui.

If not, can you please post the details of your setup? It's impossible to help people who don't even give the barest of details. Expo? Router? Bundler? etc.

**Comment by SergioGCarvalho** [comment]
gonna look silly but i was facing same issue after update to a new version, remove node modules folder, installed again and worked, some times is just what is needed

**Comment by CodyPredy** [comment]
@SergioGCarvalho  Removed node_modules, removed ios folder - npm install, npx expo run:ios - same issue.

**Comment by bradleyayers** [comment]
@CodyPredy are you using the same version for all `@tamagui/*` packages? I had this problem and it was because when I did `yarn add @tamagui/react-native-media-driver` it installed the latest version, instead of the same version as the other `@tamagui/*` packages i have already. Aligning all the versions fixed the issue for me.
