### ISSUE TITLE
[bug] Spacing Not Working Through Wrapping Component Returning Children

### ISSUE THREAD

**Issue by mwood23** [tamagui/tamagui#648]
**Describe the bug**
```tsx
export const ShowWhenAuthed = ({ children }: RequireAuthProps) => {
  const [{ isAuthed, isInitializing }] = useAuth()

  if (isInitializing || isAuthed !== true) return null

  // TS yells when it's just children although that's valid
  return children
}

const Foo = () => {
  return (
    <YStack space="$4">
      <YStack>
        <Text>Hello</Text>
      </YStack>
      <ShowWhenAuthed>
        <YStack>
          <Text>Hello</Text>
        </YStack>
      </ShowWhenAuthed>
      <YStack>
        <Text>Hello</Text>
      </YStack>
    </YStack>
  )
}
```

When I do this, the spacing spans are not added. It's like the wrapping component doesn't factor it in.

**Comment by natew** [comment]
There should be 2 spaces here right?

**Comment by mwood23** [comment]
Yeah, it's really hard to reproduce easily. I have a bunch of little things I could show you live similar to this

**Comment by natew** [comment]
Yea this is a know issue, one of the oldest open issues just because we can't do anything about it. Once gap comes we'll be good. Closing in favor of the old issue for now.
