### ISSUE TITLE
[bug] Types do not include the `$` prefix for `getTokens`

### ISSUE THREAD

**Issue by mwood23** [tamagui/tamagui#660]
**Describe the bug**
In [this release](https://github.com/tamagui/tamagui/releases/tag/v1.2.0) the contract for `getTokens` changed. However the type signature has not changed and expects values that are not prefixed with`$` (aka `getTokens({prefixed: false})`). 

**To Reproduce**

1. Create a new starter project
2. Import `getTokens` from `@my/ui`
3. Add this code:
```js
const tokens = getTokens()

console.log(tokens)
```
4. See that the types are not consistent with the logged output

**Expected**
Return types of `getTokens()` has the `$` prefixed
Return types of `getTokens({prefixed: false})` does not have a `$` prefixed

**Comment by natew** [comment]
It's hard to get the $ on the dollar sign tokens if they are numbered :/, I took a stab on the latest release but not sure it's 100% fixed let me know if so.

**Comment by aawalton** [comment]
We hit the same issue and the 1.2.8 release resolved it for us.
