### ISSUE TITLE
[bug] Cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by dimonnwc3** [tamagui/tamagui#663]
**Describe the bug**
I'm using latest expo with tamgui and receive an error running expo for web.
`Uncaught SyntaxError: Cannot use 'import.meta' outside a module`

it's coming from this line:
`var isRSC = process.env.ENABLE_RSC ? import.meta.env ? import.meta.env.SSR : false : false;`

**To Reproduce**
create fresh expo app and follow tamagui installation instruction from official docs, then run expo with `TAMAGUI_TARGET=web expo start --web`

**System Info (please complete the following information):** 

```
npx envinfo --system --npmPackages --binaries --browsers

  System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 71.08 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.asdf/installs/nodejs/18.13.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.13.0/.npm/bin/yarn
    npm: 9.4.0 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2023.01.30.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.3
  npmPackages:
    @babel/core: ^7.20.12 => 7.20.12
    @babel/plugin-syntax-import-meta: ^7.10.4 => 7.10.4
    @lingui/cli: ^3.17.0 => 3.17.0
    @lingui/macro: ^3.17.0 => 3.17.0
    @lingui/react: ^3.17.0 => 3.17.0
    @react-native-community/eslint-config: ^3.2.0 => 3.2.0
    @tamagui/animations-react-native: ^1.2.5 => 1.2.5
    @tamagui/babel-plugin: ^1.2.5 => 1.2.5
    @tamagui/config-base: ^1.2.5 => 1.2.5
    @tamagui/react-native-media-driver: ^1.2.5 => 1.2.5
    @tamagui/shorthands: ^1.2.5 => 1.2.5
    @tamagui/theme-base: ^1.2.5 => 1.2.5
    @types/react: ~18.0.24 => 18.0.27
    @types/react-native: ~0.70.6 => 0.70.10
    @typescript-eslint/eslint-plugin: ^5.50.0 => 5.50.0
    @typescript-eslint/parser: ^5.50.0 => 5.50.0
    babel-plugin-macros: ^3.1.0 => 3.1.0
    babel-plugin-transform-inline-environment-variables: ^0.4.4 => 0.4.4
    eslint: ^8.33.0 => 8.33.0
    expo: ~47.0.12 => 47.0.13
    expo-constants: ~14.0.2 => 14.0.2
    expo-dev-client: ~2.0.1 => 2.0.1
    expo-linking: ~3.3.0 => 3.3.0
    expo-router: ^1.0.0-rc5 => 1.0.0-rc5
    expo-splash-screen: ~0.17.5 => 0.17.5
    expo-status-bar: ~1.4.2 => 1.4.2
    prettier: ^2.8.3 => 2.8.3
    react: 18.1.0 => 18.1.0
    react-dom: 18.1.0 => 18.1.0
    react-native: 0.70.5 => 0.70.5
    react-native-mmkv: ^2.6.1 => 2.6.1
    react-native-safe-area-context: 4.4.1 => 4.4.1
    react-native-screens: ~3.18.0 => 3.18.2
    react-native-web: ~0.18.9 => 0.18.12
    tamagui: ^1.2.5 => 1.2.5
    typescript: ^4.9.5 => 4.9.5
```

**Comment by natew** [comment]
Haven't seen this yet so seems like a regression on Expo side, can you open there first saying it regressed and when? The syntax is valid and behind a conditional that should fail.

**Comment by JohnKing93** [comment]
I'm getting the same issue. Were you able to resolve this @dimonnwc3?

**Comment by dimonnwc3** [comment]
@JohnKing93 no, I'm not using this library anymore

**Comment by yepes** [comment]
I'm experiencing this exact issue trying out tamagui. Bare expo router template, followed the installation guide. 

process.env.TAMAGUI_TARGET = "native"; (or web) doesn't seem to make a difference (at least while developing).

**Comment by croshim** [comment]
Getting the same issues. Expo 48 + freshly installed tamagui.

**Comment by natew** [comment]
I’ll remove this for now, Jesus Christ es modules are a huge pain to support alongside React Native. 

This is just a warning though right? I saw it yesterday.

**Comment by yepes** [comment]
What do you mean by "remove". In my case, I saw the error in the browser console (chrome). It wasn't a warning.

**Comment by natew** [comment]
The latest version no longer references import.meta at all. There should be no error or warning.

**Comment by natew** [comment]
@yepes what stack? Next or vite?

**Comment by yepes** [comment]
> @yepes what stack? Next or vite?

Bare Expo (plus react native web)

**Comment by yepes** [comment]
I will try to recreate it tomorrow. Will come back with the result
