### ISSUE TITLE
padding start and padding end doesn't work.[bug] 

### ISSUE THREAD

**Issue by sinafath** [tamagui/tamagui#675]
padding start/end doesn't add any style in web (I use next.js in [next-expo-solito](https://github.com/tamagui/tamagui/tree/master/starters/next-expo-solito))
`     <H1 ta="center" paddingStart={150}>
         this is me.
        </H1>`
using padding-start and -end are necessary for rtl (right to left) .  _start_  and _end_ that I use  instead of  right and left also doesn't work even though it has typescript support for it.
`   <H1 pos="relative"   start={150}>
          this is me.
        </H1>`
update: _padding-start and -end_ , _right_ and _left_ both works in react native but not nextjs

**Comment by redbar0n** [comment]
It's probably because the Heading tags like H1 [default](https://tamagui.dev/docs/components/headings/1.0.0#how-it-works) to a `<span>` element on web, and putting a padding on a span doesn't work by default on the web in general.

> span won't have padding because it is an inline element by default, so set inline-block or block. https://stackoverflow.com/a/35592226/380607

**Comment by sinafath** [comment]
> It's probably because the Heading tags like H1 [default](https://tamagui.dev/docs/components/headings/1.0.0#how-it-works) to a `<span>` element on web, and putting a padding on a span doesn't work by default on the web in general.
> 
> > span won't have padding because it is an inline element by default, so set inline-block or block. https://stackoverflow.com/a/35592226/380607

it's not just padding. start and end positioning also doesn't work.
example:
`<H1 pos="relative"   start={150}> Welcome to Sina . this is me. </H1>`

**Comment by sinafath** [comment]
margin start and margin end also doesn't work it seems nextjs doesn't support rtl for web(next.js)

**Comment by natew** [comment]
It should work now, I had a logic error that was just mangling the output style but that was fixed in https://github.com/tamagui/tamagui/commit/54c545fa2bb10714ab2515574b58f3ef2ccf05bc
