### ISSUE TITLE
Circular button icon with size won't be circular

### ISSUE THREAD

**Issue by hoochani** [tamagui/tamagui#685]
Hey. Seems to be an issue with creating a circular icon based button. As soon as you add a size it is no longer circular. 

Good:

`<Button circular icon={myIcon} theme="red" />`

<img width="67" alt="image" src="https://user-images.githubusercontent.com/124574150/217648887-bb6da141-d15f-4def-b127-e6cd952f9b17.png">

Not so good (resorts to a border radius that is no longer "full")

`<Button circular icon={myIcon} theme="red" size="$6" />`

<img width="87" alt="image" src="https://user-images.githubusercontent.com/124574150/217649053-4af4bdbf-6c8e-469a-8045-d0c98214c2ab.png">

Thanks

**Comment by matthewhausman** [comment]
put circular last

**Comment by hoochani** [comment]
OK thanks 👍
