### ISSUE TITLE
[bug] React Native Reanimated Carousel not working with Tamagui

### ISSUE THREAD

**Issue by pgull** [tamagui/tamagui#691]
**Describe the bug**
We're transferring a project of ours from NativeBase to Tamagui. We're using [react-native-reanimated-carousel](https://github.com/dohooo/react-native-reanimated-carousel) on both. One of our components requires a parallax animation, which you can see examples of how to do in their docs.

On react-native and react-native-web, the interpolated values animate correctly. On Tamagui web, the values don't update, so no animation is visible.

**To Reproduce**
I've provided a minimal example that demonstrates this problem. Run both `yarn web` and `yarn native` and you'll see the desired effect on native, but not on web. You can see that here:
https://github.com/latitudegames/tamagui-reanimated-carousel

**Comment by tjapa** [comment]
Hey, any news on this? I don't know if it's the same problem, but here when I interact with the carousel, it disappears.
Did you manage to solve it @pgull?

**Comment by bailout00** [comment]
Did you ever find a solution to this?

**Comment by tjapa** [comment]
> Did you ever find a solution to this?

I was using the wrong version pf react-native-reanimated-carousel. Works with alpha v4.

**Comment by tjapa** [comment]
> Did you ever find a solution to this?

@bailout00  I was using the wrong version pf react-native-reanimated-carousel. Works with alpha v4.

**Comment by alitnk** [comment]
Is this still an issue on the latest tamagui and the `reanimated`/`react-native-reanimated-carousel` version?

**Comment by alitnk** [comment]
Is this still an issue on the latest tamagui and the `reanimated`/`react-native-reanimated-carousel` version?
