### ISSUE TITLE
is there any support for gap?

### ISSUE THREAD

**Issue by sinafath** [tamagui/tamagui#693]
they are so useful for separating elements in flex but it seems Tamagui doesn't support it

**Comment by natew** [comment]
Just released so looking at adding it today, should be a one line change.

**Comment by sinafath** [comment]
thanks

**Comment by natew** [comment]
Check out 1.3.1 and let me know if it works, I am having trouble upgrading my RN app right now in the monorepo but I'll test soon.

**Comment by dohomi** [comment]
gap works awesome good since recent Tamagui upgrade. Coming from React MUI I introduced a small `Grid` component which is basically just a Stack with familiar API:  
https://tamagui-extras.vercel.app/?path=/story/ui-content-grid--grid-row
It works very well with `gap` and eliminates the cumbersome negative margin issue of other grid solutions.

**Comment by dohomi** [comment]
The only issue I found regarding the `gap` prop is following typescript issue:
```ts
 Type 'string' is not assignable to type 'number'.
```
This only happens if the library is used with the optimising compiler

**Comment by natew** [comment]
I can't replicate this, it accepts the right types (SpaceToken) for me.

**Comment by timoisalive** [comment]
I'm also seeing the type error @dohomi mentioned about:
```
Type 'string' is not assignable to type 'number'.ts(2322)
StyleSheetTypes.d.ts(56, 3): The expected type comes from property 'gap' which is declared here on type 'IntrinsicAttributes & Omit<ViewProps, "display" | "children" | "onLayout" | keyof GestureResponderHandlers> & ... 7 more ... & RefAttributes<...>'
```
I just updated Tamagui into 1.7.7.

**Comment by dohomi** [comment]
@natew I especially experience this issue when I use `tamagui-extras` in my app as a dependency. There all `gap` properties only expects numbers and not the `SpaceToken`.

Am I doing anything wrong inside of https://github.com/dohomi/tamagui-kitchen-sink/blob/master/packages/ui/src/components/content/LmGrid.tsx ?
