### ISSUE TITLE
[bug] @tamagui/config default config regressed in v1.5.0

### ISSUE THREAD

**Issue by matthewhausman** [tamagui/tamagui#703]
const theme = useTheme()

theme.red <--- does not exist / throws ts error

theme.gray6  <--- does not exist / throws ts error

**Comment by matthewhausman** [comment]
reprod:

https://github.com/matthewhausman/tamagui-default-config-regression

 clone and look at /packages/app/features/home/screen.tsx

**Comment by natew** [comment]
Just tested this out myself using the latest starter and I see them coming through, can you verify again sorry.

**Comment by matthewhausman** [comment]
@natew No worries at all - I'm specifically talking about replacing @tamagui/config-base with @tamagui/config in my project's tamagui.config.js file in the ui directory

I just did a fresh install of the starter and even with the starter's tamagui.config.ts I'm unable to access theme.red for example

**Comment by matthewhausman** [comment]
Uploading Screen Recording 2023-02-14 at 8.50.26 AM.mov…

**Comment by matthewhausman** [comment]
https://user-images.githubusercontent.com/25216513/218759500-44e37045-1554-4b1c-b26b-bae15ebbd918.mov

**Comment by matthewhausman** [comment]
in The above repo I sent - you will definitely not be able to access theme.red from the useTheme hook return val, but replacing @tamagui/config with the deprecated @tamagui/config-base will fix that issue

**Comment by natew** [comment]
Figured it out! Sorry about that, fix going out.

**Comment by matthewhausman** [comment]
Thank you! No worries :)

**Comment by natew** [comment]
Check out 1.5.6 lmk if working

**Comment by matthewhausman** [comment]
Looking good
