### ISSUE TITLE
Checkbox border is transparent which results in low contrast ratio

### ISSUE THREAD

**Issue by dohomi** [tamagui/tamagui#708]
I had a look why the border colors are missing in the recent release and it seems the default style is transparent:

https://github.com/tamagui/tamagui/blob/8afaece0ce78823e20fbc348d43ed51c6e4d08f5/packages/checkbox/src/Checkbox.tsx#L190

I rather think `$borderColor` would make it more distinct?

**Comment by dohomi** [comment]
I think the Checkbox is missing a theme fallback color - as soon 
```ts
<Checkbox theme="gray" /> is set the checkbox looks ok
```

**Comment by natew** [comment]
Fixed in 1.5.8
