### ISSUE TITLE
[bug] Can't load stylesheets in Vite SSR

### ISSUE THREAD

**Issue by tazsingh** [tamagui/tamagui#711]
Hey hey,

Apologies for yet another Vite SSR issue 😅 But I thought I'd document what I'm seeing at the very least!

I've updated my Tamagui Vite SSR repo to use the latest dependencies: https://github.com/tazsingh/tamagui-ssr-vite

If you run `yarn dev` with JavaScript turned off in Dev Tools, you'll note that the stylesheets do not load

With JavaScript turned on, there is flash-of-unstyled-content (FOUC) while the JS loads to then load the styles

I believe this isn't an issue with Next, by looking at the Tamagui site itself? Would you be able to point me in the right direction on how to resolve FOUC and/or get the stylesheets to load in Vite on SSR?

I've tried including `<link rel="stylesheet" src="/src/App.tsx.tamagui.css">` in the `index.html` file, but that only seemed to load a few resets

Note: For some reason, I need to include the `ssr` config explicitly in my `vite.config.ts` as it's not being recognized from Tamagui's Vite Plugin. Not sure what's going on there, and if that's contributing to this as well 🤔 

Thanks and let me know how I can help debug this!

**Comment by natew** [comment]
There's some code around `@tamagui/core/inject-styles` that I remember putting together for Vite. If you search the monorepo may help. Not sure 100% if that's related though! I'll keep this in mind next time I check on Vite.

**Comment by redbar0n** [comment]
Maybe the recently released client-hints could help:

https://github.com/epicweb-dev/client-hints - «Eliminate a flash of incorrect content by using client hints»

https://x.com/kentcdodds/status/1727455239161475273?s=46&t=tYj6dxrnDA8GvBz3qad13A

**Comment by natew** [comment]
Should be working now or at least it does in a few vite ssr things i'm testing! Lmk if not, cleaning up backlog
