### ISSUE TITLE
[bug] colorScale incorrect mapping to index

### ISSUE THREAD

**Issue by vpctorr** [tamagui/tamagui#717]
`colorScale` from `@tamagui/themes/src/themes.tsx` is defined as follows:

const colorScale = {
  color1: 1,
  color2: 2,
  color3: 3,
  …
}

Whereas it should probably look like this instead:

const colorScale = {
  color1: 0,
  color2: 1,
  color3: 2,
  …
}

This results in a mismatch between $colorX and $themeX

For instance, `config.themes.light_blue.color9.val` returns `hsl(208, 100%, 47.3%)` (=blue10) instead of `hsl(206, 100%, 50.0%)` (=blue9, as defined in `@tamagui/colors/src/light/blue.ts`)

Looking at `createThemes` from v1.4.0 seems to confirm this: https://github.com/tamagui/tamagui/blob/v1.4.0/packages/create-themes/src/createThemes.ts#L268

I haven't tested whether this could also apply to other variables in themes.

On latest version (v1.5.15)

**Comment by natew** [comment]
We add a transparent color to the beginning of the palette's, so the 1 makes intuitive sense to me, but I do believe you that it's off. I'll look around thanks for the heads up.

**Comment by natew** [comment]
Ah yea so it does skip a value in the middle now. I had to replace the last value with something darker/lighter to match how we use color palettes so dropped one from the middle.
