### ISSUE TITLE
[bug] styled focusStyle order is not working correctly

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#725]
**Describe the bug**
When you try to override focusStyle for the Input component you will end up with the wrong order and the original style has higher priority.

**To Reproduce**

```tsx
import {
  Input,
  styled,
} from 'tamagui';

const StyledInput = styled(Input, {
  focusStyle: {
    borderWidth: 10,
  },
});

Input has borderWidth = 2

** Expected **

Input will have borderWidth = 10

<StyledInput />
```

Tamagui: 1.5.15

**Comment by seeden** [comment]
It is not working without styled as well.

```tsx

import {
  Input,
} from 'tamagui';

<Input focusStyle={{ borderWidth: 10 }} />
```

**Comment by natew** [comment]
Due to recent fixes in making HOCs more correct, but this is a regression. Turned out to be subtle too, ordering of some className output. I have a partial fix I'm testing but this area is due for some cleanup and should save some bundle size and reduce weirdness.

**Comment by seeden** [comment]
Hi @natew, I tried the latest version 1.5.19 but it is not working.

**Comment by natew** [comment]
Really, can you clone the starter and commit it, then make a repro and add that as a new commit?

**Comment by seeden** [comment]
Sorry for not getting back to you sooner, I was sick few days. 
It is weird, everything is working fine with your starter, but my version is buggy.
I will probably spend some time searching.

**Comment by seeden** [comment]
@natew I created minimal repo with reproduction
https://github.com/seeden/tamagui-focus-order-issue

I really have no idea what is wrong. Maybe it is somehow related to webpack and tamagui-loader.
It was working fine around version 1.2.x and suddenly stopped to work after upgrade.

**Comment by seeden** [comment]
During today's work, I realized that it is somehow related to other components as well. When I used just Input component everything looks good. When I am using a more complex website it will break up.

**Comment by nandorojo** [comment]
I created a reproduction of a similar issue at https://github.com/tamagui/tamagui/issues/763#issuecomment-1462243151

This reproduction shows that focusStyle correctness is having issues with the input

**Comment by natew** [comment]
Let me know if still an issue!

**Comment by tjapa** [comment]
Same bug for me. The focusStyle is not being applied.

`
import { GetProps, Input as TamaguiInput, styled } from 'tamagui'
import { config } from '../tamagui.config'

const { tokens } = config

export const Input = styled(TamaguiInput, {
  backgroundColor: tokens.color.background700,
  borderColor: tokens.color.grayAlpha20p,
  color: tokens.color.gray100,
  focusStyle: {
    borderColor: tokens.color.primary700,
    borderWidth: '$2',
  },
})

export type InputProps = GetProps<typeof Input>
`

"tamagui": "^1.9.18"
