### ISSUE TITLE
[bug] Some packages depend directly on react 18.2.0

### ISSUE THREAD

**Issue by nderscore** [tamagui/tamagui#729]
The following packages depend directly on react 18.2.0:

* `@tamagui/react-native-use-pressable` -> https://github.com/tamagui/tamagui/blob/da626cae0dd1a8d733a426bb8d02029a5e406bc8/packages/react-native-use-pressable/package.json#L21
* `@tamagui/get-font-sized` -> https://github.com/tamagui/tamagui/blob/da626cae0dd1a8d733a426bb8d02029a5e406bc8/packages/get-font-sized/package.json#L22
* `@tamagui/react-native-use-responder-events` -> https://github.com/tamagui/tamagui/blob/da626cae0dd1a8d733a426bb8d02029a5e406bc8/packages/react-native-use-responder-events/package.json#L21

If a consumer app is using React 18.1.0 (such as if they're using Expo 47), this can cause multiple copies of react to be included in a project, which often results in errors or unexpected behavior.

This should be added to peer dependencies (with either a semver range or `*`) and the dependency of react 18.2.0 should be moved to `devDependencies`:

```diff
  "dependencies": {
-    "react": "^18.2.0"
  },
  "peerDependencies": {
+    "react": "*"
  },
  "devDependencies": {
+    "react": "^18.2.0"
  }
```

**Comment by natew** [comment]
Will be fixed when this lands 0761f4dacd175088d2d7eb16831f34d8f9ef2483

**Comment by natew** [comment]
Publishing now

**Comment by natew** [comment]
Thanks for all the help here, maybe we can land some automated lints around this stuff if there are any good solutions.
