### ISSUE TITLE
styles not getting applied for hover state

### ISSUE THREAD

**Issue by sunel-pyt** [tamagui/tamagui#74]
**Describe the bug**
```jsx
<Button theme="dark" hoverStyle={{ backgroundColor: '$green04' }}>Plain</Button>
```
adding  hover style to the button is not getting applied only below if getting applied

```css
background-color: var(--backgroundHover) !important;
```

**To Reproduce**
add custom color and add it to the hover style

**Environment (please complete the following information):**
 - OS: Mac
 - Browser chrome
 - Version latest

**Comment by natew** [comment]
Thanks, good catch this reverted two weeks ago in the big atomic CSS upgrade. Fixed in beta 46 (622a9a2c426c5cc810766e1891c276c97849998d).
