### ISSUE TITLE
[bug] Expo - Error: No parent manager given

### ISSUE THREAD

**Issue by georgibakken** [tamagui/tamagui#742]
**Describe the bug**
Following the new [Expo guide](https://tamagui.dev/docs/guides/expo) for setting up tamagui with Expo 48 and the latest tamagui (1.5.22), I get the following error when running `expo start -c`:

```shell
Error: No parent manager given

This error is located at:
    in _Theme (created by App)
    in PortalProviderComponent
    in _Theme (created by _ThemeProvider)
    in _ThemeProvider (created by _TamaguiProvider)
    in _TamaguiProvider
    in Unknown (created by App)
    in ActiveTripProvider (created by App)
    in QueryClientProvider (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:102:17 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:148:19 in handleException
at node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:52:19 in showErrorDialog
at src/hooks/useCachedResources.ts:25:26 in loadResourcesAndDataAsync
at /private/var/folders/qp/ympy822d7j97b4q14r7lx30w0000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:15 in tryCallOne
at /private/var/folders/qp/ympy822d7j97b4q14r7lx30w0000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:26 in anonymous
- ... 7 more stack frames from framework internals

[Unhandled promise rejection: Error: No parent manager given]
at node_modules/@tamagui/web/dist/cjs/helpers/ThemeManager.js:46:23 in constructor
at node_modules/@tamagui/web/dist/cjs/hooks/useTheme.js:195:50 in createState
at node_modules/react/cjs/react.development.js:1622:28 in useState
at node_modules/@tamagui/web/dist/cjs/hooks/useTheme.js:155:63 in useChangeThemeEffect
at node_modules/@tamagui/web/dist/cjs/views/Theme.js:36:61 in Theme
at src/hooks/useCachedResources.ts:25:26 in loadResourcesAndDataAsync
at /private/var/folders/qp/ympy822d7j97b4q14r7lx30w0000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:15 in tryCallOne
at /private/var/folders/qp/ympy822d7j97b4q14r7lx30w0000gn/T/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:26 in anonymous
- ... 7 more stack frames from framework internals
```

**To Reproduce**

Make your changes and then push and link it here. 🙏🙏🙏🙏🙏

**System Info (please complete the following information):** 
```
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 79.97 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    Watchman: 2023.02.06.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 109.0.1
    Safari: 16.2
  npmPackages:
    @babel/core: ^7.12.9 => 7.20.12
    @expo/vector-icons: ^13.0.0 => 13.0.0
    @react-native-community/cli-debugger-ui: ^10.0.0 => 10.0.0
    @react-navigation/bottom-tabs: ^6.0.5 => 6.5.4
    @react-navigation/native: ^6.0.2 => 6.1.3
    @react-navigation/native-stack: ^6.1.0 => 6.9.9
    @tamagui/animations-react-native: ^1.5.22 => 1.5.22
    @tamagui/animations-reanimated: ^1.2.14 => 1.2.14
    @tamagui/babel-plugin: ^1.5.22 => 1.5.22
    @tamagui/config: ^1.5.22 => 1.5.22
    @tamagui/font-inter: ^1.5.22 => 1.5.22
    @tamagui/lucide-icons: ^1.2.14 => 1.2.14
    @tamagui/shorthands: ^1.2.14 => 1.2.14
    @tamagui/theme-base: ^1.5.21 => 1.5.21
    @tanstack/react-query: ^4.24.6 => 4.24.6
    @tanstack/react-query-devtools: ^4.24.6 => 4.24.6
    @types/react: ~18.0.24 => 18.0.27
    @types/react-native: ~0.70.6 => 0.70.10
    babel-plugin-inline-dotenv: ^1.7.0 => 1.7.0
    babel-plugin-transform-inline-environment-variables: ^0.4.4 => 0.4.4
    cross-env: ^7.0.3 => 7.0.3
    dotenv: ^16.0.3 => 16.0.3
    expo: ^48.0.0 => 48.0.4
    expo-asset: ~8.9.0 => 8.9.0
    expo-constants: ~14.2.1 => 14.2.1
    expo-dev-client: ~2.1.3 => 2.1.3
    expo-font: ^11.1.1 => 11.1.1
    expo-linear-gradient: ~12.1.1 => 12.1.1
    expo-linking: ~4.0.1 => 4.0.1
    expo-splash-screen: ~0.18.1 => 0.18.1
    expo-status-bar: ~1.4.4 => 1.4.4
    expo-system-ui: ~2.2.1 => 2.2.1
    expo-web-browser: ~12.1.1 => 12.1.1
    jest: ^29.2.1 => 29.4.3
    jest-expo: ~47.0.1 => 47.0.1
    react: 18.2.0 => 18.2.0
    react-dom: ^18.2.0 => 18.2.0
    react-native: 0.71.3 => 0.71.3
    react-native-quick-base64: ^2.0.5 => 2.0.5
    react-native-reanimated: ^2.14.4 => 2.14.4
    react-native-safe-area-context: 4.5.0 => 4.5.0
    react-native-screens: ~3.20.0 => 3.20.0
    react-native-svg: 13.4.0 => 13.4.0
    react-native-web: ^0.18.12 => 0.18.12
    react-test-renderer: 18.1.0 => 18.1.0
    tamagui: ^1.5.22 => 1.5.22
    typescript: ^4.6.3 => 4.9.5
```

- [x] yarn.lock or similar
- [ ] If it's a specific file, add `//! debug` to the top (the `!` works in esbuild compiled packages but not necessary always) and include that (only for compiler, but helps to know if it's on or off).
- [x] Run your server/bundler with `DEBUG=tamagui` and include that output at the bottom.

**Comment by foyarash** [comment]
I have the same error

A temporary workaround for me is to downgrade all packages in 1.5.21.

Additionally, i had to add a resolutions field for `@tamagui/web` and set it to 1.5.21

**Comment by MarioMonir** [comment]
I got the same error and found that it's happens when a react native Stack / Tab  Navigator are inside the Tamagui provider , when i don't use a react native navigator it works fine

**Comment by skdrew** [comment]
Hi @MarioMonir, can you give a bit more detail please? Which file(s) need to be changed?

**Comment by MarioMonir** [comment]
> Hi @MarioMonir, can you give a bit more detail please? Which file(s) need to be changed?

i was importing the Linear gradient from tamagui itself like the following 
import {  LinearGradient} from 'tamagui' 

in the new versions the LinearGradient import moved to be as the one of the following according to the documentation 
import { LinearGradient } from '@tamagui/linear-gradient'
import { LinearGradient } from 'tamagui/linear-gradient'

https://tamagui.dev/docs/components/linear-gradient/1.0.0

**Comment by MarioMonir** [comment]
> Ah I see, thanks - unfortunately, I'm not importing LinearGradient and I'm still getting this issue :(

okay i was wrong i found the problem because of a having an XStack not inside a parent Stack 

changed 
```
 <XStack>
      <Text col="red">asd</Text>
  </XStack>
```
    
    to 
    
```
   <Stack>
      <XStack>
        <Text color="red" fontSize={'$10'}>
          Profile
        </Text>
      </XStack>
   </Stack>
```

**Comment by MarioMonir** [comment]
i think it's a Zstack issue  and  no parent Stack for XStack

**Comment by sallar** [comment]
Im having the same issue

**Comment by skdrew** [comment]
v1.5.23 appears to have fixed this

**Comment by natew** [comment]
Yes 1.5.23 fixes (or 1.6.0 that is out now), very sorry about that everyone.

**Comment by mattmarcello** [comment]
I have noticed a similar error on 1.8 when importing icons.  This is true for both @tamagui/feather-icons and @tamagui/lucide-icons.

**Comment by natew** [comment]
It’s almost always a version mismatch issue. Triple check your Tamagui deps all line up. I’ll check this out later.

**Comment by mattmarcello** [comment]
Okay.  So it turns out that lucide-icons was at version 1.8.4, whereas everything else was at 1.8.1.  Reverting it to 1.8.1 solved the issue.  

This does strike me as a bit of a pain point though.  Do you have a recommended solution for maintaining the same package version across all tamagui packages?  ( This is not a complaint btw, thanks for much for the work you are doing ).

**Comment by natew** [comment]
See tamagui:upgrade command in the starter repo, it’s the best I’ve got for now. I’m working on a Tamagui cli that will do this and also help you with a “doctor” command to ensure everything looks right.

**Comment by mattmarcello** [comment]
Ahh cool.  Is that repo public yet?   

Thanks again.

**Comment by natew** [comment]
The cli package in this repo has the code but the upgrade command isn’t there. I could whip that up somewhat quickly once I get a past a few critical bugs

**Comment by natew** [comment]
@Enfield-Li it's very likely you have a version mis-match in one of tamagui deps. That's almost always the issue. I added a nicer warning message about this in this area.

If you can make a repro happy to help. The starter is working today as a nice example.

**Comment by pencilcheck** [comment]
Still failing because of the issue @mattmarcello pointed out about the media key importance error from the icons

**Comment by natew** [comment]
Yes yarn is much better supported in React Native and honestly it has all the same features and speed of pnpm. No reason not to use it. 

Every time I’ve tried to use pnpm with a RN project it’s ended in bad times. Highly recommend against it.

**Comment by pencilcheck** [comment]
> Yes yarn is much better supported in React Native and honestly it has all the same features and speed of pnpm. No reason not to use it.
> 
> Every time I’ve tried to use pnpm with a RN project it’s ended in bad times. Highly recommend against it.

haha, it is just that some starters uses them so I thought it might easier if it is setup that way but yea yarn is definitely better supported for RN

**Comment by zingerj** [comment]
Any update on this for pnpm? I also used the [create-t3-turbo](https://github.com/t3-oss/create-t3-turbo/) starter and it would be kind of a pain to convert everything to yarn. Any chance pnpm can work here?

**Comment by pfcodes** [comment]
This issue still happens when using storybook for some reason

**Comment by robertherber** [comment]
@pfcodes I can second that it happens with Storybook (web not native). Running Expo 49 here (with pnpm which now seems to work well in general).

**Comment by warum7** [comment]
I ran into the exact same issue. In my case it was not a dependency issue it was simply me forgetting to add the TamaguiProvider to Expo.

**Comment by Saurabh7120** [comment]
@warum7 So your react native storybook works with tamagui? Coz I am having the same exact problem

**Comment by warum7** [comment]
@Saurabh7120 Sorry for the confusion. I had the issue w/o Storybook. What you could try is add the Provider to your Story in Storybook maybe it helps.

**Comment by wael-fadlallah** [comment]
Still, I'm getting this error in 1.57.1. Here is my dependencies

```
 "dependencies": {
    "@swc/helpers": "~0.5.0",
    "@tamagui/babel-plugin": "^1.57.1",
    "@tamagui/shorthands": "^1.57.1",
    "@tamagui/themes": "^1.57.1",
    "babel-plugin-transform-inline-environment-variables": "^0.4.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.3",
    "react-native-config": "^1.5.1",
    "react-native-maps": "^1.7.1",
    "react-native-paper": "^5.10.0",
    "react-native-safe-area-context": "^4.7.1",
    "react-router-dom": "6.11.2",
    "tamagui": "^1.57.1",
    "tslib": "^2.3.0"
  },
```

I'm using `NX`

**Comment by christian-valadez** [comment]
Hey there, I'm running into this issue as well on 1.61.3. I made sure all the tamagui deps are this version: 

```
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-navigation/native": "^6.0.2",
    "@supabase/auth-helpers-react": "^0.4.2",
    "@supabase/supabase-js": "^2.33.1",
    "@tamagui/animations-react-native": "1.61.3",
    "@tamagui/babel-plugin": "1.61.3",
    "@tamagui/config": "1.61.3",
    "@tamagui/font-inter": "1.61.3",
    "@tamagui/theme-base": "1.61.3",
    "@tanstack/react-query": "^4.35.0",
    "@trpc/client": "^10.38.1",
    "@trpc/react-query": "^10.38.1",
    "babel-plugin-transform-inline-environment-variables": "^0.4.4",
    "expo": "~49.0.8",
    "expo-crypto": "^12.4.1",
    "expo-font": "^11.4.0",
    "expo-image": "^1.3.2",
    "expo-linking": "~5.0.2",
    "expo-router": "2.0.0",
    "expo-secure-store": "^12.3.1",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-system-ui": "~2.4.0",
    "expo-web-browser": "~12.3.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.4",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-url-polyfill": "^2.0.0",
    "react-native-web": "0.19.8",
    "superjson": "^1.13.1",
    "tamagui": "1.61.3"
  },
  "devDependencies": {
    "@acme/api": "*",
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "jest": "^29.2.1",
    "jest-expo": "~49.0.0",
    "react-test-renderer": "18.2.0",
    "typescript": "^5.1.3"
  },
  ```
