### ISSUE TITLE
[bug] `borderColorHover` is not being applied on Button

### ISSUE THREAD

**Issue by la55u** [tamagui/tamagui#745]
**Describe the bug**
The `borderColorHover` is not being applied on a custom Button despite being set in the theme. The expected behavior is that the border of the button should be red on hover but in the demo it is set to `rgba(0, 0, 0, 0) !important;`

**To Reproduce**

Minimal example (see the commit history):
https://github.com/la55u/tamagui-bordercolor-repro
1. clone the repo
2. run `yarn web` 

**System Info (please complete the following information):** 

```
  System:
    OS: Linux 6.1 Fedora Linux 37 (Workstation Edition)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 21.14 GB / 31.05 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.3.1 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 111.0b6
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.20.13 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    eslint: ^8.21.0 => 8.32.0 
    prettier: ^2.7.1 => 2.8.3 
    turbo: ^1.4.2 => 1.7.0 
    typescript: ^4.7.4 => 4.9.4 

```
---

- [ ] yarn.lock or similar
- [ ] If it's a specific file, add `//! debug` to the top (the `!` works in esbuild compiled packages but not necessary always) and include that (only for compiler, but helps to know if it's on or off).
- [ ] Run your server/bundler with `DEBUG=tamagui` and include that output at the bottom.

**Comment by natew** [comment]
`bordered` doesn't set up things unless you do `hoverTheme` `focusTheme` etc. I personally am not the biggest fan of this whole setup and at some point will make it a bit cleaner, I'd recommend just customizing things using your own styles/variants for the most part.

Also `theme="primary_Button"` you should never do, Button is always applied automatically, so theme="primary" is all.
