### ISSUE TITLE
[bug] No way to get Expo web working

### ISSUE THREAD

**Issue by xixixao** [tamagui/tamagui#747]
Following https://tamagui.dev/docs/guides/expo, changing `TAMAGUI_TARGET` in `babel.config.js` to `"web"` and trying to run web expo preview via `npx expo start` and `w` doesn't work.

First expo complains about missing webpack, which I install via `npx expo install @expo/webpack-config@^18.0.1`

Afterwards the expo build fails with (only last error shown here):

```
ERROR in ./node_modules/tamagui/dist/esm/index.mjs:54
Module not found: Can't resolve './views/TextArea'
Did you mean 'TextArea.mjs'?
BREAKING CHANGE: The request './views/TextArea' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
  52 | // export * from './views/Skeleton'
  53 | export * from './views/Spinner'
> 54 | export * from './views/TextArea'
  55 |
  56 | // since we overlap with StackProps and potentially others
  57 | // lets be explicit on what gets exported

web compiled with 82 errors and 23 warnings
```
(I am trying out tamagui as a replacement for Native Base which did not have trouble running under expo web preview.)

**Comment by xixixao** [comment]
After trying out the standard Next+Expo combo I can see great benefits in it. So I'd change the docs to more strongly navigate people to the standard starter.

**Comment by natew** [comment]
Added a note here 42c963a7ab3efd6d7e69f404069dea2363cdaa69

Thanks. I'll be looking at Expo Router support.... eventually...
