### ISSUE TITLE
[bug] Select cannot be controlled. Doesn't respect 'value' prop

### ISSUE THREAD

**Issue by stoickeyboard** [tamagui/tamagui#752]
**Describe the bug**
The `Select` component cannot be controlled. It does not respect the value that you pass to the `value` prop.

**To Reproduce**

Minimal example (note that I'm passing "apple" as the value but the select still works regardless. Shouldn't it stay on Apple no matter what you select or am I missing something?):

https://github.com/stoickeyboard/tamagui-issue/tree/master

clone the repo
`yarn`
`yarn web`

play with Select on localhost:3000

**System Info (please complete the following information):** 

  ```System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 274.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 3.3.1 - ~/Library/pnpm/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Brave Browser: 110.1.48.171
    Chrome: 109.0.5414.119
    Firefox Developer Edition: 101.0
    Safari: 16.3
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.20.13 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    eslint: ^8.21.0 => 8.32.0 
    prettier: ^2.7.1 => 2.8.3 
    turbo: ^1.4.2 => 1.7.0 
    typescript: ^4.7.4 => 4.9.4 ```

**Comment by natew** [comment]
Good bug report, I was using `useControllableState` with `most-recent-wins` strategy for some reason, but removing it makes more sense. 1.6.1 has the fix, going out now.

**Comment by stoickeyboard** [comment]
Working as intended now! Enjoy your weekend brotha!
