### ISSUE TITLE
X/YStack and hide element with media | question

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#76]
I am looking for the best option on how to hide elements for some media in the Stack.

The following solution will hide elements, but auto-added spaces stay visible. 

```js
const media = useMedia();

return (
  <YStack als="center" space={20}>
    <H1>Heading 1</H1>
    <H2 $gtLg={{ display: 'none' }} >Heading 2</H2>
    <H3>Heading 3</H3>
  </YStack>
);
```

The following solution is working fine, but it will remove items entirely from DOM, which I do not want to use because of SSR and SEO.

```js
const media = useMedia();

return (
  <YStack als="center" space={20}>
    <H1>Heading 1</H1>
    {!media.gtLg && <H2 >Heading 2</H2>}
    <H3>Heading 3</H3>
  </YStack>
);
```

Is there any third solution how to do that?

**Comment by natew** [comment]
Known issue, I’ll assign myself if I start on it.

I think it’s fairly involved because the compiler will flatten, I think the spacedChildren helper will have to access the current media query, and then check the className in those cases.

**Comment by alitnk** [comment]
You can wrap the hidden element inside `<Unspaced>` to avoid adding the space or just use `gap` instead of `spcae` now that it's supported in react-native.
