### ISSUE TITLE
[bug] Custom Size Tokens not working for size prop

### ISSUE THREAD

**Issue by stoickeyboard** [tamagui/tamagui#762]
**Describe the bug**
The size prop for `Switch`, `Button`, and maybe others, doesn't seem to respect custom tokens. 

For `Switch`, it takes the size that is passed to `true` but doesn't seem to take anything else.
For `Button`, it changes the fontSize but not the width, height, or padding. Like `Switch` it seems to respond to the size that you pass to the `true` property in the size config. Meaning if I set true to 60 `true: 60` both the switch and button grow in size regardless of what you're passing to the size prop.

**To Reproduce**

A minimal example of what I'm taking about can be found in this repo. Note that if you change the `true` property in `packages/ui/src/tamagui.config.ts` the sizing of Switch and Button change. Ignore the size token you pass to size:

https://github.com/stoickeyboard/tamagui-issue/tree/custom-size-prop

```
npm create tamagui@latest
```

Make your changes and then push and link it here. 🙏🙏🙏🙏🙏

**System Info (please complete the following information):** 

```
  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 984.38 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 3.3.1 - ~/Library/pnpm/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Brave Browser: 110.1.48.171
    Chrome: 109.0.5414.119
    Firefox Developer Edition: 101.0
    Safari: 16.3
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.20.13 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    eslint: ^8.21.0 => 8.32.0 
    prettier: ^2.7.1 => 2.8.3 
    turbo: ^1.4.2 => 1.7.0 
    typescript: ^4.7.4 => 4.9.4 
```

**Comment by wkoutre** [comment]
@stoickeyboard Is this, perhaps, similar / the same as [I've described in this post from last Friday](https://github.com/tamagui/tamagui/issues/559#issuecomment-1464812766)?

**Comment by stoickeyboard** [comment]
@wkoutre Yes, actually. I tried prefixing the size with $ and it works as you'd expect. I saw that issue but figured because it was closed, that wasn't the issue. This issue should be closed in favor of reopening that one

**Comment by wkoutre** [comment]
@stoickeyboard cool! i'll make a small PR tomorrow

**Comment by wkoutre** [comment]
[Here we are](https://github.com/tamagui/tamagui/pull/816)
