### ISSUE TITLE
[bug] Form onSubmit isn't called

### ISSUE THREAD

**Issue by rub1e** [tamagui/tamagui#771]
**Describe the bug**

Form `onSubmit` isn't called when `FormTrigger` element is pressed

**To Reproduce**

* Basic form as per [the docs](https://tamagui.dev/docs/components/form#anatomy)
* Tried with both `Form.Trigger` and `FormTrigger`

**Versions**
* Tamagui 1.7.2
* Expo 48

**Comment by lobor** [comment]
in anatomy, missing asChild on Form.Trigger for work with Button, if only test, thios should work as expected

**Comment by nandorojo** [comment]
Did you pass the `asChild` prop?

**Comment by lobor** [comment]
Any news ? @rub1e

**Comment by Martinnord** [comment]
I ran into this myself today. Passing `asChild` to `<Form.Trigger>` solves the issue

**Comment by natew** [comment]
Docs are improved, `asChild` is the right way!
