### ISSUE TITLE
[bug] No font size found $true undefined in size tokens ["$1"]

### ISSUE THREAD

**Issue by fruity4pie** [tamagui/tamagui#781]
**Describe the bug**
Trying to configure tamagui theme, getting this warning: 
No font size found $true undefined in size tokens ["$1"]

**To Reproduce**

do as the same as in expo section, add this config:

```
const bodyFont = createFont({
  family: 'andika400r',
  lineHeight: {
    1: 14,
  },
  size: {
    1: 14,
  },
  letterSpacing: {
    0: 0,
  },
  weight: {
    4: 400,
  },
});
```

Get the same warn.

**System Info (please complete the following information):** 

System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.95 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 3.4.1 - ~/.nvm/versions/node/v16.19.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    Watchman: 2023.02.13.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 109.0.1
    Safari: 16.3
  npmPackages:
    @babel/core: ^7.20.0 => 7.21.0
    @expo-google-fonts/andika: ^0.2.3 => 0.2.3
    @tamagui/animations-react-native: ^1.7.6 => 1.7.6
    @tamagui/babel-plugin: ^1.7.6 => 1.7.6
    @tamagui/config: ^1.7.6 => 1.7.6
    @tamagui/shorthands: ^1.7.6 => 1.7.6
    @tamagui/themes: ^1.7.6 => 1.7.6
    @tanstack/query-sync-storage-persister: ^4.24.10 => 4.26.1
    @tanstack/react-query: ^4.24.10 => 4.26.1
    @tanstack/react-query-persist-client: ^4.24.10 => 4.26.1
    @types/ramda: ^0.28.23 => 0.28.23
    @types/react: ~18.0.14 => 18.0.28
    babel-plugin-transform-inline-environment-variables: ^0.4.4 => 0.4.4
    eslint: ^8.36.0 => 8.36.0
    eslint-config-airbnb-typescript-prettier: ^5.0.0 => 5.0.0
    expo: ^48.0.6 => 48.0.6
    expo-constants: ^14.2.1 => 14.2.1
    expo-font: ~11.1.1 => 11.1.1
    expo-linking: ^4.0.1 => 4.0.1
    expo-router: ^1.2.2 => 1.2.2
    expo-status-bar: ^1.4.4 => 1.4.4
    prettier: ^2.8.4 => 2.8.4
    ramda: ^0.28.0 => 0.28.0
    react: 18.2.0 => 18.2.0
    react-devtools: ^4.27.2 => 4.27.2
    react-dom: ^18.2.0 => 18.2.0
    react-native: 0.71.3 => 0.71.3
    react-native-maps: ^1.4.0 => 1.4.0
    react-native-mmkv: ^2.6.2 => 2.7.0
    react-native-reanimated: ^3.0.2 => 3.0.2
    react-native-safe-area-context: ^4.5.0 => 4.5.0
    react-native-screens: ^3.20.0 => 3.20.0
    react-native-web: ^0.18.12 => 0.18.12
    tamagui: ^1.7.6 => 1.7.6
    typescript: ^4.9.4 => 4.9.5

---

- [x] yarn.lock or similar

**Comment by juiceo** [comment]
Hey, running into the same issue - what was the culprit for this?

**Comment by heondo** [comment]
@juiceo https://tamagui.dev/docs/core/configuration#font-tokens

> The keys of size, lineHeight, weight, and letterSpacing are meant to match.

**Comment by georgibakken** [comment]
Can you provide an example? 

Is the full set of keys on size all of [these](https://tamagui.dev/docs/intro/tokens)?

**Comment by JordanDDisch** [comment]
you have to set a default. $true is the default fontsize that get selected by the theme (i know, this is a bit annoying).

From the [docs](https://tamagui.dev/docs/core/configuration#font-tokens):

> Note, for tamagui (not core), it expects you to define a true token that maps to your default size, this way it knows what token to use by default. So you'd do something like this:

**Comment by TrejoCode** [comment]
Same thing:

``` tsx
import {shorthands} from '@tamagui/shorthands';
import {themes, tokens} from '@tamagui/themes';
import {createFont, createTamagui} from 'tamagui';

const appConfig = createTamagui({
  themes,
  tokens,
  shorthands,
  fonts: {
    body: createFont({
      family: 'Arial',
      size: {
        // You'll want to fill these values in so you can use them
        // for now, fontSize="$4" will be 14px.
        // You can define different keys, but `tamagui`
        // standardizes on 1-15.
        4: 16,
      },
      lineHeight: {
        4: 16,
      },
      weight: {
        4: '400',
      },
      letterSpacing: {
        4: 0,
      },
    }),
  },
});

export type AppConfig = typeof appConfig;

declare module '@tamagui/core' {
  interface TamaguiCustomConfig extends AppConfig {}
}

export default appConfig;

```

 No font size found $true undefined in size tokens ["$4"]

**Comment by fedorish** [comment]
> ```tsx
> import {shorthands} from '@tamagui/shorthands';
> import {themes, tokens} from '@tamagui/themes';
> import {createFont, createTamagui} from 'tamagui';
> 
> const appConfig = createTamagui({
>   themes,
>   tokens,
>   shorthands,
>   fonts: {
>     body: createFont({
>       family: 'Arial',
>       size: {
>         // You'll want to fill these values in so you can use them
>         // for now, fontSize="$4" will be 14px.
>         // You can define different keys, but `tamagui`
>         // standardizes on 1-15.
>         4: 16,
>       },
>       lineHeight: {
>         4: 16,
>       },
>       weight: {
>         4: '400',
>       },
>       letterSpacing: {
>         4: 0,
>       },
>     }),
>   },
> });
> 
> export type AppConfig = typeof appConfig;
> 
> declare module '@tamagui/core' {
>   interface TamaguiCustomConfig extends AppConfig {}
> }
> 
> export default appConfig;
> ```


This should solve it. 

```tsx
 size: {
        // You'll want to fill these values in so you can use them
        // for now, fontSize="$4" will be 14px.
        // You can define different keys, but `tamagui`
        // standardizes on 1-15.
        true: 16, //or whatever you want to default to. 
        4: 16,
      },
```
