### ISSUE TITLE
[bug] When a modal screen is presented, Dialog opens in the parent view behind the modal (iOS)

### ISSUE THREAD

**Issue by raphaelm-gioa** [tamagui/tamagui#785]

**Comment by lobor** [comment]
do you have screenshot or code ? I'm not sure I understand

**Comment by raphaelm-gioa** [comment]
Using expo-router, I present a screen in mode of `presentation: 'modal'`.
When I visit the route, the screen shows up as Modal. In this screen, if I render a Dialog - the Dialog doesn't appear in the Modal Screen but in the Parent Screen behind

**Comment by lobor** [comment]
do you have set inline mode ?

**Comment by raphaelm-gioa** [comment]
Dialog `modal` props is `true` by default (cf : https://tamagui.dev/docs/components/dialog/1.0.0#api) 
If I set `modal={false}` the Dialog does appear on the foreground screen; but then it's not fullscreen and this is more like a bug that an unexpected behaviour.

**Comment by lobor** [comment]
Sorry but with any code, screen or reproduction repo i can't help you
