### ISSUE TITLE
avatar never show image with SSR and disabled javascript

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#786]
When you try to show avatar with disabled javascript and working SSR you will always get empty avatar.

*How to reproduce*
Try to open https://tamagui.dev/docs/components/avatar/1.0.0 with disabled javascript.

*Versions*
Tamagui 1.7.6

**Comment by natew** [comment]
So looked into this, it's an issue with react-native-web itself, the image doesn't show until JS runs. 

Not a big fan of the rn Image component in general, it seems very heavy and obviously not SSR safe.

@nandorojo I'd use SolitoImage but want something really light tbh no deps on expo/next ideally. But of course native does require *something*.

cc @hirbod

**Comment by natew** [comment]
Also would be useful to open an issue on RNW for this.

**Comment by nandorojo** [comment]
i think the defaultSource prop might fix this with RNW

**Comment by natew** [comment]
Ah good catch

**Comment by hirbod** [comment]
We're using next/image and expo-image currently. Going to swap to expo-image for the web soon.

**Comment by nandorojo** [comment]
@hirbod fwiw this is what solito image does for you

**Comment by hirbod** [comment]
@nandorojo so solito image uses next/image for web and expo-image for native or expo-image for all platforms?

**Comment by nandorojo** [comment]
expo image on native, next image on web
