### ISSUE TITLE
[bug] gapColumn / gapRow are not correctly transformed to style properties

### ISSUE THREAD

**Issue by foyarash** [tamagui/tamagui#794]
**Describe the bug**

This is happening on a React Native app using expo.

The `gapColumn` and `gapRow` are not transformed to style properties. Applying for example `gapColumn={10}` will result to `gapColumn: 10` in the styles computed by the RN inspector.

Its expected that `gapColumn` is transformed into `columnGap` and `gapRow` is transformed into `rowGap`

This happens using latest tamagui version.

**Comment by natew** [comment]
Oh interesting, didn't realize these are flipped around...
