### ISSUE TITLE
variants and GetProps are not working together

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#80]
When you try to use the following typed source code, you will get a typescript error: *Property 'bold' does not exist on type 'TextProps.'*
I see the same error for boolean, string, and other variants.

```ts
import React, { memo, forwardRef, useMemo, Children, ComponentProps } from 'react';
import { SizableText, styled, type GetProps } from 'tamagui';

const StyledText = styled(SizableText, {
  variants: {
    bold: {
      true: {
        fontWeight: 'bold',
      },
    },
  }
});

export type TextProps = GetProps<typeof StyledText>;

function Text(props: TextProps) {
  const { children, bold, ...rest } = props;
```

OS: Mac
Browser: Safari
Version: latest beta 44

**Comment by natew** [comment]
This is working for me (and generally works on the site and a few other apps we use Tamagui on so fairly confident it should work), it's possible your types somehow got messed up in `tamagui.config.ts`?

<img width="641" alt="image" src="https://user-images.githubusercontent.com/12100/171545110-3f021585-8ef3-4e55-a4dd-70db3a01cc02.png">

**Comment by natew** [comment]
Feel free to open again if there's some other issue.
