### ISSUE TITLE
[bug] Input & TextArea border issue

### ISSUE THREAD

**Issue by ionutcirja** [tamagui/tamagui#801]
1. When I try to set a custom border width for Input and TextArea, on field focus, the field moves 1px to the left.
2. I cannot override border width on focus style.

Thank you

**Comment by seeden** [comment]
Probably connected to https://github.com/tamagui/tamagui/issues/725 as well

**Comment by natew** [comment]
This should be fixed, but also the negative margin trick is specific to our default styles. You can reset it with `unstyled` prop, or just override it manually.

**Comment by natew** [comment]
Should be fixed, lmk if still an issue.
