### ISSUE TITLE
[bug] non-sheet Select does not work on web with touch devices

### ISSUE THREAD

**Issue by matthewhausman** [tamagui/tamagui#804]
I didn't want to use a bottom sheet on web xs devices and found that the non-sheet select does not work on chrome, the web browser (in touch device simulation), or safari

**Comment by matthewhausman** [comment]
easiest way to reprod is on the tamagui site - if you switch from md device width to lower than sm the select doesn't respond properly  to any clicks

**Comment by alitnk** [comment]
Select has had a lot of updates since then. I'm guessing one of those has fixed this cause I can't reproduce on https://tamagui.dev/docs/components/select.
Closing the issue but feel free to re-open if you still can reproduce.
