### ISSUE TITLE
[bug] docs re index algolia

### ISSUE THREAD

**Issue by flexbox** [tamagui/tamagui#805]
https://tamagui.dev/docs/components/feather-icons is a 404 page
we should have https://tamagui.dev/docs/components/lucide-icons/1.0.0 instead

---

**Describe the bug**
<img width="696" alt="image" src="https://user-images.githubusercontent.com/360936/225911859-04c88989-a8a9-4eac-aa62-1eb9dc46336f.png">

**To Reproduce**
search "icons" from the documentation

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/360936/225912303-83f61697-a43f-4202-8144-5c4051a17379.png">

**Comment by natew** [comment]
Ok finally found in Algolia where I can fix this, it should be updating now. Thanks for the heads up.
