### ISSUE TITLE
media are mismatched with variants

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#81]
First of all here is my media configuration: (I am not using $gtLg because I was always writing just gt prefixes)
```js
  media: {
    // xs: { minWidth: 0 }, this is default behaviour - never used directly (mobile first)
    sm: { minWidth: 660 },
    md: { minWidth: 800 },
    lg: { minWidth: 1020 },
    xl: { minWidth: 1280 },
    '2xl': { minWidth: 1420 },
    '3xl': { minWidth: 1600 },
  },
```

In the following example, everything is working fine. Standard CSS properties are correctly resolved.
```tsx
<Text
  fontWeight="100"
  $md={{
    fontWeight: 'bold',
  }}
  $lg={{
    fontWeight: 'normal',
  }}
>
  Test
</Text>
```

Here you can see broken example:
I will create new Text component which is using variant bold instead of fontWeight

```tsx
import { SizableText, styled, type GetProps } from 'tamagui';

const Text = styled(SizableText, {
  variants: {
    bold: {
      true: {
        fontWeight: 'bold',
      },
    },
    defaultVariants: {
      bold: false,
    }
});
```

First broken example
```tsx
<Text
  $md={{
    bold: true,
  }}
  $lg={{
    bold: false,
  }}
>
  Test
</Text>
```

Text is bold only for media === 'lg'.

Second broken example

```tsx
<Text
  bold
  $md={{
    bold: false,
  }}
  $lg={{
    bold: true,
  }}
>
  Test
</Text>
```

Text is not bold for media < md and it is bold for media > md which is broken in the previous example.

OS: Mac
Browser: Safari
Version: latest beta 44

**Comment by natew** [comment]
I think this is working, though it took me a second to realize. Because you don't define `false` for variant `bold`:

```tsx
const Text = styled(SizableText, {
  variants: {
    bold: {
      true: {
        fontWeight: 'bold',
      },
      false: {
        fontWeight: 'normal'
      }
    },
    defaultVariants: {
      bold: false,
    }
});
```

That should make it work.

I've added a check there that warns in dev mode so this is clearer:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/12100/171544398-6af6ace5-629b-4688-945c-a85fc04ac22d.png">

**Comment by seeden** [comment]
Hi @natew. When I added false, as you suggested, it fixed style for $lg media but not for XS or default screens. Here is a more strange example:

```tsx
const Text = styled(SizableText, {
  variants: {
    bold: {
      true: {
        fontWeight: 'bold',
      },
      false: {
        fontWeight: 'normal',
      },
    },
    italic: {
      true: {
        fontStyle: 'italic',
      },
      false: {
        fontStyle: 'normal',
      },
    },
  },
  defaultVariants: {
   bold: false,
   italic: false,
  }
});

// render code
    <Text
      bold
      italic
      $md={{
        bold: false,
        italic: false,
      }}
      $lg={{
        bold: true,
        italic: true,
      }}
    >
Test
</Text>

```

Media $md and $lg are working fine. But default behavior for small screen will completely ignore bold. Italic is working fine. Whole problem is connected just to bold property.

**Comment by seeden** [comment]
There is also another question if I need to always define "false" value.
Consider following example where two variants are using same CSS property:

```tsx
const Text = styled(SizableText, {
  variants: {
    uppercase: {
      true: {
        textTransform: 'uppercase',
      },
      false: {
        textTransform: 'none',
      },
    },
    lowercase: {
      true: {
        textTransform: 'lowercase',
      },
      false: {
        textTransform: 'none',
      },
    },
  },
});
```

Next render of Text component will use textTransform === 'none' for media >= lg

```tsx
    <Text
      uppercase
      
      $md={{
        uppercase: false,
        lowercase: true,
      }}
      $lg={{
        uppercase: true,
        lowercase: false,
      }}
    >TeStBlABla</Text>
```

and following render of Text component will use textTransform === 'uppercase' for media >= lg

```tsx
    <Text
      uppercase
      
      $md={{
        uppercase: false,
        lowercase: true,
      }}
      $lg={{
        lowercase: false,
        uppercase: true,
      }}
    >TeStBlABla</Text>
```

Just order was changed.
FYI: order of properties is not consistent across browsers and therefore, users can see different results
