### ISSUE TITLE
[bug] Button (native) - Invalid props.style key cursor supplied to Text 

### ISSUE THREAD

**Issue by nderscore** [tamagui/tamagui#811]
After upgrading tamagui, I started seeing warnings about `cursor` style being passed to the tamagui Button's Text on native:

> Warning: Failed prop type: Invalid props.style key `cursor` supplied to `Text`.
> 
> ...
>
> `"cursor": "default"`
> 
>  at Text (http://.../index.tsx.bundle?platform=ios&dev=true&hot=false:73579:27)
>    in ButtonText
>    in RCTView (created by View)
>    in View (created by Button)
>    in Button
>    in Button (created by Themed(Anonymous))
>    in _Theme (created by Themed(Anonymous))

This seems to have been introduced somewhere between tamagui 1.7.9<->1.7.11

Still seen happening on 1.8.0

It can be reproduced with a bare copy of the `next-expo-solito` starter project.

**Comment by AlexanderHOtt** [comment]
I have a similar issue when using the `Select` component.

**Comment by jmurphy4** [comment]
Seeing this as well on 1.8.1.

If you are seeing the issue and need a temp fix, you can wrap the text with a <Text> component. Not perfect but 🤷

**Comment by nnennajohn** [comment]
Also happening to me. Will rollback for now. Anyone rolled back to a version that does not have this problem?

**Comment by natew** [comment]
Fixed in 1.8.2, so sorry about that everyone.
