### ISSUE TITLE
[bug] <Theme inverse> produces inconsistent results on web

### ISSUE THREAD

**Issue by nderscore** [tamagui/tamagui#821]
### Current Behavior

When using `<Theme inverse>` on the web and the user has `prefers-color-scheme: dark` selector active, not all components use the inverse theme CSS variables.

```tsx
<Theme inverse>
  <XStack background="$background" /> 
                   // ^ still uses original dark theme colors when dark color preference is active
                   //   but, it inverts correctly when light color preference is active
</Theme>
```

Not all components exhibit this behavior either - for example, the `Button` still inverts (see demo)

### Expected Behavior

Theme values set by `<Theme inverted>` should always have the highest CSS selector precedence.

### Tamagui Version

```markdown
1.8.4
```

### Reproduction

https://codesandbox.io/p/sandbox/wizardly-dirac-b6n18t?file=%2Fpackages%2Fapp%2Ffeatures%2Fhome%2Fscreen.tsx

**With `prefers-color-scheme: light`: (working!)**

![image](https://user-images.githubusercontent.com/2250252/226740828-00d12ff0-12af-4612-be0a-5eb812e326c4.png)

**With `prefers-color-scheme: dark`: (broken!)**

![image](https://user-images.githubusercontent.com/2250252/226740919-3f211fbf-6955-4465-a565-b9a118dde86b.png)

**Comment by alitnk** [comment]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/35243344/227950232-9981d3a3-d1dd-4c4e-a6a9-97080f0bc7c7.png">

Reproduction link giving me this... is it just me?

**Comment by nderscore** [comment]
> Reproduction link giving me this... is it just me?

Happening for me too. And I don't even see it in my codesandbox account anymore :thinking: 

The reproduction code looked like this, IIRC:

```tsx
    <YStack>
      <YStack bc="$background" space>
      <Button>Button</Button>
      <Text>Text</Text>
      </YStack>
      <Theme inverse>
        <YStack bc="$background" space>
          <Button>Button</Button>
          <Text>Text</Text>
        </YStack>
      </Theme>
    </YStack>
```

**Comment by alitnk** [comment]
Tested on 1.9.10; Couldn't reproduce it unfortunately (or fortunately). Tried on both tamagui sandbox (vite) and tamagui site (next.js). 

<img width="163" alt="image" src="https://user-images.githubusercontent.com/35243344/227958929-178a95a4-cfd5-4e2f-86f5-36e1e531e7e0.png">
<img width="163" alt="image" src="https://user-images.githubusercontent.com/35243344/227959029-cc47985a-ed04-4a40-b5d0-7c04cc33e0c6.png">

Can you confirm this is happening on the latest version?

**Comment by alitnk** [comment]
Was able to reproduce. some additional info on the issue:
- Does not happen when using Vite
- If using a dim, does not happen on Next.js (the reason why it worked on my previous attempt)

**Comment by natew** [comment]
Oh wups hit close too early but I think this is fixed, can you re-open if not?
