### ISSUE TITLE
Animation prop cancels other props

### ISSUE THREAD

**Issue by SofianeDjellouli** [tamagui/tamagui#832]
Hi,

I am in Next JS. 

I have a component like this:
```
      <YStack
        {...{
          borderRadius: 3,
          backgroundColor: 'white',
          hoverStyle: { backgroundColor: 'var(--light-grey)' },
          animateOnly: ['background-color'],
          tag: 'button',
          borderColor: 'black',
          borderWidth: 1,
          borderStyle: 'solid',
          animation: 'fast',
        }}
      >
```
It outputs this:
```
<div class=" is_Stack  _bc-0hover-rytrrm _display-flex _bc-d0t1q780h6 _btlr-3px _btrr-3px _bbrr-3px _bblr-3px _minHeight-0px _flexShrink-0 _ai-stretch _transition-d0t1n15dys _flexDirection-column _minWidth-0px _minHeight-0px _position-relative _boxSizing-border-box _flexBasis-auto _display-flex _flexShrink-0  is_YStack">
```
It keeps only border radius and background color props. The transition works. The button tag is ignored.

If I remove the animation props, then I get all the props.

I created animations like this
```
import { createAnimations } from '@tamagui/animations-css'

export const animations = createAnimations({
  fast: 'ease 0.3s',
})
```
I use the 1.9.0 version of all tamagui packages.

**Comment by natew** [comment]
I tested this  a few different ways and couldn't replicate, though the tag likely is hard to fix with RNW not allowing it...

**Comment by natew** [comment]
Can you add a repro and I'll re-open

**Comment by SofianeDjellouli** [comment]
Hi @natew,

Please find a repro here: https://github.com/SofianeDjellouli/animations-bug-repro. It is likely related to the config, as it was working with the original config of the template.

Thanks for the great library.
