### ISSUE TITLE
Dynamic animation delay

### ISSUE THREAD

**Issue by idrakimuhamad** [tamagui/tamagui#833]
I was just wondering if there's a way to have a dynamic delay on animation? As currently, the delay configuration sits inside the `createAnimations`. However, I do have cases where I want stagger some child animation to make it appearing in order.

For example, in [`react-native-animatable`](https://github.com/oblador/react-native-animatable#properties) one could pass the prop `delay` in the component to express the number of ms the animation should be delay. This way, I don't need to add delay into the animation configuration and let it be as dynamic as possible.

For example as such:

```jsx
<YStack
  animation="bouncy"
  enterStyle={{
    y: 25,
    opacity: 0,
  }}
  y={0}
  opacity={1}
  ai="center"
  width={40}
  height={40}
  bc="$red10"
  delay={1000} // 1ms
/>
```

Or if there's anyway I can do it through other mean, please do tell.

**Comment by natew** [comment]
You can pass options like `animation={['bouncy', { delay: 1000 }]}`, let me know if that works.

**Comment by idrakimuhamad** [comment]
This seems to work, however, it seems only work on opacity, not the transform value. 

```jsx
animation={[
  "bouncy",
  {
    opacity: {
      delay: 1000,
    },
    y: {
      delay: 1000,
    },
  },
]}
```

So the element does have a delay in appearing, however, the "fade in up" effect doesn't work, as the element appear to animate as "fade in" only.

If I remove the opacity config, the 'y' still animate instantly.

**Comment by natew** [comment]
Ah, this is because it's looking for `translateY` (and also I need to fix delay). Patch incoming for both.

**Comment by natew** [comment]
Please lmk if not working now.

**Comment by idrakimuhamad** [comment]
Can confirm using `translateY` its working as expected.

Also, after version 1.9.9, the key `y` are working now.

```jsx
animation={[
  "bouncy",
  {
    opacity: {
      delay: 1000,
    },
    y: {
      delay: 1000,
    },
  },
]}
```

Thanks for the awesome work.

**Comment by smontlouis** [comment]
I just did the same thing, it looks like it's not working anymore

**Comment by lorenzogonnelli** [comment]
Same thing here.. it's not working

**Comment by Talinx** [comment]
For me it is working on Android and iOS, on web however there is no delay.
