### ISSUE TITLE
[Issue] can't access tamagui.dev

### ISSUE THREAD

**Issue by justarya** [tamagui/tamagui#836]
### Current Behavior

In `tamagui.dev`, when I access using my browser (brave browser and safari). It shows an error

`Application error: a client-side exception has occurred (see the browser console for more information).
`

It shows in a blink the proper documentation and then it shows the error.
![Screenshot 2023-03-26 at 11 27 33](https://user-images.githubusercontent.com/26767753/227755308-1e7aa925-eef3-4045-84ea-49e7b7e7cc7d.png)
![Screenshot 2023-03-26 at 11 28 25](https://user-images.githubusercontent.com/26767753/227755332-6973cd42-819e-4396-aa8b-a5b436c9e54a.png)

### Expected Behavior

It should shows the proper website

### Tamagui Version

```markdown
-
```

### Reproduction

```markdown
- Mac OS 13.1
- Brave browser / Safari
- No extension installed
```

**Comment by idrakimuhamad** [comment]
Same. Showing below message.

```
Application error: a client-side exception has occurred (see the browser console for more information).
```

Console showing below message.

<img width="936" alt="Screenshot 2023-03-26 at 1 33 32 PM" src="https://user-images.githubusercontent.com/1400323/227757331-f9eefa6b-8cf4-4077-b701-8762cf737f58.png">

**Comment by natew** [comment]
eek fixed my bad :/
