### ISSUE TITLE
Command "yarn set version stable && yarn install" exited with 1

### ISSUE THREAD

**Issue by launchthatbrand** [tamagui/tamagui#838]
On a fresh clone of the app using `npm create tamagui`. I am deploying to vercel per the instructions and getting an error:

`Command "yarn set version stable && yarn install" exited with 1`

![image](https://user-images.githubusercontent.com/70350889/227792644-a83ac7ba-155d-4aca-bb16-7e30c06b55e0.png)

**Comment by launchthatbrand** [comment]
FIXED

I hade to run `yarn set version stable && yarn install` in my local repo, push it to github where it auto deployed to vercel fine.

**Comment by natew** [comment]
Made it so it sets a more specific version.
