### ISSUE TITLE
Unable to resolve "burnt" from "../../node_modules/@tamagui/toast/dist/cjs/createNativeToast.native.js"

### ISSUE THREAD

**Issue by raphaelm-gioa** [tamagui/tamagui#842]
### Current Behavior

Right after upgrade & build, I encounter this error 
`npx expo`
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-03-26 at 23 19 33](https://user-images.githubusercontent.com/125041507/227802415-4c63dd85-2999-42c8-918a-0c4e9fe6904b.png)

### Tamagui Version

```markdown
1.9.8
```

### Reproduction

```markdown
Upgrading to 1.9.8 and running the build
```

**Comment by raphaelm-gioa** [comment]
Should just read the docs
Although I didn't add `toast` to my package.json ! That's why I opened a ticket; but I'll add Burnt just for the sake of checking 1.9.8

**Comment by alitnk** [comment]
I can improve this error to say something like: "Package `burnt` not found. Make sure you have it installed."

**Comment by raphaelm-gioa** [comment]
Sure! Also I wonder how it has been added to tamagui dependencies; I don't have toast in my app

**Comment by launchthatbrand** [comment]
Hi so what is the fix for this? I am getting the same error and do not see anything about it in the docs.

**Comment by natew** [comment]
Did you add `burnt` to your app package.json? You need to do that. I'm moving the dep into peerDependencies for now so I think we at least get some warning.

**Comment by launchthatbrand** [comment]
That worked! `cd ./apps/expo && yarn add burnt`.

I didnt see this info anywhere

**Comment by natew** [comment]
It's added a couple days ago to the Toast docs page, but lmk if I can improve.

**Comment by KaivG** [comment]
I had the same issue when using the tamagui starter npm create tamagui. I guess burnt should be added to the apps/expo/package.json to solve this problem with the starter app
