### ISSUE TITLE
Select blocks the render of complete page

### ISSUE THREAD

**Issue by ayushsharma82** [tamagui/tamagui#844]
### Current Behavior

@natew , I upgraded tamagui from 1.7.8 -> 1.9.4 in my project and now `Select` component blocks the render of the whole page before it loads. Is this expected?

I'm using expo-router + tamagui. The screen is "not" navigated until Select component finishes loading/rendering. 

_**Suggestion:** I'll suggest upgrading the starter to use `expo-router` which provides fantastic file based navigation, just like Nextjs. It will also make the starter template a lot easier for people to understand._

### Expected Behavior

The Select component should load it's value faster or not block the render of whole page.

### Tamagui Version

```markdown
1.9.4
```

### Reproduction

```markdown
-
```

**Comment by natew** [comment]
this should be fixed
