### ISSUE TITLE
attribute text-decoration instead of css functionality

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#85]
When I use the underline variant HTML output is not correct and contains additional text-decoration attributes instead of valid CSS values. Text is not using text-decoration: 'underline' css property.

```tsx
const Text = styled(SizableText, {
  variants: {
   underline: {
      true: {
        textDecoration: 'underline',
      },
      false: {
        textDecoration: 'none',
      },
    },
  },
  defaultVariants: {
    underline: false,
  },
});
```

```tsx
<Text underline>TeStBlABla</Text>
```

HTML result:
As you can see there is attribute: text-decoration="underline" instead of default underline functionality.

```html
<span text-decoration="none" class="   _ww-fl0oek _boxs-1pkamc3 _fofam-1f039uq _disp-1ffesbf _ww-fl0oek _boxs-1pkamc3 _fofam-1f039uq _disp-1ffesbf">TeStBlABla</span>
```

 - OS: MAc
 - Browser Safari
 - Version 46

**Comment by natew** [comment]
This is fixed in this PR, should be merging here shortly https://github.com/tamagui/tamagui/pull/87
