### ISSUE TITLE
YStack space property creates space elements around hidden object

### ISSUE THREAD

**Issue by KaivG** [tamagui/tamagui#853]
### Current Behavior

I am using the starter repo and I am trying to conditionally render a Stack based on a media query:

````
<YStack space="$4" maw={600}>
        <H1 ta="center">Welcome to Tamagui.</H1>
        <Paragraph ta="center">
          Here's a basic starter to show navigating from one screen to another. This screen uses the
          same code on Next.js and React Native.
        </Paragraph>

        <Separator />
        <Stack backgroundColor="red" borderRadius={10}
          $gtLg={{ display: 'none' }}
        >
          <Text>Hello</Text>
        </Stack>
</YStack
````

The Stack is hidden, but there are two spacers created around the hidden Stack element, hence creating too much space.

### Expected Behavior

When a Stack has the property display: none there should only be the regular spacing applied between the two visible elements, not a double spacing.

### Tamagui Version

```markdown
1.9.10
```

### Reproduction

```markdown
See code above
```

**Comment by natew** [comment]
Dup of https://github.com/tamagui/tamagui/issues/76 / https://github.com/tamagui/tamagui/issues/178

This is a tough problem, but `gap` should solve it if you can use that. We likely deprecate `space` in a future version in favor of that.
