### ISSUE TITLE
console.warn when using `getToken`

### ISSUE THREAD

**Issue by idrakimuhamad** [tamagui/tamagui#860]
I'm seeing a yellow box warning in the app recently showing something like below.

![simulator_screenshot_D1810293-9B82-4181-8DBE-DD335B78A5DF](https://user-images.githubusercontent.com/1400323/228415860-3304f011-8ca5-4f35-8c69-aad7fc5f25ba.png)

It doesn't indicate anything wrong with it though. So I looked into the code and notice there's this warn inside the switch case.

https://github.com/tamagui/tamagui/blob/5f7fa105d7817f368e65435c47c010c2f46cfd07/packages/web/src/helpers/createPropMapper.ts#L457

I wonder if this really do indicate there's an issue with my configuration, perhaps.

**Comment by alitnk** [comment]
No issue with your config. This will be fixed when #858 is merged.
It's just a debugging log that ended up in the final bundle.

**Comment by alitnk** [comment]
Fixed in [1.9.13](https://github.com/tamagui/tamagui/releases/tag/v1.9.13)
