### ISSUE TITLE
[bug] No parent manager given

### ISSUE THREAD

**Issue by Stroi** [tamagui/tamagui#863]
### Current Behavior

I used tamagui starter, then installed and implemented expo-router, put `TamaguiProvider` to `expo/app/_layout.tsx` (Thats where you should put root providers) but I'm getting error `No parent manager given`. It works when I put the provider into `expo/app/index.tsx`. Maybe there is some additional setup required, any ideas ?

### Expected Behavior

TamaguiProvider should work when put in `expo/app/_layout.tsx`

### Tamagui Version

```markdown
1.9.16
```

### Reproduction

```markdown
Here is the sample repo: https://github.com/Stroi/tamagui-expo-router
Just clone and run `yarn native`
```

### System Info

```markdown
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 201.48 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: 3.5.0 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Safari: 16.3
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.20.13 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    eslint: ^8.21.0 => 8.32.0 
    prettier: ^2.7.1 => 2.8.3 
    turbo: ^1.8.3 => 1.8.3 
    typescript: ^4.7.4 => 4.9.4
```

**Comment by natew** [comment]
Duplicate deps almost always, it means there's two Tamagui instances in deps and one is being used to provide, another being used to find it.

**Comment by natew** [comment]
Send repro please
