### ISSUE TITLE
[bug] Animation for controlled Sheets and conditionally rendered Sheets are very different

### ISSUE THREAD

**Issue by deiongrahamlong** [tamagui/tamagui#877]
### Current Behavior

If you render a Sheet by relying on the `open` prop and using the `bouncy` animation, the sheet slides up smoothing for the bottom but if you conditionally render the sheet for example, ``` {showSheet && <Sheet defaultOpen...>{...}</Sheet>}``` the sheet bounces up from the bottom with a slight hesitation. Not sure what's to be expected. Using the open prop is smoother but conditionally rendering bounces.

### Expected Behavior

I'd expect both animations to be the same and not as much of a hesitation when conditionally rendering.

### Tamagui Version

```markdown
^1.9.22
```

### Reproduction

Heres a CodeSandbox https://codesandbox.io/p/sandbox/wc2r8l?file=%2FREADME.md

**Comment by natew** [comment]
So conditionally rendering is not recommended for sure, but still I'd say it'd be good for us to do something like

`useEffect(() => requestIdleCallback(() => setOpen(props.open))), [props.open])`

We may also want to have some way to easily detect "fully open" so you can more easily show a skeleton if that's desirable (more for web use cases).

And then I'd recommend for apps to also avoid rendering too much on initial load if you are conditionally rendering.

Again, I'd say ideal is not conditional rendering but we could put a little requestIdle logic.

**Comment by deiongrahamlong** [comment]
Gotcha. I refactored my code to wrap the sheet so it'll only render `children` when `open` is true which I guess is in the same ballpark as what you're suggesting. It's looking a lot better now. I'm firing queries to build a list with images inside of a full-page sheet and want to hold off the building and querying until necessary. Do you want me to close this or keep it open as a reminder for the requestIdle logic?

**Comment by natew** [comment]
Yep, you could use suspense startTransition() to show the content smoothly.
