### ISSUE TITLE
Algolia Search menu items hover change the black color to the white which hides the list item

### ISSUE THREAD

**Issue by Sabin-Subedi** [tamagui/tamagui#879]
### Current Behavior

https://user-images.githubusercontent.com/69413078/229292182-a3acc091-b8a3-4428-9a13-0f590736d578.mov

### Tamagui Version

```markdown
current doc
```

### Reproduction

```markdown
current doc
```

**Comment by TheEhsanSarshar** [comment]
@Sabin-Subedi thanks for the fix

there is still an issue when it's dark mode.

<img width="572" alt="image" src="https://user-images.githubusercontent.com/46188784/230343386-2550561e-fc98-4f55-b87b-78b0c2fec7a1.png">

maybe using `var(--color)`
