### ISSUE TITLE
@tamagui/build doesn't install devDependencies 

### ISSUE THREAD

**Issue by wlcharlie** [tamagui/tamagui#884]
### Current Behavior

@tamagui/build doesn't install devDependencies.

I found out when I using monorepo and pnpm, and tried to reproduce with new empty project.

<img width="419" alt="image" src="https://user-images.githubusercontent.com/77925413/229329837-20fd9bcf-f4af-41b3-aa1d-618e0d7d4644.png">

### Expected Behavior

It should be install other stuff I supposed?

### Tamagui Version

```markdown
1.9.22
```

### Reproduction

```markdown
Run `watch` in CodeSandbox project provided by this template.

```

[LINK](https://codesandbox.io/p/sandbox/github/tamagui/tamagui/tree/master/starters/next-expo-solito?selection=%5B%7B%22endColumn%22%3A28%2C%22endLineNumber%22%3A8%2C%22startColumn%22%3A28%2C%22startLineNumber%22%3A8%7D%5D&file=%2Fpackage.json)

**Comment by natew** [comment]
Is this a codesandbox thing? It works for me locally with yarn.

**Comment by natew** [comment]
Weird, in npm docs:

https://docs.npmjs.com/cli/v8/commands/npm-install

<img width="668" alt="CleanShot 2023-04-03 at 19 49 40@2x" src="https://user-images.githubusercontent.com/12100/229699338-bf0f6564-b81e-4bc1-81f5-db9781ce0e4f.png">

**Comment by natew** [comment]
Only thing I can think of is you have NODE_ENV set in your shell **and** somehow codesanbox does too but that can't be true...

**Comment by lostpebble** [comment]
I think technically "devDependencies" are dependencies which are not needed by the library when it is in operation. And technically- these modules which `@tamagui/build` uses are actually regular "dependencies" since they are needed in its operation. Yarn may be excluding them in the installation because it seems them as internal to the module's build process and not useful in our project.

**Comment by natew** [comment]
Put it back into dependencies in `1.11.1` I think this makes sense because so long as you put `@tamagui/build` into devDependencies it wont install it on your production build, but dev deps dont install transitively so its confusing otherwise.

**Comment by wlcharlie** [comment]
It's truly a bit weird that npm and other acting weird... 😯

Anyway, thanks for solving the issue!
