### ISSUE TITLE
[bug] Unable to resolve module burnt (NATIVE)

### ISSUE THREAD

**Issue by nderscore** [tamagui/tamagui#892]
### Current Behavior

After upgrading to the latest tamagui, I started seeing this error on native platforms:

```
Unable to resolve "burnt" from "../../node_modules/@tamagui/toast/dist/cjs/createNativeToast.native.js"
```

The error comes from here: https://github.com/tamagui/tamagui/blob/432a5f79dc6a5f74277a8283396d23f7dc6c6b77/packages/toast/src/createNativeToast.native.tsx#L7-L8

### Expected Behavior

Dependencies which are used by the library should be declared as `dependencies` or `peerDependencies` in `package.json`.

### Tamagui Version

```markdown
v1.9.18 - v1.10.0
```

### Reproduction

Start a new project with `tamagui` and without adding `burnt` as a dependency of the project.

The errors occurs **regardless** of whether the `Toast` component is used - my project isn't using it.

If you import the `tamagui` package at all, the error will always happen as a side-effect.

**Comment by nderscore** [comment]
As an aside, I think this comment in the code isn't true? 

> import inline to allow lazy usage of native dependecy

Based on the errors I'm encountering, the library is not being imported lazily.

**Comment by LunatiqueCoder** [comment]
Hey @nderscore. I also opened an issue on this matter: https://github.com/tamagui/tamagui/issues/828 🙈

**Comment by nderscore** [comment]
I missed it! 😅  This is indeed a duplicate of that issue.

Closing in favor of #828
