### ISSUE TITLE
Elevation not working on Android

### ISSUE THREAD

**Issue by idrakimuhamad** [tamagui/tamagui#897]
The `elevation` prop doesn't seem to be working on Android. It render appropriate shadow on iOS.

```jsx
<TCard bg="$bg.mainBg" elevation="$4" p="$2" mb="$5">
  <XStack jc="space-between">
    <TransferShortCut />
  </XStack>
</TCard>
```

Furthermore, manually setting elevation in `style` also doesn't work. I tried it on the `Card` and `Stack` component, so I assume the rest are the same.

Tamagui v1.9.15

**Comment by idrakimuhamad** [comment]
I've upgraded to latest version `1.11.1`, the elevation still doesn't affect Android. However, manually specifying elevation in `style` works now.

**Comment by TheEhsanSarshar** [comment]
old android SDKs ( < 28 ) don't support `shadowRaidus` and `shadowHeight` which `tamagui` internally converts `elevation="$3"` to.
we need to provide elevation as well alongside those properties.
I'll create a PR to fix this.
thanks for reporting @idrakimuhamad

**Comment by idrakimuhamad** [comment]
> old android SDKs ( < 28 ) don't support `shadowRaidus` and `shadowHeight` which `tamagui` internally converts `elevation="$3"` to.
> 
> we need to provide elevation as well alongside those properties.
> 
> I'll create a PR to fix this.
> 
> thanks for reporting @idrakimuhamad  

Thanks. I do not know that Android have such API support for shadow height and radius, as it is not documented in RN doc, apart from shadow color.

**Comment by TheEhsanSarshar** [comment]
@idrakimuhamad yeah you're right it's only shadowColor.
we need elevation anyway

**Comment by top-kat** [comment]
On my side, shadows displays but are "cuts" on both sides

<img width="311" alt="image" src="https://github.com/tamagui/tamagui/assets/17770809/4f2e352d-66a3-4ba6-98ac-b6053fcdb4b3">
