### ISSUE TITLE
token mismatch | bug

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#91]
I will get the wrong size/space when creating two different size/space tokens with similar names. 

```js
{
  '3.5': 14, 
  '3/5': '60%',
}
```

When I try to use token *3.5*, it will use value *60%* instead of *14*.

```tsx
<Space py="$3.5">
```

There is probably a problem with regex, which is ignoring some characters or something like this.

 - OS: mac
 - Browser safari
 - Version beta.54

**Comment by natew** [comment]
Fixed in https://github.com/tamagui/tamagui/pull/115/commits/2cd10acaf626a3d716e6d02565e28b41dc4223dd
