### ISSUE TITLE
The focusStyle is not being applied to Input

### ISSUE THREAD

**Issue by tjapa** [tamagui/tamagui#911]
### Current Behavior

The focusStyle is not being applied to Input:

```tsx
import { styled, Input } from 'tamagui'

export const MyInput = styled(Input, {
  borderColor: 'red',
  borderWidth: '$2',
  focusStyle: {
    borderColor: 'blue',
    borderWidth: '$2',
  },
})
```

### Expected Behavior

Change the border color to blue.

### Tamagui Version

```markdown
tamagui: "^1.11.2"
```

### Reproduction

```markdown
https://codesandbox.io/p/sandbox/late-grass-7o0pt9?file=%2Fpackages%2Fui%2Fsrc%2FMyInput.tsx
```

**Comment by tjapa** [comment]
@natew still doesn't work. I update the tamagui in the codesandbox and the problem persist.

**Comment by natew** [comment]
Added a test and verified this works here 5346242648 we've made a variety of improvements since so probably was caught there. Lmk if not.

**Comment by tjapa** [comment]
It worked great! Thank you!

**Comment by AstaninIvan** [comment]
@natew, still not working for native (android)
