### ISSUE TITLE
Tamagui Upgrade Issues

### ISSUE THREAD

**Issue by xwiz** [tamagui/tamagui#922]
Trying to use tamagui 1.12.2 and it seems I am forced to @tamagui/toast which have many open issues. Former Inputs start showing the error in lint.

1. Can @tamagui toast be made optional until it's stable.
2. Using an input as follows now throws lint errors in react native typescript:

```
       <Input br="$5 placeholder"test" />
...

```
Error message: Type 'string' is not assignable to type 'Partial<TextInputProps & Omit<TextProps, keyof TextInputProps> & Omit<{}, "size" | "unstyled"> & { readonly unstyled?: boolean; readonly size?: SizeTokens; }>'

**Comment by natew** [comment]
We've removed it from `tamagui` for now.
