### ISSUE TITLE
you can not override fontWeight in variant | bug

### ISSUE THREAD

**Issue by seeden** [tamagui/tamagui#93]
You are not able to override fontWeight in your styled() component when you use createInterFont

```js
export default createInterFont({
  family: 'Roboto',
  weight: {
    6: 'normal',
  },
});
```

```tsx
import { SizableText } from 'tamagui';

export const ExtendedSizableText = styled(SizableText, {
  name: 'ExtendedSizableText',
  variants: {
    bold: {
      true: {
        fontWeight: 'bold',
      },
      false: {
        fontWeight: 'normal',
      },
    },
});
```

When you try to use prop bold, it will be "ignored." Not ignored but overridden by element style object, which has higher priority.

```tsx
return (
   <ExtendedSizableText bold />
);
```

I used "temp hack" with an undefined value, but it is not working from version 56 because of typescript.

```js
export default createInterFont({
  family: 'Roboto',
  weight: {
    6: undefined,
  },
});
```

I also tried to use !important but there is no support for it :) 

```ts
export const ExtendedSizableText = styled(SizableText, {
  name: 'ExtendedSizableText',
  variants: {
    bold: {
      true: {
        fontWeight: 'bold !important',
      },
      false: {
        fontWeight: 'normal',
      },
    },
});
```

**Environment (please complete the following information):**
 - OS: Mac
 - Browser safari
 - Versions: all (56)

**Comment by natew** [comment]
Tested this on the upcoming release and not seeing the bug compiler/not-compiled, likely fixed with the fix to styled(Input).
