### ISSUE TITLE
Feature Request: Toast variants (non-native)

### ISSUE THREAD

**Issue by megacherry** [tamagui/tamagui#931]
### Current Behavior

Is it possible to add variants to the non-native toast, so that I can display success, info or error toasts, for example?

### Tamagui Version

```markdown
1.14.0
```

### Reproduction

```markdown
.
```

**Comment by alitnk** [comment]
Tamagui's toast uses [`burnt`](https://github.com/nandorojo/burnt) under the hood for native toasts. You can pass `preset` to the options but I believe that will only change the variant on iOS and show an `AndroidToast` on Android, which only has one style (correct me if I'm worng).

What you can do is, use presets ('done', 'error'), which will just work on iOS and then handle Android and Web with custom toasts. You can also retrieve the preset value when showing the custom toast and customize it depending on the preset.

I can add a section in the docs covering this with some code examples if you're interested!

**Comment by megacherry** [comment]
@alitnk: Thanks for your fast(!) answer.

I don't use the native toasts. I have created a component for myself that I have customized.

I was thinking more like this:

```
show('Error!', {
    message: 'Something went wrong.'
    preset: 'error'
})
```

Is this currently possible?

And about documentation: Yes, documentation that prevents such questions is always good. :)

**Comment by alitnk** [comment]
`preset` at the moment is nested under `burntOptions`, you can do:
```ts
show('Error!', {
    message: 'Something went wrong.'
    burntOptions: {
        preset: "error",
    },
})
```
I'm thinking maybe we could bring this one level up so it's no longer nested under `burntOptions`... we might end up doing that.

There's also `additionalInfo` if you only use custom toasts, where you can pass any custom data you want:
```ts
show('Error!', {
    message: 'Something went wrong.'
    additionalInfo: {
        variant: "error", // or any key you want
        isUrgent: true,
    },
})
```

**Comment by megacherry** [comment]
Thanks, that's exactly what i'm looking for. I could not find it in the documentation.

**Comment by alitnk** [comment]
#974 will improve DX when using custom data.
