### ISSUE TITLE
tamagui-build typecheck fail in monorepo with path variables

### ISSUE THREAD

**Issue by Silthus** [tamagui/tamagui#933]
tamagui-build currently overrides the `baseUrl` in the `tsc` command causing it to fail compiling where the baseUrl is something else than `.`

https://github.com/tamagui/tamagui/blob/3740e8e7b0f1f4a8a14512fb3a1902bd0e8567b0/packages/build/tamagui-build.js#L133

Why is the baseUrl explicitly set there? Shouldn't it be infered from the tsconfig?

**Comment by natew** [comment]
@Silthus can you send a PR fixing this? we'd need to read tsconfig which isn't pure JSON unfortunately.

**Comment by natew** [comment]
Fixed in 1.15.30 lmk if that works (going out now)
