### ISSUE TITLE
Modal Sheet on Mobile - Aligning items to bottom

### ISSUE THREAD

**Issue by kzlar** [tamagui/tamagui#940]
Opening this issue to follow up on https://discord.com/channels/909986013848412191/974145843919716412/1095928073653858314

Basically it seems like Modal Sheet on mobile is height is actually bigger than the displayed sheet, this means that if one tries to align items within the sheet to the bottom, those items would often render outside of the screen.

As an example, open https://tamagui.dev/docs/components/sheet/1.9.18 on iOS, make sure the type is modal and click Open. Then if you manually add "justify-content: flex-end" to the sheet node, you'll see the bottom button and half of the input is rendered outside of screen (at least on iPhone 14 Pro Max, I assume different device heights affect what you'll see)

On the surface of it, it seems like the sheet is set to `height: 100%` (i.e. the full screen height) but is then translated down, but I'm not sure if that's actually the issue.

**Comment by raphaelm-gioa** [comment]
Hey kzlar 😊  Thanks for the PR
I still wonder how this fix fixed this issue
I am still encoutering issues upon updating, I struggle to make a simple modal={true} view and justify-content space-between
I upgraded to last version tho
