### ISSUE TITLE
Input component no longer gets a border in focus mode

### ISSUE THREAD

**Issue by sallar** [tamagui/tamagui#942]
### Current Behavior

After this update:

https://github.com/tamagui/tamagui/commit/da43c9dfceac3b808b91806a85d583e58dbad44a

`Input` component no longer gets a thicker border in React Native since the `outlineColor` and `outlineWidth` properties do not exist on react native. 

<img width="391" alt="image" src="https://user-images.githubusercontent.com/768052/231695295-c9e497a1-7fd5-440e-a04c-e2b8935e357c.png">

Throws this error:

```
Warning: Failed prop type: Invalid props.style key `outlineColor` supplied to `ForwardRef(TextInput)`.
```

### Expected Behavior

Input should get a thicker border in focus mode on React Native

### Tamagui Version

```markdown
1.14.4
```

### Reproduction

```markdown
Use `<Input />` component and tap to focus.
```

**Comment by alitnk** [comment]
The fix should be in the next patch. Unfortunately I couldn't reproduce the warn (might be an issue with my setup) - so if the fix didn't work, feel free to re-open this issue.
