### ISSUE TITLE
Missing RootTag warning when using Popover 'modal' property.

### ISSUE THREAD

**Issue by KwehDev** [tamagui/tamagui#944]
### Current Behavior

When using a Popover component with the 'modal' property applied, on React Native (iOS) it will trigger a warning;

> Missing rootTag, this is a bug - you may need a different React Native version, or to avoid using "modal" on native.

### Expected Behavior

I'd expect the Popover component to behave as demonstrated when using the modal property. 

### Tamagui Version

```markdown
1.9.17
```

### Reproduction

```markdown
Use Popover with 'modal' on Tamagui 1.9.17, React Native 0.71.3.
```

**Comment by volgar1x** [comment]
Same problem on `v1.48.7`
