### ISSUE TITLE
patchReactNativeWeb doesn't work on Windows

### ISSUE THREAD

**Issue by sohcah** [tamagui/tamagui#96]
**Describe the bug**
patchReactNativeWeb doesn't work correctly on Windows.

This seems to be due to patchReactNativeWeb not correctly handling `\` as a file path separator. It looks like this should mostly be fixable just by replacing `\/` in the regex with `[\\/]` here (although I haven't tested that so might be other code which doesn't handle windows file separators either) https://github.com/tamagui/tamagui/blob/master/packages/static/src/patchReactNativeWeb.ts#L12

**To Reproduce**
Try to run the next-expo-solito starter on Windows.

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Version: 1.0.1-beta.57

**Comment by natew** [comment]
Made that change in beta 59, feel free to open another if it breaks in some other way.
