### ISSUE TITLE
Button style breaks with animation when upgrading from 1.14.3 to 1.15.5

### ISSUE THREAD

**Issue by JLuisRojas** [tamagui/tamagui#962]
### Current Behavior

This morning I updated the tamagui version to 1.15.5 and the button styles breaks when I apply animation. If i remove the animation property the style works correctly. 

With version 1.14.3 it works fine.

<img width="493" alt="Screenshot 2023-04-15 at 13 31 44" src="https://user-images.githubusercontent.com/34785814/232249851-f34a2ec6-7802-4772-bba9-686dd677b954.png">

I also tested it with Expo and its not working. I am using the @tamagui/animations-react-native driver

### Expected Behavior

This is how it looks if I remove the animation

<img width="492" alt="Screenshot 2023-04-15 at 13 31 37" src="https://user-images.githubusercontent.com/34785814/232249857-068d50ca-35bf-4baa-8ebf-9131b2eb7372.png">

### Tamagui Version

```markdown
1.15.5
```

### Reproduction

```markdown
Modify Tamagui's starter home/screen.tsx line 39 Button "Link to User" and add an animation
```

### System Info

```markdown
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 94.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/Library/Caches/fnm_multishells/72510_1681587351177/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/72510_1681587351177/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Safari: 16.1
  npmPackages:
    @ianvs/prettier-plugin-sort-imports: ^3.7.2 => 3.7.2
    @manypkg/cli: ^0.20.0 => 0.20.0
    @tamal/eslint-config: ^0.1.0 => 0.1.0
    @types/prettier: ^2.7.2 => 2.7.2
    eslint: ^8.38.0 => 8.38.0
    prettier: ^2.8.7 => 2.8.7
    turbo: ^1.8.8 => 1.8.8
    typescript: ^5.0.4 => 5.0.4
```

**Comment by JLuisRojas** [comment]
This is how I reproduced the error using the starter project

![Screenshot 2023-04-15 at 13 39 32](https://user-images.githubusercontent.com/34785814/232250129-0dbad269-8224-413d-9ebd-822b9564945e.png)

**Comment by natew** [comment]
On the latest version I don't see this, can you verify?

**Comment by JLuisRojas** [comment]
@natew yes I updated to 1.15.11 and its working fine. Thanks!
