### ISSUE TITLE
NextJS animation flash

### ISSUE THREAD

**Issue by JLuisRojas** [tamagui/tamagui#967]
### Current Behavior

When I add an animation to a Tamagui component there is white theme flash, this is especially noticeable in dark mode

https://user-images.githubusercontent.com/34785814/232326015-eb974480-1bd9-4fd0-8884-c3dec7d612da.mov

### Tamagui Version

```markdown
1.15.11
```

### Reproduction

```markdown
I made the following repo with the next-expo-solito starter:

https://github.com/JLuisRojas/tamagui-tests
```

### System Info

```markdown
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 112.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/Library/Caches/fnm_multishells/7109_1681662297597/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/7109_1681662297597/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Safari: 16.1
```

**Comment by natew** [comment]
Due to SSR switching to dark mode but assuming light mode server side.

We can fix this in a really weird way: basically we should render as non-animated before hydration, then switch it over to animated. It's a bit of a tricky problem to solve but mostly just in setting up tests and testing various use cases, shouldn't be technically too hard.

**Comment by JLuisRojas** [comment]
If you need help testing it, I am happy to help.

**Comment by natew** [comment]
should be fixed in latest release let me know

**Comment by JLuisRojas** [comment]
If I hardcode `dark` as the default theme in the TamaguiProvider It works fine.

```tsx
function ThemeProvider({ children }: { children: React.ReactNode }) {
  const [theme, setTheme] = useRootTheme()

  console.log('Theme', theme)
  console.log('isServerSide', isServerSide)

  return (
    <NextThemeProvider
      onChangeTheme={(next) => {
        setTheme(next as any)
      }}
    >
      <Provider disableRootThemeClass defaultTheme={'dark'}>
        {children}
      </Provider>
    </NextThemeProvider>
  )
}

```

Also I realize that the hook `useRootTheme` is returning `light` the first time on client side. I guess thats the reason why the flash happens.

![Screenshot 2023-04-28 at 8 11 17](https://user-images.githubusercontent.com/34785814/235171229-7173a287-19d6-455a-ae8e-cbbe8b558891.png)

**Comment by natew** [comment]
This is fixed now, lmk if not
