### ISSUE TITLE
Web Only Files Not Taking Precedence NextJs

### ISSUE THREAD

**Issue by cmaycumber** [tamagui/tamagui#97]
**Describe the bug**
Using files with the `.web.tsx` extension does not take precedence on NextJs over normal files.

**To Reproduce**
Include steps to reproduce.

* Clone starter repo
* Add a unique style to .web.tsx file in `packages/app/provider/navigation/index.web.tsx` e.i
```jsx
import { Text, XStack } from 'tamagui'

const Header = () => {
  return <XStack height="$2" backgroundColor={'$blue10'}></XStack>
}

export const NavigationProvider = ({ children }: { children: React.ReactElement }) => (
  <>
    <Header />
    {children}
  </>
)
```
* NextJs app does not update
* Change the regular `packages/app/provider/navigation/index.tsx` file
* NextJs updates as expected

**Environment (please complete the following information):**
 - OS: `MacOS - NextJs`
 - Browser `Brave`
 - Version `1.0.1-beta.57`

**Comment by natew** [comment]
Good point! We should add this to the next-plugin. Added to my backlog, anyone can grab this though.

**Comment by natew** [comment]
Added more extensions, re-open if still existing:

https://github.com/tamagui/tamagui/blob/e2fd7e5ce5c72203243de98880e86dd89bae0217/packages/next-plugin/src/withTamagui.ts#L150
