### ISSUE TITLE
Modal dialog trigger does not work on touch events until portal is unmounted

### ISSUE THREAD

**Issue by Gabrola** [tamagui/tamagui#985]
### Current Behavior

When a modal dialog is closed, there is a period of about 2-3 seconds (the time it takes to completely unmount the portal) where the the dialog trigger does not work and does not re-open the modal if it is pressed on a touchable device. It works for mouse clicks but not touch events.

This only applies to modal dialogs and not sheets.

### Tamagui Version

```markdown
1.15.17
```

### Reproduction

https://tamagui.dev/docs/components/dialog

https://user-images.githubusercontent.com/1728215/233246308-c6b12fcf-677e-4c5e-97f2-04fa20955fbd.mp4

**Comment by Gabrola** [comment]
This has gotten worse now. Every time the trigger is pressed, the "timeout" time for the portal to be unmounted is reset, so if you keep clicking the dialog never opens. You have to wait a couple of seconds before pressing for it open.

**Comment by deggertsen** [comment]
I know this isn't the ideal answer, but we've started just switching everything over to use state for open/close instead of the triggers.

**Comment by reck753** [comment]
I am experiencing something very similar which I described in another issue [here](https://github.com/tamagui/tamagui/issues/1066#issuecomment-1542910195). In my use case, I have "nested" dialogs and pressing somewhere after closing the second one, would close the first one.

I am also using `open/close` state for all of those dialogs, but it doesn't improve much.

It got a bit better with v1.27.1, but still a bit buggy.

**Comment by TheEhsanSarshar** [comment]
I wasn't able to reproduce it anymore, seems already resolved.
if you still have the issue let me know to re-open the ticket
