### ISSUE TITLE
Expo install guide

### ISSUE THREAD

**Issue by danharten-sovtech** [tamagui/tamagui#989]
### Current Behavior

Guide instructs with npm, creating a package-lock.json, but the next step asks you to use Yarn, resulting in a new yarn.lock 

### Expected Behavior

Instructions to use one or the other

### Tamagui Version

```markdown
https://tamagui.dev/docs/guides/expo
```

### Reproduction

```markdown
Follow guide on https://tamagui.dev/docs/guides/expo
```

**Comment by natew** [comment]
Not true, `npm create tamagui` uses yarn to install.
